# Atrial Fibrillation

Common arrhythmia with completely discordant atrial conduction, leading to:

* Adverse haemodynamics
	* Loss of effective atrial contraction\
	↓ Ventricular preload, significance depends on:
		* Ventricular function\
			* Systolic function
			* Diastolic function\
		* Ventricular rate
	* Variable ventricular rates
	* Rate-related **cardiomyopathy**
* Systemic embolism\
Left atrial stasis leads to clot formation and subsequent embolic events.

:::column-margin

Common terms include:

* Paroxysmal AF\
Terminates within 7 days (with or without treatment) of onset
* Persistent AF\
Lasts >7 days.
* Longstanding AF\
Lasts >1 year.
* Permanent AF\
When attempts at rhythm control have stopped.
:::

AF requires both:

* Substrate\
Underlying heart disease:
	* Atrial enlargement
		* Valvular disease
	* Heart failure
	* Pericarditis
	* Hypertrophy
	* Myocardial injury
		* ACS\
		10-15%.
		* Cardiac surgery
* Precipitant
	* Ischaemia
	* Sympathetic stimulation
		* Stress
		* Surgical
		* Critical illness
	* Endocrine
		* THyrotoxicosis
	* Toxins
		* Alcohol

## Epidemiology and Risk Factors

Common:

* 5% of >70s

Risk factors:

* Age
* Obesity
* OSA
* Cardiac disease
	* Atrial dilation
		* MR
		* MS
	* LV dysfunction
	* CABG\
	25-50%.
	* Cardiac failure\
	40%.

## Pathophysiology

### Aetiology

## Clinical Manifestations
 
## Diagnostic Approach and DDx

## Investigations

## Management

:::info
Management of AF has traditionally been divided into two competing strategies:

* **Rate control**\
Remain in AF, with controlled ventricular rate. Requires **anticoagulation**.
* **Rhythm control**\
Conversion to sinus rhythm. *May* be superior to rate control, *if* it can be achieved, and is desirable in patients:
	* <60
	* Structurally normal hearts
	* Reversible precipitant of AF
:::

:::column-margin
The rate/rhythm control debate is made more complex by the fact that rate control strategies result in SR in ~35% of patients, and rhythm control fails in 40-60% of patients. Rhythm control agents (amiodarone, flecainide) also have poorer side effect profiles than rate control agents.\
\
Overall, rhythm control is probably superior if it can be consistently achieved without requirement for heavy-duty antiarrhythmics; and so is most ideal in a young patient, without structural heart disease, and good cardiac reserve.
:::


**Resuscitation**:

* Rhythm control

**Specific Therapy**:

* Pharmacological
	* Haemodynamic control\
	One of:
		* Rhythm control
		* Rate control
	* Anticoagulation
* Procedural
	* Ablation\
	Achieves drug-free rhythm control in >80% after one attempt, and >90% after two attempts.
	* LAA occlusion
	* LAA ligation
	* Left pericardiotomy
	* MAZE

:::column-margin
LAA ligation, left pericardiotomy, and MAZE all are performed as an addition to another cardiac surgery to prevent post-operative AF, and are not performed as singular procedures.
:::

**Supportive Care**:

* Treat precipitant


### Rhythm Control

:::caution
Urgent electrical cardioversion is recommended for haemodynamically unstable AF with RVR - just as with other unstable tachyarrhythmias.
:::

Cardioversion describes restoration of normal sinus rhythm, and is associated with a temporary ↑ **stroke risk**, as any clot formed in the static atria may embolise when atrial contraction resumes. Risk significantly elevated if **both**:

* Not therapeutically anticoagulated for at least **3 weeks**
* AF duration >48 hours


Cardioversion can be performed either:

* **Electrically**\
**Synchronised** electrical cardioversion indicated if haemodynamically unstable. **Requires sedation in the conscious patient**.
	* Failure associated with:
		* Greater AF duration
		* LAE
		* Precipitants present	
* **Chemically**\
A variety of agents:
	* Amiodarone\
	Variable dosing strategies described:
		* 2mg/min for 4 hours
		* 5mg/kg over 1 hour
		* 150mg over 30 minutes, followed by infusion\
		Can repeat the IV load twice.	
	* Flecainide\
		* 2mg/kg over 10 minutes.
		* Not suitable in structural heart disease or heart failure
	* Ibutilide\
		* 1mg over 10 minutes, followed by a repeat dose after 10 minutes
		* Risk of TDP
	* Vernakalant\
		* 3mg/kg over 10 minutes, followed by 2mg/kg over 10 minutes
		* Suitable in structural heart disease or heart failure
		* More effective in the short term than amiodarone, but less effective in maintaining SR at >24 hours.


### Rate Control

For acute control:

* Stable
	* Metoprolol 2.5-5mg IV
	* Diltiazem 30-69mg PO
* Unstable
	* Amiodarone 5mg/kg
	* Digoxin 0.5-1mg IV

For maintenance:

* Stable
	* Metoprolol CR 23.75-98mg daily
	* Bisoprolol 2.5-10mg daily
	* Diltiazem 30-60mg PO TDS
* Unstable
	* Digoxin 125-500ug daily
	* Amiodarone 100-200mg daily

### Anticoagulation

Risk depends on aetiology, and therefore is classified into:

:::column-margin
No additional benefit seen from adding aspirin in the therapeutically anticoagulated.
:::

* Valvular AF\
Secondary to *rheumatic* MV disease. Requires therapeutic anticoagulation with warfarin.
* Non-valvular AF
	* Aspirin
	* Therapeutic anticoagulation\
		* Risk assessment\
		Risk-benefit of stroke versus bleeding.
			* Stroke risk assessed with CHA~2~DS~2~VASc score
				* 0: Aspirin or no therapy
				* 1: Either aspirin or anticoagulation
				* ⩾2: Anticoagulation
			* Bleeding risk assessed with HAS-BLED score\
			↑ HAS-BLED suggests use of DOAC rather than warfarin.
		* Options
			* Warfarin\
			Target INR 2-3.
			* DOAC
			* Heparin infusion
	* DAPT\
	Superior to warfarin in the warfarin non-compliant.

:::column-margin
: CHA~2~DS~2~VASc Score

+---------------------------------+--------+
| Risk Factor                     | Points |
+=================================+========+
| **C**ardiac Failure\            | 1      |
| LVEF <40%.                      |        |
+---------------------------------+--------+
| **H**ypertension                | 1      |
+---------------------------------+--------+
| **A**ge ⩾75                     | 2      |
+---------------------------------+--------+
| **D**iabetes Mellitus           | 1      |
+---------------------------------+--------+
| **P**revious embolism           | 2      |
+---------------------------------+--------+
| P**V**D, CAD, or aortic disease | 1      |
+---------------------------------+--------+
| **A**ge 65-74                   | 1      |
+---------------------------------+--------+
| **S**ex (Female)                | 1      |
+---------------------------------+--------+
:::

### Other Considerations

High-risk groups:

* Hypertrophic cardiomyopathy\
	* Rhythm control superior
	* Requires therapeutic anticoagulation

## Anaesthetic Considerations

## Complications

* C
	* Haemodynamic instability
	* Rate-related cardiomyopathy\
	Reversible ↓ in LV function, occurs in ~10%.
* D
	* Stroke


## Prognosis

Prognosis depends on cause:

* Idiopathic ("lone") AF
* Post-surgical\
Significant ↑ risk of stroke, arrhythmia, ↑ hospital length of stay.


## Key Studies

**Post-operative AF**:

{{< include /trials/palacs.qmd >}}

---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.
1. [Posterior left pericardiotomy for the prevention of atrial fibrillation after cardiac surgery: an adaptive, single-centre, single-blind, randomised, controlled trial](https://www.sciencedirect.com/science/article/abs/pii/S0140673621024909). The Lancet. 2021;398(10316):2075-2083. doi:10.1016/S0140-6736(21)02490-9
