# Amniotic Fluid Embolism

:::crisis
This is an **anaesthetic crisis**. Priority is to:

* Manage cardiorespiratory collapse
* Aggressive **right ventricular support**
* Prepare for **impending DIC**
:::

Embolism of amniotic fluid and foetal cells into the maternal circulation, which may precipitate cardiorespiratory collapse via obstructive and distributive shock, occurring in two phases:

* **Acute Right Heart Dysfunction**\
↑ PVR and right heart dysfunction due to spasm of the pulmonary artery by biochemical mediators.
	* Lasts 30-60 minutes
	* High mortality
* **DIC and LV failure**
	* LV failure\
	LV failure/APO.
		* May be due to direct pulmonary depression of mediators
	* Endothelial activation
	* DIC


## Epidemiology and Risk Factors

Epidemiology of AFE:

* Occurs in ~1:8000-80,000 pregnancies
* Has high mortality\
	* Maternal mortality 37-80%\
	↓ Over time as resuscitation has improved, but remains a **leading cause of maternal mortality**.
	* Foetal mortality ~20%
* Has high neurological morbidity\
	* Maternal impediment ~7%
	* Foetal impediment 30-50%


Risk factors:

* Maternal factors
	* Age > 35
* Pregnancy factors
	* Male foetus
	* Multiple pregnancy
	* Polyhydramnios
	* Eclampsia
	* Placenta praevia
	* Placental abruption
* Labour and delivery
	* Induction of labour
	* Assisted vaginal delivery
	* Operative deliery


## Pathophysiology

AFE requires:

* Physical rupture of foetal membranes
* Amniotic fluid pressure to exceed venous pressure
	* Uterus unlikely portal of entry during contractions
	* Likely source is cervical or lower uterine segment tears
	* Late presentation may occur if fluid is compressed into circulation during movement or uterine involution
* Embolisation of amniotic fluid into maternal circulation\
Two broad theories for mechanism of disease (neither of which independently explains findings):
	* Mechanical\
	Obstruction via:
		* Foetal squamous epithelial cells
		* Vernix
		* Mucin
		* Meconium
	* Immunological\
	Release of inflammatory and thrombotic mediators:
		* Endothelin
		* Leukotrienes
		* Prostoglandins
		* Thromboplastic
		* Tissue factor 


## Clinical Manifestations

In general:

* Timing can be variable
	* 65-70% during active labour
	* 20% during LUSCS
	* 10% following vaginal delivery
May occur up to 48 hours post-partum.
* Presentation may be non-specific\
Hypotension and foetal distress are present in **all cases**.
* Classically has a **rapid** and **severe** triad of:
	* **Hypoxic respiratory failure**\
	Pulmonary oedema occurs in ~95%.
	* **Cardiogenic shock**\
	Including cardiac arrest.
	* **DIC**\
	Occurs in basically all cases that survive the immediate cardiogenic shock.
* Cause of sudden and unexplained maternal collapse


May also present with:

* Bronchospasm
* Dyspnoea
* Seizures
* Dysrhythmias
* Chest pain
* Headache


## Diagnostic Approach and DDx

Key differentials include other causes of shock, particularly:

* Obstructive shock
	* Pulmonary embolus
	* Air embolus
* Distributive shock
	* Sepsis
	* Anaphylaxis
* Cardiogenic shock
	* Peripartum cardiomyopathy
	* MI
	* LAST
* Hypovolaemic shock
	* Placental abruption


## Investigations

**Bedside**:

* Echocardiography\
TTE or TOE if available. Key findings:
	* RV failure
	* Pulmonary hypertension
	* Underfilled LV
	* Intracardiac thrombi/emboli


**Laboratory**:

:::column-margin
AFE is fundamentally a clinical diagnosis, investigations may guide supportive management.
:::

* Bloods
	* FBE, UEC, CMP
	Commonly performed but do not aid management. Thrombocytopaenia is rare initially.
	* Cardiac enzymes
	* Coagulation assay\
	Classically low (or entirely **absent**) fibrinogen with prolonged PT and APTT.
	* TEG/ROTEM\
	For evaluating DIC.

**Imaging**:

* CXR


**Other**:

* ECG\
RV strain, tachycardia, ischaemia.

:::column-margin
Investigations that have been used for diagnosis include:

* Maternal PA blood sampling for squamous epithelial cells\
Drawn from a wedged PAC.
* Histological analysis of cervix\
If a hysterectomy has been performed
* Autopsy
:::

## Management

:::priority
* **Deliver** the foetus
* Early **intubation** if required for hypoxia
* Support circulation with fluid, **aggressive vasopressors**, and **inotropes**
* Early correction hypofibrinogenaemia with **cryoprecipitate**
:::

**Resuscitation**:

* A
	* Generally early intubation
* B
	* May require bronchodilators\
	Note uterine tone; consider avoiding β-agonists.
* C\
Rapid establishment of:
	* Invasive pressure monitoring
	* Aggressive volume resuscitation
	* Vasopressors
	* Pulmonary vasodilators
	* Mechanical support\
	Includes:
		* CPB
		* ECMO
		* IABP
* H
	* Massive transfusion likely\
	Early haematological consultation.

**Disposition:**

* ICU admission likely


## Complications

Include:

* ARDS\
Common:
	* 83% of all patients
	* 93% of patients with coagulopathy
	* Rarely may be the sole feature
* Hysterectomy\
Due to consumptive coagulopathy.
* Transfusion requirement\
Due to DIC.


## Prognosis

* High mortality\
20-60% in developed nations. Highest in initial periods.
* Neurological morbidity

---

## References

1. Metodiev Y, Ramasamy P, Tuffnell D. [Amniotic fluid embolism](https://bjaed.org/article/S2058-5349(18)30060-X/pdf). BJA Education. 2018 Aug;18(8):234–8. 
