# Aortic Stenosis


Aortic stenosis occurs when valvular disease impedes blood flow across the valve during ventricular systole. The aortic valve is normally 2.6-3.5cm^2^, and haemodynamically significant obstruction occurs when AVA approaches 1cm^2^. AS is classified based on echocardiographic findings, using either:

* Aortic valve pressure gradient/peak flow\
Dependent upon flow across the valve, and so will **underpredict severity in failure states** because the failing LV cannot generate enough pressure to produce a high flow.
	* Pressure gradients are calculated by measuring flow across the valve, using the **simplified Benoulli equation:** $$ \Delta P = 4v^2$$\
	* Peak gradients are calculated from peak flow during ejection
	* Mean gradients are calculated by the average flow (area under the doppler envelope) during ejection
* Aortic valve area\
Derived using DI and LVOT area, so is less accurate than direct measurements of flow.

|Technique|Mild|Moderate|Severe|
|--|---|
|Peak velocity (m/s)|2.6-2.9|3-4|>4|
|Mean Pressure Gradient|<30|30-50|>50|
|Aortic Valve Area|>1.5|1.5-1.0|<1.0|
|Dimensionless Index|0.5-0.75|0.25-0.5|<0.25|

^2^

## Epidemiology and Risk Factors

Risk factors include:

* Male
* CAD risk factors
	* DM
	* Hypercholesterolaemia
	* Smoking
	* Hypertension
	* Haemodialysis\
	Occurs in 10%.

## Pathophysiology

In aortic stenosis:

* LV responds to obstruction by undergoing hypertrophy\
Allows pressure gradient across the valve to be maintained without:
	* Reduction in SV
	* Ventricular dilation


* LVH leads to stiffening of the ventricle\
Subsequent diastolic dysfunction.
	* Hypertrophied ventricle more dependent on atrial kick
* LVH ↑ oxygen requirements, whilst ↑ LV diastolic pressures reduce coronary blood flow and oxygen delivery\
Susceptible to ischaemia, especially when CO is high, even in absence of coronary artery disease.


* LA hypertrophy/dilation may occur to maintain filling


### Aetiology

AS may be caused by:

* Degenerative calcification\
Mechanical stress leading to progressive fibrosis and calcification.
	* Most common cause
	* Typically in those over 70
	* Initially occurs as sclerosis\
	Thickening/calcification of leaflets without stenosis.
* Congenital bicuspid valve\
Most common congenital cardiac malformation.
	* Typically symptomatic in 40-60 year olds\
	Accounts for 50% of AVR performed for AS in those under 70.


## Clinical Manifestations

> 50% of patients with severe AS do not report symptoms

Symptoms:

* Include:
	* Angina\
	Due to mismatch between LV oxygen consumption and demand.
	* Syncope\
	Late and bad sign. Occurs due to inadequate cardiac output, and may be related to either:
		* ↑ demand in the setting of a relatively fixed cardiac output
		* Arrhythmia
	* Dyspnoea\
	Due to LV failure, and typically occurs in late disease (as it represents a failure of LV compensation.)
* Do not correlate well with anatomical severity

Signs:

* Slow rising, low volume pulse
* Reduced SBP and pulse pressure
* Ejection systolic murmur
	* Peaks in late systole
	* Radiates to carotids and to apex
	* May disappear in LV failure as flow through the valve orifice ↓



## Diagnostic Approach and DDx

## Investigations

ECG:

* Normal in ~20%
* LAD
* LVH\
* AV block\
Secondary to AV nodal calcium infiltration (extending from the aortic annulus).


Echocardiography:

* 2D exam\
Identifies thickening, impaired mobility, congenital abnormalities, and calcification of valve leaflets.

## Management

> Asymptomatic patients should be monitored for progression of AS or deteriorating LV function that would indicate requirement for AVR

### Anaesthetic Considerations

* C
	* Lesion assessment\
	Preoperative TTE ideal to evaluate degree of stenosis and LV function.
		* If unable to evaluate preoperatively, treat as if patient has at least moderate severity disease
		* Impairment can be estimated by knowing that valve area reduces by ~0.1cm^2^/year
	* **Defend perfusion pressure**\
		* Vasopressor infusions with aggressive use of boluses
		* Use neuraxial techniques with caution
	* Invasive arterial monitoring


### Marginal and Ineffective Therapies

## Complications

Extensive cardiac remodelling, including:

* LVH
* LV diastolic dysfunction
* LA dilation
* MR\
Due to annular dilatation.
* PHTN\


## Prognosis

Asymptomatic severe AS:

* Annual ↓ in AVA is ~0.1cm^2^/year
* Median time to symptom development is 1-4 years
* Within 5 years:
	* 2/3^rds^ will develop symptoms
	* 75% will have died or had valve replacement


Symptomatic severe AS:

* Very poor prognosis without AVR
* Mortality rapidly ↑ once symptoms develop\
	* Mean survival 0.5-2.8 years after onset of cardiac failure
	* Mean survival 0.8-3.8 years after onset of syncope
	* Mean survival 2-4.7 years after onset of angina
* Pulmonary hypertension is an additional risk factor and worsens prognosis after valve replacement


Perioperative death and MI risk:

* Symptomatic AS; OR 2.7
* Co-existing moderate or severe MR; OR 9.8
* Pre-existing CAD; OR 2.7

---

## References

1. Brown J, Morgan-Hughes NJ. [Aortic stenosis and non-cardiac surgery](https://academic.oup.com/bjaed/article/5/1/1/339852). Contin Educ Anaesth Crit Care Pain. 2005;5(1):1-4. doi:10.1093/bjaceaccp/mki001
2. Généreux P, Stone GW, O’Gara PT, et al. Natural History, Diagnostic Approaches, and Therapeutic Strategies for Patients With Asymptomatic Severe Aortic Stenosis. J Am Coll Cardiol. 2016;67(19):2263-2288. doi:10.1016/j.jacc.2016.02.057
