# Aortic Dissection

Life-threatening vascular emergency due to tear of the aortic intima, allowing entry of blood between the intima and media leading to creation of a **false lumen** that extends under pressure, leading to organ ischaemia due to occlusion of the true lumen.

The **Standford Classification** divides aortic dissections on their anatomical origin, and determines the management:

* Type A\
Originate in the ascending aorta.
	* Mortality of 1-2% per hour after onset
* Type B\
Originate in the descending aorta, but may propagate proximally.
	* May be medically managed\
	Control of HR and BP.

:::column-margin
The DeBakey Classification divides based on anatomical origin and extent, but is less helpful than the Stanford classification for the non-interventionalist as it is more verbose and doesn't further influence management:

* Type I
	* Begins in the ascending aorta
	* Extends past the aortic arch\
	May extend to the iliacs.
* Type II
	* Begins in the ascending aorta
	* Ends in the ascending aorta
* Type III\
Subdivided into:
	* IIIa
		* Begin distal to the L SCA
		* Does not extend past the diaphgram
	* IIIb
		* Begin distal to the L SCA
		* Extend past the diaphragm
:::

## Epidemiology and Risk Factors

Key risk factors:

* Age
* CVS disease
	* Hypertension\
	Poorly controlled or situational.
	* Hyperlipidaemia
	* Smoking
* Cocaine use
* Genetics
* Pregnancy\
Generally 3^rd^ trimester or post-partum.


## Pathophysiology

### Aetiology

May be:

* Degenerative
* Genetic disease\
Diseases of connective tissue:
	* Marfans Syndrome
	* Ehlers-Danlos Syndrome
	* Familial Aortic Dissection
	* Annuloaortic ectasia
* Iatrogenic
	* Cardiac surgery
	* Cardiac catheterisation
	* IABP insertion

## Clinical Manifestations

Presentations include:

* **Chest and back pain**\
Rapid onset, severe.
* May be **painless** in **6%**\
Generally:
	* Diabetic
	* History of AAA
	* History of cardiac surgery
* Cardiac failure
* CVA
* Syncope

## Diagnostic Approach and DDx

## Investigations

Include:

* CT
* TOE

## Management

**Resuscitation**:\

* C
	* **Haemodynamic control**\
	Vital to reduce progression of dissection, though urgency is ↑ in type A. Targets:
		* SBP 100-120mmHg
			* Labetalol
			* Magnesium
			* GTN
		* HR ⩽60bpm
			* Labetalol
			* Metoprolol
	* Arterial access to guide resuscitation
* D
	* Analgesia\
	For control of haemodynamics.
		* Fentanyl

**Specific therapy**:

* Pharmacological
* Procedural
* Physical

**Supportive care**:

**Disposition**:

* OR\
Urgent theatre for Type A dissections.
* ICU/HDU\
Often required for BP control.


### Anaesthetic Considerations

### Marginal and Ineffective Therapies

## Complications

## Prognosis

## Key Studies


---

## References


