# Infective Endocarditis

Severe and life-threatening infection of cardiac skeletal structures, characterised by:

* Cardiac destruction
    * Valvular heart disease\
    Typically on the lower-pressure side (atria AV, ventricular for aortic/pulmonary) of the valve.
        * Left sided in 90%
    * Abscesses\
    Classically aortic root.
    * Perforation
    * Fistula
* Persistent bacteraemia
* Systemic embolic complications


## Epidemiology and Risk Factors

Risk factors:

* Cardiac
    * Abnormal valve\
    More likely to become infected, and more difficult to eradicate infection from.
        * Rheumatic
        * Degenerative
    * Intracardiac device
        * Prosthetic valve
        * Implantable wires
* Bacteraemia
    * Concurrent infection
    * IVDU


## Pathophysiology

### Aetiology

Bacterial infection predominates, common causative organisms include:

* Gram positive cocci
    * *Staphylococci*
    * *Streptococci*
    * *Enterococci*
* Gram negatives
    * *Coxiella burnetii*
    Q fever, culture negative.
    * HACEK organisms\
    Usually culture negative.
        * *Haemophilus* spp.
        * *Actinobacillus*
        * *Cardiobacterium hominis*
        * *Eikenella corrodens*
        * *Kingella kingae*

Fungal endocarditis is rare, and seen with:

* Immunocompromise
* IVDU 


## Clinical Features


## Assessment

**History**:

**Exam**:

* Skin findings
    * Osler's nodes
    * Janeway lesions
    * Splinter haemorrhages
    * Roth spots
* Embolism
    * Neurological
    * Renal

### Investigations

**Bedside**:

* Echocardiography
    * Modality
        * TTE\
        * TOE\
        Better imaging of valvular structures and device leads.
    * Features
        * Vegetation
        * Valvular destruction
            * Regurgitation
            * Dehiscence of prosthetic valve
        * Fistula
        * Ventricular dysfunction

**Laboratory**:

* Bloods
    * FBE
    * UEC
    * Blood cultures

**Imaging**:


* CT
    * Embolic phenomena
* MRI
    * Embolic phenomena\
    Particularly strokes. 

**Other**:

### Diagnostic Approach and DDx

: Duke Criteria for Infective Endocarditis

+------------------------------------------+-------------------------------+
| Major                                    | Minor                         |
+==========================================+===============================+
| Typical microorganisms in blood cultures | * Predisposing condition      |
|                                          |     * Mechanical valve        |
| * 2 separate cultures                    |     * IVDU                    |
| * 2 cultures 12 hours apart              | * Fever >38.0°                |
| * 3/4 cultures taken within 1 hour       | * Vascular manifestations\    |
|                                          | e.g. Janeway lesion.          |
| Echocardiographic evidence of:           | * Immunologic manifestation\  |
|                                          | e.g. GN.                      |
| * Abscess                                | * Positive blood cultures\    |
| * Vegetation                             | Not meeting major criteria.   |
| * Prosthetic valve dehissence            | * Echocardiographic findings\ |
|                                          | Not meeting major criteria.   |
+------------------------------------------+-------------------------------+
| Diagnosis requires one of:                                               |
|                                                                          |
| * Both major and one minor criteria                                      |
| * One major and three minor criteria                                     |
| * Five minor criteria                                                    |
+--------------------------------------------------------------------------+

The Duke criteria are broadly accepted, but somewhat limited as 20% of endocarditis is culture negative.

## Management

**Specific therapy**:

* Pharmacological
    * Early antimicrobial therapy
        * Extended duration\
        Classically 6 weeks.
        * Local-microbiome adjusted\
        Consider:
            * Flucloxacillin
            * Vancomycin
            * Benzylpenicillin
            * Gentamicin
* Procedural
    * Surgery is the cornerstone of curative therapy
    * The decision on *when* to operate is complex and driven by the balance of:
        * Delaying for pre-operative optimisation
        * Intervening to prevent further decline
    * The decision should be multidisciplinary, but factors favouring proceeding include:
        * Cardiac failure
            * Refractory shock/pulmonary oedema infers urgent surgery
        * Uncontrolled infection\
        Persistent positive blood cultures despite 3-10 (recommendations vary) days of appropriate antibiotic treatment.
        * Embolisation
            * Large (>1cm) vegetation at risk of embolising
            * Ongoing embolic phenomena\
            Decision confounded by intracranial haemorrhage, which has substantial implications for therapeutic heparin required for CPB.
        * Aortic root abscess


**Supportive care**:

**Disposition**:

* ICU admission common for:
    * Heart failure
    * Septic shock
    * Neurological involvement



### Marginal and Ineffective Therapies

## Anaesthetic Considerations

## Complications

* C
    * Embolism
        * Pulmonary\
        For right sided disease.
        * Stroke\
        15-30%.
        * Splenic
        * Renal
* I
    * Sepsis


## Prognosis

Varies depending on the extent of valvular disease and severity of systemic infection, however:

* Mortality
    * 30-50% in patients receiving surgical treatment
    * 85% in those not receiving operative intervention


## Key Studies


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.