# Long QT

Prolonged duration of ventricular repolarisation which ↑ risk of **polymorphic ventricular tachycardia**. Polymorphic VT:

:::column-margin
The QT interval varies with and must be corrected for the heart rate.\
\
**Bazett's Formula** suggests:

$$QTc = {QT \over \sqrt{R \textendash R \ Interval}}$$
:::

* May:
	* Resolve spontaneously
	* Degenerate to **VF**
* Be triggered by:
	* ↑ Sympathetic tone
		* Exercise
		* Sudden loud noises
		* Emotional stress
		* Pain
* Occurs with ↑ risk with ↑ QTc\
	* Borderline 440-470ms
	* High with QTc >500ms

## Epidemiology and Risk Factors

## Pathophysiology

Myocardial repolarisation:

* Occurs due to a combination of:
	* Outward K^+^ flow
	* Inward Ca^+^ and Na^+^ flow\
	Partially counters K^+^ current.
* Is not homogenous between epicardium, mid-myocardium, and endocardial cells
	* Mid-myocardium is slower due to reduced K^+^ and Na^+^ channel density\
	The tail of the T-wave tends to represent repolarisation of mid-myocardial cells.
* ↓ mid-myocardial K^+^ or ↑ Na^+^ channel function in the mid-myocardium will therefore prolong the action potential
	* This may lead to late calcium inflow, and early after-depolarisations
		* If these EADs reach a threshold amplitude, VT may result

### Aetiology

May be:

* Congenital\
1/2,500-5,000. Multiple major genotypes have been developed, which include:
	* Jervell–Lange-Nielsen\
	Autosomal recessive.
	* Romano–Ward\
	Autosomal dominant.
* Acquired\
Likely associated with some genetic abnormality. Include:
	* Drugs
	* Electrolyte abnormalities
	* Malnutrition\
	In addition to any risk due to neurological abnormalities.
	* Neurological injury

## Clinical Manifestations

History:

* Sudden syncope\
30% of congenital present with syncope or aborted sudden death.
* Pseudo-seizures during exercise or stress
* Family history of sudden death

## Diagnostic Approach and DDx

## Investigations

ECG:

* QTc >440ms\
May only be revealed in situations of physiological stress (e.g. a stress ECG).

## Management


**Resuscitation**:\

:::column-margin
1g MgSO~4~ is ~4mmoL of Mg^2+^.
:::

* C
	* Polymorphic VT/VF
		* DC cardioversion
		* Mg^2+^\
		Reduces EADs by ↑ encouraging resting repolarisation.
			* Given as 2g MgSO~4~ over 2-3 minutes\
			May be repeated with another 2g after 15 minutes.
			* Consider infusion of 3-20mg/min if arrhythmias persist

**Specific therapy**:

* Pharmacological
	* Antiarrhythmic
		* β-blockade
* Procedural
	* Pacing\
	↑ HR and reduces QTc.
	* AICD

**Supportive care**:

**Disposition**:


Medical management:

* β-blockade
* Pacing\
↑ HR and reduces QTc.
* AICD

#### Potential Precipitants

Drugs associated with development of polymorphic VT:

* Anti-arrhythmics
	* Sotalol
	* Amiodarone
	* Procainamide
	* Flecainide
	* Disopyramide
* Antibiotics
	* Erythromycin
	* Clarithromycin
	* Fluconazole
* Anti-psychotics
	* Droperidol
	* Haloperidol
* Anti-depressants
	* Fluoxetine
* Sympathomimetics
	* Ketamine

### Anaesthetic Considerations

* B
	* Maintain normocarbia
* C
	* Malignant arrhythmia
		* High risk of intraoperative arrhythmia
		* May be precipitated by ↑ sympathetic tone
			* Intraoperative sympatholysis is crucial
		* Cardiology review pre-operatively is ideal
	* Avoid bradycardia
	* Avoid hypotension
* E
	* Avoid reversal of neuromuscular block\
	QTc is prolonged with neostigmine-glycopyrrolate.

### Marginal and Ineffective Therapies

## Complications

## Prognosis

## Key Studies


---

## References

1. Hunter JD, Sharma P, Rathi S. Long QT syndrome. Contin Educ Anaesth Crit Care Pain. 2008 Apr 1;8(2):67–70. 
