# Mitral Regurgitation

Mitral regurgitation is classified in two ways:

* Aetiology
	* Primary\
	Due to valvular pathology.
	* Secondary/Functional\
	Due to LV dysfunction interfering with normal valvular function.
* Temporality
	* Acute\
	Pathology evolving faster than LA compensation, resulting in elevated LAPs, PAPs, and pulmonary oedema (classically severe and of rapid onset).
	* Chronic\
	MR with LA compensation. Symptoms may only develop after many years when the LV fails.


MR classification is complex, and is based on echocardiographic findings:

: Grading of Mitral Regurgitation

| Measurement                        | Mild       | Moderate      | Severe      |
| ---------------------------------- | ---------- | ------------- | ----------- |
| Regurgitant fraction               | <30%       | 30-49%        | \>50%       |
| Regurgitant volume                 | <30ml/beat | 30-60mL/beat  | \>60mL/beat |
| Effective Regurgitant Orifice Area | ⩽0.2cm^2^  | 0.2-0.39cm^2^ | \>0.4cm^2^  |

## Epidemiology and Risk Factors

## Pathophysiology

Acute MR:

* Sudden regurgitation leads to acute LV volume overload\
Results in:
	* ↑ LVEDP
	* Rapid LA dilation and ↑ in LAP
	* Pulmonary hypertension
	* Acute pulmonary oedema
	* RV failure
	* Sympathetic stimulation
		* Tachycardia
		* ↑ LV contractility


Progressive regurgitation leads to:

* Volume overload
* Progressive chamber dilatation\
Initially well-compensated with preserved systolic function.
	* ↑ LVEDV with normal LVEDP
* Eccentric hypertrophy
* Eventual decompensation when dilation and hypertrophy can no longer maintain forward SV
	* ↑ PAP
	* Pulmonary congestion
	* RV failure


### Aetiology

Causes include:

* Acute
	* Chordae rupture
		* Myxomatous disease
		* Chest trauma
		* Acute rheumatic fever
	* Ischaemia
		* Papillary muscle rupture
	* Infective endocarditis
* Chronic
	* MV leaflet abnormalities
	* Annular dilatation\
	LV dilation.
	* Rheumatic heart disease


## Clinical Manifestations

### History

### Examination

## Diagnostic Approach and DDx

## Investigations

Echocardiography:

* Allows grading of severity
* LV assessment is confounded\
EF appears higher than it is due to the regurgitation fraction.
	* LVEF of ~70% is equivalent to ~55% in absence of MR.

## Management

Medical management of **acute MR** involves:

* Reducing filling pressures
	* Diuretics
	* Nitrates
* Reducing afterload
	* Vasodilators
	* IABP
* Preservation of forward flow\
Maintain normal or high-normal heart rate, sinus rhythm.

Medical management of **chronic MR** involves treating cardiac failure, and cardioversion if required.

Surgical management of MR involves either repair (most common) or replacement (rare). Indications for surgery:

* Primary, severe, acute MR\
E.g. ruptured papillary muscle.
* Symptomatic chronic MR
* Asymptomatic MR with CVS sequelae:
	* LVEF <60%
	* AF
	* Pulmonary HTN


### Anaesthetic Considerations

* C
	* Maintain preload\
	Promotes forward flow.
	* Aim high-normal heart rate (80-100)\
	Reduces diastolic regurgitant fine.
	* Afterload reduction\
	Reduces regurgitant fraction. Particularly important around intubation.
	* Inotropes

:::column-margin
In mixed valvular disease, management should prioritise the most haemodynamically significant lesion. That said, in general:

{{< include /includes/as_mr.qmd >}}
{{< include /includes/ar_mr.qmd >}}
{{< include /includes/ms_mr.qmd >}}
:::

### Marginal and Ineffective Therapies

## Complications

## Prognosis


---

## References

1. Holmes K, Gibbison B, Vohra HA. [Mitral valve and mitral valve disease](https://academic.oup.com/bjaed/article/17/1/1/2706111). BJA Educ. 2017;17(1):1-9. doi:10.1093/bjaed/mkw032