# Mitral Stenosis


Mitral stenosis is:

* Narrowing of the mitral valve orifice, leading to a fixed-cardiac output state with a pressure-overloaded (and typically subsequently volume-overloaded) left atrium  
Normal area is >4cm^2^.


MS is classified:

* Into mild, moderate, or severe  
Symptoms typically only present in moderate-severe MS.
* Based on echocardiographic findings  
Using either:
	* Mean pressure gradient over the valve
	* Pressure half-time
	* Valve area

|Measurement|Mild|Moderate|Severe|
|--|--|--|
|MPG|<5mmHg|6-10mmHg|>10mmHg|
|Pressure half-time|<139ms|140-219ms|>220ms|
|Valve area|1.6-2.0cm^2^|1.5-1cm^2^|<1cm^2^|


## Epidemiology and Risk Factors

Important associations:

* Rheumatic fever
* Pregnancy  
Leads to early presentation with symptoms due to ↑ cardiovascular work and circulating volume.
	* Fixed CO-state leads to ↑ pulmonary hypertension
	* Cardiac failure typically occurs in third-trimester in patients with moderate-severe disease

## Pathophysiology

* ↑ pressure gradient across the mitral valve  
Flow across mitral valve becomes the prime determinant of ventricular filling.
	* This leads to a **fixed cardiac output** state because:
		* ↓ afterload does not improve subsequent ventricular filling
		* ↑ contractility cannot improve output if the ventricle is not adequately filled prior to contraction

### Aetiology

Causes include:

* **MS**  
Most common cause.
	* Rarer aetiology in developed countries
	* Typically worsens at the rate of 0.1-0.3cm^2^/year  
	More rapid in cases of repeated infection.


## Clinical Manifestations

MS is typically well tolerated until LA dilation fails to compensate and pulmonary HTN ensures, leading to:

* Pulmonary oedema
* Fatigue


### History

### Examination

## Diagnostic Approach and DDx

## Investigations

## Management

Medical management consists of managing complications:

* Rate control of AF
	* β-blockers are mainstay of treatment
* Diuresis and vasodilators (e.g. nitrates) for failure

Surgical management:

* Percutaneous mitral commissurotomy  
Balloon dilation of mitral commissures, ↑ MV area.
* MV repair
* MV replacement

### Anaesthetic Considerations

* C
	* Maintain sinus rhythm
	* Maintain HR <70 to facilitate diastolic filling
	* Maintain preload
		* Volume required due to diastolic dysfunction
		* Excessive volume will worsen pulmonary oedema
	* Maintain afterload  
	As CO is fixed, reduced SVR will ↓ CPP.
	* Prevent ↑ in PVR  
	Right heart function may be tenuous in the setting of pre-existing PHTN.

### ICU Considerations

Following MV repair or replacement:

* Maintain preload due to existing diastolic dysfunction
* Reduce afterload to improve forward flow
* Right heart support may be required

## Complications

* AF  
Due to atrial dilation.
	* Leads to worsening symptoms due to:
		* Reduced diastolic time
		* Reduced atrial kick
* Pulmonary hypertension  
Due to ↑ LAP.
* Right heart failure  
Due to prolonged period of pulmonary hypertension.


## Prognosis


---

## References

1. Holmes K, Gibbison B, Vohra HA. [Mitral valve and mitral valve disease](https://academic.oup.com/bjaed/article/17/1/1/2706111). BJA Educ. 2017;17(1):1-9. doi:10.1093/bjaed/mkw032