# Pulmonary Embolism {#sec-pe}

Blockage of a pulmonary artery or its branches due to embolised clot, leading to RV dysfunction and impaired gas exchange. Significance ranges from trivial to life-threatening depending on the size of the occlusion and the cardiorespiratory reserve.

:::column-margin
VTE is an umbrella term encompassing both DVT and PE, and is used as there is substantial overlap in both pathologies. This distinction is not made here; this section covers PE whilst DVT is covered in detail under @sec-dvt.
:::

PE is classified by degree of haemodynamic impairment into:

* Massive\
PE with hypotension (**SBP <90mmHg**). Indication for clot destruction via thrombolysis or embolectomy. Anticoagulation should be commenced once thrombolysis completed.
* Submassive\
PE with evidence of RV dysfunction (ECG, echo). Clot destruction controversial - low-dose thrombolysis may be more appropriate; anticoagulation is indicated.
* Mild\
PE without haemodynamic instability or RV dysfunction. No indication for clot destruction, anticoagulation is indicated.

:::column-margin
Subsegmental PEs are also sometimes described, which refer to distal emboli seen on CT. They usually are asymptomatic, have no clinical significance, and do not require intervention.
:::

## Epidemiology and Risk Factors

Risk factors for clot formation are given by Vichows triad:

:::column-margin
Systemic prothrombotic effects (e.g. Factor V Leiden, OCP use, obesity) predominantly ↑ risk of DVT (and later embolism), pulmonary disease tends to ↑ risk of PE without ↑ DVT risk.
:::

* Stasis\
Many thrombi occur around venous valves.
	* Advanced age\
	Risk ↑ after 40.
	* Immobilisation
	* Obesity
	* General anaesthesia\
	~30-50% greater risk compared to spinal/regional technique.
* Endothelial Damage
	* Central venous access
* Hypercoagulable state
	* Surgery\
	Incidence depends on type of surgery:
		* Thoracic: ~2%
		* Abdominal: ~1%
		* Hip arthroplasty: Up to 30%
		* Knee arthroplasty: Up to 7%
		* Trauma: 2-6%
		* Neurosurgery: Up to 4%
		* Spinal cord injury: 5-9%
	* Hereditary
		* AT III deficiency
		* Protein C or S deficiency
		* Factor V leiden
		* Prothrombin gene deficiency
	* Pregnancy\
	DVT risk is 5× as high post-partum compared with durign pregnancy, and PE risk is 15× as high.
	* Malignancy
	* Acute illness
		* Trauma
		* Sepsis
	* Inflammatory diseases
		* IBD
		* Autoimmune disease
	* Previous VTE
	* Drugs
		* OCP\
		2-5× ↑ relative risk.
		* Chemotherapeutics
		* Smoking
		* Antipsychotics


Risk factors for death from PE:

* Age > 70
* Congestive heart failure
* COAD
* ASA score
* Hypotension and tachypnoea on diagnosis

## Pathophysiology

Key processes are:

* Clot formation and embolisation\
PE predominantly arise from DVT in the lower limbs, pelvic veins, or IVC. DVT can then:
	* Propagate proximally\
	PE will occur in ~50% of patients with proximal DVT. Below knee DVT rarely causes clinicially significant PE.
	* Break off entirely\
	~20% of patients with PE have no identified DVT.
* Impaired pulmonary gas exchange:
	* ↑ alveolar dead space\
	Non-perfused alveoli distal to clot.
	* Over-perfusion of non-clotted lung\
	May cause shunt via a variety of mechanisms:
		* Oedema
		* Pulmonary haemorrhage\
		Pulmonary infarction does not usually occur due to ongoing perfusion from bronchial circulation.
		* Loss of surfactant
		* Vasoactive peptide secretion
* Acute RV dysfunction
	* ↑ PVR\
	Pulmonary arterial obstruction leads to ↑ PVR and elevated RV afterload. May be exacerbated by low mixed venous PO~2~ .
	* ↑ Right-sided pressures\
	↑ in RAP may open a PFO and lead to intracardiac right-to-left shunting and risk of systemic embolism.
	

## Clinical Manifestations

Clinical features depend on:

* Clot location
* Clot burden
* Severity of disease relating to underlying CVS reserve

Features are few and generally non-specific, but may be:

* Due to pulmonary infarction
	* Haemoptysis
	* Pleuritic chest pain\
	* Pleural rub\

* Due to pulmonary hypertension
	* RV pressure overload
		* ↑ RAP\
		May be seen as elevated JVP.
		* ↑ PVR
		* ↓ CO
		* ↑ SVR
	* Loud P~2~

* Due to obstructive shock:
	* Cardiac arrest
	* Shock Index > 1 is strongly associated with in hospital mortality
	* Tachycardia\
	May be isolated finding.
	Tachypnoea
	* Hypotension


## Diagnostic Approach and DDx

PE should always be considered in patients with:

* Sudden onset syncope
* Hypotension
* Extreme hypoxia
* EMD
* Cardiac arrest

Assessing a patient who *may* have PE should:

* Commence with careful evaluation of history, risk factors, and physical exam
* Use a validated clinical prediction score to stratify need for further investigations
	* Wells Score
	* Geneva score


Other differentials include:

* B
	* Pneumonia
	* PTHx
	* Rib fractures
* C
	* Acute coronary syndrome
	* Aortic dissection
	* APO
* Trauma
	* Fat embolism
* Obstetric
	* Amniotic fluid embolism


## Investigations 

:::column-margin
Can be divided into:

* Diagnostic tests
	* Echocardiography
	* CT
	* V/Q scan
* Non-diagnostic tests
	* 
:::

**Bedside**:

* ABG\
Typically demonstrates:
	* Hypoxaemia\
	May be only abnormality in smaller PEs.
	* Respiratory alkalosis
* **Echocardiography**
	* Presence of thrombus\
	~26% of severe PE can be seen on TOE, as this provides better visualisation of the MPA and RPA.
	* Other disease
	* Quantify RV dysfunction\
	Findings include:
		* RV/LV end-diastolic diameter ratio > 0.7
		* RV/LV area ratio > 0.66
		* RV end-diastolic diameter > 27mm
		* "McConnel Sign"\
		RV free wall hypokinesis with RV apex normo or hyperkinesis.
		* Septal shift
		* TR jet >270cm/sec
		* Pulmonary artery acceleration time <60ms with maximum TR pressure <60mmHg (60/60 sign)
* ECG
	* No abnormalities\
	~30%.
	* Isolated sinus tachycardia
	* Atrial arrythmias\
	Associated with higher mortality.
	* Repolarisation abnormalities\
	Present in ~50% of PE patients.
	* RBBB and precordial TWI best correlate with severity
	* RV strain/cor pulmonale\
	Also non-specific, but suggest massive embolism rather than smaller emvoli.
		* S1Q3T3
		* P-pulmonale
		* Incomplete RBBB
		* RAD

:::column-margin
:::tick
The absence of RV dilation in a haemodynamically unstable patient means that PE is an unlikely diagnosis.
:::
:::


**Laboratory**:

* Bloods
	* D-Dimer
		* ~97% sensitive\
		May be useful in ruling out PE in patients with low to moderate clinical suspicion. Reduces the need for radiological tests.
		* Non-specific\
		Does not support diagnosis or indicate severity. Often raised in the critically ill. 
	* Troponin\
		* Elevated in <50% of patients
		* Associated with adverse outcomes\
		Death, inotropes.
	* BNP/NT-pro-BNP	



**Imaging**:

* CXR
	* Useful in supporting or ruling-out other causes of hypoxaemia and hypotension
	* Required prior to V/Q scan
* Lower limb ultrasound\
Identify presence of DVT.
* **CTPA**
	* Quicker and more available than V/Q scanning, but requires contrast load
	* ~85% sensitive\
	Varies depending on machine and radiologist.
		* ↑ to ~100% of PEs with haemodynamic instability
		* Commonly identifies subsegmental PE in asymptomatic patients\
		Clinical significance is unclear, but do not require anticoagulation.
* **V/Q scan**
	* May not be appropriate if existing cardio-pulmonary disease
	* Sensitivity ↑ with modern SPECT devices\
	~1% now non-diagnostic.
	* More sensitive than CTPA for peripheral emboli


**Other**:

* Respiratory Function Tests
	* Physiological dead space:
		* Almost always ↑ in the case of PE\
		Formal measurement is:
			* 100% sensitive
			* 89% specific
		* Requires an intubated/ventilated patient
		* Not easy to perform in practice
		* Suggested by
			* Acute reduction in ETCO~2~
			* Delay in reaching alveolar plateau on ETCO~2~ waveform



## Management

:::priority
* **Risk stratification**\
To determine need for **clot destruction** via:
	* IV thrombolysis
	* Interventional radiology
		* Clot retrieval
		* Catheter-directed thrombolysis
	* Open thrombectomy
* **Haemodynamic support**
* Therapeutic **anticoagulation**
:::


**Resuscitation**:

* B
	* Supplemental oxygen
* C
	* Haemodynamic support
		* RV support
		* ECMO

**Specific therapy**:

:::column-margin
Therapeutic anticoagulation is covered in detail under @sec-anticoagulation.
:::

* Pharmacological
	* **IV thrombolysis**
		* Most common tool
		* Dramatic improvement in haemodynamic state in 90% of patients following administration
			* ~50% reduction in mortality in massive PE
		* Tempered by significant bleeding in 10% of patients with standard dosing
			* Therapy should be ceased and factor replacement commenced if significant bleeding occurs
	* Therapeutic anticoagulation\
	Inhibits clot progression, allowing intrinsic fibrinolysis to ↓ clot burden. Anticoagulation:
		* ↓ Mortality and recurrence\
		May be reasonable to commence prior to formal diagnosis if bleeding risk is low.
		* Initial anticoagulation should be performed with heparin:
			* UFH\
			Preferred in:
				* Renal impairment
				* Following thrombolysis/embolectomy due to reversibility
			* LMWH
				* More predictable dose-response than UFH
				* Faster time to therapeutic anticoagulation
		* Transition to oral anticoagulation when bleeding risk stabilised
			* Warfarin
			* DOAC	
* Procedural
	* **Interventional radiology**
		* Endovascular embolectomy
		* Catheter-directed thrombolysis	
	* Open (surgical)\
	Overtaken by endovascular techniques due to high (25-50%) perioperative mortality, but may be appropriate in massive PE and:
		* Contraindications to thrombolysis
		* Unavailability of interventional radiology
		* Intracardiac thrombus
* Physical


**Supportive care**:

**Disposition**:

**Preventative**:


### Marginal and Ineffective Therapies

## Complications

* Death
	* 25-30% of patients with RV failure requiring inotropes
	* Up to 13% of perioperative PEs
* Recurrence
	* ~6% within 6 months\
	Despite therapeutic anticoagulation.
	* ~8% with 12 months
* Chronic Thromboembolic Pulmonary Hypertension
* Postthrombotic syndrome


## Prognosis



---

## References

1. Desciak MC, Martin DE. Perioperative pulmonary embolism: diagnosis and anesthetic management. J Clin Anesth. 2011;23:153-165.
2. Tapson VF. Acute Pulmonary Embolism. N Engl J Med. 2008;358:1037-1052.
1. Tran HA, Gibbs H, Merriman E, et al. [New guidelines from the Thrombosis and Haemostasis Society of Australia and New Zealand for the diagnosis and management of venous thromboembolism](https://onlinelibrary.wiley.com/doi/full/10.5694/mja2.50004). Medical Journal of Australia. 2019;210(5):227-235. doi:10.5694/mja2.50004