# Tricuspid Regurgitation


## Epidemiology and Risk Factors

## Pathophysiology

### Aetiology

Isolated tricuspid regurgitation may occur with:

:::column-margin
Isolated TR is generally well tolerated as the RV can compensate for the *volume* overload.
:::

* Endocarditis
	* Particularly IVDU-associated
* Carcinoid
* Ebstein's anomaly
* Connective tissue disease


Functional TR occurs secondary to RV failure, in turn due to:

:::column-margin
The RV tolerates *pressure* overload much more poorly than volume overload, resulting in ↑ symptoms and a ↓ in CO compared to primary TV disease.
:::

* Pulmonary hypertension
* Left sided disease
	* AS
	* MS


Combination TR may occur with:

* Rheumatic heart disease



## Assessment


### History


### Examination


### Investigations

**Bedside**:

**Laboratory**:

**Imaging**:

**Other**:

### Diagnostic Approach and DDx


## Management

:::priority
Goals of management
:::

**Resuscitation**:

**Specific therapy**:

* Pharmacological
* Procedural
* Physical

**Supportive care**:

**Disposition**:

**Preventative**:


### Marginal and Ineffective Therapies

## Anaesthetic Considerations

* B
	* Caution instituting positive pressure ventilation\
	Poor tolerance of pressure overload.
	* Avoid factors ↑ PVR, i.e. avoid:
		* ↑ CO~2~
		* ↓ O~2~
		* Acidosis
* C
	* Maintain preload
		* Cautious volume use
	* High-normal HR\
	Maintain forward flow.
	* ↑ Difficulty of floating PAC


## Complications

## Prognosis

## Key Studies


---

## References
