# Tricuspid Stenosis


## Epidemiology and Risk Factors

## Pathophysiology

### Aetiology

Causes include:

* Rheumatic disease\
Rare in isolation, almost always with mitral valve involvement.
* Carcinoid
* Fibroelastosis
* Lupus

## Assessment

A long asymptomatic period occurs before symptomatic right heart failure:

:::column-margin
The TV is the largest valve, and can tolerate more stenosis before haemodynamic impact results. The usual valve area is ~7-9cm^2^ which corresponds to an MPG of ~1mmHg; haemodynamic impact occurs when the MPG is >3mmHg, which genearlly requires a valve area of <1.5cm^2^.
:::

* Hepatomegaly
* Hepatic dysfunction
* Ascites
* Peripheral oedema


### History


### Examination


### Investigations

**Bedside**:

**Laboratory**:

**Imaging**:

**Other**:

### Diagnostic Approach and DDx


## Management

:::priority
Goals of management
:::

**Resuscitation**:

**Specific therapy**:

* Pharmacological
* Procedural
* Physical

**Supportive care**:

**Disposition**:

**Preventative**:


### Marginal and Ineffective Therapies

## Anaesthetic Considerations

:::column-margin
Concomitant MS is common and is generally the primary haemodynamic lesion; thus haemodynamic goals will be typically tailored towards managing the MS.
:::

* C
	* Maintain RV preload
		* Sinus rhythm
		* Normal heart rate
	* Defend RV contractility
	* Avoid ↑ PVR\
	Maintain RV SV.
	* Defend RV perfusion
 



## Complications

## Prognosis

## Key Studies


---

## References
