# Glucose Management

BSL is often erratic in the ICU patient. In general, target BSL should be **8-12mmol/L**. This is:

:::column-margin
Other suggested targets include 8-11mmol/L or 6-10mmol/L.
:::

* Relatively hyperglycaemic
* Safe\
Attempts at tight glucose control typically result in frequent hypoglycaemic episodes.
	* Hypoglycaemia is dangerous and may result in:
		* Permanent neurological injury
		* Cardiac arrest
	* Hyperglycaemia\
	Is relatively benign in the short term.



## Pathophysiology

Hyperglycaemia:

* Commonly occurs in critically ill patients
	* Secondary to  ↓ hepatic response (resistance) to insulin
* Associated with ↑ mortality
* Associated with
	* Impaired immune function
	* Impaired wound healing


Hypoglycaemia:

* Associated with ↑ morbidity and mortality
* Occurs with intensive insulin therapy


## Management



## Key Studies

**BSL control**:

{{< include /trials/nice_sugar.qmd >}}


---

## References

1. [Intensive versus Conventional Glucose Control in Critically Ill Patients](http://www.nejm.org/doi/pdf/10.1056/NEJMoa0810625). N Engl J Med. 2009;360(13):1283-1297. doi:10.1056/NEJMoa0810625
