# Sedation

Sedation is a mainstay of intensive care therapy and is indicated for:

* **Primary treatment of disease**
e.g.:
	* Neurological
		* Seizures
		* ↑ ICP
	* Drug toxicities
		* Serotonin syndrome
		* Alcohol withdrawal
* **Facilitate therapy**
	* Procedural sedation
	* Intubation
	* Mechanical ventilation
	* Active cooling
* **↓ Oxygen consumption**
	* ↓ Respiratory work
	* ↓ Other physical activity
	* ↓ Anxiety and arousal
* **Safety**
	* Of patient
	* Of carers
* **Palliation**

:::column-margin
*Relative* indications also include:

* ↓ Patient anxiety and distress
* Rest
* ↓ Distress
* ↓ Awareness of confronting environment

However, these are preferably managed by non-pharmacological means. Options include:

* Access to visitors
* Good communication
* Positive reinforcement
* Comforts
	* Ice chips
	* Comfortable mattress
	* Music and entertainment
	* Circadian routine
:::

## Assessment

Sedation scoring tools:

* Are used to quantify the degree of sedation provided
* Aim avoid over- or under-sedating patients
* Include:
	* Ramsay Sedation Scale
	* Richmond Agitation Sedation Scale

:::column-margin
EEG has also been trialled, but is limited by movement artifact and not yet made it into routine practice.
:::

### Richmond Agitation Sedation Scale

{{< include /includes/rass.qmd >}}


## Principles

The **goal of sedation** is to achieve a **controlled degree of sedation**, **specific to** the needs of the **patient**, and **based on** the **characteristics** of the **disease**, **patient**, and **therapy**.

A large number of strategies have been described to achieve this, though there is little evidence supporting any one therapy:

* **No sedation**\
↑ Risk of accidental extubation and line removal without change in mortality.
* **Goal-directed sedation**\
Sedatives freely adjusted by the beside nurse to attain the prescribed level of sedation.
	* Deep sedation
		* Indicated for certain specific disease states:
			* Severe T1RF
			* Hyperthermic emergencies
			* Super-refractory status epilepticus
			* ↑ ICP
		* Associated with
			* Delayed extubation
			* ↑ Mortality 
* **Patient-targeted sedation**\
Consist of structured approach for:
	* Assessing pain and distress
	* Adjusting analgesia and sedation based on the algorithm
* **Daily interruption of sedation**\
As goal-directed sedation, except aims to prevent excessive sedation by pausing sedation each day until the patient awakens or exhibits distress requiring recommencement.
	* Facilitate neurological assessment
	* Minimise accumulation of sedation\
	This is more relevant to routine deep sedation, and targeting light (e.g. RASS >-2) sedation will limit this as well.
* **Intermittent sedation**\
Intermittent administration of long-acting sedatives.
* **Analgo-sedation**\
	* Involves:
		* Commencing analgesia (classically opioid) until pain is controlled
		* Adding sedatives only if analgesia is inadequate
	* Benefits include possible ↓ mechanical ventilation duration, ICU length of stay, and VAP
	* Risks include possible ↑ self-extubation, myocardial ischaemia, and opioid withdrawal
* **Patient-controlled sedation**


## Practice

In general:

:::column-margin
This framework outlines intravenous sedation and analgesia for tnhe above indications. More complex overlapping scenarios, such as severe opioid tolerance (e.g. long stay burns) or hyperactive delirium requiring antipsychotics are not covered here.
:::

* Deep sedation should be limited to specific indications
* Most other patients should be sedated to RAAS of -2 to 0\
	* In general
		* Propofol is a common first-line agent
		* Dexmedetomidine
			* Has analgesic and sedative properties
			* Provides conscious sedation
			* Is useful for weaning sedation in patients who:
				* Are emerging dangerously on propofol
				* Have controlled pain
	* High levels of sedation requirements may suggest another present pathology
		* If present, these should be managed separately
		* These include:
			* Pain
			* Delirium
			* Withdrawal
	* This may result certain patients receiving no sedation, typically those with:
		* Trachestomy
		* Exceptional tube tolerance


### Sedatives

Sedation infusions:

* **Propofol**\
0-300mg/hr.
	* Easily titrated
	* ↓ Ventilation time compared to midazolam
	* May precipitate hypotension
	* Risk of hypertriglyceridaemia\
	Should be taken account of in nutrition assessment.
	* Risk of propofol infusion syndrome
		* Paediatric with heart failure
		* Prolonged, high-dose infusions
* **Dexmedetomidine**\
0-1.4μg/kg/min. Consider load of 1μg/kg over 10 minutes in well patients.
	* Analgo-sedative due to central α~2~-agonism
	* ↓ Opioid requirements
	* Minimal suppression of respiration
	* Major side effects include:
		* Bradyarrhythmia
		* Hyperthermia
* **Midazolam**\
1-20mg/hr.
	* Wide dose requirement based on
		* Previous exposure
		* Age
		* Physiologic reserve
		* Organ function
		* Alcohol
		* Other drugs
	* Risk of accumulation in renal or hepatic failure
	* Significant dose ↓ with concurrent opioid infusions
* **Ketamine**\
0.1-0.3mg/kg/hr.
	* Produces dissociative anaesthesia; with sedation, analgesia, and amnesia
	* Use limited predominantly by emergence phenomena
	* Indications include:
		* Asthma
		* Burns

Special:

* **Thiopentone**
	* Very long CSHT limits general use
	* Immunosuppression
	* Essentially reserved for:
		* Intractable ↑ ICP
		* Status epilepticus
* **Volatile anaesthetics**
	* Primarily used as bronchodilating sedation in severe asthma
	* General use is limited by:
		* Cost\
		↓ With modern devices that allow volatile to be recirculated in an ICU ventilator.
		* Complexity of running circle system
		* Occupational health risks 


### Analgesia

Opioids:

:::column-margin
Common features of opioid infusions include:

* High interindividual variability
* Long duration of action due to:
	* Retained metabolites
	* Long CSHT
* Constipation\
Aperients should be administered concurrently.
* Tolerance
:::

* **Fentanyl**
* **Morphine**
* **Remifentanil**\
0.05-0.2μg/kg/min.
	* Short and reliable context-*in*sensitive half-time
	* Provides tube tolerance and permits rapid sedation assessment
	* Risk of rebound hyperalgesia limits use to patients without much intrinsic pain


## Key Studies

**Dexmedetomidine**:

* Dexmedetomidine is a sedative that also produces biomimetic sleep
* Patients may be more easily roused and appropriate when roused, which further ↑ utility of dexmedetomidine
{{< include /trials/mends2.qmd >}}
{{< include /trials/spiceiii.qmd >}}


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.
1. Hughes CG, Mailloux PT, Devlin JW, et al. [Dexmedetomidine or Propofol for Sedation in Mechanically Ventilated Adults with Sepsis](https://www.nejm.org/doi/10.1056/NEJMoa2024922). N Engl J Med. 2021;384(15):1424-1436.
1. Olsen HT, Nedergaard HK, Strøm T, et al. [Nonsedation or Light Sedation in Critically Ill, Mechanically Ventilated Patients](https://www.nejm.org/doi/full/10.1056/NEJMoa1906759). N Engl J Med. 2020;382(12):1103-1111. doi:10.1056/NEJMoa1906759
1. Shehabi Y, Howe BD, Bellomo R, et al. [Early Sedation with Dexmedetomidine in Critically Ill Patients](https://www.nejm.org/doi/full/10.1056/NEJMoa1904710). New England Journal of Medicine. 2019;380(26):2506-2517. doi:10.1056/NEJMoa1904710
