# Thromboprophylaxis {#sec-thromboprophylaxis}

## Principles

### Vena Cava Filter

Physical sieve placed in the IVC to catch emboli from the deep veins prior to a potentially fatal pulmonary embolism. IVC filters:

* Are placed endovascularly via the femoral or RIJ veins
* Are indicated in patients:
	* At high of VTE with an absolute contraindication to chemoprophylaxis
	* Unable to achieve therapeutic anticoagulation with a known DVT/PE
	* With ongoing PE despite full anticoagulation for DVT
* Have no evidence for mortality reduction
* *May* ↓ symptomatic PE
* ↑ Risk of DVT
	* Result in venous stasis of lower limbs
	* May result in IVC occlusion with significant thrombus burden
* Should be retrieved when no longer required
	* Retrievable designs should be used
	* A system for follow-up of patients and removal should exist


## Practice

Approach:

* **Pharmacological**
	* **All patients** should **receive chemoprophylaxis unless** there is a particular **contraindication**:
		* Active **haemorrhage**
		* **Thrombocytopenia**
			* Generally **⩽50**
			* ⩽100 in some cases\
			Cardiothoracic, neurosurgery.
		* **Planned procedure** requiring thromboprophylaxis interruption
	* **GFR >30**mL/min\
	Use **enoxaparin**:
		* ⩽50kg: 20mg SC daily
		* 50-120kg: 40mg SC daily
		* \>120kg: 0.25mg/kg SC Q12H
	* GFR <30mL/min\
	**Heparin**:
		* ⩽120kg: 5000 IU SC BD
		* \>120kg: 5000 IU SC TDS
* **Mechanical**
	* Intermittent **pneumatic calf compression**\
	May reduce incidence by up to 60% in operative patients.
		* Treatment of choice where bleeding risk is high
	* **IVC filter**\
	Reasonable to use in patients with:
		* High VTE risk and contraindications to anticoagulation
		* Recurrent PE despite therapeutic anticoagulation	


### Marginal and Ineffective Therapies

* Compression stockings\
	* Do not ↓ DVT risk
	* ↑ Falls (slippery!) risk
	* ↑ Pressure areas
	* Create a lot of waste


## Key Studies


**IVC Filters**:

{{< include /trials/ho.qmd >}}


**Other**:

{{< include /trials/prevent.qmd >}}


---

## References

1. Ho KM, Rao S, Honeybul S, et al. [A Multicenter Trial of Vena Cava Filters in Severely Injured Patients](https://www.nejm.org/doi/full/10.1056/NEJMoa1806515). New England Journal of Medicine. 2019;381(4):328-337. doi:10.1056/NEJMoa1806515
1. Arabi YM, Al-Hameed F, Burns KEA, et al. [Adjunctive Intermittent Pneumatic Compression for Venous Thromboprophylaxis](https://www.nejm.org/doi/full/10.1056/NEJMoa1816150). New England Journal of Medicine. 2019;380(14):1305-1315. doi:10.1056/NEJMoa1816150
