# Airway Burns




## Epidemiology and Risk Factors

## Pathophysiology


* Upper airway burns common\
* Lower airway burns are rare\
	* Upper airway is an efficient heat exchanger
	* Gases rapidly cooled by the time they have reached carina
	
### Aetiology

## Clinical Manifestations

> * All clinical signs are non-sensitive and non-specific

Classical signs include:

* Singed nasal hairs
* Blisters in mouth
* Hoarse voice
* Sooty sputum

### History

> * History of injury is a good indicator

Key factors:

* Enclosed space
* No avenue of escape

### Examination


## Diagnostic Approach and DDx

## Investigations

## Management


* A
	* Secure airway if in doubt\
	Especially in Australia, where retrieval times are long.
	* Place normal size tube\
	Long duration of intubation is expected, and large ETT ↑ risk of vocal cord granuloma.


### Medical

### Surgical

### Anaesthetic Considerations

### Marginal and Ineffective Therapies

## Complications

## Prognosis

## Key Studies


---

## References
