# Blunt Aortic Injury

Aortic injury occurs due to either:

* Rapid deceleration causing shearing of the aorta between the mobile arch and the fixed descending aorta which is tethered by the ligamentum arteriosum
* Direct trauma


## Epidemiology and Risk Factors

## Pathophysiology

### Aetiology

## Clinical Manifestations

History:

* Rapid deceleration
* High-speed
	* MVA >50km/h
	* Motorbike crash
	* Pedestrian vs. car
	* Fall >3m

## Diagnostic Approach and DDx

## Investigations

**Bedside**:

* TOE
	* Sensitive
	* Limited imaging of the proximal arch and major branches.
	* Portable\
	Can be performed in the OR or in ED.

**Laboratory**:

**Imaging**:

* CXR\
Widened mediastinum is unreliable and CT should be performed in at-risk cases.
* CT angiography\


**Other**:

## Management

**Resuscitation**:


**Specific therapy**:

* Pharmacological
* Procedural
* Physical

**Supportive care**:

**Disposition**:

**Preventative**:


### Marginal and Ineffective Therapies

## Anaesthetic Considerations

## Complications

## Prognosis

Overwhelming majority (>90%) are fatal at scene. Of those who survive to hospital:

* 90% have significant injury
* 50% die within 24 hours

## Key Studies


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.