# Ballistic Trauma


## Epidemiology and Risk Factors

## Pathophysiology


* Temporary cavitation
	* Devitalise surrounding tissue 30-40x diameter of projectile
	* Vacuum draws in surrounding debris, contaminating the devitalised tract

:::column-margin
Bullets are not sterilised by firing.
:::

### Aetiology

## Clinical Manifestations

## Diagnostic Approach and DDx

## Investigations

**Bedside**:

**Laboratory**:

**Imaging**:

**Other**:

## Management

:::priority
* Early wound excision and irrigation
* Delayed primary closure
* Antibiotics and ADT
* Early physical therapy
:::


**Resuscitation**:

ABC approach. Comment on team coordination and clinical priorities.
**Specific therapy**:

* Pharmacological
	* Adjuvant antibiotics
	* Tetanus booster
* Procedural
	* Early and thorough wound excision and irrigation
	* Delayed primary closure
		* Excepting wounds:
			* To head, neck and genitals\
			Adequate blood supply to permit healing despite contamination.
			* Not penetrating deep fascia
		* Wound inspection every 24-48 hours until debridement completed and wound closed
		* 20% of patients will need ⩾4 procedures
	* Projectiles should only be removed if they are:
		* Easily accessible
		* In joints\
		May cause lead arthropathy.
		* In subarachnoid space\
		Neuronal damage. Notably, projectiles in the brain should not be removed.
		* Source of infection
		* Risking erosion\
		Cardiac, bronchus.
		* Causing persistent pain
* Physical
	* Early physical therapy

**Supportive care**:

**Disposition**:

**Preventative**:


### Marginal and Ineffective Therapies

## Anaesthetic Considerations

## Complications

## Prognosis

## Key Studies


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.