# Burns



>! Emergency Management
>* Remove from heat source
>* Cool the burn  
>Burnt tissue under room temperature water for 20 minutes.

## Epidemiology and Risk Factors

Burns are:

* Common  
~1% of persons.
	* ~10% require hospitalisation

## Pathophysiology

Jacksons Model:

* Zone of coagulation
* Zone of stasis  
Compromised but viable cells.
	* Amenable to treatment
	* Have impaired blood flow
* Zone of stasis loss


Eschar:

* Burnt dermis forming a non-elastic eschar atop of skin
* Circumferential eschar formation leads to compartment syndrome compressing oedematous tissue

Electrical burns:

* High resistance tissues produce excessive heat
	* Bone generates substantial heat  
	Leads to muscular burns, leading to:
		* Rhabdomyolysis
			* Fasciotomy (in addition to escharotomy)


### Aetiology

## Clinical Manifestations


Physiological response:

* Systemic inflammatory response proportional to 

### Burns Assessment

> * Burns are **dynamic** and will evolve and either improve or deteriorate depend on therapy
> * Large burn is >25% BSA

Assess:

* Depth
	* Superficial  
	Epidermal burn.
		* Red and painful
		* Healing within 1 week
		* **Not included** in **BSA calculation**
	* Superficial dermal  
	Dermal burn.
		* **Blistering**
		* Capillary return present
		* Healing is slower
	* Deep dermal
		* Dark red  
		Cooked haemoglobin locked in tissue.
		* May not blister
		* No capillary refill
	* Full thickness
		* White/waxy/charred
		* Insensate  
		**No pain**.
		* No blisters
		* No capillary refill  
		No viable blood vessels.
		* Act as a focus for infection.
* Size  
Remember to exclude superficial burns.
	* Rule of 9's
		* Patient palm is 1%


## Diagnostic Approach and DDx

## Investigations

## Management

> Fluid therapy is lifesaving

Key principles:

* Fluid resuscitation
* Transfer to burns centre
	* ⩾10% BSA full thickness, ⩾5% in children
	* Burns to key areas
		* Face
		* Hands
		* Feet
		* Perineum
	* Electrical and chemical
	* Inhalational injury
	* Circumferential

### Medical

Fluid management:

* Modified Parkland formula  
Most commonly used protocol for burns resuscitation
	* For burns >20% BSA (or 10% in children)
	* 3ml/kg/% BSA burn to calculate first 24/24 fluid requirement
		* Use lactated ringers or CSL
		* Give half over the first **8 hours**
		* **Titrate to urine output**  
		Aim >0.5ml/kg/hr.


* Avoid fluid creep  
	* Excessive volume leads to multiorgan complications
		* Airway occlusion
		* Pulmonary oedema
		* Abdominal compartment syndrome

### Surgical

Escharotomy:

* Cut down to viable tissue
* Can be performed under LA
* Precise location for cut is not essential
* Tissue will 'spring' out as pressure released
* Important in:
	* Limbs  
	Compartment syndrome.
	* Chest  
	Respiratory failure.
	* Abdomen  
	Abdominal compartment syndrome.


Debridement:

* Excision of dead tissue
* Dressings  
**Rapid transfer** to a burns centre, debridement, and dressings will significantly improve outcome.

Grafting:

* Location may be limited by availability of unburned skin
* Own skin may be best
* 'Meshing' skin graft allows graft to be applied to skin in a 4:1 ratio  
Taking skin in a 'chicken-wire' fashion.
	* Skin can be taken every ~2 weeks for harvesting
* Cadaveric skin can be used  
Temporary coverage of burnt areas.
* Artificial substances:
	* Biobrane  
	Silicone and porcine collagen.
		* Temporary dressing for intermediate and deep dermal burns
		* Early application beneficial  
		Reduces tissue damage and systemic inflammatory response.
	* Biodegradable Tissue Matrix


Optimisation and complication management:

* Contracture release
* Cosmesis

### Anaesthetic Considerations

* A
	* **Airway security**  
	May be impossible to get access again.
	* Facial burns
		* Painful mask application
		* NGT/tubes
* B
	* Inhalational injury
* C
	* Arterial line  
	No NIBP on burnt skin.
	* Fluid management
	* IV access
		* Ideally through unburnt skin
* D
	* Analgesia  
	Substantial pain.
		* Multimodal
		* Early anti-neuropathics
		* Single-shot regional ideal
* E
	* **Suxamethonium contraindicated**  
	From 48 hours to 2 years.
	* **Temperature management**
		* Warm theatre  
		28°C.
		* Warming lines
		* Warming CVCs  
		Slow rate of cooling but often unsuccessful warming.
		* Abandon procedure if unmanageable hypothermia (**⩽35°C**)
	* Positioning difficult
* G
	* Hypermetabolic  
	Rapid consumption of neuromuscular blockers.
* H
	* Bleeding can be substantial  
		* Prepare for **massive transfusion**  
		Hard to overtransfuse.
			* Hb >100g/L prior to procedure ideal
			* ABG every half hour to measure Hb
		* **Tumescent preparation**  
		1:500,000 adrenaline infiltrated widely subcutaneously under sites prior to debridement results in substantial reduction in blood loss without adverse effect on graft success.
		* Bleeding will continue post-operatively
	* Coagulopathy
* I
	* Sepsis

### Ineffective Therapies

## Complications

## Prognosis

## Key Studies


---

## References
