# Blunt Cardiac Injury

Traumatic cardiac injuries incldue a spectrum of injuries:

* Minor arrhythmias
* Complex arrhythmias
* Free-wall rupture\
Usually fatal.
* Heart failure
	* Significant muscular injury
	* Septal rupture\
	Left-to-right shunt.
	* Valvular injury\
	Regurgitation.
	* Coronary arterial injury

## Epidemiology and Risk Factors

## Pathophysiology

Injuries occur via a number of different mechanims:

* Compression of the heart between sternum and spine
* Abrupt pressurisation of the cardiac chambers
* Shearing of the heart on the vascular pedicle following rapid deceleration

### Aetiology

## Clinical Manifestations

## Diagnostic Approach and DDx

:::info
Significant injury is rare if:

* Young
* Haemodynamically stable
* Normal ECG
:::

## Investigations




**Bedside**:

**Laboratory**:

**Imaging**:

**Other**:

## Management

**Resuscitation**:\

ABC approach. Comment on team coordination and clinical priorities.
**Specific therapy**:

* Pharmacological
* Procedural
* Physical

**Supportive care**:

**Disposition**:

**Preventative**:


### Marginal and Ineffective Therapies

## Anaesthetic Considerations

## Complications

## Prognosis

## Key Studies


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.