# Diffuse Axonal Injury

Severe TBI secondary to shearing injury of the grey-white matter interface.

## Epidemiology and Risk Factors

## Pathophysiology

The process of injury and subsequent recovery:

* Immediate\
Rotational force leads to axonal stretching and tearing\
	* Concentrated around the grey-white matter interface as:
		* Grey and white matter have slightly different densities
		* Rotational force results in small differences in the velocities of each tissue type
	* Direct synaptic loss
* Hours-days
	* Swelling/Inflammation
		* ↓ CBF due to cerebral oedema and ↑ ICP
		* Induction of apoptosis
			* Axonal degeneration
			* Synaptic loss
	* Direct vascular injury\
	Regional ischaemia.
* Weeks-months
	* Neuroplastic remodelling
	* Apoptotic cell death
* Months-years
	* Further remodelling
	* Cognitive dysfunction
	* HPA dysfunction.


### Aetiology

## Clinical Manifestations

## Diagnostic Approach and DDx

## Investigations

Bedside:

Laboratory:

Imaging:

Other:

## Management

**Resuscitation**:\


**Specific therapy**:

* Pharmacological
* Procedural
* Physical

**Supportive care**:

**Disposition**:

### Marginal and Ineffective Therapies

## Anaesthetic Considerations

## Complications

## Prognosis

## Key Studies


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.