# Inhalational Injury

Injury can occur due to inhalation of:

* **Hot gases**\
Rarely extend beyond the larynx, as gas is rapidly humidified and cooled by airway mucosa. Early intubation prior to laryngeal oedema formation is recommended.
* **Steam and liquids**\
Involve the lower airway as heat exchange mechanisms are insufficient.
* **Chemical smoke**\
Chemical injury and toxidromes from toxic smoke, classically due to exposure in a confined space.

:::column-margin
Cyanide and carbon monoxide may both be produced during combustion, and may occur during inhalation in a confined space. They are covered in detail under @sec-cyanide and @sec-carbon_monoxide.
:::

## Epidemiology and Risk Factors

Inhalational injury:

* 20% of burns
	* 60% of facial burns


## Pathophysiology

Toxic injury:

* Tracheobronchial oedema
* Cast formation
* Small airway collapse\
Hypoxic respiratory failure.

	
### Aetiology

## Clinical Features

### History

* Fuel
* Enclosed\
Risk of:
	* CO toxicity
	* CN poisoning
* Duration
* Loss of consciousness


### Examination

:::column-margin
All clinical signs are non-sensitive and non-specific.
:::

* Singed nasal hairs
* Blisters in mouth
* Voice changes/hoarseness
* Sooty sputum


## Diagnostic Approach and DDx

## Investigations

**Bedside**:

**Laboratory**:

**Imaging**:

**Other**:


## Management

**Resuscitation**:

:::column-margin
Inflammation will get worse in the first few hours, particularly once fluid resuscitation commences.
:::

* A
	* Secure airway if in doubt\
	Especially in Australia, where retrieval times are long.
	* Place a normal size tube\
	Long duration of intubation is expected, and large ETT ↑ risk of vocal cord granuloma.
* B
	* Supplemental oxygen

**Specific therapy**:

* Pharmacological
* Procedural
	* Bronchoscopic toileting
		* Daily to clear debris and ↓ infection
* Physical

**Supportive care**:

**Disposition**:

**Preventative**:


### Anaesthetic Considerations

### Marginal and Ineffective Therapies

## Complications

* Toxin
	* Carbon monoxide poisoning
	* Cyanide poisoning

## Prognosis

Leads to ↑↑ burns mortality.

## Key Studies


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.