# Liver Trauma

Liver trauma has high potential for morbidity and mortality due to both massive haemorrhage and risk of delayed complications, and is graded:

* **Grade I**
	* Subcapsular haematoma <10% of surface area
	* Laceration <1cm deep
* **Grade II**
	* Subcapsular haematoma 10-50% of surface area
	* Intraparenchymal haematoma <10cm
	* Laceration 1-3cm deep
* **Grade III**
	* Subcapsular haematoma >50% of surface area
	* Intraparenchymal haematoma >10cm
	* Laceration >3cm deep
	* Vascular injury with bleeding contained within parenchyma
* **Grade IV**
	* Laceration with parenchymal disruption of 25-75% hepatic lobe or 1-3 segments
	* Vascular injury with bleeding into the peritoneum
* **Grade V**
	* Laceration with >75% of parenchymal disruption
	* Juxtahepatic venous injury

## Epidemiology and Risk Factors

## Pathophysiology

### Aetiology

## Clinical Manifestations

## Diagnostic Approach and DDx

## Investigations

**Bedside**:

**Laboratory**:

**Imaging**:

**Other**:

## Management

:::priority
Majority are managed non-operatively.
:::

**Resuscitation**:



**Specific therapy**:

* Pharmacological
* Procedural
* Physical

**Supportive care**:

**Disposition**:

**Preventative**:


### Marginal and Ineffective Therapies

## Anaesthetic Considerations

## Complications 

Rate associated with ↑ grade of injury:

* G
	* Hepatic necrosis
	* Hepatic abscesses
	* Bile leak
	* Acalculous cholecystitis
	* Delayed haemorrhage

## Prognosis

## Key Studies


---

## References