# Pelvic Fractures

Pelvic trauma is associated with high-energy mechanisms and major haemorrhage. Pelvic fractures are classified by the nature of force into:

* **Lateral compression**\
Lateral force.
	* Grade I\
	Stable.
		* Oblique or transverse ramus fracture
		* Ipsilateral sacral ala compression fracture
	* Grade II\
	Rotationally unstable, vertically stable.
		* Rami fracture
		* Ipsilateral posterior ilium fracture-dislocation
	* Grade III\
	Completely unstable.
		* Grade II with anteroposterior compression fracture on contralateral side
* **Anteroposterior compression**\
Anterior or posterior force. Leads to open-book or sprung pelvis fractures, and divided into:
	* Grade I\
	Stable.
		* Symphysis widening <2.5cm
	* Grade II\
	Rotationally unstable, vertically stable.
		* Symphysis widening >2.5cm
		* Diastasis of anterior SI joint
		* Intact posterior SI ligaments
	* Grade III\
	Completely unstable.
		* Disruption of anterior and posterior SI ligaments
		* Associated vascular injury
* **Vertical shear**\
Vertical force; typically falls from height or MVA. Completely unstable.
* **Combined mechanism**\
Completely unstable. Injuries that do not fit into the above classification.


## Epidemiology and Risk Factors

## Pathophysiology

### Aetiology

## Clinical Manifestations

## Diagnostic Approach and DDx

## Investigations

**Bedside**:

**Laboratory**:

**Imaging**:

**Other**:

## Management

**Resuscitation**:


**Specific therapy**:

* Pharmacological
* Procedural
* Physical

**Supportive care**:

**Disposition**:

**Preventative**:


### Marginal and Ineffective Therapies

## Anaesthetic Considerations

## Complications

## Prognosis

## Key Studies


---

## References