# Rib Fractures

* Pain\
Analgesia is the mainstay of treatment, with the goal of facilitating deep breathing and coughing to avoid secondary pulmonary complications.
* Flail chest\
**Four consecutive rib fractures in ⩾2 places** results in a **free segment** of the chest wall which **moves paradoxically** during negative-pressure ventilation.
	* May cause some primary respiratory defect
	* Commonly associated with underlying pulmonary contusion\
	This may cause significantly impaired gas exchange, and is probably the major driver of any respiratory impairment (rather than mechanical inefficiency).


## Epidemiology and Risk Factors

## Pathophysiology

### Aetiology

## Clinical Manifestations

## Diagnostic Approach and DDx

## Investigations

**Bedside**:

**Laboratory**:

**Imaging**:

**Other**:

## Management

**Resuscitation**:

**Specific therapy**:

* Pharmacological
* Procedural
* Physical

**Supportive care**:

**Disposition**:

**Preventative**:


### Marginal and Ineffective Therapies

## Anaesthetic Considerations

## Complications

## Prognosis

## Key Studies


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.