# Traumatic Brain Injury {#sec-trauma_tbi}

**Spectrum** of **brain injury** due to **cerebral oedema** and **impaired autoregulation**, classified by:

* **Severity**
	* Mild\
	GCS 13-15.
		* 70-80% of all TBI.		
		* Brief loss of consciousness
	* Moderate\
	GCS 9-12 after resuscitation
	* Severe\
	GCS ⩽8 after resuscitation
* **Timing**
	* **Primary brain injury**\
	Neuronal death from the initial trauma.
		* Major determinant of outcome
		* Relatively untreatable
	* **Secondary brain injury**\
	Additional harm that occurs due to post-injury insults.

:::column-margin
Primary brain injury is the damage done when the head hits the windscreen, secondary brain injury is everything that happens afterwards. Good prehospital, ED, and ICU care involves minimising secondary brain injury, since this the time when we can intervene.
:::

## Epidemiology and Risk Factors

TBI is the:

* Leading cause of death in <45 year olds
	* ↑ In males

## Pathophysiology

**Primary brain injury**:

* Can involve various physical mechanisms:
	* Impact loading\
	Collision of head with object.
	* Impulsive loading\
	Sudden change in motion without physical contact
	* Static loading\
	Force where speed of occurrence is not significant.
	* Rotational shearing\
	Leads to axonal stretching and tearing\
		* Concentrated around the grey-white matter interface as:
			* Grey and white matter have slightly different densities
			* Rotational force results in small differences in the velocities of each tissue type
* Occurs due to brain deformation via:
	* Compression
	* Stretch
	* Shearing
* Results in a constellation of effects:
	* Inflammation\
	Leads to **cerebral oedema** via:
		* Altered blood-brain barrier permeability
		* Direct neuronal injury
		* Microvascular injury
	* Haemorrhage\
	Micro and macrovascular haemorrhage:
		* Extra-axial haemorrhage
			* EDH
			* SDH
		* Intra-axial haemorrhage
			* SAH
			* Contusions
	* Sympathetic surge


**Secondary brain injury** occurs due to:

:::column-margin
Physiological derangements from other traumatic injuries will compound to further worsen secondary brain injury.
:::

* Cerebral ischaemia
	* ↓ CPP
		* Hypotension
			* Hypovolaemia
			* Shock
		* ↑ ICP
			* Cerebral oedema
			* Mass effect		
	* Hypoxaemia
		* Pulmonary injury
		* Neurogenic pulmonary oedema
	* Direct vascular injury\
	Regional ischaemia.
* Impaired cerebral autoregulation
	* Hyper/hypocarbia
	* Hypo/hyperthermia
* Induction of apoptosis
	* Axonal degeneration
	* Synaptic loss


Medium to long-term effects occur over:

* Weeks-months
	* Neuroplastic remodelling
	* Apoptotic cell death
* Months-years
	* Further remodelling
	* Cognitive dysfunction
	* HPA dysfunction.


### Aetiology

Primary brain injury causes include:

* Falls\
Most common.
* MVA\
Most common cause of death.
* Violence
	* NAI
	* Domestic violence
	* Elder abuse
* Industrial accidents
* Sport

: Drivers of Secondary Brain Injury

+----------------------+-----------------------------+
| Systemic             | Intracranial                |
+======================+=============================+
| * ↓ O~2~ (<90%)      | * Seizure                   |
| * ↓ SBP (<90mmHg)    | * Intracranial haematoma    |
| * ↑/↓ CO~2~          | * SAH\                      |
| * ↑/↓ Temperature    | Delayed cerebral ischaemia. |
| * ↑/↓ BSL            | * Hydrocephalus\            |
| * ↑/↓ Na^+^          | \                           |
| * ↑ Osmoles\         | * Intracranial infection    |
| \                    |                             |
| * Systemic infection |                             |
+----------------------+-----------------------------+


## Clinical Manifestations

Features include:

* Nausea/vomiting
* Cognitive dysfunction
* Behavioural change
* Obtundation → coma


Examination:

* ↑ Pupil size and ↓ reactivity suggest ↑↑↑ ICP with impending herniation

## Diagnostic Approach and DDx

## Investigations

**Bedside**:

**Laboratory**:

**Imaging**:

* CT
	* Goals:
		* **Exclude** a neurosurgically **correctable mass lesion**
		* Grade injury\
		Commonly used classification systems include:
			* Marshall
			* Rotterdam
	* Findings:
		* DAI
		* Cerebral contusion
		* Hydrocephalus
		* Traumatic SAH/EDH/SDH
* MRI\
Not indicated routinely in the acute phase. Role in:
	* Neuroprognostication of DAI
	* Identification of intracranial vascular injury

:::column-margin
Because EVD and ICP monitors are contraindications to MRI; MRI is only able to be performed after these have been removed (generally 7 days) and so delayed prognostication is normal.
:::

### Marshall Classification

Grades injury into **six categories** by degree of swelling or presence of contusions.

:::column-margin
High/mixed density lesions refers to haemorrhage.
:::

: Marshall Classification of TBI

+-------+---------------------------------------------------------------+
| Grade | Findings                                                      |
+=======+===============================================================+
| I     | * No visible pathology                                        |
+-------+---------------------------------------------------------------+
| II    | * Basal cisterns present with <5mm midline shift              |
|       | * Density (contusion) present\                                |
|       | * No high/mixed density >25mm                                 |
|       | * Bony fragments/foreign body                                 |
+-------+---------------------------------------------------------------+
| III   | * Compressed or absent basal cisterns with <5mm midline shift |
|       | * No high/mixed density >25mm                                 |
+-------+---------------------------------------------------------------+
| IV    | * Midline shift >5mm                                          |
|       | * No high/mixed density >25mm                                 |
+-------+---------------------------------------------------------------+
| V     | * Evacuated mass lesion\                                      |
|       | i.e Lesion that required surgery.                             |
+-------+---------------------------------------------------------------+
| VI    | * Non-evacuable mass lesion\                                  |
|       | High/mixed density lesions >25mm.                             |
+-------+---------------------------------------------------------------+


### Rotterdam Classification

: Rotterdam Classification of TBI

+----------------------+---------------+
| Region               | Score         |
+======================+===============+
| Basal Cisterns       | 0. Normal     |
|                      | 1. Compressed |
|                      | 2. Absent     |
+----------------------+---------------+
| Midline Shift        | 0. Shift <5mm |
|                      | 1. Shift >5mm |
+----------------------+---------------+
| Epidural mass lesion | 0. Present    |
|                      | 1. Absent     |
+----------------------+---------------+
| IVH or SAH           | 0. Absent     |
|                      | 1. Present    |
+----------------------+---------------+

Rotterdam score correlates with six-month mortality in adults and children. In adults the sum score + 1 gives a mortality:

* 1. 0%
* 2. 7%
* 3. 16%
* 4. 26%
* 5. 53%
* 6. 61%


**Other**:

## Management

:::priority
* Correct hypoxia
* Maintain **cerebral perfusion**
* **↓ ICP**
* Identification and treatment of other traumatic injuries
* Transfer to a neurotrauma centre
:::

**Resuscitation**:

:::column-margin
This covers brain-specific resuscitation; the principles of Damage Control Resuscitation are covered under @sec-trauma_primary.
:::

* A
	* **Intubation**
		* Coma
		* Marked agitation
		* Significant extracranial trauma
* B
	* Normal **O~2~**\
	PaO~2~ 80-100mmHg.
	* Low-normal **CO~2~**\
	PaCO~2~ 35-40mmHg.
	* Lung protective ventilation\
	PEEP of 5-10cmH~2~O is appropriate; ↑↑ PEEP will ↑ CVP and ↓ cerebral venous return.
* C
	* Defend **cerebral perfusion**
		* Target SBP or CPP:\
		SBP should be targeted if ICP is not monitored, otherwise target CPP.
			* SBP target varies with age:
				* <50: SBP >110
				* 50-69: SBP >100
				* \>70: SBP >110
			* Aim **CPP 60-70mmHg** if **ICP >15mmHg**\
			Can be relaxed after 72 hours as the brain enters a hyperaemic phase, although ICP <22mmHg should still be defended.
		* Correct hypovolaemia with blood or crystalloid
		* Vasopressors appropriate once volume resuscitated
	* Invasive arterial monitoring
* D
	* **ICP monitoring** and **treatment**
		* Indicated for:
			* Severe TBI (GCS ⩽8) with:
				* Abnormal CT scan\
				Swelling, ICH, hydrocephalus, herniation.
				* Normal CT scan but ⩾2 of:
					* Age >40
					* Motor posturing
					* SBP <90mmHg
			* Moderate TBI and unable to assess neurology\
			Discuss with neurosurgical team.
		* If monitored, ICP should be kept **<22mmHg**
		* Monitoring should occur for 72 hours - 1 week\
		Duration should be guided by neurosurgery and depends on:
			* ICP stability
			* Amount of ICP intervention needed
			* CT findings
			* Premorbid motor score
			* Pupils


**Specific therapy**:

:::column-margin
Details of **ICP management including indications** and **treatment of ↑ ICP** is covered under @sec-icp.
:::

* Pharmacological
	* ICP interventions
* Procedural
	* Evacuation of extra-axial haemorrhage
	* CSF drainage
	* Decompressive **craniectomy**
		* Primary (early) decompressive craniectomy
			* Removal of bone flap during initial evacuation of mass lesion
			* Has a defined role in specific clinical scenarios:
				* Small acute SDH with overly-proportional midline shift
				* Acute SDH with cerebral contusions or pupillary abnormalities
				* Intraoperative ↑ ICP
				* Coagulopathy
		* Secondary (late) decompressive craniectomy
			* Removal of bone flap for refractory ↑ ICP
			* ↓↓ Mortality but ↑ morbidity in survivors
			* Has a *possible* role in TBI
* Physical
	* Head of bed elevation


:::column-margin
Late decompressive craniectomy results in:

* Significantly ↑ number and disability of survivors
* A greater number of survivors with a "favourable" outcome\
Favourable is upper severe disability (see prognosis), or better.
* A significantly greater number of survivors with severe disability or vegetative state. 
:::


**Supportive care**:

:::column-margin
Basic supportive care is also known as Tier 0 therapy, and should be performed for all patients independently of ICP.
:::

* A
	* Intubation and mechanical ventilation
	* **Tracheostomy**\
	Timing is controversial but is generally late as there is no clear benefit for early tracheostomy. Can be considered:
		* \>7 days once severe TBI treatment is completed
		* Neuroprognostic workup completed
		* Patient has either:
			* Reasonable chance of recovery to acceptable quality of life
			* Require rehabilitation but are unable to protect their away
* B
	* **Avoid hypoxia**\
	Target SpO~2~ >95%.
		* Supplemental oxygen as first line 
		* PEEP\
		Concern about ↑ ICP due to ↑ CVP, however adequate oxygenation takes priority.
* C
	* Arterial line monitoring
* D
	* Sedation and analgesia\
	For comfort and ventilator synchrony.
	* **Seizure prophylaxis**\
	Can be considered to prevent early (<7 days) seizures.
	* **Head-up positioning**\
	Head of bed elevated to 30-35°C to ↑ cerebral venous drainage.
* E
	* **Temperature management**\
	Normothermia (35.5-36.5°C) should be maintained.
* F
	* **Avoid hyponatraemia**
* H
	* **Hb >70g/L**
	* **Thromboprophylaxis**\
	Difficult balance due to ↑ risk of thromboembolic events in TBI and bleeding risk of concomitant ICH. Consider:
		* Pneumatic calf compressors in patients without lower limb fractures
		* Regular (e.g. twice weekly) lower limb DVT ultrasound
		* Pharmacoprophylaxis in all patients unless:
			* ICH\
			Timing of pharmacoprophylaxis is based on risk-benefit. In general:
				* Discuss with neurosurgical team
				* Consider re-CT before or after commencing to evaluate for interval change
				* Consider IVC filter if long-term contraindication to anticoagulation
			* Destructive pathology
			* ICP monitor or EVD in situ
		* IVC filter in patients who cannot be anticoagulated and have ↑↑↑ risk of DVT, e.g. pelvic or lower limb fractures


**Disposition**:

* Neurotrauma centre\
All severely TBI should be managed at a specialist neurotrauma centre.


**Preventative**:



### Marginal and Ineffective Therapies

* Therapeutic hypothermia\
No benefit in favourable neurological outcomes, with ↑ pneumonia and bradycardia.
* Colloid fluid\
Associated with ↑ mortality.
* Hypotonic crystalloids\
Worsen cerebral oedema.
* Steroids

:::column-margin
Hartmann's and lactated Ringer's are hypotonic and should also be avoided.
:::

## Anaesthetic Considerations

## Complications

* B
	* Neurogenic pulmonary oedema\
	Sudden onset of pulmonary oedema due to ↑↑ sympathetic tone, classically **2-8 hours** following head injury.
	* Pneumonia\
	HAP/VAP, secondary to prolonged hospital stay.
* D
	* Hyperglycaemia
	* Critical neuroworsening
	* Cerebral herniation\
	Should be treated immediately with:
		* Hyperventilation
		* Osmotherapy
	* Post-traumatic amnesia\
	Transitory state between coma and return of full consciousness, that may last from minutes to many months.
	* Acquired Brain Injury
* G
	* Feeding\
	Basal feeding should be established by day 5.
* H
	* DVT/PE

:::column-margin
ABI covered in more detail under @sec-abi.
:::


### Critical Neuroworsening

A sudden deterioration in neurological state is defined as new:

* Spontaneous ↓ in GCS by ⩾1 point
* ↓ Pupillary reactivity
* Pupillary asymmetry or mydriasis
* Focal deficit
* Herniation syndrome
* Cushing's triad


Causes include:

* Neurological
	* Mass lesion
	* Oedema
	* CVA
	* Seizure/post-ictal
	* CNS infection
	* Substance withdrawal
* CVS
	* Hypotension
	* Hypovolaemia
* Metabolic
	* Electrolyte disturbance
	* ↓ Renal function
	* ↓ Hepatic function
	* Hypothermia


Management requires:

* Very low threshold for repeat CT brain
* Rapid ↑ in ICP therapy



## Prognosis

Neuroprognostication itself exceedingly difficult, and made more complex as many patients will exhibit very slow improvement. Poor prognostic factors include:

* Age
* Severity of injuries
* CT findings
* Hyperglycaemia
* Hypothermia
* **Hyperthermia**

:::column-margin
{{< include /includes/gos-e.qmd >}}
:::

Of patients hospitalised with TBI, at 12 months:

* 27% have died
* 42% have moderate or severe disability
* 15% of remainder had persistent disability


Risk factors for post-traumatic epilepsy:

* GCS <10
* Haemorrhage\
EDH, SDH, ICH, contusion.
* Depressed skull fracture
* Penetrating head wound
* Seizure within 24 hours of injury


## Key Studies

**Decompressive Craniectomy**:

{{< include /trials/decra.qmd >}}
{{< include /trials/rescue_icp.qmd >}}

**Other**:

{{< include /trials/polar.qmd >}}
{{< include /trials/cobi.qmd >}}
{{< include /trials/crash.qmd >}}
{{< include /trials/crash3.qmd >}}


---

## References

1. Maas AIR, Hukkelhoven CWPM, Marshall LF, Steyerberg EW. [Prediction of Outcome in Traumatic Brain Injury with Computed Tomographic Characteristics: A Comparison between the Computed Tomographic Classification and Combinations of Computed Tomographic Predictors: Neurosurgery](https://journals.lww.com/neurosurgery/Abstract/2005/12000/Prediction_of_Outcome_in_Traumatic_Brain_Injury.14.aspx). 2005 Dec;57(6):1173–82. 
1. Carney N, Totten AM, OʼReilly C, et al. Guidelines for the Management of Severe Traumatic Brain Injury, Fourth Edition: Neurosurgery. Published online September 2016:1. 
1. Hawryluk GWJ, Rubiano AM, Totten AM, et al. [Guidelines for the Management of Severe Traumatic Brain Injury: 2020 Update of the Decompressive Craniectomy Recommendations](www.doi.org/10.1093/neuros/nyaa278). Neurosurgery. 2020;87(3):427-434.
1. Carney N, Totten AM, OʼReilly C, et al. [Guidelines for the Management of Severe Traumatic Brain Injury, Fourth Edition: Neurosurgery](www.doi.org/10.1227/NEU.0000000000001432). Published online September 2016:1.
1. Cooper DJ, Rosenfeld JV, Murray L, et al. [Decompressive Craniectomy in Diffuse Traumatic Brain Injury](https://www.nejm.org/doi/full/10.1056/NEJMoa1102077). New England Journal of Medicine. 2011;364(16):1493-1502. doi:10.1056/NEJMoa1102077
1. Hawryluk GWJ, Aguilera S, Buki A, et al. [A management algorithm for patients with intracranial pressure monitoring: the Seattle International Severe Traumatic Brain Injury Consensus Conference (SIBICC)](https://link.springer.com/article/10.1007/s00134-019-05900-x). Intensive Care Med. 2019;45(12):1783-1794. doi:10.1007/s00134-019-05805-9
1. Effect of Continuous Infusion of Hypertonic Saline vs Standard Care on 6-Month Neurological Outcomes in Patients With Traumatic Brain Injury: The COBI Randomized Clinical Trial | Acid Base, Electrolytes, Fluids | JAMA | JAMA Network. Accessed June 12, 2023. https://jamanetwork.com/journals/jama/article-abstract/2780326
1. Cooper DJ, Nichol AD, Bailey M, et al. [Effect of Early Sustained Prophylactic Hypothermia on Neurologic Outcomes Among Patients With Severe Traumatic Brain Injury: The POLAR Randomized Clinical Trial](https://jamanetwork.com/journals/jama/fullarticle/2710778). JAMA. 2018;320(21):2211. doi:10.1001/jama.2018.17075
1. Hutchinson PJ, Kolias AG, Timofeev IS, et al. [Trial of Decompressive Craniectomy for Traumatic Intracranial Hypertension](http://www.nejm.org/doi/pdf/10.1056/NEJMoa1605215). N Engl J Med. 2016;375(12):1119-1130. doi:10.1056/NEJMoa1605215
1. [Effect of intravenous corticosteroids on death within 14 days in 10 008 adults with clinically significant head injury (MRC CRASH trial): randomised placebo-controlled trial](https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(04)17188-2/fulltext). The Lancet. 2004;364(9442):1321-1328. doi:10.1016/S0140-6736(04)17188-2