# Adrenalectomy


>Airway: ETT <br>
>Access: 14G IV x2.
>Pain: Consider epidural if open. <br>
>Position: Variable, but most commonly lateral <br>
>Time: 1-2 hours <br>
>Blood loss: May be substantial with right adrenal tumours due to IVC proximity <br>
>Special: Preoperative diagnosis critical to preparation. Labile BP with manipulation of adrenal gland <br>

Removal of the adrenal glands can be performed:

* Open
	* Transperitoneal\
	Used for large tumours; provides easy access to both glands. Prone, jacknife.
	* Flank\
	Subcostal incision, remains extraperitoneal - reduces pain. Supine.
* Laparoscopic
	* Anterior\
	Allows bilateral adrenalectomy. Supine.
	* Lateral\
	**Commonest approach**. Lateral decubitus with bed broken.
	* Retroperitoneal\
	Avoids peritoneal cavity. Prone.


## Considerations

* Preoperative diagnosis\
Significantly affects pre-operative management.
	* Aldosteronoma
	* [Phaeochromocytoma](/disease/endo/phaeo.md#mx)\
	Ensure adequate control of haemodynamic state prior.
	* Cortisol-producing tumour
	* Non-functioning lesion
	* Metastasis
	* Adrenocortical carcinoma


## Preparation

* Standard ANZCA monitoring
* Epidural awake\
If being used.
* Arterial line\
Femoral preferred for better monitoring of central pressures.
* CVC\
If any possibility of requiring adrenaline/noradrenaline.
* PAC/TOE\
Consider for phaeochromocytoma with impaired cardiac function.


## Induction

* Gentle IV induction with paralysis\
Consider intubation with 3-5μg/kg fentanyl and 50mg/kg MgSO~4~, followed by MgSO~4~ infusion at 1-2g/hr.
* Ensure adequate depth prior to stimulation


## Intraoperative

* Volatile/opioid/relaxant
* Consider continuous epidural infusion

Control of **hypertension**:

* Ask surgeon to cease manipulating adrenal gland
* Phentolamine 1-2mg IV, up to 5mg boluses\
Reversible non-selective α-antagonist. Short duration of action; may demonstrate tachyphylaxis.
	* Can be used as a sole agent
	* Useful to control BP surges\
	Behaviours similar to reverse metaraminol.
	* Can be used by infusion at 0.5-1mg/min
* Labetalol 5-20mg IV\
Combined α- & β-antagonist. 
* SNP 0.5-1.5μg/kg/min, up to 4μg/kg/min\
* GTN 0.5-10μg/kg/min
* MgSO~4~ 1-2g IV
* Nicardipine\
If in America.

Control of **arrhythmia**:

* Esmolol 0.5mg IV, with infusion at 50μg/kg/min  \
For reflex tachycardia.
* Amiodarone\
For ectopy.


Control of **hypotension**:

* Occurs in 20-70%\
Particularly post tumour ligation.
* Stop infusions
* Fluid load
* Commence noradrenaline
* Consider vasopressin
	* 0.4-20 units
	* Infusion to follow


### Surgical Stages

* Incision may be excessively stimulating
* Insufflation may cause hypertension\
Tumour compression, altered tumour blood flow, sympathetic response to hypercapnoea.
* Ensure good control of blood pressure prior to tumour handling
* Manipulation of the adrenal gland may cause catecholamine release\
**Significant hypertension** and **dysrhythmia** may occur.
* Following clamping of vein and removal of adrenal gland, significant hypotension occurs\
Anticipate:
	* Fluid load
	* Adrenaline infusion for ↓ CO
	* Vasopressin/noradrenaline if ↓ MAP with normal or ↑ CO\
	Vasopressin is useful for treating catecholamine-resistant hypotension.
	* Often **more difficult to manage** than the hypertension prior\
	Have vasopressors prepared.

## Emergence

* Extubation dependent on haemodynamic stability


## Postoperative

Key considerations:

* B
	* May required post-operative ventilation
* C
	* Invasive monitoring\
	Require at least 24 hours of HDU monitoring post-operatively.
	* **Haemodynamic instability**
		* Risk factors
			* High plasma noradrenaline levels
			* Large tumour size
			* Large postural drop
			* Pre-induction MAP >100mmHg
		* Hypotension\
		May have ongoing vasopressor/inotrope requirements.
		* Hypertension
			* Acute hypertension usually due to pain, pre-existing essential hypertension, urinary retention, or volume overload
			* Persistent post-operative hypertension may indicate incomplete resection
* D
	* Return to normal insulin sensitivity\
	Hypoglycaemia can occur from relative insulin excess; monitor Q2H.
* E~2~
	* Hypoadrenocorticism
		* Usually only occurs if bilateral resection
		* Requires gluco/mineralocorticoid replacement\
		Commence hydrocortisone 100mg Q8H, weaning to 25mg BD over first 72/24 post-op; and then usually conveted to prednisolone.



---

## References

1. Connor D, Boumphrey S. [Perioperative care of phaeochromocytoma](https://academic.oup.com/bjaed/article/16/5/153/2389873). BJA Educ. 2016 May 1;16(5):153–8. 
