# Thyroidectomy

>Airway: ETT <br>
>Access: ~18G IV <br>
>Pain: Simple analgesia and PRN opioid usually adequate <br>
>Position: Supine with neck extended. <br>
>Time: 1-3 hours. <br>
>Blood loss: Low. <br>
>Special: Use of intraoperative nerve monitoring for laryngeal nerve preservation requires use of a specialised ETT, and absence of muscle relaxation. <br>


Removal of thyroid gland, usually by transverse neck incision. Performed for:

* Cancer
	* Adenomas
* Goitre
	* Grave's disease
	* Recurrent hyperthyroidism
	* Hashimoto's thyroiditis
	* Cosmetic

## Considerations

* A
	* Goitre
		* Retrosternal
			* ⩾50% of goitres are retrosternal  
			Associated with increased rate of complications.
			* 90% have airway issues
			* 1/3<sup>rd</sup> have dysphagia.
	* Anatomical distortion  
	Difficult airway in 6%.
		* Tracheomalacia
		* Swallowing difficulty
			* Meat/bread  
			Some sort of impingement.
			* Liquids
			* Secretion control  
			Inability to control saliva/respiratory secretions indicates significant dysfunction.
		* Consider nasoendoscopy for baseline cord function
	* Airway plan  
	Particularly afterwards. Plan for:
		* Minimising coughing
		* Recurrent laryngeal nerve palsy
		* Vocal change
	* Use of NIM tube  
	ETT with built-in electrodes to monitor integrity of recurrent laryngeal nerves.
		* Surgeon identifies RLN with current of 0.2-2mA, which will stimulate cord movement  
		* Cord movement generates an electrical signal in the tube which is read on the monitor
		* Reduce incidence of neuropraxia but not of long term RLN injury  
			* Technical factors
			* Increased external diameter of tube  
			Minimum of 8.8mm OD.
			* Cannot be placed nasally
			* Requires stylet or FOI
			* Requires precise positioning; VL is helpful  
			Electrodes must straddle cords. 
			* Certain blocks will limit efficacy:
				* Nebulised lignocaine
				* Trans-tracheal lignocaine
				* Superior LN blocks
			* Avoid muscle relaxation during dissection  
			Remifentanil, atracurium, or rocuronium/sugammadex for intubation.
* B
	* Obesity
* C
	* AF or CHF  
	If hyperthyroid.
* D
	* Use of nerve monitoring
* E
	* Thyroid state  
	Requires euthyroid state. Evaluate:
		* Normal T<sub>4</sub>/T<sub>3</sub>
		* Normal temperature
		* Normal HR, BP, pulse pressure
		* Normal reflexes
	* Electrolytes  
	Notably **hypocalcaemia**.


## Preparation

## Induction

* Standard induction
* Shorter acting neuromuscular blockers should be used if using nerve integrity monitoring

## Intraoperative

* Ensure depth of anaesthesia adequate, particularly if incompletely treated hyperthyroidism


### Surgical Stages

* Skin incision
* Platsyma divided
* Subplatysmal flaps developed
	* Anterior jugular veins avoided
* Prethyroid fascia divided in midline
* Thyroid gland resected  
Depends on diagnosis.
	* Total
	* Subtotal  
	Lobe, isthmus, +/- part of remaining lobe.
	* Lobar
* Identification and preservation of the:
	* Parathyroid glands
	* Recurrent laryngeal nerve(s)
* Excision of lymph nodes

## Postoperative

Immediate serious post-operative complications include:

* Recurrent laryngeal nerve damage
	* Bilateral  
	Vocal cords adducted.
		* Unable to speak
		* Requires reintubation  
		CPAP may temporise by splinting open cords.
	* Unilateral  
	3-4%; hoarse voice.
* Tracheomalacia  
Acute upper airway obstruction due to tracheal collapse.
	* Requires emergent reintubation or tracheostomy
	* Largely a historical remnant  
	Risk is exceedingly rare in modern practice.
	* Suggested by no cuff leak prior to extubation
	* Risks may include:
		* Duration of goitre
		* Retrosternal extension of goitre
		* Significance of extrinsic compression  
		Tumour; may also include bronchogenic carcinoma or aortic aneurysm.
* Haematoma/Oedema  
Occurs in 1-2%, and expansion may lead to airway compromise.
	* Rapidly reopen incision and drain remaining blood
	* Consider CPAP to temporise airway
	* Reintubation may be required immediately, or delayed (on return to theatre)



Delayed complications include:

* Hypoparathyroidism  
Inadvertent removal of parathyroid glands leading to acute fall in PTH and **hypocalcaemia**:
	* Occurs in ~20% of patients, with 3.1% being permanent
	* Presents as:
		* Laryngeal stridor
		* Tingling/numbness
		* Tetany
		* Seizures
	* Treated with calcium supplementation  
	e.g. 10mL calcium gluconate IV.


---

## References

1. Findlay, J.M., G.P. Sadler, H. Bridge, and R. Mihai. ‘Post-Thyroidectomy Tracheomalacia: Minimal Risk despite Significant Tracheal Compression’. British Journal of Anaesthesia 106, no. 6 (June 2011): 903–6. https://doi.org/10.1093/bja/aer062.
2. Atlas G, Lee M. The neural integrity monitor electromyogram tracheal tube: Anesthetic considerations. J Anaesthesiol Clin Pharmacol. 2013;29(3):403-404. doi:10.4103/0970-9185.117052
