# Anaphylaxis

:::info
This covers both perioperative and non-perioperative anaphylaxis. Treatment recommendations for perioperative anaphylaxis are detailed separately, due to the nature of the disease (typically of more rapid onset and aggressive progression), and the immediate availability of resuscitation equipment and personnel.
:::

Anaphylaxis is a serious and **life-threatening** generalised Type 1 **hypersensitivity reaction** characterised by a **triad** of:

* **Hypotension**
* **Bronchospasm**
* **Rash**


## Epidemiology and Risk Factors

Triggers of non-perioperative anaphylaxis:

* Food
	* 60% of anaphylaxis in children
	* 16% of anaphylaxis in adults
* Insect venoms
	* 16% of anaphylaxis in children
	* 55% of anaphylaxis in adults
* Drugs
	* 8% of anaphylaxis in children
	* 21% of anaphylaxis in adults


### Perioperative Anaphylaxis

Epidemiology:

* 56% female
* Overall less common in paediatrics
	* May be due to less use of antibiotics and muscle relaxants
	* More likely to present with bronchospasm


## Pathophysiology

Anaphylaxis may be:

* Immune mediated
	* IgE mediated:
		* Allergen-specific IgE binding to high-affinity receptors on mast cells and basophils
		* Contact with allergen with **multiple** specific IgE receptors on the cell surface\
		Interaction with multiple receptors is termed **cross-linking**, and key to initiating intracellular signaling.
		* Degranulation cells occurs, leading to release of a vast number of mediators:
			* **Histamine**\
			Principle mediator of initial cardiovascular effects.
			* Prostaglandins
			* Leukotrienes
			* Tryptase
			* Platelet-activating factor
			* Cytokines
			* Chemokines
	* Immune complex mediated
* Non-immune mediated
	* Describes a clinical appearance of anaphylaxis where immunological sensitisation has not been detected
	* Probably relates to G-protein induced release of vasoactive mediators


### Aetiology

Perioperative anaphylaxis:

* ~46% are antibiotic associated\
Teicoplanin and amoxacillin-clavulanate have the highest risk.
* ~33% are related to neuromuscular blocking drugs
	* Suxamethonium: ~11/100,000
	* Rocuronium: 6/100,000
	* Atracurium: 4/100,000
* ~10% chlorhexidine\
Typically presents more slowly, unless IV (i.e. chlorhexidine-impregnated CVC) source.
	* ↑ incidence due to ↑ use
	* An untested patient with a history of perioperative anaphylaxis should be managed as having chlorhexidine hypersensitivity
* Patent Blue die\
Highest risk single therapy at ~15/100,000.
	* May present with blue urticaria


All causes:

* Food
	* 90% from 8 groups
		* Persistent into adulthood
			* Peanuts
			* Tree nuts
			* Fish
			* Crustacea
		* Paediatric\
		Tend to resolve in teens.
			* Milk
			* Egg
			* Wheat
			* Soy
	* Red meat
* Latex\
Associated with cross-reactivity to many fruits:
	* Avocado
	* Banana
	* Chestnut
	* Kiwifruit
	* Papaya
* Drugs
	* Antibiotics
		* Cephalosporins
	* Neuromuscular blocking drugs
	* NSAIDs\
	Similar mechanism by which they induce bronchospasm in asthmatics.
	* Contrast media
	* Protamine\
	May cause:
		* True anaphylaxis
		* Direct histamine release from mast cells\
		Dose and rate related.
		* Thromboxane release\
		Heparin-protamine combination may lead to profound ↑ in PVR and cardiovascular collapse, which may be mistaken for anaphylaxis.
* Gelatin-based colloids
* Chlorhexidine
* Blood products\
1:20:000 to 1:50,000 administrations, by:
	* IgA-deficient recipients with anti-IgA antibodies
	* Transfused allergy into donor blood to a sensitised recipient
	* Recipient with antibodies to plasma proteins
	* Transfusion of IgE antibody from the donor that reacts with a recipient allergen


## Clinical Manifestations

:::caution
* Unanticipated hypotension or tachycardia should raise suspicion
* Absence of skin signs does not rule out the diagnosis
:::

Symptoms and signs of anaphylaxis:

* Typically occur acutely and progress rapidly
	* 83% present within 10 minutes
	* 2% present *after* 60 minutes
* Relate to involvement of different organ systems
* Relate to the region of the body affected\
Typically tissues with high concentrations of mast cells.
	* Skin
		* Urticaria
		* **Erythema**
		* **Angioedema**
		* Airway swelling
	* Respiratory
		* **Bronchospasm**\
		**Leading symptom** in life-threatening reactions.
			* Present in 50%
			* First symptom in ~20%
		* Capnograph changes will be evident in ~30%
	* GIT
		* **Nausea**
		* Vomiting
		* Diarrhoea
	* CVS
		* **Hypotension**\
		May be **isolated**.
		* Haemoconcentration\
		Due to interstitial oedema.
			* 35-70% of circulating volume may extravasate in 10-15 minutes
		* Cardiac arrest\
		PEA most common.

:::column-margin
Skin signs are uncommon in severe anaphylaxis due to lack of perfusion.\
\
Isolated severe hypotension was typically managed poorly in NAP6.
:::

Prodromal symptoms:

* Itching
* Metallic taste
* Fearfulness
* Headache
* Disorientation


### Presentation of Perioperative Anaphylaxis

* Timing
	* ~80% occurs within 10 minutes of drug administration\
	Antibiotic-associated anaphylaxis typically occurs more rapidly and aggressively.
	* ~2% occurs after 60 minutes
* Features
	* Bronchospasm
		* Occurs in 50%
		* First feature in ~20%
		* Capnograph changes in ~30%
	* Skin signs\
	Uncommon in severe reactions.


### Classification

Anaphylaxis is classified into four grades, based on severity:

* **Grade 1 (Mild)**
	* Mucocutaneous signs only
	* Does not require treatment with adrenaline
	* Does require monitoring
* **Grade 2 (Moderate)**
	* Multi-organ manifestations\
	Typically:
		* Bronchospasm
		* Hypotension\
		Perioperatively, consider **hypotension out of proportion to what would be expected** by the drugs given or the operative stage.
		* Mucocutaneous signs\
		Typically allows differentiation from isolated bronchospasm or other causes of hypotension.
* **Grade 3 (Life-threatening)**
	* Life threatening
		* Hypotension
		* Elevated airway pressures
	* Requires immediate treatment to avoid progression
	* **Cutaneous signs** frequently **absent** due to poor cardiac output state\
	May only appear following resuscitation.
* **Grade 4 (Cardiac arrest)**
	* Absence of palpable central pulse or grossly inadequate blood pressure
	* Management follows a ALS protocol\
	Consider more frequent use of adrenaline (Q1-2 minutely) and early initiation of vasopressors when initial therapy is inadequate.



## Diagnostic Approach and DDx

Differential diagnoses include:

* Respiratory
	* Status asthmaticus
	* Airway foreign body
	* Laryngotracheitis
	* Tension pneumothorax
	* Acid aspiration
	* Dislodged, kinked, or obstructed airway device
* CVS
	* Cardiogenic shock
	* Embolism
	* MI
* Endocrinological
	* Carcinoid syndrome
	* Pheochromocytoma
	* Thyrotoxic crisis
	* Hypoglycaemia
* Skin diseases
	* Urticaria
	* Hereditary/acquired angioedema
* Toxins
	* Ethanol
	* Histaminosis


## Investigations

Laboratory:

* Bloods
	* Tryptase\
	To confirm diagnosis. Send at:
		* 0-1 hours
		* 4 hours
		* 24 hours
	* RAST testing\
	Measurement of level of allergen-specific IgE antibody.

Other:

* Skin testing\
Test of degree of histamine release on exposure to certain agents.

### Tryptase Testing

* Tryptase is a protease enzyme stored in granules in mast cells and basophils\
Two subtypes:
	* α-tryptase is secreted constitutively and found in health
	* β-tryptase is released by mast cells in anaphylaxis, and may be raised in cutaneous mastocytosis
* Will not be elevated in a basophil or complement-mediated anaphylaxis
* Acute elevation supports anaphylaxis diagnosis
	* Level >20μg/L is considered positive, assuming a normal baseline\
	Magnitude of elevation is relevant, and is more likely to have an agent identified.
	* Peak level usually within 15-120 minutes
	* Declines over 3-6 hours
* Should be measured at the 1 (as close as possible to onset), 4, and 24 hour mark\
	* 24 hour value gives a baseline level, which can then be used to identify whether there was substantial mast cell degranulation
	* Samples require refrigeration if ⩾1 hour to laboratory


### RAST Testing

* *In vitro* testing evaluating IgE response to specific agents
	* Limited to IgE mediated reactions
* Only available for a small number of agents:
	* Suxamethonium\
	Limited sensitivity.
	* Penicillin
	* Ampicillin
	* Amoxicillin
	* Cefaclor
	* Latex
	* Chlorhexidine


### Skin Testing

* Gold standard
* Most useful for:
	* Neuromuscular blocking drugs\
	Only method to determine cross-reactivity in NMBD-induced anaphylaxis.
	* Latex
	* β-lactam antibiotics
* Requirements:
	* Must be performed **6 weeks** after the event\
	Ensure mast cell recovery has occurred.
	* Several day cessation of:
		* Antihistamines
		* Psychotropic drugs
* May involve either:
	* **Skin prick testing**\
	Agent is applied to the forearm, and then a needle prick made through the agent.
	* **Intradermal testing**\
	Injection of dilute agents *into* the dermis.


## Management

**Resuscitation**:

* **Human factors**\
Call for help and allocate key roles:
	* Team leader\
	Usually most senior person present.
	* **Card reader**\
	Call out required actions of immediate management cards, and to communicate with the team leader.
	* Giver of adrenaline
* A
	* Intubation
		* Intubate if angioedema present\
		Early administration of adrenaline may avoid the need for intubation, but airway difficulty will ↑ as angioedema worsens.
		* Consider **early intubation**
* B
	* Bronchodilators
* C
	* Secure IV access
	* **Volume resuscitation**\
	Reverses haemoconcentration due to interstitial oedema.
		* Can consider colloid, provided colloid was not given prior to onset of anaphylaxis
	* **Adrenaline**
		* Key therapy
			* Prevents further mast cell degranulation
			* Bronchodilator
			* Vasoconstrictor
		* Doses may vary depend on patient factors
			* ↑ Risk of CVS compromise with overdose
				* Extremes of age
				* Hypertension
				* Ischaemic heart disease
				* Hyperthyroidism
			* Catecholamine resistance
				* β-blockade
				* ACE-I use
			* Catecholamine sensitivity
				* Amphetamines
				* Cocaine
		* Intramuscular\
		When no IV access, or no haemodynamic monitoring.
			* Appropriate when IV access is unavailable
			* Reduces chance of severe CVS side effects
			* Provides 'depot' for continued release\
			Up to 40 minutes. Useful as a 'pseudo-infusion', whilst establishing a real infusion.
		* Intravenous
			* Appropriate in severe anaphylaxis
			* May be repeated every 1-2 minutes, as required
			* If >3 doses are required, then commence an infusion
	* **Arterial line insertion**\
	Monitoring, titration, and blood sampling for tryptase.
	* Consider **central line insertion**\
	If ongoing vasopressor requirement.
	* **VA ECMO**
		* Indicated for systolic failure in resuscitated shock
		* Difficult to achieve circuit flows in a hypovolaemic state
* Disability
	* Maintain anaesthesia\
	Consider processed EEG monitoring.
* E
	* Position supine
	* Consider leg elevation
* I
	* **Cease** administration of **triggers**
		* Drug infusions
		* Colloids
		* Chlorhexidine\
		Remove chlorhexidine-impregnated CVC, IDC, and lubricants.
		* Latex

:::column-margin
Management reflects the nature of operative anaphylaxis, namely:

* High frequency of sudden onset, severe symptoms
* Presence of an anaesthetist

+----------------------------------------+-----------+---------------+
| Situation                              | Adults    | Paediatrics   |
+========================================+===========+===============+
| IM bolus (Q5M)                         | 500μg     | 150μg in ⩽6   |
|                                        |           | 300μg in 6-12 |
+----------------------------------------+-----------+---------------+
| IV bolus in Moderate/Grade II          | 20μg      | 2μg/kg        |
+----------------------------------------+-----------+---------------+
| IV bolus in life threatening/Grade III | 100-200μg | 4-10μg/kg     |
+----------------------------------------+-----------+---------------+
| IV bolus in cardiac Arrest/Grade IV    | 1mg       | 10μg/kg       |
+----------------------------------------+-----------+---------------+
| Starting infusion rate                 | 3μg/min   | 0.1μg/kg/min  |
+----------------------------------------+-----------+---------------+
| Maximum infusion rate                  | 40μg/min  | 2μg/kg/min    |
+----------------------------------------+-----------+---------------+

: Intraoperative Adrenaline Dosing
:::

**Specific Therapy**:

* Pharmacological
	* **Glucagon**\
	Recommended in patients on β-blockers due to role in β-blocker overdose. 
		* 1-2mg IV Q5M

**Disposition**:

* Grade 1 and 2 anaphylaxis which has settled quickly should be have at least 6 hours of close monitoring
* Grade 3 and Grade 4 anaphylaxis requires admission to ICU/HDU for monitoring and ongoing therapy as required
	* 30% extubated within 6 hours
	* 70% extubated within 24 hours
* All patients require a letter containing descriptions of the reaction and agents administered
* Allergy clinic\
Formal follow-up is important
	* As anaesthetists are mostly wrong about the likely causative agent
	* For patients with any of the following:
		* Unexplained cardiac arrest
		* Unexplained and unexpected hypotension
		* Unexplained bronchospasm, particularly when:
			* Severe
			* Associated with desaturation
			* Treatment resistant
		* Angioedema
	* To provide education for future anaesthetics
		* Notably, no cause is found in ~50% of cases


### Refractory Management

Anaphylaxis refractory to maximal management occurs in patients:

* On β-blockers
* On ACE-Is
* With spinal blockade

For hypotension, consider:

* TOE or TTE to guide resuscitation
* ECMO/CPB to establish adequate perfusion
* Alternative vasopressors
	* Vasopressin
		* Adults: 1-2 unit bolus, then 2 units/hr
		* Paediatrics: 0.04 units/kg bolus, then 0.02-0.06 units/kg/hr
	* Noradrenaline
		* Adults: 3-40μg/min
		* Paediatrics: 0.1-0.2μg/kg/min
	* Metaraminol
	* Phenylephrine

For bronchospasm, consider:

* Excluding:
	* Pneumothorax
	* Airway device malfunction
* Bronchodilators
	* Salbutamol
		* 1200μg (12 puffs) via MDI
		* 100-200μg IV, +/- infusion at 5-25μg/min
	* Magnesium\
	2g over 20 minutes.
	* Inhalational anaesthetics
	* Ketamine


### Post-Crisis Management

Consider:

* Steroids\
No evidence that use of corticosteroids affects outcome.
	* May be reasonable as part of secondary management in a stable patient
	* May have a role in reducing rebound
	* Dexamethasone 0.1-0.4mg/kg, up to 12mg
	* Hydrocortisone 2-4mg/kg, up to 200mg
* Antihistamines\
	* No role in acute phase
	* May be used for symptomatic management of urticaria, angioedema, and pruritus\
	Appropriate in mild anaphylaxis.
	* No effect on hypotension and bronchospasm
	* Oral agents have a preferred side-effect profile compared to IV


### Marginal and Ineffective Therapies

* Sugammadex\
Has no role in the management of rocuronium anaphylaxis.


## Complications

* Death
* C
	* Takotsubo cardiomyopathy
	* Coronary spasm\
	Kounis syndrome.

## Prognosis

Mortality is associated with:

* ↑ Age
* Comorbidities
	* CAD
	* HTN
		* β-blocker
		* ACE inhibitor

---

## References

1. Cook T, Harper N. [Anaesthesia, Surgery, and Life-Threatening Allergic Reactions: Report and findings of the Royal College of Anaesthetists' 6th National Audit Project: Perioperative Anaphylaxis](https://niaa.org.uk/NAP6Report#pt). Royal College of Anaesthetists'. 2018.
2. Ring J, Beyer K, Biedermann T, et al. [Guideline for acute therapy and management of anaphylaxis: S2 Guideline of the German Society for Allergology and Clinical Immunology (DGAKI), the Association of German Allergologists (AeDA), the Society of Pediatric Allergy and Environmental Medicine (GPA), the German Academy of Allergology and Environmental Medicine (DAAU), the German Professional Association of Pediatricians (BVKJ), the Austrian Society for Allergology and Immunology (ÖGAI), the Swiss Society for Allergy and Immunology (SGAI), the German Society of Anaesthesiology and Intensive Care Medicine (DGAI), the German Society of Pharmacology (DGP), the German Society for Psychosomatic Medicine (DGPM), the German Working Group of Anaphylaxis Training and Education (AGATE) and the patient organization German Allergy and Asthma Association (DAAB)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4479483/pdf/40629_2014_Article_9.pdf). Allergo Journal International. 2014;23(3):96-112. doi:10.1007/s40629-014-0009-1.
3. Kolawole H, Crilly H, Kerridge R, Marshall S, Roessler P. [Australian and New Zealand College of Anaesthetists (ANZCA) and Australian and New Zealand Anaesthetic Allergy Group (ANZAAG) Perioperative Anaphylaxis Management Guidelines: Background Paper](http://www.anzca.edu.au/documents/bp-anaphylaxis-2016.pdf). ANZCA/ANZAAG. 2016.
4. ANZCA. [PS60: Guidelines on the Perioperative Management of Patients with Suspected or Proven Hypersensitivity to Chlorhexidine](http://www.anzca.edu.au/Documents/ps60-2015-guidelines-on-the-perioperative-manageme.pdf).
5. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.