# Graft versus Host Disease {#sec-gvhd}

Complication of **allogeneic** haematopoietic **stem cell transplant** (and occasionally blood transfusion) where the **donor immunological cells recognise** the **host** as **foreign**, causing a generalised immune response. Divided into:

:::column-margin
Haematopoietic stem cell transplant is covered under @sec-gvhd.
:::

* Acute GvHD
	* Classically 7-28 days following transplant
	* Features:
		* Maculopapular rash
		* Diarrhoea
		* Intrahepatic cholestasis
	* Staged based on extent of rash, volume of diarrhoea, and bilirubin
* Chronic GvHD\
Multiorgan dysfunction.
	* Generally occurs >100 days post transplant
	* Generalised organ involvement


## Epidemiology and Risk Factors

Risk factors:

* Allogeneic stem cell transplant\
30-50% of cases.
* CMV positive
* Recipient frailty
* HLA mismatch
* ↑ Donor age
* ↑ Recipient age
* Inadequate immunosuppression
* Peripheral blood utilised as stem cell source

## Pathophysiology

### Aetiology

## Clinical Features

: Clinical Features of Graft versus Host Disease

+------------+-------------------------------+-------------------------------------+
| Properties | Acute                         | Chronic                             |
+============+===============================+=====================================+
| Timing     | * Classically within 100 days | * May occur at any time             |
|            |                               |                                     |
+------------+-------------------------------+-------------------------------------+
| Features   | * Skin                        | * **Absence of acute features**     |
|            |     * Maculopapular rash      | * Bronchiolitis obliterans          |
|            |     * Erythema                | * Pleural effusions                 |
|            | * GIT                         | * Pericardial effusion              |
|            |     * N/V/D                   | * Conjunctivitis                    |
|            |     * Anorexia                | * Alopecia                          |
|            |     * Mucositis               | * Sclerotic skin                    |
|            |     * Cholestasis             | * Lichenoid oral and genital mucosa |
|            |                               | * Oesophageal strictures            |
+------------+-------------------------------+-------------------------------------+
	
:::column-margin
Definition relies more on the clinical features than the timing.
:::

:::column-margin
Late-onset acute GvHD describes the clinical features of acute GvHD, occurring after 100 days.
:::

## Assessment

**History**:

**Exam**:

### Investigations	

**Bedside**:

**Laboratory**:

* Tissue biopsy\
Affected regions; classically skin, liver, or rectal.

**Imaging**:

**Other**:

### Diagnostic Approach and DDx


## Management

:::priority
* Preventative immunosuppression in at-risk individuals
* Pulsed immunosuppression 
:::

**Resuscitation**:

**Specific therapy**:

* Pharmacological
	* Pulsed methylprednisolone
	* Additional immunosuppression
* Procedural
* Physical

**Supportive care**:

* G
	* Nutritional support\
	PN may be required due to secretory diarrhoea.

**Disposition**:

**Preventative**:

* Immunosuppression
	* Corticosteroids
	* Cyclosporin
	* Mycophenolate mofetil


### Marginal and Ineffective Therapies

## Anaesthetic Considerations

## Complications

## Prognosis

## Key Studies


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.