# Immune Thrombocytopaenic Purpura

:::info
Also known as idiopathic thrombocytopaenic purpura.
:::

Pathological destruction of platelets by the monocyte-macrophage system, predominantly in the spleen, that occurs due to platelet autoantibody formation.


## Epidemiology and Risk Factors

## Pathophysiology

### Aetiology

## Clinical Features

## Assessment

**History**:

**Exam**:

### Investigations

**Bedside**:

**Laboratory**:

**Imaging**:

**Other**:

### Diagnostic Approach and DDx


## Management

:::priority
* **Corticosteroids**
* Consideration of **splenectomy**
:::

**Resuscitation**:

**Specific therapy**:

* Pharmacological
	* Dexamethasone 40mg daily for 4 days\
	Indicated for:
		* Severe thrombocytopaenia\
		<10×10^9^/L.
		* Uncontrolled bleeding
	* IVIG\
	Major bleeding not responding to corticosteroids.
	* Thrombopoietin receptor agonists
		* Romiplostim
		* Eltrombopag
	* MAB
		* Rituximab
* Procedural
	* Splenectomy
* Physical

**Supportive care**:

**Disposition**:

**Preventative**:


### Marginal and Ineffective Therapies

## Anaesthetic Considerations

## Complications

## Prognosis

## Key Studies


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.