# Systemic Sclerosis/Scleroderma


Chronic multisystem disease characterised by progressive fibrosis of organs. Subdivided by pattern of skin and internal organ involvement into:

* Limited cutaneous systemic sclerosis  
Skin sclerosis distal to elbows and knees, and prominent vascular malformations.
* Diffuse cutaneous systemic sclerosis  
Skin thickening proximal to elbows and knees, with early lung fibrosis and ↑ risk of renal and cardiac involvement.
* Systemic sclerosis without scleroderma
* Systemic sclerosis with overlap  
Any of the above may have features of another systemic rheumatic disease.

## Epidemiology and Risk Factors

## Pathophysiology

### Aetiology

## Clinical Manifestations

General:

* Pain
* Fatigue


Respiratory disease:

* Restrictive lung disease
* Pulmonary fibrosis


Cardiac disease:

* Myocardial fibrosis/LV failure
* Pulmonary hypertension
* Arrhythmias


Renal failure:

* Renal crisis


Dermatological:

* Raynauds

## Diagnostic Approach and DDx

## Investigations

## Management

### Medical

### Surgical

### Anaesthetic Considerations

* A
	* Potential difficult airway
		* Small mouth
		* ↓ Neck mobility
		* Bleeding telangiectasia
	* Aspiration risk
		* Oesophageal dysmotility
* B
	* Pulmonary fibrosis
	* Restrictive lung disease
* C
	* Myocardial fibrosis
	* Pulmonary hypertension
	* Arterial line placement  
	Beware Raynaud's and risk of limb ischaemia with small (e.g. radial) arteries.
* E
	* Difficult IV access
* G
	* Oesophageal dysmotility ↑ risk of TOE injury


### Ineffective Therapies

## Complications

## Prognosis

## Key Studies


---

## References

