# Can't Intubate, Can't Oxygenate 

*This covers the CICO situation from the [difficult airway drill](/management/airway/difficult-airway.md#drill).*

> * CICO should be **verbally declared**
> * A CICO situation may occur when oxygen saturations are normal


A CICO situation occurs when there is a **failure (or impending failure) to deliver oxygen due to supraglottic obstruction**, and:

* This obstruction is unlikely to be relieved by persistent attempts at supraglottic rescue
* This obstruction may be bypassed with front of neck access
* Failure is defined as:
	* ETT  
	Three optimal attempts.
	* SAD  
	Two attempts with different sizes or devices.
	* Bag-Mask Ventilation with use of adjuncts
* Note that therefore the **trigger for performing FONA is inability to establish airawy patency** following optimal attempts at non-surgical techniques, **not desaturation**


## Transitioning to CICO

Transition describes the phase of care leading up to, and including, a committed declaration of a CICO event. Key steps in transition:

* Prevent (where possible)
	* Adquate preparation
	* Preoxygenation
	* Airway assessment  
	Consider:
		* Awake intubation
		* Awake tracheostomy
	* Use of adjunts and tools
		* Ensure attempts at:
			* Mask ventilation  
			With adjuncts, and two-hands.
			* Supraglottic technique
			* Intubation
		* Continuous, apneic delivery of oxygen  
		Mask, nasal prongs, or supraglottic airway.
	* Call for help early
		* **Call** for skilled **help** after **failure of one technique**
* Preparation  
Of CICO kit.
	* **Prepare** equipment after **failure of two techniques**
* Priming
	* Recognise the situation  
		* **Verbally declare** when recognised, or after **failure of three techniques**
		* Many such situations may be recognition of impending CICO  
		Focus shifts from supraglottic to infraglottic rescue.
	* Communicate
	* Demonstrate willingness to act
* Puncture  
Perform critothyrotomy.

### Optimising Transition

Principles:

* Manage ambiguity
* Prevent and detect cognitive failure
	* Use of cognitive aids
	* Use pre-rehearsed responses
	* Be self-aware of vulnerability
* Optimise team support and coordination
* Monitor attention
* Minimise delays

### Front of Neck Access

Cricothyrotomy techniques include:

* Scalpel cricothyrotomy
	* Faster than needle cricothyrotomy
	* More reliable than needle cricothyrotomy
	* Should be performed with neuromuscular blockade
	* Many techniques  
	No evidence any one technique is superior.
* Needle cricothyrotomy
	* May be favoured by anaesthetists who are more comfortable with needles than scalpels
	* Use of a 14G cannula facilitates jet ventilation
	* Cannula can be converted to a definitive airway using Seldinger technique


## Epidemiology of CICO

CICO is:

* A rare event  
~1:10,000 to 1:50,000 of routine GAs.
	* ↑ risk in ICU and ED
* Influenced heavily by:
	* Organisational factors
		* Use of airway registries
		* Early warning and alert systems
		* Use of checklists
		* Safety culture
	* Cognitive errors
		* Use of cognitive aids  
		Prompt team to adopt rehearsed practices.
		* Self-awareness  
		Of vulnerability to error, and monitoring to detect and correct error.
		* Encourage  
		Team members to speak up.
		* Real-time optimisation of the environment  
		Enhance situational awareness.
	* Teamwork
		* Shared mental models
		* Role clarity
		* High coordination
		* Clear communication
		* Strong leadership
		* Rapid, robust decision making





---

## References

1. Frerk, C., Mitchell, V. S., McNarry, A. F., Mendonca, C., Bhagrath, R., Patel, A., … Ahmad, I. (2015, December 1). Difficult Airway Society 2015 guidelines for management of unanticipated difficult intubation in adults. British Journal of Anaesthesia. Oxford University Press. https://doi.org/10.1093/bja/aev371
2. ANZCA. [PS 61: Guidelines for the Management of Evolving Airway Obstruction: Transition to the Can’t Intubate Can’t Oxygenate Airway Emergency](http://www.anzca.edu.au/getattachment/resources/professional-documents/ps61_guideline_airway_cognitive_aid_2016.pdf). 2016.
3. Chrimes, N. [The Vortex: A Universal 'High-Acuity Implementation Tool' for Emergency Airway Management](https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/bja/117/suppl_1/10.1093_bja_aew175/3/aew175.pdf?Expires=1490519117&Signature=WDst8BeRnWgBXFudzgcLzu~Dw9HSr1v6yYlJwU-QUlgp5PgJ2msffuz~vsoWDXXv-XxZr1ndrpwcxCH274qVjBP~7hGZdtB3HBzH5HUNIHbFqBVtciwZlFQsMOSW6aAAt4kEtBBH6TAjkgxrA-~PpqBqpvOeOzC~08QMUjKXiqmn4errYgsKBEMXdNhxwJRPxra3w4BnOp-zluwtSsmmBzrfVvN0NmISaIOXxUGFqJHs1pWGJ9sqnuTYQsSkyAxdozEdWDnQAYkFNkq7igoHpzVNGzEkUMylsTVub1KHVEXLNT7De~LVU~c-M1Ft6G7p96r8vVYhGwOToDqGURIBig__&Key-Pair-Id=APKAIUCZBIA4LVPAVW3Q). Br J Anaesth 117 Suppl 1, i20-i27. 2016 Jul 20.