# Massive Haemoptysis


> This is an <span style="color:red">**anaesthetic crisis**</span>  
> Priority is to:
>* **Decontaminate the airway**
>* **Maintain oxygenation**

Large haemorrhage into the pulmonary tree, which may precipitate cardiac arrest secondary to **hypoxia**.

##<span style="color:red">Emergency Management</span>

Immediately:

* **Protect airway**
	* Large, **single-lumen** ETT
		* Suction cathether/bronchoscopic decontamination
	* Consider lung isoation
		* Bronchial blocker
		* Endobronchial tube
* Haemodynamic resuscitation  
	* Cardiac arrest is common
	* Hypoxia is almost always the cause
	* Hypovolaemia is rarely significant

Definitive treatment:

* Source control  
Options include:
	* Rigid bronchoscopy
	* Interventional angiography  
	Bronchial angiography and embolisation.  
		* Note risk of paralysis due to loss of spinal perfusion
	* Thoracotomy
* Correction of coagulopathy




## Epidemiology and Risk Factors


## Pathophysiology

* 90% of haemorrhage comes from the bronchial circulation  
These bleeds are dependent on ***systemic* blood pressure**.

### Aetiology

Causes can be divided into:

* Airway
* Primary lung disease
* Primary CVS disease
* Iatrogenic

## Clinical Manifestations

### History

### Examination

## Diagnostic Approach and DDx

## Investigations

## Management


### Anaesthetic Considerations

### Ineffective Therapies

## Complications

## Prognosis


---

## References

