# Preventative Medicine

Good supportive care to prevent the emergence of new issues is a key component of good intensive care medicine. Aspects can be remembered using the FASTHUGS IN BED mnemonic:

* Fluids and Feeding
* Analgesia
* Sedation
* Thromboprophylaxis
* Head-up Positioning
* Ulcer prophylaxis
* Glucose
* Skin
* IDC
* NGT
* Bowels
* Environment
* De-escalation


## DVT Prophylaxis

Preventative methods include:

* Pharmacological
* Mechanical
	* Intermittent pneumatic calf compression  
	May reduce incidence by up to 60% in operative patients.
		* Treatment of choice where bleeding risk is high
	* IVC filters
		* No evidence for mortality reduction
		* ↑ risk of DVT  
		Should be retrieved when no longer required, so retreivable designs should be used.
		* Reasonable to use in patients with:
			* High VTE risk and contraindications to anticoagulation
			* Recurrent PE despite therapeutic anticoagulation	


## Ulcer Prophylaxis

Physiological stress-related mucosal bleeding occurs in 8-45% of patients. Ulcer prophylaxis:

* Aims to increase gastric pH to decrease ulceration
* Decreases Mucosal bleeding rate but not mortality
* May increase risk of:
	* HAP/VAP\
	Via gastric bacterial overgrowth and microaspiration.


Overall, treatment should probably reserfved for at-risk patients.

Options for management include:

* PPI
* H~2~-receptor antagonsits	

---

## References