# Continuous Renal Replacement {#sec-crrt}

Form of extracorporeal blood purification using a continuous circuit, providing:

:::column-margin
This covers CRRT; a general overview and comparison of RRT modalities is provided under @sec-rrt.
:::

* Continuous control of:
	* Fluid status
	* Acid-base status
	* Electrolyte balance
	* Intracerebral water
* Good haemodynamic stability
* Minimal infective risk
* Facilitation of **renal recovery**


## Principles

{{< include /includes/rrt_principles.qmd >}}

:::column-margin
CRRT relies on the same physical principles as IHD and SLED, but as fluid shifts occur more slowly CRRT has the greatest haemodynamic stability, and is preferred in patients with:

* Haemodynamic instability
* ↑ ICP
* Cerebral oedema
:::


### Types of CRRT

There are a number of technical variations of CRRT based on the physical principles used:

* **Haemofiltration** (CVVH)\
No dialysate is used; effect occurs via filtration and convection.
	* Ultrafiltration results in a solute-water mix filtered across the semi-permeable membrane\
	* A substitution solution is used to replace lost volume\
	The difference between the ultrafiltration volume produced and the substitution solution infused is the total fluid removal.
* **Haemodialysis** (CVVHD)\
Counter-current delivery of dialysis solution, without generation of a transmembrane pressure.
	* Clearance is almost entirely by diffusion
* **Haemodiafiltration** (CVVHDF)\
Combination of the above, using both:
	* Counter-current dialysis solution\
	Solute clearance by diffusion.
	* Ultrafiltration\
	Additional substitution solution used to replace lost volume.


## Indications

Indications for CRRT include:

:::column-margin
CRRT may be initiated in ICU based on anticipation of reaching these thresholds, or on a series of composite features that individually do not meet the threshold.
:::

:::column-margin
A mnemonic for the major causes is:

* **A**acidosis
* **E**lectrolyte
* **I**ntoxication
* **O**verload (fluid)
* **U**raemia
:::

* Acidosis
* Electrolyte disorders
	* **Hyperkalaemia**\
	Thresholds vary, but consider if K^+^ >6.5mmol/L or rapidly ↑.
	* Hyponatraemia <110mmol/L
	* Hypernatraemia >160mmol/L
* Toxins
* Refractory fluid overload
* Uraemia
	* Urea >35-40mmol/L
	* Uraemic complications
		* Pericarditis
		* Encephalopathy
* Other
	* Hyperthermia >40°C

:::column-margin
A short, but mostly-adequate exam list of dialysable toxins includes:

* **Alcohols**
	* Ethanol
	* Methanol
	* Ethylene glycol
* **Anticonvulsants**
	* Lithium
	* Valproate
	* Phenytoin
	* Phenobarbital
:::

## Contraindications

## Equipment

### Vascular Access

**Vascath**:

* Uncuffed, non-tunneled catheter
* Preferentially sited in:
	* Right IJV
	* Femoral vein
	* Left IJV
	* Dominant SCV\
	Risk of central vein stenosis with SCV insertion.
	* Non-dominant SCV
* Positioned at the junction of the SCV and RA
	* Risk of atrial erosion if in too far
	* Risk of central vein stenosis if abutting SVC 


**Tunneled** dialysis catheter:

* Medium-term dialysis line
* Usually sited in RIJ


### Solutions

**Substitution**:

* Balanced crystalloid solutions used to replace water and solute\
Include:
	* **Pre-filter dilution**\
	Mixed with blood prior to the haemofilter.
		* ↓ Effective solute clearance
		* ↓ Filter clotting, due to ↓ haematocrit
		* Required if using a citrated solution, as this is where the anticoagulant is kept
	* **Post-filter replacement**\
	Mixed with blood after the haemofilter, generally in the bubble trap.
		* Restores water and solute
		* May be the same solution as the pre-filter diluent

:::column-margin
Pure post-filter replacement with no pre-filter dilution is the most efficient method for solute clearance, but has a high risk of filter clotting due to the ↑ haematocrit. In general, the haematocrit should be kept <50% in the filter to minimise the risk of clotting and maximise filter lifespan.
:::

**Dialysate**:

* Crystalloid solution
* Buffered with:
	* Citrate\
	Used when the circuit is anticoagulated with citrate and calcium.
	* Bicarbonate\
	Requires reconstitution due to instability of bicarbonate in solution.
		* Shock
		* Hepatic failure
		* Lactic acidosis
	* Lactate\
	Generally superseded by bicarbonate buffers.


## Anticoagulation

Anticoagulation is frequently used to prevent clotting of the filter and circuit, but must be balanced against risks of bleeding. In general, circuit anticoagulation is recommended when patient is:

* Not coagulopathic
* Not systemically anticoagulated


:::column-margin
Acceptable filter life is ~24 hours.
:::

: Comparison of Anticoagulation Techniques

+-------------------------------------------------+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+----------------------------------------------------------------------------+
| Technique                                       | Method                                                                                      | Advantages                                                                                  | Disadvantages                                                              |
+=================================================+=============================================================================================+=============================================================================================+============================================================================+
| No anticoagulant                                |                                                                                             | * Used in patients with endogenous coagulopathy or other contraindication                   | * ↓ Filter life                                                            |
+-------------------------------------------------+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+----------------------------------------------------------------------------+
| Heparin alone                                   | * Low dose\                                                                                 | * Easy, cheap, familiar, available                                                          | * HITTS                                                                    |
|                                                 | Heparin <500 units/hr.                                                                      | * Minimal effect on systemic coagulation                                                    | * Heparin resistance                                                       |
|                                                 | * Medium dose\                                                                              | * Therapeutic heparinisation can be used if systemic anticoagulation is indicated (e.g. PE) |                                                                            |
|                                                 | Heparin 500-1000 units/hr.                                                                  |                                                                                             |                                                                            |
+-------------------------------------------------+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+----------------------------------------------------------------------------+
| Regional anticoagulation with citrate           | Citrate given into the access line and reversed with calcium given into the return line.    | * Regional anticoagulation reduces systemic haemorrhage                                     | * Special dialysate required                                               |
|                                                 |                                                                                             | * Longer filter life                                                                        | * Citrate toxicity (especially hepatic failure, shock)\                    |
|                                                 |                                                                                             | * ↓ Transfusion and major bleeding compared to UFH                                          | Metabolic acidosis, hypocalcaemia, widening total calcium:ionised calcium. |
+-------------------------------------------------+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+----------------------------------------------------------------------------+
| Regional anticoagulation with heparin/protamine | Heparin into access line and reversed with protamine at a fixed ratio into the return line. | * Easy, cheap, familiar, available                                                          | * HITTS                                                                    |
|                                                 |                                                                                             | * Reversible                                                                                | * Heparin resistance                                                       |
|                                                 |                                                                                             | * Can be monitored                                                                          | * Narrow TI                                                                |
|                                                 |                                                                                             | * Short half-life                                                                           | * Unpredictable kinetics                                                   |
+-------------------------------------------------+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+----------------------------------------------------------------------------+
| Systemic low-molecular weight heparin           |                                                                                             | * Predictable kinetics                                                                      | * May accumulate in renal failure                                          |
|                                                 |                                                                                             | * Does not require monitoring                                                               | * Requires anti-Xa for monitoring                                          |
|                                                 |                                                                                             | * Less HITTS                                                                                | * Incompletely reversed with protamine                                     |
|                                                 |                                                                                             |                                                                                             | * More expensive                                                           |
+-------------------------------------------------+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+----------------------------------------------------------------------------+


### Responding to Filter Clotting

* Evaluate for mechanical causes\
Cannula:
	* Position
	* Flow rates
	* Kinking
* Check anticoagulation efficacy
* Consider ↑ or change of anticoagulation


## Complications

* Vascular access
* Haemodynamic instability\
More pronounced with more aggressive dialysis modes (particularly IHD).


## Key Studies

{{< include /trials/renal.qmd >}}


---

## References

1. Kidney Disease: Improving Global Outcomes (KDIGO) Acute Kidney Injury Work Group. [KDIGO Clinical Practice Guideline for Acute Kidney Injury](http://kdigo.org/wp-content/uploads/2016/10/KDIGO-2012-AKI-Guideline-English.pdf). Kidney inter., Suppl. 2012; 2: 1–138.
1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.
1. [Intensity of Continuous Renal-Replacement Therapy in Critically Ill Patients](http://www.nejm.org/doi/full/10.1056/NEJMoa0902413). New England Journal of Medicine. 2009 Oct 22;361(17):1627–38. 
1. Gemmell L, Docking R, Black E. [Renal replacement therapy in critical care](https://academic.oup.com/bjaed/article/17/3/88/2957196). BJA Education. 2017;17(3):88-93. doi:10.1093/bjaed/mkw070
