# Overview of Renal Replacement {#sec-rrt}

Renal replacement is the use of extracorporeal blood purification to control water and solute load when the kidneys are unable to do so. Methods include:

* **Intermittent Haemodialysis** (IHD)\
Rapid removal of volume and toxins.
	* Most commonly used by ESRD patients in the community
* **Continuous Renal Replacement Therapy** (CRRT)\
Slower removal, preferred in critically ill due to haemodynamic stability.
	* Typical effluent rate of 25-30mL/kg/hr
* **Sustained Low-Efficiency Dialysis** (SLED)\
Similar toxin control to CRRT, with potentially better acid-base control and HDx stability. Evidence is lacking to recommend SLED over CRRT.
* **Peritoneal Dialysis** (PD)

:::column-margin
SLED is often referred to as SLEDD, for Sustained Low-Efficiency *Daily* Dialysis.\
\
I have elected to use SLED because during renal recovery second-daily (or less) use is common, and so the "daily" is a misnomer.
:::

## Principles

{{< include /includes/rrt_principles.qmd >}}


## Comparison of Techniques

: Methods of Renal Replacement

+-----------+------------------------------------------------------+----------------------------------------------------+--------------------------------------------------------------------------------+
| Technique | Clinical Setting                                     | Advantages                                         | Disadvantages                                                                  |
+===========+======================================================+====================================================+================================================================================+
| IHD       | * HDx stability                                      | * Rapid                                            | * Hypotension due to rapid volume shifts\                                      |
|           | * Planned for continued dialysis in ward environment | * Cheaper                                          | May delay renal recovery in the ICU patient.                                   |
|           |                                                      |                                                    | * Cerebral oedema due to rapid fluid shifts (dialysis disequilibrium syndrome) |
+-----------+------------------------------------------------------+----------------------------------------------------+--------------------------------------------------------------------------------+
| CRRT      | * HDx instability                                    | * Technically simple(r)                            | * Slower clearance                                                             |
|           | * ↑ ICP                                              | * HDx stability                                    | * Prolonged anticoagulation/immobilisation                                     |
|           |                                                      | * Continuous removal of toxins                     | * Expensive                                                                    |
+-----------+------------------------------------------------------+----------------------------------------------------+--------------------------------------------------------------------------------+
| SLED      | * Encourage activity                                 | * HDx stability                                    | * Slow clearance of toxins                                                     |
|           |                                                      | * Reduced anticoagulation requirement              | * ↑ Technical complexity                                                       |
|           |                                                      | * Facilitates mobilisation with overnight dialysis |                                                                                |
+-----------+------------------------------------------------------+----------------------------------------------------+--------------------------------------------------------------------------------+
| PD        | * HDx instability                                    | * Simple                                           | * Reduced clearance in catabolic patients                                      |
|           | * Coagulopathic                                      | * Cheap                                            | * Protein loss                                                                 |
|           | * Difficult venous access                            | * No anticoagulation requirement                   | * No control over rate of fluid removal                                        |
|           | * High ICP                                           | * No vascular access requirement                   | * Risk of peritonitis                                                          |
|           | * Austere setting                                    |                                                    | * Hyperglycaemia                                                               |
|           |                                                      |                                                    | * Respiratory impairment                                                       |
+-----------+------------------------------------------------------+----------------------------------------------------+--------------------------------------------------------------------------------+
| SCUF      | * Removal of fluid\                                  | * Haemodynamic stability                           |                                                                                |
|           | 100-500mL/hr of UF.                                  |                                                    |                                                                                |
+-----------+------------------------------------------------------+----------------------------------------------------+--------------------------------------------------------------------------------+

---

## References

1. Kidney Disease: Improving Global Outcomes (KDIGO) Acute Kidney Injury Work Group. [KDIGO Clinical Practice Guideline for Acute Kidney Injury](http://kdigo.org/wp-content/uploads/2016/10/KDIGO-2012-AKI-Guideline-English.pdf). Kidney inter., Suppl. 2012; 2: 1–138.
2. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.