# Unconsciousness 


Coma is:

* A clinical state of being not aware and not awake  
More precisely, "a completely unaware patient unresponsive to external stimuli with only eye opening to pain, with no eye tracking or fixation, and limb withdrawal to a noxious stimulus at best."
* Due to impairment of the ARAS-thalmic-cortical pathway  
Lesion may be in:
	* Arousal centres  
	Dorsal pons, midbrain, thalamus.
	* Consciousness centre  
	Cerebral cortex - must be bilateral to cause coma.
	* Connecting tracts  
	Ascending reticulator activating system.


Related categories of altered conscious states include:

* **Persistent Vegetative State**  
Patients with PVS < 3 years may (rarely) partially recover; there are no known predictors though it is usually after TBI. Patients with PVS for >3 years do not recover. PVS is defined by:
	* No awareness of self or environment
	* No sustained, reproducible, purposeful, or voluntary response to a stimuli
	* No language comprehension or expression
	* Mostly intact cranail nerve reflexes
	* Roving nystagmoid eye movements
	* Presence of a sleep/wake cycle
	* Stable unsupported blood pressure
	* Intact respiratory drive
	* Double incontinence
* **Minimally Conscious State**  
May further recover, but no predictors are known. Patients with MCS:
	* Make eye contact and turns head when talked through
	* Eye tracking
	* "Abulic emotionless state"  
	* May mouth words or fend off pain
	* Some intelligible verbalisation
	* May hold or use objects when asked


Two **key pitfalls** in coma assessment are:

* **Locked-in Syndrome**  
Denervation of motor tracts in the ventral pons, leading to:
	* Ability to blink to command and move eyes vertically
	* Intact hearing, vision, and peripheral pain sensation
* **Psychogenic Unreponsiveness**


## Clinical Manifestations

Level of consciousness is graded using the GCS or FOUR score:

### GCS

The Glasgow Coma Scale is:

* The traditional coma scale  
Designed to standardise descriptions of impaired conscious state.
* Not a good predictor of outcome
* Not as useful in intubated patients
* Measured on a 15-point scale  
Consists of three components, scored variably:
	* Eye response
		* 4: Open spontaneously
		* 3: Open to voice
		* 2: Open to pain
		* 1: Not opening to pain
	* Vocal response:
		* 5: Orientated
		* 4: Appropriate words
		* 3: Inappropriate words
		* 2: Incomprehensible sounds
		* 1: No response
	* Motor response:
		* 6: Obeying commands
		* 5: Localising to pain
		* 4: Withdrawal to pain
		* 3: Flexion to pain
		* 2: Extension to pain
		* 1: No motor response


### FOUR Score

The FOUR (Full Outline of UnResponsiveness) score is:

* A coma scale (similar to GCS)
* Designed to be valid in intubated patients
* Able to further separate patients with low GCS scores  
Provides greater detail on patients with severe neurological injury.
	* Able to identify locked-in syndrome and vegetative states
* Has clinically similar inter-rater reliability to GCS
* Measured on a 16-point scale  
Consists of four components, each scored from 0-4:
	* Eye response  
	Best possible response after at least three trials.
		* 4: Open, tracking, or blinking to command  
			* If closed, eyes should be opened to test for tracking before inflicting pain
			* Tracking requires at least 3 excursions
			* Blinking requires at least 2 blinks
		* 3: Open but not tracking
		* 2: Open to loud voice
		* 1: Open to pain
		* 0: Closed to pain
	* Motor response  
	Best possible **upper limb** response.
		* 4: Thumbs up, fist, or peace sign
		* 3: Localising to pain  
		Supraorbital nerve compression results in the patient touching examiners hand.
		* 2: Flexing to pain  
		Any flexion of the upper limbs.
		* 1: Extending to pain
		* 0: No response or generalised myoclonus status epilepticus  
		Persistent, multisegmental, arrhythmic, jerking movements.
	* Brainstem response  
	Best possible response. Corneal reflexes should ideally be tested with saline drops.
		* 4: Pupillary and corneal reflexes present
		* 3: One pupil fixed and dilated
		* 2: Pupil OR corneal reflexes absent
		* 1: Pupil AND corneal reflexes absent
		* 0: Pupil, corneal, AND cough reflex absent  
		Tests mesencephalon, pons, and medulla function.
	* Respiration response
		* 4: Not intubated, regular breathing
		* 3: Not intubated, Cheyne-Stokes breathing
		* 2: Not intubated, irregular breathing
		* 1: Intubated, breathing above ventilator  
		Indicates a functional respiratory centre.
		* 0: Inbubated, breathing at ventilator rate OR apnoeic
* An overall score of 0 should prompt brain death evaluation


### Associated Findings

Presence or absence of other findings will narrow the differential:

* Bradycardia  
	* Hypnotic toxicity
	* Raised ICP  
	With hypertension (Cushing's Triad).
* Tachycardia
	* Sympathomimetic toxicity
	* Intracranial haemorrhage
* Hypotension
	* Sepsis
	* Drug toxicities
* Hypertension
	* PRES

* HENT
	* Signs of trauma
		* Haemotympanum
		* Bony deformities
	* Miosis  
		* Toxicity  
		Opioid, clonidine.
		* Pontine haemorrhage
	* Mydriasis
		* Anticholinergic toxicity
		* MDMA
	* Horizontal nystagmus
		* ETOH
		* Antiepileptics
	* Vertical nystagmus
		* Dissociate agents
		* Brainstemi lesion
	* Gaze deviation
		* Ipsilateral hemispheric lesion
		* Contralateral pontine lesion
		* Focal seizure
	* Cold-caloric reflex
		* Loss of (normal) deviation of eyes towards irrigation suggestive of midbrain or pontine lesion
		* Loss of (normal) rapid nystagmus away from the irrigation suggestive of cortical lesion
		* Loss of neither normal response suggests psychogenic coma
	* Dry mucous membranes
		* Dehydration
		* Anticholinergic toxicity

## Causes

Major causes can be classified by:

* Pathophysiology
	* Structural  
		* Cerebral hemispheres
		* Intrinsic brainstem injury
		* Cerebellar injury
	* Functional
		* Metabolic or endocrine derangement
		* Diffuse phsyiological dysfunction
* Clinical features
	* No focal signs
	* Focal neurology
	* Meningism

Classification by clinical features:

|No focal neurology|Focal Neurology|Meningism|
|--|--|--|
|Infection <br> Encephalitis, septic encephalopathy.|CVA <br> Coma due to CVA is typically due to a posterior circulation lesion, as both cerebral corticies must be disrupted to produce coma.|Infection <br> - Meningitis|
|Vasculitis|ICH <br> SDH and EDH may cause global depression and seizures. IPH effects may be due to increased ICP, or damage to key pathways.|Vascular <br> - SAH <br> SAH depresses conscious state through direct anoxic-ischaemic injury, or indirectly due to hydrocephalus.|
|Seizures <br> Including Nonconvulsive status epilepticus|Trauma||
|Brainstem|Tumour (including lymphoma and metastases) <br> Via direct pressure on key areas, or by diffuse increase in ICP. May have slow progression of findings.||
|Drugs|Abscess||
|Metabolic|Acute hydrocephalus <br> Spasticity due to stretching of motor cortex. Diplopia due to CN III or CN VI compression.||
|Hyopoxic-Ischaemic Encephalopathy|Posterior Reversible Encephalopathy Syndrome (PRES) <br> Patchwork vasodilation and vasoconstriction due to severe hypertension, producing visual disturbances and altered conscious state.|||

Drugs which may cause CNS depression can be classified broadly into:

* Sedative/hyponotics
	* Alcohols
		* Ethanol
		* Methanol
		* Ethylene glycol
	* Barbiturates
	* Benzodiazepines
	* Baclofen
	* GHB
	* Clonidine
* Opioids
* Dissociatives
	* Ketamine
	* PCP
* Toxins and overdoses
	* Carbon monoxide
	* Serotonin syndrome
	* Neuroleptic malignant syndrome

A mnemonic for the metabolic causes is COMATOSE GREAT APE:

* CO~2~  
Mechanism unclear, but possibly related to ICP or altered neurotransmitter function.
* O~2~  
Coma may occur within minutes of severe oxygen deprivation.
* Metabolism (of drugs)
* Ammonia  
Hepatic encephalopathy, as well as:
	* Valproate in the settin gof carnitine deficiency
	* Urease-producing bacterial infection
	* Hyperalimentation
	* Inborn errors of metabolism
	* Surgery
		* Lung transplantation
		* Bariatric surgery
		* Ureterosigmoidostomy
* Temperature  
Typically requires temperatures <28°C.
* Overdose
	* Neuroleptic malignant syndrome
* Seizures
* Encephalitis


* Glucose  
	* Hypoglycaemia  
	Wide variety of neurologic signs, including coma.
	* Hyperglycaemia  
	May cause coma in the setting of HHS/DKA.
* Renal failure  
Uraemic encephalopathy.
* ETOH
* Adrenal Insufficiency
* Thyroid  
	* Acute hypothyroidism  
	Myxedema coma.
	* Panhypopituitarism


* Autoimmune
* pH
* Electrolytes
	* Hyponatraemia
	* Hypernatraemia
	* Hypercalcaemia
	* Addisons IDisease



### Coma Mimics

Coma mimics include:

* Locked-in syndrome
* Neuromuscular blockade
* Akinetic mutism
* Psychogenic unresponsiveness



---

## References


1. Yartsev, A. [The Unconscious Patient](http://www.derangedphysiology.com/main/cicm-fellowship-exam/hot-cases/unconscious-patient). Deranged Physiology. Accessed 11/2017.
2. Wijdicks EFM, Bamlet WR, Maramattom BV, Manno EM, McClelland RL. Validation of a new coma scale: The FOUR score. Ann Neurol. 2005;58(4):585-593.
3. Fischer M, Rüegg S, Czaplinski A, et al. Inter-rater reliability of the Full Outline of UnResponsiveness score and the Glasgow Coma Scale in critically ill patients: a prospective observational study. Critical Care. 2010;14(2):R64.
4. Traub SJ, Wijdicks EF. [Initial Diagnosis and Management of Coma](https://www.sciencedirect.com/science/article/pii/S073386271630058X?via%3Dihub). Emerg Med Clin North Am. 2016 Nov;34(4):777-793. doi: 10.1016/j.emc.2016.06.017. Epub 2016 Sep 3.
5. Wijdicks EF. The bare essentials: coma. Pract Neurol. 2010 Feb;10(1):51-60.