# Organ Donation {#sec-organdonation}

:::info
This is specific to organ donation in the Australian context.
:::

:::column-margin
This covers medical elements of organ donation. Discussing organ donation with family is covered in @sec-donorconvo.
:::

There are several principles that guide the process of organ donation in the Australian context, that arise from various bodies:

* Legislature
	* Organ donation should be an unconditionally altruistic and non-commercial act
	* Organ donation is an opt-out process\
	Evidence is unclear if changing to an opt-in model ↑ donation.
* ANZICS
	* No financial benefit should occur to any organisation or person from organ donation
	* Conditional donation should be refused\
	Family request that donation only goes to a certain sort of individual (positive condition) or not to a certain sort (negative condition).
	* Directed donation is permissible under certain circumstances\
	Donation after death of organs to a named individual.
	* Irrespective of patient's known wishes, the family should be contacted to discuss donation and donation should not proceed if the family does not agree
	* Tissue donation should be offered to the family of all dying patients in the hospital


## Principles

Organ donation:

* **Should not** be raised **prior to family understanding** of death or impending death
* **Should not** be raised **prior** to medical **consensus** for **end-of-life** care
* **Should be discussed** with **donation staff**, *prior* to discussion with family
* **Should be discussed** with **all families** where it is a possibility
	* Any information contained on the organ donor register should also be communicated to family


## Suitability

:::tick
All patients near to the end of life should be referred for consideration of organ donation.
:::

**Suitability** for organ donation **is**:

* **Highly dynamic**\
Varies with recipient/waiting list requirements; i.e. an otherwise ineligible donor may be accepted when an appropriate recipient is *in extremis*.
* **Without fixed criteria**\
Diseases commonly (but not exclusively) considered contraindications include:
	* Malignancy
	* Active infection
		* Meningococcal
		* Hepatitis
		* HIV


Information that should be provided to donation coordinator should include:

* Age
* Sex
* Weight
* Height
* Past history
	* Co-morbidities
	* Surgery
	* Medication
	* Alcohol
	* Smoking
	* Illicit drug use
* History of fatal illness
	* Cause
	* Details of cardiac arrest
	* End-organ injury
	* Aspiration
	* Periods of ischaemia
* Current clinical state
	* Organ supports
	* Bloodwork
	* Other investigations


### Heart Donation

The heart is highly susceptible to multiple insults that occur during brain death, and therefore most responsive to antemortem interventions.

::: Donor Heart criteria

+-------------------+---------------------------+----------------------------------+
| Parameter         | Standard                  | Marginal                         |
+===================+===========================+==================================+
| Age (years)       | <50                       | \>50                             |
+-------------------+---------------------------+----------------------------------+
| Cardiac History   | Nil                       | Present                          |
+-------------------+---------------------------+----------------------------------+
| Comorbidities     | Nil                       | * Hepatitis B                    |
|                   |                           | * Hepatitis C                    |
+-------------------+---------------------------+----------------------------------+
| Echocardiography  | Normal                    | * LVEF <50%                      |
|                   |                           | * Major RWMA                     |
|                   |                           | * LVH >13mm                      |
+-------------------+---------------------------+----------------------------------+
| Angiography       | * Normal                  | Occlusive disease                |
|                   | * Non-occlusive disesease |                                  |
+-------------------+---------------------------+----------------------------------+
| Inotropic support | Low                       | \>0.2μg/kg/min or noradrenaline\ |
|                   |                           | Or equivalent.                   |
+-------------------+---------------------------+----------------------------------+
| Ischaemic time    | <6 hours                  | \>6 hours                        |
+-------------------+---------------------------+----------------------------------+


### Lung Donation

: Standard Donor Lung Criteria

+----------------------+-----------------------------+
| Parameter            | Criterion                   |
+======================+=============================+
| Age (years)          | <60                         |
+----------------------+-----------------------------+
| Smoking (pack-years) | <20                         |
+----------------------+-----------------------------+
| Chest trauma         | Nil                         |
+----------------------+-----------------------------+
| Aspiration           | Nil                         |
+----------------------+-----------------------------+
| PaO~2~ (mmHg)        | \>300mmHg on 100% oxygen    |
+----------------------+-----------------------------+
| Sputum               | Nil                         |
+----------------------+-----------------------------+
| Bronchoscopy         | Clear or minimal secretions |
+----------------------+-----------------------------+

Lung preservation techniques:

* Pneumoplegia
	* Cold colloid solution is administered into the PA and PV
	* Flushes out clot
* Ex-vivo lung perfusion
	* ↑ Ischaemic time
	* May improve function of otherwise marginal organs


## Donation

Organ donation occurs after determination of patient death, which can be either:

* Brain death
* Circulatory death

: Comparison of Recipient Outcomes after Donation

+----------+------------------------+----------------------------+
| Organ    | Brain Death            | Circulatory Death          |
+==========+========================+============================+
| Lung     | - 97% 1-year survival  | - 97% 1-year survival      |
|          | - 90% 5-year survival  | - 90% 5-year survival      |
+----------+------------------------+----------------------------+
| Heart    |                        |                            |
+----------+------------------------+----------------------------+
| Liver    | - Better than DCD      | - 75% 5-year survival      |
+----------+------------------------+----------------------------+
| Pancreas |                        | - 83% 1-year survival      |
|          |                        | - 72% 5-year survival      |
+----------+------------------------+----------------------------+
| Kidney   | - ~86% 5-year survival | - ~86% 5-year survival     |
|          |                        | - ↑ Delayed graft function |
+----------+------------------------+----------------------------+


### Donation after Brain Death

:::info
Donation after brain death is also referred to as DND, or Donation after Neurological Death.
:::

DBD is only considered in patients with a diagnosis of brain death. DBD is:

:::column-margin
Preconditions and determination of brain death are covered in detail under @sec-braindeath.
:::

* The most common path for donors\
75-90% of total donors.
* Generally associated with improved recipient outcomes\
Compared with DCD donation.
* Easier to logistically coordinate\
More predictable than DCD.


### Donation after Circulatory Death

DCD is considered in a **ventilated patient** in whom **life-sustaining treatment** is to be **withdrawn**, and **death** is **likely** to occur **in** a **period** that **permits** organ retrieval for **transplantation**. DCD should:

* Only be considered after consensus reached that active treatment is no longer in the patients interest\
This should include any member of the donation, transplant, or retrieval teams.
* Not influence the administration of sedatives or analgesics
* Be raised with a family when:
	* End of life care is proceeding
	* The family are in favour of organ donation
	* The patient is likely to become brain dead, but has not yet become so

:::column-margin
DCD is divided into **four categories**:

* I: Dead on arrival
* II: CPR ceased
* III: Cardiac arrest expected soon\
Almost all donors in Australia, NZ, UK, and the US.
* IV: Cardiac arrest whilst brain dead


Donation other than class III are uncontrolled, and consequentially more ethically complex. Systems that emphasise utilitarian approaches, or only account for previously expressed wishes of the donor (disregarding family input) have some donations in category I and II.
:::

The nature of DCD donation creates additional complexities:

:::column-margin
Acceptable warm ischaemic times vary depending on the organ:

* Liver, pancreas: <30 minutes warm ischaemic time
* Heart: <30 minutes from SBP <90 mmHg to cold perfusion
* Kidneys: <60 minutes functional warm ischaemic time
* Lungs: <90 minute functional warm ischaemic time
:::

* **Warm ischaemic time**\
Period during which the organs are still warm with usual VO~2~, but hypoperfused. Warm ischaemic time is:
	* The time from circulatory arrest to the time of perfusion with cold preservation solution during retrieval
	* Associated with ↑ complications and ↓ graft function:
		* Delayed graft function
		* Primary graft dysfunction
		* Organ-specific ischaemia
			* Biliary strictures
	* Associated with two other similar terms\
	Same underlying physiology but different metrics:
		* **Agonal time**\
		Time from cessation of cardiorespiratory support until circulatory arrest. An agonal time **>90 minutes** usually **precludes donation**, and **occurs** in ~**30%** of patients.
		* **Functional warm ischaemic time**\
		Time from SBP <50mmHg to the time of cold perfusion.
* **Communication**
	* Where WCRS occurs
	* Unpredictability of timing
	* Potential failed donation
		* Medically inappropriate
	    * Warm ischaemia time exceeded
	    * May still donate tissue once death has taken place


### Antemortem Interventions

Some patients may receive interventions when:

* The patient is still alive
* The patient is expected to become an organ donor
* The intervention will ↑ organ viability


This is appropriate **only** if:

* The patient wanted to be an organ donor
* The family has made an informed decision, and consent obtained
* The interventions do not shorten life or compromise care
* Measures are taken to prevent pain or discomfort


### Process of Donation

1. Routine referral of all patients who are likely to die for suitability of organ donation\
This includes checking the organ donation register to ascertain the patients wishes.
2. Discussion with the family (and rarely, patient, if competent) that the patient is likely to die
	* In DBD, this may be raising the chance of brain death having occurred and the need to perform further testing to confirm this
	* In DCD, this may include discussion of futility of continuing treatment
	* The organ donation nurse should be invited to attend this meeting
		* This allows them to get to know and build rapport with the family
		* They are best introduced as a "specialist nurse" rather than an organ donation specialist if organ donation has not yet been raised
2. Determination of suitability of organ donation\
By the intensivist and donation team.
3. Discussion with the family about organ donation\
A separate conversation from the end of life conversation, which includes:
	* Donation process
	* Formal consent
	* If relevant, discussing:
		* Coronial consent
		* DCD
			* Risk of a failed donation if agonal time exceeded
			* Determination of death
		* DBD
			* The patient looks the same after determination of death\
			Warm, "breathing".
4. Donor assessment
	* Blood
	* Tissue typing
	* Other tests as suitable
5. Retrieval and transplant team meeting\
	* Brief discussion of the relevant details of the donors
	* Discussion of the recipients
	* Logistical plan
6. For DCD, the withdrawal of cardiorespiratory support
	* Negotiation of time and place\
	May occur:	
		* In ICU:
			* Family can be with the patient at time of death
			* Patient does not have to be moved if agonal time exceeded
			* Rapid transfer to the OR is required following death\
			May introduce delays that limit organ donation.
		* In OR:
			* Limit family presence
			* ↑ Speed of retrieval
		* Near the OR\
		Hybrid approach of the above.
	* Appropriate prevision of sedation and analgesia\
	Should be given by the intensivist, and not by the anaesthetist or transplant team.
	* The surgical team should not be present in the ICU
7. Organ retrieval
8. Transfer of the donor to the mortuary\
The donor will "look dead: afterwards; donors generally look the same on transfer to the OR.
10. Transfer of organs to the transplant centre
11. Implantation of retrieved organs to the recipient


---

## References

1. ANZICS. [The Statement on Death and Organ Donation](https://www.anzics.com.au/wp-content/uploads/2022/04/ANZICS-Statement-on-Death-and-Organ-Donation.pdf). Edition 4.1. 2021.
2. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.