# Paediatric Considerations

:::caution
This covers principles of paediatric critical care for the adult intensivist. In general:

* Principles of adult intensive care can be safely extrapolated to children
* Involve a paediatrician early for consideration of nuances
:::

:::column-margin
Paediatric anaesthetic considerations, including airway management, is covered in detail under @sec-paeds_anaes.
:::

Difference:

* Congenital anomalies are common
	* ~1% of children have a congenital anomaly
* Periodic breathing
	* Risk of apnoea
* Diaphragmatic reliance
	* Easily fatigued
* CO is HR dependent
	* Relatively fixed stroke volume
	* Unexplained, persistent tachycardia over 30 minutes to 4 hours is very concerning
	* Therapy that ↓ HR may precipitate profound shock
	* BP will commonly remain normal until shock is advanced


* Anticipate deterioration during intubation
* Suspect sepsis
* Suspect NAI
* Treat neonates for everything


* Sick enough for ICU referral demands a CXR
	* Mediastinal mass
	* Heart failure
	* Foreign body
	* Congenital abnormality


* 4/2/1 over-estimates fluid requirements
	* Give 50-70% of this in critically unwell


* Parental presence during resuscitation is generally helpful

## Respiratory Disease

* SpO~2~:
	* Normal: 90-95%
	* Pulmonary HTN: >95%
	* Chronic lung disease: 88-92%
	* Single ventricle/chronic heart: 75-85%
* CO~2~:
	* Consider ventilator dead space
	* Targets as adults

### Stridor

Croup:

* Acute clinical syndrome characterised by:
	* Stridor
	* Barking cough
	* Hoarseness
	* Respiratory distress
* Usually precipitated by viral infection:
	* Parainfluenza
	* RSV
	* Influenza
	* Adenovirus
* 1-5% are admitted
* Steroids\
↓ Need for hospitalisation, intubation, and duration of admission.
	* Dexamethasone 0.6mg/kg
	* Budesonide 2mg nebuliser
* Adrenaline 5mg nebuliser
* Intubation
	* Small ETT required
	* Gas induction in OT preferable


Epiglottitis:

* Softer stridor
* Unimmunised
* Drooling
	* Painful swallowing
* Require intubation


Bacterial tracheitis:

### Wheezing

Problems:

* Wheeze
	* Bronchiolitis
	* Asthma

* Inflammation vs. bronchospasm
	* Atelectasis
	* Dynamic hyperinflation



* May respond to salbutamol if <1 year of age, particularly if history of atopy
* NG feeding to 70%
* High flow oxygen 2L/kg
* Target SpO2 >90%

* Acute viral myocarditis
	* Not better with bronchiolitis treatment
	* Palpable liver
	* Deterioration with IV fluid bolus
* Pertussis
	* Apnoea common


Bronchiolitis:

* 10% of infants affected
* 2-3% admitted in first year of life
* Rare after 1 year of age
* Fever and clear nasal discharge
* INcreasing breathlessness
* Fine crepitations
* Supportive management
	* Fluid
	* Suction of nasal secretions
	* Humidified inspired gas
	* Prone positioning


## Cardiac Presentations

Heart Failure:

* Left to right shunts
* Hepatomegaly\
Sensitive and specific in small children for right heart failure.
* Murmurs
* Target SpO~2~ in low 90%s
	* Hyperoxia will ↓ PVR and ↑ left to right shunt


Severe cyanosis:

* Hypoxaemia non-responsive to supplemental oxygen
* No ↑ work of breathing
* "Black lungs" on CXR
	* Little pulmonary blood flow
* Need prostin
* Need atrial septostomy


Cardiogenic shock:

* Duct-dependent lesions
	* Rapid onset of poor perfusion
	* Absent femoral pulses
	* Floppy, acidotic baby
	* Intubation
	* Inotropes
	* Prostin infusion
	* Target SpO2 75-85%
	* Target palpable pulses and improved perfusion
	* Cover for sepsis
* Consider inotropes and invasive monitoring if more than 40mL/kg of resuscitation fluid is required


## Neurological

Seizure:

* Secure the airway
* Check glucose
* Check calcium
* Give benzodiazepine
	* If vascular access:
		* Lorazepam
	* If no vascular access:
		* Midazolam


## Metabolic Presentations

Four broad presentations:

* Hypoglycaemia:
	* Primary energy failure
* HAGMA
	* Intoxication
* Acute liver failure
* Encephalopathy and seizures

Management:

* Rule out sepsis
* NBM
* Stop catabolism
* Dextrose infusion
* Call for help


## Preparation

Emergency drugs:

* Adenosine 100-200μg/kg IV
* Dextrose\
3mL/kg of 10% dextrose IV.
* Hypertonic saline\
3mL/kg of 3% NaCl.
* Mannitol\
0.25-0.5g/kg (1.25-2.5mL/kg).
* Hydrocortisone\
2-4mg/kg up to 100mg Q6H.
* Lorazepam 0.1mg/kg up to 2 doses
* Midazolam 0.15mg/kg up to 2 doses
* Levetiracetam 40mg/kg up to 3g
* Phenytoin 20mg/kg up to 2g
* Tranexamic acid 15mg/kg up to 1g

---

## References

1. Smith S, Advanced Life Support Group (Manchester, England), editors. Advanced paediatric life support: a practical approach to emergencies. Seventh edition. Hoboken, NJ: Wiley-Blackwell; 2023.