# Drugs in Pregnancy

Drugs in pregnancy are:

* Used by 20-25% of women regularly
* Often not validated for use or safety, including anaesthetic drugs\
Drug trials are difficult to perform in pregnant women.

Drug interactions in pregnancy can be classified into:

* Pharmacokinetic
	* Absorption
		* PO absorption affected by nausea and vomiting
	* Distribution
		* ↑ V~D~ of water soluble drugs\
		Due to ↑ blood and body fluid volume.
		* ↑ free portion of acidic drugs\
		Due to ↓ albumin.
	* Elimination
		* ↑ renal clearance\
		Due to high GFR.
* Pharmacodynamic\
Most unchanged, except for:
	* Volatiles\
	↓ MAC.
	* Local anaesthetics\
	↓ neuraxial LA requirement.

* Foetal transfer via placenta
	* Almost all drugs cross the placenta to a certain degree\
	* Major determinants are concentration gradient, molecular weight, lipid solubility, degree of ionisation, protein binding, uteroplacental blood flow.
* Foetal transfer via breast milk


## Risk of Drugs in Pregnancy

Extent of effect depends on timing of consumption:

* 0-2 weeks\
Generally all or nothing effect:
	* Brief slowing of gestation with no overt ill effect
	* Spontaneous abortion\
* 3-8 weeks\
Period of organogenesis and potential for major abnormalities.
* Over 8 weeks\
Foetal period, effects include:
	* Physiological abnormalities
	* Minor morphological abnormalities

## Risk Categorisation System

The Australian risk categorisation divides drugs into:

* Category A\
Taken by a **large number** of pregnant women **without any observed ↑ in malformations** or other harmful effects.
* Category B\
Drugs which have been taken by a **limited number** of pregnant women, **without any ↑ in the frequency of malformations** or other harmful effects. Divided into three **subgroups based on animal data**:
	* B1\
	No observed foetal malformations in animals.
	* B2\
	No observed foetal malformations in animals, but studies were inadequate/data was lacking.
	* B3\
	↑ foetal abnormalities in animals, of uncertain human significance.
* Category C\
Caused/suspected to have **caused *potentially reversible* harmful foetal effects**.
* Category D\
Caused/suspected to have **caused ↑ foetal malformations** or **permanent** damage.
* Category X\
Such **high risk of causing foetal damage** that they should **not be used in pregnancy or** where there is a **possiblity of pregnancy**.

## Specific Drugs in Pregnancy

|Class|Category A|Category B1|Category B2|Category B3|Category C|Category D|Category X|Notes|
|--|--|
|**Antihypertensives**|Methyldopa||Prazocin <br>- Not recommended in 1^st^ trimester||Calcium channel blockers<br>β-blockers <br>- IGUR, ↓ HR, ↓ BSL, ↓ birth weight<br>Labetalol <br>- 1^st^ line<br>Hydralazine<br>- For hypertensive emergencies only|ACE-I/A2RB<br>- Contraindicated in all 3 trimesters<br>-1^st^ trimester: Major CVS/CNS malformations<br>-2/3^nd^ trimester<br>- Renal damage<br>-MSK deformities<br>- Death||
|**Anticoagulants**|||||Heparin/LMWH<br>- ↑ peripartum bleeding|Warfarin<br>- Terratogenic, particularly 6-9 weeks||
|**Anaesthetic agents**|Thiopentone<br>Ketamine||||Propofol<br>Benzodiazepines<br>- Not recommended in 1^st^ trimester<br>- Secreted heavily in breast milk||||
|**Corticosteroids**|Cortisone<br>Hydrocortisone<br>Prednisolone||||Dexamethasone<br>Betamethasone<br>Fludrocortisone<br>Tiamcinolone<br>- May ↑ oral cleft if used in 1^st^ trimester||||
|**Analgesics**|Paracetamol||||NSAIDS<br>- Avoid in 3^rd^ trimester as may cause premature duct closure, renal impairment, oligohydramnios, delayed labour||
|**Antiemetics**|Metoclopramide|Ondansetron<br>Granisetron<br>Dolasetron||Tropisetron|||||
|**Antibiotics**|Penicillins<br>Cephalosporins<br>Erythromycin|Roxithromycin||||Aminoglycosides<br>- Risk of foetal oto/nephrotoxicity<br>Tetracyclines<br>- Teeth staining, suppressed bone development|||
|**Volatile agents**|Halothane<br>Nitrous oxide||Sevoflurane|Isoflurane<br>Desflurane||||
|**Muscle relaxants**|Suxamethonium||Rocuronium<br>Pancuronium||Vecuronium<br>Cisatracurium<br>Atracurium|||Do not cross placenta; if foetal muscle relaxation required for foetal surgery then drug must be given to foetus|
|**Vasopressors**|Adrenaline<br>Ephedrine||Phenylephrine||Metaraminol|||Used whatever agent is best for the mother|
|**Antiarrythmics**|Digoxin||Adenosine||Amiodarone||||

---

## References
