# Trauma in Pregnancy

## Epidemiology and Risk Factors

Common causes include:

* MVA
* Assault
* Falls

## Pathophysiology

Altered maternal physiology confounds assessment of shock:

* ↑ Difficult airway
* ↑ Maternal blood volume\
Up to 50%.
* ↑ CO
	* ↑ HR
	* ↓ SVR
	* ↓ MAP
* ↑ VO~2~, CO~2~ production, and ↓ FRC
	* ↑ RR
	* ↓ PaCO~2~
* Uterus\
	* Vulnerable to injury after ~12 weeks when it expands into the peritoneum
	* Displaces bowel contents into upper abdomen, which may be injured in abdominal trauma
* Hypertrophy of pelvic vasculature
	* Massive retroperitoneal injury
* ↑ Stomach acid volume
	* ↑ Aspiration risk

### Aetiology

## Clinical Manifestations

## Diagnostic Approach and DDx

## Investigations

:::info
Radiation risk to the foetus should be weighted up against risk of missing an injury. In general:

* Life-threatening injures require the same imaging as in the non-pregnant patient
:::

**Bedside**:

**Laboratory**:

* Blood
	* Kleihauer\
	Determine risk of foetal-maternal haemorrhage.

**Imaging**:

**Other**:

* Continuous cardiotocography

## Management

**Resuscitation**:

**Specific therapy**:

* Pharmacological
	* **Anti-D**\
	For all Rhesus negative pregnant women who suffer trauma.
* Procedural
* Physical

**Supportive care**:

**Disposition**:

**Preventative**:


### Marginal and Ineffective Therapies

## Anaesthetic Considerations

## Complications

* O\
↑ Risk of:
	* Placental abruption
	* Foetal distress
	* Miscarriage

## Prognosis

## Key Studies


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.