# ANZCA Final Exam

The ANZCA final exam consists of a:

* Written examination
	* MCQs
	* SAQs
* Medical Viva
* Anaesthetic Viva



## Short Answer Questions

As with the primary examination, a structured answer format:

* ↑ The chance you will deliver a complete answer
* ↓ Stress
* Is less painful to read


Almost all questions can fit into one of **five structures**:

* The **Emergency**\
A crisis of some kind.
	* "This is an emergency"
	* Immediate actions
	* Send for help
	* Simultaneous diagnosis and treatment
	* An ABC approach
* **Anaesthetic plan for *a* patient**
	* Pre-op and induction
	* Intra-op and maintenance
	* Post-op and emergence
* **Anaesthetic plan for *this* patient**\
Pre-operative management, use:
	* History
	* Examination
	* Investigations
	* Referral
* **Issues for *this* patient**\
This is the Cluedo patient: The appendix, with the Fontan, in the regional centre.
	* Patient factors
	* Anaesthetic factors
	* Surgical factors
* **Assessment and management of a disease process**\
Use a system based answer:
	* Airway considerations
	* Respiratory considerations
	* Etc


Additional structures for specific questions include:

* **Welfare question**\
When answer a welfare question for the ANZCA Part II Exam; aim:
	* Protect the patient
	* Protect the doctor
	* Short-term measures
	* Long-term measures
* **Legal question**
	* Identify the issue
	* State the legal and ethical principles that apply
	* Apply principles to facts of case & balance conflicting arguments
	* Make a conclusion
		* Seek help
	* Close the loop
* **Regional technique**\
Use the PRECIOUS mnemonic:
	* Position
	* Risk
		* General
			* Infection
			* Bleeding
			* Local anaesthetic toxicity
			* Nerve injury
		* Specific\
		e.g. Pneumothorax.
	* Equipment
	* Consent and **block time out**
	* IV
	* Oxygen and monitoring
	* Ultrasound
	* Sedation
* **Introduction of new procedure**
	* Consult regulatory authorities
	* Set up local hospital group
		* Anaesthetists
		* Surgeons
		* Nurses
		* Administrators
	* Formulate local protocols
	* Policies for selection of patients
	* Dedicated/separate ward facilities
	* Equipment appropriate for task
	* Consultation with other hospitals for advice and review
	* Slow implementation
	* Ongoing formal review and audit

## Medical Viva


## Anaesthetic Viva

Process:

* A 'realistic' patient scenario which evolves overtime
* Tests the candidate at multiple points with dilemmas and disasters
* Examines depth, breadth, and integration of knowledge
* Aims to **assess judgment** and **decision making**
* A professional discussion with a colleague
* Tests if you are **ready** to **be a consultant**\
Evaluates your:
	* Knowledge
	* Safety
	* Leadership
	* Patient advocacy
	* Collaborative approach
	* Professional


Structure:

* Eight 15 minute vivas
	* 2 minutes reading time\
	Immerse yourself in the stem:
		* Your role\
		Not always the anaesthetist.
		* Your location\
		Resources.
		* Your patient\
		Equipment sizes, drug dosing.
		* Your resources
	* Bells indicate start and end of viva
	* One examiner, often an observer
* Required to pass viva to pass exam
* Similar layout to primary exam


Dilemmas and Decisions:

* Tricky situations
* Not all unstable clinical situations requires the emergency buzzer\
But press it when you need to.
	* Failure to act safely is viewed very poorly
* Patients will deteriorate irrespective of how you are performing


Tips:

* Think like a consultant
* Have confidence or fake confidence
* Enter a dialogue with the examiner - they are a colleague, not a boss
* Immerse yourself in the scenario
* Take some time to think of an answer\
Not too much.
* Can discuss balance of risks without waffling
* Be authentic
* If you are unsure of a course of action, then describe your rationale
* Have some handy phrases
	* "In addition to my usual anaesthetic assessment..."
* Know what to say if you don't know what to do


Pitfalls:

* Attitude
	* Non-consultant like
	* Indecisive\
	Using 'could' not 'would.'
	* Inflexible
		* Refusing to be lead
	* Waffling
	* Too many lists
	* Does not answer question
* Knowledge
	* Insufficient
	* Long checklists do not demonstrate understanding
	* Inaccurate
	* Not recognising knowledge gaps\
	Demonstrates lack of safety.
* Safety
	* Inappropriate drug doses
	* Does not know how to manage a crisis
	* Lacks insight
	* Refuses to accept guidance


---
