# CICM Final Exam

The CICM final exam consists of a:

* Written exam\
Aims to **assess knowledge**.
	* Two 150 minute/15 question SAQ papers
	* 10 minutes reading time
* Oral viva\
Aims to **assess judgment**.
	* Eight 10 minute stations\
	Always:
		* Radiology
		* Communication
			* Consistently has a high maximal mark\
			Opportunity to do very well.
			* Determine what sort of meeting this is
		* Equipment
	* 2 minutes reading time per station
		* Radiology viva reading time is reviewing images
	* Break stations
		* 1 break after communication station
* Hot case\
Aims to **assess wisdom** and real-world clinical decision making.


## Timing

{{< include /includes/timing.qmd >}}


## Written Exam

{{< include /includes/written.qmd >}}


### Glossary of Terms

These verbs detail the expectations for the answer:

:::column-margin
Re-read the question half-way through your answer - make sure you are answering the question that is asked.
:::

* **Critically evaluate**\
Evaluate the evidence available relating to a topic.\
\
* **Outline**\
Provide a summary of the important points.
	* Breadth > depth\
\
* **List**\
Provide a list.\
\
* **Compare and contrast**\
Provide a description of similarities and differences. You may tabulate your
answer.
	* Provide a **description** of similarities and differences, not just a list
	* Detail the significance of these differences

:::column-margin
If the question says you *may* tabulate your answer, you **should** tabulate your answer.
:::

* **Assessment**\
Generic term that implies determining an underlying diagnosis, encompassing; history, clinical examination, and relevant investigations.
	* History
	* Examination
	* Investigations
	* Prioritised differential diagnosis
	* Indicators of severity\
\
* **Management**\
Generic term that implies determining an overall management plan, encompassing; resuscitation, definitive treatment, initial and ongoing monitoring with supportive treatment.
	* **Principles**
	* **Treatment Priorities**
	* **Resuscitation**\
	ABC approach. Comment on team coordination.
	* **Specific therapy**
		* Pharmacological
		* Procedural
		* Physical
	* **Supportive care**
	* **Disposition**\
\
* **Discuss**\
Explain the underlying key principles. Where appropriate, this may include controversies and/or advantages and disadvantages.
	* Depth > breadth
	* Controversies
	* Pros and Cons\
\
* **Explain**\
Make plain, interpret, account for.
	* Reference to underlying theory and rationale
	* Contextualised to the clinical scenario


### Answer Templates

Structures for specific question formats:

* **Adverse outcome**
	* Manage the patient
		* Resuscitation
		* Prevent further harm
	* Administrative
		* Patient and relatives\
		No fault apology and open disclosure.
		* Staff
		* Department\
		e.g. QI, M&M.
		* Document
* **Critically evaluate**
	* Rationale\
	Importance of the issue, e.g.
		* Prevalence of disease
		* Pathophysiology
		* Unique features of the therapy
	* Advantages of the intervention
	* Disadvantages of the intervention
	* Evidence
		* Pros and cons of trials
		* Limitations of trials
		* Special situations
	* Own practice
* **Toxin**
	* **R**esuscitation
	* **R**isk assessment
	* **S**upportive Care
	* **I**nvestigations
	* **D**econtamination
	* **E**nhanced Elimination
	* **A**ntidotes
	* **D**isposition


## Oral Exam

### Viva

{{< include /includes/viva.qmd >}}

:::column-margin
:::tick
Complete the CICM Communication Course prior to the exam; the communication viva scenario generally mirrors the course scenarios; although breaking *catastrophic* news is unlikely.
:::
:::

### Hot Case

The hot case is the only part of the exam that assesses a candidate at the bedside. Hot cases are:

* Challenging
* Artificial
* Incompletely correlated with clinical skill\
Hot case performance does not equal clinical performance, however hot case practice ↑ hot case performance.
* Routinely performed poorly
	* 60-70% of candidates pass
	* Only 30% of candidates pass both cases
* Composed of several stages:
	* **Clinical question**\
	Brief stem with incomplete information, and a clinical question.
	* **Reading time**\
	2 minutes. Decide:
		* What **potential clinical problems** may this patient have?
		* What **part** of the **exam**ination should be **focus**ed on?
		* Likely follow-up questions
	* **Entrance**
		* Lights
		* Gel hands
		* Introduce yourself:
			* To the patient
			* To the nurse
		* Ask about relevant **position restrictions** and **languages barriers**
	* **End-of-bed-o-gram**\
	Stand at the foot of the bed and identify key room equipment.
	* **Orbit**\
	Circle the bed space to identify:
		* Infusions
			* Nutrition
		* Ventilation\
		Ask about:
			* **Sputum**
			* Ventilator settings, if unfamiliar
		* Monitor\
		Ask for **fevers**.
		* Catheters and drains\
		Ask for:
			* **Urine output**
	* **Clinical examination**\
		* Begin with adequate exposure
		* Structured approach
		* Can ask key, targeted, relevant questions\
		Must be balanced.
			* Too many unnecessary or boilerplate questions suggest a lack of direction or thought
			* Too few questions means key information may not be provided
	* **Intermission**\
	Brief period during which:
		* PPE is doffed
		* Hand hygiene occurs
		* The clock is stopped
		* You can collate your thoughts and prepare the presentation
	* **Presentation**\
	3-5 minute presentation that should be concise, comprehensive, and *rapidly* delivered. Consists of:
		* A **brief**, 1-2 sentence **introduction** that provides an overview of the clinical scenario
		* **Answers the question**\
		This should occur even if the answer is not clear - it will often be contingent on the availability and interpretation of ancillary information.
		* Provides a **rationale** for the answer\
		Signposted, systematic description of the justifications for that answer.
		* Outlines any **caveats**\
		Signposted, systematic list of any concerns that may impact your decision, and how you plan to investigate them.
		* A list of relevant positive and negative findings from the clinical examination
	* **Further questioning**

:::column-margin
The end-of-bed-o-gram and orbit provide the majority of useful clinical information, do not neglect them. Touching the patient is expected to occur at some point however, usually by the 2-3 minute mark.
:::

:::column-margin
```{mermaid}
%%| fig-width: 100% #Hacky solution; NaN defaults to 100% width
%%| fig-height: 100%

%%{ init: {
    'flowchart': { 'curve': 'stepAfter', 'useMaxWidth': 'true'},
    'theme': 'base',
    'themeVariables': {
        'primaryColor': '#ffffff',
        'primaryTextColor': '#000000',
        'primaryBorderColor': '#000000',
        'lineColor': '#000000',
        'tertiaryColor': '#fff'
        }
    }
}%%

flowchart TD
    A[End-of-bed-o-gram] --> B[Orbit]
    B --> C[GCS]
    C --> D{"**Decide**:
    Detailed
    Neurological
    Exam?"}

    D -- Yes --> F[Detailed Neurological Exam] --> H[Targeted System Exam]
    D -- No --> G[Detailed Systems Exam] --> I[Targeted Neurological Exam]
```
:::

:::column-margin
The hot case is like a tennis match in that the only part of the game that you can control is the serve - these are the examination and the opening of the presentation. Maximise this time.
:::


---

## References

1. Hoffman, K. [How the Hot Case Works](https://intensiveblog.com/how-the-hot-case-works/). Intensive. 2021.