# Acromegaly


Chronic progressive multisystem disease caused by excess growth hormone.

## Epidemiology and Risk Factors

## Pathophysiology

Excessive growth hormone secretion occurring after puberty.


### Aetiology

## Clinical Manifestations

Usually presents in an advanced stage at middle age. Symptoms may be due to:

* Mass effect of pituitary
* Hormone excess


## Diagnostic Approach and DDx

## Investigations

## Management

### Anaesthetic Considerations

* A
	* Usually straightforward mask ventilation\
	Small hands may struggle.
	* Potential difficult laryngoscopy
		* Macrognathia
		* Macroglossia
		* Soft tissue bulk
		* ↑ Size epiglottis
	* AFOI may be preferable
	* Soft tissue enlargement\
	Ask about **vocal changes**.
* B
	* OSA\
	Present in up to 70%.
	* Restrictive lung disease due to kyphoscoliosis
* C
	* Treatment-resistant hypertension\
	Occurs in 40%. Leads to secondary:
		* Eccentric LV hypertrophy\
		Preoperative TTE beneficial.
	* Ischaemic heart disease
	* Arrhythmias
* E
	* Proximal myopathy\
	May limit respiratory function.
	* Entrapment neuropathy\
	Peripheral nerve compression.
	* Difficult cannulation
* E
	* Associated endocrine disease
		* Diabetes
		* Thyroid dysfunction
		* Adrenal dysfunction

### Marginal and Ineffective Therapies

## Complications

## Prognosis

## Key Studies


---

## References

