# Adrenal Insufficiency

Adrenal insufficiency is a clinical syndrome of cortisol and aldosterone deficiency and may be divided into:

* **Primary** adrenal insufficiency (**Addison's Disease**)\
**Hypofunction** of the **adrenal cortex** resulting in ↓ in glucocorticoid and mineralocorticoid secretion.
* **Secondary** adrenal insufficiency\
**Hypofunction** of the **pituitary**, resulting in ↓ in ACTH and subsequent steroid release.
* **Relative** adrenal insufficiency\
**Normal function** of the **entire HPA axis**, but the **cortisone** secretion is **inadequate** for the **degree** of physiological **stress**.

:::column-margin
Primary adrenal insufficiency is rare overall, and vanishingly rare as the cause in an ICU patient.
:::

:::column-margin
**Acute adrenal insufficiency**, or **Addisonian crisis**, occurs when there is an *rapid* fall in adrenal hormones from any cause.
:::

## Epidemiology and Risk Factors

* ~5-10 crises per 100 patient-years

## Pathophysiology

In health, the adrenal cortex is responsible for production of steroid hormones:

* Under the control of the HPA axis
	* CRH release from the hypothalamus stimulates ACTH release from the pituitary\
	* Stimulation is ↑ during critical illness, resulting in ↑ plasma cortisol
* Including:
	* Cortisol\
	Usually secreted:
		* In pulses
		* With a diurnal pattern
			* Peak at ~0800 hours
			* Trough at ~0100
		* Under the influence of ACTH\
		Negative feedback mechanism exists.
		* At 15-30mg/day
	* Aldosterone
	* Sex steroids\
	Relatively unimportant in critical illness.


### Aetiology

**Primary adrenal insufficiency**:

:::column-margin
**Adrenal crisis** generally occurs in a patient with known adrenal insufficiency who experience physiological stress without adequate stress-dose steroid supplementation.\
\
About half of patients presenting with adrenal crisis have undiagnosed primary adrenal insufficiency.
:::

* **Autoimmune**\
Most common in Western world.
* Infections
	* **TB**\
	Most common worldwide.
	* CMV
	* Histoplasmosis
	* Coccidiomycosis
* Adrenal haemorrhage\
Waterhouse-Friderichsen syndrome.
	* Sepsis\
	Meningococcal septicaemia, also known as Waterhouse-Friderichsen syndrome.
	* APS
	* Trauma
	* Surgery
* Infiltrative
	* Tumour
	* Amyloid
	* Sarcoid
	* Haemachromatosis
* Drug related
	* Inhibition of cortisol synthesis
		* Etomidate
		* Fluconazole
	* Induce cortisol metabolism
		* Rifampicin
		* Phenytoin
* Congenital
	* Adrenal dysgenesis


**Secondary adrenal insufficiency**:

* Cessation of exogenous glucocorticoid
* Pituitary disease
	* Surgery
	* Infarction
		* Sheehan's syndrome
	* Pituitary tumour




## Clinical Features

**Adrenal crisis** is a catastrophic syndrome characterised by:

* **Refractory shock**
* **Poor response** to **vasopressors**

:::column-margin
Many patients with primary deficiency will present with an adrenal crisis, due to the vague symptomatology of evolving disease.
:::

Presentation without an adrenal crisis is usually non-specific and ill-defined. Subtypes of adrenal insufficiency vary with their features:

* Primary adrenal insufficiency is the only cause that produces **hyperpigmentation**\
Only form with ↑ ACTH production.
* Secondary adrenal insufficiency typically does not result in substantial mineralocorticoid deficiency, and remains a primarily cortisone-deficient state

: Features of Adrenal Insufficiency

+----------------------------------------------------------------------------------------------------------------------------------------+------------------------------------+------------------------+
| Specific to Cortisone Deficiency                                                                                                       | Specific to Aldosterone Deficiency | Non-specific           |
+========================================================================================================================================+====================================+========================+
| * Hypotension\                                                                                                                         | * Hyponatraemia                    | * Weakness             |
| Refractory to fluids and vasopressors.                                                                                                 | * Hyperkalaemia                    | * Weight loss          |
| * Hypoglycaemia                                                                                                                        | * NAGMA\                           | * Anorexia             |
| * Eosinophilia                                                                                                                         | Type 4 RTA.                        | * Diarrhoea            |
| * Hyperpigmentation\                                                                                                                   |                                    | * Abdominal pain       |
| Due to ↑ ACTH, which stimulates melanogenesis. First evident on mucous membranes, then non-sun exposed areas, followed by normal skin. |                                    | * Nausea               |
|                                                                                                                                        |                                    | * Normocytic anaemia   |
|                                                                                                                                        |                                    | * Postural hypotension |
+----------------------------------------------------------------------------------------------------------------------------------------+------------------------------------+------------------------+


## Diagnostic Approach and DDx

## Investigations

**Bedside**:

* ABG
	* NAGMA
	* Hyponatraemia
	* Hyperkalaemia

**Laboratory**:

* Blood
	* FBE
		* Anaemia
	* UEC
		* Hyponatraemia
		* Hyperkalaemia
	* Random cortisol\
	In adrenal crisis would be expected to be <80nmol/L; ACTH stimulation testing is not required.
	* **ACTH stimulation test**\
	In a stable patient:
		* Administer 250μg of tetracosactrin (Synacthen)
		* Measure cortisol at 0 and 30 minutes
		* Appropriate elevation in peak cortisol should be seen\
		Threshold varies depending on the laboratory.
			* Hydrocortisone interacts with many assays and so cannot be used
			* Dexamethasone can be used as an alternative steroid if planning the test


**Imaging**:

* MRI
	* Adrenal glands

**Other**:

## Management

:::priority
* Steroid supplementation
* Correct hypovolaemia and electrolyte abnormalities
:::

**Specific therapy**:

* Pharmacological
	* **Glucocorticoids**
		* 100mg hydrocortisone IV Q6H\
		This provides adequate mineralocorticoid replacement.
* Procedural
* Physical

**Supportive care**:

* C
	* Volume resuscitation\
	Normal saline ideal.
	* Vasopressors
* E
	* Correct BSL
* F
	* Electrolyte correction

**Disposition**:

* Endocrinology involvement
* Long-term glucocorticoid therapy

**Preventative**:


### Marginal and Ineffective Therapies

## Anaesthetic Considerations

## Complications

## Prognosis

## Key Studies


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.
1. Rathbun KM, Nguyen M, Singhal M. [Addisonian Crisis](https://www.ncbi.nlm.nih.gov/books/NBK441933/). In: StatPearls. StatPearls Publishing; 2023. Accessed August 2, 2023.