# Hyperthyroidism {#sec-hyperthyroid}

Disease of excess thyroid hormone, which leads to a constellation of symptoms. Hyperthyroidism may be classified into:

:::column-margin
This covers general considerations of hyperthyroidism; thyroid storm is covered at @sec-thyroidstorm.
:::

* **Primary**\
Excess secretion of hormone from thyroid gland, further divided into:
	* Overt\
	Elevated thyroid hormone with suppressed TSH.
	* Subclinical\
	Normal thyroid hormone levels with suppressed TSH.
* **Secondary**\
Excessive TSH production from pituitary gland.

## Epidemiology and Risk Factors

Risk factors:

* Female:Male is 2:1

## Pathophysiology

### Aetiology

Include:

* Grave's disease
* Toxic nodular goitre
* Thyroiditis
* Drug induced
	* Amiodarone

## Clinical Manifestations

### History

### Examination

## Diagnostic Approach and DDx

## Investigations

## Management


## Anaesthetic Considerations

* B
	* ↓ Apnoea time due to ↑ VO~2~
* C
	* ↑ HR
	* Arrhythmia
		* AF
	* CCF
	* IHD
* E
	* Heat intolerance
	* Weight loss
* E~2~
	* Thyroid state\
	Patients should be euthyroid preoperatively to avoid thyroid storm.
		* Carbimazole\
		↓ Iodine uptake and inhibits peroxidase enzyme, preventing iodine coupling.
		* Propothiouracil\
		Inhibits thyroperoxidase, and also ↓ T~4~ to T~3~ conversion.
		* Steroids\
		↓ T~4~ to T~3~ conversion.
		* Lugol's Iodine
		* β-blockers
	* Thyroid storm may occur up to 18 hours post-operatively


### Marginal and Ineffective Therapies

## Complications

* C
	* AF\
	10-40% incidence.
	* Palpitations
	* CHF
* E
	* ↑ Incidence of myasthenia gravis
	* Thyroid storm
* H
	* Thyrombocytopenia
	* Anaemia

## Prognosis

## Key Studies


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.
