# Hypothyroidism


## Epidemiology and Risk Factors

## Pathophysiology

### Aetiology

Include:

* Iodine insufficiency
* Autoimmune thyroiditis
	* Hashimoto's Thyroiditis  
	Antibodies against peroxidase and thyroglobulin.
* Treatment of hyperthyroidism
* Drugs
	* Amiodarone
	* Lithium
* Pituitary failure

## Clinical Manifestations

### History

### Examination


### Myxoedema Coma  

Hypothyroid crisis:
## Diagnostic Approach and DDx

## Investigations

## Management

### Anaesthetic Considerations

* A
	* Tracheal compression  
	Gotires may impinge on trachea and impede airway management.
* B
	* Reduced response to ↑ CO~2~ and ↓ O~2~
* C
	* Bradydysrhythmia
	* Diastolic HTN
	* Diastolic dysfunction
	* Abnormal baroreceptor function
	* Contracted plasma volume
* D
	* Depression
	* Hypoglycaemia
	* Sensitive to anaesthetic agents
* E
	* Myxoedema coma  
	Hypothyroid crisis.
	* Hypothermia
* E~2~
	* Addisons disease  
	Occurs in 5-10% of patients with severe hypothyroidism.
* F
	* Hyponatraemia
* H
	* Anaemia

### Marginal and Ineffective Therapies

## Complications


### Myxedema Coma

Exacerbation of hypothyroidism that:

* May be life threatening  
Mortality >50%.
* Manifests with:
	* Hypoventilation and subsequent hypoxia
	* Bradycardia and hypotension
	* Altered mental state  
	Apathy, coma.
	* Hyponatraemia
	* Hypothermia
* Requires emergent maagement with:
	* Supportive therapy
		* Intubation and ventilation  
		For hypoxia and hypoventilation.
		* Cautious volume expansion  
		For hypotension. Risk of APO.
		* Pacing or chronotropic agent  
		Again, cautiously.
		* Rewarming
		* Correction of BSL
	* Curative therapy
		* Thyroxine  
		200-500μg of L-thyroxine as loading dose, followed by 100-300μg the following day.
			* Monitor TSH level for response
		* Tri-iodothyronine  
		If thyroxine unavailable.
		* Hydrocortisone  
		100-300mg IV QID.

## Prognosis

## Key Studies


---

## References
