# Hypothermia

Hypothermia is a core body temperature <35°C which is:

* Due to either:
	* Abnormal thermoregulation
	* Heat loss despite thermoregulation
* Arbitrarily classified by degree:
	* Mild: 32-35°C
	* Moderate: 28-32°C
	* Severe: <28°C



# Disease


## Epidemiology and Risk Factors

## Pathophysiology

Hypothermia has pathophysiological effects on all organ systems:

* B
	* ↓ RR
	* ↓ VO~2~
	* ↓ PaCO~2~\
	↑ CO~2~ solubility.
* C
	* ↓ HR and CO
	* ↑ QTc
	* J-point elevation
	* Arrythmias
		* AF
		* VF
	* ↑ Defibrillation threshold
	* Vasoconstriction
		* Centralisation of blood volume
* D
	* Confusion → obtundation
	* ↑ Seizure threshold
	* ↑ BSL
* F
	* ↓ Vasopressin synthesis
	* ↑ pH
* G
	* ↓ Drug metabolism
* H
	* ↑ Haematocrit
		* ↑ Blood viscosity
	* Neutropaenia
	* Thrombocytopaenia
	* Coagulopathy 
* I
	* Shivering


### Aetiology

: Mechanisms of Hypothermia

+--------------------------------------------------+-------------------+---------------------------+
| ↑ Heat Loss                                      | ↓ Production      | Abnormal Thermoregulation |
+==================================================+===================+===========================+
| * Radiation\                                     | Endocrine:        | * CNS disruption          |
| ↓ Temperature of external environment.           |                   | * Drug toxicity           |
| * Conduction\                                    | * DKA             | * Uraemia                 |
| ↑ With high heat-capacity surrounds, e.g. water. | * Hypoadrenalism  | * Critical illness        |
| * Convection\                                    | * Hypothyroidism  | * Sepsis                  |
| ↑ Effect of conduction.                          | * Hypopituitarism | * Malignancy              |
| * Evaporation\                                   |                   |                           |
| \                                                |                   |                           |
| * Vasodilatation                                 | Reserve:          |                           |
| * Skin barrier disruption\                       |                   |                           |
| Burns.\                                          | * Hypoglycaemia   |                           |
| \                                                | * Malnutrition    |                           |
| * ↑ Surface area:Volume\                         | * Extremes of age |                           |
| Children.                                        |                   |                           |
|                                                  | Immobility        |                           |
|                                                  |                   |                           |
+--------------------------------------------------+-------------------+---------------------------+


## Clinical Features

* B
	* Apnoea
	* Hypoventilation
	* Pulmonary oedema
* C
	* ↓ BP
	* ↓ HR
	* ↓ Capillary return
	* AF
	* Asystole
* D
	* Obtundation
	* ↑ Tone
	* Abnormal plantar response
	* Fixed, mid-dilated pupils
* F
	* ↑ Followed by ↓ urine output
* G
	* ↓ Bowel sounds


## Assessment

**History**:

**Exam**:

### Investigations

**Bedside**:

**Laboratory**:

**Imaging**:

**Other**:


### Diagnostic Approach and DDx

## Investigations

**Bedside**:

* ABG\
	* ↓ Core body temperature ↑ solubility of CO~2~ and ↓ PaCO~2~ in vivo\
	Samples will be warmed to 37°C in the analyser, providing a spuriously high result.
* Temperature measurement

:::column-margin
{{< include /includes/temp_measurement.qmd >}}
:::

**Laboratory**:

**Imaging**:

**Other**:

## Management

:::caution
Good neurological outcome can occur following prolonged resuscitation in patients with severe hypothermia. Changes to ALS in this cohort include:

* Prioritise rewarming
* Brief interruptions of CPR acceptable if <28°C
* Delivery of up to 3 shocks and then withholding until 30°C
* Withholding ALS drugs until 30°C
* Doubling ALS drug interval until 35°C
:::

**Resuscitation**:


**Specific therapy**:

* Pharmacological
* Procedural
* Physical
	* Rewarming\
	Note that warming IV fluids is important to prevent further heat loss but ineffective at rewarming.
	* Avoid sudden movements\
	May precipitate arrhythmia.

:::column-margin
+-----------------+------------------------------+------------------------+
| Class           | Method                       | Rate of Change (°C/hr) |
+=================+==============================+========================+
| Passive         | Warmed external environment  | 0.5-1                  |
+-----------------+------------------------------+------------------------+
| Active External | Forced-air warmers           | 1                      |
|                 +------------------------------+------------------------+
|                 | Radiant heaters              | 1-2                    |
|                 +------------------------------+------------------------+
|                 | Temperature control pad\     | 1.5-3                  |
|                 | e.g. Arctic sun.             |                        |
+-----------------+------------------------------+------------------------+
| Active Internal | Humidified warm inspired gas | 0.5-1                  |
|                 +------------------------------+------------------------+
|                 | Intravascular catheter       | 2-4                    |
|                 +------------------------------+------------------------+
|                 | Body cavity lavage           | 3-5                    |
|                 +------------------------------+------------------------+
|                 | CPB/ECMO                     | 10                     |
|                 +------------------------------+------------------------+
|                 | RRT                          | 10                     |
+-----------------+------------------------------+------------------------+

: Comparison of Rewarming Therapies
:::


**Supportive care**:

**Disposition**:

**Preventative**:


### Marginal and Ineffective Therapies

## Anaesthetic Considerations

## Complications

* C
	* Arrhythmia
		* During cooling
		* During rewarming
		* With sudden movement or invasive ventilation\
		Sudden redistribution of warmed external blood into cold core.
* D
	* ↑ ICP

## Prognosis

## Key Studies


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.