# Poisoning {#sec-tox}

Acute poisoning is common and usually intentional. Key principles of management include:

:::column-margin
This covers the general principles of approaching a poisoned patient. Management of specific agents is covered elsewhere.
:::

* **R**esuscitation
* **R**isk assessment
* **S**upportive Care\
Principles of supportive care for the ICU patient.
* **I**nvestigations
* **D**econtamination
* **E**nhanced Elimination
* **A**ntidotes\
Covered under the specific drug overdose.
* **D**isposition


## Resuscitation

:::caution
Most poisonings should be treated on the basis of observed clinical toxicity rather than measured plasma drug concentrations.
:::

* A
	* Remove dentures
	* Clear oropharynx
	* Tracheal **intubation** for patients with compromised respiratory or neurological state
* B
	* Supplemental oxygen
	* Respiratory acidosis generally indicates need for assisted ventilation
* C
	* Venous access
	* **Fluid resuscitation** is first line **for hypotension**
	* **Arrhythmias** should **generally not be treated with antiarrythmics** as a first line approach\
	Many antiarrythmics are pro-arrhythmic and negatively inotropic.
	* Cardiovascular monitoring
	* Consider invasive haemodynamic monitoring
* D
	* Benzodiazepines\
	Are beneficial in many toxidromes for managing:
		* Seizures
		* Agitation
		* Hyperthermia
	* Correct severe hypoglycaemia with 50mL 50% dextrose
	* **Naloxone** can be used as a **diagnostic tool**
* E
	* **Cool** if **>39°C**
* F
	* Maintain good UO\
	Will optimise renal clearance.
	* Correct electrolyte abnormalities\
	Minimise any arrhythmias.

:::column-margin
Intubation is reasonable to avoid in patients with a GHB or GBL overdose who will reliably resume consciousness in 2-4 hours.
:::

:::column-margin
Hyperthermia may precipitate rhabdomyolysis, acute renal failure, and DIC.
:::

## Risk Assessment

:::priority
* **Ascertain nature** and **severity** of **poisoning**
* **Requirement** for **specific therapy** or time-limited interventions
:::

### History

:::column-margin
Collateral and circumstantial history can be ascertained from:

* Family
* Medicine cabinet
	* Counting missing tablets
	* Checking medical records and pharmacy prescription
:::

* Drug factors
	* Drugs taken\
		* May be multiple or unknown (children)
		* Always assume the maximum amount if uncertain
	* Dose
	* Time since ingestion
	* Dose
* Patient factors
	* Liver impairment
	* Renal impairment
	* Psychological morbidity

:::column-margin
Consider **NAI** in **children**.
:::

### Examination

:::column-margin
Differential diagnoses of coma should include:

* ICH
	* SAH
	* EDH
	* SDH
* Meningitis
* Encephalitis
* Diabetic coma
* Uraemic encephalopathy
:::

* General
	* Needle marks
	* Self-harm
	* Heart rate
	* Blood pressure
	* Respiratory rate
* Neurological exam
	* GCS
	* Qualitative evaluation of conscious state
	* Pupil size
	* Tone, reflexes, and clonus


## Investigations

**Bedside**:

* **BSL**
* ABG/VBG
	* Acid-base status
		* Metabolic acidosis
		* Respiratory acidosis
		* Respiratory alkalosis\
		Classically in early salicylate overdose.
	* Anion gap
* **ECG**


**Laboratory**:

* Biochemistry
	* Renal function\
	Affects clinical course of most drug overdoses.
* Drug levels\
For specific poisonings.
* Urine\
Retain sample for later analysis.

:::column-margin
Routine toxin dipsticks are not recommended due to the high false-positive rate and cross-reactivity with prescription medicine.
:::


**Imaging**:

* CXR
	* Aspiration


## Decontamination

:::info
**Viable** methods include:

* Activated charcoal
* Whole bowel irrigation
* Surface decontamination
:::

:::column-margin
Historically, two other methods were used but **no longer recommended**:

* **Induced emesis**\
Removes only limited volumes and ↑ aspiration risk.
* **Gastric lavage**\
Removes insignificant volume, may propel unabsorbed poison into small intestine.
:::

### Activated Charcoal

* Very effective absorber of toxins in GIT due to high surface area and porous structure
* 1^st^ line for most poisonings\
	* Effective absorber of 100–1000Da compounds that present early, or delay gastric emptying
	* Drugs that are **not effectively removed** include:
		* Alcohols
		* Metals
		* Corrosives\
		Acids and alkalis.
		* Pesticides
		* Cyanide
* Single dose should be **given** to **all patients within 1 hour** of **ingestion** of a toxic dose\
Efficacy falls with time since ingestion - give early.
* 1g/kg up to 50g
	* May still be given if overdose ↓ gastric emptying or slow-release preparation\
	e.g. Opioids, anticholinergics, TCA.
* **Multi-dose activated charcoal** is **useful** for drugs that are **enterohepatically recirculated** or a **slow-release preparation**\
Repeated dose of charcoal used Q4H, with concurrent use of sorbitol with the first dose to ↓ risk of obstruction.
* Serious complications are rare, however:
	* Should **not be given** if **↓ GCS** due to risk of **aspiration**\
	Intubate, then administer via NG.
	* May cause bowel obstruction
		* Rare
		* More common with multi-dose and ↓ gut motility
	* May absorb therapeutic medications


### Whole Bowel Irrigation

* Gut decontamination with non-absorbable polyethylene glycol solution
* ↓ GI absorption by creating high volume of liquid stool
* **Indicated** for **limited number** of poisons:
	* Iron
	* Lithium
	* 'Body packers'
	* Slow-release preparations
		* Potassium
		* Calcium channel blockers
		* β-blockers
		* Theophylline
* Requires monitoring of electrolyte concentrations
* Administer 25mL/kg/hr up to 2L/hr via NGT
	* Place patient on commode
	* Continue until effluent is clear
	* Stop irrigation if abdominal distension occurs


### Endoscopic Removal

* Direct removal is indicated for:
	* Obstruction
	* Iron tablets
	* "Body packing"\
	Swallowed packets of high doses of drugs that may precipitate extreme overdose if they rupture.


### Surface Decontamination

* Indicated for cutaneously absorbed drugs including:
	* Glycerol
	* Industrial solvents
	* Mercury salts
	* Lead salts


## Enhanced Elimination

### Urinary Alkalinisation

:::column-margin
Urinary alkalinisation is also known as forced alkaline diuresis.
:::

* Creating an alkaline urine to trap ionised drug in the renal tubule and prevent tubular reabsorption
* **Effective if** the **drug** is:
	* A **weak acid**
	* Predominantly **renally eliminated**
	* Creating significant toxicity
* In practice, used for:
	* Salicylates
	* Phenobarbital
	* Methotrexate
	* Chlorpropamide
* Achieved by sodium bicarbonate IV
	* Infuse isotonic bicarbonate at 250mL/hr\
	Dilute 150mL of 8.4% in 850mL of D5W to produce isotonic bicarbonate.
	* Adjust infusion to maintain urinary pH of 7.5-8.5
* Complications:
	* Hypokalaemia
		* Requires regular **monitoring** and replacement of **serum potassium**\
		* Occurs as potassium is exchanged for hydrogen in the tubule\
		This leads to both:
			* Clinically significant hypokalaemia
			* ↓ Urinary pH and ↑ reabsorption of the offending substance
	* Hypocalcaemia

:::column-margin
Urinary alkalinisation relies on the following:

* Drugs can only pass through lipid membranes in their unionised form\
* Ionised drugs are water soluble and trapped by surrounding lipid membranes\
e.g. In the renal tubule.
* **Weak acids** will lose their hydrogen ion in a basic environment, becoming a (ionised) conjugate base\
$AH \leftrightarrow A^- + H^+$
	* This conjugate base is then trapped in the renal tubule, and is eliminated
* The Henderson-Hasselbach equation: 
	* Describes the relationship between the:
		* Environmental pH
		* Drug pKA
		* Concentration of ionised and unionised forms
	* $pH = pKa + {\log_{10} {[A^-] \over [HA]}}$\
	If concentrations are equal, then pH = pKa as $\log_{10} 0 = 1$
:::

### Haemodiafiltration

:::column-margin
Haemodialysis is recommended for severe overdose of:

* Barbiturates
* Salicylates
* Lithium\
Chronic.
* Theophylline
* Carbamazepine
* Metformin
* Paracetamol
* Toxic alcohols
* Phenytoin\
Some preparations.
* Valproate
* Potassium salts
:::

* Extracorporeal filtration is effective for drugs with:
	* Small V~D~\
	Essentially confined to plasma.
	* Small molecule\
	Able to cross semi-permeable membrane.
	* Rapidly redistribution from tissue to plasma\
	Not trapped in tissues.
	* Slow endogenous clearance
* Considered worthwhile if clearance ↑ by ⩾30%
* **Ultrafiltration rate** is the prime **determinant** for removal of **larger molecules**
* **Dialysate** flow **rate** is the prime **determinant** for removal of **smaller molecules**
* The extracorporeal **circuit may directly adsorb** some **drugs** in idiosyncratic fashion


### Haemoperfusion

Use of an extracorporeal circuits to bind drugs to a filter, which:

* Facilitates ↑ clearance by adsorption
* Have a high-surface area, and made from:
	* Resin
		* Bind lipophilic substances
		* May be designed with drug-specific antibodies
	* Activated charcoal\
		* Broad-spectrum

Complicated by:

* Electrolyte derangements
* Coagulopathy
	* Thrombocytopaenia
	* Removal of clotting factors
* Immunosuppression
* Loss of micronutrients
* Charcoal embolisation


### Plasmapheresis

Plasma exchange is:

:::column-margin
Plasma exchange is also beneficial in any setting where haemodialysis or haemoperfusion are helpful.
:::

* Beneficial when toxins are confined to plasma proteins\
Both:
	* Highly protein bound
	* Low V~D~
* Possibly beneficial when a toxin is highly protein bound with a high V~D~\
Several exchange runs may be required.


### Lipid Emulsion Therapy

* Role in local anaesthetic toxicity
* Unclear mechanism, may relate to either:
	* Large lipid volume that lipid soluble drugs dissolve into
	* Energy substrate for shocked myocardium
* 20% lipid emulsion given:
	* At 1.5mL/kg followed by infusion at 15mL/kg/hr
	* If further instability:
		* 1.5mL/kg Q5M
		* ↑ Rate to 30mL/kg/hr
	* Up to 12mL/kg


## Supportive Care

* B
	* Mandatory mode of mechanical ventilation\
	Compensate for any acid-base disturbances.
* D
	* Thiamine 300mg for patients at risk of Wernicke's encephalopathy

---
 
## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.
1. Greene SL, Dargan PI, Jones AL. [Acute poisoning: understanding 90% of cases in a nutshell](https://academic.oup.com/pmj/article/81/954/204/7031872). Postgraduate Medical Journal. 2005;81(954):204-216. doi:10.1136/pgmj.2004.024794
