# Adjuncts

Nitrous oxide:

* Has analgesic efficacy in labour
	* ↑ maternal satisfaction
* Neuropathy and bone marrow suppression are rare but potentially serious complications of nitrous oxide use\
Consideration should be given to duration of exposure and supplementation with vitamin B~12~.


Dexamethasone:

* Reduces post-operative pain, as well as PONV and fatigue
* May cause mild hyperglycaemia
* Prolongs duration of sensory and motor block\
Extent is similar when given in the block as to when given systemically.


**Other**:

* Avoid withdrawal of benzodiazepines in acute pain
* Calcitonin reduces acute (not chronic) phantom limb pain
* No evidence supporting use of cannabinoids

Ketamine:


* Preventive analgesic effect
* Opioid sparing
* Reduces opioid hyperalgesia
* Does not ↑ ICP or reduce CPP
* Reduces chronic post-surgical pain
* Reduces PONV\
In thoracics.
* May be useful in opioid-resistant pain
* Reduces phantom limb pain

Clonidine:

* Useful in opioid users


α2-delta ligands:

* Probably little effect in most patients, but good in opioid tolerant.
* Avoid using PRN
* Gabapentin and pregabalin are opioid-sparing
* Gabapentin reduces phantom limb pain



Lignocaine:

* Perioperative IV lignocaine reduces:
	* Pain
	* Opioid requirement
	* PONV
	* Ileus duration
	* Hospital stay

Antidepressants:

* TCA and SNRIs are effective analgesics in chronic neuropathic pain and fibromyalgia
* Duloxetine may be effective in chronic low back pain




---

## References

1. Schug SA, Palmer GM, Scott DA, Alcock M, Halliwell R, Mott JF; APM:SE Working Group of the Australian and New Zealand College of Anaesthetists and Faculty of Pain Medicine (2020), [Acute Pain Management: Scientific Evidence](https://www.anzca.edu.au/resources/college-publications/acute-pain-management/apmse5.pdf) (5th edition), ANZCA & FPM, Melbourne.