# Non-Pharmacological Analgesia

Non-pharmacological adjuncts are generally ineffective as stand-alone treatments, but are beneficial as they:

* Are well-accepted by patients
* May improve analgesia\
Evidence is limited.
* Avoid side-effects


## Management

**Specific therapy**:

* Patient and carer **education**\
Educating patients about both pain and pain management improves adherence to pain plans, and reduce pain severity.
* Cognitive behavioural therapy
* Relaxation and hypnosis
* Music therapy


### Marginal and Ineffective Therapies

Limited or no evidence exists to support:

* TENS
* Acupuncture
* Reiki

---

## References

1. Schug SA, Palmer GM, Scott DA, Alcock M, Halliwell R, Mott JF; APM:SE Working Group of the Australian and New Zealand College of Anaesthetists and Faculty of Pain Medicine (2020), [Acute Pain Management: Scientific Evidence](https://www.anzca.edu.au/resources/college-publications/acute-pain-management/apmse5.pdf) (5th edition), ANZCA & FPM, Melbourne.
1. Hu C, Zhang H, Wu W, Yu W, Li Y, Bai J, et al. [Acupuncture for Pain Management in Cancer: A Systematic Review and Meta-Analysis](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4764722/). Evid Based Complement Alternat Med. 2016;2016:1720239. doi: 10.1155/2016/1720239. Epub 2016 Feb 10.
1. Niknejad B, Bolier R, Henderson CR Jr, Delgado D, Kozlov E, Löckenhoff CE, et al. [Association Between Psychological Interventions and Chronic Pain Outcomes in Older Adults: A Systematic Review and Meta-analysis](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6145761/). JAMA Intern Med. 2018 Jun 1;178(6):830-839. doi: 10.1001/jamainternmed.2018.0756.
1. Bennett MI, Bagnall AM, José Closs S. [How effective are patient-based educational interventions in the management of cancer pain? Systematic review and meta-analysis](https://pubmed.ncbi.nlm.nih.gov/19285376/). Pain. 2009 Jun;143(3):192-9. Epub 2009 Mar 12.