# Opioid Harm Reduction Strategies {#sec-opioid_harm}

The **opioid crisis** describes the significant ↑ in opioid-related morbidity and mortality across Western nations, driven by:

:::column-margin
This section covers harms of opioid medication. Administration of IV and PO opioids for analgesia are discussed separately under @sec-opioid_harm, and intrathecal administration is covered under @sec-intrathecal.
:::

* Development of new opioid preparations, including oral slow-release formulations
* Expansion of opioids to manage cancer pain, and then chronic non-malignant pain
* Dramatic ↑ in the use of opioids for post-operative analgesia


## Epidemiology and Risk Factors

Perioperative:

* Opioid prescriptions on discharge and following surgical procedures are identified as independent risk factors
* Surgery is a potential gateway to longterm opioid use
* Significant **excess of discharge opioid**\
	* 70% of patients have opioids remaining
	* Only 5% of them dispose of it correctly


## Prevention

Harm reduction strategies can be divided into:

* **Upstream**
Pharmaceutical and government interventions.
* **Midstream**
Hospital interventions.
* **Downstream**
Community, GP, and pharmacy interventions.
 
### Upstream

Include:

* Legislative changes
	* Up-scheduling\
	Requiring more drugs to be prescription.
	* Use of prescription trackers to identify doctor shopping\
	e.g. SafeScript.
* Pharmaceutical changes
	* Formulation of abuse-deterrent preparations\
	Addition of naloxone to oral opioids.



### Midstream

↓ Prescription of opioids by:

* Identify patients at risk of chronic post-surgical pain
* Opioid stewardship programs\
* Education of patients for realistic expectations for analgesia and harms of over-prescribing
* Opioid prescribing guidelines
* Changing default opioid prescription doses in EMR systems


Optimise acute pain management:

* Early multi-modal therapy
* Regular dosing
* Titrate opioids carefully
* Dose reduction plan on discharge



### Downstream

Key principles:

* Education:
	* Prescribers
		* HMOs
		* Senior registrars and consultants
	* Dispensers
		* Pharmacy
	* Patients
	* Community
		* GP
* Opioid return programs
	* Pharmacies

---

## References

1. Schug SA, Palmer GM, Scott DA, Alcock M, Halliwell R, Mott JF; APM:SE Working Group of the Australian and New Zealand College of Anaesthetists and Faculty of Pain Medicine (2020), [Acute Pain Management: Scientific Evidence](https://www.anzca.edu.au/resources/college-publications/acute-pain-management/apmse5.pdf) (5th edition), ANZCA & FPM, Melbourne.
1. Toon, M. [Opioid harm reduction strategies - stemming the tide](ncbi.nlm.nih.gov/pmc/articles/PMC9345064). Australian Anaesthesia. 2019.