# Coronary Artery Bypass Grafting


>Airway: ETT <br>
>Access: 14G IVC or MAC line, arterial line, CVC, +/- PAC <br>
>Pain: Substantial, especially in younger patients<br>
>Position: Supine/crucifix <br>
>Time: 3-4 hours  <br>
>Blood loss: G+H required. Keep units available if **re-do surgery**, anaemic, small, sick, or emergency. <br>
>Special: CPB - higher risk for anaesthetic awareness  

Use of an autologous artery or vein to bypass a stenosed section of coronary artery and restore downstream perfusion. CABGs:

* Are almost always performed under relaxant general anaesthesia.
* Can be performed 'on-pump' (with CPB) or 'off-pump'

## Considerations

*This covers factors unique to CABG. Factors relating to cardiac surgery in general are covered [here](/anaesthesia/cardiac/cardiac-principles.md#id).*

* B
	* Atelectasis
	* Bronchospasm
* C
	* CAD  
	High risk features:
		* History:
			* Unstable angina
			* AMI within last 3 months
			* Cardiogenic shock
			* Emergency revascularisation.
			* Decompensated CCF
			* LV aneurysm  
			Indicates poor myocardial function.
		* Coronary anatomy:
			* **Left main disease**  
			Avoid drop in perfusion pressure in the case of critical left main stenosis.
				* Significant >50%
				* Severe >80%
				* Critical ~>95%
				* Note also that high-grade stenosis of the LAD and LCx lead to an effective critical stenosis of the LMCA
				* Note that effective stenosis depends on degree of collateralisation   
				Well-developed collaterals compensate for poor native disease.
			* Triple vessel disease
			* Proximal LAD stenosis
		* Ventricular function  
		Dysfunction may be unable to wean from bypass.
			* LVEF < 30%  
			* Concomitant RV dysfunction
	* Valvular disease  
	Particularly AS or MR.
	* Severe LV or RV dysfunction
		* Pulmonary oedema

* H
	* Massive haemorrhage


## Induction

* Aim for haemodynamic stability, especially in the setting of critical left main stenosis

### Intraoperative

*This covers factors unique to CABG. Factors relating to bypass are covered [here](/anaesthesia/cardiac/cpb.md#id).*

On-pump CABG can be divided into pre-, intra-, and post-bypass phases:

* Pre-bypass
	* If LIMA harvest is occurring:
		* ↓ V~T~ to 5-6ml/kg
		* Reduce anaesthetic  
		Period of minimal stimulation following the very stimulating sternotomy.
		* ↑ FiO~2~ as there is a frequent surgical requirement for apnoea
* Bypass
* Post-bypass


### Surgical Stages

For standard approach:

* Sternotomy
* Establish CPB
* Establish diastolic arrest
* Grafting performed
	* Internal mammary grafting
		* A pedicled graft may be taken  
		The origin is left attached to the SCA.
		* Bilateral IMA grafts may be used  
		↑ the risk of sternal wound infection due to poor perfusion.
	* Saphenous vein graft  
	~50% of SVG grafts will be occluded at 10 years (compared to ~10% of arterial grafts).
	* Radial artery  
	Non-dominant or dominant vessels may be used, provided there is adequate collateral flow via the ulnar artery.
* Cross-clamp is removed and coronary perfusion commences
* Wean from CPB occurs once air is removed from circulation


### Postoperative Care

Medication:

* Aspirin  
	* Within 6 hours
	* Consider clopidogrel if aspirin allergy
* Statin  
	* When PO intake resumes
* β-blockers
	* When able  
	Limited by pacing requirement, inotrope requirement, or hypotension.
* ACE-I/ARB
	* Consider in all patients
	* Initiation limited by hypotension and AKI




---

## References

1. Chikwe J, Kim M, Goldstone AB, Fallahi A, Athanasiou T. Current diagnosis and management of left main coronary disease. Eur J Cardio-Thoracic Surg. 2010;38(4):420-428.