# Principles of Cardiac Anaesthesia


>Cardiothoracic surgery has the anaesthetist and surgeon sharing the circulation. Anaesthetic management has to adapt to surgical requirements, and vice versa.


*This covers the general considerations of cardiac anaesthesia except those relating to cardiopulmonary bypass, which are covered [here](/anaesthesia/cardiac/cpb.md).*

A cardiac anaesthetic needs to **prevent decompensation** by avoiding:

* **F**ailure  
Minimise:
	* Ischaemia
	* Negative inotropy
	* Swings in preload and afterload
* **A**rrhythmia  
	* Ischaemia
	* Electrolyte abnormalities
* **I**schaemia
	* Maintain CPP  
	Maintain DBP.
	* Minimise MVO<sub>2</sub>
	* Minimise stress factors
* **L**ow BP  
Especially in left main disease, pulmonary hypertension, and AS.

## Preoperative Evaluation

Basics:

* Planned operation
* Age, weight, and height  
For indexing and drug doses.

History:

* Allergies  
Particularly:
	* Heparin
	* Protamine  
	Seafood.
	* Iodine
	* Antibiotics
* Preoperative medications
	* Cease antiplatelets prior:
		* Clopidogrel 5-7 days
		* Tirofiban 1-2 days
		* Streptokinase 3 hours
	* Heparin  
	May be continued into the anaesthetic bay.
	* Continue beta-blockers  
	Consider initiating if not already instituted.
	* Stop ACE-Is
	* Continue statins perioperatively
* Exercise tolerance
* Co-existing disease  
Cardiac patients tend to be sicker. Particularly relevant features:
	* COAD and smoking history  
	Smoking cessation should be encouraged.
	* Hypertension
	* Valvular disease
	* Coronary artery disease  
	* Cerebrovascular disease
	* Peripheral vascular disease  
	Affects graft sites and arterial line placement.
	* Cognitive function  
	Baseline level of impairment.
	* DM  
	Associated with poorer outcomes.
	* CKD  
	Associated with poorer outcomes.  
	* **Dysphagia** or oesophageal problems
	Affects use of TOE.
* Previous cardiac surgery  
**Re-do sternotomy** is associated with substantial additional risk:
	* Pericardium is usually obliterated
	* RV or innominate vein may be adherent to sternum  
	Risk of **massive haemorrhage** due to sternal saw.
	* Internal paddles may not be able to be applied  
	External defib pads should be used.
	* Peripheral bypass (femoral) may need to be established
	* Significantly prolonged case with substantial blood loss   
	Dissection of adhesions and identification of old grafts.
* Contraindications for echocardiography  
Ask about swallowing disability.
	* Absolute
		* Perforated viscous
		* Oesophageal stricture/tumour/diverticulum
		* Active upper GI bleed
	* Relative
		* Neck/mediastinal radiation
		* Atlantoaxial disease
		* Dysphagia
		* Odynophagia


Examination:

* Vital signs
* Airway assessment
* Respiratory and CVS exam
* Peripheral and central vascular access sites


Investigations:

* Bloods
	* FBE
	* UEC/CMP
	* Coagulation profile
	* G+H +/- crossmatch
* General
	* ECG
	* CXR
	* PFTs if indicated by respiratory disease
* Cardiac-specific
	* Angiogram  
		* Number, site and severity of stenoses
		* Left main or equivalent stenosis
	* Echocardiogram
		* LV function
		* RV function
		* Valvular function


### Consent

> This is an incredibly stressful time for patient and family:
> * Avoid drowning the patient in unnecessary information
> * Ensure they understand the process

Discuss:

* Airway
* Lines
* TOE
* CPB
* Blood transfusion
* Post operative ventilation
* ICU Stay


Key risks:

* Death
* Stroke
* AMI
* Oesophageal injury
* Transfusion




## Preparation{#prep}

Premedication:

* Highly stressful period
* Stress may lead to myocardial ischaemia
* Consider:
	* Lorazepam 2mg  
	Night prior and on call to OT.
	* Morphine 5-10mg or oxycodone 10-20mg PO  
	On call to OT.

Lines and monitoring:

* 5-lead ECG
* SpO<sub>2</sub>
* Arterial line and large bore cannula  
Should be placed awake and on the **right side** if surgeons are not planning on using this vessel.
	* Left sided arteries and vessels lie closer to the sternum  
	Damage to left innominate vein will render any left upper limb venous access useless.
* Consider external defibrillation pads for:
	* Re-do cases
	* High risk arrhythmia  
	Includes:
		* Ischaemic emergencies
		* Critical left main
	* Modified access
	* Deactivated AICD
	* Removal of PPM leads
* Consider awake central access in sick or unstable patients  
MAC lines are excellent choice for volume as well as providing a route of administration of centrally acting drugs.
* Pulmonary artery catheter  
	* Indication varies depending on centre; strong indications include:
		* Severe LV dysfunction (EF ⩽30%)
		* MV dysfunction
		* AKI
	* Floating after induction preferable in patients with:
		* Severe AS
		* Left main/left main equivalent
		* Conduction deficits (BBB))
* Consider hot line for small patients or those with high risk of bleeding
* Use of TOE
	* ~5% of the time an unexpected abnormality will be identified


Drugs (Push):

* 2% lignocaine in 3ml syringe with 25G needle for vascular access
* Midazolam 5mg in 5ml
* Fentanyl 500ug-1mg in 10-20ml syringe
* Induction agent  
Propofol 200mg in 20ml (can use syringe driver if required), thiopentone 500mg in 20ml.
* Cephazolin 2g
* Vasopressor  
e.g. Metaraminol 10mg in 20ml.
* Rocuronium 100mg in 2x5ml
* Heparin
	* 300 units/kg if heparin naive
	* 400 units/kg if has been on heparin or enoxaparin preoperatively

Drugs (Infusions):

* TXA 5g in 50ml
* Propofol 500mg in 50ml
* +/- Noradrenaline 3mg in 50ml
* +- GTN 6mg in 50ml


## Induction

Induction:

* Don't induce unless:
	* Surgeon capable of instituting CPB present
	* Perfusionist present
* Aim is a haemodynamically stable induction  
	* No myocardial depression
	* No autonomic response
	* No change in SVT
	* Most inductions are equivalent, with the exception desflurane and ketamine
* Typical doses
	* Fentanyl 5-10ug/kg  
	Up to 100ug/kg may be given over the course of the case in some centres.
	* Midazolam 0.05mg/kg
	* Propofol  
	Classically reduced doses; e.g. ~0.25-0.5mg/kg.
* Antibiotics prior to skin incision



### Intraoperative

Position:

* Head ring
* Leg padding
* Place head frame
* Arms positioned  
Tucked if not used for grafts.


Sternotomy:

* Highly stimulating - requires re-dose of analgesia  
e.g. 250μg fentanyl.
* Cease ventilation with ZEEP prior to sternotomy  
Prevents surgeon from damaging lung.
	* Lungs may be left on during *re*sternotomy to protect the other cardiac structures

### Postoperative

ICU Handover:

* Should be formulaic 

---

## References
