# Abdominal Aortic Aneurysm


Permanent dilatation **>30mm** of the aorta.

## Epidemiology and Risk Factors

Risk factors include:

* Family history
* Smoking  
Most important modifiable risk factor - cessation reduces growth by 15-20%.
* Race  
↑ in caucasians.

Size correlates strongly with risk of rupture:

* Aneurysms >5.5 cm have an 18% annual rupture risk in women, and 12% in men


## Pathophysiology

### Aetiology

## Clinical Manifestations

### History

### Examination

## Diagnostic Approach and DDx

## Investigations

## Management

Medical Management:

* Optimise modifiable risk factors
	* Smoking cessation slows growth by 15-20%
	* Control HTN
* Statins may alter growth
* Low-dose aspirin  
Reduces major coronary events.

Surgical management:

* Indicated when aneurysm is **greater than 5.5cm**
	* <1% annual rupture rate below this size
* May be open or endovascular
	* Equivalent long-term outcome
	* Choice depends on:
		* Co-morbidities
		* Age
		* Aneurysm morphology

### Anaesthetic Considerations

### Ineffective Therapies

## Complications

Non-surgically treated patients die of rupture in **80% of cases**:

* ~80% 5-year risk of rupture
* Surgical management may double life expectancy


Operative complications are associated with:

* Age
* ↓ renal function
* ↓ FEV~1~
* Being female


## Prognosis


---

## References

1. Al-Hashimi M, Thompson J. [Anaesthesia for elective open abdominal aortic aneurysm repair](https://academic.oup.com/bjaed/article/13/6/208/246828). Contin Educ Anaesth Crit Care Pain. 2013;13(6):208-212. doi:10.1093/bjaceaccp/mkt015