# Acute Coronary Syndromes


> * Patients with acute chest pain or other ACS symptoms should have a 12-lead ECG and have it assessed by an appropriate clinician **within 10 minutes** of clinical contact




Myocardial infarction can be classified into five types:

* Type I  
Intraluminal thrombus causing distal ischaemia, occurring due to:
	* Plaque rupture
	* Ulceration
	* Erosion
	* Dissection
* Type II  
Supply/demand mismatch.
	* Causes include:
		* Coronary spasm
		* Endothelial dysfunction
		* Arrhythmia
		* Anaemia
		* Respiratory failure
		* Hypotension
		* Hypertension
	Requires:
		* Cardiac myonecrosis  
		Enzymatic leak.
		* Presence of clinical DO~2~/VO~2~ mismatch
		* Lack of clinical picture for ACS
* Type III  
Death with symptoms or ECG findings suggestive of ischaemia, but occurring prior to biomarker collection.
* Type IV  
Iatrogenic, subdivided into:
	* 4a: PCI-related MI
	* 4b: Stent thrombosis
* Type V  
Iatrogenic, CABG-related.



## Epidemiology and Risk Factors

Prevalance:

* In Australia, patients presenting to the ED with acute chest pain have:
	* 2-5% STEMI
	* 5-10% NSTEMI
	* 5-10% UA
	* 50-70% Non-cardiac



Predictors of mortality and recurrent events:

* Very high risk
	* Haemodynamic instability
	* Cardiac failure
	* Cardiac arrest
	* Life-threatening arrhythmia
	* Recurrent or ongoing ischaemia
* High risk
	* Rise/fall in troponin level
	* Dynamic ECG changes
	* GRACE >140
* Intermediate risk
	* DM
	* eGFR <60
	* LVEF <40%
	* Previous revascularisation
	* GRACE 109-140



Type II MI:

* 40% 5-year mortality  
Worse than type I.

## Pathophysiology

### Aetiology

## Clinical Manifestations

High-risk features for cardiac chest pain:

* Ongoing or repeated chest pain
* Elevated troponin
* Persistent or dynamic STD or TWI
* Transient STE
* Haemodynamic compromise
* Diaphoresis
* Sustained VT
* Syncope
* Known LVEF <40%
* Prior AMI
* PCI or CABG in the last 6 months





### History

### Examination

## Diagnostic Approach and DDx

> * Diagnostic approach should be governed by a risk score  
e.g. MACE.

Key differentials:

* STEMI
* High-risk disease:
	* Dissection
	* PE
* NSTEACS
* Obstructed coronary disease/Angina
* Identification of high-risk patients 


## Investigations

> * Troponin should be measured on presentation and on clearly-defined intervals
> * Non-invasive objective testing is recommended in intermediate-risk patients with normal troponin and ECG


ECG:

* Should be taken every 10-15 minutes until patient is pain-free
* Evaluated in context with previous ECGs


STEMI:

* ST segment elevation in >2 contiguous leads of:
 	* ⩾2.5 mm ST elevation in leads V2-3 in men under 40 years
 	* ⩾2.0 mm ST elevation in leads V2-3 in men over 40 years, or
	* ⩾1.5 mm ST elevation in V2-3 in women, or
	* ⩾1.0 mm in other leads
* New onset LBBB
* Sgarbossa criteria positive in old LBBB




## Management

STEMI:

* For patients with STEMI presenting within **12 hours** of symptom onset, and in absence of conditions suggesting poor survival, reperfusion is recommended
* Primary PCI is preferred in STEMI if it can be performed within **90 minutes**
	* Fibronolytic is preferred otherwise, in absence of contraindications
		* Patients treated with fibrinolytics in a non-PCI capable hospital should be transferred within 24 hours
		* Rescue angioplasty should be performed on patients with <50% ST recovery after fibrinolysis at 60-90 minutes


NSTEACS:

* Very high risk patients should have invasive therapy within 2 hours of admission  
As indicated by:
	* Ongoing ischaemia
	* Haemodynamic compromise
	* Arrhythmias
	* Mechanical complications
	* Acute HF
	* Recurrent or dynamic ECG changes
* High risk patients should have invasive therapy within 24 hours of admission  
As indicated by:
	* GRACE >140
	* Dynamic ECG changes
	* Rise or fall in troponin
* Intermediate risk patients should have invasive therapy within 72 hours of admission  
Indicated by:
	* Recurrent symptoms
	* Substantial inducible ischaemia



Acute pharmacotherapy:

* Oxygen  
Target SpO~2~ >93%, and **withhold oxygen** if saturations are above this.
* GTN  
Indicated if ongoing pain and no contraindications (e.g. hypotension)
	* Give: 0.3-0.6mg SL tablet or spray Q5Min
	* Consider IV if pain unrelieved by SL GTN
* Analgesia  
Give fentanyl or morphine if ongoing pain.
* Aspirin 300mg  
For all patients.
* P2Y~12~ inhibitor  
For confirmed ACS with intermediate to very-high risk of recurrence. Consider:
	* Ticagreolor
	* Prasugrel
	* Clopidogrel  
	Least preferred.
* GIIb/IIIa inhibitor and heparin  
For patients with high-risk clinical or angiographic features.
* Heparin/enoxaparin  
For intermediate-to-high risk patients.


Discharge therapy:

* Aspirin  
Continued indefinitely.
	* Clopidogrel used as alternative
* DAPT  
For 12 months irrespective of coronary revascularisation.
	* Consider continuing if high ischaemic risk
	* Consider discontinuing if high bleeding risk
* Statin  
For all patients, at highest tolerated dose.
* β-blockade  
In patients with LVEF <40%. β-blockers:
	* Reduce angina and MI
	* Increase cardiac failure and cardiogenic shock  
	Use caution in patients with:
		* Haemodynamic compromise
		* Low EF
		* Conduction abnormalities
		* Inferior infarction
* ACE-I or A2RB  
For all patients with:
	* HTN
	* Anterior MI
	* Heart failure
	* LV dysfunction
	* DM
* Cardiac rehabilitation  
Strongly recommended for all patients hospitalised for ACS.



### Anaesthetic Considerations

### Ineffective Therapies

## Complications

## Prognosis


---

## References

1. McCarthy CP, Vaduganathan M, Januzzi JL Jr. Type 2 Myocardial Infarction-Diagnosis, Prognosis, and Treatment. JAMA. 2018 Aug 7;320(5):433-434.
1. Chew DP, Scott IA, Cullen L, et al. National Heart Foundation of Australia & Cardiac Society of Australia and New Zealand: Australian Clinical Guidelines for the Management of Acute Coronary Syndromes 2016. Heart, Lung and Circulation. 2016;25(9):895-951. doi:10.1016/j.hlc.2016.06.789
