# Heart Transplant


## Epidemiology and Risk Factors

## Pathophysiology

### Aetiology

## Clinical Manifestations

## Diagnostic Approach and DDx

## Investigations

## Management

### Medical

### Surgical

### Anaesthetic Considerations

*Covers anaesthetic considerations for patient **with** a heart transplant undergoing non-cardiac surgery.*



* C
	* Graft function  
	**Recent TTE**.
	* Donor coronary artery disease
		* **Maintain coronary perfusion pressures**
	* Denervated
		* Absence of vagal tone  
		Resting rate typically 90-100bpm.
		* Significantly impaired autoregulation  
			* No changes to heart rate and contractility with response to:
				* Laryngoscopy
				* Visceral traction
				* Change in blood pressure  
			* Lack of autoregulation means changes in SVR lead to direct changes in BP.
			* **Maintain preload**  
			Starling mechanism intact.
		* Minimal change seen in exercise  
		Due to exogenous catecholamines rather than parasympathetic and sympathetic innervation.
		* Alteration to **pharmacology**:
			* Anticholinergics (glycopyrrolate, atropine)  
			Ineffective.
			* Digoxin  
			Rate effects are due to alterations of vagal tone, and are therefore ineffective.
			* Adenosine  
			↑ sensitivity; commence at 1mg.
			* Indirect vasoactives (e.g. ephedrine)  
			Ineffective; requires direct vasoactives (e.g. metaraminol).
	* Rate dependent on donor SA node function  
	Nodal ischaemia common cause of PPM dependency.
	* Arrhythmias
		* Common, especially initially
		* RBBB particularly common
* D
	* Highly medicalised
		* Good understanding of their own disease
		* Familiar with hospital system
* E
	* Avoid right IJV cannulation  
	Preferential site for performing cardiac biopsies.
	* Osteoporosis  
	Secondary to steroids.
	* Poor IV access
* F
	* CKD  
	Secondary to immunosuppression.
* I
	* Rejection  
	Recent biopsy or indication of **rejection status**.
	* **CMV status**
	* Immunosuppression  


### Ineffective Therapies

## Complications

Acute rejection:

* Important in first year
* Infrequent once stable on long-term immunosuppressives


Immunosuppression:

* Malignancy
* Infection
* CKD
* Musculoskeletal problems

Donor coronary artery disease:

* Immunologically mediated disease of coronary microvasculature, with only later involvement of major coronary vessels.
* Major long-term complication
* Atheroma present in 50% of patients at 5 years
* Major cause of death after 12 months
* **No angina**  
Denervated heart - silent ischaemia.
* Presents with:
	* Ventricular dysfunction
	* Arrhythmia

## Prognosis

## Key Studies


---

## References

