# Systemic ICU Approach

*This describes one method of systematically assessing the ICU patient.*

## Observe

* **Monitor**
    * Breathing:
        * SpO~2~
        * E~T~CO~2~
    * Circulation:
        * ECG:
            * Rate
            * Rhythm
            * Morphology
        * Arterial BP
        * CVP
    * Others:
        * PAC
        * EVD <br>
* **Equipment**
    * Airway
        * Tracheostomy
        * ETT
        * NIV
        * HFNP
    * Breathing:
        * Ventilator/supports:\
        Determine if this patient has respiratory failure - i.e. could they be extubated/weaned from supports.
            * Oxygenation:
                * FiO~2~
                Check P:F ratio.
                * PEEP
                    * PEEP~i~
            * Ventilation:
                * V~T~
                * MV
                * Mode
            * Pressures:
                * P~Peak~
                * P~Plat~
            * Loops
        * Inhaled agents:
            * Heliox
            * Nitric
    * Circulation:
        * Circulatory Supports:\
        Determine if this patient has circulatory failure.
            * Vasopressor/inotropes
            * Pacing:\
            Is this patient pacing dependent?
                * Mode
                * Set Rate
            * Balloon Pump
                * Timing
                * Efficacy
                * Ratio
            * ECMO:
                * Configuration
                * Flow
                * RPM
                * FGF
                * SpO~2~
    * Disability:
        * EVD
            * Level
            * Open/closed
            * CSF volume/appearance
    * Extremities:
        * Temperature control:
            * Cooling mat
            * Intravascular cooling
        * Drains
            * ICCs
            * Surgical drains
    * Renal and Fluid:
        * CRRT
            * Mode
            * Dose
            * Fluid removal
            * Anticoagulation
            * Filter duration
        * IDC
            * Urine colour
            * Urine volume
        * Plasmapheresis
        * Drug Infusions
* **Patient**
    * Respiratory pattern
    * Dressings
    * Body habitus
    * Skin



## Examine

* GCS
* Hands
    * Nails
    * Pulse
    * Asterixis
* Upper Limbs
    * Tone
    * Fistula
    * Trackmarks
    * Axillary lymph nodes
* Neck
    * Lines
    * CVP
    * Trachea
    * Thyroid
    * Lymph nodes
    * Carotid pulse
* Head
    * Cranial nerve exam
* Chest
    * Chest expansion
    * Percussion
    * Auscultation
        * Lungs
        * Heart sounds
        * Carotids
    * Heaves and thrills
* Abdomen
    * Four quadrants
    * Liver edge
    * Spleen
    * Kidneys
    * Percussion
    * Auscultation
* Groin
    * Femoral lines
    * Hernias
* Lower limbs
    * Oedema
    * Asymmetrical swelling and calf tenderness
    * Muscle wasting
    * Tone
* Feet
    * Pulses
* Neurological
    * Upper limb
        * Tone
        * Power
            * Grip strength
            * Wrist flexion/extension
            * Elbow flexion/extension
            * Shoulder abduction/adduction
        * Reflexes
            * Finger jerk
            * Brachioradialis
            * Biceps
            * Triceps
        * Sensation
    * Lower limb
        * Tone
        * Power
            * Ankle plantarflexion/dorsiflexion
            * Knee flexion/extension
            * Hip flexion/extension/abduction/adduction
        * Reflexes
            * Knee jerk
            * Ankle jerk
            * Babinksi
        * Sensation
    * Cerebellar
        * Nystagmus
        * Resting Tremor
        * Coordination
            * Finger-nose
            * Heel-shin
    * Cranial nerves


---