# Intubation

> Intubation is **more** than first-pass success
> Successful intubation is also about avoiding physiological insults during the intubation process

## Indications

Multiple:

* A:
	* Airway protection
	* Maintain airway patency
* B:
	* Respiratory failure
	* Reduce work of breathing
	* Manage secretions
	* Bronchoscopy
* C:
	* Improve DO~2~
	* Reduce VO~2~
* D:
	* Decreased GCS
	* Status epilepticus
	* Neuroprotection
	* Pain control  
	Humanitarian reasons.
* E:
	* Temperature control  
	Paralysis to reduce shivering.
	* Transport

## Contraindications


## Technique

Optimising laryngoscopy:

* Ensure ear-to-sternal notch position
* Lift epiglottis
* Use of intubation adjuncts
	* Stylet
	* Bougie
	* Magill forceps  
	With nasal ETT.
* Use of alternate laryngoscopes
	* Adjust blade or handle
	* Use of **video laryngoscopes**
* Suction
* Consider adequacy of muscle relaxation



### Awake Intubation and Laryngoscopy

Awake Intubation:

* Has a favourable safety profile
	* Spontaneous ventilation maintained
	* Airway protected until intubated
* Unsuccessful in 1-2%  
Rarely leads to major complications.


Common indications for awake intubation:

* Head and neck
	* Tumour
	* Surgery
	* Radiotherapy
* Limited mouth opening
* Restricted neck movement
* Airway compromise


Preparation:

* Operating theatre ideal
* Oxygenation  
Supplemental oxygen should:
	* Always be applied
	* High-flow used if available
	* Commenced on arrival to OT



Awake VL:

* Similar success to AFOI
* Choice of technique depends upon patient status
	* Mouth opening
	* Large tongue
	* Fixed flexion deformity


---

## References

1. Nickson, C. The challenge of the critically ill airway. 2018. CIA Course Notes.
2. Chrimes, N. Fritz, P. [The Votex Approach: Management of the Unanticipated Difficult Airway](https://www.smashwords.com/books/view/277513). Smashwords. 2013.