# Mask Ventilation


Ventilation using a face mask.


## Technique

Optimising BMV:

* Leave dentures in
* Use a **two hand-technique**with a **vice grip**
* Place **airway adjuncts**
	* OPA
	* NPA
* Increase oxygen flow to overcome leak
* Consider **muscle relaxation**1



Paediatrics:

* **Difficulty** often encountered in children **under 4**
* Usually because tongue occludes mouth, and cannot be effectively ventilated through nose
* Need to ensure mouth is open with mask in place  
Can:
	* Use two hands
	* Place 5<sup>th</sup> finger high on the mandible, close to the TMJ  
	Pushing anteriorly and providing clockwise rotational force provides jaw thrust and also opens mouth, allowing one-handed jaw support.

### Niche Techniques

Use of a nasal tube:

* Nasal ETT is placed into naso/oropharynx
* Remaining nostril and mouth are then occluded
* Ventilation can be performed by breathing circuit attached to ETT
* Useful when:
	* Difficult mask ventilation
	* Rapid desaturation during nasal intubation


## Equipment



---

## References

1. Chrimes, N. Fritz, P. [The Votex Approach: Management of the Unanticipated Difficult Airway](https://www.smashwords.com/books/view/277513). Smashwords. 2013.