# Right Ventricular Failure


RV failure:

* Has similar mortality to LV failure

## Pathophysiology

The right ventricle is:

* Relatively *in*sensitive to volume loads due to high compliance  
Allows it to cope with a wide variety of filling volumes.
* Relatively sensitive to pressure loads due to poor contractility  
Dilation and ↑ in RVEDP/CVP is seen when RV afterload/PVR ↑
	* Results in progressive dilation and ↑ in EDP  
	Subsequent ↑ in LVEDP and ↓ in LVEDV, resulting in systemic hypotension, and a fall in RV coronary perfusion pressure: the RV "spiral of death".
	* The (in this instance, maladaptive) homeostatic response to a falling cardiac output is tachycardia and volume preservation to try and maintain RV preload and normalise SV volume  
	This leads to worsening RV dilation, and further failure.

### Aetiology

Causes of RV failure can be divided into:

* Primary causes
	* Volume overload
		* LV failure
	* Pressure overload
		* Pulmonary Hypertension
		* Embolism
		* ARDS
	* Cardiomyopathy
		* Sepsis


## Clinical Manifestations

### History

### Examination

## Diagnostic Approach and DDx

## Investigations

## Management

### Ineffective Therapies

## Complications

## Prognosis


---

## References

