# Thoracic Aortic Aneurysm


Dilatation of the thoracic aorta greater than 150% of expected. They are:

* Often asymptomatic
* Either:
	* Ascending
		* May be associated with AR
	* Descending
* Described the **Crawford classification**\
Divides based on surgical repair required:
	* Type I\
		* Begins distal to the L ICA
		* Extends below the diaphragm, but above the renal arteries
	* Type II
		* Begins distal to the L ICA, above the 6^th^ intercostal space
		* Extends through the diaphragm, and ends below the renal arteries
	* Type II
		* Begins below the 6^th^ intercostal space
		* Extends below the renal arteries
	* Type IV\
		* Begins below the diaphragm, but above the renal arteries
		* Extends below the renal arteries
	* Type V
		* Begins above the diaphragm
		* Ends above the renal arteries

## Epidemiology and Risk Factors

Cardiovascular risk factors:

* Hypertension
* Hypercholesterolaemia
* Smoking
* Age

## Pathophysiology

Local degeneration of elastic and muscular tissue of the aortic wall, leading to gradual dilation:

* **0.1cm/yr** for **ascending**
* **0.3cm/yr** for **descending**

### Aetiology

Causes include:

* Degenerative
* Metabolic
	* Marfans Syndrome
	* Turner Syndrome
	* Ehlers-Danlos Syndrome
	* Loeys-Dietz Syndrome
* Post-stenotic dilatation

## Clinical Manifestations

Presentation usually due to compression of adjacent structures:

* Airway
	* Hoarseness
		* Recurrent laryngeal nerve compression
		* 

## Diagnostic Approach and DDx

## Investigations


Surveillance imaging:

* Monitors growth of aneurysm
* Interval will depend on underlying disease
	* 6 months usual for initial interval
	* May be extended to 12 monthly if stable

## Management

Medical management:

* Aims to reduce:
	* Rate of growth
	* Risk of rupture
* Involves:
	* β-blockade
		* Demonstrated efficacy in Marfans Syndrome
		* Evidence lacking in other populations
	* Statins\
	Reduces rate of growth.
	* ACE-Is\


Surgical management:

* Occurs when aneurysm crosses a certain threshold\
When risk of not operating exceeds risk of operating. This depends on the pathology:
	* Normal aorta
		* 5.5cm for ascending aneurysms
		* 6.5cm for descending aneurysms
	* Normal aorta & valve
		* 4.5cm
	* Marfan Syndrome
		* 5cm for ascending aneurysms
		* 6cm for descending aneurysms
	* Marfan Syndrome & pregnancy
		* 4cm
* May be:
	* Open\
	May involve:
		* CPB
		* DHCA
	* Endovascular\
	May require:
		* Aortic debranching

### Anaesthetic Considerations

### Marginal and Ineffective Therapies

## Complications


## Prognosis

## Key Studies


---

## References

