# Trauma Approach


*This section covers clinical assessment of the trauma patient, and likely injuries based on mechanism.*

>* Volume resuscitation is not a substitute for haemorrhage control
>* Shock in the trauma patient is almost always hypovolaemic\
>Causes of shock in trauma:
>	* Haemorrhage
>	* Haemorrhage
>	* Haemorrhage
>	* Obstructive
>		* Tension PTHx
>		* Tamponade
>	* Distributive


Assessment of the trauma patient can be divided into:

* History
	* [Mechanism](#mech)
	* Injury Patterns
* [Primary Survey](/assessments/targeted/primary-survey.md)
* [Secondary Survey](/assessments/targeted/secondary-survey.md)
* Tertiary Survey

## History

History should include:

* Allergies
* Medication
* PMHx
* Last eaten
* Events\
	* [Mechanism](#mech)
	* Injuries
		* Blood loss at scene
		* Open wounds/fractures\
		Potential contaminants.
	* Symptoms
	* Treatment

### Mechanism{#mech}

Injury patterns relate to mechanism of injury:

* **MVA**
	* Position
	* Use of restrains
		* Lap belt
		* Three-point restraints
	* External damage to vehicle
	* Internal damage to vehicle
	* Speed\
	Pre and post-crash.
	* Direction of impact
	* Injuries to other passengers
* **Fall**
	* Distance
	* Landing
	* Surface
* **Crush**
	* Weight of object
	* Site
	* Duration of entrapment
* **Burns**
	* Time
	* Duration
	* Enclosed space
	* Protectie equipment
	* Agent
* **Explosion**
	* Magnitude
	* Distance
	* Enclosed space
	* Secondary projectiles
	* Sources of bacterial contamination

## Injury Patterns


### Missed Injuries

* Cardiac contusion		
* Aortic injury
* Vascular injury
* Oesophageal injury
* Ruptured diaphgram
* Tracheobronchial injury

---

## References
