# Chest

: Chest

+---------------------------------+---------------------------+------------------------+------------+--------------------+
| Component                       | Inspection                | Palpation              | Percussion | Auscultation       |
+=================================+===========================+========================+============+====================+
| **General**                     | * Scars                   |                        |            |                    |
|                                 |     * PPM                 |                        |            |                    |
|                                 |     * Thoracotomy         |                        |            |                    |
|                                 |     * Sternotomy          |                        |            |                    |
+---------------------------------+---------------------------+------------------------+------------+--------------------+
| **Respiratory**                 | * Chest form              | * Chest expansion      |            | * Breath sounds    |
|                                 |     * Hyper-expansion     |                        |            |     * Wheeze       |
|                                 |     * Pectus excavatum    |                        |            |     * Crepitations |
|                                 |     * Pectus carinatum    |                        |            |     * Rales        |
|                                 |     * Barrel-shaped chest |                        |            |                    |
|                                 |     * Flail chest         |                        |            |                    |
|                                 |                           |                        |            |                    |
+---------------------------------+---------------------------+------------------------+------------+--------------------+
| **Cardiovascular**              | * Sternotomy              | * Heave/thrills        |            | * Murmurs          |
|                                 | * CPR bruising            | * Apex beat\           |            | * Breath sounds    |
|                                 | * Epicardial pacing wires | Displaced.             |            |     * Wheeze       |
|                                 | *                         | * PPM                  |            |                    |
|                                 |                           | * Sternotomy stability |            |                    |
+---------------------------------+---------------------------+------------------------+------------+--------------------+
| **Neurological**                |                           |                        |            |                    |
+---------------------------------+---------------------------+------------------------+------------+--------------------+
| **Endocrine** and **Metabolic** |                           |                        |            |                    |
+---------------------------------+---------------------------+------------------------+------------+--------------------+
| **Renal**                       |                           |                        |            |                    |
+---------------------------------+---------------------------+------------------------+------------+--------------------+
| **Gastrointestinal**            | * Jaundice                |                        |            |                    |
|                                 | * Gynaecomastia           |                        |            |                    |
+---------------------------------+---------------------------+------------------------+------------+--------------------+
| **Haematological**              |                           |                        |            |                    |
+---------------------------------+---------------------------+------------------------+------------+--------------------+
| **Integumentary**               |                           |                        |            |                    |
+---------------------------------+---------------------------+------------------------+------------+--------------------+
| **Trauma**                      |                           |                        |            |                    |
+---------------------------------+---------------------------+------------------------+------------+--------------------+
| **Infective**                   |                           |                        |            |                    |
+---------------------------------+---------------------------+------------------------+------------+--------------------+
| **Malignant**                   |                           |                        |            |                    |
+---------------------------------+---------------------------+------------------------+------------+--------------------+
| **Toxic**                       |                           |                        |            |                    |
+---------------------------------+---------------------------+------------------------+------------+--------------------+
| **Immune**                      |                           |                        |            |                    |
+---------------------------------+---------------------------+------------------------+------------+--------------------+
| **Congenital**                  |                           |                        |            |                    |
+---------------------------------+---------------------------+------------------------+------------+--------------------+
| **Obstetric**                   |                           |                        |            |                    |
+---------------------------------+---------------------------+------------------------+------------+--------------------+

* Work of breathing

---

## References

1. Foot C, Steel L, Vidhani K, Lister B, MacPartlin M, Blackwell N. Examination Intensive Care Medicine. Elsevier Australia; 2011. (Examination series).