# Lower Limb

: Legs

+---------------------------------+-------------------------------+------------------------+------------+--------------+
| Component                       | Inspection                    | Palpation              | Percussion | Auscultation |
+=================================+===============================+========================+============+==============+
| **General**                     | * Muscle wasting              |                        |            |              |
+---------------------------------+-------------------------------+------------------------+------------+--------------+
| **Respiratory**                 |                               |                        |            |              |
+---------------------------------+-------------------------------+------------------------+------------+--------------+
| **Cardiovascular**              | * Groin vascular access sites | * Peripheral pulses    |            |              |
|                                 | * Peripheral oedema           |     * Femoral          |            |              |
|                                 |                               |     * Popliteal        |            |              |
|                                 |                               |     * Posterior tibial |            |              |
|                                 |                               |     * Dorsalis pedis   |            |              |
+---------------------------------+-------------------------------+------------------------+------------+--------------+
| **Neurological**                |                               |                        |            |              |
+---------------------------------+-------------------------------+------------------------+------------+--------------+
| **Endocrine** and **Metabolic** |                               |                        |            |              |
+---------------------------------+-------------------------------+------------------------+------------+--------------+
| **Renal**                       |                               |                        |            |              |
+---------------------------------+-------------------------------+------------------------+------------+--------------+
| **Gastrointestinal**            |                               |                        |            |              |
+---------------------------------+-------------------------------+------------------------+------------+--------------+
| **Haematological**              |                               | * Swelling\            |            |              |
|                                 |                               | DVT.                   |            |              |
+---------------------------------+-------------------------------+------------------------+------------+--------------+
| **Integumentary**               |                               | * Tense compartments   |            |              |
+---------------------------------+-------------------------------+------------------------+------------+--------------+
| **Trauma**                      |                               |                        |            |              |
+---------------------------------+-------------------------------+------------------------+------------+--------------+
| **Infective**                   |                               |                        |            |              |
+---------------------------------+-------------------------------+------------------------+------------+--------------+
| **Malignant**                   |                               |                        |            |              |
+---------------------------------+-------------------------------+------------------------+------------+--------------+
| **Toxic**                       |                               |                        |            |              |
+---------------------------------+-------------------------------+------------------------+------------+--------------+
| **Immune**                      |                               |                        |            |              |
+---------------------------------+-------------------------------+------------------------+------------+--------------+
| **Congenital**                  |                               |                        |            |              |
+---------------------------------+-------------------------------+------------------------+------------+--------------+
| **Obstetric**                   |                               |                        |            |              |
+---------------------------------+-------------------------------+------------------------+------------+--------------+

---

## References

1. Foot C, Steel L, Vidhani K, Lister B, MacPartlin M, Blackwell N. Examination Intensive Care Medicine. Elsevier Australia; 2011. (Examination series).
1. Dünser MW, Dankl D, Petros S, Mer M. Clinical Examination Skills in the Adult Critically Ill Patient. Springer International Publishing; 2018.
