# Upper Limb

## Hands

: Hands

+---------------------------------+---------------------------+-------------------------------+------------+
| Component                       | Inspection                | Palpation                     | Percussion |
+=================================+===========================+===============================+============+
| **General**                     |                           | * Clubbing                    |            |
+---------------------------------+---------------------------+-------------------------------+------------+
| **Respiratory**                 |                           | * Nicotine staining           |            |
|                                 |                           | * Intraosseous muscle wasting |            |
+---------------------------------+---------------------------+-------------------------------+------------+
| **Cardiovascular**              |                           | * Stigmata of IE              |            |
|                                 |                           |     * Janeway lesions         |            |
|                                 |                           |     * Osler's nodes           |            |
|                                 |                           |     * Splinter haemorrhages   |            |
+---------------------------------+---------------------------+-------------------------------+------------+
| **Neurological**                |                           |                               |            |
+---------------------------------+---------------------------+-------------------------------+------------+
| **Endocrine** and **Metabolic** |                           |                               |            |
+---------------------------------+---------------------------+-------------------------------+------------+
| **Renal**                       |                           |                               |            |
+---------------------------------+---------------------------+-------------------------------+------------+
| **Gastrointestinal**            |                           |                               |            |
+---------------------------------+---------------------------+-------------------------------+------------+
| **Haematological**              |                           |                               |            |
+---------------------------------+---------------------------+-------------------------------+------------+
| **Integumentary**               | * Dupuytren's contracture |                               |            |
+---------------------------------+---------------------------+-------------------------------+------------+
| **Trauma**                      |                           |                               |            |
+---------------------------------+---------------------------+-------------------------------+------------+
| **Infective**                   |                           |                               |            |
+---------------------------------+---------------------------+-------------------------------+------------+
| **Malignant**                   |                           |                               |            |
+---------------------------------+---------------------------+-------------------------------+------------+
| **Toxic**                       |                           |                               |            |
+---------------------------------+---------------------------+-------------------------------+------------+
| **Immune**                      |                           |                               |            |
+---------------------------------+---------------------------+-------------------------------+------------+
| **Congenital**                  |                           |                               |            |
+---------------------------------+---------------------------+-------------------------------+------------+
| **Obstetric**                   |                           |                               |            |
+---------------------------------+---------------------------+-------------------------------+------------+


## Arms

: Arms

+---------------------------------+------------------------------------+----------------------+------------+---------------+
| Component                       | Inspection                         | Palpation            | Percussion | Auscultation  |
+=================================+====================================+======================+============+===============+
| **General**                     | * Trackmarks                       |                      |            |               |
|                                 | * Long-term lines                  |                      |            |               |
|                                 |     * PICC                         |                      |            |               |
|                                 |     * Midline                      |                      |            |               |
+---------------------------------+------------------------------------+----------------------+------------+---------------+
| **Respiratory**                 |                                    |                      |            |               |
+---------------------------------+------------------------------------+----------------------+------------+---------------+
| **Cardiovascular**              | * Radial and brachial access sites |                      |            |               |
|                                 |     * Evidence of vascular sheath  |                      |            |               |
|                                 | * Previous radial graft harvesting |                      |            |               |
+---------------------------------+------------------------------------+----------------------+------------+---------------+
| **Neurological**                |                                    |                      |            |               |
+---------------------------------+------------------------------------+----------------------+------------+---------------+
| **Endocrine** and **Metabolic** |                                    |                      |            |               |
+---------------------------------+------------------------------------+----------------------+------------+---------------+
| **Renal**                       | * AV Fistula                       | * Fistula thrill     |            | * Fistula hum |
+---------------------------------+------------------------------------+----------------------+------------+---------------+
| **Gastrointestinal**            |                                    |                      |            |               |
+---------------------------------+------------------------------------+----------------------+------------+---------------+
| **Haematological**              |                                    |                      |            |               |
+---------------------------------+------------------------------------+----------------------+------------+---------------+
| **Integumentary**               |                                    | * Tense compartments |            |               |
+---------------------------------+------------------------------------+----------------------+------------+---------------+
| **Trauma**                      |                                    |                      |            |               |
+---------------------------------+------------------------------------+----------------------+------------+---------------+
| **Infective**                   |                                    |                      |            |               |
+---------------------------------+------------------------------------+----------------------+------------+---------------+
| **Malignant**                   |                                    |                      |            |               |
+---------------------------------+------------------------------------+----------------------+------------+---------------+
| **Toxic**                       |                                    |                      |            |               |
+---------------------------------+------------------------------------+----------------------+------------+---------------+
| **Immune**                      |                                    | * Lymphadenopathy    |            |               |
+---------------------------------+------------------------------------+----------------------+------------+---------------+
| **Congenital**                  |                                    |                      |            |               |
+---------------------------------+------------------------------------+----------------------+------------+---------------+
| **Obstetric**                   |                                    |                      |            |               |
+---------------------------------+------------------------------------+----------------------+------------+---------------+


---

## References

1. Foot C, Steel L, Vidhani K, Lister B, MacPartlin M, Blackwell N. Examination Intensive Care Medicine. Elsevier Australia; 2011. (Examination series).
1. Dünser MW, Dankl D, Petros S, Mer M. Clinical Examination Skills in the Adult Critically Ill Patient. Springer International Publishing; 2018.
