# Fasting 


Fasting:

* Aims to decrease the risk of perioperative regurgitation and aspiration of gastric contents  
May lead to:
	* Chemical pneumonitis
	* Bacterial pneumonia
	* Airway obstruction
* Should be of duration to minimise aspiration
* May be **detrimental when prolonged**
Fasting >6 hours may:
	* Prevent optimal gastric emptying
	* Lead to deleterious metabolic effects
	* Annoy patients


## Physiology

* Gastric residual volume often used as a surrogate for risk
	* No known volume which indicates a particular threshold of risk or eliminates all risk
* Fluids empty by first-order kinetics
* Solids empty by zero-order kinetics
* Gastric emptying time is increased following trauma, and standard fasting times may not be adequate

## Fasting for Adults

For elective surgery:

* **Solid** food up to **6 hours prior**
* **Clear fluid** of **200ml per hour up to 2 hours prior**  
Clear fluids are defined as:
	* Water
	* Pulp-free juice
	* Clear cordial
	* Black tea  
	Note milk is excluded.
	* Black coffee
* **Medications** may be taken up to **2 hours prior** with water
* Chewing gum should be discarded  
Due to risk of aspiration/foreign body rather than due to increasing gastric contents.

### Exceptions

These guidelines may not apply. Important considerations:

* High-risk patients
	* Delayed gastric emptying
	* Previous bariatric surgery  
		* Lap bands
		* Gastric bypass
	* Previous oesophagectomy
	* Oesophageal dysmotility
	* Pregnancy
* Use of risk-reduction techniques
	* Pharmacological
		* PPI
		* H<sub>2</sub>-antagonists
		* Antacids
			* Sodium citrate
			* Aluminium hydroxide
	* Rapid-Sequence Induction

## Fasting for Children

For elective surgery in children **> 6 months old**:

* **Breast milk**, **formula**, and **limited solid food** up to **6 hours prior**  
Includes milk drinks, food, lollies, and chewing gum.
* **Clear fluids** up to **1 hour prior**  
Clear fluids should be encouraged up to this point.
	* Timing varies depending on guideline  
	Check you local institutional practice.


For elective surgery in children **< 6 months old**:

* **Formula** up to **4 hours prior**
* **Breast milk** up to **3 hours prior**
* **Clear fluid** up to **1 hour prior**

---

## References

1. PS07: [Guidelines on Pre-Anaesthesia Consultation and Patient Preparation](https://www.anzca.edu.au/getattachment/resources/professional-documents/ps07_guidelines_pre-anaesthesia_consultation_patient_preparation.pdf). ANZCA. 2016.
2. Royal Children's Hospital Melbourne. [Fasting](https://www.rch.org.au/clinicalguide/guideline_index/Fasting_Guidelines/). Accessed 6/19.
3. Splinter WM, Schreiner MS. [Preoperative fasting in children](https://www.semanticscholar.org/paper/Preoperative-fasting-in-children.-Splinter-Schreiner/913966639884cb04bf2d0bf75c42d34e55adecee). Anesthesia and analgesia. 1999;89(1):80–9. 
