# Positioning


## Repositioning Checklist

Function and position must be checked after moving:

* Airway
	* Patent
	* In correct position
* Breathing
	* Capnography present
	* Pulmonary compliance appropriate
	* Bilateral air entry
	* SpO~2~ waveform present
* Circulation
	* Monitoring stable
	* IV lines connected and accessible
* Disability
	* Eyes  
	Free of pressure.
* Exposure
	* Bony areas padded


## Positions

Include:

* Supine
* Trendelenburg
* Reverse Trendelenburg
* Lateral
* [Prone](/anaesthesia/general/proneanaes.md)

### Supine

* Increased risk of airway obstruction
* Decreased FRC
* Decreased V~T~
* Increased VR and CO
* Loss of lumbar lordosis  
May lead to postoperative lower back pain.
* Use a wedge or table tilt to prevent aortocaval compression in the pregnant patient


### Trendelenburg

The head-down position:

* Airway oedema  
Due to increased venous pressure.
	* Check cuff leak prior to extubation
	* Consider dexamethasone
* Passive regurgitation of gastric contents
* Further reduction in FRC, compliance, and increased atelectasis  
Greater in obese patients due to weight of abdominal viscera.
* Results in more extreme CVS changes than the supine position  
	* Increased VR and LVEDP  
	Beware cardiac failure.
* Raised ICP
* Raised IOP


### Reverse Trendelenburg

The head-up position:

* Reduced VR  
May lead to hypotension.
* Reduces ICP  
Via increased venous drainage.
* Reduces CCP  
Via decrease in MAP at the level of the Circle of Willis.
* Increased risk of venous air embolism


### Lithotomy

* ETT displacement  
ETT typically moves cephalad in this position.
* Increased VR  
Venous pool drains from lower limbs.
	* May lead to volume overload
* Increased DVT risk
* Increased compartment syndrome risk  
Especially with prolonged (>5 hour) procedures.
Due to calf compression
* Neuropathy risk
	* Sciatic and obturator  
	Extreme flexion of the hip joints increases this risk.
	* Peroneal and saphenous nerve  
	Via calf compression.


### Lateral Position

In the positively-pressure ventilated patient in the lateral position:

* Increased V/Q mismatch  
May lead to hypoxia. Occurs as the:
	* Dependent lung is relatively underventilated and overperfused
	* Non-dependent lung is relatively overventilated and underperfused
* Highest risk of **ocular complications**  
Predominantly corneal abrasions.
* Brachial plexus compression
* Axillary compression  
Mitigate with use of an axillary roll.
* Venous outflow obstruction of dependent arm
* Peroneal and saphenous nerve compression  
Avoid by placing padding between legs.


### Seated/Beachchair

* Airway oedema
* Decreased cerebral perfusion pressure  
Consider arterial line placed at the level of the EAM to maintain cerebral perfusion.
	* Catastrophic cerebral hypoperfusion is rare but described
* Reduced venous return  
Can lead to significant hypotension.
* Venous air embolism  
Subatmospheric venous pressure and non-collapsible dural sinus predispose to this.


### Prone

*Covered in detail under [prone positioning](/anaesthesia/general/proneanaes.md)*.


---

## References

1. Knight DJW, Mahajan RP. [Patient positioning in anaesthesia](https://academic.oup.com/bjaed/article/4/5/160/291023). Continuing Education in Anaesthesia Critical Care & Pain. Oct 2004.
2. Pearce H, Soeding P, Hoy G. [Surgery in the "beach chair" position](http://www.anzca.edu.au/documents/the-beach-chair-position). ANZCA Bulletin. December 2013.