# Post-Operative Neuropathy


Peripheral nerve injury is:

* One of the most common anaesthetic complications
* Caused by a number of factors
	* Poor patient position\
	Leads to:
		* Stretching of the nerve
		* External compression


## Epidemiology and Risk Factors

Risk factors include:

* Male\
70%.
* Prolonged hospital stay
* Obesity
* DM
* Age


## Clinical Manifestations

* Typically is not evident in recovery\
	* May take 24 hours to become apparent
	* 90% of cases present within 7 days
* 47% sensory
* 25% involve ulnar nerve compression

## Management

Management is primarily preventative:

* Keep the arms by the side if possible
* Avoid >90° bend at elbow and shoulder
	* Rotate the head towards the abducted upper limb to reduce brachial plexus traction
* Supinate the upper limb to prevent ulnar nerve compression
* Avoid direct pressure in the axilla and shoulder
* Place pads under bony prominences
* Avoid rapid movement of the shoulder to prevent rotator cuff injury

## Prognosis

* 53% of patients recover within one year
	* Pure sensory loss has a better prognosis
	* ~25% have persistent pain

---

## References

1. Feix B, Sturgess J. [Anaesthesia in the prone position](https://academic.oup.com/bjaed/article/14/6/291/247907). Continuing Education in Anaesthesia Critical Care & Pain. 2014 Dec. Pages 291–297.
2. Knight DJW, Mahajan RP. [Patient positioning in anaesthesia](https://academic.oup.com/bjaed/article/4/5/160/291023). Continuing Education in Anaesthesia Critical Care & Pain. Oct 2004.