# Minimum Standards for Training Accreditation

CICM accredits units on a five-year cycle for the type and duration of training that may occur in a given unit. CICM expects units to demonstrate:

* High standard of unit culture, conducive to training and wellbeing of the unit
* Cultural safety
* Diversity of the inclusion of the ICU community
* Sustainable practices
* Active teaching and research programs


## General Requirements

The ICU must:

* Fulfill minimum standards for an ICU
* Offer a broad experience and acceptable case load, including within ICU (as distinct from HDU)
* Offer participation in out-of-hours rosters and outreach roles
* Maintain safe working hours
* Advertise available positions and appoint them following an approved process
* Allow access to ANZICS CORE data
* Provide a directed education program for general intensive care, and both exams
* Adequate access to educational resources
* Allow CICM to assess the unit for training suitability
* Notify CICM about changes in director, SoT, workload, case-mix, acuity, or ↓ in FTE


## Training Time

Units are divided into:

* General Training/C24/Unrestricted Core training
	* For Level III ICU and PICU
	* Major intensive care unit
	* Diverse case-mix; >1000 patients/year with >400 ventilated patients
	* \>12 months must be spent in one of these units
	* Entire core training may occur in one of these units
* General Training/C12/Limited 12 months core training
	* For Level III ICU, PICU< and occasionally level II ICU
	* Adequate case mix; >750 patients/year with >300 ventilated patients
	* Considered unsuitable for entirety of training time
* Limited General Training/C6/Limited to 6 months core
	* More limited case mix that indicates lack of suitability for >6 months of training\
	No more than 6 months of core training can occur in *any* C6 unit.


In addition to the above, other requirements include:

* Neurosurgical ICU training\
\>100 cases/year.
* Cardiac ICU training\
\>250 cases/year.
* Trauma ICU training\
\>100 cases/year.
* PICU training\
	* 12 months required if >50/year
	* 6 months required if >100/year
* Rural term


### Overseas Training

Training time in an ICU outside of Australia, Aotearoa New Zealand, or Hong Kong must:

* Be in an ICU that meets the CICM standards
* Be for up to 12 months of core training
	* The 12 months contiguous core training must occur in a CICM unit

---

## References

1. CICM. [IC-3 Minimum Standards for Intensive Care Units Seeking Accreditation for Training in Intensive Care Medicine](https://cicm.org.au/CICM_Media/CICMSite/Files/Professional/IC-3-Minimum-Standards-for-Intensive-Care-Units-Seeking-Accreditation.pdf). 2021.