# Review and Appeals

Any individual **adversely affected** by a **college decision** that is **inconsistent with CICM policy** may make a request to the college CEO that a committee be formed to:

* Reconsider the decision
* Review the decision
* Appeal the decision


## Reviewable Decisions

Decisions that can be appealed include:

* Selection into training
* Decisions of the:
	* Censor
	* Exam committee
	* Hospital accreditation committee
	* Supervisors of training progression decisions
	* Formal project assessment committee
	* Overseas trained specialists committee
	* Board with respect to:
		* Admission to fellowship
		* CPD activities
		* Financial status of fellows


## Reconsideration Committee

Committee formed of the **same people who made** the **original decision**, which:

* Is formed by the college CEO after written appellant appeal
* Should be provided with any additional relevant information by the appellant
* Will provide the appellant with a written decision, justifying the reasons
	* May be further appealed, which is performed by a review committee


## Review Committee

Committee formed of **different people to** those who made the **original decision**, which will:

:::column-margin
**Natural justice** are the principles of fairness and equity that should be upheld in legal and administrative proceedings, and include the right to:

* Be heard
* Receive a fair decision, based on impartial judgment
:::

* Consider:
	* All initial information
	* All additional information
	* The principles of natural justice
* Provide a written decision to:
	* The appellant\
	Does not have to include justification.
	* The original committee


## Appeals Committee

Last resort, formed by the college CEO after they are satisfied that the appellant has exhausted all other avenues for reconsideration and review. The appeals committee:

* Must be requested within 6 months of the decision
* Places onus of proof on the appellant
* Conforms on grounds of:
	* Error in law or due process
	* Relevant and significant information not properly considered
	* Original decision inconsistent with evidence and arguments put before the original decision maker
* Consists of a:
	* Chair\
	College vice-president or another board member.
	* Members\
		* 2 FCICM\
		⩾1 with specialised knowledge of the subject matter.
		* 2 non-FCICM who are appropriately qualified\
		⩾1 a member of the legal profession.
		* No one who is party to the original decision
	* College CEO\
	Acts as secretary.
	* College solicitor\
	Acts as legal adviser.
* Quorum requires chair and three other members
* Chair exercises a casting vote if the vote is otherwise equal
* Acts according to natural justice
* Is not bound by rules of evidence, and may inform itself on any matter as it sees fit
* Will give the appellant:
	* 21 days notice
	* A convenient location\
	Same state or territory.
	* The right to appear, or have a representative appear
	* To request legal representation
	* A cost cap of $1000 AUD
* Will produce a report to the Board with its recommendations, but no minutes
* Decisions can include:
	* Sustaining the decision
	* Revoking the decision
		* In entirety
		* And refer to the board or relevant committee
		* And replace it with an alternative decision
	* Recommending waiver of costs to the appellant
	
---

## References

1. CICM. [IC-23 Appeals, Review and Reconsideration Processes](https://cicm.org.au/CICM_Media/CICMSite/Files/Professional/IC-23-Appeals,-Review-and-Reconsideration-Processes.pdf). 2016.