# Prevention of Bullying, Discrimination, and Harassment

Trainees and fellows shall not bully, victimise, harass, or discriminate against *anyone*:

:::column-margin
"Anyone" is not stated by CICM, and instead explicitly listed as:

* CICM employees
* CICM contractors
* CICM committee members
* Other fellows
* Other trainees
* IMG
* Other people in the workplace
* Members of the public
:::

* **Discrimination**\
**Treating** a **person** with an **identified attribute** or personal characteristic **less favourably** than a person who does not have that characteristic. Legislatively defined characteristics include:
	* Gender\
	Including transgender.
	* Pregnancy
	* Potential pregnancy
	* Childbirth
	* Breastfeeding
	* Martial status
	* Sexual orientation
	* Lawful sexual activity
	* Disability
	* Impairment
	* Race\
	Colour, nationality, descent, origin.
	* Physical features
	* Age
	* Carer status
	* Family responsibilities
	* Religious beliefs and activities
	* Political beliefs and activities
	* Union membership or industrial activity
	* Association to any of the above
* **Harassment**\
**Behaviour** that is:
	* **Unwelcome**
	* Likely to humiliate, embarrass, offend, or intimidate
	* **Based on** a **personal characteristic**\
	See the above list.
* **Sexual harassment**\
Sexual behaviour that meets the criteria for harassment. May include:
	* Behaviour accompanied by direct or implied threats, benefits, or promise
	* Physical contact, comments, jokes, propositions, "graphic verbal commentaries"
	* Behaviour that creates a "sexually permeated" working environment
* **Victimisation**\
**Unfair treatment** of a person **following** a **compliant** of harassment, which causes them to feel uncomfortable, isolated, insecure, or intimidated.
* **Bullying**\
**Unreasonable**, **repeated** or pattern of **behaviour that creates** a **risk** to health and safety.
	* Unreasonableness is defined as that which could expect to:
		* Victimise
		* Humiliate
		* Undermine
		* Threaten
	* Divided into:
		* **Direct bullying**\
		Overt conduct, including:
			* Aggression
			* Intimidation
			* Spreading misinformation
			* Interfering with property
			* Displaying offensive material.
		* **Indirect bullying**\
		Conducting that excludes or removes a person, including:
			* Assigning meaningless tasks
			* Altering rosters to inconvenience someone
			* Withholding information required for work


## Complaints

Redress of grievances:

* Should be sought first from HR, or by an external body such as Worksafe for any conduct occurring in the workplace
	* CICM may also be contacted for support whilst a compliant is being investigated by another body
* From CICM for any conduct that occurred at an official CICM activity


Principles guiding CICM complaint resolution process:

* **Confidentiality**\
Need-to-know principle applies.
* **Impartiality**
* **Time-frames**\
Addressed efficiently.
* **Defamation**\
Risk is minimised by confidentiality.
* **False accusations**\
Taken seriously, if found to be malicious may result in defamation proceedings or disciplinary action.
* **Intent**\
Acceptable comments to one person may be offensive to another: innocent intent is not a defence.
* **Support person**\
May be a family member, advisor, or co-worker; cannot be a witness in the same complaint.
* **Counselling**\
May be sought independently.


### College Resolution Processes

CICM provides two complaint resolution processes:

* **Informal resolution process**\
Aim to achieve resolution, rather than present factual proof or substantiate the dispute. May include:
	* Self-help
	* Seeking assistance
	* Mediation
	* Resolution
* **Formal resolution process**\
Written compliant which aims to substantiate evidence of the claim.
	* Appropriate when:
		* Informal resolution has failed
		* Informal resolution is rejected
		* The allegation is serious
	* Requires:
		* Written complaint to CICM CEO
		* CEO appoints impartial investigator
		* Investigator separately interviews complainant, respondent, and any witnesses\
		Witnesses, and employers cannot be compelled.
		* Report is produced and returned to the CEO
		* Investigator arranges a meeting between both parties
		* Resolution may include:
			* Apology and commitment to behaviour change
			* Disciplinary action
				* Professional censure
				* Withdrawal of SOT rights
				* Suspension of fellowship/training
				* Termination of fellowship/training
			* Closed as unsubstantiated
		* Appeal is available for both complainant and respondent


### Rights

The **complainant** has a **right** to:

* Have their compliant treated informally or formally
* Have their complaint investigated or conciliated
* Support
* Express concerns without fear of retribution
* Withdraw the complaint
* Privacy
* To a remedy


The **respondent** has a **right** to:

* Be informed of what they are accused of, and by whom
* To respond
* To fair treatment, free of prejudgment and discrimination
* Support
* Not be dismissed, treated unfairly, or treated unreasonably
* Privacy
* Protection from defamation and malicious complaints 


---

## References

1. CICM. [IC-20 Prevention of Bullying, Discrimination and Harassment in the Workplace](https://cicm.org.au/CICM_Media/CICMSite/Files/Professional/IC-20-Prevention-of-Bullying,-Discrimination-and-Harassment-in-the-Workplace.pdf). 2016.