# Critical Care Echocardiography

Echocardiography is mainstream in critical care practice and a valued adjunct to history, physical examination, and standard investigations. Echocardiography is:

* Used in management of:
	* Undifferentiated shock
	* Post-cardiac surgical patient
	* Patients in cardiac arrest
	* Interventional guidance
* Immediately available
* Bedside investigation
* Non-invasive
* Repeatable

:::column-margin
Note that this summary combines both the CICM *policy* for levels of training in echocardiography (IC-29) and the *statement* on the role of echocardiography in intensive care (IC-24).
:::

## Classifications

CICM classifies echocardiography in critical care into:

* Focused cardiac ultrasound
* Advanced critical care echocardiography
* Expert critical care echocardiography


### Focused Cardiac Ultrasound

* Basic level for assessment of critically ill patients
* Answer specific, limited range of clinical questions
	* Types of shock
	* Major physiological abnormalities
* Required as part of the CICM curriculum
* Requires:
	* Attendance ata an accredited course
	* A short, on-line exam
	* Completion of a 30-case logbook of ICU patients, signed off by an accredited supervisor


### Advanced Critical Care Echocardiography

* Examination with expertise similar to a cardiologist
* Divided, based on training and experience, into:
	* TTE only
	* TTE and TOE
* TTE requires:
	* Completion of an accredited course with exit exam
		* Physics
		* Knobology
		* Artefact formation
		* Image optimisation
		* Quantitative assessment of haemodynamic states
	* Completion of 450-case logbook\
		* 2/3^rds^ in a critical care environment
		* 300 performed and reported
		* 150 reported
	* Ongoing CPD
* TTE and TOE requires:
	* All TTE requirements
	* 50 TOE studies
		* 1/2 performed in a critical care environment
		* 25 performed and reported
		* 25 reported


### Expert Critical Care Echocardiography

* Excellence in all aspects of practice and training
* Involvement in echocardiography research and publications
* Endorsed by peers
* Requires:
	* Advanced TTE and TOE for ⩾7 years
	* Substantive involvement in education and training
	* Ongoing echocardiography CPD


---

## References

1. CICM. [IC-29 Levels of Training in Adult Critical Care Echocardiography](https://cicm.org.au/CICM_Media/CICMSite/Files/Professional/IC-29-Levels-of-Training-in-Adult-Critical-Care-Echocardiography.pdf). 2018.
2. CICM. [IC-24 Statement on the Role of Echocardiography in Intensive Care Medicine](https://cicm.org.au/CICM_Media/CICMSite/Files/Professional/IC-24-Statement-on-the-Role-of-Echocardiography-in-Intensive-Care-Medicine.pdf). 2016.