# Older Intensivists

CICM values the wisdom of older intensivists. CICM also believes:

* The older intensivist should:
	* Understand the effects of aging
	* Develop a retirement plan
	* Have active involvement in CPD throughout their career
	* Consider the nature of the practice in light of their physical and mental capabilities
* The workplace should:
	* Match the volume and acuity of work to the pace of older intensivists
	* Produce an environment where night work is reduced for the older specialists
	* Transition older intensivists from more complex clinical duties to other tasks, such as administration, supervision, mentoring, and teaching
* That CICM should:
	* Consider the above when conducting its accreditation process
	* Support education and CPD activities tailored to the needs of the older specialist
	* Provide advice and assistance to members and regulators when age-related decline precludes safe practice

---

## References

1. CICM. [IC-19 Statement on the Practice of Intensive Care Medicine and the Older Intensive Care Specialist](https://cicm.org.au/CICM_Media/CICMSite/Files/Professional/IC-19-Statement-on-the-Practice-of-Intensive-Care-and-the-Older-Specialist.pdf). 2019.