# Foundation Training

All ICUs accredited for core training are suitable for foundation training. Accreditation for foundation training alone:

* Occurs for a 5-year cycle
* Requires:
	* ⩾5 beds, ⩾3 of which are ventilated
	* ⩾250 admissions annually
		* Broad case mix of medical and surgical patients
		* Reasonable acuity
	* Established policy and procedures for:
		* Admission
		* Discharge
		* Common scenarios
		* Inter-hospital transport
	* Regular use of invasive haemodynamic monitoring and ventilation
	* Outreach program
	* Availability of educational resources and structured education program
	* QI process
	* Appropriately qualified director
	* ⩾1 FCICM with significant clinical role
	* Appropriately trained nursing staff
	* Appropriate trainee ICU workload

---

## References

1. CICM. [IC-33 Minimum Criteria for Hospitals Seeking Accreditation for Foundation Training for Intensive Care](https://cicm.org.au/CICM_Media/CICMSite/Files/Professional/IC-33-Minimum-Criteria-for-Hospitals-Seeking-Accreditation-for-Foundation-Training-in-Intensive-Care-Medicine.pdf). 2020.