# Gender Balance

CICM recognises the local and global gender imbalance in intensive care medicine, particularly in senior academic and leadership positions, and commits to:

* Improving gender balance by:
	* Promoting a culture of inclusivity
	* Setting targets for female representation in:
		* College-affiliated meetings
			* Minimum 50% female speakers
			* Aim for diversity in all sessions
			* Early invitations for speakers
		* Training
			* Objective trainee selection criteria
			* Tools that select for diversity
			* Blinding initial applications
			* Gender-balanced selection panel
			* Avoid discriminatory interview questions
		* Interview panels\
		All CICM-accredited employment panels should aim for 50% female representation.
	* Publicly auditing female representation across the breadth of college leadership
	* Supporting flexible training:
		* Part-time training and ICU positions
		* Rosters supportive of pregnancy and breast-feeding
* Promoting respect and inclusivity
	* Training trainees and fellows to call out inappropriate behaviour
	* Include unconscious bias training within workshops addressing how to provide feedback

---

## References

1. CICM. [IC-28 Statement On Gender Balance Within The College Of Intensive Care Medicine](https://cicm.org.au/CICM_Media/CICMSite/Files/Professional/IC-28-Statement-On-Gender-Balance-Within-The-College-Of-Intensive-Care-Medicine.pdf). 2016.