# Healthcare Industry Relationships

:::caution
Remember, while the healthcare industry generally makes its approaches to doctors, healthcare facilities or professional organisations, the ultimate beneficiary of the approach must be the patient.
:::

Professional and ethical issues may arise from physician involvement with healthcare injury. **General principles** include:

* Formal and open **declaration** of any **industry support**
* Industry associations with CICM do not imply endorsement, and require regular disclaimers
* **Patient benefit should be the basis of any association**
* Any arrangements or negotiations in a personal capacity cannot reference CICM


## Meetings

### College-Organised, Industry-Sponsored

* Must be under the control of a college organising committee
* The committee may include industry representation
* Industry support must be fully declared, and endorsement disclaimers used
* Any profit must be devoted to dedication or research
* Normal college meeting guidelines apply


### Industry-Organised

* Should not have any CICM affiliation
* CICM representatives will not be present; members of CICM will be there in a personal capacity
* Member attendance should be in accordance with general principles


## Research

* Accepted that healthcare industry is a major research sponsor
* Written contract required between all parties
	* Must include a neutral third party\
	e.g. University, hospital, research foundation.
	* Contract subject to rules of third party
* Normal ethics committee procedures must be followed


## Other

* Industry-sponsored prizes awarded to fellows or trainees must be awarded entirely by an independent committee
* Industry-funded employment must be paid through a neutral third party
* Funding to facilitate educational attendance or talks should:
	* Be acknowledged
	* Considered based on the professional benefit of involvement
	* Any talks given should be presented in an unbiased manner

---

## References

1. CICM. [IC-6 Guidelines for Relationship Between Fellows, Trainees and Healthcare Industry](https://cicm.org.au/CICM_Media/CICMSite/Files/Professional/IC-6-Guidelines-for-Relationship-Between-Fellows-Trainees-and-Health-Care-Industry.pdf). 2019.