# Return to Practice

Any specialist returning to practice following an absence should have the opportunity to upgrade their:

* Knowledge
* Clinical skills
* Professional qualities

:::column-margin
CICM states it "has no program to assist impaired doctors", and that any concerns about impairment of an intensivist should be raised with the clinician and the regulator.
:::

## Re-entry Programs

Programs should be individualised based on the:

* Experience, skills, and personality of the intensivist
* Duration of absence\
Formal re-entry program required after **3 years** of absence.
* Nature of returned practice


In general, programs should:

* Be planned by the fellow with the aid of a mentor
	* Plan should be submitted to the Chair of the Fellowship Affairs Committee
* Include some period of supervised practice\
~4 weeks for each year of absence.


## Re-training Programs

Re-training may be:

* Requested in writing to the CICM president or CEO by:
	* Fellows
	* Medical boards
	* Regulatory bodies
* Reviewed by the Chair of the Fellowship Affairs Committee
	* If approved, will collaboratively develop a program with the fellow and supervisor that:
		* Goals specific to the areas of concern
		* Expected outcomes
		* Timeframes
		* Feedback processes
		* Supervision requirements
		* Indemnity for CICM and the fellow
	* On completion, will communicate outcomes to the fellow and the requester

## Special Circumstances

* Retired fellows seeking re-instatement must apply in writing to the CICM president or CEO


---

## References

1. CICM. [IC-15 Recommendations on Practice Re-entry, Re-Training and Remediation for Intensive Care Specialists](https://cicm.org.au/CICM_Media/CICMSite/Files/Professional/IC-15-Recommendations-on-Practice-Re-entry,-Retraining-and-Remediation.pdf). 2019.