# Specialist Practice

Expected duties of an intensivist may be:

* **Clinical**\
Exposure must be sufficient to maintain clinical skills.
* **Administrative**\
Sufficient time must be available for non-clinical duties.
	* 3 days/fortnight is recommended for full time staff
	* More may be required with major commitments
		* Director\
		Additional 3 days/fortnight.
		* Supervisor of training
	* Visiting specialists should receive a proportionate allotment


## Clinical Duties

* Provide care and assume responsibility for ICU +/- HDU patients
	* Should be predominantly present within a pod of 8-15 patients
	* Exclusively rostered and available to attend the pod when rostered on
	* Other commitments should only be undertaken when suitable specialist cover is available
* Supervise junior medical staff
* Be available for consultation with colleagues, urgently if required
* May include outreach duties, including:
	* Acute resuscitation
	* Transport
	* Vascular access
	* TPN
* May include advice to:
	* Management
	* Regulatory bodies
	* Professional bodies


## Administrative Duties

* Education
* Audit and QI
* CPD
* Committees
* College activities
* Research


---

## References

1. CICM. [IC-2 Guidelines on Intensive Care Specialist Practice in Hospitals Accredited For Training in Intensive Care Medicine](https://cicm.org.au/CICM_Media/CICMSite/Files/Professional/IC-2-Guidelines-on-Intensive-Care-Specialist-Practice.pdf). 2013.