# Clinical Supervision of Trainees

An appropriate level of supervision should be available at all times, and is:

* Required to develop clinical compotenence and the skills for safe independent practice
* Determined dynamically, and tailored based on:
	* The attributes of the trainee
		* Competence
		* Reliability
		* Honesty
		* Humility
	* The experience of the supervisor
	* The familiarity of the supervisor with the trainee
	* The nature of the work\
	Critical procedures may demand an ↑ level of supervision, e.g.:
		* Major interventions
		* Communication
* Inclusive of administrative and non-clinical duties, including:
	* Documentation
	* Research
	* Audit
	* QI programs


## Levels of Supervision

Clinical supervision is divided into:

1. **Direct Supervision**\
Requires direct observation, prompting, or active collaboration with the supervisor.
2. **Proactive Supervision**\
Requires presence and availability of the supervisor in the unit.
3. **Responsive Supervision**\
Requires the supervisor in the hospital and available for consultation and assistance.
4. **Oversight**\
Requires the supervisor to be readily contactable, but not in the hospital.
5. **Independent**\
Performs at the level of a junior FCICM, and can supervise junior trainees.


## Special Circumstances

Each ICU may set a policy that mandates discussion with the supervisor. Examples may include:

* Patient admission
* Referral or refusal of admission
* Unplanned discharge
* Unexpected or unexplained deterioration
* Performance of or requirement for complex therapy
* Management of children
* Major changes to management
	* Brain death determination
	* Withdrawal of cardio-respiratory support
	* Organ procurement
* Major discussions affecting management
	* Patient
	* Family
	* Other medical teams
* Interhospital transfer

---

## References

1. CICM. [IC-4 Guidelines on the Supervision of Vocational Trainees in Intensive Care Medicine](https://cicm.org.au/CICM_Media/CICMSite/Files/Professional/IC-4-Guidelines-on-the-Supervision-of-Vocational-Trainees-in-Intensive-Care-Medicine.pdf). 2020.