# Sustainability

CICM recognises that climate change poses severe threats, including to health, and that healthcare contributes significantly to the carbon footprint. Consequently, CICM advocates for:

* Energy efficient health-care strategies
	* Prioritisation of preventative therapy to prevent escalation to carbon-costly critical care
	* Formation of hospital sustainability teams
	* Collaboration with indigenous groups
	* Promotion of energy efficiency initiatives:
		* Air conditioning
		* Lighting
		* Medical equipment
		* Architectural design
		* Renewable energy sources
* Energy-efficient conferences:
	* 'Green event' planning
	* Video conferencing
* Individual actions:
	* Public transport
	* Cycling
	* Walking
	* Minimise air travel
		* Use carbon offset
	* Green-accredited accomodation
	* Teleconferencing
* Research in the effects of climate change on critical illness

---

## References

1. CICM. [IC-30 Statement on Sustainability](https://cicm.org.au/CICM_Media/CICMSite/Files/Professional/IC-30-Statement-on-Sustainability.pdf). 2019.