# Welfare Advocacy

CICM recognises the importance of welfare and wellbeing, and encourages the appointment of a welfare advocate. The welfare advocate is:

* A departmental role
	* Not a CICM appointment
	* Should be resourced by the department
	* Duties should include:
		* Welfare promotion
		* Development of welfare-related policies
		* Resource for colleagues seeking help
		* Coordination with other welfare advocates
* Not a therapeutic role\
Should be a neutral, safe, confidant who provides access to *support* services.
* Approachable, fair, and non-judgmental
* Not the Director of the unit

:::column-margin
Situations requiring support may include:

* Physical health
* Mental health
* Substance use and abuse
* Critical incidents
* Financial difficulty
* Family difficulty
* Sexual harassment, discrimination, and bullying
* Support of at-risk colleagues
* Mandatory reporting
* Mentoring
:::

---

## References

1. CICM. [IC-31 Guidelines on the Welfare Advocate Role in Intensive Care Units](https://cicm.org.au/CICM_Media/CICMSite/Files/Professional/IC-31-Guidelines-on-the-Welfare-Advocate-Role-in-Intensive-Care-Units.pdf). 2019.