# Health and Wellbeing

Physicians have a responsibility to maintain their own health and wellbeing, which includes:

* Lifestyle activities
* Health checks
* Vaccinations
* Specific illness management

## Personal

CICM expects members to:

* Have an identified GP
* Not self-prescribe
* Seek formal medical consultations for personal health issues
* Develop long-term health and well-being management strategies, including preparation for major life events
* Not provide medical services to family, close friends, and close colleagues
* Advise their director or SOT of any health problems that may impact on their work


## Professional

CICM expects the workplace to:

* Promote an environment that prioritises physical, psychological, and professional well-being of staff, and encourage them to appropriately access healthcare
* Maintain a list of resources to assist staff with health issues
* Provide orientation and support programs
* Encourage CPD activities that maintain health and wellbeing
* Establish mentorship programs
* Adopt work practices that minimises potential for fatigue, ill-health, and error\
e.g. Rostering and call.


---

## References

1. CICM. [IC-5 Statement on the Health and Wellbeing of Fellows and Trainees](https://cicm.org.au/CICM_Media/CICMSite/Files/Professional/IC-5-Statement-on-the-Health-of-Specialists-and-Trainees.pdf). 2018.