# Witholding and Withdrawing Treatment

Intensive care:

* May improve both quality and quantity of life
* Can cause considerable suffering for both patients and families
* May be **appropriate** to **withhold** or withdraw when there is **no** potential **benefit**\
	* This assessment is based on probability rather than certainty, and **involves weighing**:
		* **Potential benefits** of treatment
		* **Burden** of treatment
			* Pain
			* Suffering
			* Loss of dignity
		* Known **views** of the **patient**
			* Directly if competent
			* Via advanced directive, next-of-kin, or another confident if incompetent


## Considerations

* There is no obligation to initiate or continue ineffective therapy
* The competent adult is entitled to withhold or withdraw consent for any treatment at any time, even if this may shorten their life\
Under these circumstances, the clinician has a responsibility to:
	* Assess competence
	* Provide all information required to fully inform decision
* Treatment limitation may be raised by:
	* The patient
	* Patient family and friends\
	Weighed against what is known or inferred from patients wishes and values.
	* Healthcare professionals
* Basis and nature of treatment limitations should be documented
* Witholding and withdrawing treatment are legally and ethically equivalent, and the principles and processes used should be the same


---

## References

1. CICM & ANZICS. [IC-14 Statement on Withholding and Withdrawing Treatment](https://cicm.org.au/CICM_Media/CICMSite/Files/Professional/IC-14-Statement-on-Withholding-and-Withdrawing-Treatment.pdf). 2021.