# Intra-aortic Balloon Pump {sec-iabp}

Assisted circulatory device consisting of an intra-aortic balloon which:

* ↑ CO by 0.5-1L/min
* Provides temporary myocardial support as bridge to recovery or definitive treatment
* Acts via **counterpulsation** to improve myocardial supply:demand\
Deflates pre-systole and inflates during diastole, causing:
	* **Improved coronary perfusion**\
	Diastolic inflation ↑ DBP and improves coronary perfusion pressure and myocardial oxygen supply.
	* **↓ Afterload**\
	Pre-systolic deflation ↓ afterload and myocardial wall tension, ↓ myocardial oxygen demand and myocardial work.
* Improves forward flow rather than just inotropy\
Better in lesions where contractility may be adequate despite a low SV, e.g.
	* MR
	* VSD

## Indications

* Reversible cardiogenic shock
	* Post-bypass
	* Post-MI
	* Severe IHD\
	Bridge to stenting or CABG.
	* Severe acute MR\
	Awaiting surgery.

## Contraindications

* Cardiac
	* AR
	* Tachyarrhythmias\
	Less effective in:
		* Tachycardia\
		↓ Viable inflation/deflation time.
		* Irregular rhythms\
		Timing challenges.
* Anatomical
	* Aortic dissection
	* Severe peripheral vascular disease
	* Aortic aneurysm
	* Aortic grafts
* Other
	* Coagulopathy
	* Local infection
	* Sepsis
	* Lack of expertise


## Anatomy

## Equipment

* Catheter sheath\
Usually 7.5 Fr.
* Catheter balloon
	* 25-50mL\
	Size should:
		* Cover from L SCA origin to coeliac artery
		* Fill 90-95% of the aorta
		* Augmentation optimised when balloon volume equals stroke volume
	* Helium-filled\
	Low viscosity speeds inflation and smooths deflation.
* Console\
Contains pump, helium cylinder, and times inflation/deflation.


## Technique

**Patient selection**:

* Cardiogenic shock
	* Of a form less responsive to inotropes
	* Without a stronger indication for VA ECMO or Impella
* Adequate vasculature
	* Accessible and un-tortuous femoral vessels
	* No acute aortic pathology

:::column-margin
Some aortic stiffening is probably helpful though - an elastic and compliant aorta will distend during balloon inflation, impeding diastolic augmentation.
:::

**Use**:

* Setting ratio\
Proportion of augmented to non-augmented beats.
	* 1:1
	* 1:2
	* 1:3\
	Identical to no support.
	* 1:4\
	Used prior to removal. ↑ risk of thrombus formation.
* Setting trigger\
May be:
	* ECG\
	May target from R wave.
	* Pacemaker\
	From pacing spikes.
	* Arterial\
	From arterial upstroke.
	* Internal trigger\
	In asystole.
* An optimised waveform
	* Measure at 1:2
	* Slope of augmented diastolic upstroke should be:
		* Straight
		* Parallel to augmented systolic upstroke
	* Augmented DBP should exceed unaugmented SBP
	* DBP at end of augmented stroke should be lower than unaugmented DBP by 15mmHg
* Anticoagulation
	* Practices vary
		* Heparinised saline through transducer
		* Low-dose systemic heparin
	* May not be required in first 24 hours


**Optimisation**:

* Optimising location
	* Balloon distal to L SCA, 2cm above left main bronchus
* Optimising timing
	* Should be performed in a 1:2 ratio


**Weaning**:

* Once inotropic requirements minimal
* Achieved gradually


## Complications

* Vascular
	* Limb ischaemia
	* Vascular injury
		* Dissection
		* Pseudoaneurysm
		* Vessel injury/rupture
	* Embolism
		* Dislodged atheroma
* Device
	* Balloon rupture\
		* Gas embolism
	* Stroke	
		* Balloon thrombosis and embolism
		* Aortic atheroma dislodgement
	* Haemolysis
	* Infection	
* Use
	* Incorrect positioning
		* Mesenteric ischaemia
		* Failure of augmentation	



---

## References


1. Parissis H, Graham V, Lampridis S, Lau M, Hooks G, Mhandu PC. IABP: history-evolution-pathophysiology-indications: what we need to know. Journal of Cardiothoracic Surgery. 2016;11(1):122. doi:10.1186/s13019-016-0513-0
