# Vasopressors {#sec-vasopressors}

Vasopressors are drugs that predominantly constrict peripheral vasculature, causing a:

:::column-margin
Similar to @sec-inotropes, many vasopressors have inotropic effects. Unlike inotropes however, there are some *pure* vasopressors.
:::

* Primary ↑ in SVR, causing a secondary ↑ in MAP
* Primary ↑ venous tone which ↓ venous compliance and ↑ stressed volume, causing a secondary ↑ in preload

:::column-margin
Venous blood volume can be divided conceptually into:

* **Unstressed volume**\
Does not exert meaningful pressure on the walls of the vasculature, and so does not contribute to MSFP. Contributes ~85% of total vascular volume under normal circumstances.
* **Stressed volume**\
Exerts pressure on the walls of the vasculature and therefore produces MSFP.
:::


## Indications

Vasopressors are used:

* To correct **hypotension-induced hypoperfusion**\
i.e. When there is:
	* Evidence of ↓ end-organ perfusion
	* ↓ MAP
	* Despite adequate volume state
	* Despite adequate pump function
* For therapeutic *hyper*tension
	* TBI
	* DCI
	* Spinal cord ischaemia


### Blood Pressure Targets

:::info
This applies to targets in the hypotensive, hypoperfused patient.
:::

Physiological rationales exist for a variety of targets:

* High MAP targets
	* ↓ AKI by improving renal perfusion pressure
	* May ↑ cerebral perfusion and improve neurological outcomes
	* Provides margin of safety for hypotensive episodes
	* Lower MAP associated with ↑ mortality
* Lower MAP targets
	* ↓ Dose of vasopressors required
		* ↓ Arrhythmia
		* ↓ Myocardial work
		* ↓ ICU length of stay
		* ↓ Fluids, steroids, etc. administered
		* Escalating doses may not be met with ↑ pressure, resulting in very high doses used

In general:

* MAP 65-70mmHg is reasonable in most patients in the resuscitation phase
* Lowering (to MAP 60mmHg) in the elderly to ↓ vasoactive requirements and harm of administration
* If there is evidence of end-organ perfusion, trial of a vasopressor-driven MAP challenge is reasonable\
Temporarily ↑ MAP target to evaluate for a given physiological response (e.g. ↑ UO).

## Contraindications

## Comparison

: Comparison of Vasopressors

+--------------------+---------------------------------+----------------------------+---------------------------------------+
| Drug               | Overview                        | Advantages                 | Disadvantages                         |
+====================+=================================+============================+=======================================+
| **Noradrenaline**  |                                 |                            |                                       |
|                    |                                 |                            |                                       |
|                    |                                 |                            |                                       |
|                    |                                 |                            |                                       |
|                    |                                 |                            |                                       |
+--------------------+---------------------------------+----------------------------+---------------------------------------+
| **Vasopressin**    | Endogenous nonapeptide\         | * Not a catecholamine\     |                                       |
|                    | Acts on V~1~ and V~2~ receptors | Works synergistically.     |                                       |
|                    |                                 | * Not affected by acidosis |                                       |
|                    |                                 | * Not pro-arrhythmic       |                                       |
|                    |                                 | * Fluid retention          |                                       |
+--------------------+---------------------------------+----------------------------+---------------------------------------+
| **Methylene Blue** |                                 | * Effective                | * Mesenteric vasoconstriction         |
|                    |                                 | * Cheap                    | * Coronary vasoconstriction\          |
|                    |                                 |                            | May lead to ischaemia.                |
|                    |                                 |                            | * MAO Inhibition                      |
|                    |                                 |                            | * Possibly ↑ microcirculatory change  |
|                    |                                 |                            | * Hyponatraemia                       |
|                    |                                 |                            | * Contraindicated in G6PD deficiency\ |
|                    |                                 |                            | Haemolysis.                           |
|                    |                                 |                            | * Inhibition of SpO~2~ monitoring     |
+--------------------+---------------------------------+----------------------------+---------------------------------------+


## Equipment

## Technique

## Complications

## Key Studies

**Targets**:

{{< include /trials/andromeda_shock.qmd >}}
{{< include /trials/65.qmd >}}


**Vasopressin**:

{{< include /trials/vaast.qmd >}}
{{< include /trials/vanish.qmd >}}


**Other**:

{{< include /trials/bellomo_dopa.qmd >}}
{{< include /trials/midas.qmd >}}
{{< include /trials/censer.qmd >}}
{{< include /trials/athos3.qmd >}}

---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.
1. Santer P, Anstey MH, Patrocínio MD, et al. [Effect of midodrine versus placebo on time to vasopressor discontinuation in patients with persistent hypotension in the intensive care unit (MIDAS): an international randomised clinical trial](https://link.springer.com/article/10.1007/s00134-020-06216-x). Intensive Care Med. 2020;46(10):1884-1893. doi:10.1007/s00134-020-06216-x
1. Lamontagne F, Richards-Belle A, Thomas K, et al. [Effect of Reduced Exposure to Vasopressors on 90-Day Mortality in Older Critically Ill Patients With Vasodilatory Hypotension: A Randomized Clinical Trial](https://jamanetwork.com/journals/jama/fullarticle/2761427). JAMA. 2020;323(10):938-949. doi:10.1001/jama.2020.0930
1. Gordon AC, Mason AJ, Thirunavukkarasu N, et al. [Effect of Early Vasopressin vs Norepinephrine on Kidney Failure in Patients With Septic Shock: The VANISH Randomized Clinical Trial](https://jama.jamanetwork.com/article.aspx?articleid=2540403). JAMA. 2016;316(5):509-518. doi:10.1001/jama.2016.10485
1. Russell JA, Walley KR, Singer J, et al. [Vasopressin versus Norepinephrine Infusion in Patients with Septic Shock](http://www.nejm.org/doi/full/10.1056/NEJMoa067373). New England Journal of Medicine. 2008;358(9):877-887. doi:10.1056/NEJMoa067373
1. Khanna A, English SW, Wang XS, et al. Angiotensin II for the Treatment of Vasodilatory Shock. N Engl J Med. 2017;377(5):419-430. doi:10.1056/NEJMoa1704154
1. Bellomo R, Chapman M, Finfer S et al. [Low-dose dopamine in patients with early renal dysfunction: a placebo-controlled randomised trial](https://pubmed.ncbi.nlm.nih.gov/11191541/). The Lancet. 2000;356(9248):2139-2143. doi:10.1016/S0140-6736(00)03495-4