# Paediatric Analgesia



## Simple Analgesia

* Paracetamol\
Up to 90mg/kg/day above 3/12; 60mg/kg/day in neonates and infants.
	* PO: 20mg/kg load, followed by 15mg/kg Q4H
	* IV: 15mg/kg Q6H
	* PR: 40mg/kg load, followed by 20mg/kg Q6H
* NSAIDS\
	* Ibuprofen\
	Up to 400mg.
		* PO: 5-10mg/kg Q6H
	* Diclofenac\
	Up to 50mg.
		* PO: 1mg/kg Q8H


## Opioids

* Morphine sulphate PO\
Up to 15mg. Dosing depends on age:
	* <1 month: 80μg/kg Q6H
	* 1-3 months: 100μg/kg Q4H
	* 3-12 months: 200μg/kg Q4H
	* ⩾1 year: 300μg/kg Q2-4H


### Infusions

Opioid infusions:

* Are useful in:
	* Young children
	* Physical restriction
	* Developmental delalay
* Are usually prescribed by infusion rate\
Concentration varies depending on weight of child.
* Include:
	* Morphine at 10-40μg/kg/hr
* Should be paired with regular simple analgesia

### Patient/Nurse Controlled Analgesia

PCAs in children:

* Can be used when they can:
	* Understand the concept\
	Usually over 8 years old.
	* Physically press the button
* Can be nurse-controlled when the child is unable to use it
* Provide psychological benefit by giving agency over analgesia
* Can supplement a background opioid infusion
* Are usually prescribed by a set volume\
Concentration varies depending on weight of child.
* Should be paired with regular simple analgesia

## Epidurals

Epidural anaesthesia:

* Usually sited under anaesthesia
* Achieved with continuous infusions:
	* 0.1% or 0.125% levobupivacaine\
		* ⩽6 months: 0.25mg/kg/hr
		* ⩾6 months: 0.4mg/kg/hr
	* 0.2% ropivacaine
		* 0.4mg/kg/hr
	* Opioids\
	Commonly added to infusion.
		* Morphine 1-5μg/kg/hr
		* Fentanyl 0.1-0.5μg/kg/hr

---

## References
