# Perioperative Evaluation of Paediatric Heart Murmurs


Heart murmurs in the paediatric patient are:

* Common  
50-85% of children may have a heart murmur.
* Usually innocent  


## Epidemiology and Risk Factors

Congenital cardiac disease:

* Increases mortality in non-cardiac surgery by 2x  
Major risk factors:
	* Cyanosis
	* Younger age
	* Complex defect
	* Comorbidities
	* Heart failure

## Clinical Manifestations

History:

* Toxins  
Pre- and peri-natal exposure to:
	* Alcohol
	* Lithium
* Infections
* Maternal diabetes
* Prematurity
* Family history of:
	* Sudden cardiac death
	* Cardiac disease
	* Sudden infant death
	* Congenital cardiac disease


Examination:

* Palpation of pulses
	* Assess for equality and delay
* Palpation of thrills
* Evaluation of features of murmur
* Features of right heart failure


Key symptoms include:

* B
	* Recurrent chest infections
	* Cyanosis
	* Tachypnoea
* C
	* Decreased exercise tolerance/constitutional symptoms
		* Failure to thrive
		* Feeding difficulties
		* Diaphoresis
		* Fatigue
	* Squatting posture during play  
	Suggests ToF spells.
	* Syncope
	* Oedema  
	Usually peri-ocular.
* D
	* Developmental delay




## Diagnostic Approach and DDx

> There are more detailed tables that cover this in textbooks, but this approach is probably more practical than deciding if a murmur is "musical"

Innocent murmurs:

* Have no signs of cardiac disease
* Are not harsh
* Are not purely diastolic
* Are not purely pansystolic
* Have no thrill
 

## Investigations

ECG:

* Evaluate evidence of ventricular hypertrophy

CXR

## Management

Factors favouring postponement, ECG, and paediatric cardiology opinion:

* Patients <1 year  
Severe pathology may be present in absence of symptoms.
* Symptomatic patients
* Syndromic patients

Factors favouring proceeding with surgery prior to evaluation:

* Asymptomatic
* Age ⩾ 1 year
* Normal ECG


### Timing of Review

Urgency of cardiology review depends on age:

* Neonates  
Hours.
* Infants  
Days.
* Children  
Weeks.


---

## References

1. Bhatia N, Barber N. Dilemmas in the preoperative assessment of children. Contin Educ Anaesth Crit Care Pain. 2011 Dec 1;11(6):214–8. 
2. Bester K. Anaesthetist’s evaluation of a child with a heart murmur. Southern African Journal of Anaesthesia and Analgesia. 2013 Jan;19(1):14–7. 
