# Considerations in Paediatric Anaesthesia {#sec-paeds_anaes}

Paediatric anaesthesia:

:::column-margin
This section covers various considerations for paediatric anaesthesia. The anaesthetic assessment of a paediatric patient is covered under @sec-paeds_anaes_ax.
:::

* Presents its own unique challenges
	* Technical\
	Small airways, veins.
	* Psychological
		* Child\
		* Parents
* Is more similar to adult anaesthesia than it is different


## Age-Independent Factors

Airway:

* ↓ Airway diameter\
ETT diameter significantly affects airway resistance.

Breathing:

* Notably **similar tidal volume** of 7mL/kg
* Similar **dead space volume**\
However apparatus dead space becomes proportionally more important.
* ↑ atelectasis\
PEEP requirement.

Circulation:

* Absence of coronary disease means children will tolerate significant doses of anaesthesia without circulatory compromise\
Assuming no congenital cardiac disease present.

Neurological:

* Significant anxiety is common to both children and parents around time of surgery:
	* Parental anxiety is:
		* Common
		* Often exaggerated understanding of risk
	* Child anxiety is common, and exacerbated by:
		* Lack of understanding
		* Lack of cooperation


Extremities:

* Temperature control\
Surface area to volume ratio ↑ heat flux (usually loss).
	* Minimise exposure\
		* Keep dressed in preop hold
		* Wrap in OT
	* Humidification
	* Forced air warmer\
	Underbody.
	* Consider warmed fluids\
	Only effective if high volumes being given.


### Allaying Anxiety

Use of language:

* Positive language\
Remove words with negative associations, e.g. pain.
	* "You'll usually wake up pretty comfortable, we'll give you extra medicine to make you more comfortable, and a nurse will be there to give you more medicine to keep you comfortable."
* Emphasis on safety rather than risk
* Reinforce positive behaviours
* Don't downplay pain and anxiety\
Says things will hurt if they will hurt.
* Reassure that concerns and anxiety is normal, but magnitude of risk is low in well children
* Project a sense of relaxation
* Engage in normal conversation with the parents and child


### Reducing Intraoperative Heat Loss

Reduce:

* Unnecessary exposure

↑ warming with:

* Radiant heaters
* Warm fluids
	* Intravenous
	* Irrigation
	* Skin preparation
* Active warmers
* Adjust operating theatre temperature
	* 20-22°C for children
	* 26-28°C for neonates
* Humidified ventilators
	* Circle system with HME
	* Inspiratory humidifiers


## Key Differences

This section covers key differences from adults relevant to paediatric anaesthesia, broken up by age groups.

### Premature, Neonates, and Infants

This group:

* Present the greatest:
	* **Technical** challenges\
	Both in difficulty, and in difference from adults.
	* Requirement for additional resources
* Probably has the highest parental anxiety
* Should have age calculated as **post-conceptual age**\
$PCA = Weeks \ of \ Gestation + Weeks \ since \ Birth$. 

+------------------+----------------------------------------------------------+------------------------------------------------------+------------------------------------------------------------------------+
| System           | Premature                                                | Neonate                                              | Infant (up to 2 years)                                                 |
+==================+==========================================================+======================================================+========================================================================+
| **A**            | - Very small everything                                  | - As premature                                       | - Difficult one-hand mask ventilation due to obstructed nasal passages |
|                  | - Best lying flat for intubation                         |                                                      | - Small ETTs are high resistance                                       |
|                  | - Consideration of Mac vs. Miller                        |                                                      |                                                                        |
|                  | - BVM usually **straightforward**                        |                                                      |                                                                        |
|                  | - Intubation can be difficult                            |                                                      |                                                                        |
|                  | - Small ETTs are high resistance                         |                                                      |                                                                        |
+------------------+----------------------------------------------------------+------------------------------------------------------+------------------------------------------------------------------------+
| **B**            | - Surfactant may be inadequate                           | - As premature                                       | - Frequent URTIs                                                       |
|                  | - **Apnoeas**                                            | - Essentially never appropriate for day-case surgery | - Smaller airway diameter\                                             |
|                  | - Desaturate *very* quickly                              |                                                      | ↑ Severity of bronchospasm and sputum plugging.                        |
|                  | - Difficult to preoxygenate                              |                                                      |                                                                        |
+------------------+----------------------------------------------------------+------------------------------------------------------+------------------------------------------------------------------------+
| **C**            | - Foetal shunts may be open/reopen; avoid air bubbles    | - HR dependent CO                                    | - Most difficult group for IV access                                   |
|                  | - Normal MAP ≈ weeks of gestation                        | - **Defend HR**                                      |                                                                        |
+------------------+----------------------------------------------------------+------------------------------------------------------+------------------------------------------------------------------------+
| **D**            | - **BSL** management critical; apnoea with hypoglycaemia | - **BSL** management critical                        | - **Separation anxiety**                                               |
|                  | - Cord terminates S1 at 28 weeks                         | - Cord terminates at L3 at term                      | - Cord terminates at L2/3 at 1 year                                    |
+------------------+----------------------------------------------------------+------------------------------------------------------+------------------------------------------------------------------------+
| **E**            | - **Temperature** management critical                    | - **Temperature** management critical                |                                                                        |
+------------------+----------------------------------------------------------+------------------------------------------------------+------------------------------------------------------------------------+
| **Other**        | - **Why are they premature?** Foetal/maternal            |                                                      |                                                                        |
+------------------+----------------------------------------------------------+------------------------------------------------------+------------------------------------------------------------------------+
| **Requirements** | - NICU                                                   | - NICU                                               | - Anaesthetic assistant capable of cannulating and ventilating         |
|                  | - Neonatologist                                          |                                                      |                                                                        |
+------------------+----------------------------------------------------------+------------------------------------------------------+------------------------------------------------------------------------+

#### Key Considerations in Neonates

CATABOLIC:

* **C**ongenital Associations\
One abnormality suggests presence of another abnormality.
* **A**pnoea\
Post-operative.
* **T**emperature\
Tendency to hypothermia.
* **A**ir in stomach\
Significantly impedes ventilation.
* **B**radycardias\
Indicate a low CO.
* **O**pioid sensitivity\
↑ CNS and respiratory effects.
* **L**ines\
Avoid air bubbles.
* **I**ntubation
* **C**alcium\
Contractility and blood pressure are dependent on extracellular calcium.
* **G**lucose\
Tendency to hypoglycaemia.

#### Changes in Infants in Detail

**Airway Differences:**

* Relatively large:
	* Head
	* Tongue
		* Difficult to negotiate with laryngoscopy
		* ↑ Risk of upper airway obstruction
		* Obligate nasal breathing in first few weeks of life\
			* ↑ Risk of obstruction with:
				* Nasal congestion
				* Foreign body
					* Nasal prongs
					* NGT
	* Epiglottis\
	May cover laryngeal inlet if laryngoscope is engaged in the vallecula - hence use of straight blades to elevate epiglottis.
* Relatively small mandible
* Prominent occiput
* Short neck and trachea
	* High risk of both endobronchial intubation and inadvertent extubation\
	Endobronchial intubation may be eithe left- or right-sided, as both main bronchi divert at the same angle.
* Higher larynx\
Results in relatively **anterior larynx**.


**Respiratory Differences:**

* ↑ VA:FRC ratio\
Change in inspired gas mixture rapidly alters alveolar (and arterial) gas composition.
	* Rapid uptake of volatile agents
* Higher closing volume (until 6-12 months) and reduced FRC\
	* ↑ Risk of atelectasis
	* ↑ Risk of shunt
	* Rapid desaturation 
* Immature respiratory centres
	* Periodic breathing with apnoeas in neonates
	* Sub-anaesthetic drug concentrations still affect respiration
* Anatomically inefficient alignment of thoracic bones, and weak respiratory musculature
	* Less efficient ventilation\
	Reliant on diaphragm as bucket-handle mechanism not functional.
	* ↓ Respiratory reserve
	* Earlier onset of respiratory failure due to fatigue
	* ↑ Chest wall compliance\
	Early appearance of intercostal and sternal recession when work of breathing is ↑.
* ↓ Number of thick-walled alveoli\
May only be 10% of adult total.


**Cardiac Differences:**

* ↓ Myocardial compliance\
Heart failure with ↑ volume due to poor Starling response.
* ↓ Contractility\
Due to ↓ number of elements.
	* Fixed stroke volume
	* CO is HR dependent
* Heart rate
	* Bradycardia is poorly tolerated\
	HR <60 does not give adequate CO - **commence CPR** in neonates, or when there are signs of inadequate perfusion in older children.
		* Atropine\
		Relative parasympathetic predominance in autonomically stressed child, but not always reliable.
		* Adrenaline\
		Better choice when bradycardia must be corrected immediately and reliably (which is usually the case).
			* Consider ~1μg/kg adrenaline for bradycardia in non-arrest situations\
			0.1ml/kg of 1:10,000 adrenaline, diluted into a 10ml syringe, will give 1μg/kg/ml.
	* Tachycardia is well tolerated
* Dominate vagal tone\
Bradycardia common with vagal stimuli, such as laryngoscopy, hypoxia.


**CNS Differences:**

* Incomplete blood-brain barrier\
Free passage of:
	* Opioids
	* Barbiturates
	* Bilirubin
* Open sutures and large anterior fontanelle
	* Can be used to evaluate presence of ↑ ICP
	* Sutures will open and fontanelle expand prior to ↑ in ICP
* Greater volume of CSF
	* Subarachnoid anaesthesia requires higher doses, and does not last as long
* Spinal cord occupies entire length of canal\
Canal and cord grow at different rates, so the termination moves cephalad with age:

* Incomplete ossification of sacral vertebrae\
Neuraxial techniques achievable.


**MSK Differences:**

* Sensitivity to **hypothermia** due to:
	* ↑ Surface area:volume ratio\
	↑ Heat losses to environment, and in respiratory vapour (due to higher MV).
	* ↓ Heat production\
	Weaker compensatory mechanisms:
		* Ineffective shivering
		* Poor vasoconstriction\
		Ineffective A-V shunts.
		* Non-shivering thermogenesis\
		Brown fat metabolism key to heat production.

**Renal Differences:**

* ↓ Tubular concentrating ability
* ↓ Renal bicarbonate levels
* ↓ GFR\
Reduced ability to cope with volume and electrolyte loads.


**Hepatic Differences:**

* Neonate
	* Reduced vitamin K dependent clotting factors in neonate
	* Reduced glucose storage in neonate
		* Hypoglycaemia common if not feeding
* Infants\
Up to 2-3 months:
	* Immature metabolic pathways
		* Many drugs\
		May prolong post-operative effects, and alter dosage intervals or infusion rates.
		* Bilirubin

**Pharmacological Differences:**

* Major differences occur in children up to ~6 months
* Absorption
	* Reduced IM and SC absorption
* Distribution\
	* Rapid distribution due to high CO
	* ↑ TBW and V~d~ of water-soluble drugs
	* ↑ ECF compartment volume\
	↑ required dosing for drugs distributed to ECF.
	* ↓ Plasma protein level and protein binding\
	↑ free drug fraction.
	* Poorly developed blood-brain barrier\
	↑ CNS distribution of drugs. 
* Metabolism
	* Immature hepatic metabolism
* Elimination
	* Immature renal function



### Young Children

2-4 year old children:

* Have interactions with adults other than parents\
* Recognise *something is up* when in hospital, and will be generally suspicious
	* Usually cannot be approached with a needle without significant distress
	* May benefit from premedication\
	Difficult to predict which children will require premedication.
		* ~50% of children who are predicted to be well behaved will not be
		* ~50% of children who are given a premedication will still be difficult to manage
	* **Tone of language** is important

+--------+-----------------------------------------------------------------+
| System | 2-4 Year Olds                                                   |
+========+=================================================================+
| **A**  | - Laryngospasm                                                  |
+--------+-----------------------------------------------------------------+
| **B**  | - Frequent URTIs                                                |
|        | - Asthma common                                                 |
+--------+-----------------------------------------------------------------+
| **C**  | - Assess METs with climbing, crying, and fighting with siblings |
+--------+-----------------------------------------------------------------+
| **D**  | - Parental involvement helpful for child anxiety                |
+--------+-----------------------------------------------------------------+


### Primary School-Aged Children

5-10 year old children:

* Physiology is more similar to adults
* Primary issue is psychological
	* Word choice is crucial\
	Avoid:
		* Needle
		* Mash
		* Pain
		* Separation (from parent)
		* Vomit
		* Nausea
		* Sick
	* Distraction and hyponosis are beneficial
	* In general, believe that the world is fair and adults Do The Right Thing\
	Play to this.
	* Ideally, use one voice during induction\
	Yours or the parents; but avoid chattering.

+--------+-----------------------------------------------------------------+
| System | 5-10 Year Olds                                                  |
+========+=================================================================+
| **A**  | - Loose teeth                                                   |
+--------+-----------------------------------------------------------------+
| **B**  | - Frequent URTIs                                                |
|        | - Asthma                                                        |
|        | - Respiratory management                                        |
+--------+-----------------------------------------------------------------+
| **C**  | - Assess METs with climbing, crying, and fighting with siblings |
+--------+-----------------------------------------------------------------+
| **D**  | - **Choose words carefully**                                    |
|        | - Distractible                                                  |
|        | - Cord terminates at L1/2 at 8                                  |
+--------+-----------------------------------------------------------------+

### Secondary School-Aged Children

11-18 year old children:

* Physiology and management almost identical to adults
* Psychological differences remain the major difference\
Tend to respond in two ways to the stress of hospital and disease. Consult should be tailored appropriately.
	* Child-like response\
		* Frustrated, angry, "unfair"
		* Need gentle reassurance
	* Adult-like response
		* Existential fears, uncertainty
		* Honest but fair discussion

| System | 5-10 Year Olds                             |
+--------+--------------------------------------------+
| **A**  | - Nil                                      |
| **B**  | - Nil                                      |
| **C**  | - Nil                                      |
| **D**  | - Tailor discussion to psychological state |



---

## References

1. von Ungern-Sternberg BS, Boda K, Chambers NA, Rebmann C, Johnson C, Sly PD, et al. Risk assessment for respiratory complications in paediatric anaesthesia: a prospective cohort study. The Lancet. 2010 Sep;376(9743):773–83. 
