# Univentricular Pathway


Describes a general operative pathway for congenital cardiac disease that:

* Enables survival and growth
* Occurs in three stages
	* Norwood at day 1-3
	* 
* Ends in a [Fontan Circulation](/management/cvs/fontan.md)
* May be performed for the following:
	* Hypoplastic Left Heart Syndrome
	* Pulmonary Atresia with VSD
	* Tricuspid atresia
	* Ebstein's Anomaly
	* Atrioventricular Septal Defect
	* Double-Inlet Left Ventricle
	* Double-Outlet Right Ventricle


## Norwood Procedure

The Norwood:

* Aims to provide a reliable blood supply to support growth and development
* Occurs at day 1-3 of life  
Sickness at birth is dependent on:
	* Degree of atrial mixing
	* Patency of the ductus arteriosus
	* Qp:Qs ratio

### Preoperative Management

* B
	* Maintain PVR  
	Required to achieve adequate systemic flow and prevent a pulmonary steal. Aim:
		* Normal to high-normal PCO~2~
		* **SpO~2~ 80-85%**  
		May be achieved with hypoxic gas mixtures, if required.
	* ↓ FiO~2~
	* IPPV may be required  
	Due to apnoea from PGE~1~.
* C
	* PGE~1~ infusion  
	Prevents ductus arteriosus from closing.
	* Inotropes  
	Augmentation of ventricular function.


### Surgical Stages

Involves:

* Closure of ductus arteriosus
* Formation of a neo-aorta  
Through joining of the pulmonary artery and the aorta; the Damus-Kay-Stansel procedure.
* Formation of a systemic-pulmonary artery shunt  
Results in supra-normal pulmonary flow. May be:
	* Right modified Blalock-Thomas-Taussig Shunt (RMBTTS)  
	Shunt placed between right subclavian artery and right pulmonary artery.
		* Right because it is on the right side
		* Modified because it uses goretex, rather than a direct side-to-side anastomosis
		* Results in a "pulmonary steal", as systemic blood pressure drives flow into the compliant pulmonary circulation  
		Leads to a fall in MAP and DBP, and ↓ in organ (particularly coronary) flow.
	* Central shunt
	* Ventricular-PA conduit  
	A Sano shunt.
		* No fall in DBP, and thus coronary perfusion is maintained
		* May lead to bleeding from ventricle
* Atrial septectomy  
Formation of a common atria.


## Bi-Directional Cavo-Pulmonary Connection/Shunt (The Glenn Procedure)

The BDCPC/S:

* Aims to begin offloading of the RV
	* Avoiding pulmonary hypertension associated with the supra-normal flow following the Norwood
* Occurs at month 2-6 of life


### Surgical Stages

Involves:

* Connecting SVC to PA
* Removal of the systemic-PA shunt

### Postoperative

* Pulmonary flow is dependent on SVC VR
* Systemic ventricle preload is a function of both:
	* Pulmonary flow
	* IVC VR


## Fontan

*Management of the Fontan circulation is covered [elsewhere](/management/cvs/fontan.md)*.

The Fontan procedure:

* Is the last step in the single-ventricle pathway
* Aims to offload the heart and establish a separate pulmonary circulation

### Surgical Stages

Involves creation of:

* An IVC to right PA conduit
* +/- A 4mm fenestration  
Allows right-to-left shunting to occur, which:
	* Prevents development of pulmonary hypertension
	* Reduces venous congestion and the associated complications
	* Ensures some ventricular filling is maintained, even if PVR is transiently elevated
	* Leads to post-operative SpO~2~ of ~89%


### Anaesthetic Considerations

For anaesthetising a patient with a Fontan circulation:

* Get SET
	* Is this the right centre/should they be transferred?
	* Do you have the right team?
* B
	* Minimise PVR  
	TPG must be kept low to maintain CO. Aim:
		* Spontaneous ventilation if possible
		* Normoxia
		* Normocarbia
		* If IPPV required:
			* Minimal PEEP
			* Minimise Pip
			* Long expiratory time
* C
	* Assess cardiac function
		* Is there a fenestration?  
		Reduces hypotension from transiently ↑ TPG/PAP, at the cost of shunt.
		* Exercise tolerance
		* Cardiac complications:
			* Dysrhythmias
			* Ventricular dysfunction
			* Raised PAPs
	* Strongly consider arterial line
	* Consider central line
	* Optimise preload  
	Will drop on induction and is critical to maintain VR and CO; ensure adequately resuscitated and well-filled before induction.
	* Minimise Common Atrial Pressure
		* Avoid dysrhythmia  
		Particularly AF.
		* Normal A-V valve function
		* Optimise ventricular function
	* Avoid ↑ afterload
* E
	* Elevate head and feet  
	Optimise venous return
* G
	* Assess other complications:
		* Ascites
		* Protein losing enteropathies  
		Raised venous pressures reduce lymphatic flow and nutrient absorption.
* H
	* Bleeding risk  
	↑ due to raised venous pressures.


---

## References
