# Acute Kidney Injury 

A spectrum of acute glomerular dysfunction characterised by a ↓ UO and ↑ serum creatinine and urea, and defined by the KDIGO classification as an:

:::column-margin
Diagnosis is more complex in the critically ill due to lack of steady-state conditions, variable rate of creatinine production, and variable rate of elimination.
:::

* **↑ Serum Creatinine**\
	* Best overall index of renal function
		* Independently associated with ↑ mortality\
		Larger rises in creatinine are correlated with poorer survival
		* Absolute rises are less accurate in patients with pre-existing renal impairment as an absolute change in GFR will cause a variable change in creatinine
	* Only rises once ~50% of GFR is lost\
	This can become apparent where a patient with normal premorbid renal function develops an AKI after a relatively trivial physiological insult.
	* Lags with respect to "true" GFR, so does not reflect dynamic changes
* **↓ Urine Output**\
UO is a reasonably sensitive but not specific index of kidney function.
	* A significant ↓ in GFR immediately results in ↓ UO, however serum creatinine will not rise for several hours
	* Volume depletion and hypotension stimulate vasopressin secretion and water reabsorption
	* Polyuria may occur when tubular function is impaired, even if hypovolaemic\
	Impaired concentration of urine in the loop causes **non-oliguric renal failure**.
	* Ideal body weight should be used instead of actual body weight in the obese population for UO calculation

:::column-margin
On **Acute tubular necrosis**:

* The term ATN is often used to describe the intrinsic renal injury that occurs following a persistent pre-renal insult
	* This is probably not correct, as the histology of tubular necrosis is not confirmed in this population
	* The classical pattern is one of an:
		* Oliguric renal failure of 1-2 weeks
		* Non-oliguric renal failure of 10-14 days\
		Likely due to restoration of glomerular filtration without recovery of tubular concentration.
* In animal models, necrosis of the PCT (and occasionally DCT) occurs when blood flow is no longer adequate to maintain tubular perfusion and is believed to be a form of ischaemia-reperfusion injury
* 'True' ATN may occur following arterial occlusion (such as AAA rupture or dissection)
:::


: The KDIGO Classification

+-------+---------------------------------------+-------------------------------+
| Stage | Creatinine                            | Urine Output                  |
+=======+=======================================+===============================+
| 1     | - 1.5-1.9× baseline in 7 days         | - ⩽0.5ml/kg/hr for 6-12 hours |
|       | - ⩾26.5 μmol/L ↑ in Cr in 48 hours    |                               |
+-------+---------------------------------------+-------------------------------+
| 2     | - 2-2.9× baseline                     | - ⩽0.5ml/kg/hr for ⩾12 hours  |
+-------+---------------------------------------+-------------------------------+
| 3     | - 3× baseline                         | - ⩽0.3ml/kg/hr for ⩾24 hours  |
|       | - Cr ⩾354μmol/L                       | - Anuria > 12 hours           |
|       | - Initiation of RRT                   |                               |
|       | - eGFR ⩽35ml/min/1.73m^2^ in children |                               |
+-------+---------------------------------------+-------------------------------+

:::column-margin
Noting that KDIGO is an imperfect definition: not all AKI will fit into this criteria, and not all cases fitting the criteria are true AKI.
:::

## Epidemiology and Risk Factors

Risk factors:

* Occurs in:
	* 7% of hospital inpatients
	* Up to 25% of ICU patients
* Significant morbidity and mortality
	* Mortality of patients requiring inpatient dialysis is 50-75%
* Risk factors
	* Patient factors
		* Age
		* Pre-exiting CKD	
		* Dehydration
		* Female
		* Black race
		* Elderly
	* Disease factors
		* COAD
		* Obesity
		* Sepsis
		* CCF
		* IABP
		* DM
		* Cancer
		* Anaemia
		* Hypertension
		* Vascular disease
		* Critical illness
		* Shock
		* Burns
		* Nephrotoxic drugs
		* Toxins
	* Perioperative
		* Trauma
		* Major surgery
			* Cardiac surgery
				* ↑ With CPB

## Pathophysiology

Pathophysiology varies by aetiology, which are generally classified into:

* Pre-renal\
40-70% of AKI.
* Intra-renal\
10-50% of AKI.
* Post-renal\
10% of AKI in ICU patients, but the most common cause in the general population.

:::column-margin
Most common causes in the critically ill are:

* Sepsis
* Heart failure
* HDx instability
* Hypovolaemia
* Nephrotoxins
:::

### Pre-Renal

Renal dysfunction due to extra-renal factors, resulting in decreased perfusion. Rapid correction of the systemic cause usually results in rapid renal recovery.

Causes can be divided into:

* Hypovolaemia
	* Haemorrhage
	* Vomiting/Diarrhoea
	* Inappropriate diuresis
	* Burns
* Hypotensive/low flow
	* Shock states
	* AAA
	* Renal artery stenosis
	* Hepatorenal syndrome
* Impaired autoregulation
	* NSAIDS
	* ACE-Is/ARBs
* Oedema
	* Cardiac failure
	* Cirrhosis
	* Nephrotic syndrome

### Intra-Renal

Disease of the renal parenchyma, with structural changes visible on biopsy. Causes include:

* Glomerular disease
	* Inflammatory
		* Post-infective GN
		* Henoch-Schonlein Purpura
		* SLE
		* Antineutrophil cytoplasmic antibody-associated GN
		* Antiglomerular basement membrane disease
* Interstitial nephritis
	* Drugs
		* NSAID
		* Aminoglycosides
		* Radiological contrast\
		It is theorised that osmotic stress and direct tubular toxic effects lead to renal tubular injury, and may cause acute tubular necrosis.
			* Typically, acute contrast nephropathy is benign, with creatinine returning to baseline within 10-14 days\
			* There is significant uncertainty as to whether contrast media do cause acute kidney injury\
			*If* this risk is present, it is probably only relevant in patients who have:
				* Impaired renal function
				* Arterial contrast
			* Rehydration and volume correction are effective in preventing a rise in creatinine
	* Infiltrative disease
		* Lymphoma
		* Granulomatous disease
			* Sarcoidosis
			* Tuberculosis
		* Infection
			* Pyelonephritis
* Tubular injury\
Typically due to continuation of pre-renal causes.
	* Ischaemia
	* Toxins
		* Drugs
		* Myoglobin
		* Heavy metals
	* Metabolic
		* Hypercalcaemia
		* Immunoglobulins
	* Crystals
		* Urate
		* Oxalate
* Vascular
	* Vasculitis
	* Cryoglobulinaemia
	* Polyarteritis Nodosa
	* Thrombotic microangiopathy
	* Cholesterol emboli
	* Renal artery/renal vein thrombosis

### Post-renal

Divided into:

* Intraluminal
	* Urinary retention
	* Stone
	* Clot
* Intramural
	* Urethral stricture
	* Prostatic hypertrophy
	* Tumour
* Extramural
	* Malignancy


## Clinical Manifestations


## Diagnostic Approach and DDx

1. Is this acute or chronic?
	* Previous creatinine measurements
	* Chronicity suggested by:
		* Symptom duration
		* Nocturia
		* Anaemia
		* Hyperphosphataemia
		* Hypocalcaemia
2. Is there ↓ renal perfusion?
	* Volume status?
	* Cardiac insufficiency?
	* Renal vasoconstriction
3. Is there obstruction?
	* Ultrasound
		* Bladder
		* Renal tract
	* Palpable bladder
4. Is there other evidence or concern for renal parenchymal disease?
	* Rashes
	* Arthralgia
	* Myalgia
	* Haematuria
5. Is there vascular occlusion?

## Investigations

**Laboratory**:

* Blood
	* Creatinine
		* Normal daily variation in SCr is ~10%
		* Measurements are affected by:
			* Volume state (as it is measured as a concentration)
			* 
		* Ideally, results from the same lab should be used
	* Urea
	* Autoimmune profile\
	ANCA, ANA, C3, C4. Perform in patients with:
		* Pulmonary-Renal Syndrome
		* Haemoptysis
		* Haemolysis
		* Thrombocytopaenia
* Urine
	* Sodium and osmolality
		* Healthy kidneys respond to hypovolaemia/hypoperfusion by ↑ urinary osmolarity and ↓ sodium, urea, and water excretion\
		This response may be impaired in disease, as well as due to drugs and other therapies (such as CPB).
		* Low urine osmolality may indicate impaired tubular function
		* High osmolality and low sodium with uraemia and oliguria suggests intact tubular function\
	* Renal tubular cells\
	Tubular disease.
	* Red cell casts/dysmorphic red cells\
	Indicate glomerular disease.
	* Oxalate crystals\
	Ethylene glycol poisoning.
	* Urate crystals\
	Tumour lysis syndrome.
	* Urinary light chains


**Imaging**:

* Urinary tract ultrasound\
For diagnosis of obstruction.


**Other**:

* Intrabdominal pressure measurement\
	* \>20mmHg suggests abdominal compartment syndrome contributing to AKI
* Renal biopsy


## Management

### Preventative

:::priority
* Maintain **renal perfusion**
* Avoid **nephrotoxins**
* Remove **obstruction**
:::

**Specific therapy**:

:::column-margin
CRRT is covered in detail under @sec-crrt.
:::

* Pharmacological
	* **Avoid nephrotoxins**
		* Avoid aminoglycosides unless no other alternatives are available\
		If used:
			* Administer as single daily dose
			* Monitor levels when used for >48 hours
		* Use lipid formulations of amphotericin B
		* Use azoles or echinocandins as alternatives to amphotericin B if able
		* IV contrast
* Procedural
	* **RRT**
		* Indicated for life-threatening:
			* Volume overload
			* Electrolyte disturbance
			* Acidosis
			* Uraemia\
			Typically initiated for uraemia prior to onset of uraemic complications.
				* Uraemic pericarditis
				* Encephalopathy
				* Coagulopathy
			* Toxins
		* Consider:
			* Later initiation in single-organ failure as:
				* We are poor at predicting renal recovery
				* There is potential harm from unnecessary early RRT
			* Earlier initiation in multi-organ failure
				* Optimise volume and physiological state
		* Aimed at:
			* Maintaining electrolyte, solute, and acid-base homeostasis
			* Preventing further renal insult
			* Permitting renal recover
			* Facilitate delivery of other supportive measures
		* Ceased when either:
			* Intrinsic kidney function has recovered\
			Mean duration ~12 days.
			* Not consistent with goals of care

:::column-margin
Not that RRT is indicated by creatinine and urea values alone.
:::

:::column-margin
There is no mortality difference between IHD and CRRT, but CRRT is less likely to cause hypotension.
:::

**Supportive care**:

* C
	* Maintain intravascular volume
		* Crystalloid > colloid
	* Maintain renal perfusion pressure\
	Maintain **MAP 65-90mmHg**.
		* Consider higher MAP targets in patients with hypertension
		* Vasopressors and fluids
* G
	* Avoid hyperglycaemia\
	Use IV insulin to maintain BSL 6-10 mmol/L.
	* Maintain 20-30 kcal/kg/day of energy intake\
	Enteric route if possible.
	* Avoid protein restriction
* H
	* Correct anaemia


### Marginal and Ineffective Therapies

* Loop diuretics\
Reduce volume but do not affect survival or renal recovery.
	* Theoretically reduce oxygen consumption in loop of Henle and therefore lessen ischaemic injury\
	Minimal supportive evidence outweighed by evidence of harm.
	* **Appropriate to treat volume overload in the setting of AKI, but not AKI itself**
	* Ineffective in reducing frequency or duration of RRT
	* ⩾1g/day of frusemide may cause ototoxicity
* Mannitol\
Likely no benefit.
* Dopamine\
↑ UO but does not improve renal recovery. Some evidence of harm (particularly arrhythmias).
* Natriuretic peptides (e.g. ANP) \
No benefit.
* Fenoldopam\
No benefit.
* (rh)IGF-1\
No benefit.
* NAC


## Anaesthetic Considerations

Major perioperative considerations:

* Meticulous fluid management
* Cardiac output and blood pressure control
* Consideration of dynamic changes in renal clearance


## Complications


* Death
	* Perioperative mortality over 50%
* C
	* Volume overload
* F
	* Metabolic acidosis
	* Hyperkalaemia
	* Uraemia
		* Platelet dysfunction
		* Pericarditis
		* Encephalopathy
* I
	* Sepsis


## Key Studies

**Early RRT**:

* AKI is common in ICU patients and a high proportion need CRRT
* Early dialysis may correct the abnormal metabolic and inflammatory milieu before instability occurs, but ↑ risk of procedural complications from an unnecessary intervention
{{< include /trials/elain.qmd >}}
{{< include /trials/akiki.qmd >}}
{{< include /trials/starrtaki.qmd >}}

**Other**:

{{< include /trials/bellomo_dopa.qmd >}}
{{< include /trials/renal.qmd >}}

---

## References

1. Hilton R. [Acute renal failure](https://www.ncbi.nlm.nih.gov/pubmed/17038736). BMJ. 2006 Oct 14;333(7572):786-90.
1. Kidney Disease: Improving Global Outcomes (KDIGO) Acute Kidney Injury Work Group. [KDIGO Clinical Practice Guideline for Acute Kidney Injury](http://kdigo.org/wp-content/uploads/2016/10/KDIGO-2012-AKI-Guideline-English.pdf). Kidney inter., Suppl. 2012; 2: 1–138.
1. The Royal Australian and New Zealand College of Radiologists. [Iodinated Contrast Media Guideline](https://www.ranzcr.com/documents/573-iodinated-contrast-guidelines-2016/file). Sydney: RANZCR; 2016.
1. Ostermann M, Joannidis M. [Acute kidney injury 2016: diagnosis and diagnostic workup](https://ccforum.biomedcentral.com/articles/10.1186/s13054-016-1478-z). Crit Care [Internet]. 2016 Dec 27 [cited 2018 Jan 31];20(1):299.
1. The STARRT-AKI Investigators. [Timing of Initiation of Renal-Replacement Therapy in Acute Kidney Injury](https://www.nejm.org/doi/full/10.1056/NEJMoa2000741). N Engl J Med. 2020;383(3):240-251. doi:10.1056/NEJMoa2000741
1. Bellomo R, Chapman M, Finfer S et al. [Low-dose dopamine in patients with early renal dysfunction: a placebo-controlled randomised trial](https://pubmed.ncbi.nlm.nih.gov/11191541/). The Lancet. 2000;356(9248):2139-2143. doi:10.1016/S0140-6736(00)03495-4
