# Syndrome of Inappropriate ADH

Clinical syndrome defined by a excessive secretion of ADH.

## Epidemiology and Risk Factors

## Pathophysiology

Causes of SIADH can be classified into:

* Primary CNS
	* CVA
	* Haemorrhage
	* Infection
	* Trauma
	* TBI
	* Psychosis
* Respiratory
	* Pneumonia
		* Aspergillus
	* Tuberculosis
	* Asthma
	* Atelectasis
	* Acute respiratory failure
	* Pneumothorax
* Hormonal
	* Hypothyroidism
	* Hypopituitarism
* Malignancy
	* Paraneoplastic syndrome\
	Classically small cell lung carcinoma.
	* Neuroblastoma
* Infective
	* HIV
* Congenital
* Surgery
* Drugs
	* Anti-convulsants
		* Carbamazepine
		* Sodium valproate
	* Anti-depressants
		* SSRIs
		* MAO-Is
		* TCAs
	* Antipsychotics
		* Haloperidol
	* Analgesics
		* Opioids
		* NSAIDs
	* Exogenous ADH
		* Vasopressin
		* DDAVP
		* Oxytocin
	* Other
		* Amiodarone
		* Bromocriptine
		* Ciprofloxacin
		* Interferon-alpha
		* Interferon-gamma
		* MDMA\
		Ecstasy.
* Exercise associated
* Primary polydipsia
* Idiopathic


## Clinical Manifestations

## Diagnostic Approach and DDx

Diagnostic criteria:

* Hypotonic hyponatraemia
* Urine osmolality > plasma osmolality
* Absence of other factors affecting ADH secretion:
	* Hypotension
	* Hypovolaemia
	* Drugs
	* Oedema
* Corrected by water restriction


## Investigations

## Management

:::priority
* Fluid restriction
* Hypertonic saline for severe or recalcitrant cases\
Avoid correction >10mmol/24 hours.
:::

**Specific therapy**:

* Pharmacological
	* Sodium
	* Vasopressin receptor antagonists
	* Fludrocortisone
* Physical
	* Fluid restriction

### Marginal and Ineffective Therapies


---

## References

1. Sahay M, Sahay R. [Hyponatremia: A practical approach](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4192979/). Indian Journal of Endocrinology and Metabolism. 2014;18(6):760-771. doi:10.4103/2230-8210.141320.