# TURP Syndrome

Syndrome of **cardiac** and **neurological toxicity** occurring due to **systemic absorption** of **glycine** which causes:

* Rapid changes in:
	* Osmolality\
	With associated hyponatraemia.
	* Circulating volume
* Direct CNS effects


## Epidemiology and Risk Factors

Prevalence:

* Confusion, nausea, vomiting in ~2% of TURP patients


Primary risk factor is rate and amount of irrigation fluid absorption:

* Volume absorbed is directly proportional to degree of hyponatraemia\
**~10mmol/L** fall **for each 1L of irrigation fluid absorbed**; though this will vary depending on lean body weight.
* Factors influencing rate of absorption:
	* Operating time\
	⩾1 hour.
	* Low venous pressure\
	CVP ⩽10 will permit fluid absorption.
		* Hypovolaemia
		* Hypotension\
	* Extensive bleeding
	* Capsular perforation
	* High irrigation fluid pressure


## Pathophysiology

Occurs due to systemic absorption of hypertonic, non-conductive irrigation fluid in percutaneous procedures using **unipolar** diathermy:

* Use is rarer now that bipolar diathermy more common\
Though large fluid shifts still occur due to absorption of irrigation fluid.
* Procedures include
	* TURP
	* Hysteroscopy

:::column-margin
Fluids used include:

* Glycine 1.5%\
220mOsmol/kg.
* Sorbitol 3%
* Mannitol 5%
:::

Effects due to:

* Osmolality\
Effects mostly due to hypoosmolality, rather than hyponatraemia.
* Circulating volume
* Direct neurological effects of glycine\
Acts as major inhibitory neurotransmitter and potentiates NMDA in CNS.
	* Less common with sorbitol
	* Significantly less common with mannitol


## Clinical Features

Timing:

* Intraoperatively\
Within 15 minutes.
* Post-operatively\
Up to 24 hours.

Presentation:

* Early:
	* Headache
	* Restlessnes
	* Dyspnoea
	* Burning sensation in face and hands
	* Visual disturbance\
	Mainly due to glycine.
* Late/severe:
	* Hypoxia
	* Pulmonary oedema
	* Nausea/vomiting
	* Confusion/convulsions/coma


## Diagnostic Approach and DDx

## Investigations

## Management

:::priority
* **Prevention** is key
* **Abandon operation** if toxicity occurs
* **Correct hyponatraemia**
:::

**Prevention**:

* Avoid use of non-electrolyte fluids\
Use bipolar diathermy.
* Minimise fluid absorption
* Monitor fluid absorption\
Calculate deficit between administered and suctioned fluid.
* Have a (predetermined) threshold at which to abandon surgery
	* At 750ml-1L:\
	Depending on weight and sex.
		* Cease fluid administration
		* Assess mental state
		* Check serum sodium
	* At 1-2L:\
	Depending on weight and sex.
		* Abandon surgery
		* Assess mental state
		* Check serum sodium

**Specific therapy**:

* Pharmacological
	* Volume changes
		* **Cease IV fluid**
		* **Frusemide**\
		Only recommended if APO is present, as it will worsen hyponatraemia.
	* Solute changes
		* **3% NaCl**\
			* 100ml, Q10 minutely, until resolution or 300ml given\
			Each bolus should raise serum sodium by ~2-3mmol/L.
			* Indicated if:
				* Serum sodium is ⩽120mmol/L
				* Serum osmolality is <260mOsm/kg
				* Severe neurological symptoms
					* Transient blindness
					* Persistent nausea/vomiting
					* Severe headaches
					* Severe hypotension
* Procedural
	* **Abandon surgery**


**Supportive care**:

* C
	* Bradycardia\
		* Atropine
		* Adrenaline
* D
	* Seizures\
		* Benzodiazepines
		* Magnesium\
		May be considered if refractory.


### Anaesthetic Considerations

* C
	* Arterial line\
	Recommended if managing as TURP syndrome.
	* Consider CVC


## Complications

* SIADH occurs in most patients, and impairs correction of hyponatraemia


## Prognosis

Associated with significant harm:

* Morbidity ~20%
* Mortality ~1%


---

## References

1. O’Donnell, Aidan M., and Irwin T.H. Foo. ‘Anaesthesia for Transurethral Resection of the Prostate’. Continuing Education in Anaesthesia Critical Care & Pain 9, no. 3 (June 2009): 92–96. https://doi.org/10.1093/bjaceaccp/mkp012.
2. Hahn RG. Fluid absorption in endoscopic surgery. British Journal of Anaesthesia. 2006 Jan 1;96(1):8–20. 
3. Istre O, Bjoennes J, Naess R, Hornbaek K, Forman A. Postoperative cerebral oedema after transcervical endometrial resection and uterine irrigation with 1.5% glycine. Lancet. 1994 Oct 29;344(8931):1187–9. 
4. American College of Obstetricians and Gynecologists. ACOG technology assessment in obstetrics and gynecology, number 4, August 2005: hysteroscopy. Obstet Gynecol. 2005 Aug;106(2):439-42.