# Mediastinal Mass


>Airway: ETT; aim distal to obstruction <br>
>Access: Multiple large IV, consider lower limb if SVC involvement<br>
>Pain: Variable<br>
>Position: Semi-erect, supine, or prone *in extremis*<br>
>Time: Variable<br>
>Blood loss: Risk of major haemorrhage with mediastinoscopy<br>
>Special: Complex induction, and management of airway, respiration, and circulation <br>

Mediastinal masses include aneurysms, tumours, and cysts that:

* Occur in the anterior, posterior, middle, or superior mediastinum\
Anterior masses are most likely to cause severe cardiorespiratory problems due to:
	* Proximity to vascular/airway structures
	* Exacerbation of compression in the supine position
* Cause significant physiological upset via compression of:
	* Tracheobronchial tree
	* Main PA
	* SVC

## Considerations

> * Degree of compression may worsen as the mass shifts, which may occur with:
>	* Induction of anaesthesia
>	* Loss of spontaneous ventilation
>	* Muscle relaxation
>	* Supine positioning
> **Life-threatening complications** may occur in **absence of symptoms** in **children**


Anaesthetic considerations:

* Team
	* Surgeon available\
		* With rigid bronchoscope
		* To perform emergent sternotomy and relieve compression of mass.
* A
	* **Mass effect on airway**\
	* Airway device(s)\
	**Aim to intubate distal to obstruction**, which may be endobronchial.
		* Long ETT
		* Reinforced ETT
		* MLT
		* Jet ventilation
		* LMA\
		Permit spontaneous ventilation and bronchoscopy.
* B
	* **Mass effect on lungs**\
		* Reduced lung volume
		* Bronchial muscle relaxation\
		Occurs under GA, and ↑ airway compressibility.
	* Ventilation strategy
		* **Maintenance of spontaneous ventilation**\
		Desirable to minimise adverse cardiac effects.
		* Positive pressure ventilation\
		Ideally commenced gradually, with progressive taking-over of spontaneous ventilation.
* C
	* **Mass effect on heart and great vessels**\
	Evaluate:
		* Size
		* Location\
		Relation to vascular tree/airway.
		* Compression
			* SVC obstruction\
				* ↑ venous pressures and bleeding
				* IV access preferentially in lower limbs
			* PA
				* RV dysfunction
				* Cardiac arrest
	* Invasive pressure monitoring
* D
	* Anaesthetic technique\
	See below.
* E
	* **Positioning**
		* Induction may have to occur in semi-erect or sitting position
		* Post-induction position may need to be changed; consider:
			* Prone
			* Lateral
			* Semi-erect
	* Avoid muscle relaxation\
	To maintain spontaneous ventilation.

## Preparation

> * Presence of symptoms indicates elevated risk
> * **Especially concerning** if **worse when supine**

Evaluate patient:

* Clinical manifestations:
	* Airway compression
		* Dyspnoea
		* Stridor
		* Wheeze
		* ↓ breath sounds
	* SVC syndrome
		* Dyspnoea
		* Headache
		* Visual disturbance
		* Altered mentation
		* Distended neck veins
	* Pericardial effusion
* Review investigations:
	* CT chest\
	Most useful scan to evaluate size, location, and severity of compression.
	* Flow-volume loops\
	May demonstrate intrathoracic obstruction, but are unreliable as a diagnostic test.


Prepare:

* Standard ANZCA monitoring
* Multiple IVs\
Consider in lower limb if SVC is involved.
* Arterial line\
Either arterial line or pulse oximeter in right arm for mediastinoscopy, to identify intraoperative compression of the innominate artery.
* NIBP\
On left arm if arterial line is in right side, to monitor systemic perfusion pressures.




## Induction

> * Asymptomatic patients can develop life-threatening obstruction at induction and during maintenance

Anaesthetic technique:

* Depends on pre-operative risk assessment\
High risk features include:
	* Orthopnoea
	* Cough when supine
	* Syncope
	* SVC syndrome
	* Pericardial effusion
	* Tracheal compression <50% of CSA
* For **low-risk** patients
	* Standard IV induction +/- muscle relaxation appropriate
* For **intermediate-risk** patients\
Maintain spontaneous ventilation and avoid muscle relaxation:
	* Semi-erect patient
	* Induction\
	May be:
		* IV induction\
		Small boluses of propofol/ketamine, or dexmedetomidine.
		* Inhalational
			* May precipitate airway obstruction
			* Difficult to abandon
			* Partial obstruction may lead to very negative intrathoracic pressures
	* Once GA instituted:
		* Stepwise ↑ in support as tolerated and required:
			* Intubation\
			* Lay supine
			* Transition to IPPV
			* Muscle relaxation
	* **If failure at any stage**:
		* **Revert** to previous stage
		* Intubate distal to obstruction over FOB
		* Rigid bronchoscopy
		* Change position\
			* Semi-erect
			* Prone
		* If the above fail:
			* CBP/ECMO
			* Emergency thoracotomy
* For **high-risk** patients\
	* Local anaesthetic is preferable in every instance
	* Sedation should be minimised\
	Risk of:
		* Respiratory depression
		* Upper airway obstruction
	* Consider pre-op treatment
	* Consider CPB or ECMO pre-operatively, including awake bypass
		* Unlikely to succeed as a rescue technique; should be established semi-electively
		* Consider when ventilation is unlikely to be successful post-induction, i.e. compression of:
			* Distal 1/3^rd^ of trachea
			* Mainstem bronchi
			* Carina
	* Consider AFOI with intubation distal to obstruction
		* Safest
		* Allows assessment of site and degree of airway compression
		* Permits intubation distal to site of obstruction


## Intraoperative

### Surgical Stages

## Emergence

## Postoperative


---

## References

1. Chow L. Anesthesia for Patients with Mediastinal Masses. In: Slinger P, editor. Principles and Practice of Anesthesia for Thoracic Surgery [Internet]. Cham: Springer International Publishing; 2019 [cited 2019 Nov 30]. p. 251–63. Available from: http://link.springer.com/10.1007/978-3-030-00859-8_14
