# Staphylococcus Aureus


## Epidemiology and Risk Factors

## Pathophysiology

### Aetiology

Common sites of infection include:

* B
	* HAP
* C
	* Infective endocarditis
	* Invasive vascular devices
		* CLABSI
		* Pacemaker
* D
	* Osteomyelitis
	* Discitis
	* Epidural abscess
* E
	* Skin
	* Soft tissue
	* Joint prostheses


## Clinical Manifestations

## Diagnostic Approach and DDx

## Investigations

Bedside:

* TTE\
For vegetations. Does not exclude IE, but can rule-in.
* TOE\
Should be performed if TTE is negative.

Laboratory:

Imaging:

Other:

## Management

**Resuscitation**:\

ABC approach. Comment on team coordination and clinical priorities.
**Specific therapy**:

* Pharmacological
	* MSSA\
		* β-lactams\
		Desensitisation for β-lactam allergic patients should be performed.
			* Flucloxacillin
			* Cefazolin
		* Clindamycin
		* Moxifloxacin
		* Vancomycin\
		Failure rates ~4x that of β-lactams. 
	* MRSA
		* Vancomycin
* Procedural
* Physical


**Supportive care**:

**Disposition**:

**Preventative**:


### Marginal and Ineffective Therapies

## Anaesthetic Considerations

## Complications

## Prognosis

Mortality varies on site of origin, but can reach 50% with:

* Lung
* CLABSI
* Infective endocarditis

## Key Studies


---

## References
