# Brain Abscess



## Epidemiology and Risk Factors

## Pathophysiology

Infective spread from:

* Bone
* Dura
* Bacteraemia

### Aetiology

Oragnisms include:

* Common
	* *S. Aureus*
	* *Streptococcus* spp.
	* *Bacteroides fragilis*
	* Assorted Gram negatives


## Clinical Manifestations

Feature include:

* ↑ ICP
	* Obtundation
* Mass lesion
	* Headache
	* Vomiting
	* Obtundation
	* Seizures

:::column-margin
Notably, **meningism** is often **absent**.
:::


## Diagnostic Approach and DDx

## Investigations

**Bedside**:

**Laboratory**:

**Imaging**:

**Other**:

## Management

**Resuscitation**:\

ABC approach. Comment on team coordination and clinical priorities.
**Specific therapy**:

* Pharmacological
* Procedural
* Physical

**Supportive care**:

**Disposition**:

### Marginal and Ineffective Therapies

## Anaesthetic Considerations

## Complications

## Prognosis

## Key Studies


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.
