# Candidiasis {#sec-candida}

Candidiasis is the most common invasive fungal infection worldwide, and a significant cause of mortality in the ICU patient.

:::column-margin
Candidal infections also include the more pedestrian mucous membrane infections of the systemically well, which are caused by local overgrowth of yeast and respond well to topical treatment.\
\
These are not covered here.
:::


## Epidemiology and Risk Factors

Risk factors:

* ICU admission
* Immunocompromise
	* Transplant
	* Haematological malignancy
	* Diabetes
* For non-*Albicans*
	* **TPN**
	* Central access
	* Antimicrobial exposure:
		* Broad spectrum antibiotics
		* Fluconazole
	* Malignancy
	* Renal failure

## Pathophysiology

Candida is:

* A genus of yeasts\
Over 100 different species, ~20 of which are pathogens.
* Part of the normal skin and gut flora



### Aetiology

Causes have been classically divided on epidemiological and fluconazole-sensitive grounds into:

:::column-margin
The ongoing utility of this classification is questionable as the non-Albicans infections have become increasingly common, and *albicans* has become increasingly resistant to fluconazole.
::: 

* *C. Albicans*\
~50% of all infections; less common if fluconazole prophylaxis has been used.
* Non-Albicans infections\
All the rest:
	* ***C. Auris***\
	Multi-drug resistant form, though still generally sensitive to echinocandins.
	* *C. glabrata*\
	~25% of infections, ↑ resistant to azoles.
	* *C. krusei*\
	↑ Resistant to azoles.
	* *C. parapsilosis*
	* *C. dubliniensis*
	* *C. tropicalis*


## Clinical Manifestations

Features are non-specific and include:

* Fever\
Generally unreliable, though may be high with hepatosplenic abscesses.
* Sepsis\
Non-responsive to other antimicrobial therapy.

## Diagnostic Approach and DDx

Differentiating invasive candidiasis from culture of a normal commensal requires any of:

* Culture from a sterile site
	* Blood\
	⩾2 non-contiguous sites.
* Culture from wound or burn site
* Cultured species is non-commensal

Supportive features include:

* Radiographic fungal lesions\
May be suppressed during **neutropaenia**.

## Investigations

Bedside:

Laboratory:

* Blood
	* Blood cultures
* Sputum
	* Bronchoalveolar lavage
* Other fluid culture

Imaging:

Other:

## Management

**Specific therapy**:

* Pharmacological
	* **Antifungal**
		* **Echinocandin** as initial therapy
		* Fluconazole as step-down therapy\
		If sensitivity is proven.
	* ↓ Immunosuppressants
* Procedural
	* Source control
	* Remove lines and devices


**Supportive care**:

* G
	* Adequate nutrition


### Marginal and Ineffective Therapies

## Anaesthetic Considerations

## Complications

Disseminated Candida causes a large number of organ-specific complications:

* B
	* Pulmonary candidiasis\
	Cavitating lung lesions.
* C
	* Endocarditis
		* Very high mortality
* D
	* Endophthalmitis\
	3-15 days following infection.
* E
	* Candidal joint infections
	* Skin lesions
	* Muscle abscesses
* G
	* Hepatic abscess
* H
	* Splenic abscess

## Prognosis

Mortality in the ICU patient is up to 50%.
* Late diagnosis
* 

## Key Studies


---

## References

1. Chow JK, Golan Y, Ruthazer R, Karchmer AW, Carmeli Y, Lichtenberg D, et al. [Factors Associated with Candidemia Caused by Non-albicans Candida Species Versus Candida albicans in the Intensive Care Unit. Clinical Infectious Diseases](https://academic.oup.com/cid/article/46/8/1206/361259?login=false). 2008 Apr 15;46(8):1206–13.
2. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.

