# Community Acquired Pneumonia

Infection of pulmonary parenchyma in a patient who was not hospitalised prior to the onset of symptoms, with both:

:::column-margin
Systemic symptoms are much less common in the elderly and may be absent.\
\
Non-respiratory symptoms may also be present.
:::

* Symptoms of acute infection
* Evidence of pulmonary infiltrate
    * Radiographic
    * Clinical\
    Crepitations, etc.


## Epidemiology and Risk Factors

CAP has an annual incidence of up to 4% of the population:

* 50% require hospital admission
    * Mortality 10% among the hospitalised group
* 10% require ICU admission


## Pathophysiology

### Aetiology

There are vast numbers of potentially causative organisms, however the most common in patients requiring ICU admission are:

* Viral\
25%, most commonly:
    * RSV
    * Influenza
* ***S. Pneumoniae***
* *H. Influenzae*
* *Legionella* spp.
* *Enterobacteriaceae* spp.
* *S. aureus*
* *Pseudomonas* spp.


Factors favouring infection with certain organisms include:

* Exposures
    * Animal
        * Animal exposures
        * Birds and excreta
        * Parturient pets or farm animals
        * Insect bites
        * Mice and excreta
        * Bats and excreta
    * Geographical factors
        * TB prevalence
        * Locally endemic organisms
* Patient factors
    * IVDU
    * Alcoholism 
    * Respiratory disease
        * COPD
        * CF
        * Bronchiectasis
    * Other disease
        * Diabetes
        * Sickle cell
        * Poor dental hygeine
    * Immunosuppression\
* Disease factors
    * Sputum smell
    * Lung abscesses
    * Empyema


## Clinical Manifestations

May be either:

* Systemic
    * Fever
    * Sweats
    * Rigors
* Respiratory
    * Productive cough
    * Pleural rub
    * Inspiratory crepitations


## Assessment

**History**:

* Prognostic factors
    * Cardiopulmonary
        * Smoking
        * COPD
        * CCF
        * Pulmonary hypertension
        * Exercise tolerance
    * Immune function
        * Immunocompromise
        * Vaccinations
    * Malignancy
        * Chemotherapy
    * Other organ failures
* Aetiology
    * Country of origin
    * Travel history
    * TB exposure
    * Recent hospital admission
    * Recent antibiotic use
    * Activities
        * Gardening
        * Bushwalking
        * Animal exposure
            * Birds
            * Pets

**Exam**:


## Investigations

**Laboratory**:

* **Blood**:
    * FBE
    * UEC
    * LFT
    * Blood cultures (×2-3)
    * CRP\
        * Prognostic
        * ↑ CRP identifies a subgroup that demonstrate ↑ benefit from steroids
    * HIV status
* **Sputum**:
    * Tests include:
        * Gram stain
        * Culture\
        Neither sensitive nor specific; more accurate results seen with:
            * Induced sputum
            * Deep tracheal suctioning
            * BAL
        * *Mycoplasma pneumoniae* PCR
        * *Chlamydophila* PCR
        * Influenza PCR
        * *Legionella* PCR
        * COVID PCR
    * Collection is ideally:
        * From a **deep cough**\
        To minimise contamination from upper respiratory tract commensals.
        * Prior to antibiotics
    * Rapid transport to laboratory ↑ chance of detecting fastidious organisms
    * Causative organism is likely if:
        * Dominant on gram stain
        * Heavy growth on culture
* **Urine**:
    * Legionella antigen\
        * Highly specific but not sensitive for infection\
        Only detects *Legionella pneumophilia*, and not other pathogenic strains.
    * Pneumococcal antigen\
        * Highly specific and moderately sensitive
        * Unaffected by antibiotic therapy
        * Level correlates with severity
        * May have a role in narrowing spectrum of treatment to penicillin alone

:::column-margin
Anaerobic culture cannot be performed on sputum due to contamination from other upper respiratory organisms.
:::

:::column-margin
Interpretation of sputum cultures is fraught due to the amount of contamination with oropharyngeal flora. Tracheal aspirate or BAL is preferable.
:::

**Imaging**:

* CXR\
Radiographic infiltrates may be absent in up to 25%.
* CT\
More sensitive than CXR.
* Lung ultrasound


## Diagnostic Approach and DDx

Several tools exist to determine severity:

* **CURB-65**\
Good for identifying low-mortality patients, more useful in ED and GP practices.
    * Consists of:
        * **C**onfusion
        * **U**rea >7mmol/L
        * **R**espiratory rate ⩾30
        * S**B**P <90mmHg or DBP <60mmHg
        * Age ⩾**65**
    * Interpretation:\
    Mortality increases with each additional point.
        * 0-1: Low risk: Consider home treatment
        * 2: Intermediate risk: Closely supervised outpatient treatment +/- hospitalisation
        * \>3: High risk: Hospitalise +/- ICU.
* **SMART-COP**\
Better at determining disposition, including need for ICU care.
    * ⩾4 has 1/3 chance of requiring vasoactive or respiratory support
    * Consists of:
        * SBP <90
        * Multilobar infiltrate
        * Albumin <35g/L
        * RR:
            * \>30 if age >50
            * \>25 if age >25
        * Tachycardia >125
        * Confusion
        * Oxygen saturation <93%
        * pH <7.35

:::column-margin
Other scores include the Pneumonia Severity Index, which is similar to CURB65.
:::


## Management

:::priority
* Standard sepsis management\
Covered under @sec-sepsis_mx.
* Respiratory support
* Early antimicrobials
:::

**Resuscitation**:

* A
    * Intubation\
    For respiratory failure.
* B
    * High-flow oxygen
    * NIV
        * Beneficial if there is pneumonia superimposed on another cause of respiratory failure that is manageable with NIV (e.g. APO)
        * Unhelpful in isolated pneumonia due to ↓ cough efficacy
    * Mechanical ventilation\
    If requiring intubation.


**Specific therapy**:

* Pharmacological
    * **Antimicrobial therapy**
        * Non-tropical
            * Mild:\
            5-7 days of:
                * Amoxicillin 1g PO TDS
                * Clarithromycin 250mg PO BD
            * Moderate:\
            7-10 days of dual therapy, either:
                * Benzylpenicillin 1.2g IV QID and doxycycline 100mg PO BD
                * Ceftriaxone 1g IV daily and doxycycline 100mg PO BD
            * Severe:\
            7-10 days of dual therapy:
                * Ceftriaxone 1g IV daily and azithromycin 500mg IV daily
                * Benzylpenicillin 1.2g IV Q4H and gentamicin
        * Tropical\
        To cover *Burkholderia pseudomallei* and *Acinetobacter baumannii*:
            * Meropenem 1g IV TDS and azithromycin 500mg IV daily
    * **Hydrocortisone**
        * Probable mortality benefit
        * Suggest 200mg/day for 4-7 days, followed by 3-7 days of weaning
        * Unless contraindicated
            * Chronic infection
            * Immunocompromised
            * Poorly controlled diabetes
            * Pregnancy
* Procedural
    * Bronchoscopy
        * Diagnostic sampling
        * For segmental or lobar collapse
* Physical

:::column-margin
Antimicrobial therapy is often unit or region-specific based on local flora and resistance patterns.
:::

:::column-margin
Failure of treatment response is usually due to a resistance Gram *positive*, e.g. *S. pneumoniae*, and so broadening Gram negative cover from ceftriaxone to tazocin is not helpful.
:::

:::column-margin
Up to 40% of patients have a polymicrobial infection, so narrowing the spectrum of cover following identification of an organism may result in adequate treatment.
:::

:::column-margin
A reasonable approach to hydrocortisone therapy, including weaning, is included in the summary of the CAPE COD trial; see Key Studies.
:::


**Supportive care**:

* B
    * Supplemental oxygen
    * Chest physiotherapy
        * Sitting position
        * Bubble PEEP
        * Encouraging coughing


**Disposition**:

* ICU or HDU for severe disease


### Marginal and Ineffective Therapies


## Complications

{{< include /includes/pneumonia_complications.qmd >}}

## Prognosis

Time until improvement varies:

* Average ~3 days
* 7 days in the:
    * Elderly
    * Bacteraemic
* 2.5 days in young patients with pneumococcal pneumonia


Poor prognostic signs follow logically:

:::column-margin
{{< include /includes/pf.qmd >}}
:::

* Severity of respiratory failure
    * Invasive mechanical ventilation
    * RR >30
    * P/F <250
* Severity of sepsis
    * Septic shock
    * Leukopenia
    * Thrombocytopenia
    * Hypothermia



## Key Studies

**Steroids**:

* LRTI alters alveolar membrane permeability
    * Local inflammatory response
    * Systemic inflammatory response
* Immunomodulation potentially therapeutic
* Ceftriaxone ↑ inflammation in *S. pneumoniae* (pneumonococcus) infection
* CAP is a heterogenous disease with a variety of different causative organisms and degrees of severity
{{< include /trials/cape_cod.qmd >}}


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.
2. Dequin PF, Meziani F, Quenot JP, et al. [Hydrocortisone in Severe Community-Acquired Pneumonia](https://www.nejm.org/doi/10.1056/NEJMoa2215145). N Engl J Med. Published online March 21, 2023:NEJMoa2215145.
