# Hospital/Ventilator Acquired Pneumonia {#sec-hap}

Pneumonia (infection with chest infiltrate) occurring **48 hours** after:

* Hospital admission (HAP)
* Intubation (VAP)

:::column-margin
Clinical signs of respiratory infection without CXR infiltrates are suggestive of tracheobronchitis.
:::

:::column-margin
VAP is ventilator-*associated*, i.e. there is no requirement to demonstrate causality.
:::

## Epidemiology and Risk Factors

HAP:

* Occurs in 0.5-5% of inpatients


VAP:

* 8-30% of mechanically ventilated patients
    * ~3%/day over first 5 days, with a decline thereafter
* 25-50% mortality
    * Earlier infections are typically less-resistant and therefore more treatable than late-developing VAP

Risk factors:

* Immunocompromised
    * Critically unwell
        * In ICU
    * Diabetes
    * Advanced age
* Microaspiration
    * Intubated
    * ↓ Conscious state
    * NGT in situ
* Pathology
    * Chronic lung disease
    * Receiving antibiotics
* Procedural
    * Post-operative
    * Bronchoscopy
    * Thoracic surgery
    * Abdominal surgery
* Environmental
    * Local biogram
    * Regular ventilator tubing changes


## Pathophysiology

Proposed mechanisms include:

* Microaspiration of upper respiratory tract colonisers
* Local spread
* Haematogenous spread


### Aetiology

Broadly, three classes of infection can occur:

* Most **common**\
Aerobic gram negative bacilli:
    * *Klebsiella* spp.
    * *E. coli*
    * *Pseudomonas* spp.
* **Early-onset**\
VAP within **5 days** is more likely to include a wider array of community pathogens: 
    * MRSA
    * *S. pneumoniae*
    * *H. influenzae*
* **Late-onset**\
After 5 days, exogenous MRO may be seen:
    * MRSA
    * *P. aeruginosa*
    * *Acinetobacter baumannii*
    * *S. maltophilia*


## Clinical Manifestations

## Diagnostic Approach and DDx

## Investigations

Blood:

* FBE\
WCC may ↑ or ↓.
* Procalcitonin\
May have a role in timing deescalation of antibiotics.
* Blood cultures

Sputum:

* *Deep* respiratory samples are required to avoid culturing respiratory tract commensal organisms\
More complex in the intubated patient; options include:
    * Tracheal aspirate\
    Identify potentially causative organisms but is not quantitative.
    * Bronchial washings
    * Bronchoalveolar lavage


Radiology:

* CXR
    * Infiltrates required for diagnosis is many guidelines
    * Appearance usually worsens in initial period, even with institution of appropriate antibiotics\
    Features of concern are:
        * Cavitation
        * Pleural effusion
    * Radiographic improvement lags behind clinical response

## Management

:::priority
* Standard sepsis management\
Covered under @sec-sepsis_mx.
* Respiratory support
* Early antimicrobials
:::

**Resuscitation**:

* A
    * Intubation may be required
* B
    * Supplemental oxygen
* C
    * Haemodynamic support if concurrent sepsis 


**Specific therapy**:

:::column-margin
Risk factors for MDR include:

* Disease
    * Immunosuppression
    * Bronchiectasis
    * Septic shock
    * ARDS
* Treatment
    * Prior IV ABx in previous 90 days
    * Hospitalisation >5 days
    * RRT
* Environmental
    * High local MDR burden 
:::

* Pharmacological
    * Antimicrobial therapy\
        * **7 day course** recommended to reduce subsequent MDR pneumonias.
        * 2-3 days until clinical response seen is usual
        * If **failing to respond**, consider:
            * Wrong bug\
            Repeat cultures.
            * Wrong drug\
            Ensure sensitivity of organism to the antibiotic beingused.
            * Wrong dose\
            Appropriate for patient weight.
            * Sequestration\
            Abscess cavity or similar
            * Patient factors
                * Immunosuppression
                * Frailty
        * No MDR risk factors\
        Consider:
            * Tazocin 4.5g Q6-8H
            * Cefepime 2g Q8H
            * Meropenem 1g Q8H
        * MDR risk factors\
        Consider one of each of:
            * Antipseudomonal broad spectrum agent\
            As above.
            * Additional gram negative cover\
            ↓ Risk that pathogen is resistant to the primary agent.
                * Aminoglycoside 15-20mg Q24H
                * Ciprofloxacin 400mg Q8H
                * Levofloxacin 750mg Q24H
            * MRSA cover:
                * Linezolid 600mg Q12H\
                Preferable due to better pulmonary penetration.
                * Vancomycin
    * Nebulised antibiotics\
    Appropriate in limited circumstances, namely all of:
        * VAP
        * Multi-resistant Gram negative\
        Sensitive only to:
            * Aminoglycosides
            * Colistin

:::column-margin
Nebulisation of antibiotics is:

* Pharmacologically justified by:
    * Achieving ↑ drug concentration at site of infection
    * Most antibiotics have poor lung penetration
    * ↓ Systemic dose and therefore toxicity
* Limited by:
    * Uncertain dose delivered
    * Binding of drug to circuit filter
    * Complications of excipients
    * Lack of strong evidence
* Recommended only for:
    * Colistin
:::


**Prevention**:

* A
    * Nurse 30° head up to ↓ risk of microaspiration
    * Oral care Q4H with chlorhexidine mouthwash BD
    * Use cuff-pressures
    * Use subglottic suctioning
    * Use closed suction circuits
    * Avoid non-essential suctioning
    * Intubate orally (rather than nasally)
    * Minimise changes of ventilation equipment
        * Suction catheters
        * Humidifiers
        * Circuit\
        Weekly intervals.
* B
    * Minimise duration of mechanical ventilation
* E
    * Early mobilisation
* G
    * SDD
    * Post-pyloric feeding
    * Avoid NG tubes\
    OG tubes are preferable.


### Marginal and Ineffective Therapies


## Complications

{{< include /includes/pneumonia_complications.qmd >}}

## Prognosis

* Average ↑ hospital LoS by ~13 days

## Key Studies


---

## References