# Necrotising Fasciitis 


Necrotising fasciitis is an aggressive, life-threatening infection characterised by:

* Rapidly progressing necrosis of subcutaneous tissue and fascia  
Relative sparing of underlying muscle.
	* Also known as Fournier's Gangrene when involving the perineum
* Systemic toxicity with associated multi-organ failure and high mortality  
In absence of this, it may be difficult to differentiate from a severe necrotising abscess or other necrotising soft tissue infection.
* Two subtypes
	* Polymicrobial necrotising fasciitis (Type 1)
	* Group A Strep necrotising fasciitis (Type 2)


## Epidemiology and Risk Factors

Predisposing factors for necrotising soft tissue infection include:

* Previous trauma
* Previous surgery
* Pre-existing infection
* Obesity
* Diabetes
* Smoking
* IV drug use
* Immunosuppression

Risk factors associated with ↑ mortality include:

* Age  
Especially in >70 age group.
* Illness severity
* Organism  
Higher mortality seen with:
	* Group A Streptococci
	* Enteric organisms

## Pathophysiology

Necrotising fasciitis involves
* Rapid proliferation of subcutaneous bacteria
* Leukococyte proliferation
* Thrombosis of fascial vessels  
Leads to ischaemia and necrosis of tissue.

## Clinical Manifestations



### History



### Examination



## Diagnostic Approach and DDx



## Investigations



## Management

Standard treatment involves:

* Immediate and radical surgical debridement of dead and infected tissue  
Delayed debridement associated with increasd mortalityh.
* Antibiotics  
Broad spectrum.
	* Should include good streptococcal cover
* HDU or ICU care

### Hyperbaric oxygen therapy

* Controversial
* A retrospective review suggested that HBOT suggests patients are 4x less likely to die  
Multiple suggested mechanisms:
	* ↑ viability of marginal tissue
	* Reduces bacterial toxin prouction
	* Inhibits anaerobic bacterial growth  
	↑ tissue oxdiation reduction potential.
	* Potentiates antibiotic function
	* Improves efficacy of neutrophil respiratory burst
* Evidence is conflicting and some retrospective studies do not demonstrate mortality benefit

### Intravenous Immunoglobulin


### Ineffective Therapies



## Complications



## Prognosis

* 30% mortality with aggressive surgical intervention and appropriate antibiotics
* Frequent surgical debridements
* Long hospital stay
* Large soft tissue defects

---

## References


1. Devaney B, Frawley G, Frawley L, Pilcher DV. [Necrotising soft tissue infections: the effect of hyperbaric oxygen on mortality](https://www.ncbi.nlm.nih.gov/pubmed/26603791). Anaesth Intensive Care. 2015 Nov;43(6):685-92. PubMed PMID: 26603791.
2. Levett D, Bennett MH, Millar I. [Adjunctive hyperbaric oxygen for necrotizing fasciitis](http://cochranelibrary-wiley.com/doi/10.1002/14651858.CD007937.pub2/full). Cochrane Database of Systematic Reviews 2015, Issue 1. Art. No.: CD007937. 