# Pneumocystis Jirovecii Pneumonia

:::info
*Pneumocystis jirovecii* was previously known as *Pneumocystis carinii*, and was also once classified as a protozoan and not a fungus.

It is therefore sometimes still referred to by the "PCP" acronym.
:::

Severe fungal pneumonia caused by *Pneumocystis Jirovecii*, which is essentially confined to the severely immunocompromised:

* HIV
* Transplant recipients
* Haematological malignancy

## Epidemiology and Risk Factors

## Pathophysiology

*Pneumocystis Jirovecii* differs from most fungi as it has cholesterol rather than ergosterol in the cell wall, which results in:

* Minimal extrapulmonary invasion
* Immunity to most classical antifungals
    * No response to amphotericin or azoles
    * Highly resistant to echinocandins
    

### Aetiology

## Clinical Manifestations

Usually insidious:

* Non-productive cough
* Dyspnoea
* Fever
* Fatigue
* Weight loss
* Crepitations are **rare**

## Diagnostic Approach and DDx

* Alternative diagnosis for respiratory failure is present in ~15%


## Investigations

**Laboratory**:

* Blood
    * ↑ LDH\
    Common, non-specific.
* Sputum
    * PJP PCR
    * Adequate non-invasive sampling requires **induced sputum**
        * Hypertonic saline nebuliser provokes bronchorrhoea and extensive coughing
        * Time consuming
        * Requires good operator skill
    * Bronchoscopy with BAL\
    Diagnostic in >90%. \

:::column-margin
Organisms **persist** for days or weeks, so unlike many other infections, treatment can start prior to sampling if diagnostic suspicion is high enough.
:::

**Imaging**:

* CXR
    * Normal in 10%
    * Perihilar and interstitial shadowing\
    Often subtle and missed.


## Management

**Resuscitation**:\


**Specific therapy**:

* Pharmacological
    * Antimicrobials
        * **Trimethoprim/Sulphamethoxazole** (cotrimoxazole) 20+100mg/kg daily for 3 weeks\
        Dose ↓ by 25% if WCC falls
        * Pentamidine 4mg/kg IV daily\
        Only if cotrimoxazole not tolerated. Note that cotrimoxazole is a much better agent, and so mild hypersensitivity reactions are best put up with.
    * Corticosteroids\
    For patients with HIV infection or ↑ A-a gradient >35mmHg.
        * Prednisolone
            * 40mg BD for 5 days
            * 20mg BD for 5 days
            * 20mg daily until antibiotic treatment completed
* Physical
* Procedural

**Supportive care**:

**Disposition**:

### Marginal and Ineffective Therapies

## Anaesthetic Considerations

## Complications

* B
    * Pneumothorax

## Prognosis

## Key Studies

---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.