# Sepsis

A **life-threatening organ dysfunction** due to a **dysregulated** host **response to infection**, where:

:::column-margin
The definition of sepsis has remained necessarily vague, as the clinical diagnosis of sepsis is based on a constellation of non-specific features. Drawing a line which neatly includes the septic and excludes other illnesses is therefore not currently possible.\
\
This is the [Sepsis-3](https://jamanetwork.com/journals/jama/fullarticle/2492881) definition, which moved the definitional goalposts from trying to pin down "sepsis" to trying to identify patients with clinically suspected infection who had a high mortality.
:::

* **Organ dysfunction**\
⩾2 ↑ in SOFA score.
* **Septic shock**\
Sepsis, with:
	* ↓ BP requiring vasopressors
	* Lactate >2mmol/L

:::column-margin
Management of febrile neutropaenia and neutropaenic sepsis is covered under @sec-febrile_neut.
:::

## Epidemiology and Risk Factors

Major global healthcare burden:

* High number of cases
* High mortality\
~30%.

Host response is highly heterogenous, and is affected by:

* Patient factors:
	* Comorbidities
	* Genetics
* Pathogen factors:
	* Pathogen virulence
	* Location of infection


## Pathophysiology

Progression from a localised infection to systemic involvement requires:

* Activation of pattern-recognition receptors
	* Toll-like receptors
	* C-type lectin receptors
	* Retinoic acid inducible gene-1-like receptors
* Receptor activation leads to complex, simultaneous alteration of multiple metabolic pathways:
	* Pro-inflammatory
	* Anti-inflammatory\
	Simultaneously with pro-inflammatory processes.
	* Neurohormonal
	* Metabolic change
	* Coagulation activation\
	Tend towards a prothrombotic, antifibrionolytic state which may promote microvascular thrombosis and organ ischaemia.
	* Macrovascular dysfunction
	* Microvascular dysfunction
	* Endothelial dysfunction
		* Glycocalyx disruption resulting in ↑ fluid extravasation


Immune paralysis:

* Survival of the initial septic phase may lead to:
	* A dysfunctional immune system
	* Infections classically associated with immunocompromise


Vasodilation occurs via several mechanisms:

* Acidosis
	* K^+^ efflux leading to membrane hyperpolarisation\
	↓ Ca^2+^ entry into vascular smooth muscle.
	* Catecholamine resistance
* ↑ NO production\
Induced by cytokines and bacterial endotoxin.
* Adrenal suppression
* Endogenous vasopressin suppression


Septic cardiomyopathy:

* ↓ Diastolic function

### Aetiology

Any progression of localised infection may lead to sepsis; the most common in adults include:

* Lung\
~60%.
* Abdominal\
~20%.
* Primary bacteraemia
* Renal or GU

:::column-margin
Lung causes are less common in children, with the difference made up with CNS infections and ↑ primary bacteraemia.
:::

Organisms most commonly associated with sepsis include:

* Gram negative\
60%.
	* *Pseudomonas*\
	20%.
	* *E. coli*\
	15%.
* Gram positive
	* *S. aureus*\
	20%.
* Fungi

: Source of Infection

+------------------------------------------------------------------------------------+------------------+-------------------------------------+
| Organ System                                                                       | Common           | Uncommon                            |
+====================================================================================+==================+=====================================+
| **Respiratory**                                                                    | * Pneumonia      |                                     |
|                                                                                    | * *Dental*       |                                     |
|                                                                                    | * *Sinusitis*    |                                     |
+------------------------------------------------------------------------------------+------------------+-------------------------------------+
| **Cardiovascular**                                                                 | * Bloodstream    | * Endocarditis                      |
|                                                                                    | * Lines          |     * Prosthetic valves             |
|                                                                                    |     * CLABSI     |                                     |
|                                                                                    |                  |                                     |
+------------------------------------------------------------------------------------+------------------+-------------------------------------+
| **Neurological**                                                                   |                  | * Meningitis                        |
|                                                                                    |                  | * *Discitis*                        |
|                                                                                    |                  | * *Epidural abscess*                |
|                                                                                    |                  | * *V-P shunt*                       |
+------------------------------------------------------------------------------------+------------------+-------------------------------------+
| **Genitourinary**                                                                  | * UTI            | * Pyelonephritis                    |
|                                                                                    | * CAUTI          | * Endometritis                      |
|                                                                                    | * PID            | * *Prostatitis*                     |
+------------------------------------------------------------------------------------+------------------+-------------------------------------+
| **Gastrointestinal**                                                               | * Cholecystitis  | * Spontaneous Bacterial Peritonitis |
|                                                                                    | * Cholangitis    | * Polymicrobial peritonitis         |
|                                                                                    | * Pancreatitis   | * Infective colitis                 |
|                                                                                    | * Diverticulitis |     * *C. difficile*                |
+------------------------------------------------------------------------------------+------------------+-------------------------------------+
| **Integumentary**                                                                  | * Cellulitis     | * Septic arthritis                  |
|                                                                                    |                  | * Osteomyelitis                     |
|                                                                                    |                  | * Prosthetic joints                 |
|                                                                                    |                  | * *Psoas abscess*                   |
|                                                                                    |                  | * Necrotising fasciitis             |
+------------------------------------------------------------------------------------+------------------+-------------------------------------+
| **Notes**:                                                                                                                                  |
|                                                                                                                                             |
| * Classified by relative incidence in each category, rather than overall incidence                                                          |
| * Sources of potentially *occult* infection are *italicised*                                                                                |
+---------------------------------------------------------------------------------------------------------------------------------------------+



## Clinical Manifestations

Heterogenous and non-specific features:

* Tachycardia
* Temperature
	* 35% normothermic
	* 10% hypothermic
	* 55% hyperthermic\
		* Often fluctuant
		* Less likely to be present in the:
			* Elderly
			* Immunosuppressed
			* Malnourished


## Diagnostic Approach and DDx

Diagnosis of sepsis is difficult.

* Clinical
	* Signs are non-specific
		* Changes with local infection
		* May not be present in:
			* Elderly
			* Immunocompromised
	* Findings may reflect other forms of shock
* Laboratory
	* Markers are non-specific
	* Microbiological samples:
		* Take significant time to process\
		Requires treatment to be initiated in advance of knowing.
		* Must distinguish infection from colonisation\
		Requires clinical interpretation.

:::column-margin
The qSOFA is a quick screening tool to identify patients who should be *considered* for sepsis workup, and requires **⩾2 of**:

* Altered mentation
* RR >22
* SBP <100mmHg
:::

## Investigations

**Laboratory**:

* Blood
	* CRP
		* Non-specific marker of inflammation
			* May be more specific for *Strep. pneumoniae* infection\
			This may also better identify patients in whom steroid would be appropriate. 
		* Rises 4-6 hours after onset of infection, doubles ~8 hourly
		* Correlates with severity of infection
			* Rapid ↓ indicates response
	* Procalcitonin
		* Relatively more specific marker of inflammation\
		Elevated in:
			* Bacterial infection\
			Produced in response to bacterial endotoxin.
				* Levels rise in 6-8 hours\
				Prior to cultures flagging positive.
				* Not ↑ in viral or fungal infections
				* Not ↑ in local bacterial infection without a systemic response
			* Burns
			* TLS
			* Major surgery
			* Multi-organ failure
			* ESRD\
			Renally cleared.
		* No better than clinical judgment in discriminating infectious vs. non-infectious causes
		* Expensive, requires serial measurements
	* Blood cultures\
	Prior to antibiotics.


## Management {#sec-sepsis_mx}

:::priority
* Early **antibiotics** (**<1 hour**) with **blood cultures** (2-3 sets) **prior**
* Determine haemodynamic goals and target with:
	* **Fluids**
	* **Vasopressors**
:::

**Resuscitation**:\

:::column-margin
Each hour delay in antibiotic administration is associated with a 12% ↓ in survival.
:::

* C
	* **Target MAP** >65mmHg\
	Consider ↑ (e.g. MAP >70mmHg) if renal failure, poorly controlled hypertension.
	* **Fluid resuscitation**\
	10-20mL/kg up to 30mL/kg total.
		* Crystalloid most effective
			* Albumin equivalent outcomes with potentially ↓ total volume delivered, and haemodynamic goals are achieved move quickly
			* Starch harmful
		* Use dynamic measures of fluid responsiveness to assess need for more therapy
			* Passive leg raise
			* Pulse pressure variation
	* **Arterial line**\
	If vasopressors required.
	* **Vasopressors**
		* Noradrenaline 1^st^ line
			* ↑ Preload due to *veno*constriction
			* ↑ SVR due to vasoconstriction
			* Maintain or ↑ CO\
			B~1~ effects ↑ CO, compensating for ↑ in afterload.
		* Consider adrenaline as 2^nd^ line
		* Vasopressin as 3^rd^ line
		* End-of-the line vasopressor options without much supporting evidence include:
			* Methylene blue\
			1mg/kg bolus over ~30 minutes.
			* Hydroxycobalamin\
			5g.
			* Terlipressin
			* Angiotensin II
	* **Assess CO**
		* **Inotropic support** if:
			* Adequately volume resuscitated
			* Evidence of ↓ perfusion:
				* ↑ Lactate
				* ↓ Central capillary refill
				* Echocardiography
			* Pre-existing LV dysfunction
		* VA ECMO\
		Appropriate in selected patients with myocardial dysfunction, acknowledging high mortality of this cohort.


:::column-margin
Early use of noradrenaline is associated with ↓ mortality.
:::

:::column-margin
**Average** total **IV fluid** resuscitation at:

* **6** hours is **~4.2L** ±**1.4L**
* **72** hours is **~6.8L** ±**3L**
:::

**Specific therapy**:

* Pharmacological
	* **Antibiotics**
		* Empirical\
		Tailored to likely sources and resistance patterns.
	* Toxic Shock cover\
	If treating TSS, or empirical if clinically likely.
		* Clindamycin
		* IVIG
* Procedural
	* Source control
	* Removal of short-term intravascular catheters if catheter-related sepsis is likely\
	This includes arterial catheters. 
* Physical


**Supportive care**:

* F
	* pH >7.15\
	↑ Cardiac sensitivity to catecholamines.
		* Sodium bicarbonate
		* THAM
	* iCa >1.1mmol/L\
	Very low supporting evidence.
* H
	* Hb >70

**Disposition**:

**Preventative**:


### Marginal and Ineffective Therapies

**Drugs**:

* **Corticosteroids**
	* Controversial
	* Appropriate for patients:
		* With another indication for steroids
		* Sepsis with CAP
	* *May* be appropriate in septic patients:
		* Refractory to vasopressors
		* Otherwise high risk
	* Unlikely to change mortality or outcome
	* Will spare vasopressors
	* May ↓ ventilator days and speed shock resolution
* β-blockade
	* Esmolol probably most well studied
		* Very high control group mortality
		* May reflect reversal of harmful exogenous β-agonists 
* Activated protein C
* Vitamin C
* IVIG\
No proven role outside of TSS.

**Resuscitation targets**:

* CVP targeting
* ScvO~2~ targeting
* PAC targeting\
Use of PAC does not improve and may worsen outcome.


**Blood Purification**:

* High-volume haemofiltration\
CRRT with target dose >35mL/kg/hr.
* Polymyxin B Haemoperfusion\
CRRT with Polymyxin B bound to the filter, which binds bacterial endotoxin.
* High cut-off haemofiltration\
CRRT with larger pores, allowing filtration of middle-molecular weight proteins which include pro- and anti-inflammatory cytokines.


**Other**:

* Hydroxy-ethyl starch resuscitation fluids\
↑ AKI and mortality.


## Anaesthetic Considerations



## Complications

Complications of sepsis include:

* B
	* ARDS
* C
	* Septic cardiomyopathy
* D
	* **Septic encephalopathy**\
	Impaired mental function in the setting of extracranial infection.
		* 10-80% of septic cases
		* ↑ Mortality associated with ↓ GCS
		* Potential contributors include:
			* Bacterial endotoxin
			* Cytokine release
			* Haemodynamic collapse
* F
	* AKI

### Septic AKI

Epidemiology of septic AKI:

* Occurs in 22% of ICU patients with sepsis
* Associated with ↑ in mortality to 38%


Management:

* Preventative\
Most effective method:
	* Low dose vasopressors\
	Achieving a **MAP >80mmHg** may reduce requirement for RRT.
	* Note that excessive **IV fluid is *in*effective**
		* May worsen oedema\
		Aim euvolaemia.
		* Septic AKI is **not a low-flow state**
		* Balanced solutions are beneficial
		* Avoid starch and gelatin colloids
	* Treat the sepsis

## Prognosis

High mortality:

* ICU death 28-40%\
~30% when adjusted for severity.


## Key Studies

**Fluid**:

{{< include /trials/feast.qmd >}}
{{< include /trials/arise.qmd >}}
{{< include /trials/safe.qmd >}}
{{< include /trials/albios.qmd >}}
{{< include /trials/clovers.qmd >}}
{{< include /trials/classic.qmd >}}


**Early Goal Directed Therapy**:

* Early Goal-Directed Therapy is (?was) a protocolised pathway for sepsis management, targeting specific haemodynamic goals in order to maximise DO~2~ and thus restore cellular oxygen balance:
	* CVP 8-12mmHg
	* MAP 65-90mmHg
	* UO >0.5mL/kg/hr
	* ScvO~2~ >70%
	* Haematocrit >30%
* The comfort of this physiological approach did not survive the crucible of real-word RCT evaluation, and EGDT has been subsequently dismissed
* The principles of aggressive, goal-directed (but not CVP and ScvO~2~-directed) therapy live on
{{< include /trials/rivers.qmd >}}
{{< include /trials/arise.qmd >}}
{{< include /trials/process.qmd >}}


**Steroids**:

* The rationale for steroids is that they *may*:
	* C
		* Limit ↓ inotropy due to bacterial endotoxin
		* ↑ Catecholamine function
		* ↓ NO synthetase production
	* I
		* Correct adrenal insufficiency
		* Dampen hyperactive immune response
{{< include /trials/corticus.qmd >}}
{{< include /trials/adrenal.qmd >}}
{{< include /trials/aprocchss.qmd >}}


**Vitamin C**:

* The rationale for Vitamin C is that:
	* Levels are ↓ in the critically ill
	* Oxidative stress is ↑ in the critically ill
	* Vitamin C has antioxidant effects that may alleviate some oxidative stress
{{< include /trials/marik.qmd >}}
{{< include /trials/citris_ali.qmd >}}
{{< include /trials/vitamins.qmd >}}
{{< include /trials/lovit.qmd >}}


**Other**:

{{< include /trials/censer.qmd >}}
{{< include /trials/andromeda_shock.qmd >}}
{{< include /trials/fabled.qmd >}}
{{< include /trials/candisep.qmd >}}
{{< include /trials/triss.qmd >}}
{{< include /trials/morelli.qmd >}}


---

## References

1. Bellomo R, Kellum JA, Ronco C et al. Acute kidney injury in sepsis. Intensive Care Med. 2017 Jun;43(6):816-828. doi: 10.1007/s00134-017-4755-7. Epub 2017 Mar 31.
1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.
1. [Early Restrictive or Liberal Fluid Management for Sepsis-Induced Hypotension](https://www.nejm.org/doi/full/10.1056/NEJMoa2212663). New England Journal of Medicine. 2023;388(6):499-510.
1. Singer, M., Deutschman, C.S., Seymour, C.W., Shankar-Hari, M., Annane, D., Bauer, M., Bellomo, R., Bernard, G.R., Chiche, J.-D., Coopersmith, C.M., Hotchkiss, R.S., Levy, M.M., Marshall, J.C., Martin, G.S., Opal, S.M., Rubenfeld, G.D., van der Poll, T., Vincent, J.-L., Angus, D.C., 2016. [The Third International Consensus Definitions for Sepsis and Septic Shock (Sepsis-3)](https://jamanetwork.com/journals/jama/fullarticle/2492881). JAMA 315, 801.
1. Lamontagne F, Masse MH, Menard J, et al. [Intravenous Vitamin C in Adults with Sepsis in the Intensive Care Unit](https://www.nejm.org/doi/10.1056/NEJMoa2200644). N Engl J Med. 2022;386(25):2387-2398.
1. Bloos F, Held J, Kluge S, et al. [(1→3)-β-d-Glucan-guided antifungal therapy in adults with sepsis: the CandiSep randomized clinical trial](https://link.springer.com/article/10.1007/s00134-022-06733-x). Intensive Care Med. 2022;48(7):865-875. doi:10.1007/s00134-022-06733-x
1. Meyhoff TS, Hjortrup PB, Wetterslev J, et al. [Restriction of Intravenous Fluid in ICU Patients with Septic Shock. New England Journal of Medicine](https://www.nejm.org/doi/full/10.1056/NEJMoa2202707). 2022;386(26):2459-2470.
1. O’Grady NP, Barie PS, Bartlett JG, et al. [Guidelines for evaluation of new fever in critically ill adult patients: 2008 update from the American College of Critical Care Medicine and the Infectious Diseases Society of America](https://journals.lww.com/ccmjournal/Fulltext/2008/04000/Guidelines_for_evaluation_of_new_fever_in.40.aspx). Critical Care Medicine. 2008;36(4):1330.
1. Morelli A, Ertmer C, Westphal M, et al. [Effect of Heart Rate Control With Esmolol on Hemodynamic and Clinical Outcomes in Patients With Septic Shock: A Randomized Clinical Trial](https://jamanetwork.com/journals/jama/fullarticle/1752246). JAMA. 2013;310(16):1683-1691. doi:10.1001/jama.2013.278477
1. Cheng MP, Stenstrom R, Paquette K, et al. [Blood Culture Results Before and After Antimicrobial Administration in Patients With Severe Manifestations of Sepsis](https://www.acpjournals.org/doi/10.7326/M19-1696). Ann Intern Med. 2019;171(8):547-554. doi:10.7326/M19-1696
1. Fujii T, Luethi N, Young PJ, et al. [Effect of Vitamin C, Hydrocortisone, and Thiamine vs Hydrocortisone Alone on Time Alive and Free of Vasopressor Support Among Patients With Septic Shock: The VITAMINS Randomized Clinical Trial](https://jamanetwork.com/journals/jama/fullarticle/2759414). JAMA. 2020;323(5):423. doi:10.1001/jama.2019.22176
1. Fowler AA III, Truwit JD, Hite RD, et al. [Effect of Vitamin C Infusion on Organ Failure and Biomarkers of Inflammation and Vascular Injury in Patients With Sepsis and Severe Acute Respiratory Failure: The CITRIS-ALI Randomized Clinical Trial](https://jamanetwork.com/journals/jama/article-abstract/2752063). JAMA. 2019;322(13):1261-1270. doi:10.1001/jama.2019.11825
1. Hernández G, Ospina-Tascón GA, Damiani LP, et al. [Effect of a Resuscitation Strategy Targeting Peripheral Perfusion Status vs Serum Lactate Levels on 28-Day Mortality Among Patients With Septic Shock: The ANDROMEDA-SHOCK Randomized Clinical Trial](https://jamanetwork.com/journals/jama/article-abstract/2724361). JAMA. 2019;321(7):654-664. doi:10.1001/jama.2019.0071
1. Annane D, Renault A, Brun-Buisson C, et al. [Hydrocortisone plus Fludrocortisone for Adults with Septic Shock](http://www.nejm.org/doi/full/10.1056/NEJMoa1705716). New England Journal of Medicine. 2018;378(9):809-818. doi:10.1056/NEJMoa1705716
1. Venkatesh B, Finfer S, Cohen J, et al. [Adjunctive Glucocorticoid Therapy in Patients with Septic Shock](http://www.nejm.org/doi/full/10.1056/NEJMoa1705835). New England Journal of Medicine. 2018;378(9):797-808. doi:10.1056/NEJMoa1705835
1. Sprung CL, Annane D, Keh D, et al. [Hydrocortisone Therapy for Patients with Septic Shock](http://www.nejm.org/doi/pdf/10.1056/NEJMoa071366). N Engl J Med. 2008;358(2):111-124. doi:10.1056/NEJMoa071366
1. Marik PE, Khangoora V, Rivera R, Hooper MH, Catravas J. [Hydrocortisone, Vitamin C, and Thiamine for the Treatment of Severe Sepsis and Septic Shock: A Retrospective Before-After Study](https://journal.chestnet.org/article/S0012-3692(16)62564-3/fulltext). CHEST. 2017;151(6):1229-1238. doi:10.1016/j.chest.2016.11.036
1. Maitland K, Kiguli S, Opoka RO, et al. [Mortality after Fluid Bolus in African Children with Severe Infection](http://www.nejm.org/doi/full/10.1056/NEJMoa1101549). New England Journal of Medicine. 2011;364(26):2483-2495. doi:10.1056/NEJMoa1101549
1. [Goal-Directed Resuscitation for Patients with Early Septic Shock](http://www.nejm.org/doi/full/10.1056/NEJMoa1404380). New England Journal of Medicine. 2014;371(16):1496-1506. doi:10.1056/NEJMoa1404380
