# Toxic Shock Syndrome {#sec-toxic_shock}

Syndrome of **severe distributive shock** and generalised **inflammation** that occur **secondary** to **bacterial endotoxin** that:

* Is produced by some:
	* **Streptococci**
		* Occurs in up to 20% of Streptococcal infections
		* Much more common that staphylococcal toxic shock
		* Due to:
			* *S. pyogenes*
			* *S. dysgalactiae* subspecies *equisimilis*
	* Staphylococci
		* Less common
		* May occur with colonisation without infection
		* Usually due to *S. Aureus* (MRSA or MSSA)
* Occurs in non-immune individuals\
Most people develop antibodies to these toxins.

:::column-margin
Streptococcal and staphylococcal toxic shock syndromes are similar enough to be merged. An overview of these pathogens can be found @sec-strep and @sec-staph.
:::

## Epidemiology and Risk Factors

General Risk factors:

* Immunocompromise
* **Pregnancy**


Streptococcal toxic shock:

* Infections
	* Pneumonia
	* Necrotising fasciitis


Staphylococcal toxic shock:

* Infections
	* Surgical wound
	* Mastitis
	* Sinusitis
	* Osteomyelitis
	* Burns
* Tampon use
	* Prolonged use of same tampon
	* High-absorbency tampons
	* Within 2 days of menstruation


## Pathophysiology

Bacteria secrete endotoxin:

* Bind to T-cell Major Histocompatibility COmplex
* Stimulates T-lymphocyte response\
Up to 20% of T-cells may respond, compared to ~0.01% that usually respond to antigens.
* Leads to **massive T-cell activation** and large release of T-cell cytokines, in particular:
	* IL-2
	* Interferon-γ
	* TNF-α

### Aetiology

Streptococcal toxic shock occurs with **invasive** streptococcal infection, including:

* Pneumonia
* Septic arthritis
* Peritonitis
* Obstetric
	* Endometritis
	* Chorioamnionitis
	* Mastitis


Staphylococcal toxic shock syndrome occurs with:

* **Colonisation**:
	* Menstrual (~50%)\
	Tampon colonisation.
	* Non-menstrual
		* Nasal packing
		* IUD
		* Wounds\
		Uninfected wounds can be still colonised with *S. Aureus*, and be a source of toxic shock.
* Invasive infection:
	* Pneumonia
	* Soft tissue infection
* Colonisation without infection


## Clinical Manifestations

Diagnostic features:

* Inflammatory syndrome
	* Fever ⩾39°C
	* Chills
	* Headache
	* Myalgia
	* Sore throat
* Skin findings
	* Diffuse macular erythrodermic rash\
	Sunburn to bright erythema.
	* "Strawberry tongue"
	* Desquamation\
	Of palms and soles. Late finding.
* Multiorgan failure


Suggestive features:

* Rapid onset
* Disproportionate:
	* No obvious source with staphyloccal aetiology
	* Otherwise unimpressive infection


## Diagnostic Approach and DDx

Consider if:

* Classical skin findings
* Known streptococcal infection and sepsis
* Soft tissue infection and sepsis
* Flu-like illness with:
	* Significant left-shift
	* Haemodynamic instability despite resuscitation
* Pregnancy

:::column-margin
The US CDC has published diagnostic criteria, which are not reproduced here as they exhibit the unfortunate combination of being both very long and clinically limited.
::: 

## Investigations

Laboratory:

* Blood
	* FBE
		* ↑ WCC with left shift
		* Thrombocytopenia
	* CK\
	↑ Secondary to cytokine ↑.
	* UEC
	* LFT
		* ↑ Bilirubin
		* ↑ AST/ALT
	* Coag
	* Cultures

:::column-margin
CK may also be ↑ in necrotising fasciitis.
:::


## Management

:::info
Principles:

* Good sepsis resuscitation\
Covered under @sec-sepsis_mx.
* Specific therapy for toxic shock is relatively benign and a low-threshold to initiate it is appropriate:
	* Known or reasonable likelihood of streptococcal infection
	* Persistent vasopressor requirements
:::

**Specific therapy**:

:::column-margin
:::caution
This just covers management of toxic shock syndrome; you still need to **treat the actual infection** with appropriate antimicrobials and source control.
:::
:::

* Pharmacological
	* **Toxin-suppressive antimicrobials**
		* Clindamycin 900mg IV Q8H
			* Most evidence
			* Generally broad activity against streptococci and staphylococci\
			Combination with a β-lactam recommended for streptococcal infections to avoid potential clindamycin resistance.
		* Linezolid 600mg IV Q12H\
		Toxin suppression with better coverage of both streptococci and staphylococci.
	* **IVIG**\
	Neutralise toxic antibodies.
		* 1g/kg on day 1\
		Can ↑ to 2g/kg if faiulure of response.
		* 0.5g/kg on day 2 and 3, if required
* Procedural
	* Source control
		* Debridement of necrotic tissue
		* Removal of tampon

:::column-margin
The role and dosing of IVIG in staphyloccal toxic shock is not well elucidated.
:::


## Complications

* C
	* Septic cardiomyopathy\
	↑ Risk in toxic shock.
* F
	* AKI
* H
	* DIC


---

## References