# Zygomycoses

Collection of life-threatening fungal infections caused by:

* **Mucorales**\
Causes the majority of cases, and generally known as **mucor**.
* Entomopthorales

## Epidemiology and Risk Factors

Mucormycosis:

* 3^rd^ most common disease of stem-cell transplants
* ↑ Incidence 

## Pathophysiology

### Aetiology

## Clinical Manifestations

Generally non-specific:

* Local inflammation
	* Generally sinusitis as sinus infection common
* Progression to more extensive local invasion with:
	* Cellulitis
		* Black eschar over skin
	* Pneumonia
	* Cerebral invasion
		* Cranial nerve signs

## Diagnostic Approach and DDx

## Investigations

**Bedside**:

**Laboratory**:

* Culture
	* Generally 3-5 days to positivity
* Tissue or abscess samples
	* Periodic acid-Schiff staining
	* Grocott's methenamine silver dry-mount staining

**Laboratory**:

**Other**:

## Management

**Resuscitation**:\


**Specific therapy**:

* Pharmacological
	* Antifungals
		* Amphotericin B
* Procedural
* Physical

**Supportive care**:

**Disposition**:

**Preventative**:


### Marginal and Ineffective Therapies

## Anaesthetic Considerations

## Complications

## Prognosis

## Key Studies


---

## References
