# Bad News

:::caution
An important distinction needs to be made between **bad** and **catastrophic news**. Catastrophic news needs to be delivered **immediately** - don't beat around the bush.
:::

## Catastrophic News

Process:

:::column-margin
What is catastrophic may vary a bit depending on the person; but death is always catastrophic. 
:::

1. Check identify\
Ensure you have the right patient and the right family member.
2. Introduce self\
You can do this with a bundled warning shot ("I am terribly sorry to meet you like this.", but avoid dragging it out.
3. Deliver the message\
Concisely and completely.
4. Fallout\
"Sit in the rubble with them."
	* Offer to call someone else


## Bad News

Process: 

:::column-margin
The key difference between bad and catastrophic news is that it is reasonable to spend some time clarifying understanding before delivering the message.
:::

1. Check identity
2. Introduce self
3. Ask what they already understand\
Avoid this if there is catastrophic news, i.e. some major change that obviates previous discussions. Important first question as it reveals:
	* What they already know
	* Health literacy
	* Communication style
4. Deliver the message
5. Fallout


## Key Studies

{{< include /trials/cosmic_eol.qmd >}}

---

## References

1. CICM Communications Course. Course Notes. 2023.
1. Kentish-Barnes N, Chevret S, Valade S, et al. [A three-step support strategy for relatives of patients dying in the intensive care unit: a cluster randomised trial](https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(21)02176-0/fulltext). The Lancet. 2022;399(10325):656-664.
