# Colleagues

Discussing treatment (particularly treatment limitation) with colleagues outside of the unit can be challenging. Some important considerations are:

:::column-margin
Standard communication tips apply:

* Warning shots
* Giving time to process what is being said
* Respond to emotions
:::

* Acknowledge uncertainty
* Be humble\
You can be wrong.
* Be prepared to negotiate\
Consider:
	* Time-limited trials
	* Second opinion
	* Waiting a day
* Maintain professionalism\
The working relationship will continue after the therapeutic relationship with this patient has ended.
* Develop good relationships with colleagues outside of the ICU
* Recognise the efforts and successes of your colleagues
* Focus on your area of expertise, not theirs
* Flag deterioration early
* Discuss patients in private, away from the bedside
* Come to a consensus before announcing a plan to the family
* Focus on what you are doing, not on what you want to withhold or stop


---

1. CICM Communications Course. Course Notes. 2023.