# Concepts

Hearing bad news and having complex, emotionally charged conversations affects how people receive and process information. Having complex conversations well is essential to good care for both patients and families.


General considerations:

* Avoiding **jargon**\
Even in titles - just say "Doctor" (not registrar, consultant, intensivist, etc). Simplify information.
* Keep messaging **consistent**\
Try and minimise different statements between the (multiple) medical and nursing teams. 
* Use **repetition**
* Keep things **concise**\
Primacy-recency theory indicates that people will tend to remember the first and last things that you say.
* Use **silence**\
	* Ensure the rest of the team knows there will be long pauses
	* If a silence feels too long, consider a "content-free statement" (e.g. "I can't imagine how hard it is to hear this information.")
* **Check in**\
	* How they are feeling with what is being said?
	* What are their concerns?
	* Ask them to summarise\
* Use **signposting**\
Provide a framework for the conversation; either enumerated (there is a number of things I would like to discuss), or with headings.
* Be **empathic**\
Often, questions may *seem* like a request for more medical information, but may actually just be existential distress ("What happens now?") and may be better served with kind words. More information can always be provided later.
* **Reflective listening**\
Restate what someone has told you, prompting them to continue.
* **Chunking**\
Deliver information in small packets, interspersed with silence for processing time.
* **Body language**
	* Aim for an open posture
	* Consider matching your body language to that of the person you are speaking to\
	This is called "attunement".
* Have a **phrase library**\
Write down phrases and statements that you find work well for you, and practice them so they feel natural.


## Responding to Emotion

Understanding and responding to emotions is critical. It is important to:

* **Listen**\
Recognise that it is an emotional response, and don't respond with information.
* **Acknowledge**\
Acknowledge the presence of the emotion. If you're unsure if it will be helpful then you can avoid naming it too directly (e.g. "I feel this is frustrating for you.") Normalise the emotional response.
* **Support**\
Offer support, and a solution if one is available.
* **Thank**\
Thank them for sharing the concern.


If an emotion has got to you, it is important to re-centre yourself to avoid escalating things. There are a variety of techniques to deal with this, consider:

* Recognise\
Note the emotion you have.
* Accept\
That you've had an emotional response.
* Reset
* Engage\
Continue the conversation.


## Remote

Phone and video conversations are a common way to update family members. Extra considerations include:

:::column-margin
If delivering bad news over the phone, consider a follow-up call after to check in.
:::

* No visual stimulation\
Describe the surroundings in a reassuring way.
* No non-verbal communication\
Extra attention to empathic oral communication - state things that would be otherwise be conveyed silently.
	* "I'm listening."
	* "I'd like to hear more about that."
* Silence can be more difficult\
Need to signpost silence:
	* "I'm going to pause to let you take that all in."
	* "Let me know when you're ready for me to continue."
* Technical factors
	* Call quality
	* Signal strength
* Check in before ending the call


## Cultural Humility

Culture, traditions, spiritual beliefs, and upbringing form an important role in guiding an individuals beliefs. Culture is important because:

* Medical needs are contextual and dependent, in part, on an individuals values
* Individuals may have many different cultural heritages that they feel different degrees of affinity and connection to\
This makes generalising the beliefs of a culture to a person potentially harmful.

:::column-margin
The term "died" may not be appropriate in some indigenous Australian groups - "finished up" might be used instead.
:::

Cultural humility is the practice of **suspending what you** (think) **you know** about a person based on **generalisations about their culture**.


## Use of Interpreters

Professional interpreters are the best available option, although bilingual staff are acceptable in low-risk situations. Family and friends should be avoided.

Interpreters should be used when:

:::column-margin
Family may request **no** interpreter if:

* Feel their understanding is good enough
* Be embarrassed
* Know the interpreter
* Fear loss of privacy
* Be uncomfortable with gender/religious/ethnic background
* Worry about cost
:::

* Family requests
* When people cannot comprehend or respond to questions in English
* Stressful, complex, or unfamiliar situations
* When consent is required 

Using an interpreter:

* Consider discussing aim of the meeting with the interpreter prior\
Clarify the use of any technical terms.
* Introduce both yourself and the interpreter
* Make confidentiality explicit
* Talk directly to the family
* Avoid jargon
* Use silence and short packets of information


## Speaking with Children

Principles:

* Parents have the choice in determining what information is given to their children
	* Find out what the parents or guardians have already told them
	* We have a role to advocate for children
* Children should be allowed to choose whether or not to visit a loved one
	* Families may look for guidance
	* Those who choose not to visit can be supported in other ways
		* Write a message for someone else to read out
		* Draw a picture
	* Children who visit should be appropriately prepared
		* Describe appearance, smells, and sounds
		* Describe what the loved one will look like
		* Introduce them to the bedside nurse
	* Children should be able to leave when they wish
* Communicate at eye level
* Answer questions
* Be explicit in saying it is not their fault\
Children often blame themselves, even when this is irrational.

---

## References

1. CICM Communications Course. Course Notes. 2023.
1. Core Family Donation Conversation (FDC) Workshop. Course Notes. 2023.
1. Australian Government Organ and Tissue Authority. Family Donation Conversation Resource Guide V2.0. 2021.
1. Philpot SJ, Bilgrami I, Sullivan L. [Communicating medical information over the telephone in critical care](https://ccr.cicm.org.au/journal-editions/articles/1360). Critical Care and Resuscitation. 2020;22(3). 
