# Cultural Humility

Culture, traditions, spiritual beliefs, and upbringing form an important role in guiding an individuals beliefs. Cultural humility is the practice of **suspending what you** (think) **you know** about a person based on **generalisations about their culture**. Culture (and humility) are important because:

* Medical needs are contextual and dependent, in part, on an individuals values
* Individuals may have many different cultural heritages that they feel different degrees of affinity and connection to\
This makes generalising the beliefs of a culture to a person potentially harmful.
* Ignoring culture has a demonstrable adverse impact on healthcare outcomes

:::column-margin
The term "died" may not be appropriate in some indigenous Australian groups - "finished up" might be used instead.
:::

## Cultural Identity

Cultural identity reflects how an individual sees themselves in relations to the world, and may incorporate:

* Beliefs
* Values
* Ethnicity
* Nationality
* Language
* Social background
* Generation
* Wealth
* Sex
* Gender
* Religion


Individual differences in cultural identify can be seen by how different people adopt the attitudes, behaviours, beliefs, and values of different cultural groups that they belong to.


## Approach

Recognise where your understanding ends and when to seek help. Avenues include:

:::column-margin
Focusing only on the patients cultural identify may becoming "othering", as it emphasises the differences of the patient from the practioners frame of reference. Instead, be:

* Regard*ful* of your own attitudes, beliefs, and behaviours
* Respectful of the patients
:::

* Ask the patient how they would like to be treated\
Genuine interest, openness, and sharing vulnerability is almost always well-regarded.
* Consult the family\
* Cultural representatives
* Read about the culture
* Engage an indigenous liaison officer or cultural support worker


---

## References

1. CICM Communications Course. Course Notes. 2023.
1. Core Family Donation Conversation (FDC) Workshop. Course Notes. 2023.
1. RACP. [Australian Aboriginal, Torres Strait Islander and Māori Cultural Competence and Cultural Safety](https://elearning.racp.edu.au/course/info.php?id=79). RACP Online Learning. 2024.
1. Belfrage M. [Why “culturally safe” health care?](https://www.mja.com.au/journal/2007/186/10/why-culturally-safe-health-care) Med J Aust. 2007 May 21;186(10).
