# Family Meetings

Considerations:

:::column-margin
If the family is small, reduce the number of clinical staff attending so you don't outnumber and overwhelm them.
:::

* **Where**\
Decide a location.
	* Bedside\
	Better if the patient is conscious.
		* Ensure privacy
		* Minimise interruptions\
		Alarms, other staff.
	* Room\
	Unconscious patient.
* **What**\
Set an **agenda**, and decide what to say.
	* Decide what sort of meeting is this?\
	Update? Shared decision making?
	* Be clear on the facts
		* **Reassess** the **patient** prior
		* Know the input from other teams
	* Confirm the **medical consensus**
		* Current issues\
		Examine the patient prior.
		* Current future stages
		* Huddle\
		Confirm with staff attending the:
			* Goal of the meeting
			* Role of each team member
			* Leader of the meeting
			* Consensus opinion
* **Who**
	* Family
		* Delegated spokesperson if patient is unable
	* Support staff
		* Bedside nurse
		* Social work
		* Pastoral care

---

## References

1. CICM Communications Course. Course Notes. 2023.