# Phrase Library

Content-free statements:

* "This must be overwhelming for you."
* "It's awful. It's unfair."

Silence:

* "I'd like to pause for a minute so you can take this all in."
* "Let me know when you're ready for more information."
* "Are you ready for me to keep talking?"

Recap and questions:

* "Have I explained this well?"
* "I want to see if I've done a good job explaining things to you. Would you mind telling me what you will tell the rest of the family?"
* "What would you like to ask me?"


## Shared Decision Making

Explore:

* "What does a *usual* day look like for you?"
	* "What does a good day look like?"
	* "What does a bad day look like?"
		* "After a time in ICU, the bad day may become your usual day. How do you feel about that?"
	* "How many good days compared to bad days do you have?"
	* "How does this compare to six months ago?"
* "When did you last enjoy good health?"
* "What is important to you?"
	* "How would you feel if you couldn't do those things anymore?"

Options:

* "It's really important that the treatment you get is the treatment that you want."
* "I don't want to subject you to treatments that have no realistic chance of helping you."

Advice:

* "If you got so sick that someone else needed to make decisions for you, who would you choose?"
	* "What would you want them to know about you?"
* "Would you like my help in making this decision?"


## Family Meetings

Learning:

* "Because [they] were so sick when [they] arrived, I never got a chance to get to know [them]. I was wondering if you could tell me a bit about [them]?"
* "What would they say if they were here now?"

Involving people:

* "I notice that you've been quiet - I'd like to know your thoughts."

Ending:

* "Feel free to keep this room for as long as you need; I'll come back in an hour and we can talk more."

## Bad News

* "[They] have become very unwell and you need to come in."
* "The situation is dire and we are trying really hard to save [their] life."
* "I'm going to call someone else for you - who would like me to call?"
* "I'm going to call you back in 10 minutes."

## Open Disclosure

Content:

* "We're still trying to understand exactly what happened, but I'd like to share with you everything we know so far."

Responsibility:

* "I am the consultant looking after [them] today, so the buck stops with me."
* "Usually when harm occurs to a patient, there are multiple things that have happened."

## Speaking Up

Rudeness:

* "Sorry I missed that, can you say it again?"
* "I don't really get that joke, can you explain it to me?"

Bullying:

* "What did they say when you told them this?"