# Shared Decision Making {#sec-shared}

Shared decision making is a two-way conversation between healthcare staff and the patient and their family, aiming to develop a **goal-orientated** medical plan which is tailored to the patients individual values. The overall goal which is to empower the patient to make the decision they would make if they knew all the medical information that you do.

Key aspects of this conversation are to understand:

* What is their **current life like**?
* **What is important to them**?
	* What do they enjoy doing?
	* What quality of life would be unacceptable to them?
* What is their risk appetite like? How much medical treatment would they be willing to undergo?

:::column-margin
The traditional approach generally assumes:

* Survival is the (only) goal
* Death is a medical failure
* The disease is the most important issue

Conversely, a goal-orientated approach assumes:

* Survival is one of several possible goals
* A *bad* death is a medical failure
* The person is the most important issue
:::

## Seven Steps

:::tick
Frame discussions with "We can..." rather than "What would you like me to do?"
:::

1. **Ask**\
What does the patient understand about their diagnosis?
2. **Explain**\
Fill any gaps in the patients knowledge of their disease.
3. **Explore**\
Get to know the patient as a person. Find out:
	* Values and goals
	* Hopes and fears
	* Illness vs. disease perspective
	* Presence and role of advocates
4. **Options**\
Provide options to the patient, and discuss what the expected outcomes with each would be.
5. **Advise**\
Find out how much patients want to be guided by the medical teams.
	* ~75% of patients want advice from medical teams
	* ~20% want to defer the decision to the clinician
	* ~5% want to decide on their own
6. **Agree**\
Find a plan that is suitable.
7. **Communicate**\
Disseminate the agreed plan to staff, patient, and family.

:::column-margin
Giving good advice requires understanding the patient; the critical steps here are:

* Explore
* Options
* Advise
:::

:::column-margin
**Prognostic discordance** occurs when patients and clinicians have different understanding of their disease:

* Often patients have a more optimistic view of their prognosis
* Discordance may lead to apparently contradictory wishes being expressed
:::

---

## References

1. CICM Communications Course. Course Notes. 2023.