# Discussion Themes

An overview of different types of discussions in critical care, and some pointers for each.

## Shared Decision Making

Shared decision making is a two-way conversation between healthcare staff and the patient and their familiy, aiming to develop a medical plan which is tailored to their individual values. Key aspects are:

* What is their current life like?
* What is important to them?
	* What do they enjoy doing?
	* What quality of life would be unacceptable to them?
* What is their risk tolerance like? How much medical treatment would they be willing to undergo?

The seven step approach:

1. **Ask**\
What does the patient understand about their diagnosis?
2. **Explain**\
Fill any gaps in the patients knowledge of their disease.
3. **Explore**\
Get to know the patient as a person. Find out both:
	* Values
	* Functional state
4. **Options**\
Provide options to the patient, and discuss what the expected outcomes with each would be.
5. **Advice**\
Find out how much patients want to be guided by the medical teams.
6. **Agree**\
Find a plan that is suitable.
7. **Communicate**\
Disseminate the agreed plan to staff, patient, and family.

## Remote

Phone and video conversations are a common way to update family members. Considerations include:

:::column-margin
If delivering bad news over the phone, consider a follow-up call after to check in.
:::

* No visual stimulation\
Describe the surroundings in a reassuring way.
* No non-verbal communication\
Extra attention to empathic oral communication.
* Silence can be more difficult\
Need to signpost silence - "I'm going to pause to let you take that all in."
* Technical factors
	* Call quality
	* Signal strength

## Bad News

* Warning shot
	* Overt\
	"Unfortunately, the news I have to share is not good."
	* Covert
	"I wanted to meet with you because I am concerned about [your loved one]."
* Ask what they already understand\
Avoid this if there is catastrophic news, i.e. some major change that obviates previous discussions. Important first question as it reveals:
	* What they already know
	* Health literacy
	* Communication style


## Open Disclosure

Open disclosure is an open discussion with a patient who has received harm during medical care. Open disclosure is a:

* Patient right
* Professional and institutional obligation
* Part of healthcare quality improvement
* Process involving:
	* A factual explanation
	* An apology\
	Including the words "I am sorry", and an admission of responsibility.
	* An explanation of steps to prevent recurrence


---

1. CICM Communications Course. Course Notes.