# Extubation

> * In all peri-extubation airway problems, rapid supplemental oxygen administration is beneficial


Emergence is associated with more airway problems than induction. Planning for extubation should **consider**:

* How well the patient will **tolerate the physiological response** to extubation  
Coughing/bucking/Valsalva, hypertension.
* The **likelihood** of the patient **requiring reintubation**  
* The predicted **difficulty of reintubation**

## Assessment

* A
	* How easy will this patient be to reintubate?
		* Anatomical
		* Physiological
		* Environmental
	* Can the patient protect their own airway?
	* What is the risk of aspiration?  
	Baseline risk of aspiration in the anaesthetic population is 2-10/10,000.
	* **Cuff leak** if prolonged intubation or prone
* B
	* Is there adequate oxygenation, and can they oxygenate without support?
		* FiO~2~
		* PEEP requirement
	* Is there adequate ventilation, and can they ventilate without support?
		* ETCO~2~
		* Pressure Support requirement
	* Can this patient clear secretions adequately?
* C
	* Is there any CVS compromise?
	* Does this patient require tight haemodynamic control peri-extubation?
* D
	* Is there adequate analgesia?


## Problems Occurring During Extubation

Problems include:

* A
	* **Obstruction**
		* Laryngospasm  
		Most common cause of post-extubation upper airway obstruction.
		* Oedema  
		Particularly in:
			* Children
			* Prolonged period of intubation
			* Prone
			* Larger ETT to tracheal size
		* Trauma
		* Vocal Cord Dysfunction  
		Paradoxical movement of the vocal cords, which may present as stridor or complete upper airway obstruction.
			* Diagnosed by  visualisation of paradoxical adduction of vocal cords in inspiration
			* More common in:
				* Young
				* Female
				* Upper respiratory tract infections
				* Stress
		* Vocal Cords Paralysis
			* Due to vagal nerve injury
	* ETT damage
		* Damaged pilot tube preventing deflation
	* Laryngeal trauma/oedemma
	* Cuff herniation
	* Surgical fixation  
	Of airway device to surrounding structures
* B
	* Coughing  
	May be reduced by placing lignocaine or lignocaine/sodium bicarbonate solution into the ETT cuff, or marinating the ETT cuff in lignocaine prior to intubation.
	* Bronchospasm
	* Negative pulmonary oedema  
	Pulmonary oedema due to extreme negative intra-alveolar pressure, in turn due to high inspiratory effort against a narrow or closed upper airway (e.g. occluded ETT).
* C
	* CVS instability  
	Generally ↑ MAP and HR, with corresponding ↓ in EF due to a reduction in afterload.


## Performing Extubation

**General case for the low-risk extubation:**
* Provide 90-100% oxygen  
Consider some nitrogen to avoid complete atelectasis.
* Sit up to optimise FRC
* Ensure ToF >0.9
* Suction the pharynx
* Deflate the ETT cuff  
Slow deflation minimises coughing.
* Extubate at end-inspiration  
Vocal cords are maximally abducted at this point.
* Consider:
	* Suction of tube during extubation to clear pharynx  
	* Providing positive airway pressure during extubation, prior to removing the tube from the glottis  
	↑ airway pressure in the trachea, assisting expulsion of secretions from the vocal cords as the tube is removed.


### Low-Risk Considerations

* Place a **bite block**  
Recommended in young, male patients to prevent complete occlusion of the tube if bitten. If the tube is bitten, then deflate the pilot balloon to allow the patient to breath around the ETT, minimising the risk of negative-pressure pulmonary oedema.
* **Extubate lateral**ly  
Left lateral with the head below the level of the heart if high aspiration risk. Especially useful in children as this helps to maintain airway without requiring jaw thrust.


### High-Risk Considerations

* Place an **airway exchange catheter** or **exchange wire**  
Indicated when reintubation may be potentially anatomically difficult.
	* Catheter is placed through ETT and left in place after extubation, and can be used as a stylet to guide reintubation
	* Airway exchange wires are generally better tolerated, and can be left up to 72 hours  
	Wires require an exchange catheter to be railroaded prior to an ETT.



### Attenuating Physiological Response

If it is important to minimise coughing or maintain tight haemodynamics peri-extubation, then consider:

* **Deep extubation**  
Extubation after recovery of spontaneous ventilation but prior to recovery of laryngeal reflexes. Haemodynamically stable but risks both aspiration and airway obstruction; so is contraindicated in patients who are at risk of aspiration, difficult mask ventilation, or difficult reintubation. Process:
	* Ensure steady, stable, adequate ventilation on minimal pressure support
	* No response (cough, breath-hold, or altered respiratory pattern) to:
		* Removal of ETT tape/tie
		* Suctioning of oropharynx
		* Deflation of ETT cuff
	* Remove ETT at end-inspiration
* **Lignocaine**  
	* 1-1.5mg/kg IV peri-extubation via cuff
	* Use lignocaine in ETT cuff  
	Must be delivered early (usually with induction) and given adequate time to work.
* **LMA exchange** ("Bailey maneuvre")  
Exchange ETT for an LMA during a deep plane of anaesthesia and allow emergence to occur with the LMA in situ.
* **Remifentanil**  
Effect site 2.0ng/mL peri-extubation.






### Strategies for Difficult Extubation







---

## References

1. Karmarkar S, Varshney S. [Tracheal extubation](https://academic.oup.com/bjaed/article/8/6/214/405940). Contin Educ Anaesth Crit Care Pain. 2008;8(6):214-220.