# Tracheostomy Overview

Definitive airway produced by inserting a tube subglottically through the anterior neck directly into the trachea. May be:

:::column-margin
This covers the management of a tracheostomy, including considerations for their use. [Tracheostomy weaning](/management/airway/trache-wean.qmd) and insertion of percutaneous tracheostomy are covered elsewhere.
:::

* Surgical\
Dissection and incision of the trachea under direct vision.
* Percutaneous\
Seldinger dilation.


## Indications

:::column-margin

| Favours Percutaneous                     | Favours Surgical                             |
| --                                       | --                                           |
| ↓ Bleeding                               | Vascular insertion site on ultrasound        |
| ↓ Infection                              | Complex neck anatomy                         |
| ↓ Tracheal stenosis                      | Less risk of death/cardiac arrest            |
| Better cosmetic result                   | Greater airway backup (anaesthetist/surgeon) |
| Logistics (no waiting on surgical lists) | Does not require bronchoscope                |
| No risk of intrahospital transfer        | Emergent                                     |

: Factors to consider: Percutaneous versus surgical tracheostomy

:::

* A
	* **Surgical**\
	e.g. Laryngectomy.
* B
	* **Long-term mechanical ventilation**\
	Useful for patients requiring long-term ventilation, and to aid **respiratory weaning** by:
		* **↓ Sedation** requirements\
		Facilitates spontaneous ventilation, ↑ proportion of respiratory work done by the patient. May lead to ↓ total time on mechanical ventilation.
		* ↓ Work of breathing\
		↓ Airway resistance and (marginally) ↓ dead space relative to ETT.
		* **↓** Airway **trauma**\
		↓ Risk of laryngeal stenosis, vocal cord ulceration, and improves voice recovery. These risks rise after **1 week** of oral intubation.
		* **↓ Aspiration** risk\
		Glottic competence is restored, so the tube cuff is not the only thing preventing aspiration.
		* Better **secretion management**\
		Awake patients can cough more effectively. Potentially less VAP.
		* Better **oral care**\
		Can brush teeth.
* D
	* **↓ Sedation** requirements\
	Better tube tolerance and **patient comfort** compared to oral ETT.
		* Improved **communication**\
			* Desedation facilitates interaction
			* Lip-reading\
			Easier without an ETT.
			* Talking\
			With the cuff down, and with or without a speaking valve. Requires generating subglottic pressure of >2cmH~2~O.
		* Facilitate **neurological assessment**
	* **Quality of life**\
* E
	* Facilitate **physiotherapy**\
	Positioning, rehabilitation, coughing.



## Considerations

Considerations for tracheostomy insertion include:

:::column-margin
**Timing** of tracheostomy insertion is difficult. In general:

* Clinicians are **bad at predicting** who will need a tracheostomy
* Routine early tracheostomy therefore leads to large numbers of unnecessary tracheostomies
* An approach:
	* Early if **prolonged ventilation inevitable**\
	e.g. GBS.
	*  **>10 days** following **mechanical ventilation**, without imminent extubation
:::

* A
	* Neck anatomy
		* Vascularity
		* Length of accessible trachea\
		Patients without much extra-thoracic trachea will be more difficult with both insertion and management.
	* Intubation grade
	* C-spine stability
* B
	* Respiratory function\
	Ideally:
		* FiO~2~ **<0.6**
		Risk of airway fire with electrocautery, and indicates tolerance of interruption of ventilation during insertion.
		* PEEP\ **<10cmH~2~O**
		Tolerance of de-recruitment and interruption of ventilation during insertion.
* H
	* Coagulopathy
* I
	* Infection\
	At site of insertion.


## Components

Components of the tracheostomy setup:

* **Tracheostomy tube**\
May be:
	* Fenestrated\
	Tube has holes *above* the cuff.
		* Permits coughing, phonation, and **aspiration**\
		Outer portion needs to be blocked to divert gas flow via vocal cords.
		* Aids respiratory weaning
		* Patient must protect own airway
		* Improves swallow
		* Inner cannula can be:
			* Fenestrated\
			Allows tube to function as a fenestrated tube.
			* Unfenestrated\
			Blocks fenestration, which permits mechanical ventilation. Mechanical ventilation of a fenestrated tube results in significant circuit leak and a distressed, continually-exhaling patient.
	* Unfenestrated
* **Inner cannula**\
Inner tube placed inside the tracheostomy tube to prevent it being contaminated.
	* Easy cleaning\
	Just remove the inner cannula, clean, and replace.
	* ↓ Internal dimensions/↑ airway resistance\
	Degree depends on the catheter size.
* **Speaking** (Passy Muir) **valve**\
One-way valve that allows a patient to *in*spire through the tracheostomy, and then *ex*pire via the native away, allowing phonation. The valve:
	* **Requires** the **cuff** to be **deflated**\
	Or the patient will be unable to exhale.
	* A humidifier can (and should) be used\
	An HME will be ineffective as the patient exhales via a different route.
	* Can be used with or without a ventilator\
	The ventilator will need to be set accordingly, to prevent continual alarms.
* Tracheostomy **cap**\
Occlusive cover for the tracheostomy tube, preventing inspiration via the tracheostomy tube, turning the tube into a partial upper airway obstruction. This requires the patient to inspire and expire via the native airway, and also the cuff to be deflated.


## Management

Caring for a tracheostomy tube:

:::column-margin
Tracheostomy patients are high risk and should be managed by trained staff. An ICU outreach team is beneficial.
:::

* A
	* **Cuff pressures**\
	Keep **<30mmHg** to reduce the risk of tracheal ulceration and stenosis.
	* **Clean**ing\
	Inner cannula (if present) should be cleaned when necessary.
	* **Suction**ing\
		* *Shallow* tracheal suctioning (to the length of the tube) to remove secretions, particularly if cough is inadequate
		* Suction channels (above the cuff) should be suctioned at least Q4H
	* Wound care\
	The wound must be kept clean to prevent infection.
* B
	* **Humidification**\
	Should be routine, including if patient is using trache hood or Swedish nose. Important for:
		* Patient comfort
		* Secretion management\
		↓ Viscosity.


### Facilitating Speech

Speech greatly improves the quality of life of a patient with a tracheostomy. All methods of phonation require gas to be exhaled via the native airway. This requires:

:::column-margin
Contraindications to speaking:

* High aspiration risk
	* Unconscious/comatose
	* Loss of upper airway reflexes
	* High secretion load
* Unable to exhale via native airway
	* Upper airway obstruction
	* Inadequate lung mechanics\
	↑ Resistance, ↓ compliance.
:::

* A **deflated** cuff
* Prevention of expiration via the tracheostomy
	* Finger-occlusion
	* Speaking valve
	* Cap


## Complications

In-situ tracheostomy:

* A
	* **Dislodgement**\
	Risks include:
		* Patient
			* Agitation
			* Large s
		* Equipment
			* Poorly sized tube
		* Staff\
		Inadequate:
			* Training
			* Numbers
	* **Bleeding**\
	~5% of cases.
		* Early\
		Bleeding within **48 hours** is likely venous.
		* Late\
		Due to erosion of the tracheostomy into a vascular structure.
			* [**Tracheo-innominate fistula**](/management/airway/trache-crisis.qmd)\
			Erosion (classically of the *cuff*) into the innominate artery.
				* Leads to catastrophic:
					* Bleeding and airway soiling
					* Air entrainment
			* Any bleeding between 3 days and 6 weeks should be investigated for a fistula\
			Either bronchoscopically or via CT.
	* **Obstruction**
		* Bleeding
		* Secretions\
		↑ Risk if dehumidified.
* B
	* **Failure to wean**\
	If the patient is unable to wean from the ventilator despite the tracheostomy, this may be an unsatisfactory outcome for both patient and family.
	* Pneumonia\
	↑ Risk due to bypass of normal upper respiratory protective mechanisms. Occurs in **~25%** of patients.
* D
	* **Quality of life**\
	Generally worse in patients who have received a tracheostomy, compared to patients who did not.
* G
	* Swallowing difficulty
* I
	* **Infection**\
	Either of the stoma, or contamination of wounds (sternal, CVC) with secretions.


Post-tracheostomy:

* A
	* Tracheal **stenosis**\
	Commonly occurring (1-2%), rarely significant. Risk ↑ with:
		* Procedural
			* Tracheal ring fracture
		* Equipment
			* Oversized cannula
		* Patient
			* Male
			* Elderly
			* Prolonged duration of use
	* **Tracheomalacia**\
	Loss of tracheal cartilage (usually ischaemic), leading to collapse under negative-pressure inspiration.
	* Persistent stoma\
	May require surgical repair.




---

## References

1. De Leyn, Paul, Lieven Bedert, Marion Delcroix, Pieter Depuydt, Geert Lauwers, Youri Sokolov, Alain Van Meerhaeghe, Paul Van Schil, and Belgian Association of Pneumology and Belgian Association of Cardiothoracic Surgery. “Tracheotomy: Clinical Review and Guidelines.” European Journal of Cardio-Thoracic Surgery: Official Journal of the European Association for Cardio-Thoracic Surgery 32, no. 3 (September 2007): 412–21. [](https://doi.org/10.1016/j.ejcts.2007.05.018)
2. Dulguerov, Pavel, Gysin, Claudine, Perneger, Thomas, MD, PhD, Chevrolet, Jean-Claude. Percutaneous or surgical tracheostomy: A meta-analysis. Crit Care Med. 1999;27(8):1617-1625. [](https://doi.org/10.1097/00003246-199908000-00041)
3. Hess, Dean R. “Facilitating Speech in the Patient With a Tracheostomy.” Respiratory Care 50, no. 4 (April 1, 2005): 519–25. [](https://doi.org/10.1097/00003246-199908000-00041)
4. Ailawadi, Gorav. “Technique for Managing Tracheo-Innominate Artery Fistula.” Operative Techniques in Thoracic and Cardiovascular Surgery 14, no. 1 (March 1, 2009): 66–72. [](https://doi.org/10.1053/j.optechstcvs.2009.02.003).
5. Donaldson, Lachlan, and Raymond Raper. “Successful Emergency Management of a Bleeding Tracheoinnominate Fistula.” BMJ Case Reports 12, no. 12 (December 2019): e232257. https://doi.org/10.1136/bcr-2019-232257.

