# Brain Death {#sec-braindeath}

:::info
Brain death and circulatory death are both death, and do not differ in type or degree, but in the way they are determined.
:::

**Brain Death** is the irreversible loss of all functions of the brain, including the brainstem. Brain death is also referred to as neurological death.

:::column-margin
This covers epidemiology and determination of brain death in a general Australasian context. Management of the brain dead patient proceeding to organ donation is covered at @sec-braindeathmx.\
\
Some suggested phrases for describing brain death to families are listed under @sec-donorconvo.
:::

## Epidemiology and Risk Factors

Brain death:

* Accounts for 1-2% of all death
	* 5-10% of ICU death
* Rates decline as treatment of brain injury improves
* Is poorly understood by both physicians and the general public
	* In a 2015 survey, 57% of physicians did not believe that brain death equates to cardiorespiratory death

## Pathophysiology

{{< include /includes/brain_death_pathophys.qmd >}}

## Determination of Brain Death

:::info
The definitions and process discussed here are specific to brain death in the Australian context, which requires **whole brain death**. Some other jurisdictions accept brain-stem death as sufficient, and vary as to the procedural requirements to determine brain death.
:::

Determination of brain death requires:

* Meeting **preconditions**
	* Consistent lesion
	* No reversible cause
	* Possible to diagnose
* **Observation period**\
Sustained period with absence of neurological activity.
* **Clinical assessment**\
Formal testing by two clinicians.

:::column-margin
Time of death is the completion of examination by the second doctor.
:::

### Preconditions

For brain stem testing to be appropriate, the following preconditions must be met:

:::column-margin
Due to the immaturity of brain-stem reflexes, brain death cannot be determined in preterm neonates, and ↑ caution should be used in neonates and infants.
:::

* A **brain lesion consistent with a diagnosis of brain death**\
Neuroimaging consistent with acute brain pathology that could cause brain death. Only in the case of HIE is imaging not required, and the diagnosis may be made on history alone.
* **Absence of physiological** and **anatomical confounders** of assessment:
	* No high cervical spine injury\
	Must be able to assess:
		* Upper limb motor response to central stimulus
		* Central response (grimace) to upper limb stimulus
		* Cough reflex
	* Normotensive\
	SBP ≥90mmHg or MAP >60mmHg in adults, or age-appropriate perfusion pressure in children.
	* No sedation, analgesia\
	The amount of elapsed time required since the last administration varies on the drugs used and the degree of any renal or hepatic dysfunction.
		* This is a question of clinical judgment
		* Thiopentone plasma levels should be <10mg/L
		* Drug antagonists can be used if concern about persisting effects
	* No muscle relaxation\
	Confirm with train-of-four.
	* Normothermia\
	≥ 36.5°C. Hypothermia depresses consciousness, and brainstem reflexes may be absent <28°C.
	* Absence of severe metabolic, endocrine, and electrolyte derangements
		* Glucose: <3 or >25mmol/L
		* Sodium: <125 or >160mmol/L
		* Phosphate: <0.5mmol/L
		* Magnesium: <0.5mmol/L
		* Urea: >40mmol/L
		* Severe hypothyroidism
		* Severe hypoadrenalism
* **Ability to perform clinical testing**\
	* Ability to assess brain stem reflexes\
	At least one functioning eye and ear.
	* Ability to perform apnoea test\
	Neuromuscular system capable of independent respiration (e.g. no high cervical spine injury), saturations able to be maintained with supplemental oxygen.

:::column-margin
Conditions which may mimic brain death include:

* Neurological
	* GBS
		* Miller-Fisher
* Drug and Toxin
	* Baclofen
	* Valproic acid
	* Organophosphate intoxication
:::


### Observation Period

Prior to performing clinical testing, a minimum of **4 hours** of observation should be performed during which the:

:::column-margin
The observation period should be extended to **24** hours in the case of HIE or hypothermia >6 hours.
:::

* **Preconditions** are **met**
* **GCS** is **3**
* Non-reactive pupils\
May be mid-sized or dilated.
* No spontaneous respiratory effort
* Absent cough reflex

:::column-margin
Since all patients undergoing brain death testing will be intubated, GCS 3 = GCS 2T.
:::


### Clinical Testing

:::info
Each Australian state has slightly different requirements around the qualifications, experience, and relationship to the patient of the clinicians determining brain death.
:::

Equipment required for testing:

* Pupil torch
* Gauze or cotton wool
* Otoscope
* 50mL syringe\
And a cannula, or use a Toomey syringe.
* Cold ice water
* Kidney dish\
To collect cold ice water.

:::column-margin
In order to help the testing process flow smoothly, ↓ the minute ventilation so that the PaCO~2~ is close to the upper limit of normal and place the patient on 100% oxygen at the start of testing. If the minute ventilation and PaCO~2~ are stable, the pre-apnoea ABG can also be taken prior to commencing testing.
:::

Clinical testing is performed **separately** by two suitably trained and experienced clinicians (at least one a specialist), and requires:

:::column-margin
Family should be offered the opportunity to observe clinical testing, after appropriate explanation (particularly about **spinal reflexes**) and support. Consider using the second set of testing, as the family can be warned about any spinal reflexes that may occur.
:::

* **Coma**\
GCS 3; with no motor response following painful stimulus applied centrally (bilaterally) and to all four limbs.
* **Absence** of **brainstem reflexes**\
Should be tested **sequentially** and **bilaterally**.
	* **Pupils**\
	Fixed and non-reactive.
	* **Corneal** reflex\
	Use of cotton wool or gauze are appropriate stimuli. Touch the cornea until visible deformation of the gauze is seen, and use a fresh corner for the opposite side.
	* **Oculo-vestibular** reflexes\
		* Firstly, inspect both ear canals to confirm:
			* Intact tympanic membrane
			* Absence of canal occlusion
		* Secondly, inject cold ice water into each EAM via a small catheter:
			* 50mL should be infused
			* The eyes should be observed for 60 seconds after instillation
			* A normal reflex  until either:
			* Nystagmus\
			Slow-phase towards irrigated ear in intact brainstem.
			* Ocular deviation
	* **Gag**\
		* Expose the chest to evaluate for respiratory effort
		* Use a tongue depressor or cotton swab to stimulate the posterior pharynx on each side\
		A laryngoscope can be used for assistance, if required.
	* **Cough**
		* Expose the chest to evaluate for respiratory effort
		* Pass a a tracheal suction catheter to evaluate for cough
* **Apnoea**\
Conducted last so that an ↑ PaCO~2~ does not confound assessment. Apnoea testing assesses ventilatory drive, and is performed by:
	* Preoxygenation with 100% O~2~
	* Expose the chest to evaluate for respiratory effort
	* Ventilator disconnection\
	Hypoxia (SpO~2~ <88%) should be avoided; attach a self-inflating bag with a PEEP valve to prevent atelectasis and provide some passive entrainment.
	* No respiratory effort when:
		* PaCO~2~ is ≥60mmHg, OR\
		Expect PaCO~2~ to ↑ by ~3mmHg/min as a guide for when to perform the ABG.
		* PaCO~2~ has risen 20mmHg above baseline\
		Expect ~3mmHg of rise per minute, so leave 7-10 minutes until testing.

:::column-margin
Use of suction catheter or t-piece to provide passive oxygenation during apnoea testing is not recommended.\
\
For patients on ECMO during apnoea testing:

* Preoxygenate via the lung and circuit
* ↑ PaCO~2~ to >45mmHg on the circuit
* Attach a CPAP circuit as describe above
* ↓ Sweep to 0.5-1L/min
:::

The **time of death** is the time of the **second** set of testing. This should be discussed with family in advance as:

* Certain times may be important for the family
* The patient will look the same after they have died as they did before\
Still warm, "breathing" on the ventilator.


### Spinal Reflexes

Spinal reflexes are movements due to loss of higher centre inhibition of a reflex arc, are **compatible with brain death** and:

* Occur:
	* In up to 50% of patients
	* Usually within 24 hours of death, though can stretch to days
	* Consistently\
	May be highly variable between patients, but usually repeatable within a given patient.
* Include:
	* Upper limb extension-pronation
	* Lower limb flexion
	* Deep tendon reflexes
	* Lazarus sign\
	Bilateral arm flexion, shoulder adduction, hand raising above chest.
	* Plantar response


## Investigations

:::tick
If there is any doubt as to whether there is a confounding effect of sedation, then radiological testing should be performed.
:::

Cerebral perfusion imaging is used when brain death cannot be determined because the ***preconditions* are not met**.

:::column-margin
Obviously, if the preconditions *are* met then clinical testing should be performed, and that will determine whether or not brain death has occurred. Some institutions may routinely perform radiological investigations in addition to clinical assessment, but this is not required to establish a diagnosis of brain death.
:::

Key investigations:

* **4-vessel angiogram**\
Demonstrating absence of flow above the carotid siphon in the anterior circulation and foramen magnum in the posterior circulation. Reliable, easy to interpret, but limited access.
* **Tc-99 HMPAO Spect**\
Nuclear medicine study that determines lack of perfusion in the brain parenchyma.
* **CT Angiography**\
Acceptable when formal angiography or radionuclide imaging is not available.
 

Other investigations:

* MRI\
Should not be used to determine brain death.
* Transcranial doppler\
Should not be used to determine brain death, although may be helpful to **time** formal imaging if brain death is expected as presence of MCA flow indicates radiographic evidence of brain death will not be present.
* EEG\
No benefit. Absence of cortical activity does not confirm brainstem death and electrical activity in some cortical cells does not indicate brain functioning.


---

## References

1. ANZICS. [Brain Death Determination](https://www.anzics.com.au/wp-content/uploads/2018/08/Brain-Death-Determination-Statement-FINAL.pdf). 2018.
1. ANZICS. [The Statement on Death and Organ Donation](https://www.anzics.com.au/wp-content/uploads/2022/04/ANZICS-Statement-on-Death-and-Organ-Donation.pdf). Edition 4.1. 2021.
1. Wijdicks EF. The bare essentials: coma. Pract Neurol. 2010 Feb;10(1):51-60.
1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.
1. Dünser MW, Dankl D, Petros S, Mer M. Clinical Examination Skills in the Adult Critically Ill Patient. Springer International Publishing; 2018.