# Ocular Procedures Performed with Local Anaesthetic Blocks

>Time: Variable  <br>
>Pain: Minimal  <br>
>Position: Supine, face parallel to ceiling  <br>
>Blood loss: Negligible  <br>
>Special: Hyaluronidase: Hydrolyses hyaluronan, reducing integrity of the extracellular matrix and ↑ tissue permeability  

Local anaesthetic with or without sedation for eye surgery is:

* Common
* Relatively free of risk
Predominant morbidity related to oversedation.
* Used for many ocular surgeries including:
	* Trabeculectomy  
	50-80 minutes.
	* Intraocular Lens Insertion


## Techniques

Different methods for LA include:

* Topical  
Provides corneal anaesthesia.
	* Adequate for cataract surgery by phacoemulsification  
	Does not provide akinesia.
* [Peribulbar Block](/anaesthesia/regional/peribulbar.md#id)  
The most commonly used injection technique.
* [Sub-Tenon's Block](/anaesthesia/regional/subtenon.md)  
A useful alternative when a peri-bulbar block is contraindicated.
* Retrobulbar block  
Produces better akinesis and lower IOP than a peribulbar block, but has greater associated risks and is essentially superseded by a peribulbar block.


## Considerations

* B
	* COAD  
	CO~2~ retention may occur under the drapes. High-flow oxygen under the drapes may reduce this.
	* Ability to lie flat for up to 30 minutes
* C
	* Hypertension  
	High SBP may ↑ risk of bleeding, especially with use of phenylephrine drops to dilate the eye. Normal antihypertensives should be taken.
* D
	* **Axial length**  
	Determines which technique would be more appropriate.
	* Ability to obey commands
	* Anxiety levels around LA and eye
* H
	* Clotting status
		* Bleeding issues
		* Presence of anticoagulants    
		Clotting profile should be checked within 24 hours for patients on anticoagulants.
			* Use of antiplatelet agents including aspirin
			* Warfarin and INR if applicable
			* NOACs


## Preparation

* Standard ANZCA monitoring
* IV Access

## Induction

* Time out
* Give sedation  
Many appropriate techniques:
	* Midazolam 0.5-2mg
	* Propofol 10-30mg with alfentanil 250ug
	* Propofol 10-20 mg with ketamine 10mg and alfentanil 100-250ug
* Apply topical local anaesthetic drops  
3 drops of 1% amethocaine or oxybuprocaine into the eye. Repeat 3 times at 1 minutely intervals, as required.


---

## References

1. Ripart J, Mehrige K, Rocca RD. [Local & Regional Anesthesia for Eye Surgery](https://www.nysora.com/local-regional-anesthesia-for-eye-surgery). NYSORA.
2. Royal College of Anaesthetists and Royal College of Opthalmologists. [Local Anaesthesia in Opthalmic Surgery](https://www.rcophth.ac.uk/wp-content/uploads/2014/12/2012-SCI-247-Local-Anaesthesia-in-Ophthalmic-Surgery-2012.pdf). 2012.