# Penetrating Eye Injuries


>Airway: ETT usual given emergent surgery and remote airway. <br>
>Access: Any<br>
>Pain: Substantial intraoperative stimulation, requiring deep analgesia or anaesthesia. <br>
>Position: Aim head elevated to reduce IOP <br>
>Time: Variable <br>
>Blood loss: Negligible <br>
>The Bottom Line:
>* [IOP control critical](/anaesthesia/opthal/opthal-principles.md#Intra-Ocular Pressure): intubation, extubation, and PONV prevention
>* Oculocardic reflex

Major issues with anaesthetic management include:

* Avoidance of ↑ IOP  
Risks evacuation of ocular contents.
* Emergency surgery


## Surgical Stages

## Preoperative

Assessment:

* Size of defect  
Affects risk of evacuation of ocular contents.
* Mechanism  
Associated injuries.

Premedication:

* Consider anxiolytic

## Intraoperative

> * Goal is to avoid ↑ in IOP  
> Most anaesthetic agents lower IOP, including:
> 	* Opioids
> 	* Volatiles
>	* IV hypnotics

Induction:

* RSI
* Suxamethonium can be used, noting that it is associated with a (mild) rise in IOP
* Rocuronium/sugammadex is also an appropriate combination
* Lignocaine 1-1.5mg/kg prior to induction to minimise IOP ↑ with laryngoscopy


Maintenance:

* Deep anaesthesia required to avoid coughing
* Nitrous oxide is acceptable provided there is no air in the eye


Emergence:

* Cough-free extubation is critical to avoid associated rise in IOP

## Postoperative

Control of PONV to avoid vomiting and rise in IOP:

* Two antiemetics prior to emergence

### Complications


---

## References

1. Murgatroyd H, Bembridge J. Intraocular pressure. Contin Educ Anaesth Crit Care Pain. 2008;8(3):100-103. doi:10.1093/bjaceaccp/mkn015
