# Paediatric Anaesthetic Assessment

*This covers specific elements of assessing a paediatric patient for anaesthesia. The general elements of the [pre-Anaesthetic](/assessment/anaesthetic/pre-anaesthetic.md) and [considerations for paediatric anaesthesia](/anaesthesia/paeds/considerations.md) are covered elsewhere.*

Anaesthetic assessment of the paediatric patient aims to:

* Obtain a medical history and examination
* Develop rapport with the child and guardian
* Explain the anaesthetic components
* Plan the induction
* Gain consent

## History

Particularly important are:

* Birth and prematurity
* Respiratory disease

### Birth and Prematurity

* Perinatal events
* Problems with delivery
* **Prematurity**
	* Gestational age at birth
	* Current post-conception age  
	Children <56 weeks post-conception age should have pulse oximetry for 12-24 hours post-operatively, due to risk of apnoeas.

### Respiratory Disease

* Asthma
* Stridor
* Respiratory tract infection  
Current, or recent (last 6/52).


#### Respiratory Tract Infection

RTIs are:

* Defined as two or more of:
	* Sore throat
	* Sneezing
	* Rhinorrhoea
	* Nasal congestion
	* Malaise
	* Cough
	* Fever/laryngitis
* Usually viral  
May have bacterial superinfection.
* Commonly described as URTIs, but usually involve whole respiratory tract
* Associated with ↑ risk of respiratory complications:  
For 6/52 post infection (though highest risk in first 2/52):
	* 5x increase
	* 10x increase if intubated
	* Including:
		* Laryngospasm
		* Coughing
		* Hypoxia
* Common cause of procedural cancellation

Factors favouring cancellation:

* Elective surgery
* Signs of severity
	* Productive cough
	* Purulent secretions
	* Febrile >38°C
	* Systemically unwell
		* Fatigue
		* Anorexia
		* Diarrhoea
		* Vomiting

Factors favouring proceeding:

* 'As well as they ever are'
* Largely recovered
* Brief surgery
* Not requiring intubation
* Continual unwellness  
Many children have multiple RTIs per year, and will never be 'low risk'.
* Surgically correctible  
Respiratory symptoms may be due to the lesion requiring surgery.
* Inconvenience  
Logistical burden on the family may be significant.

### Cardiovascular Disease

* Murmurs
	* Functional and flow murmurs are common in children  
	Non-pathological murmurs are:  
		* Asymptomatic
		* Soft
		* Systolic
		* Present with normal heart sounds
	* Pathological murmurs are:
		* Symptomatic
			* Failure to thrive
			* Poor exercise tolerance
			* Cyanotic
		* Pansystolic/diastolic
	* Murmurs should be evaluated:
		* Prior to surgery if pathological
		* After surgery if non-pathological (and previously unknown)

---

## References

1. von Ungern-Sternberg BS, Boda K, Chambers NA, Rebmann C, Johnson C, Sly PD, et al. Risk assessment for respiratory complications in paediatric anaesthesia: a prospective cohort study. The Lancet. 2010 Sep;376(9743):773–83. 
