# Disseminated Intravascular Coagulation

Acquired syndrome of **extreme systemic intravascular activation** of **coagulation** that:

* Occurs secondary to an underlying condition
* Causes **consumption** of **platelets** and **coagulation factors**\
With subsequent:
	* Coagulopathy and bleeding.
	* Microvascular fibrin thrombi\
	Leading to tissue ischaemia and multiorgan dysfunction.
* May be acute or chronic
	* Acute DIC is:
		* Generally more familiar
		* Characterised by microvascular thrombosis and bleeding
			* Bruising
			* Bleeding\
			Venepuncture sites, surgical wounds.
	* Chronic DIC is:
		* Associated with disease where thrombin formation is occurring over a prolonged period\
		e.g. Malignancy, IUFD, aneurysms, wound healing.
		* Partially compensated\
		Upregulation of:
			* Platelet and factor production\
			Assays may be normal or only slightly abnormal.
			* Hepatic FDP clearance
		* Characterised by thrombosis without bleeding


## Epidemiology and Risk Factors

Conditions which lead to the development of DIC include:

* Septic shock\
Occurs in ~35% of cases of severe sepsis.
* Trauma
	* Exsanguination
	* Burns
* Obstetrics
	* Abruptio placentae
	* Haemorrhage
	* AFE
* Vascular malformations
* Malignancy
	* Solid organ tumours\
	Primarily thrombosis.
	* Acute promyelocytic leukaemia


## Pathophysiology

Normal coagulation involves:

* Vascular constriction
	* ↓ Bleeding
	* Provides time for haemostasis
* Platelet plugging
* Fibrin clot formation
	* Coagulation cascade initiated predominantly via the extrinsic pathway by exposed tissue factor


Pathological coagulation occurs through a series of steps:

* Activation of coagulation system
	* Release of tissue thromboplastins
		* Trauma
		* Surgery
		* Malignancy
		* Intravascular haemolysis
	* Vessel wall endothelial injury
		* Platelet activation
			* Gram negative endotoxin
			* Viral infections
			* Burns
			* Dysoxia
			* Acidosis
		* Trauma
		* Thrombi
	* Primary induction of platelet activation
		* Sepsis
* Excessive thrombin generation
* Thrombin load overcomes anticoagulant control mechanisms\
Including:
	* Protein C
	* Antithrombin
	* Tissue factor pathway inhibitor
* Thrombosis occurring throughout the vasculature

### Aetiology

## Assessment

## Diagnostic Approach and DDx

:::info
Diagnosis based on a combination of:

* Clinical features
* Laboratory testing
:::

The International Society for Thrombosis and Haemostasis scoring system:

* **Requires presence** of a **DIC-associated disease**
* Suggests **DIC** if **score ⩾5**

: ISTH DIC Scoring System

+---------------------------+----------+----------+----------+
| Category                  | 2 Points | 1 Point  | 0 Points |
+===========================+==========+==========+==========+
| Platelet count (×10^9^/L) | <50      | <100     | \>100    |
+---------------------------+----------+----------+----------+
| ↑ FDP                     | High     | Moderate | No       |
+---------------------------+----------+----------+----------+
| ↑ PT (s)                  | \>6      | 6-3      | <3       |
+---------------------------+----------+----------+----------+
| Fibrinogen (g/L)          |          | <1.0     | \>1.0    |
+---------------------------+----------+----------+----------+


## Investigations

:::info
Laboratory investigations:

* Are not accurate to provide diagnosis on their own
* Can be used to score likelihood for DIC
:::

**Laboratory**:

* Blood:
	* FBE
		* Anaemia\
		Microangiopathic haemolytic anaemia.
		* Thrombocytopaenia\
		Low or rapidly ↓
	.* Coagulation
		* Assays (PT, APTT)\
		Prolonged, but this may be minimal.
		* Fibrinogen\
		May be either reduced or ↑.
			* Reduced to consumption
			* ↑ Due to role as acute phase reactant
	* D-Dimer\
	↑ FDP due to fibrinolysis.
	* Blood film\
	Schistocyte formation.

:::column-margin
Coagulation **assays** may be **normal** in **chronic DIC** due to ↑ production, which compensates for ↑ consumption.
:::

## Management

:::priority
* **Treat** the **underlying condition**
* If bleeding: **Judicious** use of **blood products**
* If clotting: Cautious anticoagulation
:::

**Specific therapy**:

* Pharmacological\
Three strategies:
	* **Active bleeding**\
	Transfuse to keep:
		* Platelets >30-50
		* PT <3s
		* Fibrinogen >1.5g/L
		* Consider vitamin K
		* Consider antifibrinolytic
	* **No major bleeding or thrombosis**\
	Prophylactic LMWH.
	* **Overt thromboembolism** or organ failure\
		* Therapeutic anticoagulation\
		Usually UFH.


### Anaesthetic Considerations

### Marginal and Ineffective Therapies

## Complications

Include:

* Microangiopathic haemolytic anaemia
* Organ failures
	* 15% of malignancy
	* 40% of sepsis

## Prognosis

Strong independent predictor of mortality in critically ill patients.

## Key Studies


---

## References


1. Levi M, Scully M. How I treat disseminated intravascular coagulation. Blood. 2018 Feb 22;131(8):845–54. 
