# Heparin Induced Thrombotic Thrombocytopaenia

Immune-mediated **hypercoagulable state** due to **formation** of **auto-antibodies** to a **heparin-platelet** complex characterised by:

* Presentation **5-14 days after** heparin **exposure**\
Key exceptions:
	* Major surgery "resets the clock"\
	May precipitate HITT after the appropriate interval in a patient receiving long-term heparin.
	* Re-commencing heparin in a patient who has been heparin exposed in the preceding 90 days\
	Initial exposure leads to antibody formation, which causes rapid onset of HITT when heparin is recommenced.
* Thrombocytopenia
	* Usually to 30-50% of baseline
	* Not <20×10^9^/L
	* Occurs over 1-3 days
* Thrombosis
	* 30%
	* May be arterial or venous
	* May be in both large and small vessels

:::column-margin
Various definitions and classifications are used interchangeably. This definition emphasises Type II HITT, which is the clinically significant form.

Some authorities distinguish between:

* **Type I**, or HIT\
Benign condition characterised by:
	* Transient, mild thrombocytopaenia\
	Platelets >100×10^9^/L.
	* 10% of patients who receive heparin
	* Resolves following heparin administration
	* **No thrombosis**
	* Occurs in **first 2 days**
	* Probably non-immune in origin
* **Type II**, or HITT\
Clinically significant thrombocytopaenia with thrombosis.
:::

## Epidemiology and Risk Factors

Incidence:

* 1/5000 hospitalised patients

Risk factors:

* Critically ill\
0.3-9.5%.
* Surgery\
	* Cardiac surgery
1-3%.
* UFH > LMWH
* Duration
* Female

:::column-margin
Highest risk in patients who received UFH for 7-10 days.
:::

## Pathophysiology

* **Platelet factor 4** protein is expressed on platelet cell surface
* This binds heparin and activates lymphocytes and antibodies
* Production of an IgG anti-PF4 antibody occurs
* Binding of antibody results in:
	* Platelet activation
	* Platelet factor 4 release
		* Positive feedback
	* Removal of IgG-coated platelets by reticuloendothelial system


## Clinical Features

Key factors:

* Appropriate timing
* Thrombocytopenia\
Either <150×10^9^/L or ↓ by >50%.
* Thrombosis

## Investigations

**Laboratory**:

* Blood
	* FBE
		* Thrombocytopenia
	* Anti-PF4 antibody immunoassay
		* Sensitive but non-specific\
		Detects many insignificant anti-PF4 antibodies.
		* High false positive rate
		* Require adequate pre-test probability
	* Serotonin release assay (functional assay)
		* Limited to reference laboratories
		* Functional test evaluating immunologic response of platelets to heparin
		* Donor platelets pre-treated with C-serotonin are exposed to patient serum (or plasma nad heparin)
		* Serotonin release >20-50% (lab dependent) is positive


**Imaging**:

* DVT ultrasound

## Diagnostic Approach and DDx

:::caution
Diagnosis is challenging due to multiple potential causes of thrombocytopaenia and common use of heparins.
:::

Risk may be calculated using the **4T score**:

* 0-3: Low probability
* 4-5: Intermediate probability
* 6-8: high probability

: 4T Score

+-----------------------------------+---------------------------------------------------+--------------------------------------------------+---------------------+
| Category                          | 2 Points                                          | 1 Point                                          | 0 Points            |
+===================================+===================================================+==================================================+=====================+
| Magnitude of thrombocytopaenia    | * ↓ By >50%                                       | * ↓ By 30-50%                                    | * ↓ By <30%         |
|                                   | * Nadir >20×10^9^/L                               | * Nadir 10-19×10^9^/L                            | * Nadir <10×10^9^/L |
+-----------------------------------+---------------------------------------------------+--------------------------------------------------+---------------------+
| Timing of thrombocytopaenia       | * 5-10 days                                       | * \>10 days                                      | * <4 days           |
|                                   | * <1 day following restarting heparin\            | * <1 day following restarting heparin\           |                     |
|                                   | With previous heparin exposure in last 30 days.   | With previous heparin exposure in last 100 days. |                     |
+-----------------------------------+---------------------------------------------------+--------------------------------------------------+---------------------+
| Thrombotic sequelae               | * Proven thrombosis                               | * Progressive thrombosis                         |                     |
|                                   | * Skin necrosis                                   | * Recurrent thrombosis                           |                     |
|                                   | * Acute systemic reaction following heparin bolus | * Silent thrombosis                              |                     |
|                                   |                                                   | * Erythematous lesions                           |                     |
+-----------------------------------+---------------------------------------------------+--------------------------------------------------+---------------------+
| Other causes of thrombocytopaenia | Non-evident                                       | Possible                                         | Definite            |
+-----------------------------------+---------------------------------------------------+--------------------------------------------------+---------------------+


Differentials include:

* Thrombotic microangiopathy
* Drug-induced thrombocytopenia
* Venous thrombosis
* Hypersensitivity reactions

Diagnostic process:

* Calculate 4T score
* If intermediate or high
	* Cease heparin
	* Immunoassay
	* If positive, confirm with functional assay
	* If strongly positive, commence therapeutic non-heparin anticoagulation


## Management

:::priority
* **Tailor investigations** to clinical suspicion
* **Cease heparin**
* Commence non-heparin **anticoagulation**
:::


**Specific therapy**:

* Pharmacological
	* **Cease heparin**
		* UFH and LMWH
		* Heparin flushes in arterial lines
		* Heparin bonded:
			* Extracorporeal circuits
			* Lines
			* IDCs
	* Transition to a non-heparinoid **anticoagulant**
		* Direct thrombin-inhibitor
			* Bivalirudin\
			If impaired hepatic and renal function.
			* Argatroban\
			If normal hepatic function.
		* Factor Xa inhibitor\
			* Fondaparinux
		* Vitamin K antagonist\
		Only when platelet count is >150×10^9^/L due to risk of worsening thrombosis.
		* DOAC
* Procedural
	* Plasmapheresis
		* If refractory to medical therapy
		* If requiring heparin/protamine for CPB in patients with previous HITT
* Physical


**Supportive care**:

* H
	* Platelet transfusion\
	If platelets <20×10^9^/L.


### Anaesthetic Considerations

### Marginal and Ineffective Therapies

## Complications

* Death\
Up to 20%
* F
	* Adrenal-vein thrombosis
* H
	* DVT

## Prognosis

Recovery:

* Platelet count improves usually within ~1/52 after cessation of heparin\
May take weeks.
* Antibody clearance takes 50-85 days
* Future heparin exposure does not guarantee recurrence, but heparin exposure should be minimised in future


## Key Studies


---

## References

1. Greinacher A. [Heparin-Induced Thrombocytopenia](https://www.nejm.org/doi/10.1056/NEJMcp1411910). Solomon CG, ed. N Engl J Med. 2015;373(3):252-261. doi:10.1056/NEJMcp1411910
1. Ivascu NS, Fitzgerald M, Ghadimi K, Patel P, Evans AS, Goeddel LA, et al. [Heparin-Induced Thrombocytopenia: A Review for Cardiac Anesthesiologists and Intensivists](https://pubmed.ncbi.nlm.nih.gov/30502310/). Journal of Cardiothoracic and Vascular Anesthesia. 2019 Feb;33(2):511–20. 
