# Immune Thrombocytopaenic Purpura

:::info
Also known as idiopathic thrombocytopaenic purpura.
:::

Autoimmune destruction of platelets by the monocyte-macrophage system (predominantly in the spleen), divided into:

* Primary ITP\
No inciting cause.
* Secondary ITP


## Epidemiology and Risk Factors

## Pathophysiology

### Aetiology

## Clinical Features

* Mucocutaneous bleeding

## Assessment

**History**:

**Exam**:

### Investigations

**Bedside**:

**Laboratory**:

**Imaging**:

**Other**:

### Diagnostic Approach and DDx

Diagnosis of exclusion, requires:

* Isolated thrombocytopaenia
* No other underlying cause

## Management

:::priority
* **Corticosteroids**
* Consideration of **splenectomy**
* Achieve a safe (rather than normal) platelet count
:::

**Resuscitation**:

**Specific therapy**:

* Pharmacological
	* Dexamethasone 40mg daily for 4 days\
	Indicated for:
		* Severe thrombocytopaenia\
		<10×10^9^/L.
		* Uncontrolled bleeding
	* IVIG\
	Major bleeding not responding to corticosteroids.
	* Thrombopoietin receptor agonists
		* Romiplostim
		* Eltrombopag
	* MAB
		* Rituximab
* Procedural
	* Splenectomy
* Physical

**Supportive care**:

**Disposition**:

**Preventative**:


### Marginal and Ineffective Therapies

## Anaesthetic Considerations

## Complications

## Prognosis

## Key Studies


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.
1. Kappler S, Ronan-Bentle S, Graham A. [Thrombotic Microangiopathies (TTP, HUS, HELLP)](https://www.sciencedirect.com/science/article/pii/S0733862714000327). Emergency Medicine Clinics of North America. 2014;32(3):649-671. doi:10.1016/j.emc.2014.04.008