# Sickle Cell


Congenital haemoglobinopathy leading to production of **relatively insoluble haemoglobin S** which causes erythrocytes to adopt a 'sickle' shape, and leads to:

* Vaso-occlusion and haemolysis
	* Pain due to microvascular obstruction
	* Progressive multiorgan dysfunction due to ischaemia

## Epidemiology and Risk Factors

## Pathophysiology

Autosomal recessive:

* Homozyogotes have **sickle cell disease**
	* Chronic haemolytic anaemia
	* Recurrent vaso-occlusion and severe pain
	* Progressive organ damage
	* Early death
* Heterozygotes have **sickle cell trait**
	* Results in HbS levels of ~30-40%
	* HbS may precipitate in conditions of physiologic stress


### Aetiology

## Clinical Manifestations

Sickle Cell Disease:

* Failure to thrive
* Often frequent hospital admissions
* Multiorgan failure
	* Pulmonary hypertension  
	Recurrent pulmonary infarction.
	* Cardiac failure
	* Functional asplenism  
	Consequential lymphoid hypertrophy.
	* TIAs/CVAs


Sickle Cell Trait:

* Usually well

## Diagnostic Approach and DDx

## Investigations

Sickledex test:

* Rapid screening
* Qualitative detection of HbS levels >10%

Haemoglobin electrophoresis:

* Definitive diagnostic 

Blood film:

* Sickle forms
* Reticulocytosis

## Management

Prevention:

* Avoid dehydration
	* Exercise
	* Hot weather
	* Alcohol
* Folic acid supplementation
* Hydroxyurea  
↑ HbF formation, and so reduces frequency and severity of vaso-occlusive crises.


Therapeutic:

* Bone marrow transplantation  
Usually restricted to <16 year olds.

Other:

* Vaccination if asplenic
*

### Medical

### Surgical

### Anaesthetic Considerations

* B
	* PHTN
	* Avoid:
		* Hypoxia
		* Acidosis
		* Hypercapnoea
* C
	* CCF
	* Volume state
		* Minimise fasting period
		* Preoperative hydration
	* Avoid venous stasis
* E
	* Tourniquet use
		* May precipitate sickle crisis distal to tourniquet  
		* Careful exsanguination of distal limb prior to inflation
* H
	* Sickle cell severity
		* Frequency of exacerbations
	* Hb
		* Should be transfused to Hb >10g/dL or HbS <30%



### Ineffective Therapies

## Complications

## Prognosis

## Key Studies


---

## References

1. Wilson M, Forsyth P, Whiteside J. Haemoglobinopathy and sickle cell disease. Contin Educ Anaesth Crit Care Pain. 2010;10(1):24-28. doi:10.1093/bjaceaccp/mkp038

