# Thrombotic Thrombocytopenic Purpura

Potentially life-threatening MAHA due to small vessel platelet microthrombi, caused by severe deficiency in the ADAMTS13 protein.

## Epidemiology and Risk Factors

## Pathophysiology

### Aetiology

## Clinical Features

Pentad of:

* Thrombocytopaenia
* MAHA
* Fever
* Renal dysfunction
* Neurological abnormalities


Other features include:

* Hepatic dysfunction
* Pulmonary dysfunction 

## Assessment

**History**:

**Exam**:

### Investigations

**Bedside**:

**Laboratory**:

**Imaging**:

**Other**:

### Diagnostic Approach and DDx


## Management

:::priority
Goals of management
:::

**Resuscitation**:

**Specific therapy**:

* Pharmacological
* Procedural
* Physical

**Supportive care**:

**Disposition**:

**Preventative**:


### Marginal and Ineffective Therapies

## Anaesthetic Considerations

## Complications

## Prognosis

* Mortality of 90% without plasma exchange

## Key Studies


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.