# von Willebrand Disease

von Willebrand Disease is a family of bleeding disorders caused by abnormal von Willebrand factor, and classified by cause into:

* **Congenital**\
Further divided into **three** subtypes:
	* **Type 1**\
	*Quant*itative reduction in normal vWF.
		* Mild clinical symptoms
		* Usually autosomal dominant
		* ~75% of patients
	* **Type 2**\
	Primarily ***qual*itative** defect.
		* 4 subtypes with varying degrees of severity
		* Autosomal dominant or recessive
	* **Type 3**\
	*Absence* of vWF.
		* Severe clinical bleeding
		* Autosomal recessive
* **Acquired**


## Epidemiology and Risk Factors

Most common hereditary bleeding disorder:

* Prevalence is ~1% worldwide\
However, only ~1% of these patients will display symptoms.


## Pathophysiology

von Willebrand factor is a large glycoprotein that:

* Acts as the **carrier protein** for **factor VIII**
* Is required for **platelet adhesion**\
Provides an adhesive bridge from platelet to damaged subendothelium.


### Aetiology

Causes of acquired vWD:

* Malignant 
	* Lymphoproliferative disease
	* Myeloproliferative neoplasms
	* Wilms tumour
	* Carcinomas
* Immune
	* SLE
* Vascular flow\
Shear stress on vWF multimers ↑ susceptibility to cleavage by ADAMTS13.
	* AS
	* LVAD/ECMO
	* MV prolapse
	* Congenital heart disease
	* Toxins
		* Valproic acid
		* Ciprofloxacin
	* Other
		* Hypothyroidism


## Clinical Features

Bleeding:

* Mucocutaneous bleeding most common\
	* Dental procedures
* Minor surgery
	* Circumcision
* Menorrhagia
* PPH\
Usually secondary.

## Assessment

**History**:

**Exam**:

### Investigations

**Bedside**:

**Laboratory**:

**Imaging**:

**Other**:


## Diagnostic Approach and DDx

## Investigations

:::caution
Majority of patients will have normal FBE and coagulation studies
:::

**Laboratory**:

* Blood
	* FBE
		* Thrombocytopaenia\
		Mild may be seen in type 2B.
	* Coag
		* **Prolonged APTT**\
		Abnormality depends on degree of factor VIII deficiency.
	* vWF level
	* Factor VIII level
	* Specialised testing\
	Distinguish subtypes of type II:
		* Ristocetin co-factor activity
		* VWF collagen binding


## Management

:::priority
* Clot stabilisation
* Replenish vWF and factor VIII levels
* Platelet transfusion
:::

:::column-margin
Utility of DDAVP depends on type - if unknown then begin empirically with **vWF concentrate**.
:::

**Specific therapy**:

* Pharmacological
	* **Clot stabilisation**\
		* Antifibrinolytics (**TXA**)\
		Effective independent of aetiology of defect.
	* **Replenish vWF and factor VIII**
		* ↑ Native secretion
			* DDAVP\
			Causes release of vWF from endothelial storage sites. Therefore:
				* Usually **effective in type 1**
				* Occasionally effective in type 2
				* Never effective in type 3
		* Exogenous factor replacement
			* vWF/FVIII concentrates
	* **Platelet transfusions**
	* Refractory bleeding
		* Consider FVIIa
		* Consider IVIG\
		May be effective if due to anti-vWF autoantibodies, particularly if immune-acquired disease.
* Procedural
* Physical

:::column-margin
{{< include /includes/ddavp.qmd >}}
:::

**Supportive care**:

**Disposition**:

**Preventative**:


### Anaesthetic Considerations

### Marginal and Ineffective Therapies

## Complications

## Prognosis

## Key Studies


---

## References
