# Perioperative Management of Implantable Cardiac Devices

:::info
Key questions:

* What is the EMI risk of the surgery?
* How dependent is the patient?
:::

Implantable cardiac devices include:

* **Pacemakers**  
Generate an electrical impulse to stimulate myocardial contraction. Used for:
	* Bradycardias\
	* Anti-tachycardia therapy
	* Resynchronisation therapy
* **Defibrillators**  
Used for primary or secondary prevention of VT, in patients with:
	* Severe LV dysfunction
	* Post-MI
	* Sudden cardiac death syndromes
* **Implantable Loop Recorders**  
Diagnostic tool used in recurrent unexplained syncope.

## Risks

Include:

* Electromechanical interference  
External electrical stimuli (e.g. due to diathermy) may interfere with pacemaker function in two ways:
	* Over-sensing  
	The pacemaker interprets EMI as intrinsic activity, and does not pace despite the intrinsic rhythm being inadequate. This:
		* Will result in the underlying rhythm being the actual rhythm  
		Extent of haemodynamic compromise depends on the nature of the underlying rhythm.
	* Under-sensing  
	Pacemaker does not detect intrinsic activity, and paces over an intrinsic rhythm. This:
		* Leads to over-pacing
		* May cause **malignant arrhythmias** as if an R-on-T occurs


## Clinical Manifestations

Includes both:

* Nature of surgery
* Device assessment

### Surgery Assessment

EMI risk of the procedure:

* Electrical
	* Diathermy
		* Particularly unipolar  
		Ensure pad is placed such that current does not run through device.
		* Location  
		Within 15cm is high risk.
	* Evoked potential monitors
	* External defibrillation
	* Radiofrequency ablation
	* ECT
* Magnetic
	* MRI
* Mechanical
	* Shivering
	* Extracorporeal shock-wave lithotripsy
	* Large tidal volumes

### Device Assessment

Evaluation of pacemakers should consider:

* Indication for pacing
* Dependency on pacing  
What proportion of time is the patient actively paced.
	* Underlying cardiac activity on ECG  
	No underlying activity, or a non-perfusing rhythm, is at higher risk.
	* Use of antiarrhythmics
* Pacemaker function and setup
	* Presence of rate-responsive pacing modes  
	Pacemaker detects a certain event (usually motion, implying exertion) and increases paced rate to compensate.
	* Magnet mode effect  
	Usually places the devices into DOO or VOO at a set rate.
	* Last pacing check  
	Within **12 months**.
	* Pacing threshold  
	Amplitude should be at least double the threshold.
	* Lead impedance  
	High impedance suggests damage, excessively low impedance suggests insulation defect.
	* Battery life
* Lead setup
	* Number of leads  
	May be 1, 2, or 3.
	* Biventricular pacing  
	Biventricular pacing is used for cardiac resynchronisation therapy, and suggests the patient has HFrEF. Indicated with LVEF <35% with LBBB and NYHA III/IV despite optimal medical therapy.
	* Unipolar or bipolar leads  
	Unipolar leads are usually present in older models. In a unipolar lead, the lead is the cathode and the device is the anode; whilst a bipolar lead has both anode and cathode. Unipolar leads are associated with more myocardial scarring and increased impedance.


Evaluation of AICDs should consider:

* Last pacing check  
Within **6 months**.
* Indication
* Dependence
	* Shock history
* Magnet mode effect  
Usually disables the ICD.


Investigations:

* ECG
	* Pacing dependency
	* Pacing capture
* CXR
	* Lead placement
	* Number of leads
	* Presence of ICD  
	Identified by use of shock coils on lead and a capacitor in the device.

## Management

Includes:

* [Pre-operative](#Pre-operative)
* [Intra-operative](#Intraoperative)
* [Post-operative](#Post-operative)

### Pre-operative

General measures:

* Measure and correct electrolytes
* Continue prescribed anti-arrhythmics


Consider **re-programming pacemaker functions** if:

* Significant pacemaker dependency and EMI present
* Modes need to be adjusted
	* Rate-responsive modes will be triggered incorrectly:
		* Respiratory rate
		* Accelerometry
	* Sleep/rest mode  
	Fall in HR and CO overnight, if late surgery is planned.
* Augmentation of CO and DO~2~ helpful


Consider **re-programming an AICD** if:

* EMI is expected
* Movement from shock could be hazardous  
Patients who have defibrillation or antitachycardia functions inactivated should be on continuous monitoring with external defibrillation equipment readily available, and have their therapy reactivated prior to discharge.


Consider a **magnet instead of re-programming if**:

* Magnet response present  
Exists in most devices planted after 2000.
* Magnet response known  
Magnet function can be disabled in some Boston Scientific and St. Jude devices.
* Magnet effect is desirable
* Patient is supine
* Magnet can be accessed:
	* Observed
	* Removed in case of arrhythmia


### Intraoperative

Anaesthesia:

* C
	* Avoid precipitants of arrhythmia
		* Hypoxia
		* Hypercapnoea
		* Electrolyte abnormalities
	* Have defibrillation equipment available
	* Consider induction with pads on if high risk  
	Pads should be placed **at least 8cm** from the device.
	* Consider arterial line
	* Consider cardiac output monitor
* D
	* Nerve stimulators can be used if:
		* Distant from the device
		* Stimulus is not parallel to pacemaker circuit
* E
	* Avoid suxamethonium


Surgery:

* Use bipolar diathermy if possible
* If using unipolar diathermy:
	* Ensure the return path does not cross the ICD
	* Use in short (1-2s) bursts
	* Use cutting rather than coagulation
* Have a magnet available


### Post-operative

* Reactivate any disabled functions  
Electrophysiologist should check the patient prior to departure from recovery.
* Check the device if a magnet has been used
	* AICD should be examined by an electrophysiologist to confirm functions have reactivated
	* Resumption of normal pacing function can be checked at bedside with an ECG

---

## References

1. Bryant HC, Roberts PR, Diprose P. Perioperative management of patients with cardiac implantable electronic devices. BJA Educ. 2016;16(11):388-396. doi:10.1093/bjaed/mkw020
2. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.
