# Patient Blood Management {#sec-pbm}

Patient Blood Management describes a set of processes that aim to ↓ unnecessary transfusions by:

:::column-margin
Anaemia is covered in detail under @sec-anaemia.
:::

* Early detection and treatment of anaemia
* Minimising perioperative blood loss
* Improving post-operative tolerance to anaemia

:::column-margin
Transfusion is associated with:

* Mortality:
	* Cardiac and non-cardiac surgery
	* Short-term and 5 year mortality
* Morbidity:
	* ↑ Length of stay
	* ↑ Postoperative infections
	* TRIM
* Cost
:::

## Minimising Perioperative Blood Loss

### Preoperative

* Identifying and managing bleeding list
* Reviewing medications


### Intraoperative:

* Surgical
	* Meticulous haemostasis
	* Topical haemostatics
* Anaesthetic
	* Avoid coagulopathy
		* Temperature ⩾35°C
		* pH ⩾7.2
		* iCa ⩾1mmol/L
	* Anaesthetic blood-sparing techniques\
	Central neuraxial blockade reduces perioperative bleeding, especially in orthopaedics.
	* TXA\
	If EBL ⩾500mL.
	* Cell salvage\
	If EBL ⩾1L.


### Postoperative

* Preventing secondary haemorrhage
* Minimising iatrogenic blood sampling
	* Reduce sample volumes
	* Using continuous sampling lines

## Postoperative Anaemia Tolerance

* Maintain DO~2~
	* Optimise CO
	* Optimise oxygenation and ventilation
	* Use appropriate transfusion thresholds\
		* Hb 70g/dL in patients without underlying cardiac disease
		* Hb 80g/dL in patients with cardiac disease
		* Transfuse smallest volume possible\
		i.e. Single units, if clinically appropriate.
* Minimise excess VO~2~
	* Rapidly treat infections/sepsis



---

## References

1. WHO. [Haemoglobin concentrations for the diagnosis of anaemia and assessment of severity](https://www.who.int/vmnis/indicators/haemoglobin.pdf). 
2. Hughes, R, Khalafallah A, Aras, D. Perioperative iron deficiency anaemia – a review with a regional flavour. ANZCA Blue Book 2015.
3. Thakrar SV, Clevenger B, Mallett S. Patient blood management and perioperative anaemia. BJA Educ. 2017 Jan 1;17(1):28–34. 
