# Peri-Operative Management of Antiplatelet Agents


Effective management of antiplatelet agents requires balancing:

* Thrombus risk  
Indication:
	* Primary prevention  
	* Secondary prevention
	* [PCI](#pci)  
	Aspirin generally should be continued.
	* Carotid Endarterectomy  
	Aspirin generally should be continued.
* Bleeding risk



## Aspirin

> For non-cardiac surgery, excluding carotid endarterectomy, in patients without coronary stents

For **primary prevention**:

* Should be discontinued at least 3 days prior  
Reduces rate of major bleeding.

For secondary prevention:

* Consider discontinuation at least 3 days prior
* Important to restart when the risk of bleeding has passed


## Antiplatelets for Coronary Artery Stents{#pci}

>* Premature cessation of DAPT is the greatest contributor to stent thrombosis  
>	* Cessation increases risk
> 	* Surgery increases risk  
>	Proinflammatory states.
> * Stent thrombosis risk is higher if ACS was the initial indication for PCI (compared with stable CAD)


Stent types:

* **Bare-metal stent** (BMS)  
High rates of early stent thrombosis, but low rates of late and very-late stent thrombosis.
	* Require **DAPT** for **minimum of 4 weeks** and **ideally 6 months**  
	Risk of progressive stent narrowing with early DAPT withdrawal.
	* **Elective surgery** can be **considered one month** after insertion, **provided aspirin** is **continued**
* **Drug-eluting stent** (DES)  
Incorporate an anti-proliferative drug which delays endothelialisation.
	* Two generations of DES exist:
		* First-generation:
			* Include sirolimus and paclitaxel
			* Higher rate of late and very-late stent thrombosis
		* Second-generation
			* Include everolimus and zotarolimus-eluting stents
			* Improved risk profile
			* Very low rates of early, late, and very-late ST  
			Appropriate to use if surgery is expected within 4 weeks of PCI.
	* Require **DAPT** for **minimum of 6 months**  
	High risk of cardiac death due to complete stent thrombosis with early DAPT withdrawal.
	* **Elective surgery** should be performed:
		* Ideally after **6 months**
		* Can be considered after **3-6 months**
* Bioresorbable vascular scaffold (BVS)
	* Potential increased risk of thrombosis
	* Ceasing DAPT **within 3 years of insertion** should be discussed with cardiology


### Perioperative Management

* Assess thrombosis risk
	* Cardiac history
		* Low EF
	* Non-cardiac history
		* CKD  
		eGFR <60ml/min.
		* DM
	* Coronary & stent anatomy
		* ACS as indication
		* Prior stent thrombosis
		* Left mainstem or diffuse multivessel disease
		* ⩾3 stents
		* ⩾3 lesions
		* Bifurcation with 2 stents
		* Total stent length >60mm
		* All vessels stented
* Assess bleeding risk  
High-risk surgeries include:
	* Bronchoscopy
	* Intra-cranial surgery
	* Spine surgery
	* Retinal surgery
	* Prostatectomy
* Adjust medications
	* Cease P2Y~12~ inhibitor:
		* In high or intermediate risk surgery
		* Restart and **reload** after 24-72 hours
	* Continue aspirin if at all possible  
	If ceasing aspirin, discuss with cardiology.


|Drug|When to cease pre-operatively|Re-loading dose|Indications|Other|
|--|--|
|**Clopidogrel**|5 days|300-600mg|Intracranial stents (others are off label), or cardiac stents with high-bleeding risk|Clopidogrel resistance in ~30% of patients due to pharmacogenetic variation|
|**Prasugrel**|7 days|60mg|Recommended for patients at high risk of recurrent ischaemia|Greater risk of bleeding than clopidogrel, fastest time to onset|
|**Ticagrelor**|3-5 days|180mg|Preferred to clopidogrel in patients at low risk of ischaemia|More effective than clopidogrel with similar rate of bleeding|


### Urgent Surgery	

* Discussion with cardiology and haematology
* Consider platelet transfusion



---

## References

1. Carruthers J, Shaw J, Tran H, Kusre S. Guideline: Perioperative Management of Antiplatelet Therapy in Patients with Coronary Artery Stents. The Alfred Hospital, Melbourne. May 2019.
2. Indraratna P, Cao C. New antiplatelet drugs for acute coronary syndrome. Aust Prescr. 2014. doi:10.18773/austprescr.2014.074

