# Perioperative Management


### Respiratory Management

Smoking:

* Cessation prior to OT if possible
	* At least 4 weeks
	* Ideally over 8 weeks
	* Abstaining 24/24 prior may still have benefit

OSA:

* Screen with STOPBANG
* Institution of CPAP pre-operatively if appropriate

### Renal Management

* Identify patients at risk for AKI and aim to mitigate these risk factors
	* Maintain volume state
	* Avoid nephrotoxins
	* Maintain adequate renal perfusion

## Haematological Management

* Identify patients with high bleeding risk
	* History
	* Platelet counts
	* Coagulation assays
* Anaemia\
Defined as Hb < 120 g/L for women and < 130 g/L for men.
	* Iron deficiency anaemia should be treated with IV iron transfusion
	* EPO supplementation should be used pre-operatively when other causes of anaemia are excluded/treated
* TXA should be used in anaemic patients
* Cell salvage should be used for orthopaedic procedures with high anticipated blood loss


---

## References

1. De Hert, S., Staender, S., Fritsch, G., Hinkelbein, J., Afshari, A., Bettelli, G., … Wappler, F. (2018). Pre-operative evaluation of adults undergoing elective noncardiac surgery: Updated guideline from the European Society of Anaesthesiology. European Journal of Anaesthesiology (Vol. 35).