# Post-Operative Nausea and Vomiting


Common and distressing anaesthetic complication that:

* Affects up to 30% of patients
* May prolong PACU stay or require hospital admission  
Significant ↑ in healthcare costs.
* PONV prevention therefore aims to improve patient comfort, throughput, and reduce cost

## Risk Factors

Key patient risk factors:

* Female
* PHx PONV
* PHx motion sickness
* Younger age
* Non-smoker


Anaesthetic risk factors:

* General anaesthesia
* Use of volatile anaesthetics  
Dose dependent.
* Use of nitrous oxide  
Has minimal impact when baseline risk is low.
* Duration of anaesthesia
* Post-operative opioids


Key risk factors in children:

* Surgery ⩾30 minutes
* Age ⩾4 years
* Family history of PONV
* Strabismus surgery


### Risk Scores

Apfel Score:

* Four predictors
	* Female
	* Previous PONV/motion sickness
	* Nonsmoker
	* Use of post-operative opioids
* Scored as:
	* 0-1: Low risk
	* 2: Moderate risk
	* ⩾3: High risk


## Management

Preventative therapy is titrated to risk:

* Low risk  
Nil intervention required.
* Moderate risk  
1 or 2 interventions.
* High risk  
⩾2 interventions.


### Preventative Interventions

Include:

* TIVA
* Regional anaesthesia
* Acupuncture
* Antiemetic prophylaxis
	* 5-HT~3~ antagonists  
	Give at end of surgery.
		* Ondansetron 4-8mg
		* Granisetron 0.3-3mg
	* Corticosteroids  
	Give at induction.
		* Dexamethasone 4mg
	* Butyrophenones
	Give at end of surgery.
		* Droperidol 0.625-1.25mg
	* NK-1 antagonists  
	Give at induction.
		* Aprepitant 40mg PO
	* Transdermal scopolamine  
	Give evening prior to surgery or 2/24 prior.


### Rescue Interventions

> * Treatment should use a different agent to the initial prophylaxis
> * If no prophylaxis given, then initial treatment should be with a 5-HT~3~ antagonist

* Propofol 20mg  
Effective but brief.
* Antiemetic

### Antiemetics

|Drug|Class|Dose|Timing for prophylaxis|
|--|--|
|Ondansetron|5-HT~3~ antagonist|4mg|End of surgery|
|Granisetron|5-HT~3~ antagonist|0.3-3mg|End of surgery|
|Dexamethasone|Corticosteroid|4mg|Induction|
|Droperidol|Butyrophenones|0.625-1.25mg|End of surgery|
|Aprepitant|NK-1 antagonist|40mg PO|Induction|
|Scopolamien|Anticholinergic|2mg patch|Evening prior or 2/24 pre-operatively|

---

## References

1. Gan, Tong J., Pierre Diemunsch, Ashraf S. Habib, Anthony Kovac, Peter Kranke, Tricia A. Meyer, Mehernoor Watcha, et al. ‘Consensus Guidelines for the Management of Postoperative Nausea and Vomiting’: Anesthesia & Analgesia 118, no. 1 (January 2014): 85–113. https://doi.org/10.1213/ANE.0000000000000002.
