# General Anaesthetic for Caesarian Section

*[General principles](luscs.md) of caesarian section and [regional anaesthesia for caesiarian](reg-luscs.md) are covered separately.*

Provision of general anaesthesia for a [caesarian section](/luscs.md).

## Considerations

In addition to [general considerations](luscs.md#considerations), particular considerations for caesarian under general anaesthesia are:

* A
	* Aspiration prophylaxis
	* Airway plan
* D
	* High risk of anaesthetic awareness
		* Reluctance to use opioid for foetal effects
		* Desire to preserve haemodynamic stability
		* Most occur at, or shortly after, induction  
		Multifactorial:
			* Rapid offset of IV agents and slower uptake of volatile in this population  
			Remember to **mind the gap**!
			* Common avoidance of opioid
			* Maximal surgical stimulus occurring immediately post-induction
	* Foetal effects  
	Foetus will be affected by agents.
		* Volatile agents will diffuse across placenta  
		Aim is to **minimise induction-to-delivery time** to reduce the magnitude of this effect.
		* Opioids increase foetal respiratory depression  
		Consider using smaller doses of shorter acting agents.
* O
	* Tocolytic effects of volatile agents  
	Increased risk of bleeding related adverse events without increased transfusion requirement.

## Preparation

* Surgeons scrubbed
* Abdomen prepped and draped

## Induction

* Preoxygenate well
* Perform RSI  
Ensure adequate doses induction agent and relaxant.
	* Thiopentone 5mg/kg
	* Propofol 3-4mg/kg  
	High sympathetic drive - heavier doses tolerated well.
		* *May* be associated with poorer neonatal status, but is commonly used  
	* Relaxant
		* Suxamethonium 1-2mg/kg  
		Additional relaxation should not be required
		* Rocuronium 1.2-2mg/kg
		Remember that **magnesium will prolong duration of action** of non-depolarising agents.
	* Opioid  
	Not necessarily required, but tell the paediatrician that it has been given if used.
		* Alfentanil  
		Reasonable in patients with severe cardiac disease or hypertensive disorders of pregnancy.
		* Remifentanil  
		1μg/kg bolus with intubation, minimal foetal effects.
		* Fentanyl  
		Intubating doses will cause significant foetal effects.
* Intubate  
A slightly smaller tube may make intubation easier and will be adequate to ventilate with.
* Commence ventilation
	* 30% O~2~/70% N~2~O  
	MAC-sparing, thereby reducing tocolytic effects of volatile agent.
		* Make sure to avoid maternal hypoxia, and decraese the FiN~2~O if needed
	* Sevoflurane ~1.5%  
	Use high flows (10L/min) to reach target quickly.
		* Consider overpressuring the volatile, but remember to turn it down again  
		Can be easy to forget in this chaotic situation.


## Maintenance

* Consider changing to TIVA
* Aim low-normal CO~2~
* **Following delivery**
	* Give oxytocin
	* Give analgesia  
		* Paracetamol
		* NSAID
		* Opioid  
		20-30mg IV morphine.
		Opioid, paracetamol, NSAID.
* Consider regional analgesia
	* TAP block
	* Rectus sheath catheters.
* Extubate awake



## Postoperative

* Regular PO analgesia
* PCA
* Follow-up about experience  
	* Often a confusing, stressful time
	* Risk of awareness


## Complications of GA in Caesarian Section

* Awareness  
High risk in obstetric population, and especially CS:
	* Occurs in ~1/670  
	In NAP 5.
	* Multifactorial:
		* High CO  
			* Increased onset/offset of IV agents
			* Decreased onset/offset of volatile agents
		* No premedication
		* Rapid onset of surgical stimulation following induction
		* Increased V~D~
		* Airway difficulty  
		Decreases time to delivery of volatile.
		* Often junior staff, after hours
	* 20% risk of new psychological morbidity following an awareness event


* Failed intubation  
Higher risk in obstetric population.
	* Occurs in ~1/300
	* Major cause of death in obstetric population
	* Anatomical changes
		* Laryngeal oedema
		* Increased breast size
		* Decreased safe apnoea time
			* Increased VO~2~
			* Decreased FRC


* Aspiration  
Increased risk in obstetric population.
	* Major cause of death in obstetric population
	* Occurs in 0.15% of obstetric GAs with unsecured airways
	* 25mls of gastric contents may cause pulmonary complications
	* Multifactorial:
		* Lower gastric pH
		* Increased gastric volume


---

## References

1. Maronge, L., & Bogod, D. (2018). Complications in obstetric anaesthesia. Anaesthesia.
2. Aberdeen Maternity Hospital Anaesthetic Guidelines. Management of Blood Pressure during Caesarean Sections under Spinal Anaesthesia. 2009.
3. Nixon H, Leffert L. [Anesthesia for cesarian delivery](https://www.uptodate.com/contents/anesthesia-for-cesarean-delivery). Post TW, ed. UpToDate. Waltham, MA: UpToDate Inc. http://www.uptodate.com
4. Rollins M, Lucero J. [Overview of anesthetic considerations for Cesarean delivery](https://academic.oup.com/bmb/article/101/1/105/262350). Br Med Bull. 2012;101:105-25. doi: 10.1093/bmb/ldr050. Epub 2012 Jan 4.
5. McGlennan A, Mustafa A. [General anaesthesia for Caesarean section](https://academic.oup.com/bjaed/article/9/5/148/439565). Continuing Education in Anaesthesia Critical Care & Pain, Volume 9, Issue 5, 1 October 2009, Pages 148–151.
6. Chaggar, Rs, and Jp Campbell. ‘The Future of General Anaesthesia in Obstetrics’. BJA Education 17, no. 3 (March 2017): 79–83. https://doi.org/10.1093/bjaed/mkw046.
