# Labour Analgesia

Options for analgesia in labour include:

* Nitrous Oxide
* PCA
* [Epidurals](epi)
* Spinal-Epidural Techniques
	* [Combined-Spinal Epidural](cse)
	* Sequential Spinal Epidural

## Nitrous Oxide



## PCA


## Labour Epidural{#epi}





### Informed Consent During Labour  

Should still be performed, though is made more difficult by the situation. In general:

* Women wish to be involved in the process
* About 30% of information will be retained
* Written consent is not required  
Verbal consent should be documented.
* Talk between contractions if possible
* Involve the birth partner, particularly if contractions are continuous
* Good discussion points include:
    * What will happen  
    The position, what they will feel (e.g. skin local), the need to keep still.
    * Risk of PDPH  
    ~1:100.
    * Risk of failure/inadequate analgesia  
    Replacement required ~1:20.
    * Risk of neurological complications  
    	* Temporary: ~1:5,000
    	* Permanent: ~1:50,000
    	* Paraplegia: ~1:1,000,000
* Consider mentioning:
    * Risk of instrumental delivery
    * Back pain  
    Over next 1-2 days, but not longterm.


### Test and Loading Doses{#test}

The ideal test dose should:

* Identify intrathecal injection
    * Inject small volumes slowly and titrate to effect
* Identify intravascular injection
* Avoid haemodynamic instability
* Give a slower onset of analgesia  
Optimal onset time is 15 minutes. Rapid onset is associated with ↑ uterine tone and foetal bradycardia.


#### A Good Loading Technique

* 5ml 0.2% ropivacaine  
    * If intrathecal, should be associated with warm sensation (as with spinal) and **rapid analgesia**  
    Ask the patient if they have a substantial reduction in pain.
    * Using a higher dose (e.g. 10ml) may also lead to early motor block, excessive sensory block, or hypotension
* 100μg fentanyl
    * If intravascular, should be associated with a potent opioid effect (analgesia, narcosis)
* Further 10-15ml 0.2% ropivacaine  
Titrated to achieve desired block height.


#### Not-so-good Loading Techniques

* 2% lignocaine  
Associated with more motor block.
* Adrenaline  
Heart rate changes with 15-20μg of intravascular adrenaline are not reliably distinguishable from effect of epidural adrenaline, or normal heart rate variability.
* Identify intravascular injection  
Options include:
    * Negative aspiration of blood prior to injection
    * Adrenaline 15μg  
    Neither **sensitive nor specific**, as it is associated with an ↑ in HR by ~30bpm for ~30s if intravascular, and ~20-30bpm if epidural. No respone may be seen in β-blocked patients.


### Maintenance Dosing



### Complications  

*This covers complications unique to the labour epidural. Management of issues of [insertion](/anaesthesia/regional/epidural.md#comp) and [troubleshooting an inadequate or failing epidural](/anaesthesia/regional/epidural-mx.md#comp) are covered elsewhere.*


#### Foetal Distress

Foetal distress after an epidural is common, and may be:

* Direct  
Related to effects of epidural drugs on the foetus, as some will be absorbed by the mother and transferred to the foetus. Effects seen depend on the type of drug, but **are not clinically significant**:
	* Opioid  
	Respiratory depression.
	* LA  
		* Transient reduced variability
* Indirect  
Related to effects on the mother by epidural. Include:
	* Maternal ↓ BP  
	Maternal symptholysis results in reduced uteroplacental perfusion, and foetal ischaemia. Requires correction of BP and [intrauterine resuscitation](/management/obs/intrauterineresus.md).
	* Oxytocin/Adrenaline Imbalance  
	Theory based on the fact that rapid onset of analgesia results in a rapid fall in the circulating (tocolytic) adrenaline, resulting in unopposed oxytocin stimulation and a subsequent fall in uteroplacental perfusion due to the high intrauterine pressure. Notably, foetal distress does not appear to be ↑ with a CSE, despite the more rapid onset of analgesia with this technique.
	* Maternal Positioning  
	Position for epidural *may* result in foetus compressing cord and reducing perfusion.

## Spinal Epidural Techniques

Combination techniques include:

* CSE  
Provision of spinal and epidural anaesthesia using a combination needle technique.
	* Elegant
	* Technically more difficult
	* Excellent technique for a second attempt at an epidural which has failed, despite seeming technically correct at time of the initial insertion
* Sequential spinal and epidural anaesthesia  
Provision of a spinal anaesthetic, followed by an epidural anaesthetic.
	* Excellent technique for provision of analgesia in a woman who is unable to maintain a safe position for insertion of an epidural during labour
	* Spinal anaesthesia (through a spinal needle) removes the risk of inadvertent dural puncture  
	Once intrathecal analgesia has taken effect, an epidural can be performed under safer conditions.


### Combined Spinal Epidural in Labour{#cse}

The CSE technique has both:

* Pros
	* Faster onset of better analgesia  
	~5 minutes.
	* Greater sacral block  
	May be beneficial particularly in late labour.
	* No additional motor block
	* No ↑ in complications relating to:  
	PDPH, instrumental delivery, or caesarian section rate.
	* Potentially more reliable epidural catheter rate  
	Visualisation of CSF from spinal needle confirms correct position.
* Cons
	* Greater **technical difficulty**
	* Untested epidural catheter  
	Epidural catheter is traditionally not loaded at time of intrathecal delivery.
		* Should be tested by anaesthesia provider once intrathecal component has worn off
	* Cost


#### Intrathecal Dosing

In general:

* Plain solutions spread better than heavy solutions
* Opioid alone may be used in early labour to minimise motor block
* 1-5-5mg of bupivacaine is a reasonable dose
* Drugs used will depend on institutional practice and availability

Suggested dosing regimes:

* 0.5ml of 0.5% **plain** bupivacaine with 25μg of fentanyl and 1ml of 0.9% saline  
Total volume 2ml.
* 1-2ml of 0.2% ropivacaine with 15-25μg of fentanyl  

---

## References

