# Anaesthesia for Non-Obstetric Surgery in the Obstetric Patient

> The Bottom Line:
>* Miscarriage is a complication but rarely due to anaesthesia
>* Principles of intrauterine resuscitation apply
>* General considerations for the obstetric patient apply
>* Consider antenatal steroids
>* Perioperative foetal monitoring required for all pregnancies, but intraoperative only if the pregnancy is viable and the operation could be paused to facilitate caesarian delivery


Approximately **2%** of pregnant women will undergo surgery for **non-obstetric indications**. Key considerations are:

* Maternal
	* Physiological changes
* Foetal
	* Maintaining a permissive intrauterine environment  
	Avoiding:
		* Hypotension
		* Hypoxia
		* Hyper/hypocapnoea
	* Placental transfer of drugs
	* Miscarriage  
	Predominantly due to risk of surgery and concomitant inflammatory response, rather than any direct effect of anaesthesia.
	* Pre-term delivery


## Preoperative

**Assessment:**
* Indication for surgery and inherent risk to foetus  
Most common including:
	* Appendicitis
	* Cholecystitis
	* Trauma
	* Maternal malignancy
* Gestational age


**Consultation:**
* Obstetric team
* Paediatrician if pre-term labour anticipated


**Optimisation:**
* Operation should occur at centre that is:
	* Capable of performing a delivery if delivery indicated
	* Capable of looking after child post-delivery (e.g. PICU/NICU, depending on gestational age)


**Premedication:**
* Consideration of antenatal glucocorticoids if pre-term delivery likely


**Explain/Consent:**
* Risk of miscarriage  
Increases with lower gestational age and conditions associated with **local inflammation**.
	* Overall ~6%, though up to 10% in **first trimester**
	* Second trimester preferred for semi-elective surgery
	* Elective surgery should be postponed until postpartum
	* **Pregnancy is never a contraindication** to urgent surgery


## Intraoperative

**Preparation:**
* Regional anaesthesia preferred where feasible, though this lacks evidence
	* Minimises foetal drug exposure
* Consideration of **CTG monitoring**
	* Should be considered in a **viable pregnancy**, i.e. if the use of the monitor would change management  
	Note that **loss of foetal heart rate variability** is **normal in the context of anaesthesia**.
	* Continuous monitoring preferable provided:
		* Technically possible with surgery
		* Surgery can be interrupted to deliver a distressed foetus
	* Prior to viability, doppler monitoring pre- and post-operatively can be used to confirm foetal wellbeing


**Induction:**
* Use a **wedge** to prevent **aorto-caval compression after 20 weeks**  
May be required earlier if polyhydramnios or multiple pregnancy.
* Other [obstetric considerations](/anaesthesia/obs/obs-principles.md#id), depending on degree of gestation


**Maintenance:**
* Drug considerations
	* N<sub>2</sub>O  
	Avoid in first trimester, may be teratogenic.
	* NSAIDs  
	Avoid after 28 weeks due to concern about premature ductus closure.


## Postoperative

**Referrals/Review:**
* Foetal monitoring must be performed in the recovery room:
	* Continuously for viable foetuses
	* Intermittently for non-viable foetuses


**Thromboprophylaxis:**
* All pregnant patients are high risk and both mechanical and pharmacological prophylaxis should be employed



---

## References

1. Nejdlova M, Johnson T. Anaesthesia for non-obstetric procedures during pregnancy. Contin Educ Anaesth Crit Care Pain. 2012;12(4):203-206. doi:10.1093/bjaceaccp/mks022
2. Practice Guidelines for Obstetric Anesthesia: An Updated Report by the American Society of Anesthesiologists Task Force on Obstetric Anesthesia and the Society for Obstetric Anesthesia and Perinatology. Anesthesiology 2016;124(2):270–300.
3. Nonobstetric Surgery During Pregnancy – ACOG [Internet]. [cited 2019 Jul 18];Available from: https://www.acog.org/Clinical-Guidance-and-Publications/Committee-Opinions/Committee-on-Obstetric-Practice/Nonobstetric-Surgery-During-Pregnancy?IsMobileSet=false
4. Tolcher MC, Fisher WE, Clark SL. Nonobstetric Surgery During Pregnancy. ObstetGynecol 2018;132(2):395–403.