# Anaesthesia for Postpartum Haemorrhage

*A broad overview of the anaesthetic management of [PPH](/disease/obs/pph.md); including vaginal tract trauma, evacuation of retained products, and emergency hysterectomy.*

>Airway: ETT RSI (if GA), or spontaneous ventilation
>Access: At least 1x18G
>Pain: Hysterectomy may be substantial
>Position: Supine lithotomy
>Time: 20 minutes - 3 hours
>Blood loss: Mild to **substantial**, G+H required
>Special: Oxytocics commonly required

Anaesthetic and surgical management depends on the **cause** and **extent** of blood loss. Causes of PPH include:

* Tone  
In ascending order:
	* Uterotonic therapy
	* Uterine massage/bimanual compression
	* Balloon tamponade/uterine packing
	* Uterine artery embolisation  
	Requires interventional radiology.
	* Uterine compression sutures
	* Iliac artery ligation
	* Uterine devascularisation
	* Hysterectomy
		* Supracervical
		* Total hysterectomy
* Tissue  
Retained products of conception; i.e. **incomplete placenta**.
	* If regional technique used, a block to **T4** is required
	* Tocolysis may be required
		* GTN 100-200μg IV
		* GTN 400μg SL
		* Volatile anaesthetic agents
* Trauma  
Vaginal tract or cervical trauma.
	* Usually amenable to primary repair
	* *Very* superficial lacerations may be repaired on labour ward
	* Laparotomy rarely required if cervical laceration extends into lower uterine segment
* Thrombin (Coagulopathy)  
Rare, but causes include:
	* Congenital coaguolpathies
	* Acquired coagulopathies  
		* [Pre-eclampsia](/disease/obs/htn.md)
		* Placental abruption
		* DIC

## Considerations

*General anaesthetic considerations of the obstetric patient are covered [here](/anaesthesia/obs/principles.md).*

* A
	* Airway oedema will linger post-partum
* C
	* Aortocaval compression resolved upon foetal delivery
	* **Haemodyamic state**  
	**Key consideration for GA vs. regional technique:**
		* GA offers ↑ haemodynamic stability and is the preferred option in an unstable/undervolumed patient  
		Spinal generally lower risk and facilitates early post-operative breast feeding.
		* Resuscitate with IVT and blood prior
* G
	* Aspiration risk remains
* O
	* Malplacentation  
	Note presence of:
		* Placenta accreta
		* Placenta praevia
		* Uterine rupture
		* Uterine inversion

## Induction

Will vary depending on technique:

* Spinal
	* For vaginal tract repair **without** retained products  
	A **block to ~T10** is required. Consider:
		* 1.5ml of 0.5% heavy bupivacaine with 15μg fentanyl
	* For retained products/when the uterine cavity is instrumented  
	A **block to T4 is required**. Consider:
		* 2.2ml of 0.5% heavy bupivacaine with 15μg of fentanyl  
		Standard obstetric spinal, without a requirement for long-acting opioid.
* Epidural top-up
	* 10-15ml of 2% lignocaine with adrenaline and 50-100μg of fentanyl
* GA
	* Standard RSI for induction  
	Consider ketamine ~1.5mg/kg if haemodynamic state is unfavourable.


## Postoperative

Complications include:

* Surgical complications
	* Uterovaginal fistula
	* Vesicovaginal fistula
* Haemorrhagic complications
	* Sheehan's syndrome
	* DIC
* Wound infection

---

## References

