# Obstetric Terms


*This section covers obstetric terms, procedures, acronyms, and conditions which are too small to have their own page, but are of relevance to the practice of obstetric anaesthesia and critical care.*

## Abortion - AB

Usually understood by patients to refer to an **elective** termination of pregnancy. Non-elective abortions are covered under [miscarriage](#mis)

## Anteflexed - AF

*See [anteverted](#anteverted)*.

## Amniotic Fluid Index - AFI {#afi}

Estimate of uterine amniotic fluid volume:

* Indicator of foetal well-being.
* Normal is 5-25cm
	* Begins to reduce after 35/40
	* [Oligohydramnios](#oligo) is < 5cm
	* [Polyhydramnios](#poly) is >25cm

## Alpha-foetal protein - AFP

Maternal blood test used to evaluate for presence of foetal birth defects. AFP is:

* Produced in foetal liver
* Elevated in:
	* Neural tube defects
	* Abdominal wall defects
	* Abnormal placentation

## Advanced Maternal Age - AMA

Pregnancy in woman over 35. Associated with increased risk of obstetric complications, including:

* Placental abruption
* Placenta praevia
* Malposition
* Low Birth Weight
* Preterm Delivery
* Post-dates delivery
* PPH
* Requirement for IVF
	* Subsequent increased risk of multiple pregnancy (due to IVF) amplifies some of the above risks

## Artificial Rupture of Membranes - AROM {#arom}

Deliberate breaking of amniotic membranes surrounding foetus. AROM:

* Also known as amniotomy
* Indications include:
	* Induce or augment labour  
	With or without oxytocin infusion.
	* Perform foetal measurements
		* Apply foetal scalp electrode
		* Measure foetal lactate/pH
	* Assess composition of liquor in presence of abnormal [FHR](#fhr)
* Benefits:
	* Reduced length of labour
	* Reduced oxytocin requirement  
	For augmented labour.
	* Allow liquor assessment
* Complications:
	* Cord prolapse
	* Rupture of vasa praevia
	* Infection  
	Proportional to number of subsequent VE's.
	* Pain


## Anteverted - AV{#anteverted}

Normal anterior flexion of uterus over bladder.

## Biparietal Diameter - BPD

Ultrasonographic measurement of foetal head width, used to produce an estimate of foetal weight and subsequently gestational age.

## Bilateral Salpingo-oophorectomy - BSO

Removal of both ovaries and fallopian tubes.

## Biophysical Profile - BPP

Prenatal ultrasound evaluation of foetal well-being. Evaluates:

* [FHR](#FHR)
* Foetal Breathing
* Foetal Movement
* Foetal Tone
* [AFI](#afi)

## Beat-to-beat varibility - BTBV

Short-term variability in foetal heart rate.

## Bilateral Tubal Ligation - BTL ("Beetle")

Permanent technique for female sterilisation.

## Breech Presentation {#breech}

Where the [presenting part](#pp) is the bottom or feet. Breech presentations are:

* Sometimes able to be converted to a cephalic presentation with [ECV](#ecv)
* Safest delivered via caesarian section
* Subdivided into:
	* Frank (extended) breech  
	Feet are next to ears with hips flexed and knees extended.
	* Complete (flexed) breech  
	Foetus is cross-legged.
	* Footling breech  
	One or both feet are the presenting part.

## Cephalopelvic Disproportion - CPD

Mismatch between size of foetal head and maternal pelvis. Results in obstructed labour due to mechanical failure to progress, and commonly leads to caesarian section.

## Cord Prolapse{#cord}

Prolapse of umbilical cord through an open cervix in advance of the [presenting part](#pp). Cord prolapse:

* May lead to rapid foetal ischaemia and death - this is an **obstetric emergency** 
Requires rapid intervention and commonly operative delivery. Broadly, management consists of:
	* Minimising cord impingement
		* Replacing cord into vagina
		* Elevating the presenting part  
		* Tocolysis
	* Assisted vaginal birth may be considered if cervix is dilated and presenting part is engaged
	* Emergency [caesarian section](/anaesthesia/obs/luscs.md) is required if foetus is viable and unable to deliver vaginally.
* Occurs in 0.2-0.4% of births  
About half are iatrogenic, due to:
	* [AROM](#arom)
	* [ECV](#ecv)
	* Insertion of intrauterine pressure monitor
* Risk factors include:
	* Malpresentation
	* LBW
	* Multiple pregnancy
	* Multiparity
	* [Polyhydramnios](#poly)
	* Prematurity
	* Pelvic tumours
	* Abnormally long umbilical cord
* Differs from:
	* Umbilical cord presentation  
	Umbilical cord lies in front of the presenting part, but the membranes are intact.
	* Occult umbilical cord prolapse  
	Cord lies trapped beside the presenting part.

## Cartiotocograph - CTG

Electronic measurement of foetal heart rate and uterine tone.

## Contractions

Tightening and shorterning of uterine muscle, causing the cervix to shorten and foetus to move into the birth canal. Key terms:

* Number of contractions  
Quantified as number per 10 minutes, e.g. 4:10.
	* Tachysystole is >5:10  
	May be associated with increased foetal acidosis, and is associated with placental abruption.
* Duration  
Time in seconds from onset to offset.
* Relaxation time  
Time in minutes and seconds between contractions.
* Resting tone  
Intrauterine pressure during relaxation.
	* Qualified as 'soft' or 'firm'
	* Quantified in mmHg if transduced directly
* Strength/intensity  
Intrauterine pressure during contaction.
	* Qualified as 'mild', 'moderate', or 'strong'
	* Quantified as peak pressure in mmHg if transduced directly

## Dilation{#dilation}

First stage of labour is defined by extent (in cm) of cervical dilation, and is divided into:

* Latent phase  
Softening and shortening of cervix. Occurs from 0-3cm.
* Active phase  
Active labour from 3-10cm. Contractions become more active and dilation continues at 0.5-1cm/hr.

## External Cephalic Version - ECV {#ecv}

External rotation of foetus in the womb to a cephalic presentation. ECG is:

* Associated with risks of:
	* ROM
	* APH
	* Failure
* Contraindicated when:
	* Caesarian section required for other reasons
	* APH occurred in last 7/7
	* CTG is abnormal
	* Major uterine abnormality
	* ROM
	* Multiple presentation

## External Foetal Monitoring - EFM

*See [CTG].

## Estimated Gestational Age - EGA

Measure of age of pregnancy in weeks, i.e. x/40. May be calculated from:

* Days since last menstrual period
* Size of foetus on early obstetric ultrasound
* Days since oocyte retrieval (if IVF)

## Foetal Death in Utero - FDIU {#fdiu}

Death occurring after point of viability, usually 20 weeks.

## Group B Strep - GBS

Bacteria which commonly colonises maternal vagina. GBS colonisation:

* Increases risk of:
	* Preterm labour
	* PROM
	* Chorioamnionitis
	* Neonatal infection  
	5% mortality from:
		* Pneumonia
		* Sepsis
		* Meningitis
* Identified with routine antenatal culture
* Treated with IV antibiotics during labour

## Gestational diabetes - GDM

Diabetes that occurs during pregnancy. GDM:

* Occurs in ~10% of Australian Pregnancies
* Usually resolves following the pregnancy
* Increases risks of:
	* Pre-eclapsia
	* HTN
	* Premature labour
	* Macrosomia
	* IUGR
	* Caesarian section
* Treatment includes:
	* Insulin  
	First line treatment as it does not cross the placenta.
	


## Gravida and Parity

Summary of obstetric history:

* Gravida  
Number of pregnancies. NB:
	* Includes curent pregnancy
	* A twin pregnancy counts as 1
* Parity  
Pregnancy carried to >20 weeks.

Related terms:

* Nulligravida  
Woman who has never been pregnant.
* Primigravida  
Woman with her first pregnancy.
* Multigravida  
Woman who has had multiple pregnancies.
* Nulliparous  
Woman who has never delivered.
* Primiparous  
Woman who has delivered once.
* Multiparous  
Woman who has had multiple deliveries.
* Grand multipara  
Woman who has had 5 or more deliveries.

## Hydrops Foetalis  

Abnormal accumulation of fluid:

* With at least two of:
	* Subcutaneous oedema
	* Ascites
	* Pleural effusion
	* Pericardial effusion
* Classified into:
	* Immune  
	10-20% of cases.
		* [Rhesus isoimmunisation](#rhesus)  
		High-output cardiac failure secondary to anaemia.
	* Non-immune:  
		* Cardiac failure
		* Venous obstruction
		* Lymphatic obstruction
		* Decreased oncotic pressure


## Intrauterine Foetal Demise - IUFD

*See [FDIU](#FDIU).


## Intrauterine Growth Restriction - IUGR {#iugr}

Estimated foetal weight that is **under the 10^th^ centile** on ultrasound:

* Does not imply pathology  
May be normal, but also associated with:
	* Uteroplacental insufficiency  
	In turn associated with **severe preeclampsia**, which requires monitoring.
	* ntepartum stillbirth
	* Preterm delivery
* Generally requires increased surveillance
* May require early delivery for foetal or maternal reasons

## Internal Foetal Monitoring

Describes foetal scalp pH and lactate electrodes, providing indications of foetal ischaemia and influence obstetric decision making around urgency of caesarian section.

## Low Birth Weight - LBW

Defined as birth weight < **2500g**. Related terms include:

* Very low birth weight (VLBW)  
Weight < 1500g.
* Extremely low birth weight (ELBW)  
Weight < 1000g.

## Kleihauer-Betke Test

Quantitative assessment of volume of foetomaternal haemorrhage, used both to diagnose the presence of foetal-maternal blood transfer and determine the dose of anti-D required in an Rh- mother. The Kleihauer test:

* Measures foetal hameoglobin
* Has poor sensitivity and reproducibility
* Tends to overestimate haemorrhage
* Cannot identify the source foetal haemoglobin
Most inaccurate during 2^nd^ trimester when maternal HbF is high

## Last Menstrual Perioid - LMP

Time of last menstrual period, used as a surrogate marker for when conception occured; usually 14 days after LMP.

## Miscarriage{#mis}

Collection of terms, including:

* Complete miscarriage  
Return to normal uterine size following passage of all products of conception. 
* Inevitable Miscarriage  
Heavy vaginal bleeding with an open cervix and passage of products of conception.
* Incomplete Miscarriage  
Failure to pass all products of conception.
	* May require evacuation 
	*Usually* requires **GA**. Blood loss may be substantial.
* Threatened Miscarriage  
Vaginal bleeding at < 20/40, in presence of a **viable foetus**. Threatened miscarriage is:
	* First symptom of pregnancy in ~20%
	* Suggested by small volume blood loss, minimal pain, a closed cervix, and presence of foetal heart sounds
	* Managed with bed rest and anti-D
	* Associated with increased risk of complete miscarriage
* Missed miscarriage
Spontaneous abortion with the absence of vaginal bleeding, see [FDIU](#FDIU)
	* Requires evacuation of products of conception
* Septic Miscarriage  
Infection of retained products following an incomplete miscarriage.
	* Suggested by pain, fever, discharge from an open cervix
	* Requires cultures, antibiotics, resuscitation, and D&C


## Nucal Cord

Where umbilical cord wraps around the foetal neck.

## Oligohydramnios{#oligo}

Where amniotic fluid volume is less than expected for gestational age. Oligohydramnios:

* Occurs in ~6% of pregnancies
* Causes include:
	* [FDIU](#fdiu)
	* Renal abnormalities  
	Decreased foetal urine output.
	* [IUGR](#iugr)
	* [PROM](#prom)
	* [Post-dates](#pd)
	* Chromosomal abnormalities


## Pregnancy Induced Hypertension (PIH)

*See [hypertension of pregnancy](/disease/obs/htn.md).

## Presentations {#presentations}

Position that the foetus sits in the birth canal. Includes:>
* Cephalic  
Normal, head-first. Includes:
	* Occiput Anterior (OA)  
	Includes left occiput anterior (LOA) and right occiput anterior (ROA).
	* Occiput Posterior (OP)  
	Includes left occiput posterior (LOP) and right occiput posterior (ROP).
	* Occiput Transverse  
	Includes left occiput transverse (LOT) and right occiput transverse (ROT).
* [Breech](#breech)
* Shoulder

## Polyhydramnios{#poly}

Where amniotic fluid volume is greater than expected for gestational age. Polyhydramnios:

* Occurs in ~1% of pregnancies
* Causes include:
	* Idiopathic  
	Majority.
	* Maternal  
	60-65% of cases.
		* GDM
		* CHF
	* Foetal  
	10-20% of cases.
		* Neural tube defects  
		Majority of foetal causes.
		* Foetal macrosomia
		* Gastrointestinal obstruction  
			* Upper GI atresia
			* Abdominal wall defects
		* Cervical masses
		* Thoracic masses
		* Arrhythmia
		* Twin-twin transfusion
		* Hydrops foetalis


## Presenting Part {#pp}

Refers to which anatomical part of the foetus is closest to the birth canal. *See [presentations](#presentations)*.

## Preterm Premature Rupture of Membranes - PPROM

PROM occurring prior to 37 weeks.

## Premature Rupture of Membranes - PROM

Rupture of the amniotic sac prior to onset of labour. May lead to:

* Foetal:
	* Premature birth
	* Cord compression  
	*See [cord prolapse](#cord).*
	* Infection
* Maternal:
	* Placental abruption  
	*See [PPH](/obstetric/disease/obs/pph.md).*
	* Endometritis

## Preterm labour - PTL

Onset of labour prior to 37 weeks. *See [preterm labour](/disease/obs/preg.md#preterm)*.

## Post-Dates{#pd} - PD

Pregnancy extending past 42 weeks.


## Rhesus

Refers to maternal Rhesus status, either RH(-) or RH(+). This is important as:

* Rh(-) mothers may develop Anti-RH(+) if the foetus is RH(+)  
Due to foetal-maternal transfer of blood.
* May lead to haemolytic disease of the newborn  
Anaemia may be:
	* Mild  
	Observation/phototherapy.
	* Moderate  
	Exchange transfusion.
	* Severe  
	FDIU, [foetal hydrops](#hydrops).


## Rupture of Membranes - ROM {#rom}

Breakage of the amniotic sac, causing amniotic fluid (the 'waters') to leak out of the vagina.


## Small for Gestational Age - SGA

*See [IUGR](#iugr).

## Spontaneous Abortion (SAB)

*See [miscarriage](#mis)*.


## Spontaneous Rupture of Membranes - SROM

Unassisted/normal [ROM](#rom).

## Station{#station}

Describes location of the [presenting part](#pp) of the foetus in reference to the ischial spines. Operative vaginal delivery is not recommended at negative station, i.e. when the presenting part is above the ischial spines.

## Termination of Pregnancy - TOP

Use of medication or surgery to end a pregnancy.

## Trial of Labour After Caesarian Section (TOLAC)

Attempting normal vaginal delivery after previous caesarian. TOLAC is associated with:

* Increased risk of **uterine rupture**
* Re-do caesarian rate of ~50%

## Vaginal Birth After Caesarian Section - VBAC

Successful vaginal delivery after previous caesarian.

## Vasa Praevia  

Where foetal vessels within the amniotic membrane cover or are close to the internal cervical os. May lead to foetal death due to hypovolamic shock if foetal vessels rupture when [ROM](#rom) occurs.

## Vaginal Delivery

Birth via the vagina. Related terms include:

* Spontaneous Vaginal Delivery (SVD)  
Labor and delivery achieved without induction, assisted, or caesarian.
* Induced Vaginal Delivery  
Artificial induction of labor, *see [induction of labour](/disease/obstetrics/preg.md#induction)*.
* Normal Vaginal Delivery (NVD)
Vaginal delivery without caesarian.
* Assited/Instrumented Vaginal Delivery (AVD)  
Vaginal delivery

## Vaginal Examination - VE

Internal examination performed to assess [dilation](#dilation), [station](#station), and [presentation](#presentations).

---

## References

1. Bell DJ, Weerakkody Y. [Amniotic Fluid Index](https://radiopaedia.org/articles/amniotic-fluid-index). Radiopaedia. 2018.
2. Lau A, Refaey M. [Polyhydramnios](https://radiopaedia.org/articles/polyhydramnios?lang=gb). Radiopaedia. 2018.
3. Khoshnaw KT, Refaey M. [Oligohydramnios](https://radiopaedia.org/articles/oligohydramnios?lang=gb). Radiopaedia. 2018.
4. Smith GC, Shah I, Crossley JA, Aitken DA, Pell JP, Nelson SM, Cameron AD,
Connor MJ, Dobbie R. [Pregnancy-associated plasma protein A and alpha-fetoprotein 
and prediction of adverse perinatal outcome](https://www.ncbi.nlm.nih.gov/pubmed/16394054). Obstet Gynecol. 2006
Jan;107(1):161-6.
5. RCOG. [Induction of Labour at Term in Older Mothers](https://www.rcog.org.uk/globalassets/documents/guidelines/scientific-impact-papers/sip_34.pdf). RCOG. 2013.
6. Stanislavsky A. [Biparietal Diameter](https://radiopaedia.org/articles/biparietal-diameter). Radiopaedia. 2016.
7. Maharaj D. [Assessing cephalopelvic disproportion: back to the basics](https://www.ncbi.nlm.nih.gov/pubmed/20633305). Obstet
Gynecol Surv. 2010 Jun;65(6):387-95.
8. King Edward Memorial Hospital. [Clinical Practice Guideline: Cord Prolapse: Umbilical.](https://www.kemh.health.wa.gov.au/~/media/Files/Hospitals/WNHS/For%20health%20professionals/Clinical%20guidelines/OG/WNHS.OG.CordProlapse.pdf). Government of Western Australia North Metropolital Health Service.
9. RANZCOG. [Management of breech presentation at term](https://www.ranzcog.edu.au/RANZCOG_SITE/media/RANZCOG-MEDIA/Women%27s%20Health/Statement%20and%20guidelines/Clinical-Obstetrics/Management-of-breech-presentation-at-term-(C-Obs-11)-Review-July-2016.pdf?ext=.pdf). RANZCOG. 2001.
10. Department of Health. [Pregnancy Care Guidelines; Part F: Routine Maternal Health Tests 39: Group B Streptococcus](https://beta.health.gov.au/resources/pregnancy-care-guidelines/part-f-routine-maternal-health-tests/group-b-streptococcus). Australian Government. 2018.
11. Nankervis A, Price S, Conn J. [Gestational diabetes mellitus: A pragmatic
approach to diagnosis and management](https://www1.racgp.org.au/ajgp/2018/july/gestational-diabetes-mellitus). Aust J Gen Pract. 2018 Jul;47(7):445-449.
12. Lausman A, Kingdom J; MATERNAL FETAL MEDICINE COMMITTEE. [Intrauterine growth restriction: screening, diagnosis, and management](https://www.jogc.com/article/S1701-2163(15)30865-3/fulltext). J Obstet Gynaecol Can. 2013 Aug;35(8):741-748. doi: 10.1016/S1701-2163(15)30865-3.
13. Perinatology. [Hydrops Fetalis](http://perinatology.com/conditions/Hydrops.htm). Perinatology. 2015.
14. RANZCOG. [Vasa praevia](https://www.ranzcog.edu.au/RANZCOG_SITE/media/RANZCOG-MEDIA/Women's%20Health/Statement%20and%20guidelines/Clinical-Obstetrics/Vasa-praevia-(C-Obs-47)-Review-July-2016.pdf?ext=.pdf). RANZCOG. 2016.
15. Garite TJ, Simpson KR. [Intrauterine resuscitation during labor](https://www.ncbi.nlm.nih.gov/pubmed/21278499). Clin Obstet Gynecol. 2011 Mar;54(1):28-39.
16. Callum J, Barrett J. [Kleihauer-Betke Test](https://www.sciencedirect.com/topics/medicine-and-dentistry/kleihauer-betke-test). Blood Banking and Transfusion Medicine: Basic Principles & Practice. 2^nd^ Ed. 2007.
