# Gender Equity


Gender equity has substantial ethical, social, and economic benefits to society. ANZCA recognises that fellows should have equal opportunity, irrespective of gender. The position statement outlines **five focus areas**:

* Inclusive and equitable culture
* Diverse and representative workforce
* Flexible and empowering workspace
* Attention to gaps
* Strategic and accountable leadership

## Inequity

Inequity:

* Affects people of all genders
* Occurs due to interplay of may factors:
	* Cultural  
	Gender stereotyping leading to:
		* Unintentional exclusion and loss of opportunities
		* Selection and advancement based on factors other than merit
	* Structural  
	Governance processes that unintentionally discriminate based upon gender.
	* Behavioural  
	Gender-based differences in behaviour predominantly disadvantage women.
	* Personal
	* Inertia  
	Failure to act perpetuates inequality.
* Impact is cumulative


---

## References

1. ANZCA. [Gender Equity Position Statement: Version 1](http://www.anzca.edu.au/about-anzca/gender-equity). Feb 2019.