# Handover Responsibilities of the Anaesthetist


Handover may occur:

* During anaesthesia  
May be:
	* Temporary
	* Permanent
* After anaesthesia  
To PACU or HDU/ICU.

The anaesthetist remains responsible for patient care:

* Whilst the patient is in the recovery room
* Until the patient has been handed over to another suitably qualified medical practitioner

## Handover During Anaesthesia  

Principles:

* Relieving anaesthetist must be competent to manage the patient
* Patient should be clinically stable  
* All relevant factors should be explained  
Including:
	* PMHx and HOPC
	* Surgery  
	Procedure, state, and implications.
	* Anaesthetic technique:
		* Airway
		* IV line and location
		* Fluid management
		* Drugs and infusions
	* Observations
* Temporary anaesthetist should not substantially change the anaesthetic management

## Handover After Anaesthesia

Principles:

* Care is shared between:
	* Anaesthetist
	* Proceduralist
	* Nursing staff
* Formal handover should:
	* Occur when the the patient is stable
	* Include instructions relating to:
		* Relevant aspects of anaesthetic technique
			* Airways
			* Throat packs
			* IV and arterial devices
			* Epidurals
			* Drug infusions
			* Residual block
		* Relevant aspects of surgery
		* Clinical observations and reportable levels
		* Analgesia
		* PONV
		* Fluid therapy
* Patients should not be discharged from recovery until discharge criteria are satisfied

---

## References

1. ANZCA. [PS53: Statement on the Handover Responsibilities of the Anaesthetist](http://www.anzca.edu.au/Documents/ps53-2013-statement-on-the-handover-responsibiliti.pdf).