# Monitoring During Anaesthesia


General Principles:

* Monitoring is essential during anaesthesia, and must be used in conjunction with clinical observation  
Vigilance is essential for safe practice.
	* Therefore, a proceduralist cannot also provide anaesthesia
* Person responsible for provision of anaesthesia must be constantly present from induction until transfer to PACU or ICU  
In exceptional circumstances, a brief absence may be unavoidable. In such instances, observation should be delegated to a suitably trained and skilled practitioner.
	* Permanent handover of responsibility can only occur to an anaesthetist who is able to accept that responsibility
* Duration of monitoring post-operatively relies on clinical judgment 
* Presence of monitoring is the responsibility of the anaesthetist

Regular monitoring should include assessment and recording of:

* Oxygenation  
Continuously. Adequate light should be available.
	* Pulse oximetry is required for every GA or sedation  
	Variable pulse tone and alarm should be set and audible.
	* An oxygen analyser (for low FiO<sub>2</sub>) must be in continuous use for every case involving an anaesthetic breathing system
* Ventilation  
Continuously.
	* If an automatic ventilator is in use, an alarm for a disconnection must also be in use
	* ETCO<sub>2</sub>:
		* Must be used for every GA
		* Should be available for every sedation
* Circulation  
Detection of pulse and blood pressure.
	* ECG must be available
	* ECG should be used for GA and major regional cases, if clinically indicated
	* NIBP should be:
		* Available for every GA
		* If used, measured no less than every 10 minutes
	* Invasive blood pressure monitoring should be available
* Awareness/Anaesthesia
	* Equipment to measure effect of anaesthesia on the brain should be available
	* End-tidal inhalational anaesthetic concentration must be used for every inhalational anaesthetic
* Extremities
	* Core temperature monitors should be:
		* Available for every patient undergoing GA
		* Used whenever warming devices are used
	* Neuromuscular function monitors:
		* Must be available if neuromuscular blockade is induced
		* Used prior to extubating a patient who has received a non-depolarising neuromuscular blocker

Alarms:

* Alarms are visual and audible
* Alarms should be enabled on commencement of anaesthesia  
* Alarms should only be disabled in exceptional circumstances

---

## References

1. ANZCA. [PS18: Guidelines on Monitoring During Anaesthesia](http://www.anzca.edu.au/Documents/ps18-2015-guidelines-on-monitoring-during-anaesthe.pdf).