# The Post-Anaesthesia Care Unit


Principles of PACU:

* A PACU is required for all patients who have recently undergone surgery or other procedures, irrespective of the type of anaesthesia or sedation used
* Patient safety is paramount
	* If patients are transferred to PACU from elsewhere, they must be monitored as per [guidelines for transport of the critically ill patient](/intensive-care/transport.md).
* Recovery staff should be trained for their role, have appropriate supervision, and have appropriate paediatric experience (if required)
* With respect to nursing ratios:
	* All **patients must be monitored one-to-one** until the patient:
		* Controls their own airway
		* Has stable observations within acceptable limits
		* Can communicate purposefully
		* Is awake
	* **Two-to-one** ratio is usually needed **during reception**
		* Second person may be the anaesthetist or operating room nurse
* With respect to airway devices:
	* **Intubated** patients must be **monitored** by the **anaesthetist**
	* Patients with a SAD must be breathing spontaneously\
	* The **anaesthetist cannot leave a facility** whilst a **SAD** is still **in situ** for their patient
* Must be resourced to:
	* Manage common and expected outcomes of the given procedure
	* Cover the spectrum of patients managed in that facility
	* Manage airway, respiratory, and cardiovascular complications
	* Treat both common and life-threatening post-anaesthetic events\
	e.g. PONV, pain, anaphylaxis.
* Must have an **emergency call system** to summon assistance from appropriate areas within the facility

## Design Features

* Part of the operating theatre or procedural suite
* Have easy access from the operating theatres
* Accessible without passing through OR
* Have routes for rapid evacuation if required
* Have enough bed spaces to accommodate expected peak loads
* Adequate space for the patients bed, equipment, and personnel:
	* A **minimum of 9m^2^** for each patient
	* Up to **20m^2^** for higher-acuity patients
* Staff should be able to view all patients at once\
**'Line-of-sight nursing care'**.
* Separate area for paediatric patients, if the facility deals with both adult and paediatric patients
* Each bed space must have:
	* An oxygen outlet
	* Medical suction
	* At least four power outlets
	* Appropriate lighting and wall colour to allow accurate assessment of skin colour
	* Emergency lighting
	* Facilities for mounting equipment
	* Facilities for charting/accessing electronic records
* A clock
* Emergency power supply
* Access for portable x-ray

## Equipment Requirements

Within all PACU there must be:

* Equipment for manual ventilation:
	* At least one per two bed-spaces
	* Not less than two
* Equipment and drugs for intubation
* Capnography
* ECG monitoring
* Nebulisers
* Drugs\
Including:
	* Emergency drugs
	* Antiemetics
	* Analgesics
	* Local anaesthetics
* Intravenous fluids
* Thermometer
* BSL and ketone testing
* Stethoscope
* Defibrillator
* Handwashing basin
* Routine for checking equipment

For facilities conducting general anaesthesia, major regional/neuraxial anaesthesia, or major surgery, there should be easy access to:

* 12-lead ECG
* End-tidal CO~2~
* Nerve stimulator
* Warming cupboard
* Patient warming devices
* Drug and blood refrigerator
* Procedure light
* Surgical tray
* Point-of-care blood gas/electrolyte/Hb measurement
* Diagnostic imaging services
* Apparatus for mechanical ventilation
* Heated, humidified, high-flow nasal oxygen
* Monitors for direct pressure monitoring
* Equipment for inserting a urinary catheter

Each bed space must have:

* Oxygen flowmeter
* Suction equipment
* Pulse oximetry
* Manual and automated blood pressure measurement

Each bed should:

* Have a firm base and mattress allowing effective CPR
* Tilt both head-up and head-down at least 15°
* Be easy to move
* Have efficient and accessible brakes
* Have secure side rails which must be able to be dropped below the base or be easily removed
* Have provision for maintaining IV infusions

## Discharge

Patients should remain until they are:

* Considered safe to discharge by establish criteria\
These include:
	* Respiratory stability
	* CVS stability
	* Adequate analgesia
	* Normothermia
	* No active bleeding
	* No immediate surgical complications
	* Minimal nausea
	* Return of consciousness
* Stage 2 recovery\
	* Provides a period of additional supervised care for day-stay or ambulatory patients
	* Allows:
		* Additional period of monitoring
		* Provision of food and fluids
		* Discussion of procedural outcomes and discharge instructions
	* Discharge criteria include:
		* Pain and nausea manageable with oral medications
		* Return of cognition to pre-procedure levels
		* Ability to safely mobilise

---

## References

1. ANZCA. [PS04: Statement of the Post-Anaesthesia Care Unit](http://www.anzca.edu.au/Documents/ps04-2006-recommendations-for-the-post-anaesthesia.pdf).