# Guidelines on Acute Pain Management


Treatment of pain is fundamental to quality patient care.

## Principles

* Pain may lead to adverse physiological and psychological efffects
* Effective post-operative pain management:
	* Reduces morbidity
	* Speeds discharge
	* Must be tailored tto the patient
	* Requires a multidisciplinary approach
	* Requires formal protocols and guidelines
* Pain is affected by patient attitudes and beliefs


## Clinical Manifestations

Assessment of analgesia:

* Must occur to tailor analgesic regimens
* Should be performed:
	* Frequently
	* At rest
	* During activity  
	Physical therapy, mobilisation, coughing, deep breathing.


## Pharmacological Therapies

Analgesics:

* May include:
	* Opioids
	* NSAIDS
	Local anaesthetics.
	* Antidepressants
	* Anticonvulsants
	* Membrane stabilisers
* Should be carefully titrated
* Should be used in combination  
Multimodal analgesia improves efficacy.


## Acute Pain Services

A formalised, multidisciplinary pain service:

* Improves patient outcomes  
Recommended for patients with complex medical or psychological pathology.
* Should be run by medical personell  
Anaesthetists and pain nurses.
* Involve liason with paramedical teams  
Physiotherapy, psychology, pharmacy.
* Should develop specific policies, protocols, and guidelines
* Should review all patients under their care **at least daily**
* Should consult on acute pain and acute-on-chronic pain
* Should conduct regular audits of practice

## Rights of the Patient

Patients with pain, have the right to:

* Have pain relief  
Professional response be reasonable and proportionate to level and character of the pain experience. This **does not mean that**:
	* The pain will (or can) be treated successfully
	* The patient will be free of pain
	* That pain relief can be provided on demand  
	Notably opioids.
* Have their complaints respected and taken seriously
* Be cared for in a timely manner by health professionals trained and experienced in assessment and management of pain
* Participate actively in the education and goal development
* Have their pain history, assessment, and management documented so that optimal ongoing relief is provided
* Have access to best practice care
* Informed of the evidence of efficacy and liklihood of sucess of management, and of alternative therapies
* Have appropriate planning for pain management after discharge

## Responsibilities of the Patient

Paients, carers, and families should:

* Engage openly
* Educate themselves about their pain and its management
* Participate actively in their own care, and decisions about their care
* Consider best-practice advice


---

## References


1. ANZCA. [PS41: Guidelines on Acute Pain Management.](http://www.anzca.edu.au/Documents/ps41-2013-guidelines-on-acute-pain-management.pdf).
2. ANZCA. [PS45: Statement on Patients' Rights to Pain Management and Associated Responsibilities](http://www.anzca.edu.au/Documents/ps45-2010-statement-on-patients-rights-to-pain-man.pdf).