# Patient Transport


Transport may involve
* Primary retrieval  
Retrieval from scene of injury to a hospital. Requires:
	* Adequate training
		* Scene organisation and safety
		* Mass casualty
		* Chemical, biological, radiological incidents
	* Adequate PPE
	* Adequate fitness
* Secondary retrieval  
Interhospital transport. Requires:
	* Sufficient staff  
	To cover rest, if required.
	* Consideration of transporting expert assistance to the patient
* Intra-hospital transport  
Transport of a critically ill patient within the hospital. Requires:
	* Appropriate nurse
	* Orderly
	* Medical practitioner  
	With appropriate skills.

## Modes of Transport

Choice of transportation vehicle will depend on:

* Clinical requirements
	* Nature of illness
	* Effect of transport method on the illness
	* Urgency
* Vehicle availability and suitability
	* Safety
	* Power and gas supply
	* Lighting and climate control
	* Restraints for stretcher
	* Communication systems
	* Suction
	* Number of retrieval personnel
	* Amount of equipment
	* Time taken to transport
	* Range and speed of vehicle
	* Weather and road conditions
	* Staffing training on transport platform
* Conditions at the referring and receiving centre
	* Location
	* Distance

### Risks of Air Transport

Pressure effects:

* Reduced PO<sub>2</sub>
* Requirement for pressurisation
* Risk of rapid depressurisation
* Expansion of gases
	* Air emboli
	* ETT cuff
	* Middle-ear
	* Airfilled spaces
		* Under dressing
	* DCI risk

Other effects:

* Limb swelling
* Temperature changes
* Humidity changes
* Acceleration, deceleration, turbulence
* Electromagnetic interference
* Motion sickness

## Prerequisites

* Secure airway
* IV access
* Secure catheters
* Appropriate monitoring
* Adequate infusion and fluid volume


## Equipment

Needs depend on requirements:

* Transport duration  
Oxygen and drug supplies should exceed estimated maximum transport time.
* Severity of illness

---

## References

1. ANZCA. [PS52: Guidelines for Transport of Critically Ill Patients](http://www.anzca.edu.au/Documents/ps52-2015-guidelines-for-transport-of-critically-i.pdf).