# Sedation and Analgesia for Diagnostic and Interventional Medical, Dental, or Surgical Procedures


Definitions:

* Procedural sedation and analgesia\
Drug-induced tolerance of uncomfortable or painful procedure.
	* May include lack of memory
	* Does not necessarily include lack of response to painful stimulation
* Conscious sedation\
Drug-induced depression of consciousness, in which patients are able to response purposefully to commands or light tactile stimulation.
	* Airway or cardiorespiratory support should only rarely be required
* Deep sedation\
Drug-induced depression of consciousness that readily progresses to the poijnt where consciousness is lost, and patients respond only to painful stimulation.
* Analgesia\
Reduction or elimination of pain perception.
* General anaesthesia\
Drug-induced state characterised by:
	* Absence of purposeful response to any stimulus
	* Loss of protective airway reflexes
	* Depression of respiration
	* Disturbance of circulatory reflexes

Aims of sedation:

* Enhance patient comfort whilst facilitating the procedure
* Range of options may be required\
Options exist on a continuum and are not discrete stages.
* Must be prepared to manage:
	* Loss of airway patency
	* Respiratory depression
	* Cardiovascular depression
	* Adverse drug reactions

Requirements of sedation:

* Adequate pre-anaesthetic consultation\
Aiming to identify patients at ↑ risk of airway or cardiorespiratory compromise.
* Facilities
	* Room to perform resuscitation
	* Appropriate lighting
* Equipment
	* Suction source
	* Oxygen source
	* Bag-Mask Ventilator
	* Airway equipment
	* Resuscitation drugs
	* Monitoring\
	Including ETCO~2~.
	* Access to ECG and defibrillator
	* Oxygen\
	100% oxygen if anaesthetic gases are used.
* Training
	* Minimum of three months full time equivalent of supervised training in procedural sedation or anaesthesia
* Documentation
* Recovery

---

## References

1. ANZCA. [PS09: Guidelines on Sedation and/or Analgesia for Diagnostic and Interventional Medical, Dental or Surgical Procedures](http://www.anzca.edu.au/getattachment/Resources/Professional-documents/ps09-2014-guidelines-on-sedation-and-or-analgesia-for-diagnostic-and-interventional-medical-dental-or-surgical-procedures.pdf).