# Guidelines on Smoking as Related to the Perioperative Period


Overview:

* Smoking is a major global health problem  
Greatest preventable cause of death in Australia and New Zealand.
* ↑ risk of perioperative respiratory, cardiac, and wound related complications
	* Cessation prior to surgery improves surgical outcome
* Perioperative period is a "teachable moment", where smokers may quit

Benefits of cessation:

* Quitting smoking for:
	* 12 hours will normalise carboxyhaemoglobin and nicotine levels  
	Could be expected to improve tissue oxygen delivery.
	* One day has a reduced IHD risk
	* 2 days has improved taste and reduced sputum load
	* Three weeks has been shown to improve wound healing
	* 2 months has normal sputum load, and improved pulmonary function
	* Six months results in significant recovery of immune function
	* One year has a 50% reduction in IHD risk
	* 5 years; CVA and cervical cancer risk is normalised and oral and oesophageal cancer risk is halved
	* 10 years; lung cancer risk is halved
	* 15 years; IHD risk has normalised

---

## References

1. ANZCA. [PS12: Guidelines on Smoking as Related to the Perioperative Period](http://www.anzca.edu.au/Documents/ps12-2013-guidelines-on-smoking-as-related-to-the.pdf).