# Antepartum Haemorrhage

Vaginal **bleeding** occurring **after** the **24^th^ week** of pregnancy and **prior to delivery**, usually due to:

* **Placenta previa**\
Implantation of the placenta round the internal os of the cervix. Classically presents with:
	* Painless, fresh vaginal bleeding
	* Foetal distress is rare
	* Coagulopathy is rare
* **Abruptio placentae**\
Premature separation of placenta from the decidua basalis. Classically presents with:
	* Painful
	* Generally older bleeding
	* **Blood loss may be concealed**
	* Significant foetal distress\
	Up to 50% foetal mortality.

## Epidemiology and Risk Factors

APH:

* **Major cause** of maternal mortality
* Occurs in 3-5% of pregnancies


Placenta Previa:

* Usually ~1% of total pregnancies
* Risk factors:
	* Prior:
		* Placenta previa
		* LUSCS
		* Myomectomy
		* Endometrial trauma
	* Age
		* < 20 or > 35
	* Smoking
	* Previous uterine trauma
		* Previous surgery
			* Caesarian
			* Curettage
			* Manual removal of placenta
		* Endometritis


Placental abruption:

* Risk factors
	* Maternal thrombophilias\
	* Placental abruption\
	Previous abruption gives ~20% risk of subsequent abruption.
	* Smoking
	* Cocaine
	* Amphetamine


## Pathophysiology

Placenta previa classified into:

* Complete (37%)\
Complete coverage of intenal os.
* Partial (27%)\
Partial coverage of the internal os.
* Marginal (37%)\
Placenta encroaches on internal os.


Placental abruption is classified by:

* Degree of blood loss:
	* Mild
	* Moderate
	* Severe
* Placental location:
	* Concealed haemorrhage\
	Bleeding trapped in uterus by placenta.
	* External haemorrhage\
	Blood flowing out of cervix.
	* External haemorrhage with placental prolapse


## Investigations

Maternal investigations are targeted towards assessing extent and consequences of haemorrhage. Investigations will depend on bleeding:

**Laboratory**:

* Bloods
	* FBE
	* Coagulation screen\
	If platelet count abnormal (suggestive of coagulopathy).
	* Group and hold\
	Cross-match 4 units if major haemorrhage.
	* UEC
	* LFT
	* Kleihauer\
	For Rh- mothers, to quantify extent of FMH.


**Other**:

* CTG
	* Once mother stable or resuscitation commenced
	* Aids decision making on mode of delivery
	* In general, a non-reassuring trace should result in expedited delivery.

## Management

:::info
Key determination is whether emergency caesarian is indicated, which is contingent on whether there is:

* **Active bleeding**\
* A **viable pregnancy**
:::


**Resuscitation:**



**Specific Therapy**:

* Procedural
	* Delivery\
	Ultimately required for both praevia and abruption.
		* Emergency caesarian
			* Often under GA
			* Massive transfusion often required\
				* Transfuse at 1:1:1, as per trauma resuscitation
				* Early coagulation profile and haematology involvement
			* Careful induction of anaesthesia required
			* Significant likelihood of post-partum hysterectomy


### Marginal and Ineffective Therapies


## Anaesthetic Considerations

* C
	* High likelihood of massive transfusion
	* Invasive arterial monitoring
* D
	* Anaesthetic technique
		* Regional\
		Appropriate if **no evidence of hypovolaemia**.
			* Reduced blood loss
			* Reduced aspiration
			* ↑ hypotension
			* Technical difficulty
		* General
			* Haemodynamic stability
			* Difficult airway and aspiration risk
* H
	* DIC\
	May develop following profound haemorrhage.



## Complications

Maternal complications:

* Haemorrhage
	 * Death
	 * Shock
	 * Anaemia
	 * Coagulopathy
	 * Prolonged hospital stay
	 * Blood transfusion

Foetal complications:

* Haemorrhage\
Particularly in vasa praevia or abruption.
* Hypoxia
	* Death
* Prematurity
* IUGR

## Prognosis


---

## References

1. RCOG. [Antepartum Haemorrhage: Green-top Guideline](https://www.rcog.org.uk/globalassets/documents/guidelines/gtg_63.pdf). RCOG. 2011.
2. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.