# Hypertensive Dieases of Pregnancy


Hypertension in pregnancy is:

* Common
* Associated with increased maternal, foetal, and neonatal morbidity and mortality
* Associated with additional complications
* Classified into four sub-groups:
	* **Gestational hypertension**
		* SBP > 140mmHg *or* DBP > 90mmHg
		* Present after 20^th^ week of gestation
		* Resolving following delivery  
	Usually within 6 weeks.
	* **Preeclampsia/Eclampsia**
		* Preeclampsia is defined as **gestational hypertension** with **organ system involvement**  
		Preeclampsia with severe features is preeclampsia with severe end-organ dysfunction or hypertension, see [clinical features](#clinical).
		* Eclampsia is defined as **preeclampsia** with **seizures**
	* **Chronic hypertension**  
	Pre-existing hypertension.
	* **Chronic hypertension with super-imposed preclampsia/eclampsia**


## Epidemiology and Risk Factors

Risk factors include:

* Patient factors:
	* Age > 35
	* Pre-existing HTN
	* CKD
	* DM
	* Anaemia
	* Living at altitude
	* *Non-*smokers
* Pregnancy factors:
	* Nulliparity
	* Multiple gestation

Preeclampsia is:

* A leading cause of maternal morbidity and mortality
* Present in 5-8% of pregnancies

Eclampsia:

* Occurs in ~0.05% of pregnancies
* Risk continues up to 1 week following delivery  
30% of seizures are post-partum.


## Pathophysiology

Underlying processes driving placental insufficiency include:

* Maternal endothelial dysfunction
	* Altered endothelial function
		* Increased endothelial secretion
		* Decreased nitric oxide
	* Normal development of a high-flow, low-resistance placental circulation does not occur
* Acute atherosclerosis and thrombosis of placental vessels  
Results in decreased placental flow and structural blood vessel damage.

These processes:

* Lead to the triad of:
	* **Vasoconstriction**  
	* **Platelet** activation and **aggregation**
	* **Loss** of **circulating volume**
* Result in other end-organ dysfunction
	* Laryngeal oedema
	* Cardiac
		* High cardiac output state with inappropriate SVR
		* Diastolic dysfunction
		* Decreased venous capacitance  
		Subsequently, generally normal filling pressures.
		Risk of acute LV failure if diastolic dysfunction present, especially if given volume.
	* Retinal vasospasm
	* Cerebral
		* Oedema
		* Haemorrhage
	* Renal
		* Oliguria
		* Uraemia
	* Hepatic
		* Synthetic coagulopathy
	* Haematological
		* Consumptive coagulopathy

### Aetiology

## Clinical Manifestations{#clinical}

Pre-eclampsia is classified by:

* Gestational age at diagnosis
	* Late  
	≥37 weeks.
		* Majority of cases
	* Preterm  
	34-37 weeks.
	* Early  
	<34 weeks.
* Severity
	* **Preeclampsia**  
	Gestational hypertension with organ system involvement:
		* Cardiorespiratory
		* CNS
		* GIT
		* Renal
			* Proteinuria >0.3g/24 hours
		* GIT
		* Uteroplacental circulation
	* **Preeclampsia with severe features**  
	Preeclampsia with *any* of the following features:
		* Cardiorespiratory 
			* Severe hypertension  
			Defined as SBP > 160mmHg or DBP > 90mmHg.
			* Hypertensive crisis  
			Defined as SBP >180mmHg or DBP >110mmHg.
			* Pulmonary oedema
		* CNS
			* Seizures/eclampsia
			* Headache
			* Visual disturbances
			* Papilloedema
			* Clonus/hyperreflexia
		* Renal
			* Proteinuria  
			≥5g/24 hours.
			* Oliguria  
			< 500ml/24 hours.
			* Protein/creatinine >0.5g/mmol.
			* Renal failure
		* GIT
			* Elevated transaminases
			* Hepatic tenderness
			* Nausea/vomiting
		* Haematological
			* Haemolysis
			* Thrombocytopenia  
			⩽100 x 10^9^sup>/L.
			* DIC
		* Uteroplacental circulation
			* Placental abruption
			* IUGR
			* Abnormal umbilical/uterine blood flow  
			Absent or reversed end-diastolic flow.
		* HELLP syndrome  
		Haemolysis, elevated liver enzymes, thrombocytopaenia.
	* Generally a high-cardiac output state, associated with inappopriately high SVR


### History

### Examination

## Diagnostic Approach and DDx

## Investigations

## Management

Preventative therapy:

* Limit intravenous fluid  
IV fluid increases risk of APO.
	* Avoid if:
		* Euvolaemic
		* Renal function normal 
* Avoid NSAIDs  
Reduce APO risk.
* Aspirin  
Indicated in pregnancy with major risk factors for pre-eclampsia, including:
	* Pre-disposing medical conditions
		* SLE
		* Scleroderma
		* Anti-phospholipid syndrome
	* Chronic hypertension
	* Diabetes
	* CKD
	* Oocyte donation
	* Family history of pre-eclampsia  
	Mother or sister.


Treatment revolves around:

* Control of blood pressure
	* Target SBP 140-150mmHg and DBP 90-100mmHg
	* Strategy depends on severity of hypertension
		* For non-severe hypertension:
			* Labetalol
			Drug of choice.
				* 100-400mg PO BD-TDS
			* Nifedipine
				* 20-60mg PO SR
			* Methyldopa
				* 250-750mg PO TDS
			* Clonidine
				* 75-300μg PO TDS
			* Hydralazine
				* 25-50mg PO Q8H
			* Metoprolol
			* Propranolol
		* For **severe hypertension** or **hypertensive crisis**:
		Aim to lower BP by 10-20mmHg every 10-20 minutes to reduce incidence of intracerebral haemorrhage.
			* Labetalol
				* 20-80mg IV over 2 minutes  
				Can repeat every 10 minutes.
			* Nifedipine
				* 10-20mg PO IR
			* Hydralazine  
				* 10mg IV Q20 minutes
			* GTN  
			For hypertension and APO
		* Safe agents in pregnancy include
			* Labetalol
* **Planning for delivery**  
	* Only curative option
	* Neuraxial techniques preferred in absence of coagulopathy  
	No clear advantage of any (CSE, epidural, single-shot spinal) technique.
* Managing complications
	* Magnesium Sulphate
		* **Prophylaxis** for **eclampsia** in women with **severe preeclampsia**  
		Not recommended for use as an antihypertensive agent.
		* Multifactorial mechanism of action:
			* Increased prostacyclin synthesis
			* Decreases calcium influx  
			Thereby decreasing ATP-consuming Ca^2+^-dependent processes.
			* NMDA antagonism
		* Give **4g over 20 minutes**, and then **1g/hr** thereafter
		* Target level is **1.7-3.5mmol/L**
		* Monitoring should be performed:
			* Q6H in women with renal impairment
			* If:
				* RR < 12
				* UO < 100ml over 4 hours
				* Loss of patella reflexes
				* Further seizures occur


### Timing of Delivery  

Timing of delivery is dependent on gestational age at time of onset of pre-eclampsia:

* Previable (< 23^6^ weeks)
	* High risk patient
	* Will likely require either:
		* Termination of pregnancy
		* Extreme preterm delivery
* 24-31^6^ weeks
	* High risk patient
	* Transfer to tertiary institution
	* Will likely require pre-term delivery
	* Aim to prolong pregnancy as able
* 32-36^6^ weeks
	* Aim to prolong pregnancy
	* Delivery where appropriate paediatric support is available
* 37^0^
	* Planned delivery


### Breastfeeding and Post-Partum Management

Ongoing and new-onset hypertension occur in the post-partum period. In addition to drugs used antenatally, drugs with low milk:maternal plasma ratios include:

* Enalapril
* Captopril

### Eclampsia

* A
	* Airway protection  
	Prevention of aspiration.
* C
* D
	* Anticonvulsant  
		* Magnesium Sulfate

### Anaesthetic Considerations

* A
	* Laryngeal oedema
		* Note presence of stridor pre-induction
		* Use a smaller ETT
* C
	* Hypertension
		* Management is difficult
		* Hypertension with light GA/laryngoscopy may be problematic
		* Key questions:
			* What is the current BP?
			* What is the trend in the BP?
			* What antihypertensive agents is the patient taking?
	* Volume state  
	May have ↓ intravascular volume; **↑ hypotension with neuraxial techniques**.
* D
	* Liklihood of eclampsia  
	Evaluate presence of:
		* Headache
		* Hyperreflexia/clonus
		* Visual symptoms
		* Extreme hypertension
	* Anaesthetic technique
		* Epidural
			* Reduces BP, and improves placental perfusion
			* Provides analgesia during labour
			* Slow titration may be **better than spinal** in severe preeclampsia
			* Consider inserting early, prior to thrombocytopenia developing
			* Requires **normal coagulation profile prior**
				* Platelet count > 70,000/ml  
				Institutional policy may differ.
				* Routine APTT/PT is not required unless:
					* Clinical history of bleeding
					* Other clinical condition that may contribute to coagulopathy
		* Spinal
			* Safe alternative
			* May require additional volume to compensate for the low-volume pre-eclamptic state
		* CSE
			* Preferable to spinal if surgery is long
		* GA
			* RSI associated with dangerous hypertension  
			Consider:
				* Labetalol 1mg/kg pre-induction  
				Reduces BP without affecting foetal blood flow.
			* Magnesium increases sensitivity to muscle relaxants
* F
	* Volume state
		* Urine output
		* Thirst
* H
	* Coagulation profile

	
## Complications

Maternal complications of severe pre-eclampsia include:

* Airway obstruction  
Vocal cord oedema due to decreased oncotic and increased hydrostatic pressure.
* Pulmonary oedema  
	* *Usually* due to low oncotic pressure or increased capillary permeability
	* Rarely due to diastolic dysfunction
* Cerebral haemorrhage
* Cerebral oedema
* Renal failure
* DIC
* Death
	* 40% due to cerebral oedema/haemorrhage
	* 40% due to pulmonary  
	Usually iatrogenic fluid overload.
	* Hepatic failure  
	Including hepatic rupture.


Foetal complications of pre-eclampsia include:

* IUGR
* FDIU
* Preterm birth


---

## References

1. Dennis AT. Management of pre-eclampsia: issues for anaesthetists. Anaesthesia. 2012;67(9):1009-1020.
2. Dennis AT, Castro J, Carr C, Simmons S, Permezel M, Royse C. Haemodynamics in women with untreated pre-eclampsia*. Anaesthesia. 2012;67(10):1105-1118.
3. Dennis AT, Solnordal CB. Acute pulmonary oedema in pregnant women. Anaesthesia. 2012;67(6):646-659.
4. Dennis AT, Castro JM. Hypertension and haemodynamics in pregnant women - is a unified theory for pre-eclampsia possible? Anaesthesia. 2014;69(11):1183-1189.
5. New Zealand Committee of RANZCOG, NZCOM. [Guidance regarding the use of low-dose aspirin in the prevention of pre-eclampsia in high-risk women](https://www.ranzcog.edu.au/RANZCOG_SITE/media/RANZCOG-MEDIA/New%20Zealand/Guidance-Aspirin-for-Prevention-of-Pre-eclampsia.pdf). 2018.
6. Lowe SA, Bowyer L, Lust K, McMahon LP, Morton M, North RA, Paech M. Said JM. [Guideline for the Management of Hypertensive Disorders of Pregnancy](https://www.ranzcog.edu.au/RANZCOG_SITE/media/RANZCOG-MEDIA/Women%27s%20Health/SOMANZ-Hypertension-Pregnancy-Guideline-April-2014.pdf?ext=.pdf). 2014.