# Placental Adhesive Disorders

Placental adhesive disorders, or abnormal placental, describes abnormal attachment of the placenta to the uterine wall. PAD:

* Includes placenta:
	* Accreta  
	Placental invading through decidua basalis onto the myometrium.
	* Increta  
	Placenta invading into but not through the myometrium.
	* Percreta  
	Placenta invading through uterine serosa, and may attach to extra-uterine organs (e.g., bladder).
* May cause massive haemorrhage  
Common cause of post-partum hysterectomy.

## Epidemiology and Risk Factors

Occurs in **1 in 500 pregnancies**.

Major risk factors:

* Placenta praevia
* Previous caesarian section  
↑ Risk:
	* 0: 2%
	* 1: 16%
	* 2: 24%
	* 3: 30%
* Placenta praevia AND previous caesarian section  
Multiplicative risk: 40% of women with praevia and three previous caesarians will have placental adhesive disorder.
* Smoking
* Uterine trauma
	* Multiple curettes  
	Asherman's syndrome describes intrauterine adhesions occuring following uterine surgery.

## Pathophysiology

Placenta:

* Invades deep into the uterine wall
* Does not separate from the uterus as it contracts  
Placental vessels remaing wide-open and continue to haemorrhage.

## Clinical Manifestations

Diagnosis is difficult, and investigations usualy proceed based on risk factors.


## Investigations

Diagnosis may be made on:

* Ultrasound  
	* Second or third trimester
	* Not reliable
	* Significant inter-observer differences
* MRI
	* Greater sensitivity and specificity
* Cystoscopy
	* Not usually performed as diagnostic test
	* Diagnosis of percreta may be made on cystoscopy performed for insertion of JJ stents prior to caesarian

## Management

Antenatal diagnosis facilitates adequate preparation:

* Patient counselling
	* Liklihood of hysterectomy  
	May include plan for caesarian-hysterectomy.
* Elective delivery
	* Tertiary obstetric centre
		* Personnel availability  
		Senior:
			* Obstetric
			* Paediatric
			* Haematology
			* Intensive care
		* Use of cell salvage
		* Blood bank availability
	* Ureteric stenting  
	If percreta. 
	* Interventional radiology  
	For:
		* Embolisation
		* Pre-emptive placement of balloon catheters to reduce haemorrhage


Surgical management options:

* Caesarian hysterectomy  
Uterus removed with placenta in-situ.
* Caesarian with uterine preservation  
**One-third** will still require **hysterectomy** due to bleeding, which may be delayed up to 4 week. Four major techniques:
	* Extirpative technique  
	Manual removal of placenta.
	* Expectant management  
	Placenta is left in situ.
		* ↓ risk of massive obstetric haemorrhage and placenta is removed from uterus
		* Preserves fertility
		* Placenta will necrose and ideally progressively detach itself  
		Risk of sepsis or failure (and massive haemorrhage).
	* Conservative surgery  
	Placenta accreta area is removed.
	* Triple-P  
	Acceta is resected and then sutured.



### Anaesthetic Considerations

*[General considerations for caesarian section](/anaesthesia/obs/luscs.md#considerations), as well as considerations for [general](/anaesthesia/obs/ga-luscs.md) or [regional](/anaesthesia/obs/reg-luscs.md) techniques, are also critical.*


* C
	* Ensure 2x wide-bore IVs
	* Invasive arterial monitoring
* D
	* Anaesthetic technique  
	Either GA or neuraxial can be performed safely. A technique that the provider and system are comfortable with is appropriate.
		* Primary GA
			* Attendant risks of GA caesarian
			* Foetal effects of general anaesthetic agents  
			Time to delivery often prolonged, and may be over an hour.
		* Primary neuraxial  
			* Planned conversion to GA following delivery is reasonable in the setting of:
				* Hysterectomy
				* Massive PPH
				* Large volume resuscitation
				* Acidosis
* H
	* Cross-match blood prior
* O
	* **Avoid oxytocin**  
	Placental separation is to be avoided in many surgical techniques.

## Complications

* Haemorrhage
* Hysterectomy
* Death


---

## References

1. Walfish M, Neuman A, Wlody D. [Maternal haemorrhage](https://academic.oup.com/bja/article/103/suppl_1/i47/230462). Br J Anaesth. 2009 Dec 1;103(suppl_1):i47–56. 
2. Sentilhes L, Kayem G, Chandraharan E, Palacios‐Jaraquemada J, Jauniaux E. [FIGO consensus guidelines on placenta accreta spectrum disorders: Conservative management](https://obgyn.onlinelibrary.wiley.com/doi/full/10.1002/ijgo.12410). International Journal of Gynecology & Obstetrics. 2018;140(3):291–8. 
3. Bowman ZS, Eller AG, Bardsley TR, Greene T, Varner MW, Silver RM. [Risk Factors for Placenta Accreta: A Large Prospective Cohort](https://www.thieme-connect.com/products/ejournals/html/10.1055/s-0033-1361833). Amer J Perinatol. 2014 Oct;31(9):799–804. 
4. RANZCOG. [Placental Accreta](https://www.ranzcog.edu.au/getattachment/Statements-Guidelines/Obstetrics/Placenta-Accreta-(C-Obs-20)/Placenta-Accreta-(C-Obs-20)-Review-March-2014,-Amended-November-2015.pdf?lang=en-AU&ext=.pdf). 2014.