# Primary Postpartum Haemorrhage


Postpartum haemorrhage is a major cause of maternal mortality. With respect to PPH:

* Primary PPH is blood loss the first 24 hours post-partum that:
	* Exceeds 500mL
	* Causes haemodynamic instability
* Massive PPH is loss of >50% of the circulating blood volume

## Epidemiology and Risk Factors

In Australia, PPH:

* Occurs at 6/1,000 deliveries  
Will likely ↑ over time:
	* ↑ maternal age
	* Conception following LUSCS  
	↑ percreta/accreta risk.
* Has a mortality of 4/100,000 deliveries


Risk factors for PPH relate to the cause:

* Atony
	* Maternal obesity
	* Maternal DM
	* Multiple pregnancy
	* Multiparity
	* Advanced maternal age
	* Prolonged labour
	* Augmented labour
	* Amniotic infection
	* Abnormal uterine anatomy
	* Uterine inversion
	* Macrosomia
* Tissue
	* Abnormal placenta
	* Retained clot
	* Previous uterine surgery
	* Placenta praevia
	* Placenta accreta/percreta
* Trauma
	* Precipitous delivery
	* Operative delivery
	* Foetal malposition
	* Multiparity
	* Previous uterine surgery
* Thrombin 
	* Hereditary disease  
		* von Willebrand's
		* Haemophilia
	* Acquired disease
		* ITTP
		* Pre-eclampsia
		* FDIU
		* Infection
		* Placental abruption
		* AFE
	* Therapeutic
		* Thromboprophylaxis

## Pathophysiology

### Aetiology

Causes grouped into the **four T's**:

* A**t**ony  
Failure of uterine contraction.
	* Occurs in 10% of pregnancies
	* Causes 70% of PPH
* **T**rauma  
Second most common cause, due to injury to:
	* Uterus
	* Cervix
	* Vagina
	* Perineum
* **T**issue  
Retained products of conception.
	* Third most common cause
	* Generally retained placental fragment  
	May be related to placenta accreta.
* **T**hrombin  
Coagulopathy.

Other causes:

* Uterine inversion  
Where the fundus of the uterus begins to prolapse out of the cervix.
* Uterine rupture  
Usually along a scar from previous caesarian or uterine surgery.


## Clinical Manifestations

> Many features may be **masked by the physiology** of pregnancy

Symptoms and signs of massive blood loss:

* Tachycardia
* Lightheadedness
* Sweating
* Pallor
* Weakness
* Hypotension  
Classically late sign in pregnant women.

## Diagnostic Approach and DDx

## Investigations

Key investigations:

* Group and Hold
* Coagulation studies
	* Including D-dimer

## Management

> Treatment should be initiated as soon as blood loss is obvious, assumed, or predicted

Management principles follow the general principles of massive blood loss, plus specific management of uterine causes:

* Apply 100% oxygen
* Give warmed IV fluids  
Fluid resuscitation should continue whilst bleeding is ongoing.
* Prepare for transfusion
	* Ensure at least 2x ≥ 16G IVC access
	* Ensure key investigations have been sent
	* Prepare fluid warmers
* Transfuse appropriately
* Avoid hypothermia
* Consider DDAVP 0.3μg/kg
	* Uraemia  
	≥20mmol/L.
	* von Willebrand's disease
* Consider factor VIIa
* Treat the cause  
See below.


Management of uterine tone:

* Uterine contraction or relaxation may be required depending on cause
	* Uterotonics
	* Uterine relaxation
		* Volatile anaesthetics
		* GTN




Management of continued bleeding, despite active management of the third stage and specific treatment below:

* Repeat oxytocin
* Give prostaglandin F2-alpha if not already given
* Bimanual uterine compression
* Aorta compression
* If bleeding persists:
	* Pack uterus  
	Up to 24 hours, cover with IV antibiotics and continue oxytocin infusion.
	* Uterine artery ligation
	* Internal iliac ligation
	* B-lynch
	* Hysterectomy
	* Interventional radiology


#### Atony

* Uterine massage  
Rub up. Effective in most cases.
* Uterotonics  
Ensure active management of the third stage has been completed.
	* Oxytocin 10 units IV  
	Commence infusion at 10 units/hr; usually 40 units in 1L of CSL/NS/D5W over 4 hours.
	* Ergometrine 0.25mg IM  
	Can give a further 0.25mg IV; beware bronchospasm and hypertension. Up to a total of 1mg.
	* Metoclopramide 10mg IV
	* Carboprost 0.25mg **IM**  
	Can repeat Q15 minutely, up to 2mg.
	* Consider misoprostol 1mg **PR**
	* Misoprostol


### Trauma

> Blood loss often underestimated

* May require anaesthesia for closure  
Regional techniques appropriate if haemodynamically stable.


### Tissue

> May have significant blood product requirement  
> Uterine relaxation may be required

* Deliver placenta
	* Controlled cord traction  
	Examine for completeness.
* Retained placenta requires operated delivery  
Anaesthetic techniques, in order of preference:  
	* Epidural top-up
	* Spinal anaesthesia
	* Intravenous sedation  
	May be appropriate in some instances.
	* General anaesthesia

### Coagulopathy

>"An empty, intact, **contracted** uterus will not bleed unless there is coagulopathy"

* Ensure coagulation profile has been sent
* Replacement of platelets and clotting factors
* Consider TXA  
Of dubious benefit in obstetric haemorrhage in the 1^st^ world setting.

### Uterine Inversion

>Haemorrhagic shock is common  
>Uterine relaxation may be required

Anaesthetic techniques:

* Regional  
Appropriate if haemodynamically stable.
* General anaesthesia  
May be required if **uterine relaxation** needed, particularly in the case of **chronic inversion**.


### Anaesthetic Considerations

* C
	* Haemodynamic stability
		* Key guide for resuscitation goals

### Ineffective Therapies

## Complications

## Prognosis


---

## References

1. RANZCOG. [Management of Postpartum Haemorrhage](https://www.ranzcog.edu.au/RANZCOG_SITE/media/RANZCOG-MEDIA/Women%27s%20Health/Statement%20and%20guidelines/Clinical-Obstetrics/Management-of-Postpartum-Haemorrhage-(C-Obs-43)-Review-July-2017.pdf?ext=.pdf). RANZCOG. 2017.