# Pregnancy and Labour

Period of time during which a child develops inside a woman. Pregnancy is:

* Normally 37-42 weeks
* Divided into trimesters
	* First trimester\
	0-12 weeks. The first trimester:
		* Has the highest rate of misscarriage
	* Second trimester\
	13-28 weeks. The second trimester:
		* Foetal movement begins
	* Third trimester\
	29-40 weeks.

## Physiology of Pregnancy

Physiological changes and their implications can be classified by system:

* Respiratory
	* MV\
	↑; ↑ uptake of volatile agents.
	* FRC\
	↓; ↓ safe apnoea time.
	* RV\
	↓; ↑ atelectasis and shunt.
	* VO~2~\
	↑; ↓ safe apnoea time.
* CVS
	* Cardiac output\
	↑ up to 40%; ↓ physiological reserve.
	* Heart rate\
	↑ by 15-20 bpm; ↓ reserve and coronary perfusion time.
	* SVR\
	↓.
	* BP\
	↓.
	* Volume\
	↑ circulating volume.
	* Other\
	Aortocaval compression by uterus reduces CO in supine position; can be reduced by placing tilt under **right** hip.
* Endocrine\
	* Insulin\
	↑ production and resistance; gestational diabetes.
	* Thyroid hormones\
	↑; incidence of hyperthyroidism.
* Renal
	* Renal blood flow\
	↑; natriuresis.
	* Blader emptying\
	↓; ↑ UTI.
* GIT
	* Bowel\
	Displaced into upper abdomen; ↑ reflux risk.
* Hepatic\
	* Plasma cholinesterase\
	↓; ↑ duration of suxamethonium.
	* Albumin\
	↓; altered pharmacokinetics via change in protein binding, ↑ peripheral oedema.
	* Biliary\
	↓ gallbladder contractility; biliary stasis.
* Haematological
	* Haemoglobin\
	↓ due to dilution; may be confused with haemorrhage.
	* White Cell Count\
	↑; may mimic infection.
	* Coagulation factors\
	↑; ↑ thrombosis risk.
* Immunological
	* Cell mediated immunity\
	↓; ↑ viral infections.

### Physiology of Labour

Labour is divided into **three stages**:

* **First stage**\
Covers the process of cervical dilation (0-10cm).
	* Involves:
		* Cervical dilation
		* Cervical effacement
		* Desent of the presenting part
	* **Normal** progress\
	Based on rate of cervical dilation, should be **>1cm/hr**.
		* 0.5cm/hr is 10^th^ centile, and is often accepted
* **Second stage**\
Covers full dilation to delivery.
	* Involves:
		* Flexion
		* Descent
		* Rotation of the presenting part\
		Head moulds, flexes, and rotates through the birth canal.
			* Head should be delivered occiput-anterior (OA); i.e. **face-down**
			* Head has to rotate through the pelvis as the pelvic inlet is widest in the transverse diameter, and the outlet in the A-P diameter
	* Normal progress\
	**Delivery** should occur:
		* **Within 2 hours** of full dilation without epidural
		* Within **3 hours with epidural**
* **Third stage**\
Delivery of the placenta.



## Management

Divided into:

* Drugs in pregnancy
	* Risks
	* Risk categorisation of drugs
	* Examples
* Labour
	* Induction of labour
	* Premature labour
	* Foetal distress


### Drugs in Pregnancy

Drugs in pregnancy are:

* Used by 20-25% of women regularly
* Often not validated for use or safety, including anaesthetic drugs\
Drug trials are difficult to perform in pregnant women.

Drug interactions in pregnancy can be classified into:

* Pharmacokinetic
	* Absorption
		* PO absorption affected by nausea and vomiting
	* Distribution
		* ↑ V~D~ of water soluble drugs\
		Due to ↑ blood and body fluid volume.
		* ↑ free portion of acidic drugs\
		Due to ↓ albumin.
	* Elimination
		* ↑ renal clearance\
		Due to high GFR.
* Pharmacodynamic\
Most unchanged, except for:
	* Volatiles\
	↓ MAC.
	* Local anaesthetics\
	↓ neuraxial LA requirement.

* Foetal transfer via placenta
	* Almost all drugs cross the placenta to a certain degree\
	* Major determinants are concentration gradient, molecular weight, lipid solubility, degree of ionisation, protein binding, uteroplacental blood flow.
* Foetal transfer via breast milk


#### Risk of Drugs in Pregnancy

Extent of effect depends on timing of consumption:

* 0-2 weeks\
Generally all or nothing effect:
	* Brief slowing of gestation with no overt ill effect
	* Spontaneous abortion\
* 3-8 weeks\
Period of organogenesis and potential for major abnormalities.
* Over 8 weeks\
Foetal period, effects include:
	* Physiological abnormalities
	* Minor morphological abnormalities

#### Risk Categorisation System

The Australian risk categorisation divides drugs into:

* Category A\
Taken by a **large number** of pregnant women **without any observed ↑ in malformations** or other harmful effects.
* Category B\
Drugs which have been taken by a **limited number** of pregnant women, **without any ↑ in the frequency of malformations** or other harmful effects. Divided into three **subgroups based on animal data**:
	* B1\
	No observed foetal malformations in animals.
	* B2\
	No observed foetal malformations in animals, but studies were inadequate/data was lacking.
	* B3\
	↑ foetal abnormalities in animals, of uncertain human significance.
* Category C\
Caused/suspected to have **caused *potentially reversible* harmful foetal effects**.
* Category D\
Caused/suspected to have **caused ↑ foetal malformations** or **permanent** damage.
* Category X\
Such **high risk of causing foetal damage** that they should **not be used in pregnancy or** where there is a **possiblity of pregnancy**.

#### Specific Drugs in Pregnancy


|Class|Category A|Category B1|Category B2|Category B3|Category C|Category D|Category X|Notes|
|--|--|
|**Antihypertensives**|Methyldopa||Prazocin <br>- Not recommended in 1^st^ trimester||Calcium channel blockers<br>β-blockers <br>- IGUR, ↓ HR, ↓ BSL, ↓ birth weight<br>Labetalol <br>- 1^st^ line<br>Hydralazine<br>- For hypertensive emergencies only|ACE-I/A2RB<br>- Contraindicated in all 3 trimesters<br>-1^st^ trimester: Major CVS/CNS malformations<br>-2/3^nd^ trimester<br>- Renal damage<br>-MSK deformities<br>- Death||
|**Anticoagulants**|||||Heparin/LMWH<br>- ↑ peripartum bleeding|Warfarin<br>- Terratogenic, particularly 6-9 weeks||
|**Anaesthetic agents**|Thiopentone<br>Ketamine||||Propofol<br>Benzodiazepines<br>- Not recommended in 1^st^ trimester<br>- Secreted heavily in breast milk||||
|**Corticosteroids**|Cortisone<br>Hydrocortisone<br>Prednisolone||||Dexamethasone<br>Betamethasone<br>Fludrocortisone<br>Tiamcinolone<br>- May ↑ oral cleft if used in 1^st^ trimester||||
|**Analgesics**|Paracetamol||||NSAIDS<br>- Avoid in 3^rd^ trimester as may cause premature duct closure, renal impairment, oligohydramnios, delayed labour||
|**Antiemetics**|Metoclopramide|Ondansetron<br>Granisetron<br>Dolasetron||Tropisetron|||||
|**Antibiotics**|Penicillins<br>Cephalosporins<br>Erythromycin|Roxithromycin||||Aminoglycosides<br>- Risk of foetal oto/nephrotoxicity<br>Tetracyclines<br>- Teeth staining, suppressed bone development|||
|**Volatile agents**|Halothane<br>Nitrous oxide||Sevoflurane|Isoflurane<br>Desflurane||||
|**Muscle relaxants**|Suxamethonium||Rocuronium<br>Pancuronium||Vecuronium<br>Cisatracurium<br>Atracurium|||Do not cross placenta; if foetal muscle relaxation required for foetal surgery then drug must be given to foetus|
|**Vasopressors**|Adrenaline<br>Ephedrine||Phenylephrine||Metaraminol|||Used whatever agent is best for the mother|
|**Antiarrythmics**|Digoxin||Adenosine||Amiodarone||||

### Labour{#labour}

Management of abnormal labour depends on stage:

* Abnormal S1
	* Trial of oxytocin\
	↑ rate of dilation.
	* LUSCS\
	If concerns about:
		* Uterine rupture
		* Obstruction
		* Power of contraction
		* Foetus
* Abnormal S2
	* Trial of oxytocin\
	↑ uterine contractility.
	* Operative vaginal delivery\
	Forceps, vacuum. Indications can be divided into:
		* Maternal\
			* Exhaustion
			* Contraindication to pushing
				* HTN
				* Cerebral aneurysm
		* Foetal
			* Distress\
			CTG, scalp pH, prolapse.
		* Failure to progress\
		Arrested descent. May be due to:
			* Mento-anterior (MA)\
			Failure to descend.
			* Occiput Posterior (OP)\
			Failure to rotate.
			* Other\
			Usually requires LUSCS.
	* LUSCS
* S3\
Active management of S3 significantly reduces PPH and maternal mortality. Active management involves:
	* Prophylactic oxytocin\
	Upon delivery of the anterior shoulder.
	* Early cord clamping
	* Controlled cord traction


#### Induction of Labour{#induction}

Artificial techniques to initiate the process of labour. Induction is performed:

* For:
	* Pregnancy reasons
		* PD
		* Twin pregnancy > 38 weeks
		* PROM\
		See [premature rupture of membranes](/anaesthesia/obs/terms.md)
		* FDIU
	* Maternal disease
		* [Pre-eclampsia](/disease/obs/htn.md)
		* Diabetes
	* Foetal
		* IUGR
* By:
	* Pharmaceutical means:
		* Intravaginal or endocervical prostaglandin
		* Intravenous oxytocin\
	* Non-pharmaceutical means:
		* Membrane sweep\
		Digital stimulation of the cervix to release endogenous prostaglandins.
		* AROM
		* Cervical ripening balloon


#### Premature Labour{#preterm}

Premature:

* Labor occurs prior to 37 weeks gestation
* Birth occurs in ~10% of deliveries\
Associated with 85% of all perinatal morbidity and mortality, due to:
	* Respiratory distress syndrome
	* Intracranial haemorrhage
	* Ischaemic cerebral damage\
	Intrapartum:
		* Hypoxia
		* Asphyxia
		* Hypotension
	* Hypoglycaemia


Management of Premature Labour:

* Foetal protection
	* Antenatal corticosteroids
		* For women <34^+6^ and birth expected in <7 days\
		Risk:benefit of precise timing varies.
		* ↓ Foetal morbidity and mortality by ↓ incidence of respiratory distress syndrome by:
			* Accelerating lung maturity
			* ↓ IVH
			* ↓ Necrotising enterocolitis
		* Betamethasone 11.4mg IM daily for 2 days
	* Magnesium
		* For women <30^0^
		* ↓ Risk of cerebral palsy and death in preterm infants
		* Administer **within 4 hours of birth**:
			* 4g over 20 minutes
			* 1g/hr thereafter
* **Tocolytics** are used to stop premature contractions\
Agents include:
	* Magnesium sulfate
	* Calcium channel blockers
	* Methylxanthines
	* Prostaglandin inhibitors
	* β-agonists
		* Evaluate for hyperkalemia if on treatment longer than 24 hours
	* Ethanol
		* Historical
		* Inhibits ADH, oxytocin, and myometrial contractility
* Consider epidural as anaesthetic technique
	* Reduces effects of systemic drugs on foetus
	* Improved foetal perfusion
	* May reduce incidence of ICH by allowing controlled delivery


#### Foetal distress

* Avoid aortocaval compression
* Supplemental oxygen
* Treat hypotension
* Cease oxytocin\
Generally decision of obstetric team.
* Consider tocolytics
	* Terbutaline 250μg IV/SC
	* Salbutamol 100μg IV
	* GTN 400μg SL
* Prepare for em LUSCS

## Complications

## Prognosis


---

## References
