# Antiplatelets

Antiplatelet agents are:

* Used predominantly for **arterial disease**
* Include:
	* NSAIDs\
	Less potent, reversible, usually resolves within 24 hours.
	* **Aspirin**\
	Irreversible.
	* P2Y~12~ antagonists\
	Irreversible, and ↑ potency compared to aspirin, with ↑ bleeding risk.
		* Clopidogrel
		* Ticagrelor
		* Prasugrel
	* GP IIb/IIIa inhibitors\
	Reversible with cessation.
		* Tirofiban
		* Eptifibatide
		* Abciximab


## Indications

* Arterial stenting

## Contraindications


## Enteral

### Aspirin

Weak salicylic acid that causes irreversible COX-1 inhibition:

* ↓ Thromboxane A2 production for the duration of platelet lifespan (5-10 days)


**Key** pharmacological **properties**:

* Renally cleared
* Half-life 1-2 hours


### Clopidogrel

Thienopyridine that:

* Causes irreversible P2Y12 ADP receptor inhibition\
Inhibits cAMP-dependent platelet activation for duration of platelet lifespan
* Displays significant inter-individual variability\
15-50% of patients have impaired response to clopidogrel activity, which may be due to:
	* CYP450 polymorphism
	* Drug interaction
	* DM


**Key** pharmacological **properties**:

* 50% renally, 50% biliary cleared
* Half-life 1-2 hours


### Ticagrelor

Adenosine analogue that:

* Causes **reversible** P2Y12 ADP receptor inhibition
* Has a similar mechanism of action to clopidogrel
* More predictable inhibition than clopidogrel
* ↑ Bleeding risk compared to clopidogrel


**Key** pharmacological **properties**:

* Biliary elimination
* Half-life 8 hours

### Reversal

All enteral antiplatelet agents are minimally reversible, therapeutic options include:

* Cessation
* Other haemostatic measures
* DDAVP\
May have effect in aspirin-induced platelet inhibition, minimal evidence in other contexts.
* Platelet transfusions
	* More effective in aspirin
	* May be ineffective in reversing ticagrelor

:::column-margin
{{< include /includes/ddavp.qmd >}}
:::

## Parenteral

### Tirofiban

* GP IIb/IIIa inhibitor\
Prevents platelet binding to fibrinogen and vWF.


**Key** pharmacological **properties**:

* Intravenous administration
* Renally cleared
* Half-life 2 hours
* Reversal in 4-8 hours following cessation


### Eptifibatide

* Reversal in 4-8 hours following cessation


### Abciximab

* Reversal in 1-2 days following cessation





## Complications


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.