# Anticoagulation {#sec-anticoagulation}

Therapeutic anticoagulation has a broad array of both:

:::column-margin
This provides a general overview of therapeutic anticoagulation. Management of perioperative anticoagulation is covered @sec-periop_anticoag, and thromboprophylaxis is covered under @sec-thromboprophylaxis.
:::

* Indications
* Therapeutic options
	* Parenteral
		* Intravenous UFH
		* Low-molecular weight heparins
	* Oral
		* Vitamin K Antagonists
		* Direct Anticoagulants


## Indications

## Contraindications

## Parenteral

### Unfractionated Heparin

Cocktail of bovine or porcine, variable-length, mucopolysaccharides with three major mechanisms of action:

* **Potentiates antithrombin III**
* Neutralises thrombin
* Neutralises Factor Xa


**Key** pharmacological **properties**:

* Dosing varies depending on level of anticoagulation required:
	* 8-12 unit/kg/hr infusion
* Requires monitoring:
	* Detectable through ↑ APTT or anti-Xa
	* High inter-individual variability


**Reversal**:

* Cessation
	* Safe
	* Relatively rapid
* Protamine

:::column-margin
**Protamine is** an **anticoagulant** in excess doses.
:::

**Resistance**:

* Heparin resistance occurs when the APTT fails to ↑ despite very high doses of heparin\
Considered >25-30 U/kg/hr.
* Causes include:
	* ↓ Antithrombin III\
	Functional assay of <60% correlates with ↓ *in vitro* activity.
	* ↑ Heparin binding proteins\
		* Are an acute phase reactant and so often elevated in the critically ill
		* Results in a greater amount of UFH required to achieve a therapeutic APTT
		* **APTT correlates with** degree of **anticoagulation**
	* ↑ Factor VIII
		* May occur due to:
			* Systemic inflammation
			* Pregnancy
			* Malignancy
			* Hepatic disease
			* Renal disease
		* Results in a greater amount of UFH required to achieve a therapeutic APTT
		* **APTT does *not* correlate** with degree of **anticoagulation**\
		Also known as pseudo-heparin resistance.
		* Requires monitoring with anti-Xa
	* ↑ Heparin clearance
* **Management** options:
	* Check an anti-Xa to quantify the heparin effect
	* Give more heparin
		* Cheap
		* Unlikely to over-correct
	* Supplemental antithrombin III\
		* Goal to achieve >120% effect on functional assay
		* May be unpredictable\
		Significant ↑ in APTT if large dose of heparin has been already given.
		* Options include:
			* **FFP**\
			20mL/kg ↑ functional assay by 20-25%; so large volumes may be required.
			* **Antithrombin III concentrate**
			~1.4%/unit/kg; generally given in 1000 unit increments.
				* Significantly ↓ volume compared with FFP
				* Expensive and limited availability
	* Alternative anticoagulation\
	Generally a direct thrombin inhibitor:
		* Bivalirudin
		* Argatroban


### Low Molecular Weight Heparin

**Reversal**:

* Cessation
* Protamine\
Reverses ~50% of total effect.
* Andexanet alfa


## Enteral

### Vitamin K Antagonists

Prevent synthesis of vitamin K dependent clotting factors, and are functionally synonymous with the various flavours of warfarin.

:::column-margin
Vitamin K dependent clotting factors include:

* Factor II
* Factor VII
* Factor IX
* Factor X
:::

**Key** pharmacological **properties**:

* Rapid and complete oral absorption
* Highly inter- and intra-individual variability
* Requires monitoring
	* Frequency varies depending on stability and compliance.
	* Detectable though ↑ PT and INR
* Effective half-life 20-60 hours
* Stable in renal failure
* Substantial drug interactions

:::column-margin
{{< include /includes/warfarin.qmd >}}
:::

**Reversal**:

* Factor replacement\
	* Indicated for rapid and complete reversal
	* Consumption of administered factors will result in anticoagulation\
	Synthesis remains inhibited.
	* Options include:
		* 4-factor PCC
		* 3-factor PCC\
		May still require FFP.
		* FFP
* Vitamin K
	* Acts within ~6 hours
	* Sustained reversal\
	Balanced against thrombotic risk.
	* High doses may cause significant warfarin resistance if it is recommenced


### Direct Anticoagulants

Direct anticoagulants inhibit specific elements of the clotting cascade, either:

* Factor Xa\
Inhibit free and prothrombinase-bound factor Xa.
	* Rivaro**xa**ban
		* Contraindicated in renal failure
	* Api**xa**ban
		* Appropriate in renal failure
	* Edo**xa**ban
* Thrombin
	* Dabigatran\
		* Prodrug
		* Reversible direct thrombin inhibition

:::column-margin
: Rivaroxaban Dosing

+----------------------+--------------------+-----------------------------------------+
| Creatinine Clearance | Non-valvular AF    | VTE                                     |
| (mL/min)             |                    |                                         |
+======================+====================+=========================================+
| \>49                 | 20mg daily         | 15mg BD for 21 days, then 10-20mg daily |
+----------------------+--------------------+                                         |
| 30–49                | 15mg daily         |                                         |
+----------------------+--------------------+                                         |
| 15–29                | 15mg daily\        |                                         |
|                      | (Use with caution) |                                         |
+----------------------+--------------------+-----------------------------------------+
| <15                  | Avoid              | Avoid                                   |
+----------------------+--------------------+-----------------------------------------+
:::

:::column-margin
: Apixaban Dosing

+-----------------+----------------+----------------------------------+
| Non-valvular AF | VTE Prevention | VTE Treatment                    |
+=================+================+==================================+
| 5mg BD          | 2.5mg BD       | 10mg BD for 7 days, then 5 mg BD |
+-----------------+----------------+----------------------------------+
:::

**Key** pharmacological **properties**:

:::column-margin
DOAC may be preferable to VKA for both VTE and stroke prevention in AF.
:::

* Are 60-80% renally cleared\
Apixaban is the notable exception, with only 25% of the drug renally cleared.
* Hepatic metabolism is via CYP450 enzymes
* Elimination half-life of 7-12 hours
* Have fixed dosing
* Do not require monitoring
	* ↑ Therapeutic time compared to VKA
	* ↓ ICH risk compared to VKA
	* No drug interactions


**Monitoring**:

* Monitoring of anticoagulant effect is more difficult compared to VKA
* Coagulation assays **qualitatively assess** the **presence** of a **coagulation effect**, but not the degree
	* ↑ APTT and ↑ TCT occurs with thrombin inhibition\
	i.e. Dabigatran.
	* ↑ PT occurs with Factor Xa inhibition\
	Requires an appropriate DOAC-sensitive reagent.
* Specific drug assays are available, although drug levels corresponding to therapeutic anticoagulation are not widely available


**Reversal**:

* Reversal options are limited
* Dabigatran
	* Idrarucizumab 5g IV
		* Monoclonal antibody
		* Rapidly effective
	* Factor replacement\
	Significantly ↓ efficacy.
	* Dialysis\
	Limited efficacy, 2^nd^ line to idrarucizumab.
* Xa inhibitors
	* Andexanaet alfa 400mg IV bolus, then 4mg/min for 4 hours
		* Recombinant factor Xa, which acts as a decoy receptor for circulating inhibitor
		* Binds to rivaroxaban, apixaban, and enoxaparin


## Technique

## Complications


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.
1. Ansell J, Hirsh J, Poller L, Bussey H, Jacobson A, Hylek E. [The Pharmacology and Management of the Vitamin K Antagonists](https://linkinghub.elsevier.com/retrieve/pii/S0012-3692(15)31492-6). Chest. 2004;126(3):204S-233S. doi:10.1378/chest.126.3_suppl.204S
1. Tran HA, Gibbs H, Merriman E, et al. [New guidelines from the Thrombosis and Haemostasis Society of Australia and New Zealand for the diagnosis and management of venous thromboembolism](https://onlinelibrary.wiley.com/doi/full/10.5694/mja2.50004). Medical Journal of Australia. 2019;210(5):227-235. doi:10.5694/mja2.50004
