# Transfusion Overview {#sec-transfusion}



## Blood Typing

Blood typing is matching donated products to the donor, and is done to balance the:

* Risk of haemolytic transfusion reactions
* Urgency of required transfusion
* Allocation of scare resources


Blood products can be divided based on the degree of typing required:

* **Untyped**\
Immediately available. Use of untyped blood:
	* Consumes limited pool of universal units
	* Is justified in patients needing emergency transfusion
	* Is not justified in patients stable enough to wait until crossmatching is complete
	* Has a higher risk of transfusion reaction\
	Risk is from minor antibodies.
		* Present in **2% of population**\
		Prevalence **↑ with age**.
		* Typically IgG mediated
		* Does not generally cause major haemolysis\
		Overall **haemolysis rate of emergency transfusion is 0.1%**.
	* For **packed red cells** is **O-**
		* Rh- (or unknown) females of childbearing age should receive O-\
		Risk of rhesus disease if Rh+ blood given.
			* If prolonged/repeated transfusion required, use of Rh+ blood can be justified due to limited availability of Rh- blood
	* For **plasma** is usually **AB+**, but can be A+ with **low anti-B**\
	Justified due to:
		* Very limited supply of AB+ plasma
		* Low risk of significant reactions in B patients receiving incompatible group A plasma:
			* Low overall presence of AB+ and B+ individuals
			* Dilution of recipient group B RBCs with untyped
			* Low risk of significant reaction in B patients 

:::column-margin
Each subsequent stage results in a significantly smaller ↓ in the absolute risk of incompatibility - the greatest gains are had with blood grouping and typing.
:::

* **Group-specific uncrossmatched blood**\
	* Prevents ABO reaction
	* 99.8% chance of compatibility
	* Generally available within 5-10 minutes\
\
* **Group-specific partial crossmatch**
	* 99.94% chance of compatibility\
\
* **Group-specific fully crossmatched**
	* 99.95% chance of compatibility
	* Generally available in 30-45 minutes


### Typing Process

Testing a recipient and preparing donor blood for transfusion involves **three stages**:

1. Blood group (ABO and Rhesus) typing\
Takes ~15 minutes.
2. Antibody screen\
Screening for minor antibodies other than anti-A and anti-B.
	* **If** antibody screen is **normal**, computer cross-match can typically match unit of blood in <5 minutes
	* Otherwise a prolonged cross-match is required, which may take **45 minutes to** several **hours**
3. Crossmatching


## Blood Products

Include:

* Packed cells
* Fresh frozen plasma
* Factor concentrates
* Cryoprecipitate
* Fibrinogen concentrate
* Platelets


### Packed Cells

Donor blood is cytapheresed to produce cells and a small volume of carrier plasma. PRBC:

* 1 unit ≈ 200-300mL\
Generally raises Hb by ~10g/dL.


:::column-margin
The small amount of incompatible plasma that is transfused with unmatched (e.g. O-) RBCs is not considered to be clinically significant.
:::


### Fresh Frozen Plasma

Donor plasma remaining after cytapheresis of RBC, which is then frozen and re-thawed prior to use. FFP:

* 1 unit ≈ 200-300 ml\
Contains normal levels of clotting factors, albumin, and immunoglobulin:
	* ~0.5g of fibrinogen
	* 0.7 IU/mL of Factor VIKI
* Dose is usually 10-15ml/kg\
This is a substantial volume for a normovolaemic patient - consider factor concentrates.
* Stored at -18°C to prevent clotting factor degradation\
Must be thawed prior to administration.
* ABO compatibility highly desirable but not essential

:::column-margin
FFP should not be used as a volume expander for hypovolaemia in absence of an appropriate indication.
:::

### Factor IX Complex

Factor IX complex:

:::column-margin
Factor IX complex is also known as prothrombin complex concentrate.
:::

* Freeze-dried preparation from donor plasma
* Contains the vitamin-K dependent clotting factors
	* Factor II
	* Factor VII
	* Factor IX
	* Factor X
* Indicated for:
	* Correction of vitamin K antagonism
	* Correction of coagulopathy in absence of hypovolaemia

:::column-margin
I find Factor IX complex useful in the operating room for *rapidly* correcting coagulopathy, as it can be given far more quickly than an equivalent factor-load of FFP.
:::

### Single-Factor Concentrates

Donor plasma isolated or recombinant production of concentrated:

* AT III
* Activated factor VII
* Factor VIII
	* Heat treated to inactivate HIV
	* For treatment of haemophilia A
* Factor IX


### Cryoprecipitate

Derivative of FFP which:

:::column-margin
Manufactured by freezing and then thawing FFP, collecting the precipitate, and then re-suspending it in plasma.
:::

* May be presented as:
	* Single donor\
	30-40mL.
	* Apheresis\
	~50mL.
* Stored at -18°C
* Contains concentrated:
	* **Fibrinogen**\
	Main advantage, as there is little fibrinogen in FFP.
	* Factor VIII
	* Factor XIII
	* Fibronectin
	* vWF


### Fibrinogen Concentrate

Freeze-dried human plasma:

* Contains ~1g of fibrinogen
* Reconstituted with water
* Used in massive transfusion


### Platelets

* 1 unit ≈ 50mL\
Generally raises platelet cont by ~10× 10^9^/L.
* ABO match preferable but not essential


:::column-margin
The volume of incompatible plasma administered with platelets is significantly higher (due to greater platelet volume), but because of greater limitations in platelet availability the higher risk is assumed necessary.
:::


---

## References

1. Yazer MH, Waters JH, Spinella PC, et al. Use of Uncrossmatched Erythrocytes in Emergency Bleeding Situations. Anesthesiology. 2018;128(3):650-656.
2. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.