# Immunosuppressants

Intentional suppression of the immune system to prevent a harmful immune response, but ↑ susceptibility to infection and malignancy.

:::column-margin
The nomenclature used here distinguishes between immuno*suppression* (iatrogenic use of medication to dampen an immune response) versus immunocompromise, an umbrella term for both iatrogenic and pathological (e.g. diabetes, HIV/AIDS) causes.
:::

## Indications

* Normalise hyper-active immune system
	* Autoimmune disease
* Suppress normal immune system
	* Prevent allograft rejection in organ transplantation


## Contraindications

## Principles

### Key Terms

* **Induction immunosuppression**\
Immediate use of high-intensity immunosuppression after transplantation.
* Maintenance immunosuppression
* **Cytokine release syndrome**\
Occurs due to initial T-cell activation and is characterised by fever, hypotension, and pulmonary oedema.
* **Fusion protein**\
Created by joining genes that initially coded for different proteins.


### Medications

: Comparison of Immunosuppressants

+----------------------------------+------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------+
| Immunosuppressive drug           | Class of Drug                                  | Mechanism of Action                                                                                                                   | Considerations                                                                       |
+==================================+================================================+=======================================================================================================================================+======================================================================================+
| Antithymocyte globulin           | Polyclonal antibody                            | Animal immunoglobulin targeted to human T-cells, which block T-cell membrane proteins modulating their homing and cytotoxic function. | * Indicated for induction immunosuppression and steroid-resistant rejection          |
|                                  |                                                |                                                                                                                                       | * Cytokine-release syndrome                                                          |
|                                  |                                                |                                                                                                                                       | * Persistent, profound lymphopenia                                                   |
|                                  |                                                |                                                                                                                                       | * ↑ Post-transplant lymphoma                                                         |
|                                  |                                                |                                                                                                                                       | * Rabbit ATG preferred to horse ATG due to ↓ rejection and ↑ tolerability            |
+----------------------------------+------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------+
| Alemtuzumab\                     | Monoclonal antibody                            | Humanised rat IgG1 anti-CD52 antibody, depleting:                                                                                     | * Indicated for induction immunosuppression and steroid-resistant rejection          |
| (CAMPATH-1H)                     |                                                |                                                                                                                                       | * Cytokine-release syndrome                                                          |
|                                  |                                                | * T-cells                                                                                                                             | * Autoimmune disease                                                                 |
|                                  |                                                | * B-cells                                                                                                                             | * Persistent, profound lymphopenia                                                   |
|                                  |                                                | * NK cells                                                                                                                            |                                                                                      |
|                                  |                                                | * Monocytes                                                                                                                           |                                                                                      |
+----------------------------------+------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------+
| Rituximab                        | Monoclonal antibody                            | Anti-CD20 antibody, causing:                                                                                                          | * Induction immunosuppression                                                        |
|                                  |                                                |                                                                                                                                       | * Infusion-related reactions                                                         |
|                                  |                                                | * B-cell depletion                                                                                                                    |                                                                                      |
|                                  |                                                | * ↓ T-cell proliferation                                                                                                              |                                                                                      |
+----------------------------------+------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------+
| Basiliximab                      | Non-depleting monoclonal antibody              | Chimeric human-mouse monoclonal anti-CD25 antibody, causing:                                                                          | * Hypersensitivity reactions                                                         |
|                                  |                                                |                                                                                                                                       |                                                                                      |
|                                  |                                                | * ↓ IL-2-induced T-cell proliferation\                                                                                                |                                                                                      |
|                                  |                                                | But not depletion.                                                                                                                    |                                                                                      |
+----------------------------------+------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------+
| Belatacept                       | Fusion protein                                 | Blocks co-stimulation by binding to CD80 and CD86 receptors on APCs and prevents binding to CD28 on the T-cell                        | * Post-transplant lymphoproliferative disease\                                       |
|                                  |                                                |                                                                                                                                       | Only in EBV negative, so should be restricted to EPB positive patients.              |
|                                  |                                                |                                                                                                                                       | * Bone marrow suppression                                                            |
|                                  |                                                |                                                                                                                                       | * Hypertension                                                                       |
|                                  |                                                |                                                                                                                                       | * Dyslipidemia                                                                       |
+----------------------------------+------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------+
| Azathioprine                     | Antimetabolite or antiproliferative            | ↓ Purine synthesis, which ↓ T-cell proliferation                                                                                      |                                                                                      |
|                                  |                                                |                                                                                                                                       | * Leukopenia and thrombocytopenia                                                    |
|                                  |                                                |                                                                                                                                       | * Nausea and vomiting                                                                |
|                                  |                                                |                                                                                                                                       | * Hepatotoxicity                                                                     |
|                                  |                                                |                                                                                                                                       | * Malignancy                                                                         |
+----------------------------------+------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------+
| Mycophenolate mofetil            | Antimetabolite or antiproliferative            | Inhibits inosine monophosphate dehydrogenase, ↓ T and B-cell proliferation                                                            | * Maintenance immunosuppression                                                      |
|                                  |                                                |                                                                                                                                       | * More selective than azathioprine                                                   |
|                                  |                                                |                                                                                                                                       | * Neutropenia                                                                        |
|                                  |                                                |                                                                                                                                       | * Anorexia, abdominal pain, gastritis and diarrhea                                   |
|                                  |                                                |                                                                                                                                       | * Opportunistic infections                                                           |
|                                  |                                                |                                                                                                                                       | * Teratogenic                                                                        |
+----------------------------------+------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------+
| Cyclosporine                     | Calcineurin inhibitor                          | Inhibits calcineurin by binding cyclophilin, causing:                                                                                 | * Maintenance immunosuppression                                                      |
|                                  |                                                |                                                                                                                                       | * Acute and chronic nephrotoxicity                                                   |
|                                  |                                                | * ↓ T-cell proliferation                                                                                                              | * Diabetes                                                                           |
|                                  |                                                | * ↓ Cytokine production                                                                                                               | * Hypomagnesemia and hyperkalemia                                                    |
|                                  |                                                |                                                                                                                                       | * Neurotoxicity                                                                      |
|                                  |                                                |                                                                                                                                       | * Malignancy                                                                         |
+----------------------------------+------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------+
| Tacrolimus                       | Calcineurin inhibitor                          | Inhibits calcineurin by binding FK506-binding protein 12, causing:                                                                    | * As cyclosporine except:                                                            |
|                                  |                                                |                                                                                                                                       |   * ↓ Incidence of hyperlipidemia, hypertension, hirsutism, and gingival hyperplasia |
|                                  |                                                | * ↓ Cytokine production                                                                                                               |   * ↑ Incidence of: diabetes, neurotoxicity                                          |
|                                  |                                                | * ↓ T-cell proliferation                                                                                                              |   * Better outcomes than cyclosporine for transplantation                            |
+----------------------------------+------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------+
| Sirolimus, everolimus            | Mammalian target of rapamycin (mTOR) inhibitor | Inhibits mTOR by binding FK506-binding protein 12, causing ↓ T-cell proliferation                                                     | * Maintenance immunosuppression\                                                     |
|                                  |                                                |                                                                                                                                       | Alternative to calcineurin inhibitors in the setting of:                             |
|                                  |                                                |                                                                                                                                       |     * Neurotoxicity                                                                  |
|                                  |                                                |                                                                                                                                       |     * SCC or Karposi's sarcoma\                                                      |
|                                  |                                                |                                                                                                                                       |     Anti-tumour properties.                                                          |
|                                  |                                                |                                                                                                                                       | * Delayed wound healing                                                              |
|                                  |                                                |                                                                                                                                       | * Leukopenia and thrombocytopenia                                                    |
|                                  |                                                |                                                                                                                                       | * Increased risk of infections                                                       |
|                                  |                                                |                                                                                                                                       | * Anaphylaxis and hypersensitivity reactions                                         |
+----------------------------------+------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------+
| Prednisolone, methylprednisolone | Corticosteroid                                 | Broad array of effects by:                                                                                                            | * Induction and maintenance immunosuppression                                        |
|                                  |                                                |                                                                                                                                       | * ↓ Wound healing                                                                    |
|                                  |                                                | * Direct genomic                                                                                                                      | * Opportunistic infections                                                           |
|                                  |                                                |     * ↓ Prostaglandin synthesis                                                                                                       | * Sleep disturbances and mood changes                                                |
|                                  |                                                |     * ↑ Anti-inflammatory protein synthesis                                                                                           | * Cushing syndrome                                                                   |
|                                  |                                                |     * ↓ Inflammatory protein synthesis                                                                                                | * ↑ BSL                                                                              |
|                                  |                                                | * Indirect genomic                                                                                                                    | * HTN                                                                                |
|                                  |                                                |     * ↓ Prostaglandin synthesis                                                                                                       | * Dyslipidaemia                                                                      |
|                                  |                                                | * Non-genomic                                                                                                                         | * Osteoporosis                                                                       |
|                                  |                                                |     * ↑ NO synthetase                                                                                                                 |                                                                                      |
+----------------------------------+------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------+


## Practice


## Complications


## Key Studies

---

## References

1. Claeys E, Vermeire K. [Immunosuppressive drugs in organ transplantation to prevent allograft rejection: Mode of action and side effects](https://www.immunologyresearchjournal.com/articles/immunosuppressive-drugs-in-organ-transplantation-to-prevent-allograft-rejection-mode-of-action-and-side-effects.html). Journal of Immunological Sciences. 2019;3(4). Accessed July 13, 2023. https://www.immunologyresearchjournal.com/articles/immunosuppressive-drugs-in-organ-transplantation-to-prevent-allograft-rejection-mode-of-action-and-side-effects.html
1. Pilch NA, Bowman LJ, Taber DJ. [Immunosuppression trends in solid organ transplantation: The future of individualization, monitoring, and management](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8778961/). Pharmacotherapy. 2021;41(1):119-131. doi:10.1002/phar.2481
