# Blood Typing

Blood typing is matching donated products to the donor, and is done to balance the:

:::column-margin
A Brief Refresher on Blood Types:

* RBC may express either type A, type B, both, or no antigen
* The blood group refers to what antigen your RBC express\
The O blood group express no antigen on the RBC.
* Plasma contains IgM antibody to non-expressed antigens\
These are developed within 3-6 months of birth.
* Therefore, the following can be given to anyone with risk of *ABO* incompatibility:
	* Type O *RBC*, as they **express** no antigen\
	Thus, type O are referred to as the universal donor.
	* Type AB *plasma*, as it **contains** no antibody\
	Type AB have unjustly been referred to as the universal recipient, which is only true in an erythro-centric model of the universe.
:::

* Risk of haemolytic transfusion reactions
* Urgency of required transfusion
* Allocation of scare resources


Blood products can be divided based on the degree of typing required:

* **Untyped**\
Immediately available. Use of untyped blood:
	* Consumes limited pool of universal units
	* Is justified in patients needing emergency transfusion
	* Is not justified in patients stable enough to wait until crossmatching is complete
	* Has a higher risk of transfusion reaction\
	Risk is from minor antibodies.
		* Present in **2% of population**\
		Prevalence **↑ with age**.
		* Typically IgG mediated
		* Does not generally cause major haemolysis\
		Overall **haemolysis rate of emergency transfusion is 0.1%**.
	* For **packed red cells** is **O-**
		* Rh- (or unknown) females of childbearing age should receive O-\
		Risk of rhesus disease if Rh+ blood given.
			* If prolonged/repeated transfusion required, use of Rh+ blood can be justified due to limited availability of Rh- blood
	* For **plasma** is usually **AB+**, but can be A+ with **low anti-B**\
	Justified due to:
		* Very limited supply of AB+ plasma
		* Low risk of significant reactions in B patients receiving incompatible group A plasma:
			* Low overall presence of AB+ and B+ individuals
			* Dilution of recipient group B RBCs with untyped
			* Low risk of significant reaction in B patients 

:::column-margin
Each subsequent stage results in a significantly smaller ↓ in the absolute risk of incompatibility - the greatest gains are had with blood grouping and typing.
:::

* **Group-specific uncrossmatched**\
	* Prevents ABO reaction
	* 99.8% chance of compatibility
	* Rhesus-matching is mandatory in children and women of childbearing potential\
	Prevent maternal antibody causing foetal haemolysis and subsequent miscarriage/death of an Rh+ foetus.
	* Generally available within 5-10 minutes\
\
* **Group-specific partial crossmatch**
	* 99.94% chance of compatibility\
\
* **Group-specific fully crossmatched**
	* 99.95% chance of compatibility
	* Generally available in 30-45 minutes


## Typing Process

Testing a recipient and preparing donor blood for transfusion involves **three stages**:

1. **Blood group** (ABO and Rhesus) typing\
Takes ~15 minutes.
	* Forward gropuing\
	Patient RBC mixed with anti-A and anti-B antibodies; agglutination indicates antigen presence.
	* Reverse grouping\
	Patient plasma mixed with known type A or type B RBC; agglutination indicates antibody presence.
	* Forward and reverse grouping tests must agree to confirm an ABO  grouping\
	Divergence indicate:
		* Recent incompatible transfusion
		* Foetomaternal haemorrhage
		* Presence of a strange antibody.
	* Rhesus typing performed with known anti-D serum.
2. **Antibody screen**\
Screening for minor antibodies other than anti-A and anti-B.
3. **Crossmatching**\
Testing of patients blood with a *particular* donated sample to make sure they are compatible.
	* Detects:
		* ABO incompatibility\
		Should be determined by the previous round of testing.
		* Minor antibody presence
	* Speed depends on the antibody screen:
		* A computer cross-match can typically match a unit of blood in <5 minutes, if the minor antibody screen is normal
		* An abnormal minor antibody screen requires a prolonged (usually manual) cross-match, which may take **45 minutes to** several **hours**

---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.
1. Yazer MH, Waters JH, Spinella PC, et al. Use of Uncrossmatched Erythrocytes in Emergency Bleeding Situations. Anesthesiology. 2018;128(3):650-656.