# Transjugular Intrahepatic Portosystemic Shunt

:::gas
**Airway**: 
**Access**: 
**Pain**: 
**Position**:
**Time**: 
**Blood loss**:
**Special**:
:::

Creation of a direct communication between a hepatic vein and the portal vein, decompressing the portal circulation and reducing the sequelae of portal hypertension. 

Indications include:

* Acute variceal bleeding
* Variceal disease
* Refractory ascites
* Hypertensive gastropathy
* Hepatorenal syndrome
* Budd-Chiari syndrome not responsive to anticoagulation

## Surgical Stages

## Preoperative

**Assessment:**

* Right heart failure\
↑ VR and RV preload.
* Concurrent infection\
↑ Risk of stent infection.

**Consultation:**

**Optimisation:**

**Premedication:**

**Explain/Consent:**


## Intraoperative

**Preparation:**

**Induction:**

**Maintenance:**

**Echocardiography:**

**Emergence:**

## Postoperative

**Disposition:**

**Referrals/Review:**

**Analgesia:**

**Fluids:**

**Thromboprophylaxis:**

**Specific:**

* Complications include:
	* C
		* Tricuspid endocarditis
		* Right heart failure
	* D
		* Worsening hepatic encephalopathy\
		May worsen due to diversion of unfiltered blood.
	* G
		* Portal vein thrombosis
		* Ischaemic hepatitis\
		Hepatic ischaemia may occur due to ↓ portal venous flow.
	* I
		* Shunt infection

---

## References