# Tracheostomy Insertion

Place at 2-3 ring to minimise fistula risk.

The outer tube should not be changed for at least **1 week** to allow the tract to mature. If it does, someone skilled in airway management and prepared to intubate should be present.

## Technique

### Top End

* Insert bronchoscope to carina
* Withdraw ETT into mouth whilst ensuring bronchoscope remains in trachea
* Over-inflate ETT cuff in the oropharynx
* Advance ETT over bronchoscope so it is abutting the vocal cords, and secure with gentle forwards pressure 

---

## References


1. De Leyn, Paul, Lieven Bedert, Marion Delcroix, Pieter Depuydt, Geert Lauwers, Youri Sokolov, Alain Van Meerhaeghe, Paul Van Schil, and Belgian Association of Pneumology and Belgian Association of Cardiothoracic Surgery. [Tracheotomy: Clinical Review and Guidelines](https://doi.org/10.1016/j.ejcts.2007.05.018). European Journal of Cardio-Thoracic Surgery: Official Journal of the European Association for Cardio-Thoracic Surgery 32, no. 3 (September 2007): 412–21.

