Innervation of the lower extremities occurs via the **lumbosacral plexus**, which divides into the:

* Sciatic nerve
* Femoral nerve


### Sciatic Nerve and Branches

The sciatic nerve:

* Arises from L4-S3
* Directly provides:
	* Motor supply to the posterior compartment of thigh
	* Sensory supply to posterior thigh
* Divides at a variable location (but usually close to the popliteal fossa) into the:
	* **Common peroneal nerve**  
	Divides at the knee into two branches which provides sensation to the posterolateral leg: 
		* **Superficial peroneal nerve**  
		Provides sensation to dorsum of foot and toes.
		* **Deep peroneal nerve**  
		Provides sensation to the web space between the great and second toe.
	* **Tibial nerve**  
	Innervates the posterior compartment and sole of the foot. Gives off the:
		* **Sural nerve**  
		Provides sensation to the heel, back of the ankle, and the lateral malleolus.
		* **Posterior tibial nerve**



### Femoral Nerve and Branches

The femoral nerve:  
* Arises from L2-4  
Largest branch.
* Directly provides:
	* Motor supply to knee extensors
	* Sensory supply to anteromedial thigh
* Divides into the:
	* **Obturator nerve**  
	Formed from L2-4, and enters thigh through obturator foramen. Provides:
		* Motor supply to hip adductors
		* Sensory supply to a variable aspect of the medial thigh/knee
	* **Lateral femoral cutaneous nerve**  
	Formed from L2-3, and runs on ventral surface of iliacus, beneath fascia iliaca. Provides:
		* Sensory supply to lateral aspect of thigh and knee
	* **Saphenous nerve**  
		* Lies in the adductor canal, close to the femoral artery and vein  
		Deep to sartorius and superficial to vastus medialis.
			* Typically not visible on ultrasound  
			May be seen as a small, round, hyperechoic structure medial to the artery.
			* Typically 2-3cm deep
		* Entirely sensory nerve, providing sensation to medial lower leg and ankle.