# Abdominal Compartment Syndrome

Raised intraabdominal pressure:

* Impairs venous outflow, resulting in:
	* ↓ Systemic VR
	* ↓ Renal and splanchnic blood flow
* Is classified into:
	* Intraabdominal hypertension\
	IAP **>12mmHg**.
	* Abdominal compartment syndrome\
	IAP **>20mmHg**.


## Epidemiology and Risk Factors

## Pathophysiology

↑ Volume of abdominal contents leads to an ↑ IAP, and is usually the result of gut oedema. Precipitants include:

* Trauma
	* Laparotomy
* Capillary leak
	* Sepsis
* Fluid administration

## Clinical Manifestations

## Diagnostic Approach and DDx

## Investigations

## Management

**Resuscitation**:\

ABC approach. Comment on team coordination and clinical priorities.
**Specific therapy**:

* Pharmacological
* Procedural
	* Decompressive laparotomy with temporary fascial closure
* Physical

**Supportive care**:

**Disposition**:

### Marginal and Ineffective Therapies

## Anaesthetic Considerations

## Complications

## Prognosis

## Key Studies


---

## References
