# Cardiac Arrest {#sec-arrest}

:::column-margin
This covers cardiac arrest. Components of post-arrest care, including interventions performed immediately following ROSC (e.g. angiography) are covered under @sec-post_arrest.
::: 

## Epidemiology and Risk Factors

IHCA:

* ~10/100,000 admissions
* Majority are expected and occur without attempt at resuscitation

OOHCA:

* 50-150/100,000 person-years


## Pathophysiology

### Aetiology

Management requires identification and correction of **reversible** cause:

* Hypoxia
* Hypovolaemia
* Hyper/hypokalaemia\
* Hypo/hyperthermia
* Tension pneumothorax
* Tamponade
* Toxins
* Thrombosis
	* Coronary
	* Pulmonary (embolism)

## Investigations

## Management

### Basic Life Support

Pillars of basic life support:

* **D**anger
* **R**esponse
* **S**end for help
* Open **A**irway
* Normal **B**reathing?\
* Start **C**PR
	* 30 compressions:2 breaths
	* 100 compressions/minute
	* 1/3^rd^ depth of chest
	* Lower half of sternum\
	Above this is less effective, below has ↑↑ risk of solid organ injury.

### Advanced Life Support

:::column-margin
In a witnessed and monitored arrest, with **pads already attached**, it is **ideal** to perform **3 stacked** (repeated) **shocks** prior to commencing CPR.\
\
In a witnessed and monitored arrest, **without pads**, it is *reasonable* to perform a precordial thump.
:::

* A
	* Airway\
	Adequate airway for gas exchange is the goal. Attempts at securing a definitive airway may excessively prolong time without CPR or gas exchange, without improving survival.
* B
	* End-tidal CO~2~
		* Correlates with cardiac index
		* Allows detection of ROSC
* C
	* Attach **D**efibrillator
		* 200J biphasic or 360J monophasic
		* Anterior-Posterior pad position may be slightly preferable as it is less dependent on heart position


## Marginal and Ineffective Therapies

## Complications

* Death
* C
	* Ischaemic injury
	* CPR complications
		* Rib/sternal fractures
		* Solid organ injury
* D
	* Hypoxic brain injury
	* Seizures\
	In ~36% of patients after ROSC.


## Prognosis

In-hospital cardiac arrest has a surprisingly good overall prognosis:

:::column-margin
Neuroprognostication is covered under @sec-neuroprog.
:::

* Hospital discharge in 52%\
Multifactorial:
	* Early detection
	* Early arrival of ALS


Out-of-hospital cardiac arrest requiring ICU admission is significantly worse:

* 80% are comatose
* ~60% die with HIE\
The **most common cause of death** is **withdrawal** of life sustaining **therapy**.


## Key Studies

:::info
Many key trials include only OOHCA or IHCA even though the therapy could conceivably benefit patients in either group.\
\
It is unclear how generalisable results in one group are to the other, given the disparities in aetiology and outcome.
:::

:::column-margin
This includes key trials on the management of cardiac arrest. Trials evaluating interventions that occur after achieving ROSC (e.g. angiography, hypothermia) are covered under @sec-post_arrest.
:::

**ECMO**:

* Observation studies indicate improved survival following OOHCA with ECMO compared to standard care
{{< include /trials/arrest.qmd >}}


**Other**:

{{< include /trials/paramedic2.qmd >}}
{{< include /trials/dosevf.qmd >}}
{{< include /trials/coca.qmd >}}
{{< include /trials/vam_ihca.qmd >}}


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.
1. Schmidt H, Kjaergaard J, Hassager C, et al. Oxygen Targets in Comatose Survivors of Cardiac Arrest. New England Journal of Medicine. 2022;387(16):1467-1476. doi:10.1056/NEJMoa2208686
1. Andersen LW, Isbye D, Kjærgaard J, et al. [Effect of Vasopressin and Methylprednisolone vs Placebo on Return of Spontaneous Circulation in Patients With In-Hospital Cardiac Arrest: A Randomized Clinical Trial](https://jamanetwork.com/journals/jama/fullarticle/2784625). JAMA. 2021;326(16):1586–1594. doi:10.1001/jama.2021.16628
1. Cheskes S, Verbeek PR, Drennan IR, et al. [Defibrillation Strategies for Refractory Ventricular Fibrillation](https://www.nejm.org/doi/pdf/10.1056/NEJMoa2207304). N Engl J Med. 2022;387(21):1947-1956.
1. Vallentin MF, Granfeldt A, Meilandt C, et al. [Effect of Intravenous or Intraosseous Calcium vs Saline on Return of Spontaneous Circulation in Adults With Out-of-Hospital Cardiac Arrest: A Randomized Clinical Trial](https://jamanetwork.com/journals/jama/fullarticle/2786819). JAMA. 2021;326(22):2268–2276.
1. Desch S, Freund A, Akin I, et al. [Angiography after Out-of-Hospital Cardiac Arrest without ST-Segment Elevation](https://www.nejm.org/doi/full/10.1056/NEJMoa2101909). New England Journal of Medicine. 2021;385(27):2544-2553.
1. Lemkes JS, Janssens GN, Van Der Hoeven NW, et al. [Coronary Angiography after Cardiac Arrest without ST-Segment Elevation](https://www.nejm.org/doi/full/10.1056/NEJMoa1816897). N Engl J Med. 2019;380(15):1397-1407.
1. Dankiewicz J, Cronberg T, Lilja G, et al. [Hypothermia versus Normothermia after Out-of-Hospital Cardiac Arrest](https://www.nejm.org/doi/full/10.1056/NEJMoa2100591?query=featured_cardiology). New England Journal of Medicine. 2021;384(24):2283-2294. doi:10.1056/NEJMoa2100591
1. Yannopoulos D, Bartos J, Raveendran G, et al. [Advanced reperfusion strategies for patients with out-of-hospital cardiac arrest and refractory ventricular fibrillation (ARREST): a phase 2, single centre, open-label, randomised controlled trial](https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(20)32338-2/fulltext). The Lancet. 2020;396(10265):1807-1816. doi:10.1016/S0140-6736(20)32338-2
1. Lascarrou JB, Merdji H, Le Gouge A, et al. [Targeted Temperature Management for Cardiac Arrest with Nonshockable Rhythm](https://www.nejm.org/doi/full/10.1056/NEJMoa1906661). New England Journal of Medicine. 2019;381(24):2327-2337. doi:10.1056/NEJMoa1906661
1. Perkins GD, Ji C, Deakin CD, et al.[ A Randomized Trial of Epinephrine in Out-of-Hospital Cardiac Arrest](https://www.nejm.org/doi/full/10.1056/nejmoa1806842). New England Journal of Medicine. 2018;379(8):711-721. doi:10.1056/NEJMoa1806842
