# Cardiac Advanced Life Support

This section covers the algorithmic management of cardiac arrest in an adult patient who is **up to 14 days** after cardiac surgery.

:::column-margin
These patients are also typically:

* In the ICU  
* Invasively monitored
:::

## Protocol

This algorithm assumes that the patient has ECG and invasive arterial monitoring:

* **Recognition**  
Arrest is consistent with:
	* Loss of central pulse
	* Loss of haemodynamic waveform pulsatility
		* Systemic arterial pressure
		* Pulmonary arterial pressure
		* CVP
		* Pulse oximetry
	* Loss of ETCO~2~
* **Assess rhythm**
	* **VF/VT/Tachycardia**
		* DC shock  
		Up to 3 attempts.
		* Start BLS  
		CPR *may* be delayed up to 1 minute to facilitate cardioversion.
		* Amiodarone  
		300mg. Further loading of 150mg followed by infusion may be given for refractory VT/VF.
		* Prepare for emergency resternotomy
	* **Asystole/Severe bradycardia**
		* Pace  
		In DDD or DOO at 100bpm and at maximal amplitude.  
		* Start BLS  
		CPR *may* be delayed up to 1 minute to facilitate cardioversion.
		* Consider external pacing
		* Prepare for emergency resternotomy
	* **PEA**
		* If paced, turn off external pacing to exclude underlying VF
		* Start BLS
		* Prepare for emergency resternotomy
* **Adjuvant management**
	* Airway  
		* Change to BVM with 100% O~2~
	* Breathing  
		* PEEP to 0cmH~2~O  
		Improve cardiac preload in the setting of tamponade/hypovolaemia.
			* Consider increasing PEEP if arrest secondary to hypoxia
		* Auscultate/ultrasound to evaluate for tension pneumo/haemothorax  
		Decompress if present.
	* Circulation
		* Avoid adrenaline unless advised by senior clinician  
		Typical dose is 50-300ug.
		* Give fluid bolus
		* Activate massive transfusion
		* Pause infusions  
			* Evaluate for dosing/drug errors
			* Consider restarting vasopressor infusions
		* Lignocaine 1mg/kg may be considered as an alternative to amiodarone
		* Change IABP settings:
			* Pressure trigger
			* Maximum augmentation
			* 1:1 ratio
		* Consider echocardiography  
		Use should not delay CPR or resternotomy.
* **Evaluate for reversible causes**


External Cardiac Compressions:

* Standard site, depth, and compression ratio
* An SBP of >60mmHg should be targeted if invasive arterial monitoring is present
* Inability to achieve an SBP of >60mmHg with compressions indicates need for **immediate resternotomy**  
Indication of arrest due to low preload (and not amenable to cardiac compressions) - tamponade or hypovolaemia are likely causes.


### Emergency Resternotomy

:::caution
Resternotomy occurring ⩽10 minutes is associated with ~50% survival, compared to ~10% if >10 minutes
:::

Emergency resternotomy should be:

* Performed within 5 minutes of arrest  
Or immediately if SBP <60mmHg with external chest compressions.
* Considered in patients up to 14 days post surgery
* Prepared for immediately upon identification of cardiac arrest

Process:

* Cease chest compressions
* Remove sternotomy dressing, apply betadine, apply sterile drape  
Should be performed in ⩽10 seconds.
* Cut sternotomy incision and wires
	* Deep incision through sternotomy sutures down to sternal wires
	* Cut sternal wires
	* Remove sternal wires with heavy needle holder
* Suction blood and clot
* Open sternum with sternal retractor
* If no output despite opening sternum:
	* Consider internal defibrillation
	20J with internal paddles.
	* Commence internal cardiac massage
		* Avoid grafts
		* Right hand over apex and around behind the heart
		* Left hand over anterior surface of heart
		* Squeeze both hands together with flat palms and straight fingers  
		Aim SBP >60mmHg at a 100 bpm.

Post-procedural care:

* Transfer to OT
	* Washout
	* Consider closure
* Antibiotics
* Avoid fever  
Temperature ⩽36°C.

---

## References

1. Society of Thoracic Surgeons Task Force on Resuscitation After Cardiac Surgery. [The Society of Thoracic Surgeons Expert Consensus for the Resuscitation of Patients Who Arrest After Cardiac Surgery](https://www.ncbi.nlm.nih.gov/pubmed/28122680). Ann Thorac Surg. 2017 Mar;103(3):1005-1020.
2. Truhlar A, Deakin CD, Soar J et al. [European Resuscitation Council Guidelines for Resuscitation 2015: Section 4. Cardiac arrest in special circumstances](https://ercguidelines.elsevierresource.com/european-resuscitation-council-guidelines-resuscitation-2015-section-4-cardiac-arrest-special). Resuscitation 2015; 95: 148-201.