# Neonatal Resuscitation


This section covers resuscitation of the neonate. Neonatal resuscitation is:

* Required in ~5%  
The majority need gentle manoeuvres; drying, stimulation, warming. Need for:
	* Intubation and ventilation is unlikely
	* Compressions is rare  
	Those who require compressions generally do badly.
* Required more commonly in premature infants  
Poor alveolar expansion and reduced surfactant impair transition to adult circulation.


## Clinical Manifestations

Should cover:

* A
	* Patency  
	Crying indicates patency.
	* Presence of blood/meconium  
	Suction if present.
* B
	* Colour  
		* Normal to remain "hypoxic" for first 10 minutes of life  
		Bluish hands and feet are normal.
* C
	* HR > 130
* E
	* Spontaneous flexion and movements are sign of good tone  
	Suggest unlikely to be compromised.
	* Heat loss prevention is essential

### APGAR Score

Evaluation of a newborn:

* Used to determine whether they need medical intervention  
Poor scores at later times (e.g. 10-30 minutes post-delivery) do correlate with poor neurological outcome.
* Based on five criteria
* Performed at 1, 5, and 10 minutes post-delivery
* Scored out of 10  
0, 1, or 2 points in each category.

|Criterion|0|1|2|
|--|--|
|**A**ppearance|Blue or pale|Blue extremities|Pink|
|**P**ulse|Absent|<100bpm|>100bpm|
|**G**rimace|No response|Grimace to suction/aggressive stimulation|Cry on stimulation|
|**A**ctivity|None|Some flexion|Flexed limbs resisting extension|
|**R**espiration|Absent|Weak/irregular|Strong/robust|

## Management

Follows an ABC approach:

* A
	* Place supine
	* **Dry and stimulate**
	* Head neutral/slightly extended
	* Intubation can be considered if:
		* Unable to BMV
		* No detectable heart rate
* B
	* Commence CPAP with room air if HR >100 and there is laboured breathing or persistent cyanosis
	* Commence **PPV with room air** if HR ⩽100 after drying and stimulation  
	Generally Pip 30, PEEP 5, at a rate of 40-60/minute.
	* Transition to **100% oxygen if**:
		* SpO~2~ is ⩽70% **at 5 minutes**
		* HR ⩽100/min after 1 minute of PPV
		* Preparing for intubation
		* HR ⩽60/min and chest compressions indicated
* C
	* Commence chest compressions at **100-120** per minute if:  
	Need for chest compressions mostly occurs if PPV has not been performed correctly.
		* HR ⩽60/min despite adequate PPV with supplementary oxygen
	* Adrenaline 10-30µg/kg (0.1-0.3mL/kg of 1:10,000 solution) if HR < 60
	* Consider 10mL/kg IV crystalloid if blood loss suspected
* E
	* Warm
		* Radiant warmer
		* Polyethylene bag if ⩽1500g


### Target SpO~2~

> A rough rule of thumb is that the lower limit at birth is 60%, and ↑ by ~5% every minute


SpO~2~ should be measured **pre-ductally**, i.e. on the right arm or ear:

|Time (minutes)|Saturation|
|--|--|
|1|60-70%|
|2|65-85%|
|3|70-90%|
|4|75-90%|
|10|80-90%|


### Equipment

* General
	* Resuscitation trolley
	* Light source
	* Timer
* A
	* Suction and suction tubing
	* Oxygen masks
	* T-piece
	* Ventilation system
		* Neopuff
		* Self-inflating bag
		* Flow-inflating bag
	* Laryngoscope
	* ETT  
	In a range of sizes: 2.5-4.0.
	* Magill neonatal forceps
	* Sterile scissors
* B
	* Medical air
	* Medical oxygen
	* Flowmeters and tubing
* C
	* Fluid
	* Adrenaline
* E
	* Overhead warmer
	* Warmed towel
	* Polyethylene bag  

---

## References
