# Maternal Arrest


## Epidemiology and Risk Factors

* Rare
	* 1:20,000 pregnancies with an OOHCA

## Pathophysiology

Causes include:

* Common
	* PE (29%)
	* Haemorrhage (17%)
	* Sepsis (13%)
	* Cardiomyopathy (8%)
* Obstetric-specific
	* AFE
	* Neuraxial anaesthesia
	* Hypertensive disorders of pregnancy
* Other
	* Poisoning and self-harm
	* Anaphylaxis


Key changes:

* ↑ CO, VO~2~, and ↓ FRC\
Hypoxaemia occurs more quickly.
* Gravid uterus compresses abdominal organs

## Modifications to Standard Life Support

ALS:

* Call for obstetrician and neonatologist
* If **>20 weeks or uterus palpable above the umbilicus**:
	* Prepare for emergency hysterotomy
	* Manually displace the uterus, and place wedge to achieve lateral tilt\
	15-30°.
* Plan for early intubation
↑ Aspiration risk.
* If indicated, perform **emergency hysterotomy**:
	* **If resuscitation not successful within 4 minutes**
	* Aiming for **delivery within 5 minutes** of arrest\
	i.e. 1 minute between initiation of procedure and completed delivery.


---

## References