# Hypernatraemia {#sec-hyper_na}

Serum sodium concentration >145mmol/L occurring due to a deficit of free water relative to sodium levels.

## Epidemiology and Risk Factors

## Pathophysiology

### Aetiology

: Causes of Hypernatraemia

+----------------------+-----------------------+
| Water Loss           | Salt Gain             |
+======================+=======================+
| Renal:               | * Iatrogenic          |
|                      | * Sea-water ingestion |
| * Hyperaldosteronism | * Excess salt         |
| * Diabetes Insipidus |                       |
| * Glucosuria         |                       |
| * Drugs              |                       |
|     * Loop diuretics |                       |
|     * Mannitol       |                       |
|     * Urea           |                       |
|                      |                       |
| Extra-renal:         |                       |
|                      |                       |
| * Gastric            |                       |
| * Burns              |                       |
| * Diarrhoea          |                       |
| * Dehydration        |                       |
|     * Exposure       |                       |
|     * Exercise       |                       |
+----------------------+-----------------------+


:::column-margin
Diabetes insipidus is covered in detail under @sec-di.
:::

## Clinical Features

:::info
Significant neurological features typically emerge when Na^+^ > 155mmol/L.
:::

* Polydipsia
* Confusion
* Obtundation → Coma
* Seizures
* Hyperthermia


## Assessment

### History

### Exam

### Investigations

**Bedside**:

**Laboratory**:

**Imaging**:

**Other**:

### Diagnostic Approach and DDx


## Management

:::priority
* **Correct** free **water deficit**\
Avoid rapid correction to minimise cerebral osmotic shifts.
:::

**Resuscitation**:

**Specific therapy**:

:::column-margin
{{< include /includes/free_water.qmd >}}
:::

* Pharmacological
* Procedural
* Physical

**Supportive care**:

**Disposition**:

**Preventative**:


### Marginal and Ineffective Therapies

## Anaesthetic Considerations

## Complications

* D
	* Subarachnoid haemorrhage\
	Due to cerebral osmotic effects, causing excessive ↓ cerebral volume causing vascular injury.

## Prognosis

## Key Studies


---

## References

1. Adrogué HJ, Madias NE. [Hypernatremia](https://www.nejm.org/doi/full/10.1056/nejm200005183422006). N Engl J Med. 2000;342(20):1493-1499. doi:10.1056/NEJM200005183422006