# Hypokalaemia {#sec-hypo_k}

Serum potassium level <3.5mmol/L, classified by magnitude into:

* **Mild**\
3.0-3.4.
* **Moderate**\
2.5-2.9.
* **Severe**\
<2.4.

## Epidemiology and Risk Factors

## Pathophysiology

### Aetiology

Causes include:

* **↓ Potassium intake**
	* Dietary\
	<1g/day.
* **Redistribution**
	* Alkalosis
	* Drugs
		* Insulin
		* β-agonism
* **↑ Potassium loss**
	* GI
		* Diarrhoea
		* Vomiting
		* Ileostomy
		* Fistulae
		* Villous adenoma
	* Renal
		* Hypomagnesaemia	
		* Nephrogenic DI
		* Bartter's syndrome
		* Liddle's syndrome
		* Gitelman's syndrome
	* Hyperaldosteronism
	* Drugs
		* Diuretics
		* Laxative abuse
		* Licorice
		* Steroids
	* RRT


## Clinical Features

## Assessment

### History

### Exam

### Investigations

**Bedside**:

**Laboratory**:

**Imaging**:

**Other**:

* ECG
	* ↑ P wave amplitude
	* Prolonged PR interval
	* ST depression, T-wave flattening or inversion
	* U waves

### Diagnostic Approach and DDx


## Management

:::priority
Goals of management
:::

**Resuscitation**:

**Specific therapy**:

* Pharmacological
* Procedural
* Physical

**Supportive care**:

**Disposition**:

**Preventative**:


### Marginal and Ineffective Therapies

## Anaesthetic Considerations

## Complications

## Prognosis

## Key Studies


---

## References