# Hyponatraemia 

Hyponatraemia is a **serum sodium** level **<135mmol/L**, which occurs due to an **excess** of **water relative to sodium**. Hyponatraemia is classified by:

* Serum concentrations and symptoms into:
	* Mild\
	125-134.
	* Moderate\
	120-124.
	* Severe\
	⩽119.
* Time course into:	
	* Acute\
	⩽48 hours.
	* Chronic\
	⩾48 hours.

## Epidemiology and Risk Factors

* Most common electrolyte abnormality
	* 30-40% of hospitalised patients
	* 25-30% of ICU patients
		* ~2.7% mild
		* ~1.2% severe
* ↑ Severity is associated with ↑ mortality
* Risk factors for rapid correction of hyponatraemia\
↑ frequency of monitoring should be performed in patients with:
	* Hypovolaemia
	* Glucocorticoid deficiency
	* Beer potomania
	* Polydipsia
	* Desmopressin cessation


## Pathophysiology

Basic principles:

* Water diffuses freely across cell membranes
* Hyponatraemia indicates extracellular hyposmolality, and therefore intracellular hypoosmolality


Pontine myelinolysis occurs when:

* Water influx into cells causes swelling, and may lead to life-threatening cerebral oedema
	* Initially, neurons excrete osmoles to reduce oedema formation
	* Swelling will occur when compensatory mechanisms are overwhelmed
* As hyponatraemia is corrected, neurons must reabsorb osmoles\
This process is slower than excretion, and may take several days.
	* Rapid correction of extracellular sodium may therefore lead to dehydration of brain cells as more water leaves the neuron as extracellular osmoles rise\
	This causes cells to shrink, and potentially demyelinate.

### Aetiology

Hyponatraemia is a disorder of water excess. Broadly, this may be either due to:

* Excessive water intake
* Failure of the kidneys to remove water

## Clinical Manifestations

Speed of onset is more important than the absolute value.

### History

* Symptoms\
Largely attributable to brain oedema; rare if Na^+^ >135mmol/L.
	* Symptoms of mild hyponatraemia:
		* Nausea
		* Vomiting
		* Headache
	* Symptoms of severe hyponatraemia:
		* Altered mental status
		* Seizures
		* Obtundation
		* Coma
	* Symptoms of chronic hyponatraemia:
		* Disorientation
		* Lethargy
		* Dysarthria
		* Gait disturbance
		* Seizure\
		Rare in chronic hyponatraemia.


* Drug history
	* Diuretics
	* Steroids
	* SIADH precipitants
* Medical History
	* Ascites
	* Peripheral oedema
	* Trauma
		* Pituitary injury/Cerebral Salt Wasting
	* Urine output
		* HONK
		* ATN
	* Recent procedures
		* TURP
		* IV contrast administration
* Social history
	* Alcohol intake
	* Dietary


### Examination

* Volume state\
Key in differentiating SIADH from CSW.


## Diagnostic Approach

:::info
A variety of approaches are described, this one is suggested because it doesn't require assessment of volume state, which clinicians are generally bad at.
:::

### Identify Subtype

Measure serum osmolality, and classify into:

* **Isotonic hyponatraemia** (pseudo-hyponatraemia)\
Hyponatraemia occurring with normal serum osmoles.
	* Due to ↑ solid phase of plasma which dilutes electrolytes in sample\
	e.g. Proteins, lipids.
* **Hypertonic hyponatraemia**\
Hyponatraemia with ↑ serum osmoles.
	* Due to ↑ **impermeant solute** concentration, causing shift of water from ICF to ECF\
	e.g. Glucose, mannitol, glycerol, sorbitol
* **Hypotonic hyponatraemia**\
Hyponatraemia with ↓ serum osmoles. Measure urine sodium and osmolality, and classify by *both*:
	* **Urine osmolality**
		* Water retainers\
		Indicated by urinary osmolality **⩾100mmol/L.**
		* Water wasters
	* **Urine sodium**
		* Sodium retainers\
		Indicated by urinary sodium **⩽40mmol/L**.
		* Sodium waters

:::column-margin
Pseudohyponatraemia does not occur with Na^+^ measured by ion-sensitive electrodes, as occurs with blood gases as they are not affected by the dilution of plasma by protein and lipid.
:::


### Subtypes

Based on the above findings of hyponatraemia can then be grouped into **six types**:

1. **Hyper-osmotic hyponatraemia**\
	* ↑ Serum osmolality\
	Pseudohyponatraemia.
	* Causes:
		* Mannitol
		* Sorbitol
		* IV contrast
		* Hyperglycaemia
2. **Iso-osmotic hyponatraemia**\
	* Normal serum osmolality\
	Pseudohyponatraemia.
	* Causes:
		* Hyperlipidaemia
		* Hyperproteinaemia
		* Post-TURP hyponatraemia
		* Massive uraemia

:::column-margin
Iso-osmotic and hyper-osmotic hyponatraemia can be diagnosed on blood testing alone.
:::

3. **Sodium retainers, water retainers**\
	* ↓ Serum osmolality
	* ↑ Urine osmolality, ↓ urine sodium
	* Causes:
		* Hypovolaemia\
		Significant enough to cause ↑ ADH secretion, despite the ↓ Na^+^.
		* Heart failure\
		Consider TTE.
		* Cirrhosis\
		Consider LFTs.
		* Nephrotic syndrome\
		Consider 24 hour urinary protein.

:::column-margin
In sodium and water retention, volume-conservation mechanisms have been activated for either physiological (true hypovolaemia) or pathological means.
:::

4. **Sodium wasters, water retainers**\
	* ↓ Serum osmolality
	* ↑ Urine osmolality, ↑ urine sodium\
	* Causes:
		* Failure to reabsorb renal sodium
			* Diuretics
			* Polyuric ATN
			* Post-obstruction diuresis
			* Chronic renal failure
		* Mineralocorticoid deficiency\
		Consider cortisol level.
		* Hypothyroidism\
		Consider TFTs.
		* SIADH\
		Low urine output but euvolaemic.
		* Renal osmostat syndrome
		* Cerebral Salt Wasting\
		High urine output but hypovolaemic.


:::column-margin
Sodium wasting and water retaining implies both inappropriate loss of sodium and probably inappropriate retention of water.
:::

5. **Sodium retainers, water wasters**\
	* ↓ Serum osmolality
	* ↓ Urine osmolality, ↓ urine sodium.
	* Causes:
		* Polydipsia
		* Iatrogenic free water\
		Dextrose.
		* Malnutrition
		* Beer potomania

:::column-margin
Wasting water whilst retaining sodium is a completely appropriate response to hyponatraemia, and implies some source of excess free water as the cause.\
\
Sadly, the word potomania comes from the Latin "pōtō", which means to drink; and does not imply a particular obsession with the [Australian pot glass](https://en.wikipedia.org/wiki/Pot_glass).
:::

6. **Sodium wasters, water wasters**\
	* ↓ Serum osmolality
	* ↓ Urine osmolality, ↑ urine sodium\
	Failure of water and sodium reabsorption.
	* Renal sodium loss
		* Post-obstructive diuresis
		* Polyuric ATN
		* AKI

:::column-margin
Wasting both sodium and water indicates a failure of both sodium and water reabsorption.
:::


## Investigations

**Bedside**:

* ABG
	* Na^+^


**Laboratory**:

* Blood
	* Serum osmolality\
		* Normal >280mOsm/L
	* **Sodium Measurement**\
	Two methods are available:
		* Direct Ion-Specific Electrode (ISE)
			* Used in point of care systems
			* Undiluted blood is measured at the measuring electrode
		* Indirect ISE
			* Used in central laboratory analysers
			* Pre-diluted serum is used\
			Accuracy is therefore dependent on the volume of serum occupied by water (usually ~93%) versus by lipids and proteins (usually ~7%)
				* If there is a significantly high protein or lipid content:
					* The water fraction will be significantly less than 93%
					* The diluted fraction will contain fewer sodium ions than it would if it had a normal proportion of water\
					Serum sodium will be underestimated (leading to pseudohyponatraemia).
				* If there is a significantly low protein or lipid content (as in critical illness):
					* The water fraction will be greater than 93%
					* The diluted fraction will contain more sodium ions\
					Serum sodium will be overestimated.
					* Serum sodium can be partially corrected for hypoalbuminaemia by subtracting **0.7mmol/L for every 1g/dL** ↓ in total protein.
	* Cholesterol
		* Triglycerides
	* Protein
	* Random cortisol
	* Short Synacthen test\
	Test of adrenal insufficiency.
* Urine
	* **Urine osmolality**
		* <100mOsm/L indicates (appropriate) suppression of ADH\
		This is an appropriate response to hyponatraemia, as the body is in a state of water excess. 
	* **Urine sodium**\
	Indicates how the kidneys are handling sodium.
		* 10mmol/L is the theoretical minimum excretable load
		* ⩽20mmol/L suggests hypovolaemia\
		May be **true** hypovolaemia, or **perceived** hypovolaemia (e.g. heart failure).
		* ⩾40mmol/L suggests SIADH\
		Key in discriminating CSW and hypovolaemia from SIADH.
	* Urine/Plasma electrolyte ratio\
	Ratio of urinary electrolytes to plasma electrolytes, given an indication of the relative tonicity of urine and plasma.
		* Typically given by: ${U \over P}Ratio = {[Na]_u + [K]_u \over [Na]_p}$
		* A positive ratio indicates that electrolyte-free water excretion is negative\
		Fluid restriction alone is unlikely to correct sodium, as the kidneys are not excreting a dilute urine.
			* Water intake in excess of losses will cause further ↓ in serum sodium
			* A very restrictive (e.g. <500ml/day) restriction will be required
		* A negative ratio indicates a degree of electrolyte-free water excretion


### Calculation of Sodium Deficit

In order to guide replacement infusiono rate, a crude calculation of the total body sodium deficit can be performed:

$$Sodium \ Deficit = TBW \times Weight \times (Desired \ [Na^+] - Current \ [Na^+])$$

:::column-margin
Despite the fact that sodium is Na^+^ to the ECF and therefore TBW should not logically be the relevant denominator, the equation has been empirically validated and so has stuck around.
:::

Where:

* $Deficit$ is in mmol of sodium\
The volume of saline given to replace the deficit depends on the concentration of the replacement fluid.
* $TBW$ is the fraction of weight that is water:
	* $~0.6$ for men
	* $~0.5$ for women
* $Weight$ is body weight

:::column-margin
{{< include /includes/saline.qmd >}}
:::

## Management

:::priority
* Correct **hypovolaemia**
* ***Slow*** (<10mmol/24 hours) **correction** of serum **sodium**
* Correct **hypokalaemia**
:::

**Specific therapy**:

* Pharmacological
	* **Volume state correction**\
		* Hypovolaemia
			* This can be considered as a separate problem to hyponatraemia\
			i.e. Have one therapy (3% NaCl) for hyponatraemia, and another therapy (0.9% NaCl) for hypovolaemia).
			* Normal saline is appropriate
		* Hypervolaemia
			* Loop diuretics\
			Produce a hypo-osmotic urine, and so ↑ serum osmolality.
	* **Hypertonic saline**\
	3% NaCl is the mainstay of treatment, and may be given peripherally.
		* For **severe, acute** hyponatraemia:\
		100ml of 3% NaCl over 10 minutes, repeated up to 3 times or until symptoms resolve.
			* Risk of ongoing oedema exceeds risk of osmotic demyelination syndrome
		* For **acute** (but less severe) hyponatraemia:
			* 1-2ml/kg/hr of 3% NaCl
			* Target ↑ in serum sodium up to 2mmol/L/hr until symptoms improve
		* For **chronic** hyponatraemia:
			* Infusion rate should be calculated based on calculated sodium deficit and desired rate of correction\
			$Infusion \ Rate = Body \ Weight \ (kg) \times Desired \ Rate \ of \ Sodium \ ↑ (mmol/L/hr)$
			* Target an ↑ in serum sodium of **4-8mmol/day**
		* Sodium levels should be checked every 2-4 hours during replacement
		* As sodium levels improve, a more dilute urine should be produced
	* **Potassium replacement**\
	Correcting hypokalaemia will also ↑ serum sodium.
	* **Fludrocortisone**\
	Indicated in CSW to ↑ sodium retention.
	* **Vasopressin antagonists**
* Physical
	* **Free water restriction**\
	Important in hyponatraemia associated with cardiac failure.
		* Degree of restriction may be calculated from a spot urine/plasma electrolyte ratio
		* Unlikely to work if:
			* Urine osmolality is high
			* Urine output is low


### Marginal and Ineffective Therapies



## Complications

* D
	* Osmotic Demyelination Syndrome:
		* Also known as central pontine myelinolysis\
		Though oedema and demyelination will occur everywhere there is myelin, not just in the pons.
		* Risk factors include:
			* Severe hyponatraemia
			* Chronic hyponatraemia
			* Rapid correction of serum sodium
		* Symptoms may appear 24-48 hours after correction
		* Symptoms in include:
			* Quadriplegia
			* Pseudobulbar palsy
			* Seizures
			* Coma
			* Death

---

## References


1. Yartsev, A. [Hyponatraemia: A Lazy Man's Classification](http://www.derangedphysiology.com/main/required-reading/electrolytes-and-fluids/Chapter%205.3.1/hyponatremia-lazy-mans-classification). Deranged Physiology. 2016.
2. Milionis HJ, Liamis GL, Elisaf MS. [The hyponatremic patient: a systematic approach to laboratory diagnosis](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC100882/). CMAJ: Canadian Medical Association Journal. 2002;166(8):1056-1062.
3. Buffington MA, Abreo K. [Hyponatremia: A Review](https://www.ncbi.nlm.nih.gov/pubmed/25592330). J Intensive Care Med. 2016. May;31(4):223-36. 
4. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.