# Liver Transplant {#sec-icu_liver_tx}

Major post-operative considerations include:

:::column-margin
As a consequence of broader indications and fewer contraindications, the number of patients on the waiting list tends to exceed available donors. Consequently, patients are generally transplanted later when they are more unwell, which ↑ risk and peri-operative complications.
:::

* **Pre-morbid complications** of **liver disease**:
	* Porto-pulmonary hypertension
	* Hepatopulmonary syndrome


## Indications

## Contraindications

## Principles

## Practice


## Complications

* Death
* D
	* Encephalopathy
		* Pre-existing hepatic encephalopathy
		* Hepatic encephalopathy with PGD
		* Calcineurin inhibitors
* F
	* AKI
* G
	* PGD
		* Primary graft non-function occurs in 2-20% of cases and may require retransplantation
		* Major differential is hepatic artery thrombosis, ergo patients require hepatic artery ultrasound.
	* Hepatic artery thrombosis\
	* Bile duct ischaemia\
	Gastroduodenal artery usually supplies majority of bile duct blood flow, but this is not anastomosed, ↑ vulnerability of the duct.
	* Acute rejection\
	Typically at 5-7 days.
* I
	* Infection
		* Bacterial most common
			* Gram positive most common
				* Enterococci
				* MRSA
				* VRE
			* ESBL
		* Fungal
			* Candidiasis


## Key Studies


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.