# Post Cardiac Surgery

Cardiac surgery forms a significant component of intensive care work, and is unique due to the:

* Use of [Cardiopulmonary Bypass](/anaesthesia/cardiac/cpb.md) and cardioplegia
* Variety in the types of procedure and the physiological consequences of changes in loading conditions
* Nature of post-operative complications

## Initial Evaluation

Reception of the post-cardiac surgical patient includes:

* Handover
* Examination
* Investigation

### Handover

Important information for the cardiac admission:

* Patient factors
	* Age
	* Key past medical history
		* Allergies
		* Major CVS risk factors and previous interventions
		* Chronic health conditions
		* Current medications\
		Timing of last anticoagulants and anti-platelet agents.
	* Social history
		* Functional state
		* Next of kin\
		Have they been contacted by the surgical team?
* Surgical factors
	* What operation?
		* CABG
			* Adequacy of graft targets\
			* Graft locations
		* Valvular
			* Adequacy of repair
			* Type of replacmeent
				* Mechanical
				* Tissue	
	* Adequacy of myocardial protection	
	* Complications and management
	* Bleeding
	* Drain location\
	Pleural drains generally placed only if pleural breached (e.g., left pleural during mammary takedown for CABG).
	* Major surgical concerns
* Anaesthetic factors
	* Airway management and intubation grade
	* Any issues with lines?
	* Pre-bypass haemodynamics
	* Pre-bypass echo\
	Ventricular and valvular function.
	* Bypass time and cross-clamp time
	* Separation from bypass\
	Requirements for:
		* Inotropes/vasopressors
		* Nitric Oxide
		* Pacing
		* IABP
		* Return to CPB
	* Post-bypass haemodynamics and changes in vasoactives
	* Post-bypass echo
	* Transfusion requirement	
	* Coagulation status
	* Pacing wires\
	Thresholds.
	* Current supports on arrival to ICU


### Examination

Examination should involve:

* Airway
	* ETT position
* Breathing
	* Adequacy of gas exchange
		* ABG
		* Auscultation
		* Monitoring
	* Ventilation settings
* Circulation
	* Haemodynamic state
		* HR
		* BP
		* CO/CI
		* Pressures\
		Ensure zeroed.
	* Peripheral perfusion
	* Drain
		* Patency
		* Outputs
* Disability
	* Pupils
	* GCS
* E
	* Temperature

### Investigations

Post-operative investigations should include:

* ABG
	* Adequacy of gas exchange
	* Lactataemia
	* Hb
	* Electrolyte abnormalities
* ECG\
Compare with pre-operative ECG:
	* Common and benign post-operative changes include:
		* RBBB
		* Pericarditic changes
	* Concerning changes include:
		* Heart block\
		Indicates AV nodal dysfunction, particularly after valvular surgery.
		* STE in continguous leads in a grafted vascular territory\
		May be acute graft failure.
		* Anterior STE\
		LIMA spasm in a LIMA-LAD graft.
		* Low voltage\
		Consider tamponade.
* CXR
	* Pneumothorax
	* Device position\
	ETT, PAC, NGT, ICC, drains.
* Bloods\
Depending on degree of concern.
	* AVG
	* Electrolytes
	* Coagulation status
	* TEG
	* Cardiac markers\
	Always elevated post-cardiac surgery, but are useful in trending changes.

## Management

:::info
The goal for the uncomplicated intubated post-operative cardiac patient is to rewarm, desedate and ensure adequate analgesia, wean ventilator support, and extubate.
:::

General post-operative trajectory:

:::column-margin
Specific post-operative considerations for different procedures are under the relevant operation in the cardiac anaesthetic section.
:::

* C
	* Remove PAC\
	Once HDx stable for 6 hours on minimal vasoactive suppport.
	* Remove other invasive lines\
	As able.
	* Remove pacing wires\
		* Once there has been no pacing requirement for 24 hours, wires can be **isolated**, i.e. removed from the pacing box\
		This improves mobility whilst still allowing pacing to be restarted if required.
		* Wires can be removed after a further 24 hours, provided there is **no coagulopathy**
* D
	* Analgesia
	* Wean sedation\
	Short acting agents preferred.
* E
	* Warming\
	Should be rewarmed to >36°C. This:
		* Reduces arrhythmia
		* ↓ SVR and myocardial work
		* Improves coagulopathy
* F
	* Electrolytes
		* Hypokalaemia\
		Aim 4.5-5mmol/L.
		* Hypomagnesaemia\
		Aim >1mmol/L.
	* Urine output\
	Polyuria dominates the early post-operative period, but usually resolves in ⩽6 hours.
	* Remove IDC\
	Second post-operative day if mobilising.



## Complications

Key issues in the post-cardiac surgical patient include:

* Bleeding
* Haemodynamic instability
* AF
* Cardiac tamponade

	

### Bleeding

**Medical bleeding**, due to abnormalities of coagulation:

* Causes:
	* **Platelets**
		* Qualitative abnormality\
		Platelet function is ↓ by:
			* Preoperative use of antiplatelet agents
			* Cardiopulmonary bypass\
			Greater bypass duration is associated with greater impairment.
		* Quantitative abnormality\
	* Coagulation abnormality
		* Residual heparinisation
		* Haemodilution
		* Consumption
	* Fibrinogen\
		* Plasminogen is activated by CPB
* Treatment:
	* Normalise temperature
	* Prevent hypertension
	* Correct platelet dysfunction:
		* Platelet transfusion\
		Aim *functional* platelet count >100 × 10^9^ in significant bleeding.
		* DDAVP\
		Aim to improve platelet function.
			* 20μg IV
	* Correct coagulopathy\
	Aim to normalise APTT and PT.
		* Typically 20ml/kg of FFP
	* Correct fibrinogen\
	Aim to keep fibrinogen >1g/L.
	* Prevent fibrinolysis\
	Consider in the setting of fibrinolysis (i.e. elevated D-Dimer and low fibrinogen).
		* TXA
	* ↑ mediastinal pressure\
	Theoretically reduce venous bleeding.
		* ↑ PEEP
		* Raise head of bed

**Surgical bleeding**, due to uncontrolled (typically arterial) source. Suggested by:

* Bleeding with normal coagulation parameters
* Bleeding following period of extreme hypertension\
Anastomotic breakdown.
* Large volume drain outputs\
	* >500ml in 1 hour
	* >400ml/hr for 2 hours
	* >300ml/hr for 3 horus
	* >200ml/hr for 4 hours


### Causes of Haemodynamic Perturbation

Haemodynamic impairment can be divided into problems with:

* Heart Rate/Rhythm
	* Tachycardias
		* Pacing malfunction
		* Electrolytes
		* AF
	* Bradycardia
		* Pacing malfunction
		* Electrolytes
		* Ischaemia
* Preload\
	* Hypovolaemia\
	Associated with lower filling pressures, and accentuated by diastolic dysfunction.
		* Bleeding
		* Diuretics
		* Rewarming
		* Vasodilators
	* ↑ Intrathoracic pressure
		* Pneumothorax
		* Excessive PEEP
	* ↑ Intrapericardial pressure
		* Tamponade\
		Elevation and equalisation of diastolic pressures.
	* RV failure
* Afterload/SVR 
	* ↑ **LV** afterload:
		*  Aortic valve dysfunction
		* Excessive vasoconstrictors
		* Dynamic outflow tract obstruction
	* ↓ LV afterload:
		* SIRS
		* Post-pump vasoplegia
		* Anaphylaxis
			* Protamine reactions
		* Excessive vasodilator therapy
		* Thyroid dysfunction
		* Adrenal insufficiency
	* ↑ RV afterload:
		* Acidosis
		* Hypoxia
		* Excessive PEEP
		* Thromboembolism
* Contractility
	* Ischaemia
		* Acute graft dysfunction
		* Air embolus\
		Predominantly RCA.
	* Inadequate myocardial protection
		* Myocardial stunning\
		Long bypass time.
		* Ventricular dilatation
		* Inadequate cardioplegia
	* Pre-existing ventricular dysfunction


### Cardiac Tamponade

Post-surgical tamponade:

* Occurs in up to 5%
* May emerge slowly
* Combination of clinical suspicion and echocardiographic diagnosis
* Features (not all of which may be present):
	* Tachycardia
	* Low UO
	* Fall in CO/SV/MVO~2~
	* Elevation and equalisation of diastolic pressures\
	RAP ≃ PADP ≃ PCWP. May not occur if a **small clot impedes filling to only one chamber**.
	* Loss of y-descent on CVP waveform
	Indicates that the pressure gradient between the atria and the ventricles is reduced.
	* Loss of mediastinal drain output
	* Echocardiography evidence of tamponade	
* Treatment
	* Resternotomy and evacuation of clot



### Atrial Fibrillation

AF occurs in 10-40% of post-cardiac surgery patients, and is associated with significant morbidity:

* ↑ CVA risk (3x)
* ↑ Inotrope requirement
* ↑ Reoperation
* ↑ ICU and hospital LoS


Risk factors include:

* Age
* Use of cardiac supports:
	* Inotropes
	* IABP
* Previous AF
* Valvular heart disease


Prevention strategies include:

* Antiarrhythmics
	* Beta-blockade
	* Amiodarone
	* Diltiazem
	* Sotalol
* Procedural
	* Bi-atrial pacing
* Anti-inflammatories
	* Statins
	* Dexamethasone
	* Colchicine		


Treatment strategies:

* Pharmacological
	* Rhythm control
		* Amiodarone
		* Magnesium
	* Rate control
		* Beta-blockade
		* Diltiazem
		* Digoxin
	* Anticoagulation\
	Consider if >48 hours.	
* Procedural
	* Electrical cardioversion
	

### Renal Failure

Post-operative AKI:	

* Occurs in 1-5%
* Significant associated morbidity and mortality

### Other

Other complications of cardiac surgery include:

* C
	* Permanent pacing
		* AVR + MVR: 11%
		* MVR: 8%
		* AVR: 5%
* D
	* Delirium/POCD
	10-20%.
	* Stroke	
	1-5%.
* G
	* Mesenteric ischaemia
		* Embolic
* I
	* Infection
		* Deep sternal wound infection in 1-2%\
		Significant morbidity.
	
---

## References

1. Melanson, P. [Management of post-op cardiac surgery patients](https://www.mcgill.ca/criticalcare/teaching/protocols/cardiac). 2001. McGill.