# Post-Liver Transplant

Liver transplant is a successful 

:::column-margin
As a consequence of broader indications and fewer contraindications, the number of patients on the waiting list tends to exceed available donors. Consequently, patients are generally transplanted later when they are more unwell, which ↑ risk and peri-operative complications.
:::


## Epidemiology and Risk Factors

Risks for perioperative complications include:

* Porto-pulmonary hypertension
* Hepatopulmonary syndrome

## Pathophysiology

### Aetiology

## Clinical Features

## Assessment

**History**:

**Exam**:

### Investigations

**Bedside**:

**Laboratory**:

**Imaging**:

**Other**:

### Diagnostic Approach and DDx


## Management

:::priority
Goals of management
:::

**Resuscitation**:

**Specific therapy**:

* Pharmacological
* Procedural
* Physical

**Supportive care**:

**Disposition**:

**Preventative**:


### Marginal and Ineffective Therapies

## Anaesthetic Considerations

## Complications

* Death
* D
	* Encephalopathy
		* Pre-existing hepatic encephalopathy
		* Hepatic encephalopathy with PGD
		* Calcineurin inhibitors
* F
	* AKI
* G
	* PGD
		* Primary graft non-function occurs in 2-20% of cases and may require retransplantation
		* Major differential is hepatic artery thrombosis, ergo patients require hepatic artery ultrasound.
	* Hepatic artery thrombosis\
	* Bile duct ischaemia\
	Gastroduodenal artery usually supplies majority of bile duct blood flow, but this is not anastomosed, ↑ vulnerability of the duct.
	* Acute rejection\
	Typically at 5-7 days.
* I
	* Infection
		* Bacterial most common
			* Gram positive most common
				* Enterococci
				* MRSA
				* VRE
			* ESBL
		* Fungal
			* Candidiasis

## Prognosis

## Key Studies


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.