# Acute Behavioural Disturbance


Rapid onset of intensive agitation and physical actions that:

* Are contextually inappropriate
* May result in significant harm to self or others

## Epidemiology and Risk Factors

## Pathophysiology

### Aetiology

## Clinical Manifestations

## Diagnostic Approach and DDx

## Investigations

## Management

> * Goal of drug management is to safely manage and modify disturbed behaviour
> * Relevant drugs often have:
> 	* Narrow therapeutic index
> 	* Variable onset
> 	* Variable depth
> * Provision of safe sedation is essential
> * Principles of a preanaesthetic assessment should be followed when planning sedation


Safety:

* Suitable sedating locations must be provided  
As required for sedation.
* Fundamental physiological monitoring is essential  
Must be paired with clinical observation.
* Staff present to recognise and manage:
	* Airway obstruction
	* Respiratory depression
	* CVS depression
	* Drug interactions
* Minimum of 3 trained staff
	* Doctor capable of ALS and airway management
	* RN capable of BLS and assisting with sedation
	* One other


Considerations for prolonged sedation:

* Standardised tool to monitor depth of sedation
* Extrapyramidal side effects
* Urinary retention  
Consider IDC.
* Hydration state
* Pressure area care
* Thromboprophylaxis

### Anaesthetic Considerations

### Marginal and Ineffective Therapies

## Complications

## Prognosis

## Key Studies


---

## References

1. ANZCA. [PS63: Guidelines for Safe Care for Patients Sedated in Health Care Facilities for Acute Behavioural Disturbance](http://www.anzca.edu.au/Documents/ps26-2005-guidelines-on-consent-for-anaesthesia-or.pdf).