# Acquired Brain Injury {#sec-abi}

Acquired Brain Injury is an umbrella term that:

* Encompasses a wide spectrum of brain injuries
* Has a wide range of impairments affecting physical, neurocognitive, or psychological functioning
* May result from
	* Traumatic aetiologies
		* Concussion
		* Contusions
	* Non-traumatic aetiologies
		* Subarachnoid haemorrhage

## Epidemiology and Risk Factors

## Pathophysiology

### Aetiology

## Assessment

### History

Behavioural change is common and may be significant. Features include:

* Impulsivity
* Low frustration tolerance
* Verbal or physical threats and aggression
* Non–adherence
* Disinhibition
	* Inappropriate sexual behaviours
* Repetitive behaviour
* Wandering or absconding
* Inappropriate or irresponsible social behaviour
	* Intrusiveness
	* Self-centeredness
	* Manipulative behaviours
* Apathy

### Examination


### Investigations

**Bedside**:

**Laboratory**:

**Imaging**:

**Other**:

### Diagnostic Approach and DDx


## Management

:::priority
* **Staff safety**
* **Behavioural management**
* Non-benzodiazepine sedation
:::

**Specific therapy**:

:::column-margin
Pharmacological management should be secondary to non-pharmacological means.
:::

* Pharmacological
	* Aggression/behavioural control
		* **Avoidance** of benzodiazepines
		* Propranolol 5mg TDS-QID\
		Uptitrate as haemodynamic tolerance permits, up to 160mg (total) per day.
		* Valproate 100-200mg BD\
		Second-line agent for aggression and behaviours of concern.
		* Atypical antipsychotics\
		May be appropriate if an agent is required for acute agitation.
* Procedural
* Physical

**Supportive care**:

* D
	* Behavioural management\
	Will require multidisciplinary engagement. Considerations include:
		* Detection and avoidance of exacerbating factors
		* Build rapport

**Disposition**:

**Preventative**:


### Marginal and Ineffective Therapies

## Anaesthetic Considerations

## Complications

* D
	* Mental health diagnoses\
	Common following ABI, and include:
		* Depression
		* Anxiety
		* Psychosis

## Prognosis

## Key Studies


---

## References