# Autonomic Dysreflexia


Potentially **life-threatening sympathetic overactivity** occurring in patients with a **spinal injury above T6**.


## Epidemiology and Risk Factors

## Pathophysiology

Requires:

* Spinal injury level is T6 or higher
* Noxious stimulus below the level of injury:
	* Ascending sensory fibres convey message to spinal cord
	* Widespread SNS reflex activity occuring below the level of injury  
	Sympathetic ganglion activity remains uncontrolled due to lack of descending inhibition.
	* Compensatory parasympathetic activity **above** the level of injury
		* ↑ BP detected by baroreceptors  
		Leads to compensatory bradycardia.

### Aetiology

Common causes include:

* Bladder
	* Distension
	* Hyperactivity
	* UTI
	* Stones
	* IDC placement
	* Trans-urethral urological procedures
* Bowel
	* Distension
		* Constipation
		* Gas
	* Rectal irritation
		* Haemorrhoids
* Skin
	* Burns
	* Pressure areas
	* Tight clothing
* GU
	* Intercourse
	* Menstrual cramping
	* Labour
* Pain
	* Lower limb trauma


## Clinical Manifestations

Presentation due to SNS overactivity, with compensatory PNS responses:

* B
	* Dyspnoea
* C
	* HTN  
	↑ SBP ⩾20%,
	* Bradycardia
	* Flushing  
	Above level.
* D
	* Blurred vision
	* Headache  
	Due to HTN.
	* Anxiety/irritation
* E
	* Above level
		* Sweating  
	* Below level
		* Palor
		* Piloerection

## Diagnostic Approach and DDx

## Investigations

## Management

> * Identify and remove obvious causes
> * Control BP
> * BP may drop precipitously folllowing removal of stimulus.

Sit upright.

Remove obvious causes:

* Ask the patient/carer
* Loosen constrictive clothing
* Check bladder drainage equipment
	* Kinks
	* Clogging
	* Overfull bag
	* Consider irrigating catheter if blocked  
* Consider IDC
* Consider faecal evacuation  
If bladder empty.

Pharmacological therapy:

* If SBP >150mmHg
* Use short acting agents  
Minimises hypotension once stimulus has resolved.
	* GTN 400μg SL
	* Captopril 25mg SL
	* Hydralazine 5mg IV Q10min
	* Labetaolol 5mg IV Q5min
* Analgesia  
If a noxious stimulus present, e.g. trauma.

### Anaesthetic Considerations

* D
	* Anaesthetic technique
		* General  
		Appropriate if there is a risk of autonomic dysreflexia, or muscle spasms.
		* Neuraxial  
		Appropriate if there is a risk of autonomic dysreflexia, or muscle spasms.
			* Spinal anaesthesia effectively prevents autonomic dysreflexia
			* Epidural anaesthesia is less reliable, as a patch block may occur
		* Regional/local  
		Appropriate if:
			* Reduced sensation at site
			* No risk of autonimic dysreflexia
		* Monitored anaesthetic care  
		Appropriate if:
			* No sensation at site
			* No risk of autonomic dysreflexia

## Complications

Include:

* Death
* CVS  
~22%.
	* Myocardial ischaemia
	* APO
* CNS  
~70%; major cause of death.
	* CVA

## Prognosis

## Key Studies


---

## References

1. Middleton J, Ramakrishnan K, Cameron I. [Treatment of Autonomic Dysreflexia for Adults & Adolescents with Spinal Cord Injuries](https://www.aci.health.nsw.gov.au/__data/assets/pdf_file/0007/155149/Autonomic-Dysreflexia-Treatment.pdf). Agency for Clinical Innovation. 2013.