# Epilepsy {#sec-epilepsy}

Epilepsy is a primary seizure disorder with recurrent (two or more) epileptic seizures.

:::column-margin
This covers epilepsy. Management of seizures including status epilepticus are covered at @sec-seizure, and NCSE is covered at @sec-ncse.
:::

## Epidemiology and Risk Factors

Prevalence:

* Most common serious neurological disorder
* ~0.5-1% of the population

Incidence:

* Bimodal
	* Extremes of age

Risk factors:

* Male
* Lower socioeconomic status
* Brain abnormality
	* Structural
	* Developmental

## Pathophysiology


### Aetiology

Multiple causes exist, and include:

* D
	* Migraine
	* Cerebrovascular disease
		* CVA\
		Equally likely after infarction or haemorrhage.
	* Tumour
		* Anterior
		* Slow-growing
	* Degenerative
		* Dementia
		* Alzheimer's Disease
	* Post-syncope
* F
	* Hypo/hypernatraemia
	* Hypo/hypercalcaemia
	* Hypo/hypermagnesaemia
	* Hypoglycaemia
* Immune
	* Multiple sclerosis
* Traumatic\
Post-traumatic epilepsy associated with:
	* Early seizures
	* Depressed skull fractures
	* ICH
* Infective
	* Meningitis
	* Encephalitis
* Congenital
	* Associated with other disorders
		* Down's Syndrome
		* Mitochondrial disease
	* Epilepsy syndromes
		* Juvenile myoclonic epilepsy
		* Benign rolandic epilepsy



## Clinical Manifestations

### History

### Examination

## Diagnostic Approach and DDx

## Investigations

**Laboratory**:

* UEC/CMP
* Prolactin


**Imaging**:

* CTB\
Evaluation of structural cause.
* MRI\
Evaluation of structural cause, with ↑ sensitivity and specificity compared with CT.


**Other**:

* EEG:
	* Interpretation may be difficult
	* Patients with disease will have abnormalities ~50% of the time


## Management

Principles of medical management:

* Single-agent therapy optimised before progressing to multi-agent therapy
	* If adverse effect to first agent, a second agent tried as monotherapy\
	* If seizures continue despite adequate dosing, combination therapy usually begun
* Significant side effect profile of many older agents
* Usually continued until 2-3 year seizure-free period\
	* Drugs may then be withdrawn over 3-6 months
	* ~66% of patients will remain seizure free
* Drug therapy depends on type of epilepsy
* Patients who have had one episode of status epilepticus should be prescribed benzodiazepines to treat refractory status


Drugs used:

* Focal seizures
	* Lamotrigine
	* Carbamazepine
* Generalised
	* Valproate\
	Most effective drug for primary generalised epilepsy.


### Mechanisms of Action

|Mechanism|Drug|
|---|---|
|**↑ GABA Cl^-^ channel opening frequency**|- Benzodiazepines<br>- Tiagabine<br>- Gabapentin|
|**↑ GABA Cl^-^ channel opening duration**|- Barbiturates|
|**Block GABA transaminase**|Vigabatrin|
|**Antagonise glutamate**|Topiramate|
|**↓ Inward voltage-gated positive currents**|- Phenytoin<br>- Carbamazepine<br>- Ethosuximide|
|**↑ Outward voltage-gated positive currents**|- Valproate|
|**Pleotropic**|- Valproate<br>- Lamotrigine<br>- Topiramate|

### Key Drug Interactions

Predominantly related to CYP450 induction and inhibition:

* Inductors
	* Carbamazepine
	* Phenytoin
	* Phenobarbital
	* Primidone
* Inhibitors



### Anaesthetic Considerations

* D
	* Anaesthetic affects\
	Drugs may:
		* Modulate seizure activity
		* Interact with antiepileptic medication
	* General principles
		* Continue antiepileptic drugs on day of surgery, and recommence as soon as possible afterwards\
		Administer parenterally if multiple doses missed or are likely to be missed.
		* Avoid epileptogenic drugs
		* Note presence of drug interactions\

#### Effect of Anaesthetic Agents on Epilepsy

Anaesthetic agents may be:

* Pro-convulsant
* Anti-convulsant
* Both

|Agent|Effect|
|---|---|
|Nitrous Oxide|Seizures in mice, but not in humans|
|Sevoflurane|May induce seizure-like activity particularly:<br>- In children<br>- With associated hypocapnoea|
|Isoflurane|Antiepileptic, may be used in refractory status epilepticus|
|Desflurane|Antiepileptic|
|Opioids|Lower seizure threshold, and may be used to potentiate seizures|
|Barbiturates|Antiepileptic, may be used in status|
|Propofol|Antiepileptic, may be used in status|
|Ketamine|↑ Seizures at low dose, ↓ seizures at anaesthetic doses|
|NMBD|No effect|

### Marginal and Ineffective Therapies

## Complications

Pregnancy:

* 4-8% risk of congenital malformations
* ↑ seizure frequency in ~30% of patients
* GTCS associated with ↑ miscarriage risk
* Excretion of benzodiazepines and barbiturates in baby


## Prognosis

Related to severity and degree of control. Morbidity associated with:

* Requiring ⩾3 antiepileptic drugs
* Status epilepticus

## Key Studies


---

## References

1. Gratrix AP, Enright SM. Epilepsy in anaesthesia and intensive care. Continuing Education in Anaesthesia Critical Care & Pain. 2005 Aug;5(4):118–21. 
2. Perks A, Cheema S, Mohanraj R. Anaesthesia and epilepsy. Br J Anaesth. 2012 Apr 1;108(4):562–71. 
