# Hepatic Encephalopathy {#sec-hep_enc}

Neuropsychiatric syndrome characterized by cognitive and motor dysfunction, resulting from the liver's inability to effectively clear ammonia and other toxins, and is classified by cause into:

:::column-margin
Acute and chronic liver failure are covered in detail under @sec-alf and @sec-cld.
:::

* **Type 1**\
Secondary to acute liver failure. Encephalopathy secondary to acute liver failure is:
	* Associated with cerebral oedema and ↑↑ ICP
	* A severe and acute threat to life\
	Responsible for most of the mortality burden of acute liver failure.
* **Type 2**\
Secondary to portosystemic shunting without liver disease.
* **Type 3**\
Secondary to cirrhosis. Typically:
	* Encephalopathy *without* severe ↑ ICP\
	Consequently has no:
		* Requirement for aggressive ICP control
		* Significant ↑ in mortality

:::column-margin
Degree of hepatic encephalopathy is strongly associated with the degree of hyperammonaemia, and so is typically less severe in ACLF compared to ALF.
:::

## Epidemiology and Risk Factors

## Pathophysiology

Ammonia has complex effects on brain pathophysiology, with neurotoxicity driven by:

* Converted to glutamate by astrocytes\
Glutamate:
	* Creates an osmotic gradient which increases intracellular fluid shifts
	* Impairs amino acid transfer and neurotransmitter release
	* Impairs Kreb's cycle, limiting metabolism
* Direct neurotoxicity\
Especially >150mmol/L.

:::column-margin
Raised intracranial pressure and cerebral oedema are characteristics of hepatic encephalopathy in acute liver failure rather than decompensated chronic liver failure.
:::

### Aetiology

Hyperammonaemia can be caused by:

* ↑ Ammonia generation
* Ingestion
* GI bleeding
* Infection with urea splitting organism
* Valproate toxicity\
Promotes glutamate uptake into mitochondria.
* Glycine intoxication


Decreased metabolism:

* Acute liver failure
* Chronic liver disease
* Portosystemic shunting
* Metabolic defects
	* Urea cycle disorders
	* Organic acidaemia
	* Fatty acid oxidation disorders


Contributory factors:

* Volume depletion
* Hypokalaemia\
↑ Renal NH~4~^+^ production
* Protein load
* ↑ Catabolism
	* Critical illness
	* Corticosteroids
	* Seizures
	* Exercise
	* Burns

## Clinical Features


## Assessment

Hepatic encephalopathy has a wide variety of clinical appearances:

:::column-margin
The **Parson-Smith scale** grades hepatic encephalopathy into:

1. Mild confusion/irritability, ↓ attention
2. Disorientation, drowsiness, inappropriate
3. Somnolent but rousable, incoherent
4. Coma
:::

* Asterixis
* Delirium
	* Inattention
	* Psychomotor retardation
	* Personality changes
	* Agitation
	* Somnolence
	* Coma

### History

### Exam

### Investigations

**Bedside**:

* BSL
* ABG\
Primary respiratory alkalosis.


**Laboratory**:

* Blood
	* Electrolytes
	* LFTs
	* Ammonia\
		* Good negative predictive value
		* High false positive rate
		* Typically useful in Type A encephalopathy, not useful in Type C due to:
			* Fluctuating levels
			* Poorly correlated with degree of clinical encephalopathy
* Other
	* Paracentesis

:::column-margin
Ammonia >200μmol/L associated with cerebral herniation.
:::

**Imaging**:

* CXR

**Other**:

### Diagnostic Approach and DDx

:::caution
Many patients with (or at risk for) hepatic encephalopathy are at risk for multifactorial delirium. However, the treatment for encephalopathy is also benign and can be initiated whilst conducting a search for other causes.
:::

Diagnosis of encephalopathy should consider:

* **Triggers**
	* Infection
	* GI bleeding
	* ↑ Protein diet
	* Non-compliance with rifaximin or lactulose
	* AKI
	* Portal vein thrombosis
	* Intoxication
* **Features**
	* Delirium\
	Typically hypoactive.
	* Non-focal
	* Stupor
	* Respiratory alkalosis


Key differential diagnoses include:

* Medication-induced delirium
	* Opioids
	* Alcohol intoxication
	* Alcohol withdrawal
* Infective delirium
* Metabolic encephalopathy
	* Wernicke's
	* ↓ BSL
	* Uraemic
	* Hyponatraemia

## Management

:::priority
* **Secure airway** if high grade encephalopathy
* Manage ICP with **quad-H** therapy in Type A disease
	* **Hyperventilation**
	* **Haemodiafiltration**
	* **Hypernatraemia**
	* **Hypothermia**
* **Correct ammonia** with polyethylene glycol or lactulose
* Identify and **treat precipitants**
:::

**Resuscitation**:

:::column-margin
Invasive intracranial pressure monitoring associated with ~10% intracranial haemorrhage rate.
:::

* A
	* Secure if high grade (III/IV) encephalopathy
* B
	* **Hyperventilation**\
	If required for ICP control.
* C
	* Defend cerebral perfusion\
	MAP 65-70mmHg, or CPP >50mmHg if measuring ICP.
* D
	* **↑ ICP**\
		* General measures\
		If **grade 3/4** encephalopathy, recommend:
			* Intubation
			* Sedation
			* Avoid stimulation
			* Head-up positioning
		* Consider invasive ICP management if **all** of:\
			* Grade 3-4 encephalopathy
			* Hyperacute liver failure
			* Ammonia >150mmolL
			* Young
* E
	* **Hypothermia** (**35°C**)\
	In addition to ↓ in ICP, also ↓ proteolysis and ammonia production.
* F
	* **Hypernatraemia**\
	If required for ICP control. Target 148-152mmol/L.


:::column-margin
The **combination** of **hyperventilation**, **haemodiafiltration**, **hypernatraemia**, and **hypothermia** is referred to as **quadruple-H** or quad-H therapy.
:::

**Specific therapy**:

* Pharmacological
	* Hyperammonaemia
		* **Polyethylene glycol**\
		Preferred in severe encephalopathy. Results in rapid clearance of:
			* Stool\
			And ammonia-producing bacteria.
			* Water\
			Assists in ↑ Na^+^. 
		* **Lactulose**\
		May ↓ hepatic encephalopathy but lead to gaseous intestinal distension.
			* 15-45mL Q4-12H PO, adjusted to achieve >4 bowel actions/day
			* 300mL in 700mL of sterile water PR Q2H\
			Nurse patient in the lateral position to optimise colonic spread.
		* **Rifaximin** 550mg PO BD\
		Combination with lactulose more effective than lactulose alone.
* Procedural
	* Shunt ligation\
	↓ Porto-systemic shunting may improve encephalopathy, but ↑ portal hypertension and risk of variceal bleeding.
		* Closure of previous TIPS
		* Ligation
* Physical

:::column-margin
Lactulose, an osmotic diuretic, ↓ ammonia by several mechanisms:

* Osmotic diuretic\
↓ Intestinal transit time and ↓ absorption.
* ↑ Lactobacillus division\
Non-ammonia producing gut flora.
* Colonic acidification
	* Lactulose is metabolised by gut bacteria into lactic and acetic acid
	* The ↓ in colonic pH favours conversion of ammonia (NH~3~) to ionised ammonium (NH~4~^+^), which is trapped in the colon\
	This is **analogous to urinary alkalinisation** for elimination of weak acids.
	* Trapped ammonium is then cleared by the more mundane osmotic laxative effect

Rifaximin is a non-absorbed, broad-spectrum antibiotic that ↓ gut flora concentrations, ↓ ammonia production.
:::

:::column-margin
TIPS is covered under @sec-tips.
:::

**Supportive care**:

* G
	* Feeding\
	Enteral nutrition should be given.
	* Thiamine supplementation


**Disposition**:

**Preventative**:

* Rifaximin 550mg PO BD\
Significant (~60%) ↓ in hepatic encephalopathy in patients with chronic liver disease.


### Marginal and Ineffective Therapies

## Anaesthetic Considerations

## Complications

## Prognosis

* Death
	* Type A\
	High mortality if untreated.
	* Type C
		* Favourable short-term prognosis
		* Poor long-term (1-3 year) prognosis in absence of transplantation
			* 1-year survival ~40%
			* 3-year survival ~20%

## Key Studies


---

## References
