# Motor Neuron Disease

:::info
Also known as Lou Gehrig's disease.
:::

Paralytic disorder characterised by gradual, heterogenous, and progressive degeneration of all motor neurons. There is also a strong association with **frontotemporal** dementia.


Motor neuron disease is divided into four main types:

* Amyotropic Lateral Sclerosis\
Mixed UMN and LMN signs in all limbs. ALS is the most:
	* Common (70%)
	* Malignant\
	Life expectancy ~3 years.
* Isolated bulbar palsy\
Initial swallowing and speech difficulty; progresses to generalised disease.
	* ~5-10% of cases
	* Life expectancy ~ 4 years
* Progressive muscular atrophy\
Pure LMN signs.
	* ~5%
* Primary lateral sclerosis\
Pure UMN signs, predominantly in lower limbs.
	* Slower disease progression


## Epidemiology and Risk Factors

## Pathophysiology

### Aetiology

## Clinical Manifestations

Motor findings:

* UMN
	* Spasticity
	* Hyperreflexia
* LMN
	* Weakness
	* Wasting


## Diagnostic Approach and DDx

Diagnosis is made on clinical grounds.

Differential diagnoses:

* Multifocal motor neuropathy\
Amenable to treatment.

## Investigations

**Bedside**:

**Laboratory**:

**Laboratory**:

**Other**:

## Management

**Resuscitation**:\

ABC approach. Comment on team coordination and clinical priorities.
**Specific therapy**:

* Pharmacological
* Procedural
* Physical

**Supportive care**:

**Disposition**:

**Preventative**:


### Marginal and Ineffective Therapies

## Anaesthetic Considerations

## Complications

* Death\
3-5 years following diagnosis, secondary to respiratory failure.
* D
	* Frontotemporal dementia

## Prognosis

## Key Studies


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.