# Myotonic Dystrophy



## Epidemiology and Risk Factors

## Pathophysiology

### Aetiology

## Clinical Manifestations

## Diagnostic Approach and DDx

## Investigations

## Management

### Medical

### Surgical

### Anaesthetic Considerations

* General
	* Low threshold for HDU monitoring  
	↑ risk of apnoea and death for 24 hours following extubation.
* A
	* Limited mouth opening
	* Bulbar palsy and aspiration risk
* B
	* Respiratory muscle weakness and expectoration  
	Pulmonary complications are the most common cause of peri-operative morbidity.
	* OSA
* C
	* Cardiomyopathy
	* Conduction abnormalities
* D
	* ↑ sensitivity to IV induction agents
		* Addition of lignocaine may reduce the incidence of contractures
	* **Shivering** from neuraxial anaesthesia **may precipitate myotonic contractures**
	* Regional techniques ideal to reduce analgesia and opioid requirements
* E
	* Hypothermia  
	Avoid shivering.
	* **Avoid suxamethonium**  
	May result in severe hyperkalaemia.
	* Avoid muscle relaxation where possible  
	Reduce initial doses and titrate with a nerve stimulator.
* E
	* DM
	* Hypothyroidism
	* Adrenal insufficiency
	* Gonadal atrophy
* O
	* Neuraxial anaesthesia preferred for labour and caesarian delivery
	* Tocolytic medications are problematic
		* β~2~-agonists may precipitate myotonia
		* MgSO~4~ may precipitate respiratory depression

### Marginal and Ineffective Therapies

## Complications

## Prognosis

## Key Studies


---

## References
