# Overview of Neuromuscular Disease

* Describes a heterogenous group of skeletal muscle defects
* Are classified by:
	* Cause:
		* Congenital
		* Acquired
	* Anatomical site
		* Pre-junctional
		* Junctional
		* Post-junctional

### Types of Neuromuscular Disease

+-----------------+-------------------------------------------+-----------------------------------------------------+
| Cause           | Congenital                                | Acquired                                            |
+=================+===========================================+=====================================================+
| Pre-junctional  | Peripheral Neuropathies:                  | * Motor Neuron Disease (ALS, Lou Gehrig's Disease) |
|                 |                                           | * MS                                                |
|                 | * Charcot-Marie-Tooth                     | * GBS                                               |
|                 | * Fredrichs ataxia                        | * Diabetic neuropathy                               |
+-----------------+-------------------------------------------+-----------------------------------------------------+
| Junctional      |                                           | * MG                                                |
|                 |                                           | * Eaton-Lambert Syndrome                            |
+-----------------+-------------------------------------------+-----------------------------------------------------+
| Post-junctional | Dystrophicas:                             | * Inflammatory myopathies                           |
|                 |                                           | * CIM/CIN                                           |
|                 | * Duchenne                                |                                                     |
|                 | * Becker's                                |                                                     |
|                 |                                           |                                                     |
|                 | Myotonias:                                |                                                     |
|                 |                                           |                                                     |
|                 | * Myotonic Dystrophy                      |                                                     |
|                 | * Myotonia congenita                      |                                                     |
|                 | * Hyper-, hypokalaemic periodic paralysis |                                                     |
|                 | * Metabolic disorders                     |                                                     |
+-----------------+-------------------------------------------+-----------------------------------------------------+



## Anaesthetic Considerations

* A
	* Aspiration risk\
	Due to gastric dysmotility.
	* Strict extubation criteria\
	May require perioperative ICU admission.
* B
	* Respiratory function\
	High incidence of peri-operative respiratory complications due to:
		* Respiratory and pharyngeal muscle impediment
		* Progressive spinal deformities
		* Potential difficult airway
		* Strongly consider perioperative BiPAP
		* Continuous SpO~2~ monitoring until consciousness resumed
	* CXR
	* PFTs
* C
	* Cardiac function
		* Cardiac reserve may be difficult to quantify as exercise tolerance limited by the disorder
	* ECG
	* TTE
* D
	* Avoidance of **volatile**
		* Primarily due to ↑ risk of rhabdomyolysis, rather than ↑ MH risk (though this may still be present)
		* TIVA with a clean anaesthetic machine is recommended
	* Regional anaesthesia
		* Advantageous if significant cardiac or respiratory disease; and so is recommended whenever appropriate
		* Autonomic dysfunction may be exacerbated with regional techniques
		* Consider avoiding if rapidly progressing neurological deficit
	* Minimise opioid use\
	Multimodal analgesia, including regional techniques preferred.
* E
	* Avoidance of **neuromuscular blockers**
		* Depolarising agents contraindicated (except in myasthenia gravis) due to:
			* Massive potassium efflux\
			Upregulation of extra-junctional receptors, and presence of foetal γ isoforms of the ACh receptor.
			* Fasiculations may cause trismus and prevent intubation and ventilation.
			* Rhabdomyolysis
		* Non-depolarising agents:
			* Usually show excessive sensitivity\
			Use at **10-20% of recommended dose**.
			* Monitor block
			* Use agents with a rapid degradation\
			e.g. Atracurium.
			* Avoid reversal\
			Acetylcholinesterases may lead to hyperkalaemia.
	* Thermoregulation\
	Usually impaired. Vulnerability to both hypo- and hyperthermia.
		* Ensure normothermia pre-induction and actively warm
		* Hypothermia may:
			* Exacerbate myotonia
			* ↑ sensitivity to non-depolarising agents
			* Aggravate rhabdomyolysis


## Complications

Include:

* Death\
Usually due to respiratory failure.
* Respiratory failure
	* Exhaustion
	* Atelectasis
	* Aspiration\
	Bulbar weakness.
	* OSA
	* Spinal deformities\
	Restrictive lung disease.
* Cardiac
	* Cardiomyopathies
	* Arrhythmia
* Myotonic contractures


### Myotonic Contractures\

Muscle spasm due to excessive Na^+^ influx or Cl^-^ efflux across a membrane. Contractures are usually:

* Due to drugs or environmental conditions
	* Suxamethonium
	* Anti-cholinesterases
	* Opioids
	* Temperature
	* Acidosis
	* Shivering
* Not responsive to:
	* Neuromuscular blockade
	* Regional/neuraxial anaesthesia
* Treated with:
	* Correction of cause
	* Sodium channel blocking agents
		* Lignocaine
		* Antiarrhythmics


---

## References

1. Marsh S, Ross N, Pittard A. [Neuromuscular disorders and anaesthesia. Part 1: generic anaesthetic management](https://academic.oup.com/bjaed/article/11/4/119/266998). Contin Educ Anaesth Crit Care Pain. 2011;11(4):115-118. 
2. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.
