# Parkinson's Disease


Progressive chronic central neurological disorder that occurs due to degeneration of dopaminergic neurons in the substantia nigra, and is characterised by:

* Motor symptoms
	* Tremor
	* Bradykinesia
	* Rigidity
* Autonomic dysfunction
* Bulbar dysfunction
* Dementia

## Epidemiology and Risk Factors

Prevalence:

* Highly prevalent once over 50  
Lifetime risk:
	* Men: 2%
	* Women: 1.3%
* Second-most common neurodegenerative condition  
Following Alzheimer disease.


## Pathophysiology

Histologically characterised by:

* Loss of dopaminergic neurons in the nigrostriatal system  
60-80% loss required for motor symptoms to be present.
* Lewy bodies in brainstem


### Aetiology

Multifactorial:

* Genetic   
5-10%.
* Environmental
	* Pesticides
	* Heavy metals
	* Well water
	* Woodworking
	* Head injury
	* Carbon monoxide

## Clinical Manifestations

**Four** cardinal symptoms:

* Tremor  
Rhythmic oscillation around a fixed point in the rest position.
	* Often first symptom
	* Usually a resting tremor
	* Characteristics include:
		* Asymmetrical  
		Bilateral once deterioration occurs.
		* Supination/pronation
		* "Pill-rolling"
* Rigidity
* Bradykinesia  
Slowness of movement. May be:
	* Initiation
	* Continuation
* Postural instability  
Balance dysfunction.
	* Major cause of falls, and subsequent injury and loss of independence




Secondary motor symptoms:

* Dyskinesia  
Involuntary, prolonged muscle contractions with abnormal posturing.
	* Usually occurs when dopamine levels are low  
	SUch as early morning.
* Motor fluctuations  
Times of poor response to levodopa, and associated with advancing disease.
* Reduced arm swing
* ↓ blink rate
* Masked facies
* ↓ voice volume
* Difficulty turning over


> Non-motor symptoms may also fluctuate:
> * In off states: Poorer mood, and dysautonomia
> * In on states: Mania, agitation, delusions, paranoid, impulsivity

Autonomic dysfunction:

* Orthostatic hypotension
* Constipation
* Incontinence
* Nausea/Vomiting


Neuropsychiatric manifestations:

* Mood disorders
	* Depression
	* Anxiety
	* Apathy
* Impulse control
* Psychosis
* Hallucinations
* Panic attacks
* Executive dysfunction
* Dementia


## Diagnostic Approach and DDx

Remains a clinical diagnosis.

## Investigations

## Management

>* Therapy targeted to symptoms
>* Dopaminergic replacement when symptoms become bothersome
>* Surgical treatment is indicated when motor symptoms are unable to be ameliorated by medication


### Medical

* Levodopa  
Dopamine precursor.
	* Gold standard
	* Administered with a dopa-decarboxylase inhibitor (e.g. carbidopa) to reduce peripheral breakdown and nausea  
	Variable preparations:
		* Immediate release
		* Extended release
		* Orally disintegrating tablet
		* Gel for PEG administration
	* Effective for rigidity and akinesia
	* Variable effects on tremor
	* Treatment does not worsen disease progression but high daily doses and long duration of *disease* is associated with motor fluctuations and dyskinesias
	* Benefit ↓ as disease worsens  
	Reduced storage and release of dopamine limits utility of levodopa therapy.
* Dopamine agonists  
Directly agonise receptors, bypassing degenerating dopaminergic neurones.
	* Used as monotherapy or adjuncts
	* Longer half-life
	* ↑ incidence of psychiatric side effects
	* Agents included:
		* Pramipexole
		* Ropinirole
		* Rotigotine
		* Apomorphine  
		Rescue medication given subcutaneously.
* COMT inhibitors  
Reduce levodopa breakdown.
	* Used in conjunction with levodopa
	* May ↑ dyskinesia
	* Include:
		* Entacapone
		* Tolcapone
* MAO-B inhibitors  
Reduce levodopa breakdown.
	* Include:
		* Selegiline  
		Selective, irreversible; used as an adjunct.
		* Rasagiline  
		Monotherapy or adjunct.

### Surgical

Deep Brain Stimulation:

* Modulation of brain circuitry via electrical stimulation
* Improves tremor, dyskinesia, and motor fluctuations

### Anaesthetic Considerations


* A
	* Potential difficult airway
		* Cervical spine rigidity
		* TMJ dysfunction
	* Aspiration
		* **Bulbar dysfunction**  
		* Oesophageal dysfunction  
		Bradykinesia and pharyngeal rigidity ↑ aspiration risl.
		* Gastroparesis
		* Sialorrhoea
* B
	* Chest wall rigidity
		* Impaired secretion clearance
* C
	* **Autonomic instability**
* D
	* Parkinsonian medications  
	Medication management is critical.
		* Continue anti-Parkinson's drugs perioperatively
			* Give up to the time of surgery  
			Except prior to deep brain stimulator placement.
			* Restart as soon as possible after surgery
		* Avoid dopamine antagonists
			* Metoclopramide
			* Typical antipsychotics  
			Droperidol, haloperidol.
			* Phenothiazines  
			Chlorpromazine.
		* **MAO-I** use  
		Selegiline.
	* **Deep brain stimulators**  
	Consist of electrodes implanted into brain parenchyma, a pulse generator located (usually) below the clavicle, and a wire connecting them.
		* Preoperatively  
		Assess:
			* Model, location, last check, battery life
			* Severity of symptoms when disabled
			* How to use the patient programmer  
			Particularly how to turn it on and off.
			* Discuss with patients neurologist about any post-operative checks required
			* Path of wires and location of device to avoid iatrogenic injury
		* Intraoperatively
			* Turn device off to minimise EMI  
			Can turn off after induction if severe symptoms.
			* Regional anaesthesia may require ↑ sedation to control symptoms whilst off
			* Turn device on prior to emergence
			* Use bipolar diathermy in short bursts with lowest possible power
		* Post-operatively
			* Neurological examination to rule out adverse events
			* Device check by product representative or neurologist
	* Opioids  
		* Muscle rigidity
		* Dystonic reactions
	* **Dementia**
* E
	* **Motor function**

### Marginal and Ineffective Therapies

## Complications

Parkinson Hyperpyrexia Syndrome:

* Potentially fatal complication of withdrawal of antiparkinsonian medications leading to sudden suppression of central dopaminergic activity
* Additional precipitants include:
	* Neuroleptics
	* Dehydration
	* Hot weather
* Presents 18-24 hours following the trigger
* Clinical features include:
	* Initial tremor, rigidity, and leads to immobility
	* Later (24-72 hours) development of pyrexia and obtundation
	* Autonomic dysfunction  
	Tachycardia, labile BP, fever.
* Treatment recommendations include:
	* Replace antiparkinsonian medications
		* Premorbid levodopa dose
		* Dopamine agonists
	* Supportive therapy
		* HDU
		* Cooling
		* Consider dantrolene if rigidity not responding to other measures
* Complications of the syndrome include:
	* Aspiration pneumonia
	* DVT/PE
	* DIC
	* Rhabdomyolysis
	* Seizures


## Prognosis

Progression subdivided into three stages:

* Preclinical phase  
Asymptomatic neurodegeneration.
* Prodromal phase  
Symptoms present but insufficient for diagnosis.
* Clinical phase  
Symptoms manifest and recognisable.

## Key Studies


---

## References

1. Zesiewicz TA. Parkinson Disease. CONTINUUM: Lifelong Learning in Neurology. 2019 Aug;25(4):896. 
2. Newman EJ, Grosset DG, Kennedy PGE. The Parkinsonism-Hyperpyrexia Syndrome. Neurocrit Care. 2009;10(1):136-140. doi:10.1007/s12028-008-9125-4
3. Yeoh, Tze Yeng, Pirjo Manninen, Suneil K. Kalia, and Lashmi Venkatraghavan. ‘Anesthesia Considerations for Patients with an Implanted Deep Brain Stimulator Undergoing Surgery: A Review and Update’. Canadian Journal of Anesthesia/Journal Canadien d’anesthésie 64, no. 3 (1 March 2017): 308–19. https://doi.org/10.1007/s12630-016-0794-8.
