# Post-Dural Puncture Headache

PDPH is **postural** headache occuring as a complication of neuraxial anaesthesia. PDPH is divided into:

* Mild PDPH  
No affect on daily activities, responds to non-opioid analgesia.
* Moderate PDPH  
Predominantly bedridden, requires opioids.
* Severe PDPH  
Completely bedridden, associated symptoms, no response to conservative therapy.


## Epidemiology

* Occurs in ~1-2% of labour epidurals
* Exceedingly rare following LP with modern spinal (25-27G) needles
	* Risk increases as gauge decreases


## Pathophysiology

* Puncture of the dura causes CSF to leak into the epidural space, reducing CSF volume.

## Clinical Manifestations

May be recognised during procedure as:

* CSF leak from Tuohy needle during epidural insertion
* Aspiration of CSF from catheter

Symptoms:

* Headache
* Worse when sitting/standing
* Nausea/Vomiting
* Blurred vision/diplopia  
Due to 6^th^ nerve stretch

## Investigations



## Management

*Procedural management options are covered under [epidural](/anaesthesia/regional/epidural.md).*

Management of established PDPH:

* Mild and moderate PDPH  
Conservative approach:
	* Best rest
	* Oral analgesia

* Severe PDPH  
	* Neostigmine and Atropine  
	 20 µg/kg neostigmine and 10 µg/kg atropine in 20 mL of 0.9% saline given over 5 minutes every 8 hours until resolution.
	 	* Resolution usually seen within 2 doses
	 	* Atropine increases CSF secretion and reverses cerebral vasodilation
	 	* Neostigmine also reduces cerebral vasodilation
	* Epidural blood patch

### Epidural Blood Patch  

Placement of patients own blood in epidural space, which clots and prevents futher CSF leakage.
* 70-90% efficacy
* Indications:
	* Severe PDPH  
	Note that prophylactic blood patch after a dural puncture is not effective.
* Contraindications:
	* Systemic fever
	* Systemic infection
	* Local infection
	* Coagulopathy
* Risks:
	* Failure
	* Back pain  
	Common for first 24-48 hours.
	* Dural puncture
	* Nerve injury
	* Infection
		* Abscess
		* Meningitis

Process:

* Aseptic technique  
Including blood draw.
* Epidural puncture at or 1 level below the original site  
Lowest puncture should be used if multiple punctures present.
* Following epidural puncture, draw 20-30ml of blood
* 10-30ml of blood injected  
	* Until pressure felt in back
	* Stop if radicular pain occurs
* Lay supine for 1-2 hours


#### Failure of BLood Patch

Failure may be due to:

* Incorrect diagnosis  
Diagnosis should be re-evaluated if patch fails. Consider:
	* Neurological consult
	* Cortical vein thrombosis  
	Mimics dural puncture and worsened by blood patch.
* Incorrect placement
	* A second or third blood patch may be required


### Ineffective Therapies

* Caffeine
* 5-HT
* ACTH
* Epidural saline


---

## References

1. Maronge, L., & Bogod, D. (2018). Complications in obstetric anaesthesia. Anaesthesia.
2. Mahmoud, Ahmed Abdelaal Ahmed, Amr Zaki Mansour, Hany Mahmoud Yassin, Hazem Abdelwahab Hussein, Ahmed Moustafa Kamal, Mohamed Elayashy, Mohamed Farid Elemady, et al. ‘Addition of Neostigmine and Atropine to Conventional Management of Postdural Puncture Headache: A Randomized Controlled Trial’ 127, no. 6 (2018): 6.
