# Subarachnoid Haemorrhage

Intracranial haemorrhage into the subarachnoid space that occurs commonly with other forms of intracranial haemorrhage, and is secondary to:

:::column-margin
Intra**cranial** haemorrhage can be divided into:

* Intra-axial\
Intracerebral haemorrhage.
* Extra-axial
	* EDH
	* SDH
	* SAH
	* IVH
:::

* Aneurysm rupture\
85% of all cases.
* Trauma
* Other
	* AVM
	* Pituitary apoplexy
	* Cocaine
	* Fistulae
	* Reversible cerebral vasoconstriction syndrome


| Grade | WFNS                                                                           | Grade | Modified Fisher                                                           |
| ----- | ------------------------------------------------------------------------------ | ----- | ------------------------------------------------------------------------- |
| **1** | GCS 15                                                                         | **0** | No SAH or IVH                                                             |
| **2** | GCS 13-14, no motor deficit                                                    | **1** | Thin SAH, no IVH                                                          |
| **3** | GCS 13-14, motor deficit                                                       | **2** | Thin SAH, IVH present                                                     |
| **4** | GCS 7-12                                                                       | **3** | Thick SAH, no IVH                                                         |
| **5** | GCS 3-6                                                                        | **4** | Thick SAH, IVH present                                                    |
| Notes: | Assists prognosis and determining post-operative destination. Graded from 1-5. |       | Radiological grading scale that predicts vasospasm risk. Graded from 0-4. |


: Grading of Subarachnoid Haemorrhage

:::column-margin
The Hunt & Hess grading system is largely deprecated due to high inter-rater *un*reliability, but is included as a historical footnote.

| Grade | Hunt & Hess                                                       |
| ----- | ----------------------------------------------------------------- |
| **1** | Mild headache, no or minimal nuchal rigidity                      |
| **2** | Moderate to severe headache, nuchal rigidity, may have CN deficit |
| **3** | Confusion or lethargy, with or without mild focal deficit         |
| **4** | Stuporous, severe focal deficit                                   |
| **5** | Comatose, posturing or no motor response                          |

: Hunt & Hess Grading

:::

## Epidemiology and Risk Factors

Aneurysmal SAH:

* Occurs in ~9/100,000
* Has a high mortality rate
	* 15% prehospital
	* 30% 30-day
* 40% make a good recovery\
Prognostication:
	* Age
	* Conscious state
	* Blood volume
* Risk factors include:
	* Patient
		* Age
		* Female
		* Smoking
		* Heavy ETOH use
		* Sympathomimetic drug use
	* Disease
		* HTN
		* PHx SAH
		* FHx SAH
		* Polycystic kidney disease
		* Type IV Ehlers-Danlos syndrome


## Pathophysiology


### Aetiology

## Clinical Manifestations

Typical presentation of:

* Sudden, severe headache
	* "Worst headache of life"
	* Different from usual headaches
	* 20% of patients may have had similar headache before\
	Potentially sentinel haemorrhage.
* Often associated with:
	* Loss of consciousness
	* Nausea
	* Vomiting
	* Photophobia
	* Meningeal irritation\
	More reliable in patients iwth higher GCS.

:::column-margin
Headache may occur without other symptoms, and patients may not seek medical attention or be misdiagnosed.
:::


## Diagnostic Approach and DDx

## Investigations

**Laboratory**:

* LP\
Recommended if negative or equivocal CT in the setting of high clinical suspicion. Important findings: 
	* Opening pressure
	* CSF collection in 4 consecutive tubes\
	RBC counts can be measured in each to exclude traumatic tap.
	* Xanthochromia\
		* By visual inspection\
		May take 12 hours to develop.
		* Spectrophotometry\
		Superior to visual inspection.

**Imaging**:

* Non-contrast CT head\
	* Sensitivity ↑ from 93% to 100% over 6 hours, and falls to 60% over the next 7 days.
	* Repeat CT should occur at 24-48 hours to identify any new infarctions\
	Those not attributable to EVD or IPH should be considered to be due to delayed cerebral ischaemia.
* CTA\
First-line vascular imaging to identify source, though may miss aneurysms ⩽4mm.
* MRI\
May be slightly superior to CT.
* DSA\
Gold-standard for vascular imaging, and facilitates treatment.
* Transcranial Doppler\
Used to monitor for vasospasm.
	* Suggested by a Lindegaard ratio >3\
	Mean velocity in the MCA/mean velocity in ipsilateral ICA.


**Other**:

* EEG\
Consider continuous EEG monitoring in patients who
	* Have a poor grade of SAH
	* Fail to improve

## Management

**Resuscitation**:\

* A
	* Secure if required
* C
	* Aggressive **blood pressure control** for the unsecured aneurysm
		* Target **SBP 100-160**mmHg or **MAP ≤110**mmHg\
		Adjust target based on premorbid baseline BP.
		* Agents should preferably be given by infusion, and include:
			* **Labetalol** 5-20mg/hr
		* Short-acting **opioids** for analgesia
			* Dexamethasone can be considered for meningeal irritation
		* Avoid hypotension
	* Maintain euvolaemia\
	Avoid hypervolaemia.
* H
	* Reverse anticoagulation


**Specific therapy**:

* Pharmacological
	* **Tranexamic acid**\
	For up to 72 hours prior to aneurysm repair to ↓ risk of rebleeding.
	* **Nimodipine**
		* 60mg Q4H PO\
		Can adjust to 30mg Q2H PO if symptomatic hypotension.
			* Commonly requires vasopressors
		* Administered to all SAH patients for **21 days**
		* Significantly improves outcome (↓ stroke by 34%) but does not appear to reduce radiological vasospasm\
		Neuroprotection probably by another mechanism.
* Procedural
	* **Aneurysm securing**
		* Transfer to high-volume aneurysm centre for securing of aneurysm
		* Securing recommended within 48 hours of onset
		* Decision for clipping or coiling depends on location aneurysm location and characteristics
			* **Clipping**\
			Favoured for aneurysms:
				* From the MCA
				* With a wide neck:body ratio
				* With crucial arteries from aneurysm dome
				* With a large parenchymal haematoma
			* Coiling\
				* Higher 1-year survival in patients who are equally suitable for clipping or clipping
				* ↑ Risk of rebleeding
				* Risk of rupture without option for immediate surgical control
	* EVD\
	Early if signs of hydrocephalus or IVH. Open at:
		* **10cmH~2~O** for **secured** aneurysm
		* **15cmH~2~O** for **unsecured** aneurysm


**Supportive care**:

* C
	* Defend CPP
* D
	* Glucose control\
	Careful control with strict avoidance of hypoglycaemia.
* E
	* Temperature control\
	Treat >38°C targeting normothermia, with aggressiveness based on risk of delayed cerebral ischaemia.
		* Anti-pyretics
		* Active cooling
* F
	* Hyponatraemia\
	Treat early with hydrocortisone and fludrocortisone.
* H
	* Anaemia\
	Hb level should be maintained at 80-100g/L.
	* DVT prophylaxis\
	UFH should be considered:
		* 24 hours after coiling
		* 48 hours after clipping\
		↑ Abstinence due ↑ bleeding risk of craniotomy.
	

**Disposition**:

* ICU
	* If intubated or airway concerns
	* Often required for haemodynamic control prior to securing aneurysm
	* May be required if EVD in situ, depending on ward skill
* Neurosurgical HDU
	

### Anaesthetic Considerations

### Marginal and Ineffective Therapies

* Prophylactic 'triple-H' therapy:
	* Not recommended due to lack of efficacy and evidence of harm
	* Consists of:
		* Hypervolaemia
		* Hypertension
		* Haemodilution\
		Theorised to improve laminar flow and ↑ overall DO~2~.
* Prophylactic anticonvulsants\
Routine use worsens outcomes.
* Tranexamic acid\
May ↑ risk of poor neurological outcome with no clear evidence of benefit.

## Complications

:::column-margin
DCI is covered in detail under @sec-vasospasm.
:::

* C
	* Myocardial injury\
	Catecholamine surge with risk of myocardial necrosis.
		* LV dysfunction in 10-30%
		* Neurocardiogenic shock/Takotsubo cardiomyopathy may arise due to combination of ↑ preload and afterload (catecholamines), and ↓ inotropy (necrosis)
* D
	* **Rebleeding**\
	Major life-threatening complication
		* 20% of patients in first 24 hours
		* Majority (50-90%) occur within 6 hours
		* Uncommon after 72 hours
		* 20-60% mortality
	* **DCI**\
	Leading cause of neurological morbidity due to cerebral infarction.
	* Secondary **hydrocephalus**
		* Occurs in 20% of patients\
		Within minutes to hours of onset.
		* Requires EVD
	* **Seizures**
		* Occurs in 26% of patients\
		Correlated with blood volume and MCA aneurysms.
		* Levetiracetam is first line
* F
	* Hyponatraemia\
	30% of cases.
		* CSW
	* Hypernatraemia

:::column-margin
Delayed cerebral ischaemia is covered in detail under @sec-vasospasm.
:::

## Prognosis

Poor prognostic features:

* Age
* Medical comorbidities
* Delayed Cerebral Ischaemia
* Hyperglycaemia
* Anaemia


Good prognostic features:

* High-volume neurosurgical centre


## Key Studies

{{< include /trials/ultra.qmd >}}


---

## References

1. Okazaki T, Kuroda Y. Aneurysmal subarachnoid hemorrhage: intensive care for improving neurological outcome. Journal of Intensive Care. 2018 May 8;6(1):28. 
1. Muehlschlegel S. Subarachnoid Hemorrhage. Continuum (Minneap Minn). 2018 Dec;24(6):1623–57.
1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.
1. Post R, Germans MR, Tjerkstra MA, et al. [Ultra-early tranexamic acid after subarachnoid haemorrhage (ULTRA): a randomised controlled trial](https://doi.org/10.1016/S0140-6736(20)32518-6). The Lancet. 2021;397(10269):112-118. doi:10.1016/S0140-6736(20)32518-6
