# Seizures {#sec-seizure}

Seizures are the **clinical manifestation** of an **abnormal** and **excessive** **discharge** of **neurones**, with alterations of consciousness, motor, sensory, or autonomic function. Seizures are classified into:

:::column-margin
Covers emergency management of seizures, including status epilepticus. Other seizure disorders include:

* NCSE, covered at @sec-ncse
* Epilepsy, covered at @sec-epilepsy
* Eclampsia, covered at @sec-eclampsia
:::

* **Partial**\
Arise from one hemisphere.
	* Simple
	* Complex
	* Partial onset, becoming generalised
* **Generalised**\
Activity across both hemispheres.
	* Inhibitory
		* Absence
		* Atonic
	* Excitatory
		* Myoclonic
		* Clonic
		* Tonic
* **Pseudoseizures**
* **Non-epileptic** seizures


:::crisis
**Status Epilepticus** is:

* A medical **emergency**
* Defined as *either*:
	* **Continuous seizure** activity for **5 minutes** without return of consciousness
	* **Recurrent seizure** activity over **30 minutes**, between which **consciousness** is **not regained**\
\
* **Refractory status epilepticus** are seizures non-responsive to first and second line agents
* **Super-refractory status epilepticus** are seizures continuing despite general anaesthesia
:::


## Epidemiology and Risk Factors

## Pathophysiology

Physiological changes occur in two stages:

* First stage
	* ↑ Cerebral metabolism
	* ↑ CBF
	* ↑ BSL and lactate
	* ↑↑ Catecholamine release
		* ↑ CO/HR/BP/CVP\
		Compensation reduces cerebral damage in first 30-60 minutes.
	* ↑ Temperature\
	Only partially obviated by muscle relaxation, as partially driven by ↑ sympathetic drive.
	* Normal termination mechanisms fail
		* Internalisation of GABA receptors\
		Accounts for ↓ response to benzodiazepines with ↑ seizure duration.
* Second stage\
Compensatory mechanisms exhausted.
	* Cerebral damage may occur
	* Failure of cerebral autoregulation
		* Hypoxia
		* ↓ BSL
		* Cerebral oedema\
		↑ ICP.
	* ↑ Catecholamines\
	Cessation may precipitate hypotension and hypoglycaemia following seizure resolution.


### Aetiology

Causes may be multifactorial, as multiple insults may ↓ seizure threshold:

* B
	* Hypoxia
* C
	* Hypertensive encephalopathy
		* **Eclampsia**\
		Aggressive control of seizures in pregnancy is required for good foetal outcome.
		* PRES
* D
	* CVA
	* Tumour
	* Degenerative
		* Dementia
		* Alzheimer's Disease
	* Post-syncope
	* Chronic epilepsy
* F
	* Hypo/hypernatraemia
	* Hypo/hypercalcaemia
	* Hypo/hypermagnesaemia
	* Hypoglycaemia
	* Uraemia
* G
	* Hepatic encephalopathy
* Immune
	* Multiple sclerosis
	* Autoimmune encephalitis
		* anti-NMDA receptor antibodies
		* anti-VGKC receptor antibodies
		* Paraneoplastic
* Traumatic\
Post-traumatic epilepsy associated with:
	* Early seizures
	* Depressed skull fractures
	* ICH
	* TBI
* Infective
	* Meningitis
	* Encephalitis
* Toxin/Drug
	* **Low antiepileptic drug levels**
	* Toxicity
		* Antibiotics
			* Cephalosporins
			* Isoniazid
		* Immunosuppression
			* Tacrolimus
		* TXA
		* Recreational
			* **Alcohol**\
			Toxicity and withdrawal.
			* Cocaine
			* Amphetamines



## Clinical Manifestations

:::info
* Most convulsive seizures cease within 2-3 minutes
* Any **seizure continuing ⩾5 minutes** is **unlikely** to **resolve** spontaneously
* All seizures lasting ⩾2 minutes longer than the patients usual seizure should be treated
* Rapid control ↓ brain injury
* ↑ Seizure duration associated with:
	* ↓ Response to treatment
	* ↑ Risk of refractory status epilepticus
:::

Seizures affect:

* Consciousness
* Motor function
	* Tonic-clonic (sustained-interrupted) seizures
	* May begin generalised or with focal onset, evolving into bilateral convulsive SE
* Autonomic function
	* Urinary incontinence
* Sensory function


History should cover:

* Seizure
	* Time of onset
	* Time of offset
	* Prodromal symptoms
	* Manifestations\
	Sequence of involvement/evolution.
* Past or family history of epilepsy
* Medications taken\
	* Compliance
	* New medications
	* Recreational drug use
* Other precipitants
	* Drug withdrawal


## Diagnostic Approach and DDx

Include:

:::column-margin
Determination of pseudo-seizures can be difficult and is best confirmed with EEG.
:::

* Psychogenic non-epileptic seizures (pseudoseizures)
	* Variable manifestations from event to event
	* Non-sustained convulsions
	* ↑ Movement with restraint
	* Suggestible movements
	* Resistance to eye opening
	* Absence of pupillary dilatation
	* Normal tendon reflexes post-convulsion
	* Paucity of metabolic consequences
* Syncope

:::column-margin
Jerking and tonic posturing is common in syncope. The **10/20 rule** states:

* <10 jerks is likely secondary to syncope
* \>20 jerks is a convulsive seizure
:::

## Investigations

**Bedside**:

* ABG
	* Lactate
	* BSL


**Laboratory**:

* Blood
	* FBE/Coagulation assay
	* UEC
	* CMP
	* LFTs
	* TFTs
	* Porphyrins
	* Drug levels
		* Antiepileptic
		* Alcohol
		* Benzodiazepines
* LP\
If consideration of:
	* Infection
	* Autoimmune encephalitis


**Imaging**:

* CXR\
Aspiration.
* CTB\
Investigation of structural cause.


**Other**:

* EEG
	* Diagnostic
	* Required following resolution without improvement in conscious state\
	15% of this group have NCSE.
	* Changing appearance over time
		* Initially discrete seizure activity
		* Continuous monomorphic discharges
		* Periodic epileptiform discharges
	* Continuous EEG required for refractory status, ideally with video monitoring if available



## Management {#sec-seizuremx}

:::info
**Principles**:

* Seizure termination\
**Early benzodiazepines**. Definitive control should occur within 60 minutes of onset.
* Prevent secondary brain injury
* Treat underlying cause
* Prevent recurrence
:::

:::column-margin
The more the seizure is disturbing consciousness, the greater the risk of brain injury to the patient therefore there is strong justification to escalate treatment.
:::

**Resuscitation**:\

* A
	* Airway protection\
	If intubation is required, consider **suxamethonium** so seizure recurrence can be rapidly identified.
* B
	* Supplemental oxygenation
* C
	* IV access
* D
	* **50% Dextrose** 50mL IV with **thiamine** 100mg IV\
	Low threshold if ↓ BSL is a possibility.
	* **Seizure termination**\
	See below.


**Specific therapy**:

:::column-margin
Interestingly, patients convulsive status are unlikely to get respiratory depression following benzodiazepines.
:::

* Pharmacological
	* Seizure termination\
{{< include /includes/seizure_rx.qmd >}}
* Procedural\
Last-line therapy for refractory status may include:
	* Deep brain stimulation
	* Surgical resection
		* Callostomy


**Disposition**:



### Anaesthetic Considerations

### Marginal and Ineffective Therapies

* Hypothermia\
Theorised to be neuroprotective in setting of seizures.
* Muscle relaxation\
Prevent the metabolic cost of seizures, however renders it unclear if fitting has ceased.

## Complications

* Death\
10-20% of status epilepticus.
* B
	* Aspiration pneumonitis
	* Neurogenic pulmonary oedema
* D
	* Permanent neurological deficit
		* Primary injury\
		Neuronal cell death occurs after ~30 minutes of status. Occurs in 10-16% of status.
		* Secondary injury
			* Hypoxia
			* Hyperthermia
			* Hypotension
	* Focal epilepsy
	* Todd's Paresis\
	Transient (hours-days) focal weakness following seizure activity in that limb.
* E
	* Rhabdomyolysis
	* Hyperthermia
* F
	* Glucose derangements
		* Hyperglycaemia\
		Early, due to catecholamine release.
		* Hypoglycaemia\
		Late, due to catecholamine tachyphylaxis.
		* Lactic acidosis


## Prognosis

Poor prognostic signs include:

* Age
* Aetiology
	* CNS infection
	* HIE\
	Usually fatal.
* Degree of impaired consciousness
* Refractory status\
↑ Mortality and ↓ chance of returning to functional baseline.

Good prognostic signs include:

* Aetiology
	* Drug withdrawal
	* Drug induced
	* Systemic infection

## Key Studies

{{< include /trials/esett.qmd >}}

---

## References

1. Gratrix AP, Enright SM. Epilepsy in anaesthesia and intensive care. Continuing Education in Anaesthesia Critical Care & Pain. 2005 Aug;5(4):118–21. 
1. Perks A, Cheema S, Mohanraj R. Anaesthesia and epilepsy. Br J Anaesth. 2012 Apr 1;108(4):562–71.
1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.
1. Neurocritical Care Society Status Epilepticus Guideline Writing Committee et al. [Guidelines for the Evaluation and Management of Status Epilepticus](https://doi.org/10.1007/s12028-012-9695-z). Neurocritical Care 17, no. 1 (August 2012): 3–23.
1. Kapur J, Elm J, Chamberlain JM, et al. [Randomized Trial of Three Anticonvulsant Medications for Status Epilepticus](https://www.nejm.org/doi/full/10.1056/NEJMoa1905795). New England Journal of Medicine. 2019;381(22):2103-2113. doi:10.1056/NEJMoa1905795
1. Shmuely S, Bauer PR, van Zwet EW, van Dijk JG, Thijs RD. [Differentiating motor phenomena in tilt-induced syncope and convulsive seizures](https://n.neurology.org/content/90/15/e1339.long). Neurology. 2018 Apr 10;90(15):e1339–46. 