# Delayed Cerebral Ischaemia {#sec-vasospasm}

:::info
DCI was historically referred to as **vasospasm** due to the narrowed cerebral vasculature seen on angiogram. The nomenclature has changed due to recognition that:

* The pathophysiology is more complex than just vasoconstriction
* Not all patients with radiological vasospasm are symptomatic
* Not all symptomatic patients have radiological vasospasm
:::

Acute neurological deterioration in the setting of SAH that:

* Consists of one or more of:
	* **New focal** neurological **deficit**
	* **Drop** in **GCS** by **⩾2**
	* Cerebral infarction
* Lasts **>1 hour**
* Is **not otherwise explained**


## Epidemiology and Risk Factors

Risk factors:

* SAH
	* Directly related to volume of interventricular blood.
	* Risk between **4-21 days**
		* **Greatest** risk between **4-10 days**
		* Develops in **one-third** of SAH patients between **4 and 14 days**
* Hyponatraemia

## Pathophysiology

Mechanisms include:

* Vasospasm\
Of large and medium-sized intracranial arteries.
* Microcirculatory dysfunction
* Microthrombosis
* Cortical spreading depolarisation
* Neuro-inflammation

### Aetiology

## Clinical Manifestations

## Diagnostic Approach and DDx

## Investigations

**Imaging**:

* CT Brain & Circle of Willis angiogram

## Management

:::priority
Aggressive management of vasospasm is critical to prevent neurological injury and should progress in a stepwise fashion:

* Euvolaemia
* Induced hypertension
* Formal angiography with:
	* Cerebral angioplasty
	* Direct cerebral vasodilators
:::

**Specific Therapy**:

* Pharmacological
	* **Volume** resuscitation\
	To euvolaemia.
	* **Induced hypertension**\
	Process of ↑ SBP and monitoring for neurological improvement or complications of hypertension.
		* Depending on preference for MAP or SBP targets, initially aim:
			* MAP 20mmHg above baseline
			* SBP 20-40mmHg above baseline
		* Use noradrenaline\
		**Avoid vasopressin**, may ↑ water retention and ↓ Na^+^.
		* Continue to augment SBP until:
			* Neurology resolves
			* SBP 200mmHg
			* Complications of hypertension
			* Noradrenaline 20μg/min\
			Consider echocardiography to evaluate pump function.
	* **Nimodipine**
		* 60mg Q4H PO\
		Can adjust to 30mg Q2H PO if symptomatic hypotension.
		* Administered to all SAH patients for 21 days
		* Improves outcome but does not appear to reduce radiological vasospasm\
		Neuroprotection probably by another mechanism.
* Procedural
	* Consider **interventional radiology** for vasospasm-related DCI for provision of:
		* Intraarterial vasodilators
		* Angioplasty

### Anaesthetic Considerations

### Marginal and Ineffective Therapies

## Complications

* C
	* APO
	* Stress induced cardiomyopathy\
	Via ↑ catecholamines.
		* Milrinone 1^st^-line if inotropes required
* D
	* Seizures
	* Infection
	* Cerebral oedema
* I
	* Infection
	* Fever\
	Intracranial blood is pyrogenic.


## Prognosis

## Key Studies


---

## References

1. Okazaki T, Kuroda Y. Aneurysmal subarachnoid hemorrhage: intensive care for improving neurological outcome. Journal of Intensive Care. 2018 May 8;6(1):28. 
2. Muehlschlegel S. Subarachnoid Hemorrhage. Continuum (Minneap Minn). 2018 Dec;24(6):1623–57.
3. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.
