# Transvenous Pacing

Emergency transvenous pacing is indicated for:

* Haemodynamically unstable bradycardia that is unresponsive to medical therapy\
Includes:
	* Symptomatic bradycardia
	* AV block
	* Asystole

## Indications

## Contraindications

## Anatomy

## Equipment

* Sheath
* Transvenous pacing wire
* Pacing adaptor\
To connect wires to pacing system.
	* Black to negative terminal
	* Red to positive terminal
* Pacing cable ("bridging cable")
* External pacing system


## Technique

Insertion:

* Ensure ECG connected
* Place 5-6Fr introducer\
	* Right IJV best for convenience and familiarity
	* Aim to avoid left SCV - may be needed for a permanent system
* Insert pacing wire through sheath and connect sterile sheath
* Apply dressing\
The sterile portion of the procedure is now completed.

:::column-margin
The wire is easier to float into position without the sterile sheath in situ, and can be done if you have a skilled assistant who can handle the non-sterile aspects of the procedure.
:::

Establish pacing:

* Set external pacing system\
Consider VVI 80, output 15-20mA, sensitivity threshold 0.8mV.
* Attach external pacing system to wires
	* Distal lead to negative terminal
	* **Proximal** lead to **positive** terminal
* Inflate balloon\
Ensure balloon is out of the end of the introducer.
* Slowly insert wire, looking for:
	* ↑ HR to set rate
	* Alternation of QRS morphology
	ST segment elevation in V~1~ or LBBB appearance.
* Secure wire in location
* *Partially* deflate balloon (0.5mL)
	* Full deflation of the balloon may ↑ risk of perforation\
	Full deflation can be used if there is concern about advancement of the catheter into the PA.
	* No deflation ↑ risk of wire dislodgement
* Have patient cough to ensure wire doesn't move
* Perform pacing check
	* Sensitivity testing\
		* Should only be performed if the patient has a haemodynamically stable rhythm with a native HR >30 bpm
		* Sensing threshold should be ideally **>5mV**
	* Capture testing
		* Capture threshold should be <1mA if the lead is correctly placed
		* Capture threshold >5mA is concerning for lead malposition

:::column-margin
Echocardiographic guidance can be helpful for guidance.
:::

:::column-margin
Performance of a pacing check is covered in detail under @sec-pacing.
:::


Removal:

:::column-margin
Consider removal in the morning in usual business hours to ↓ risk of tamponade.
:::

* Ensure restoration of a normal rhythm, or availability of alternative pacing
* Disconnect the pacing box
* Fully deflate the balloon
* Remove the wire via the sheath

## Complications

High rate of complications, usually as a function of low-volume of practice:

* Central access
	* Pneumothorax
	* Haemothorax
	* Arterial injury
	* Central vein thrombosis
* Pacing lead
	* Cardiac perforation
		* Tamponade
* Pacing
	* Undersensing\
	Inappropriate pacing and arrhythmia.
	* Oversensing
	* Diaphragmatic pacing\
	Associated with RV perforation.


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.