# Pulmonary Function Tests


*Preoperative assessment for thoracic surgery is covered under [thoracic principles](/anaesthesia/thoracics/thoracic-principles.md#lung).*

Pulmonary function tests are used to:

* Diagnose disease
* Monitor response to therapy
* Monitor disease progress
* Perioperatively for:
	* Lung resection
	* Other surgery
* Evaluate disability
* Prognosticate


Includes tests of:

* Ventilation
* Gas exchange
* Other

## Testing

May involve testing:

* Ventilation
* Gas exchange
* Other

## Ventilation Tests

Include:

* Peak flow
* Spirometry
* Total body plethysmography

### Peak Flow

Patient forcefully exhales from a vital capacity breath into a peak flow meter:

* Measures peak expiratory flow rate
* Cheap and easy to perform
* Used in monitoring course of obstructive disease\
Asthma and COAD.

### Spirometry

Process:

* Patients breaths in and out of a flowmeter
	* Difficult to coordinate in children under 5
* Allows all volumes *except* residual volume to be measured, i.e.
	* Tidal volume
	* Expiratory reserve volume
	* Inspiratory reserve volume
* From this, capacities calculated include:
	* Vital capacity
	* Inspiratory capacity
* Forced vital capacity can also be measured\
Tests ability of lungs to act as a bellows ,and is reduced by restrictive disease.
	* FEV~1~ can be derived\
	Indicates how effectively a patient can cough, and is reduced in obstructive disease.
	* FEV~1~/FVC ratio\
	Allows differentiation between obstructive and restrictive disease.
		* Normal is ~80%
* May be performed before-and-after bronchodilator use\
Assesses reversibility of disease.



Interpretation:

* Validity\
Multiple best-effort measurements should be taken, and FEV~1~ and FVC measurements should be within 0.2L
* FEV~1~FVC ratio of <70% (adults) or <85% (children) of predicted\
Indicates an **obstructive** defect.
	* Reversibility demonstrated by >12% ↑ following bronchodilator\
	Asthma is usually reversible, COPD is not.
	* Multiple grading systems, the GOLD 2008/NICE 2010 system:
		* FEV~1~ ⩾80% predicted\
		Mild.
		* FEV~1~ 50-79% predicted\
		Moderate.
		* FEV~1~ 30-49% predicted\
		Severe.
		* FEV~1~ ⩽30% predicted\
		Very severe.
* FVC <80% predicted\
Indicates a **restrictive** defect.
* Presence of both a reduced FVC and reduced FEV~1~/FVC ratio indicates a **mixed defect**

### Total Body Plethysmography\

Allows measurement of volumes and capacities that are not measured with spirometry, including:

* Residual volume
* Functional residual capacity
* Total lung capacity

## Gas Exchange Testing

Include:

* Transfer factor (TLCO)

### Transfer Factor (TLCO/DLCO)

Measures the diffusion capacity of the lungs for carbon monoxide, which can be used to calculate the functional surface area of the lungs. Involves:

* Laboratory test
* Involves:
	* Single-breath of 10% helium with 0.3% CO
		* Helium is minimally absorbed and so can be used to calculate the initial concentration of CO
		* CO is highly bound by Hb and so the partial pressure in the blood remains low, such that the primary determinant of CO absorption is the diffusing capacity of the lungs
	* Patient holds breath for 10-20s
	* First 750mL of gas is discarded\
	To ensure dead space removed.
	* Subsequent litre is analysed
	* Residual CO can be used to calculate how much CO has been absorbed
	* The amount of CO absorbed allows diffusing capacity to be calculated
* Reduced by:
	* ↑ thickness\
	Fibrosis.
	* ↓ area\
	Lung resection, emphysema.
	* Reduced ability to bind to Hb\
	Anaemia.

## Other Tests

Include:

* Maximal breathing capacity
* Cardiopulmonary exercise testing
* 6-minute walk test

### Maximal Breathing Capacity\

Maximal volume of air that can be breathed when the subject hyperventilates as forcefully as possible:

* ⩽40% predicted indicates high perioperative risk


### Cardiopulmonary Exercise Testing

Provides a functional assessment of cardiopulmonary reserve:

* Involves:
	* Exercising at ↑ intensity on an exercise bike
	* Inspired and expired O~2~ and CO~2~ are measured
	* Aims to calculate VO~2~ max and anaerobic threshold


---

## References

1. Portch D, McCormick B. Pulmonary Function Tests and Assessment for Lung Resection. Update in Anaesthesia.
1. Gould G, Pearce A. Assessment of suitability for lung resection. Contin Educ Anaesth Crit Care Pain. 2006 Jun 1;6(3):97–100. 
1. Johnson JD, Theurer WM. A Stepwise Approach to the Interpretation of Pulmonary Function Tests. AFP. 2014;89(5):359-366.
