# Primary Survey

> * Aims to **identify and treat immediately life threatening injuries**
> * These injuries should be **actively looked for and excluded**:
>	* **A**irway Obstruction
>	* **T**ension Pneumothorax
>	* **O**pen Pneumothorax
>	* **M**assive haemorrhage
>	* **H**aemothorax
>	* **F**lail Chest and pulmonary contusion
>	* **C**ardiac Tamponade

The primary survey follows the **CABCD** approach:

* **Safe Approach**  
Ensure the approach to the patient is safe.


* **C**  
Catastrophic haemorrhage control.
	* Control of immediately life threatening bleeds only
	* Typically applies to extremety trauma  
	* Interventions  
	**DDIT**:
		* Direct Pressure
		* Direct Pressure (more)
		* Indirect Pressure  
		To artery proximal to injury.
		* **Torniquets**
		* Consider:
			* Wound packing
			* Haemostatic agents


* **A**  
Airway assessment and immediate management:
	* Rapid Assessment:  
	Ask the patient to:
		* **Identify themselves and what happened**  
		This indicates airway patency, adequate breathing, conscious state.
		* Open their mouth
		* Take two deep breaths
		* Cough
		* Ask: "Does your breathing feel normal?"  
		If the above are normal, then the chance of a serious breathing problem is unlikely.
		* Ask: "Where do you hurt?"
		* Ask: "Where else do you hurt?"
	* Check for **threatened airway**:
		* Unconsciousness/obtundation  
		Loss of airway reflexes.
		* **Patency**
			* Look for obstruction or foreign body
			* Listen for stridor, gurgling, abnormal phonation
			* Consider:
				* Facial, mandibular, tracheal, or laryngeal fractures
	* Interventions to restore patency:
		* Basic manouvres
		* Place OPA
		* Intubate  
		Consider when:
			* Patient, team, and environment are optimised.  
			Roles assigned (including MILS).
			* SpO2 < 93%
			* GCS < 8



* **B**  
Assess breathing (**RU IN SHAPE**). If there are no signs of life, commence traumatic cardiac arrest protocol.
	* Assessment:
		* Respiratory Rate  
		Significant when:
			* RR > 20
			* RR < 8
		* Unequal movements
		* Injuries  
		Major thoracic trauma.
		* Search
		* Hands on  
		Palpate.
		* Auscultate
		* Percuss
		* (Everywhere)
		* Interventions to optimise
	The **respiratory support ladder**:
		* Rescue  
		If entrapped.
		* Optimise positioning
		* Oxygen
		* Analgesia
		* NIV
		* Decompression
		* RSI


* **C**  
Assess perfusion:
	* GCS
	* Capillary return  
	Central >3 seconds.
	* Pulse  
		* Present
		* \>120
	* Fluid responsiveness
	* Actively look for sources of bleeding  
	**SCALPER**:
		* Scalp
		* Chest
		* Abdomen  
			* Pain on palpation away from bruises
			* Fat fractures suggest high risk of hollow organ injury  
			Divet felt under intact skin.
		* Long Bones
		* Pelvis  
			* Pain suggests pelvic injury
		* External  
		"The Floor."
		* Retroperitoneum


* **D**  
Assess neurology:
	* GCS
	* Pupillary size and reaction
	* Focal defect
	* Spinal Cord Injury level


* **E**  
Exposure and extremities:
	* Completely undress
	* Logroll
	* **Cover and rewarm**

### Adjuncts to the Primary Survey

* **A**
	* Capnography  
	Confirm ETT position.
* **C**
	* Ultrasound  
	FAST scanning:
		* Free fluid in abdomen
		* Pneumothorax in chest
	* ECG
		* Dysrhythmias/ST segement changes  
		May indicate blunt cardiac injury or causative event (e.g. MI leading to MVC).
	* IDC
		* Consider filling bladder to tamponade pelvic venous bleeds 

---