# Secondary Survey

> * Only begins once primary survey is completed and resuscitation is underway
> * Aims to identify important, but not immediately treatable life-threatening (or **immediately treatable**) life-threatening injuries
> * The following injuries should be **actively looked for and excluded** during the secondary survey:  
>Imaging will be required.
>	* Tracheobronchial tree injury
>	* Pneumothorax
>	* Pulmonary contusions
>	* Haemothorax
>	* Blunt cardiac injury
>	* Traumatic aortic injury
>	* Oesophageal rupture
>	* Traumatic diaphragmatic injury


The secondary survey is a thorough head-to-toe evaluation, including complete history, physical examination, and reassessment of vitals.

* Head
	* Scalp & Skull  
	Lacerations and fractures.
	* Brief cranial nerve examination
	* Eye
		* Acuity
		* Mobility  
		May be reduced with entrapment.
		* Pupil size
		* Penetrating injury
		* **Contact lenses**
		* Lens dislocation
	* Ear
		* BoS fracture
		* Membrane integrity
	* Midface
	* Mandible


* Neck
	* C-spine tenderness
	* SC emphysema
	* Tracheal deviation
	* Laryngeal fracture
	* Carotid palpation and auscultation
		* Overlying blunt injury may require angiography
		* Blunt carotid injuries may cause intimal tears and present late
	* Lacerations
	* Distension of neck veins
		* Tamponade/tension pneumothorax will ↑ right sided filling pressures and raise CVP
		* Hypovolaemia will reduce filling pressures


* Chest
	* Palpate ribs, clavicle, sternum
	* Auscultate anterior chest wall and bases


* Abdomen


* Pelvis
	* Bruising of iliac wings, scrotum/labia suggests pelvic fracture
	* Pelvic spring
	* Rectal examination
		* If mechanism suggests injury
		* If patient is unconscious
	* Vaginal examination
		* If mechanism suggests injury
		* Consider retained **tampon**


* Extremities
	* Tenderness
	* Abnormal movement  
	The ability to move a joint through its full range of motion usually indicates that the muscle unit is intact and the joint is stable.
	* Distal pulses  

### Adjuncts to the Secondary Survey

* X-Ray
	* CXR
	* Pelvis
	* Long bones
* CT


---