# Acute Spinal Cord Injury


*Covers management of spinal cord injuries in the first few weeks following injury. Management differs in the patient with a [chronic spinal cord injury](/management/cns/chronic-spine.md).*

Acute spinal cord injury occurs commonly, and is frequently devastating. Management involves identifying and treating:

* **Spinal shock**\
Altered physiological state that:
	* Occurs **immediately** after spinal cord injury
	* May **last days to weeks**
	* Involves a loss of function distal to the injury:
		* Flaccid paralysis
		* Hyporeflexia
		* Anaesthesia
		* Incontinence
* **Neurogenic shock**\
Distributive shock process due to loss of sympathetic tone:
	* May occur within 30 minutes after injury
	* May last up to 6 weeks
	Features include:
		* Hypotension\
		Significant orthostatic hypotension.
		* Bradycardia
		* Hypothermia
* **[Autonomic dysreflexia](/management/cns/autonomic-dysreflexia.md)**\


## Epidemiology and Risk Factors

## Pathophysiology

### Neurogenic shock

Spinal cord injury causing sympathectomy, leading to relative parasympathetic overactivity.

## Clinical Manifestations

> Beware the **rising lesion** - an ↑ in spinal cord injury level occurring with spinal cord oedema, which may precipitate respiratory failure

## Diagnostic Approach and DDx

## Investigations

## Management

> * Avoid secondary injury by preventing hypoxia and hypotension
> * Early fixation does not improve neurology, but it does permit immediate rehabilitation and overall improves outcome

* A
	* May have unstable c-spine or require immobilisation
* B
	* Multiple potential respiratory complications\
	Due to poor respiratory muscle function and immobility.
		* Respiratory failure
		* Atelectasis
		* Bronchospasm\
		If sympathectomy above T6.
		* Pneumonia\
		Mucous plugging.
		* PE
* C
	* Maintain spinal cord perfusion\
		* **MAP 85-90mmHg**
		* Avoid SBP ⩽90mmHg
		* Usually resting SBP 60-80mmHg
	* Neurogenic shock\
	Maintenance of blood pressure crucical to prevent ongoing secondary injury.
		* HR\
		**Bradycardia may require atropine** or pacing; especially with **vagal response to intubation**.
	* [Autonomic dysreflexia](/management/cns/autonomic-dysreflexia.md)
* E
	* Temperature control\
	Vasodilation and excessive heat loss below the injury.
	* **Pressure injury prevention**
* F
	* Electrolyte disorders\
		* Hyponatraemia\
		Common, likely due to RAS dysfunction due to reduced renal sympathetic tone.
	* Urinary retention
* G
	* Delayed gastric emptying
	* Constipation
	* Gastric ulceration

### Airway Management

Principles:

* MILS\
Reduces amount of c-spine movement during airway management. MILS:
	* Involves:
		* Stabilisation of the head by an assistant
		* Assistant holds the mastoid processes and occiput steady\
		May be done from from or back.
	* ↑ the rate of failed airway management
* Use of airway adjuncts\
Use for mask ventilation to reduce:
	* Requirement for c-spine movement
	* Gastric insufflation
* Avoid suxamethonium
* Consider:
	* Videolaryngoscopy\
	At a minimum for all patients with high-thoracic or c-spine injury.
	* FOI\
	Reduces amount of c-spine movement. May be performed awake or asleep.
		* May be difficult due to blood/secretions
		* Awake FOI
			* Coughing and gagging may lead to spine movement\
			May occur either from topicalisation, or if topicalisation inadequate.
			* Requires sedation\
			Limits post-intubation neurological assessment.
		* Asleep FOI
	* Not using cricoid pressure\
	May worsen injury.

### Anaesthetic Considerations

* A
	* Difficult airway due to immobilisation
* C
	* Arterial line\
	Required if high thoracic injury or above.
	* Vasoactive support
		* Consider vasopressor infusion during induction
* E
	**Suxamethonium** is **contraindicated 48-72 hours post-injury**\
	Fatal hyperkalaemia may result due to up-regulation of ACh receptors.
* G
	* Aspiration risk\
	High risk due to gastric dilation and ↓ emptying.

### Marginal and Ineffective Therapies

## Complications

## Prognosis

## Key Studies


---

## References

