# Intracranial Pressure {#sec-icp}

## Indications

## Contraindications

## Anatomy

## Pathophysiology

Normal ICP waveform contains 3 peaks:

* P1\
Percussion wave from arterial pressure transmitted to the choroid plexus.
* P2\
Tidal wave due to brain compliance. P2 > P1 when brain compliance falls.
* P3\
Dicrotic wave from AV closure.


Lundberg waves are pathological waveforms seen rarely:

* Lundberg A waves\
Slow rise in ICP to very high (50-100mmHg) levels, occurring due to a fall in MAP/CPP leading to cerebral vasodilatation and ↑ ICP. Can be terminated by an ↑ in MAP and restoration of CPP.
* Lundberg B waves\
Changes in ICP by 10-20mmHg over shorter (30-180s) time periods, with associated change in respiratory pattern.
* Lundberg C waves\
Low amplitude changes in ICP that occur several times per minute.


## Clinical Manifestations

Clinical features of ↑ ICP include:

* Seizures
* GCS\
⩽12 is relative contraindication to LP without radiographic exclusion of ↑ ICP or hydrocephalus.
* Focal neurological signs
* Papilloedema


## Monitoring

ICP monitoring is indicated:

* For **salvageable patients** with **GCS ⩽8** and **TBI**, after resuscitation with:
	* Abnormal CT scan\
	Swelling, ICH, hydrocephalus, herniation.
	* Normal CT scan but ⩾2 of:
		* Age >40
		* Motor posturing
		* SBP <90mmHg
* Until ICP has stabilised and clinical assessment can be performed


Commonly used systems for measuring ICP include:

* Intraparenchymal transducer
* Intraventricular catheter
* Multimodality monitoring


### Intraparenchymal Transducer

Intraparenchymal transducers:

* Assess regional pressure
* Can be inserted at the bedside via small burr hole\
Ideally done in OR for sterility.
* Include:
	* Fibre-optic\
	Camino.
	* Strain-gauge\
	Codman.
* Accuracy drifts over time


### Intraventricular Catheter

Intraventricular catheters (EVD):

* Provide an assessment of global ICP
* Facilitate drainage and sampling of CSF
* More difficult to place with severe brain oedema and ↓ ventricle size
* Can be regularly re-calibrated\
Remain accurate over time.


### Multimodality Monitoring

A variety of other intracranial monitors see use in specialist centres, although without much evidence supporting them. These include:

* Intraparenchymal oxygen content\
Invasive measurement of cerebral oxygen tension.
	* Normal 20-35mmHg
	* \<10mmHg associated with ↑ morbidity and mortality
	* \<20mmHg suggested as threshold for intervention
* Jugular bulb oxygen saturation\
Invasive measurement of cerebral venous oxygen saturation.
	* Normal 55-70%
	* Low levels suggested oxygen supply-demand mismatch
	* Elevated levels suggest hyperaemia or brain death
* Cerebral Microdialysis\
Invasive measurement of cerebral interstitial metabolic milieu via microdialysis probes.
	* Measurement of:
		* Lactate
		* Pyruvate
		* Glucose
		* Glutamate
		* Glycerol
	* Lactate and pyruvate used as markers of ischaemia
* Transcranial Doppler\
Noninvasive measurement of cerebral blood flow.
* NIRS\
Non-invasive measurement of cerebral oxygen saturation. Not validated in neurological intensive care.


## Management {#sec-icp_mx}

Broadly divided into **three tiers**:

:::column-margin
Although evidence exists for these therapies in isolation, there is little evidence demonstrating effect of any combination or process. However, they are commonly arranged into tiers based on invasiveness and side-effect profile to provide a framework treatment and escalation.
:::

* **Tier 1**\
	* **Sedation** and **analgesia** to ↓ ICP
		* Benzodiazepine
		* Opioid
	* Maintain **CPP 60-70mmHg**
		* Fluid boluses, avoiding hypervolaemia
		* Vasopressors
	* Low-normal **CO~2~**\
	Tight control aiming PaCO~2~ of 35-38mmHg.
	* **Osmotherapy** ↓ cerebral oedema:
		* Mannitol 0.25-1g/kg
			* Creates an osmolar gap
			* Enters brain via damaged BBB, which may result in local ↑ ICP
		* Hypertonic saline\
		3mmol ↑ in osmolality ↓ cerebral volume by **~7%**.
			* 5-10mL 23.4%
	* **Drain CSF**
		* Consider EVD if only parenchymal probe is placed
		* Set at **10mmHg** with EVD
		* Should be vented continuously, not intermittently
	* Consider seizure prophylaxis

:::column-margin
There is no evidence supporting mannitol or hypertonic saline over the other, however I prefer hypertonic saline due to:

* Repeatability
* Preservation of osmolar gap
:::

* **Tier 2**:
	* **Neuromuscular blockade**\
	Trial paralysis - if effective, produce with continuous infusion.
		* **Remove** hard cervical spine **collar**\
		If present.
	* Mild ↓ **CO~2~**\
	Tight control aiming PaCO~2~ of 32-35mmHg. Caution should be used if brain tissue oxygenation mointoring is not available.
	* Consider MAP challenge

:::column-margin
At each stage, reconsider the:

* Need for surgical intervention for potentially correctable lesions
* Effect of extracranial causes for ↑ ICP
:::

* **Tier 3**:
	* **Thiopentone** coma\
		* Profound ↓ CMRO~2~
		* Long half-life\
		Delays further neuro-prognostication.
		* EEG monitoring recommended to avoid titrating past burst suppression
	* **Secondary decompressive craniectomy**
	* Aggressive **hyperventilation**
		* Hyperventilation to hypocarbia does ↓ CO~2~ and ↓ ICP, but leads to cerebral vasoconstriction and ↓ CBF
		* Has a role for short term control of ↑ ICP prior to some definitive therapy, or in response to tonsilar herniation\
		e.g. the patient who blows a pupil during transfer to the OR.
		* Should be **avoided** during **first 24 hours** of a TBI, as CBF is critically ↓ over this period


### MAP Challenge

**Principles**:

* Tests whether patients intrinsic CPP requirement is higher than the standard 60-70mmHg
* Success requires both:
	* Intact cerebral static pressure autoregulation
	* Current CPP < lower breakpoint of static pressure autoregulation
* Cerebral autoregulation may not be stable and so regular revaluation is required

**Practice**:

* Pharmacologically **↑ MAP** by **10mmHg for** up to 20 minutes
* Observe the change in:
	* MAP
	* ICP
	* CPP
	* P~bt~O~2~
* A **successful** MAP **challenge**:
	* Results in a **↓ ICP for an ↑ CPP** and MAP
	* Occurs because intact autoregulation causes vasoconstriction in response to ↑ CPP, and therefore ↓ cerebral blood volume
* An unsuccessful MAP challenge:
	* Results in ↑ ICP as cerebral blood volume ↑ in absence of functioning autoregulation
* Adjust blood pressure targets accordingly


## Complications


## Key Trials

* DECRA
* RESCUE ICP

---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.
3. Hawryluk GWJ, Rubiano AM, Totten AM, et al. [Guidelines for the Management of Severe Traumatic Brain Injury: 2020 Update of the Decompressive Craniectomy Recommendations](www.doi.org/10.1093/neuros/nyaa278). Neurosurgery. 2020;87(3):427-434.
4. Carney N, Totten AM, OʼReilly C, et al. [Guidelines for the Management of Severe Traumatic Brain Injury, Fourth Edition: Neurosurgery](www.doi.org/10.1227/NEU.0000000000001432). Published online September 2016:1.
5. Hawryluk GWJ, Aguilera S, Buki A, et al. [A management algorithm for patients with intracranial pressure monitoring: the Seattle International Severe Traumatic Brain Injury Consensus Conference (SIBICC)](https://link.springer.com/article/10.1007/s00134-019-05900-x). Intensive Care Med. 2019;45(12):1783-1794. doi:10.1007/s00134-019-05805-9
