# Acute Respiratory Distress Syndrome {#sec-ards}

Bilateral diffuse inflammatory lung injury characterised by loss of aerated lung tissue and reduced pulmonary compliance. Various diagnostic criteria exist; the **Berlin Criteria** requires all of:

* **Acute onset**\
Within **7 days** of known precipitant.
* **Bilateral** radiographic **opacities**\
Consistent with pulmonary oedema.
* **Non-hydrostatic**\
Not related to an ↑ PCWP, i.e. not due to LV failure.
* **Hypoxia**\
ARDS is graded by severity of hypoxia into:
    * Mild\
    PaO~2~/FiO~2~: 200-300.
    * Moderate\
    PaO~2~/FiO~2~: 100-200.
    * Severe\
    PaO~2~/FiO~2~: <100. 

:::column-margin
: Precipitants of ARDS

| Direct              | Indirect           |
| ------------------- | ------------------ |
| Pneumonia           | Sepsis             |
| Aspiration          | Trauma             |
| Contusion           | Massive transfusion|
| Fat embolism        | Pancreatitis       |
| Drowning            | CPB                |
| Inhalational injury |                    |
| Reperfusion injury  |                    |
:::

## Epidemiology and Risk Factors

Significant regional variation, in part due to different definitions. In general, ARDS:

* Represents ~10% of ICU admissions
    * ~25% of those requiring mechanical ventilation
* Cases are reasonably spread across all severities:
    * ~30% are mild
    * ~45% are moderate
    * ~25% are severe

## Pathophysiology

Acute phase consists of a combination of:

* Alveolar-capillary barrier damage\
Bidirectional leakage of fluid and protein:
    * Plasma protein into alveolus\
    Causing pulmonary oedema.
    * Alveolar protein into plasma\
    Surfactant and other alveolar proteins.
* Inflammatory infiltrate\
Large ↑ in:
    * Alveolar macrophages\
    Usually dominant cell in health.
    * Alveolar neutrophils\
    Rare in health (~1% of cells), become superabundant (~90%) in ARDS.
* Surfactant dysfunction\
Epithelial cell damage alters cellular production of inflammatory mediators and ↑ water egress into the alveolus, as well as production of dysfunctional surfactant.


The late (>5 days) phase is characterised by fibrosing alveolitis

## Clinical Manifestations

## Diagnostic Approach and DDx

## Investigations

## Management

:::info
Principles of management are:

* Early identification and treatment of cause
* Avoidance of further lung injury
:::

**Specific therapy**:

* Pharmacological
    * **Dexamethasone**
        * 10mg IV OD
        * Evidence only supportive for infective (pneumonia, sepsis) causes of ARDS
        * Pure glucocorticoid preferable to mineralocorticoid\
        Avoids sodium and water retention.
* Physical
    * **Proning**

:::column-margin
Proning is a cornerstone of ARDS management, and is covered in detail under @sec-proning.
:::

**Supportive care**:

* B
    * **Lung protective ventilation**\
        * Appropriate PEEP\
        Often titrated to a PEEP-FiO~2~ table. Considerations:
            * The disease and degree of recruitable lung is highly heterogenous and often over-distension and under-recruitment will occur together
            * Higher PEEP is associated with better outcomes in more severe disease, and worse outcomes in milder disease
            * Inadequate PEEP tends to cause under-recruitment and hypoxia
            * Excessive PEEP tends to cause over-distension, ↑ lung stress, and reduced cardiac output
            * Ideal PEEP is described by the Open Lung Approach\
            PEEP at which the lung volume is maintained at FRC, thereby:
                * Maximally recruiting available alveoli
                * Spreading Vt over a greater number of alveoli
                * Reducing Pip
                * Deceasing Barotrauma and volutrauma
        * Appropriate FiO~2~\
        High FiO~2~ is associated with diffuse alveolar damage. FiO~2~ should be titrated (in combination with PEEP adjustment):
            * Down to <0.6 (as able)
            * Aiming SpO~2~ >90%
        * Permissive hypercapnoea\
        * Avoid:
            * Volutrauma\
            Aim Vt 4-6mL/kg predicted body weight.
            * Barotrauma\
            Aim Pplat <30cmH~2~O.
                * The plateau pressure is a substitute for the transpulmonary pressure, which reflects the actual elastic distending pressure of the lung
                    * Measurement of the transpulmonary pressure can be performed with an oesophageal balloon, which allows the chest wall and lung elastance to be separated (rather than measuring the elastance of the respiratory system as a whole)
                * This may be still be excessive (or inadequate) in patients at extremes of chest wall elastance
    * **Neuromuscular blockade**
        * No evidence of benefit for routine use
        * Appropriate for:
            * Ventilator dyssynchrony despite deep sedation
            * Very poor lung compliance preventing lung protective ventilation
        * Advantages
            * ↓ PTHx rate
            * Predicate of proning
        * Disadvantages
            * Requires deep sedation
            * ↑ Haemodynamic instability
    * **iNO**\
    Appropriate to trial for hypoxaemia refractory to tranditional ventilation, for:
        * Short periods
        * As a bridge to proning or ECMO
    * **VV ECMO**
* E
    * Early mobilisation 
* G
    * Stress ulcer prophylaxis
    * Feeding
* H
    * DVT prophylaxis
 

:::column-margin
One reasonable approach to PEEP-setting is identifying the level where DO~2~ (i.e., the product of arterial oxygen content and cardiac output) is maximal. Determining this point at the bedside is, of course, difficult.
:::

**Disposition**:

### Marginal and Ineffective Therapies

* High-Frequency Oscillatory Ventilation\
↑ Mortality compared to lung protective ventilation strategies.
* Recruitment Manoeuvres\
In theory, recruitment manoeuvres improve oxygenation by ↑ number of ventilated alveoli. In practice, following a recruitment manoeuvre:
    * Over-inflation of previously normal lung occurs\
    May be harmful.
    * Oxygenation may improve\
    Predominantly early ARDS with a lower baseline PEEP.
    * Haemodynamic instability may occur due to large changes in VR

:::column-margin
Recruitment manoeuvres are covered in more detail under @sec-recruit.
:::

## Anaesthetic Considerations

## Complications

## Prognosis

* Death\
Improving with better preventative care and ↓ VILI. Mortality varies on:
    * Severity:
        * ~35% mild
        * ~40% moderate
        * ~45% severe
    * Cause and comorbidities:
        * ↓ In trauma
        * ↑ In elderly, chronic or acute organ failures, and sepsis
* Chronic lung disease\
Pulmonary function tests normalise in 6-12 months.
* Persistent critical illness\
↑ In survivors of ARDS compared to non-ARDS ICU patients.
    * Functional impairment persists in young survivors of severe disease


## Key Studies

**Lung Protective Ventilation**:

{{< include /trials/arma.qmd >}}


**Open Lung Approach**:

* Combination of high PEEP and recruitment manoeuvres to prevent alveolar collapse, and thereby:
    * ↓ VILI
    * ↓ Atelectotrauma
    * ↑ Oxygenation
* (Appropriately) high PEEP is generally well established as safe and effective, the role of recruitment manoeuvres is unclear 
{{< include /trials/art.qmd >}}


**Muscle Relaxation**:

* Lung protective ventilation aims to ↓ VILI by ↓ barotrauma and Pip
* NMBA bypass any ventilator dyssynchrony and may improve chest wall compliance
{{< include /trials/acurasys.qmd >}}
{{< include /trials/rose.qmd >}}


**Other**:

{{< include /trials/proseva.qmd >}}
{{< include /trials/dexa_ards.qmd >}}


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.
1. Villar J, Ferrando C, Martínez D, et al. [Dexamethasone treatment for the acute respiratory distress syndrome: a multicentre, randomised controlled trial](https://www.sciencedirect.com/science/article/abs/pii/S2213260019304175). The Lancet Respiratory Medicine. 2020;8(3):267-276. doi:10.1016/S2213-2600(19)30417-5
1. [Early Neuromuscular Blockade in the Acute Respiratory Distress Syndrome](https://www.nejm.org/doi/full/10.1056/NEJMoa1901686). New England Journal of Medicine. 2019;380(21):1997-2008. doi:10.1056/NEJMoa1901686
1. Writing Group for the Alveolar Recruitment for Acute Respiratory Distress Syndrome Trial (ART) Investigators. [Effect of Lung Recruitment and Titrated Positive End-Expiratory Pressure (PEEP) vs Low PEEP on Mortality in Patients With Acute Respiratory Distress Syndrome: A Randomized Clinical Trial](https://jamanetwork.com/journals/jama/fullarticle/2654894). JAMA. 2017;318(14):1335-1345. doi:10.1001/jama.2017.14171
1. Papazian L, Forel JM, Gacouin A, et al. [Neuromuscular Blockers in Early Acute Respiratory Distress Syndrome](http://www.nejm.org/doi/full/10.1056/NEJMoa1005372). New England Journal of Medicine. 2010;363(12):1107-1116. doi:10.1056/NEJMoa1005372
1. Guérin C, Reignier J, Richard JC, et al. [Prone Positioning in Severe Acute Respiratory Distress Syndrome](http://www.nejm.org/doi/10.1056/NEJMoa1214103). N Engl J Med. 2013;368(23):2159-2168. doi:10.1056/NEJMoa1214103
