# Bronchospasm

:::danger
This is an **anaesthetic crisis**. Priority is to:

* **Maintain oxygenation**
* **Keep Pip < 50cmH~2~O**
:::

## Emergency Management

Immediately:

* Cease surgical stimulation
* Provide 100% oxygen
* **Manually ventilate**  
Assess lung resistance and compliance.
* Rapidly deepen anaesthesia  
	* Change from desflurane if able
* Consider:
	* <span style="color:red">**Is this anaphylaxis**?</span>  
	Cause of ~20% of bronchospasm.
	* If intubated:  
	Exclude endobronchial or oesophageal intubation.
	* If not intubated:
		* Exclude laryngospasm or airway obstruction
		* Exclude regurgitation or aspiration


* **Bronchodilate**
	* Inhaled therapies  
	Typically adequate in mild bronchospasm.
		* Salbutamol  
		12 puffs MDI via circuit.
		* Ipratropium Bromide  
		6 puffs MDI via circuit.
	* IV therapies  
	Required in severe bronchospasm.
		* Salbutamol  
		5ug/kg up to 250ug slow push, with a 100ug/kg/**hr** infusion.
		* Adrenaline
		0.1-1ug/kg bolus, with a 0.1ug/kg/min infusion.
* **Optimise ventilation**
	* I:E ratio of at least 1:6
	* Low RR  
	Target complete expiration on expiratory flow waveform, accepting hypercapnoea.
	* Consider ventilator disconnection if concern for stacked breaths
* Consider additional drugs
	* Hydrocortisone  
	1-2mg/kg IV.
	* Ketamine  
	0.5-1mg/kg IV.
	* Magnesium
	* Aminophyline  
	5-7mg/kg over 15 minutes, then 0.5mg/kg/hr thereafter.


## Epidemiology and Risk Factors

Epidemiology:

* Majority of bronchospasm occurs during induction or maintenance  
Bronchospasm due to anaphylaxis predominantly occurs during maintenance.

Risk factors:

* Asthma/COAD
* Reflux
* Heavy smokers
* Recent URTI
* Prior laryngospasm

## Pathophysiology

## Clinical Manifestations

Typically presents as a triad of:

* Expiratory wheeze
* Prolonged expiration time  
"Obstructed" capnographic waveform.
* High Pip  
First sign in 30% of cases.


Clinical features:

* Desaturation/cyanosis  
First sign in 20% of cases.
* Hypercapnoea
* Poor lung compliance
	* Fall in tidal volumes
	* Difficulty hand ventilating
* Wheeze  
May not be present in severe spasm when gas flow is impaired, but is the first sign in 30% of cases.





### History

### Examination

## Diagnostic Approach and DDx

Key differential diagnoses:

* **Anaphylaxis**
* Laryngospasm
* Endobronchial intubation  
Also causes high airway pressures/reduced volumes and reduced SpO2~.
* Poor chest wall compliance
	* Eschar
	* 'Wooden Chest' phenomenon
* Poor lung compliance
	* PTHx


## Investigations

## Management

### Ineffective Therapies

## Complications

## Prognosis


---

## References


1. Westhorpe RN, Ludbrook GL, Helps SC. [Crisis management during anaesthesia: bronchospasm](http://qualitysafety.bmj.com/content/14/3/e7). Qual Saf Health Care. 2005;14(3):e7. doi:10.1136/qshc.2002.004457