# Haemothorax


## Epidemiology and Risk Factors

## Pathophysiology

### Aetiology

## Clinical Manifestations

## Diagnostic Approach and DDx

## Investigations

**Bedside**:

**Laboratory**:

**Imaging**:

**Other**:

## Management

**Resuscitation**:\

ABC approach. Comment on team coordination and clinical priorities.
**Specific therapy**:

* Pharmacological
* Procedural
* Physical

**Supportive care**:

**Disposition**:

**Preventative**:


### Marginal and Ineffective Therapies

## Anaesthetic Considerations

## Complications

* B
	* Retained haemothorax\
	Undrained blood clots, becomes organised and fibrosed causing progressive pleural thickening.
		* May lead to subsequent:	
			* ↓ Lung volume
			* ↓ Pulmonary compliance
			* Empyema
		* May require either:
			* Radiological drainage of loculated collections
			* Surgical washout\
			Open or VATS.

## Prognosis

## Key Studies


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.