# Tourniquets


Intraoperative tourniquets:

* Are used in extremity surgery to improve operating conditions  
Provide a (mostly) bloodless surgical field (bleeding may still occur from intramedullary vessels).
* May be contraindicated in peripheral vascular disease
* Should be inflated above the **limb occlusion pressure**
	* Determined by inflating the tourniquet and monitoring arterial flow with doppler  
	Typically higher than SBP as tourniquet pressure is not transmitted evenly to deeper structures.
	* A safety margin of 40-80mmHg should then be added
* Should generally not be used for longer than 1.5-2 hours in a healthy adult  
ATP stores are exhausted after this point.
	* Tourniquet can be released for 10-15 minutes to allow ischaemic washout and reoxygenation prior to re-exsanguination and re-inflation


## Local Effects of Tourniquets

Include:

* Muscle
	* Ischaemia  
	Necrosis may occur after 2 hours
	* Post-tourniquet syndrome  
	Swollen, pale, stiff, and weak limb for 1-6 hours after tourniquet application.
		* May lead to compartment syndrome
* Nerve  
	* Temporary neuropathy  
	Conduction block develops after 15-45 minutes.
	* Permanent neuropathy  
	Exceedingly rare. Most neurological complications resolve within 6 months.
		* Pressure used is more significant than tourniquet time
* Vascular injury  
Permanent vascular injury is rare but catastrophic, and probably involves tourniquet pressure rupturing atheromatous plaque.


## Systemic Effects of Tourniquets

Include:

* CVS
	* ↑ effective circulating volume following limb drainage and tourniquet inflation  
	Bilateral thigh tourniquets may ↑ effective volume by 15%.
		* May lead to cardiac failure
	* Hypertension  
	Gradual ↑ in BP seen with tourniquet use.
		* Probably due to tourniquet pain
* Pain  
Tourniquet inflation leads to a dull aching pain. This pain:
	* May occur despite apparently adequate neuraxial anaesthesia  
	As the neuraxial block wears off, C-fibres will conduct dull pain though the patient remains insensate to sharp pain (due to ongoing A-fibre blockade).
	* Responds to 0.1-0.25mg/kg IV ketamine  
	Beware treating as it will resolve with tourniquet deflation.
* Extremity
	* Temperature  
	↑ core temperature due to reduced heat loss from ischaemic limb, typically 0.5°C after 2 hours.


## Effects of Tourniquet Deflation

Include:

* CVS
	* CVS instability  
	Seen on tourniquet deflation, due to reactive hyperaemia and wash-out of anaerobic metabolites.
* Respiratory
	* ↑ PaCO~2~  
	Occurs on tourniquet deflation, may result in hyperventilation or hypercarbia (with subsequent changes to CNS blood flow).
* Extremity  
↓ core temperature on tourniquet deflation due to heat redistribution.
* Fluid and Electrolyte
	* Hyperlactataemia  
	On tourniquet deflation.
	* Hyperkalaemia  
	On tourniquet deflation.
* Haematological
	* ↑ fibrinolysis


## Reducing Tourniquet Risk

Key interventions to reduce iatrogenic harm include:

* Minimising pressure
* Minimising time  
Ensure alarms set.
* Padding under tourniquet
* Use a wider tourniquet  
Reduce pressure at any given point.
* 5-10 minute break for limb re-perfusion every 2 hours

---

## References


1. Deloughry JL, Griffiths R. [Arterial tourniquets](https://academic.oup.com/bjaed/article/9/2/56/299450). Continuing Education in Anaesthesia Critical Care & Pain, Volume 9, Issue 2, 1 April 2009, Pages 56–60.