# Epidural Troubleshooting

*This covers management of the working and non-working epidurals. [Insertion of an epidural](/anaesthesia/regional/epidural.md) and the particulars of the [labour epidural](/anaesthesia/obs/labour-analgesia.md) are covered elsewhere.*

## Management of a Working Epidural

Maintenance of analgesia can be performed via:

* Intermittent boluses alone  
Essentially a historical relic.
* Continuous infusion with intermittent boluses
* Patient Controlled Epidural Analgesia (PCEA)

In general, maximal anaesthetic doses should be:

* Ropivacaine 3-4mg.kg^-1^.6 hours^-1^
* Bupivacaine 2-3mg.kg^-1^.6 hours^-1^
* Reducedin:
    * Hepatic failure
    * Renal failure
    * Severe hypoalbuminaemia


### Continuous Infusion

* Typically lower concentrations used to minimise motor block
    * Ropivacaine 0.2%
    * Bupivacaine 0.0625-0.125%
* Generally run at 6-10ml/hr
* May have 5ml boluses Q20min
* Adjuvants include:
    * Opioid  
    Classically fentanyl.
    * Adrenaline

### Patient Controlled Epidural Analgesia

* May be run with a background infusion
* Reduced need for intervention
* e.g. Ropivacaine 0.2% with 2μg/ml fentanyl:
    * 5ml patient demand bolus, Q15 minute lockout

### Catheter Removal

Removal of an epidural can occur when:

* Coagulation status is normal  
Covered under [coagulopathy](/anaesthesia/regional/principles/principles-neuraxial.md#coag).
* No longer therapeutically indicated
* Risk of infection is too high to justify ongoing use
Typically epidurals may stay up to **5 days** following insertion, though local procedure may vary.
    * This needs to be balanced against the requirement for ongoing analgesia

Removing the catheter:

* Remove dressing
* Apply gentle pressure to remove the catheter
* Tip of catheter should be visible
* If **catheter does not come out easily**  
Place the patient in the same position they were in for insertion, and pull gently.


## Troubleshooting an Epidural{#comp}

Common issues include:

* High Block
* Inadequate analgesia
    * Patchy block
    * Asymmetric block
    * Diminished block
* Inadequate perineal analgesia


### High Block

Symptoms include:

* Nasal stuffiness
* Difficulty breathing
* Lightheadedness
* Horner's Syndrome  
    * May occur following blockade of sympathetic ganglion of T1-4
    * Occur commonly with epidural top-up for LUSCS  
    Of itself, not of clinical significance.


Treatment is based upon symptoms:

* Hypotension  
Vasopressor, such as metaraminol.
* Bradycardia  
Atropine.
* Hypoxia  
Supplemental oxygen, respiratory support. 


### Inadequate Analgesia

Can be defined as:

* Pain > 5
* Inability to cough or move effectively

May be associated with:

* Patchy block
* Asymmetric block
* Diminishing analgesia


Management process:

* Assess vitals
* Exclude surgical cause of pain
* Check pump on and working correctly
* Check catheter is connected
* Check catheter location  
Catheter may migrate out of the epidural space.
    * Check anticoagulation status prior to manipulation
* Check BP  
Hypotension and uncorrected hypovolaemia are relative contraindications to epidural bolus.
* Assess block
    * Patchy
    * Asymmetric
    * Dimishing analgesia


#### Patchy Block

* Immediately patchy blocks may be misplaced; **consider replacing**  
e.g. subdural, paravertebral, threaded over nerve root.
* Bolus with a moderately concentrated solution  
e.g. 0.125-0.25% bupivacaine.

#### Asymmetric/Unilateral Block

Generally indicates catheter is too far within the space:

* Withdraw catheter by 1cm and bolus  
Place in lateral position (un-blocked side down) to improve onset of block
* Catheter can be pulled back up to 3cm within the space


#### Diminishing Analgesia

A rescue bolus of LA can be delivered to re-establish a failing epidural.
* Ensure adequate monitoring
* Ensure working IV access
* Ensure vasopressor is readily available
* Give a rescue bolus  
The end point is either analgesia or side effects.
    * Appropriate agents include:
        * 0.25% bupivacaine  
        6-10ml is appropriate for most adult patients, though more will sometimes be required.
        * Ropivacaine 0.35%
        * Ropivacaine 0.2%
    * If analgesia is achieved:
        * ↑ rate by one-third
        * Change solution
    * If no block to ice is present:
        * Consider alternate methods of analgesia



### Inadequate Perineal Analgesia

Perineal analgesia is important at time of delivery. Block can be augmented with:

* LA bolus  
    * 6-8ml of 0.125% bupivacaine
    * 3-4ml of 0.25% bupivacaine
* Fentanyl  
50-100μg augments analgesia without providing motor block.
* Position in semi-Fowler's  
Enhances perineal analgesia from epidural.


**Dosing** for **forceps delivery** or **episiotomy**:

* Requires dense blockade with concentrated LA
* Consider:
    * 1-2% lignocaine
    * 0.25-0.5% bupivacaine


## Neurological Injury

Can be divided into:

* Anaesthesia/epidural related
* Obstetric/surgery related

### Anaesthesia Related

Anaethetic-related neurology includes:

* Prolonged neural blockade
    * May last 10-48 hours  
    * Ultimately resolves
* Bladder dysfunction  
Associated with:
    * Urinary retention due to epidural anaesthesia  
    Can be avoided with IDC.
* Direct trauma/neuritis
    * May occur from intraneural injection of LA
    * Leads to paraesthesia/sensory/motor loss in a specific dermatomal distribution.
* **Epidural haematoma**
    * Rare  
    ↑ risk with coagulopathy.
* **Epidural abscess/meningitis**  
Key features:
    * Severe back pain
    * Local tenderness
    * Fever
    * Leukocytosis
* Adhesive arachnoiditis
* Anterior spinal artery syndrome


### Obstetric/Surgery Related

Obstetric neurology:

* Occurs in 1:2400-6500
* Associated with:
    * Prolonged labour
    * Forceps delivery
* Typically causes neurology in a **peripheral nerve distribution**





---

## References

1. Don't Panic! The Registrars Guide to the Epidural. Miles L, Christelis N.
