# Fascia Iliaca Block

Blockade is:

* Low-tech alternative to femoral nerve block  
Relies on high-volume to spread underneath fascia and provide blockade to:
	* Femoral nerve  
	Blocked in all instances.
	* Lateral cutaneous nerve of the thigh (lateral femoral cutaneous nerve)  
	In most (80-100%) of instances.
	* Obturator nerve is not reliably blocked
* Delivers analgesia but not anaesthesia
* Requires large volume and dose of LA
* Does not reliably block obturator nerve


## Indications

*Analgesia* for:

* Thigh surgery
* Knee arthroscopy
* Fractured neck of femur


## Contraindications

* General contraindications:
	* Patient refusal
	* LA allergy
	* Local infection
* Specific contraindications
	* **Previous femoral bypass**


## Anatomy

{{< include /includes/ll-neuro.qmd >}}


## Equipment

* Standard nerve block tray
* High-frequency linear probe
* 5-10cm **blunted**, short-beveled, or Tuohy needle  
Blunted needles improve tactile feeling of block.
* 40ml local anaesthetic


## Technique

Can be either:

* Landmark  
Easy and reliable, but high volume of LA required.
* Ultrasound  
Greater equipment requirement but associated with lower risk of complications.


### Landmark

* Position patient supine
* Identify landmarks:
	* ASIS
	* Pubic tubercle
* Divide distance between ASIS and tubercle into **thirds**
* Mark a point **1cm caudal** from the junction of the **lateral and middle third**  
Confirm that this point is ~1-2cm lateral to the femoral pulse.
* Standard prep, drape, skin anaesthesia, etc
* Perform block:
	* Insert needle perpendicularly
	* Angle slightly cranio-medially to avoid vessels
	* Advance needle slowly, feeling for two pops
		* Distinct pop through fascia lata
		* Subtle pop through fascia iliaca
	* Flaten needle and insert a further 1-2mm
	* Aspirate and inject in 5ml aliquots  
		* No resistance to injection should be appreciated  
		Resistance suggests needle is within iliacus - withdraw until injection is easy.


### Ultrasound

* Position patient supine
* Identify femoral vessels
* Follow fascia iliaca laterally to the ASIS  
Identifed as the thick fascial plane superficial to the femoral nerve and femoral vessels.
* Perform block  
	* Insert needle IP from the lateral side
	* Aim to place needle tip under the fascia iliaca at the junction of the middle and lateral thirds of the line between the ASIS and pubic tubercle  
	As per landmark technique. Pops are usually perceived.
	* Aspirate and inject 1-2ml of LA to confirm location with hydrodissection of fascia
	* Inject remainder of LA in 5ml aliquots (aspirating between)
	* Aim is to identify spread both:
		* Laterally towards iliac crest
		* Medially towards femoral nerve


## Complications

* General complications
	* Intravascular injection
	* LAST
	* Nerve injury
	* Infection
	* Failure
	* Allergy to LA


---

## References

1. Range C, Egeler C. [Fascia Iliaca Compartment Block: Landmark and Ultrasound Approach](http://www.frca.co.uk/Documents/193%20Fascia%20Iliaca%20compartment%20block.pdf). WFOSOA. 2010.
2. Chuan A, Scott DM. Regional Anaesthesia: A Pocket Guide. 1st Ed. Oxford University Press.
2. NYSORA. [Ultrasound Guided Fascia Iliaca Block](https://www.nysora.com/ultrasound-guided-fascia-iliaca-block). Accessed September 2018.
