# Femoral Nerve Block

Blockade provides anaesthesia to:

* Anterior and medial thigh
* Knee
* Variable strip on the medial leg and foot

## Indications

Surgery on:

* Anterior thigh
* Knee
* Femur


## Contraindications

* General contraindications:
	* Patient refusal
	* LA allergy
	* Local infection
* Specific contraindications
	* **Previous femoral bypass**

## Anatomy

{% include "/stubs/ll-neuro.md" %}

## Equipment

* Standard nerve block tray
* High-frequency linear probe
* 5-10cm 22G short-bevel needle
* 20ml local anaesthetic

## Technique

* Position patient supine
* Identify the inguinal ligament and the femoral artery by palpation or ultrasound
* Standard prep, drape, skin anaesthesia, etc
* Place probe in the transverse plane close to the femoral crease, over the femoral artery
* Identify femoral artery and common femoral vein
* Identify femoral nerve lateral to the femoral artery  
Features include:
	* Hyperechoic triangular or oval in shape
	* Lies in a sulcus in the iliopsoas muscle
	* Typically 2-4cm deep
	* More visible during dynamic cranial/caudal tilting
	* Best visualised prior to bifurcation of CFA
* Perform block:
	* Pass needle IP, lateral to medial, through the iliopectineal fascia
	* Aim to place needle adjacent to lateral aspect of the nerve  
	May be below fascia iliac, or between its two layers.
	* Inject 1-20ml of LA around nerve, ensuring it remains contained underneath the fascia  
	Proper location should result in:
		* Nerve being elevated off iliopsoas
		* LA spreading into the wedge-shaped space lateral to the femoral artery

## Complications

* General complications
	* Intravascular injection
	* LAST
	* Nerve injury
	* Infection
	* Failure
	* Allergy to LA

---

## References

1. Chuan A, Scott DM. Regional Anaesthesia: A Pocket Guide. 1st Ed. Oxford University Press.
2. NYSORA. [Ultrasound Guided Femoral Nerve Block](https://www.nysora.com/ultrasound-guided-femoral-nerve-block). Accessed September 2018.
3. Range C, Egeler C. [Fascia Iliaca Compartment Block: Landmark and Ultrasound Approach](http://www.frca.co.uk/Documents/193%20Fascia%20Iliaca%20compartment%20block.pdf). WFOSOA. 2010.
