# Interscalene


## Indications

Analgesia and anaesthesia for:

* Shoulder surgery  
	* Particularly open surgery  
	Arthroplasty, arthroscopy, rotator cuff repair, subacromial decompression.
	* Mobilisation  
	Frozen shoulder.
* Proximal humerus surgery
* Sympathicolysis

## Contraindications

Absolute:

* **Contralateral** recurrent laryngeal or phrenic nerve injury  
Risk of bilateral phrenic nerve palsy.
* **Contralateral** pneumonectomy/pneumothorax


Relative:

* Reduced respiratory reserve

## Anatomy

{% include "/stubs/ul-neuro.md" %}

## Equipment

* 22G 4cm needle
* Local anaesthetic:  
10-20ml of:
	* 1% lignocaine
	* 0.5% bupivacaine
	* 0.75% ropivacaine  
	0.2-0.5% ropivacaine at the C5-C6 level.
	* 1% lignocaine with 0.5% ropivacaine  
	i.e. 1:1 of 2% lignocaine with 1% ropivacaine.

## Technique

* Position:  
May be either:
	* Supine, head up and rotated away with, ipsilateral arm on patient's lap
	* Lateral
* Place ultrasound probe lateral to larynx  
Identify thyroid, carotid, and IJV.
* Translate laterally and slightly caudally to identify:
	* Lateral border of SCM
	* Scalenus anterior  
	Under SCM and lateral to the carotid artery.
	* Scalenus medius
	* Interscalene plexus  
	Appears as three nerves ('traffic light') between the anterior and middle scalene muscles.
* Occasionally a scalenus intermedius muscle/fascial layer divides the plexus into a superficial and deep plexus.
* Insert needle IP:
	* From posterolateral to anteromedial  
	* Through middle scalene
	* Aiming deep to the plexus  
	This position minimises the risk of nerve injury.


* Nerve stimulation  
May be used to identify improper positioning:
	* Contraction of levator scapulae indicates too posterior
	* Contraction of diaphragm (via phrenic nerve) indicates too anterior

## Complications

Specific complications include:

* Blockage of additional nerves, leading to:
	* Horner's syndrome
	* Facial numbness
	* Vocal cord paralysis  
	Due to recurrent laryngeal nerve blockade.
* Vertebral artery injection  
May lead to seizure.
* Subarachnoid/epidural injection
* Pneumothorax


---

## References

