# Principles of Neuraxial Anaesthesia

*This section discusses factors common to spinal and epidural anaesthesia.*

## Indications

* Analgesia
* Anaesthesia

## Contraindications

Absolute contraindications:

* Patient refusal
* Anaphylaxis to local anaesthetics\
True allergy is rare.
* Anticoagulants\
Covered in detail in [principles of neuraxial anaesthesia](/anaesthesia/regional/principles/principles-neuraxial.md).
* Localised infection at insertion site
* Sepsis
    * Risk of infected blood/haematoma in the epidural or subarachnoid space
    * Exaggerated hypotension due to pre-existing vasodilation
    * Coagulopathy

Relative contraindications:

* Immunocompromise
* Coagulopathy
    * Epidural should be withheld in patients with pre-existing coagulopathy where intraoperative heparin administration is planned.
* Raised ICP
* Leukocytosis\
WCC > 20 x 10^9^/L.
* Infection
    * Chorioamnionitis
    * Usually safe to insert if temperature is < 38°C and patient is on antibiotics.
* CVS disease:
	* AS\
	Afterload reduction results in ↓ LV perfusion pressure.
	* Pulmonary hypertension\
	Afterload reduction results in ↓ RV perfusion pressure.
	* Hypotension/hypovolaemia/shock states\
	Exacerbated by drop in SVR.
* Anxiety/behavioural concern
* Lack of expertise in the technique and management of potential complications

### Coagulopathy{#coag}

In general:

* Coagulation studies should be performed prior to insertion if there is any concern\
Any abnormality of coagulation is always a *relative* contraindication.
* Risk of haematoma exists on a continuum - a platelet count of 79 is not substantially more risky than a platelet count of 81\
**Decision needs to be based upon a risk-benefit analysis for this particular patient.**
* Risk varies depending on technique\
Paravertebral is less risky than a spinal, which is less risky than a single-shot epidural, which is less risky than an epidural catheter.
* Absolute thresholds will vary depending on the centre; one particular set of numbers is:
    * Normal APTT
    * INR < 1.5
    * Platelets > 80 x 10^12^/L\
    Institutional policy may vary.
        * Above 100 is ideal
        * < 70 can be considered an absolute contraindication
        * Beware patients whose platlet counts are falling
* Strong history of bleeding\
Even in presence of normal coagulation studies.

### Anticoagulants


|Drug|Time between last dose and epidural insertion/adjustment/removal|Time before next dose|
|--|--|--|
|**Heparin** <br>5,000 Units S/C|6 hours.|2 hours.|
|**Heparin** Infusion|6 hours since cessation, and a normal APTT|2 hours|
|**Enoxaparin** (prophylactic)|12 hours, 24 hours post-operative|4 hours|
|**Enoxaparin** (therapeutic)|24 hours|4 hours|
|**Warfarin**|INR < 1.5 prior to insertion. Warfarin cannot be used with an epidural in situ - use UFH. INR < 1.5 prior to removal.|6 hours|
|**Aspirin**|2-3 days prior to cervical/thoracic epidural placement.|-|
|**NSAIDs**|-|-|
|**Clopidogrel**|7 days for insertion, can consider 5 days if high cardiac risk.|12-24 hours following catheter removal (24 hours if loading dose to be given).|
|**Ticagrelor**|5 days|24 hours|
|**Prasugrel**|7-10 days|24 hours|
|**Dabigatran**|Ideally 4 days|24 hours|
|**Rivaroxaban/Apixaban**|At least 2 days, ideally 3 days|24 hours
|**Tirofiban**|8-24 hours|8-12 hours|
|**Thrombin inhibitors** including bivalirudin, lepirudin|Avoid. Seek expert advice.|Seek expert advice.
|**Thrombolytics**|10 days.|Measure fibrinogen level prior to removal. Seek expert advice.|
|**Herbal** including garglic, gingseng, and gingo bilboa|-|-|


## Anatomy

Layers of the back include:

* Skin
* Subcutaneous tissue
* Longitudinal ligament
* Interspinous ligament
* Ligamentum flavum
* Epidural space\
The epidural space:
    * Bounded:
        * Anteriorly by the posterior longitudinal ligament\
        Remember the epidural space forms a ring around the dural sac.
        * Superiorly by the skull\
        At the foramen magnum.\
        * Inferiorly by the sacrococcygeal ligament
        * Posteriorly by the ligamentum flavum
    * Contains fat, **valveless veins**, nerve roots, as well as the posterior and anterior spinal arteries and the artery of Adamkiewicz
    * Has different properties in different areas of the spine:
        * Lumbar
            * At an average of 5cm  (3-8 in 90%)
            * Usually catheterised between L2 and L5 interspaces
        * Thoracic
            * Narrow, avoid midline approach between T5 and T8
        * Cervical
            * Thin and soft ligamentum flavum leads to poor appreciation of LoR
            * Space is ~ 1.5-2mm deep at C7, ↑ to 3-4mm with neck flexion
* Dura and arachnoid
* Subarachnoid space

## Complications

Divided into:

* Physiological\
Arising due to effect of the drugs:
    * Hypotension
    * LAST
    * Narcosis
* Procedural
    * Permanent nerve injury
    * Bleeding
        * Epidural haematoma
    * Infection
        * Epidural abscess
    * Drug error
        * Antiseptic injection
    * [PDPH](/disease/cns/pdph.md)
* Failure/Incomplete analgesia


---

## References

1. Narouze S, Benzon HT, Provenzano D, Buvanendran A, De Andres J, Deer T, Rauck R, Huntoon MA. [Interventional Spine and Pain Procedures in Patients on Antiplatelet and Anticoagulant Medications (Second Edition): Guidelines From the American Society of Regional Anesthesia and Pain Medicine, the European Society of Regional Anaesthesia and Pain Therapy, the American Academy of Pain Medicine, the International Neuromodulation Society, the North American Neuromodulation Society, and the World Institute of Pain](https://journals.lww.com/rapm/fulltext/2018/04000/Interventional_Spine_and_Pain_Procedures_in.2.aspx). Reg Anesth Pain Med. 2018 Apr;43(3):225-262.
2. ANZCA. [PS03: Guidelines for the Management of Major Regional Analgesia](http://www.anzca.edu.au/Documents/ps03-2014-guidelines-for-the-management-of-major-r.pdf).