# Peribulbar Block


The peribulbar block:

* Involves injection of LA into the **extraconal space** around the eyeball
	* A larger volume is used to facilitate intraconal spread of LA
* Preferable to retrobulbar block as it has a lower rate of complications



## Indications

Anaesthesia and akinesia of the globe for:

* Cataract extraction
* Trabeculectomy
* Vitrectomy
* Strabismus repair


## Contraindications

Should be avoided when:

* Axial length is **>26mm**  
Increased risk of globe perforation, particularly due to risk of posterior staphylomas.
* Severe coagulopathy
* Perforated globe
* Infected eye
* Inability to lie flat
* Staphyloma  
Increased risk of globe perforation.

## Anatomy

{{< include /includes/orbit.qmd >}}



## Equipment

* Gauze
* Antiseptic  
Typically 50% saline with 50% aqueous betadine
* Topical local anaesthetic drops
* Mix LA solution  
Many different options exist.
	* Lignocaine/Ropivacaine
		* Take 40mls of 1%% ropivacaine, 10ml 10% lignocaine, and 1500 units of hyaluronidase
		* Into a 50ml syringe, draw up the local anaesthetics and mix in the hylauronidase
		* This gives a combination of 0.8% ropivacaine, 2% lignocaine, and 30U/ml hyaluronidase  
		Hyaluronidase concentrations of 30U/ml or greater are associated with periorbital cellulitis.
	* Ropivacaine alone  
	0.75-1% ropivacaine with 75-150 U/ml hyaluronidase.

	
* A needle  
Typically 23-27G.
* A syringe  
Typically 10ml.
* Minimum volume extension  
Removes weight of syringe from needle improving manual dexterity.


## Technique

> Avoid oversedation - patients are usually frail, and the very fine needles are minimally painful. A small dose of midazolam and alfentanil are adequate for good conscious sedation.

*Assumes monitoring, IV access, time-out, topical local anaesthetic drops, and conscious sedation have been performed, as discussed [here](/anaesthesia/opthal/opthal-la.md#id).*

* Apply antiseptic  
Ensure there is some antiseptic under the lower lid and in the conjunctival sac.
* Ask the patient to look directly ahead
* Perform block:
	* Palpate **medial two-thirds** and **lateral one-third** of the inferior rim of the orbit  
	This should be lateral to the limbus, to avoid damaging the fragile extra-ocular muscles.
	* Using a 23-27G needle, advance **directly backwards**  
	Parallel to orbital floor.
	**Limit insertion depth to 25mm**.
		* Avoid displacing the globe with a finger - this may cause globe rotation and the posterior part to move into the path of the needle
		* Bevel should be orientated supero-medially
		* If contacting bone, redirect slightly superiorly
		* If the globe rotates, this suggests scleral contact  
		Ensure patient can **move eye freely** once in at desired depth.
		* *Slight* superior and medial angulation can be performed once past the equator of the globe
	* Aspirate, then inject 4-10ml of LA
		* Cease injection if the globe becomes tense
* Use digital pressure or a Honan balloon to compress the globe, reducing LA volume and therefore IOP
* Assess for block efficacy  
Assess:
	* Eye opening  
	Levator block is usually a good indication of block efficacy.
	* Eye movements
	* Eye closing  
	* Vision  
	Difficult to interpret; normal findings include:
		* Normal vision
		* Grayscale vision
		* Flashing lights
* If required, a **top-up block** can be performed with a **different technique**:
	* Using a 30G 13mm needle
	* Place needle between the caruncle and medial canthus
	* Aim directly back, perpendicular to the coronal plane
	* Inject 3-4ml LA


## Complications{#comp}

Minor complications:

* Chemosis  
Subconjunctival swelling. Transient.
* Venous haemorrhage  
Cosmetic but rarely significant.
* Arterial haemorrhage  
May be dramatic, leading to rise in IOP. Usually requires postponing OT, but may require canthotomy.


Major complications:

* Globe perforation  
Due to direct trauma.
	* Increased risk with myopia, repeated injections
	* Presents with ocular pain, intraocular haemorrhage, restlessness  
	May not be immediately obvious.
* Retrobulbar haemorrhage  
Due to direct trauma.
	* Presents with bruising, propotosis, and pain  
	Inadequate retinal artery flow may require a lateral canthotomy to relieve IOP and prevent loss of vision.
	* May be subtle, occasionally presents as rapid orbital swelling and proptosis. 
* Optic nerve damage  
Due to direct injury or vascular occlusion.
	* Presents with visual loss
* Intraarterial injection  
Flow down the ICA may result in the dose of LA being delivered directly to midbrain structures.
	* May present with seizure or CVS toxicity
* Brainstem anaesthesia  
Due to needle passing through the nerve sheath, resulting in subarachnoid deposition of LA.
	* May present with a broad array of symptoms, including respiratory or CVS arrest, agitation, ptosis, dysphagia, confusion
* Oculocardic reflex  
Due to raised intraocular pressure.
	* Presents with bradycardia, which may be profound.


---

## References

1. Ripart J, Mehrige K, Rocca RD. [Local & Regional Anesthesia for Eye Surgery](https://www.nysora.com/local-regional-anesthesia-for-eye-surgery). NYSORA.
2. Chuan A, Scott DM. Regional Anaesthesia: A Pocket Guide. 1st Ed. Oxford University Press
