# Principles of Regional Anaesthesia


*This section covers aspects common to peripheral nerve blockade. [Complications](/anaesthesia/regional/principles.md) are covered elsewhere.*

This section is divided into:

* Requirements
* Procedural techniques
* Delivery mechanisms
* LA dosing

## Requirements

Requires:

* Informed consent
	* Nerve injury
	* Drug toxicity
	* Haemodynamic changes
	* Bleeding/bruising
	* Failure
* Assistance
* Sterile technique
* Coagulation assessment
* IV access
* Monitoring
* Ability to manage potential complications

### Block Time-Out {#timeout}

Prior to performing a regional block:

* Verify the **side** and **site** of proposed block with another clinician\
Requires:
	* Patient identification
	* Checking of the surgical consent
	* Identification of a surgical site mark
	* Discussion with the patient if possible
	* Placement of a mark close enough to the block site to be visible whilst performing the block
	* **Pausing *just*** prior to needle insertion to:
		* Verify presence of side and site mark
		* Verbally confirm site with the assistant

## Procedural Techniques

Can use:

* Landmark only
* Nerve stimulator
* Ultrasound


### Landmark

### Ultrasound

* Gold standard
* Associated with reduced rate of vascular injury compared to stimulator
	* Identify vessels on proposed needle path and choose approach to avoid them
* Approach:
	* Halt needle advancement prior to encountering nerve
	* Aim off
* **Tips for optimising success**:
	* Place digital pressure on the needle insertion site\
	Allows insertion site to be used as a fulcrum and torque the needle to drastically change direction after having penetrated a muscle plane.
	* Penetrate fascial planes away from nerves/vessels, then slide up within that plane
	* Injection inside the nerve *sheath* causes a rapid onset of surgical anaesthesia, but ↑ the risk of nerve injury

### Stimulator

* Allows localisation of nerves via electrical stimulation
* Stimulate:
	* At 1mA until muscle contractions visible in that nere area
	* Reduce current to 0.3-0.5mA/0.1ms prior to injection
* Consider giving a 0.5ml saline injection (Raj test)\
Should be associated with a loss of motor response.

Troubleshooting:

* Battery charged
* Wires are connected
* ECG electrode has good electrical contact
* Ensure landmarks correct


## Delivery Mechanisms

Can use:

* Single-shot
* Catheter

### Single-Shot

### Catheter for Continuous Infusion

* Prepare skin carefully\
Ensure catheter is not contaminated by alcohol solutions (neurotoxic).
* Inject small bolus of LA prior to inserting catheter\
Hydrodissect space for catheter.
* Pass catheter 2-5cm past needle tip
* Remove needle\
Ensure catheter position does not change.
* Inject remainder of loading dose into catheter

Postoperative management:

* Unambiguous labeling of the giving set
	* Tubing colour should be unique to regional analgesia infusions
	* Infusion pumps should be unique to regional analgesia
* Regular monitoring of physiological parameters and pain
* Ideally daily review by the proceduralist or a trained delegate
* Continue LA delivery:
	* Constant infusion at 2-10ml/h
	* Background infusion of 2ml/h with 5ml Q30min boluses PRN
* May be left in for 3-5 days


Troubleshooting:

* Ensure catheter is positioned correctly/not dislodged
* Consider bolus (e.g. 10ml 0.2% ropivacaine) if only partial analgesia present


## Dosing


**Single-shot:**

|Factors|Lignocaine|Bupivacaine|Ropivacaine|
|--|--|
|**Concentration**|1-2%|0.25-0.5%|0.5-1%|
|**Dose**|< 4mg/kg|< 2mg/kg|< 3mg/kg|
|**Time to Onset**|5-15 minutes|10-25 minutes|10-25 minutes|
|**Duration**|2-5 hours|Up to 12 hours|Up to 12 hours|


**Continuous Infusion:**

||Bupivacaine|Ropivacaine|
|--|--|
|**Concentration**|0.125-0.25%|0.2%|
|**Maximum Dose Rate**|Up to 18.75mg/hr|Up to 28mg/hr|


---

## References

1. Narouze S, Benzon HT, Provenzano D, Buvanendran A, De Andres J, Deer T, Rauck R, Huntoon MA. [Interventional Spine and Pain Procedures in Patients on Antiplatelet and Anticoagulant Medications (Second Edition): Guidelines From the American Society of Regional Anesthesia and Pain Medicine, the European Society of Regional Anaesthesia and Pain Therapy, the American Academy of Pain Medicine, the International Neuromodulation Society, the North American Neuromodulation Society, and the World Institute of Pain](https://journals.lww.com/rapm/fulltext/2018/04000/Interventional_Spine_and_Pain_Procedures_in.2.aspx). Reg Anesth Pain Med. 2018 Apr;43(3):225-262.