# Distal Femoral Triangle/Adductor Canal Block

This is a block of the femoral nerve in the mid-thigh, which aims to achieve analgesia to the anterior knee and medial lower leg, whilst sparing the nerve to vastus medialis and therefore motor function of the quadriceps.


## Indications

Anaesthesia for lower leg surgery
* May facilitate superficial procedures
* Usually supplements a sciatic block when performing foot and ankle procedures

## Contraindications

* General contraindications:
	* Patient refusal
	* LA allergy
	* Local infection

## Anatomy

{{< include /includes/ll_neuro.qmd >}}

## Equipment

* Standard nerve block tray
* High-frequency linear probe
* 5-10cm 22G short-bevel needle
* 5-10ml local anaesthetic

## Technique

* Position supine
* Place US probe over sartorius in the mid-thigh
* Identify sartorious  
Triangular, 'hull-shaped' muscle, with femoral artery running along the 'keel'. Saphenous nerve runs with the artery in this canal.
* Identify femoral artery  
Can scan caudally from groin if artery is not immediately identifiable.
* Standard prep, drape, skin anaesthesia, etc
* Perform block IP or OOP:
	* Aim to place needle tip just medial to femoral artery, deep to sartorius
	* Ensure good deposition of LA below sartorious, forming ring around artery

## Complications

* General complications
	* Intravascular injection
	* LAST
	* Nerve injury
	* Infection
	* Failure
	* Allergy to LA
* Specific complications
	* Motor block to vastus medialis  
	Avoid unsupported ambulation immediately post.

---

## References

1. Chuan A, Scott DM. Regional Anaesthesia: A Pocket Guide. 1st Ed. Oxford University Press.
2. NYSORA. [Ultrasound Guided Saphenous Block](https://www.nysora.com/ultrasound-guided-saphenous-nerve-block). Accessed September 2018.
