# Sub-Tenon's Block


A sub-Tenon's (episcleral) block:

* Involves injecting LA between the sclera and Tenon's capsule  
Causes spread of LA around the globe with a small volume of injection.

## Indications

Anaesthesia and akinesia of the globe, in a patient with:

* Increased axial length
* Presence of anticoagulant or antiplatelet agents  
Sub-tenons may be preferred by some providers, for a *potentially* lower risk of significant haematoma.

## Contraindications

Surgical factors:

* Trabeculectomy  
May reduce operative success.
* Previous sub-Tenon block in the same quadrant  
Adhesions may reduce efficacy of hydrodissection.
* Complete akinesia required
* Where chemosis or haemorrhage may reduce outcome  
Glaucoma filtration surgery.


Relative contraindications:

* Eye trauma
* Orbital infection
* Ocular pemphigoid


## Anatomy

{{< include /includes/orbit.qmd >}}


## Equipment 

* Gauze
* Antiseptic  
Typically 50% saline with 50% aqueous betadine
* Topical local anaesthetic drops
* Mix LA solution  
Many different options exist.
	* Lignocaine/Ropivacaine
		* Take 40mls of 0.75% ropivacaine, 10ml 10% lignocaine, and 1500 units of hyaluronidase
		* Into a 50ml syringe, draw up the local anaesthetics and mix in the hylauronidase
		* This gives a combination of 0.8% ropivacaine, 2% lignocaine, and 30U/ml hyaluronidase  
		Hyaluronidase concentrations of 30U/ml or greater are associated with periorbital cellulitis.
	* Ropivacaine alone  
	0.75-1% ropivacaine with 75-150 U/ml hyaluronidase.


* Eye speculum
* Fine non-toothed (Moorfields) forceps
* Westcott Scissors  
Preferably spring scissors.
* Sub-Tenon cannula


## Technique

*Assumes monitoring, IV access, time-out, topical local anaesthetic drops, and sedation have been performed, as discussed [here](/anaesthesia/opthal/opthal-la.md#id).*

The surgical approach involves:

* Topical LA drops  
Onto intranasal quadrant as this is more comfortable.
* Apply antiseptic  
Ensure there is some antiseptic under the lower lid and in the conjunctival sac.
* Ask the patient to look directly up and out
* Perform block:
	* With small forceps, push in and then grab the inferonasal quadrant of the globe 5-10mm from the limbus  
	The infranasal quadrant is preferred as there are no muscle insertions and it is not used for a surgical approach.
	* Keep pressure on the globe with the forceps throughout the procedure
	* Use the scissors to create a **linear** incision in the Tenon's capsule  
	Bring the scissors in vertically to create a straight incision. A curved incision creates a conjunctival flap, and may cause a cyst.
	* Perform blunt dissection with the scissors past the equator of the globe
	* Insert a blunt cannula into the episcleral space, tangential to the globe
	* Inject LA
		* 3-5ml typically produces good analgesia but only partial akinesia
		* 8-11ml produces akinesia via spread of LA to extraocular muscle sheaths
* Remove speculum

## Complications

*Mechanism of complications are similar to [peribulbar blocks](/procedures/regional/peribulbar.md#comp), but are typically much less common.*


Minor complications:

* Chemosis  
Almost universal.
* Pain on injection
* Subconjunctival haemorrhage

Major complications:

* Brainstem anaesthesia
* Globe perforation
* Retrobulbar haemorrhage
* Retinal ischaemia  
May occur in absence of retrobulbar haemorrhage, and result in permanent visual loss.
* Optic nerve damage
* Rectus muscle dysfunctikon  
May be due to direct trauma and haemoatoma formation, leading to muscular contracture.

---

## References

1. Ripart J, Mehrige K, Rocca RD. [Local & Regional Anesthesia for Eye Surgery](https://www.nysora.com/local-regional-anesthesia-for-eye-surgery). NYSORA.
2. Olive, D. [Sub-Tenon's Eye Block Version 2](https://www.youtube.com/watch?v=JJBlwHknBcA). Anaestricks. 2013.
3. Kumar CM, Eid H, Dodds C. [Sub-Tenon’s anaesthesia: complications and their prevention](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3178142/pdf/eye201169a.pdf). Eye. 2011;25(6):694-703.
4. Chuan A, Scott DM. Regional Anaesthesia: A Pocket Guide. 1st Ed. Oxford University Press
