# Lung Isolation


Lung isolation and one-lung ventilation:

* Has many uses in thoracic surgery and ICU
* May be difficult to achieve
* May lead to complications and physiological compromise  
Clinically meaningful hypoxia in ~10% of thoracic surgery during OLV.


## Indications

Absolute:

* Protective isolation
	* Massive haemorrhage
	* Pneumonia
* Control of distribution of ventilation
	* Massive bullae
	* Bronchopleural fistula
* Unilateral lung lavage
* VATS


Relative:

* Surgical exposure
	* Thoracic aortic aneurysm
	* Pneumonectomy
	* Upper lobectomy
	* Oesophageal surgery
	* Thoracoscopy

## Contraindications

Inability to maintain oxygenation on one-lung.

Predictors of hypoxaemia:

* Patient
	* Preferential perfusion to operative lung
		* Right-sided surgery
		* Previous contralateral resection
		* Contralateral pathology
	* Normal FEV<sub>1</sub>
	* Chronic vasodilator therapy
	* Poor oxygenation on two lung ventilation
* Procedure
	* Supine perfusion
	* Volatile anaesthesia >>1 MAC

## Anatomy

## Equipment

Specific equipment for lung isolation include:

* Double-lumen ETT
	* Oral
	* Tracheostomy  

* Bronchial blocker  
Subclassified into:
	* Torque-guided  
	e.g. Cohen.
	* FOI-guided  
	e.g. Arndt, Fuji.
	* Bilateral  
	e.g. Easy blocker.
* Single-lumen ETT
	* Endobronchial tube
	* ETT tube  
	Advanced directly.
		* Mostly likely to enter RMB
		* Can be guided with FOI into either bronchus


### Double-Lumen ETT

DLTs:

* Common and versatile
* Relatively contraindicated in:
	* Poor laryngoscopic airway grades  
	Difficult to insert, and *extremely* challenging to railroad over a bougie or bronchoscope.
	* Aberrant tracheobronchial anatomy  
	Potential for significant iatrogenic injury.
* Come in left- and right-sided variants
	* As the right bronchus intermedius is very short, it is easy to accidentally occlude the right upper lobe with a right-sided DLT  
	The side-port on right-sided ports should generally be positioned under bronchoscopic guidance to minimise this risk.
	* In general, a left sided DLT is used for most cases unless:
		* Surgical resection will involve the proximal left main bronchus
		* Aberrant anatomy precludes use of a left-sided DLT
* Measured in French gauge  
	* In general; 41-39Fr is appropriate for males, and 37Fr for females.
	* **Depth** of DLT insertion: **12cm + 0.1cm per 10cm of patient height**


Pros of DLTs:

* Provide generally good isolation
* Facilitate easy recruitment and de-recruitment of lung


Cons of DLTs:

* Large and harder to insert than standard ETTs  
* Smaller internal lumens than standard ETTs  
Require a bronchoscope with a **⩽4mm lumen** to instrument a **35 Fr** DLT.


Insertion of a left-sided DLT:

* Place DLT through cords with curve in A-P plane
* Remove stylet once through cords
* Rotate DLT 90°  
Anticlockwise for left-sided.
* Insert DLT until reaching slight resistance
* Inflate tracheal cuff
* Confirm ventilation and CO<sub>2</sub>
* Evaluate position with bronchoscope
	 * Bronchoscope down tracheal lumen
	 * Confirm RUL position
	 * If RUL unable to be visualised:
	 	* Shield scope in tracheal lumen
	 	* Deflate tracheal cuff
	 	* Slowly withdraw tube until carina visualised
	 	* Use scope as stylet to advance DLT to desired position
* Inflate bronchial cuff under vision  
Slight rim of blue cuff should be seen in the LMB.
* Place bronchoscope down bronchial lumen to ensure left upper lobe bronchus not obstructed


### Bronchial Blockers

A low-pressure, high-volume balloon that is inflated to occlude the bronchus.
* Key sizes:
	* 7 Fr for a 6.5 Fr ETT
	* 9 Fr for a 7.5 Fr ETT

Pros:

* Preferable in certain situations
	* Difficult intubation
	* High-risk tube exchange
	* Tracheostomy
	* Anatomical abnormalities
		* Endoluminal stricture
* Selective lobar isolation  
Apply CPAP down internal channel when wire removed.
* Paediatrics


Cons:

* Limited control
	* Can't suction
	* Harder to oxygenate/perform pulmonary toilet
	* Repeated deflation and reinflation is limited
* Increased dislodgement
* Slower:
	* Lung deflation
	* Positioning



## Isolation Technique

Isolation can be achieved using:

* Double lumen ETT
* Bronchial blocker
* Endobronchial intubation with a single-lumen ETT

General principles involve:

* Ventilation with 100% O<sub>2</sub>  
Aim for maximal denitrogenation; absorption of oxygen will speed up lung collapse.


### Isolation with Double-Lumen Tube

> Remember to re-check isolation after repositioning the patient

Confirmation of position:

* Clinical
	* Insert DLT
	* Inflate bronchial cuff
	* Connect circuit directly to bronchial lumen
	* Confirm ventilation on bronchial side, and not on tracheal side
	* Connect circuit to tracheal lumen
	* Inflate tracheal cuff until there is no leak
	* Confirm breath sounds on tracheal side, and not on bronchial side
* Bronchoscopic
	* Insert DLT
	* Inflate tracheal cuff
	* Confirm tracheal intubation with CO<sub>2</sub>
	* Bronchoscope down tracheal lumen and identify carina  
	Identify trifurcation of RUL if right-sided.
	* Inflate bronchial cuff under vision  
	Aim to see narrow rim of blue cuff visible in the main bronchus.
	* If right-sided DLT, pass bronchoscope down bronchial lumen and confirm that the RUL ventilation port is aligned with the RUL bronchus


Isolation:

* Confirm DLT positioning
* Clamp DLT proximally on side to be deflated
* Open DLT to air, distal to the clamp, on the side to be deflated  
	* Consider suctioning down open lumen to speed up collapse
* Confirm ventilation appropriate on remaining lung


### Isolation with Bronchial Blocker

* Turn PEEP to 0cmH<sub>2</sub>O
* Insert bronchial blocker  
May be inserted under bronchoscopic guidance or directed blindly.
* Inflate the bronchial blocker  
This can be performed:
	* At end-expiration (when lung volume is at its minimum)  
	This will decrease the size of the isolated section of lung and therefore the impediment to the surgeon.
	* After waiting until desaturation begins to occur  
	In a patient who has been ventilated on 100% oxygen, this will indicate maximal atelectasis in the lung (though may take some time to occur).


#### Selective Lobar Isolation with Bronchial Blocker

* This technique allows isolation of one particular area of lung whilst maintaining gas exchange in the remaining lung  
Isolation of the RUL or RML/RLL is easiest to perform.
* Place DLT and isolate the operative/injured lung
* Place bronchial blocker into the non-ventilated lung and inflate the blocker
* Apply CPAP:  
Initially 5-10cmH<sub>2</sub>O until recruited, then decrease to 2-5cmH<sub>2</sub>O.
	* Down bronchial blocker  
	Can be performed by removing loop from Arndt blocker.
	* To DLT lumen


### Lung Isolation in the Difficult Airway

Options include:

* Awake FOI with DLT
* Awake FOI with SLT and BB
* Awake FOI with SLT and airway exchange  
Requires a catheter at least 70cm long.
* Asleep DLT with combined VL and bronchoscopy


Tracheostomy:

* Remove and insert DLT  
Certain DLTs made for this purpose.
* Leave in and insert BB



## Surgical Considerations

Surgical technique will affect rate and adequacy of lung collapse:

* Airtight seal with thoracoscopic ports will reduce pneumothorax development
* Suctioning will re-expand lung


## Ventilatory Technique

> * Priority is to **avoid hypoxia**  
Typically aim SpO<sub>2</sub> > 90%.
>	* Maintain FRC in ventilated lung
> * Maximise PVR in the independent/operative/deflated lung
> * Minimise PVR in the dependent/ventilated lung

General Approach:

* Optimise FRC of the dependent lung  
Occurs at lower than usual volumes due to paralysis, lateral position, and the weight of the mediastinum.
	* Any shunt in ventilated lung is poorly tolerated
* Avoid impediments to hypoxic pulmonary vasoconstriction in ventilated lung
	* Hypocapnoea
	* Vasodilators
	* Excessive volatile
* Begin at:
	* FiO<sub>2</sub> of 1.0  
	Aim to down-titrate to 0.5-0.8.
	* Vt of 5ml/kg
	* 5-10cmH<sub>2</sub> of PEEP  
	Consider ZEEP in the severe COAD patient.
* Targeting:
	* Pplat < 25cmH<sub>2</sub>O
	* PaCO<sub>2</sub> ~35mmHg  
	Permissive hypercapnoea acceptable; 


### Responding to Hypoxaemia

>PaO<sub>2</sub> falls rapidly initially, with a nadir at 20-30 minutes. Will tend to improve as HPV increases.

Critical hypoxaemia:

* May occur with:
	* Rapid decline
	* Major comorbidity
	* Haemodynamic instability
* Recruit operative lung until stabilised/help arrived
	* Increase FiO<sub>2</sub>
	* Two-lung ventilation  
	If SpO<sub>2</sub> <88-85%.
	* CPAP

Identify and treat common causes:

* Basics first  
Check the tube and check the patient:
	* Failure of isolation
		* Bronchoscopy
	* Obstruction
		* Suction
* Derecruitment
	* Recruitment maneuvre
	30-40cmH<sub>2</sub>O, noting a drop in CO, BP, and SpO<sub>2</sub> will transiently follow.
		* Arterial line useful if recruiting longer than 10-20s
	* PEEP titration  
	Typically up to 10cmH<sub>2</sub>O - noting that excessive PEEP will worsen PVR.
* Low DO<sub>2</sub>
	* Ensure Hb adequate
	* Consider inotropes
	* Fall in CO
		* Mediastinal pressure by surgeon
* Shunt through operative lung  
Likely cause of hypoxia when other factors are optimised. Consider:
	* Oxygen to operative lung  
	Delivery of low-flow (e.g. 2L/min) O<sub>2</sub> down a suction catheter.
		* Catheter can be placed under bronchoscopic guidance to minimise effect on surgical exposure
	* CPAP to operative lung  
	May interfere with surgical exposure depending on amount of CPAP applied and proximity of operative site to hilum.
		* 2cmH<sub>2</sub>O nearly always tolerated
		* 9cmH<sub>2</sub>O begins to impinge
	* Pulmonary vasodilators to ventilated lung  
	Not appropriate as rescue therapy. 
		* iNO at 20ppm is effective only when combined with a vasoconstrictor
		* Inhaled PGE1 at 10ng/kg/min
	* Intermittent two-lung ventilation  
	May significantly hamper surgical access and prolong operating time.
	* Clamp PA of operative lung  
	Technically difficult for surgeons to accomplish and not risk-free; they are usually reluctant to do this but it is very helpful if the vessels are exposed (e.g. in pneumonectomy).




## Complications

Complications of one-lung ventilation include:

* Hypoxia due to shunt
* Acute Lung Injury  
~2-5% incidence.


---

## References

1. Lohser J. Managing Hypoxemia During Minimally Invasive Thoracic Surgery. Anesthesiology Clinics. 2012;30(4):683-697.
2. Collins SR, Titus BJ, Campos JH, Blank RS. Lung Isolation in the Patient With a Difficult Airway. Anesth Analg. 2018 Jun;126(6):1968–78. 
