# Overview of Mechanical Ventilation

Use of a machine to augment or supplant native respiration. Goals of mechanical ventilation are to:

* Correct hypoxia
* Correct hypercapnoea
* Minimise VILI\
Avoid excessive lung stretch and cyclic recruitment-collapse.
    * V~T~ 6mL/kg predicted body weight
    * Pplat <30cmH~2~O
    * Adequate PEEP

## Indications

Divided into need for:

* Definitive airway
    * Loss of airway reflexes
    * Secretion management
    * Following use of sedation or paralysis
    * Upper airway obstruction
* Mechanical ventilation
    * T1RF
    * T2RF
    * Manipulate physiology\
    e.g. CO~2~ control for increased ICP.
    * Work of breathing

## Complications

* Equipment
    * Malfunction
    * Incorrect settings
* A
    * Airway trauma
        * Teeth
        * Cords
* B
    * VAP
    * VILI
    * Barotrauma\
    Pneumothorax.
* C
    * RV dysfunction
        * Decreased Preload
        * Increased Afterload
    * Organ blood flow
        * Decreased RBF
        * Decreased Splanchnic flow
    * Fluid retention
* D
    * Dyssynchrony
    * Complications of sedation
* E
    * Deconditioning     

## Physiological Principles


---

## References