# Jet Ventilation


Jet ventilation is the use of high-pressure (1-3 bar), high frequency ventilation to facilitate oxygenation and ventilation. Jet ventilation:

* Is used in the operating room for:
	* Diagnostic laryngoscopy and glottic ENT surgery
		* Allows unimpeded view of larynx  
		Narrow bore catheters.
		* Immobility of vocal cords  
		Small tidal volumes cause less movement.
	* Thoracics
		* Selective jet ventilation to non-dependent lung ↑ PaO~2~
	* Radiofrequency ablation
		* Jet ventilation reduces breathing-related motion of abdominal and thoracic organs
* Achieves gas exchange via alternate means compared with conventional ventilation  
When tidal volumes are smaller than dead space volumes, bulk flow is relatively less effective.
	* Pendelluft  
	Movement of gas between lung units with different time constants. Fast-filling alveoli will redistribute inspired gas to slow-filling alveoli.
	* Convective streaming  
	Higher velocity central jets will diffuse to lateral zones at end-expiration.
	* Cardiogenic mixing  
	Cardiac pulsations agitate lung tissue and improve molecular diffusion.
* Requires:
	* Close communication with surgeon  
	Jet fired between laser pulses to prevent cord movement.
	* Paralysis
	* TIVA
	* Careful control of **FiO~2~**  
		* No laser: 100% O~2~
		* Laser: 30% O~2~  
		Consider ↑ FiO~2~ between pulses or whilst waiting for biopsy results, etc.



## Mechanisms

May be either:

* [Manual](man)  
Low frequency.
* [Automated](auto)  
Low (8 bpm) to high (up to 300bpm) frequency.  
	* Reduced barotrauma compared to manual jet ventilation


## Manual Jet Ventilation{#man}

Initial setup:

* Driving pressure: 3.5 bar (0-3.5 bar)
* Respiratory rate: ~8
* Inspiratory time: ~1s, aiming 4-5s expiration  
Keep hand or eyes on chest throughout to ensure full expiration occurs - high risk for barotrauma.


## Automated Jet Ventilators{#auto}

* Deliver heated, humidified gas jets in a square wave at 1-10Hz
* Clinician can control driving pressure, frequency, inspiratory time, and composition of gas
* Have alarms and emergency shutdown devices in presence of high airway pressures


Advantages:

* Minimises vocal cord, bronchial, and mediastinal excursion
* Can be passed through surgical field to jet into trachea
* Less haemodynamic impact compared with IPPV
* CO can be augmented using ECG synchronisation
* Avoids potential for ETT fire


Initial Setup:

* Driving pressure: 2 bar  
1-3 bar acceptable range.
* Frequency: 200/min  
150-300cpm. ↑ frequency **reduces** tidal volume.
* FiO2: 1.0
* I-time: 20%  
Adjust 20-70%. ↑ inspiratory time ↑ tidal volume.
* Pause pressure: 2mbar  
10-40mbar. This is the pressure measured at the tip of the ventilation catheter ~1ms before the next jet.


Adjustment:

* ↑ oxygenation and ventilation requires ↑ pressure, not rate


Intraoperative Management:

* Check for movements of the chest and abdomen
* Check CO~2~ if sampling port connected  
Not an accurate assessment of arterial CO~2~, and is easily lost if the port is blocked or kinked.
* Turn off HFJV prior to removing catheter to prevent contamination


## Techniques

> Supraglottic ventilation usually required for posterior cord lesions.

May be:

* [Supraglottic](supra)
* [Infraglottic](infra)
* [Transtracheal](trach)


### Supraglottic{#supra}  

Jet kept in glottis and gas jetted through the glottis.
* Pros:
	* Cheap
	* No tube in surgical field
* Cons:
	* Greater rate of ↑ in airway pressure compared to subglottic ventilation  
	Counter-intuitive, but occurs due to:
		* Venturi effect  
		Greater entrained air with supraglottic approach ↑ tidal volume and reduces FiO~2~.
		* Double jetting  
		Supraglottic jet is reflected from glottis, ↑ supraglottic pressure and impeding expiratory flow.
		* Expiratory impedance  
		Expiration can only occur during the expiratory phase of the cycle, which is a function of the I:E ratio of the jet ventilator.
	* No CO~2~ monitoring
	* Cannot monitor peak airway pressure
	* Inadequate ventilation  
	If aim is incorrect. Monitor:
		* Sound
		* Chest movement
	* Movement of surgical field ↑ compared to subglottic approaches 
	Can't ventilate whilst lasering.




### Infraglottic

Jet catheter placed in trachea via glottis:

* Pros
	* Slow rate of pressure ↑
	* Consistent FiO~2~  
	Minimal entrainment.
	* Expiration can occur through a subglottic stenosis throughout the respiratory cycle, reducing expiratory impedance
* Cons
	* Requires an intra-tracheal catheter  
	Obstructs surgical field.
		* Hunsaker Monjet  
			* Basket assists central direction of jet
			* Laser-resistant
			* Should be placed >7.5cm post the cords so the monitoring port is at an adequate depth  
			* Monitoring port easily blocked or kinked
		* LaserJet
			* Similar to Hunsaker but without the basket
			* Monitoring lumen for airway pressure and CO~2~


### Transtracheal

Jet catheter placed in trachea via front of neck:

* Pros
	* Anaesthetic advantages of infraglottic jet ventilation
	* Surgical advantages of supraglottic jet ventilation
* Cons
	* Requires front of neck access
	* Risk of gas trapping with small diameter stenoses  
	Air pressure exceeds that of infraglottic jetting when stenosis diameter is <4.5mm.

## Complications

* **Barotrauma**  
May lead to subcutaneous emphysema, pneumothorax, or pneumomediastinum. Occurs due to:
	* Excessive inspiratory pressures
	* Prolonged inspiratory time
	* Outflow obstruction
* Gas trapping  
Outflow obstruction leading to rise in airway pressures and occlusion of venous return.
* Dry gas trauma  
Occurs if jetting without humidified gas. Leads to epithelial necrosis, mucous buildup, and airway pluggin.
* Hyperoxia  
Due to fall in FiO~2~ or ↓ airway pressure and atelectasis.
* Hypercapnoea  
Can be avoided by ↑ driving pressure (to ↑ tidal volume) and ↓ frequency (to ↑ E time).


	* Malignancy  
	Theoretical risk of spreading tumour cells.
	* Risk of airborne contamination if **papilloma**; wear masks



---