# Tonsillectomy and Adenoidectomy


>Airway: Requires either a south RAE, reinforced ETT, or flexible LMA. <br>
>Access: 22G-18G, depending on  age.<br>
>Pain: Moderate; usually worst at day 5-7. <br>
>Position: Supine, head elevated with neck extended. <br>
>Time: 30-60min. <br>
>Blood loss: Usually minimal; ~4ml/kg in children. May be difficult to estimate if blood enters stomach.<br>
>Special: Antibiotic chemoprophylaxis are usually not required. <br>


*This covers anaesthesia for elective tonsillectomy. Anaesthetic management of the bleeding tonsil is [covered elsewhere](/anaesthesia/ent/bleeding-tonsil.md).*


Removal of tonsils and adenoids. Performed for either:

* Chronic infection\
Usually appropriate for day-surgery provided oral intake is tolerated post-operatively.
* OSA

## Considerations

* Indication for surgery\
Primary pathology may affect choice of premedication, opioids, and choice of discharge destination.
* A
	* Risk of difficult mask ventilation and intubation
	* Discussion with surgeon about preferred airway
* B
	* Presence and severity of OSA will affect
		* Secondary effects
			* CO~2~ retention
			* Failure to thrive
			* Cor pulmonale
		* Sensitivity to opioids and sedatives\
		Generally **avoid premedication** in paediatric cohort.
		* Post-operative destination\
		* Awake vs. deep extubation
	* Risk factors for post-operative apnoea
		* Age ⩽3
		* Moderate-severe OSA
		* Overnight nadir SpO^2^ ⩽90%
		* Ex-premature
		* Under/overweight
		* Syndromic
		* Recent RTI/asthma
		* Intraoperative desaturation
* G
	* PONV prevention\
	Suggest 0.5mg/kg of dexamethasone.
* H
	* Coagulopathy

## Preparation

* Standard ANZCA monitoring in adults


## Induction

* Gas induction\
Common in children.
* IV induction may be safer in severe OSA


* Airway obstruction is common\
Often require CPAP to alleviate.


* Intubation
	* Careful laryngoscopy to avoid bleeding from enlarged tonsils and adenoids
* Laryngeal mask\
Reduced incidence of post-extubation complications.

## Intraoperative

Maintenance with:

* Propofol/remifentanil\
Smooth haemodynamics and emergence.
* Deep volatile


### Analgesia Strategies

> Goal is to provide adequate analgesia and avoid post-operative apnoeas

A recipe:

* Dexamethasone 0.2mg/kg\
Reduces pain, bleeding, PONV, and time to first oral intake.
* Paracetamol 15mg/kg
* Parecoxib 1mg/kg
* Opioid
	* Children\
	Fentanyl 1-2mcg/kg.
	* Adults\
	Have more pain, and pain will depend on surgical technique.
		* Cold steel\
		Less pain; fentanyl or smaller doses of morphine.
		* Bipolar diathermy\
		Less pain.
		* Unipolar diathermy\
		Significant pain. Morphine or oxycodone, often >10mg.


### Surgical Stages

* Positioning
* Insertion of mouth gag\
	* May **compress ETT** if not using a reinforced tube
	* Highly stimulating
	* May dislodge ETT
* Adenoidectomy\
If performed, will be removed with a curette.
* Packing of nasopharynx
* Tonsillectomy
	* Superior pole drawn medially
	* Dissected from the tonsillar pillar and removed
* Haemostasis\


## Postoperative

Emergence is **critical**:

* **Remove throat pack**\
If used. Suction stomach if not used.
* **Careful suctioning**\
Under vision.
* Consider **deep extubation**
	* Most suitable in small children
	* Place left lateral, head-down\
	Leave until fully awake.
* Avoid coughing


Risk factors for post-operative airway events:

* Age < 3 years
* Severe OSA
* Ex-premature
* Under-overweight
* Syndromic
* Significant cardio/respiratory disease
* Intercurrent RTI
* Intraoperative event:
	* Desaturation
	* Use of CPAP
	* Delayed emergence


Post-operative care:

* Day stay unless:\
	* ⩽2 years old\
	More likely to have severe airway obstruction postoperatively.
	* Severe OSA
	* Other comorbidities
* Analgesia
	* Paracetamol QID
	* Celecoxib BD for 5/7
	* PRN opioid whilst in hospital\
	Not on discharge.


---

## References

1. Coté CJ, Posner KL, Domino KB. Death or neurologic injury after tonsillectomy in children with a focus on obstructive sleep apnea: houston, we have a problem! Anesth Analg. 2014 Jun;118(6):1276-83.