# Last Days of Life

Priorities in the last days of life should be:

* Maintain the patient's **dignity**
* Effective control of discomfort and pain
* Open, honest, and compassionate **communication** with **families**
	* Acknowledging the uncertainty in being able to accurately predict trajectory
* Collegial communication with other clinicians\
A patients death is often a challenging time for colleagues used to treating patients with curative intent.
* De-prescribing
	* Cease all medications without demonstrable symptomatic benefit
	* Consider withdrawal or rebound syndromes
	e.g. Steroids, benzodiazepines, anticonvulsants and antidepressants.

:::column-margin
Therapeutic interventions may be advocated for by families or other clinicians. A useful compromise is a time-limited (e.g. up to 48 hours) trial of a therapeutic intervention, which would be ceased if some threshold of improvement is not met.
:::

## Management

: Specific Therapy for Patients in the Last Days of Life

+-----------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Symptom                     | Principles                                                                                                                                                         | Specifics |
+=============================+====================================================================================================================================================================+===========+
| **Pain**                    | * **Regular analgesia** via infusion                                                                                                                               |           |
|                             | * **Breakthrough analgesia**                                                                                                                                       |           |
|                             | * Placement of IDC\                                                                                                                                                |           |
|                             | Prevent urinary retention. Discomfort from the IDC is usually minimal.                                                                                             |           |
|                             | * Massage                                                                                                                                                          |           |
|                             | * Hot packs                                                                                                                                                        |           |
|                             | * Regular turns and pressure area care                                                                                                                             |           |
+-----------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| **Dyspnoea**                | * **Position**\                                                                                                                                                    |           |
|                             | Head up.                                                                                                                                                           |           |
|                             | * Supplemental oxygen\                                                                                                                                             |           |
|                             | For symptomatic relief. Consider HFNO.                                                                                                                             |           |
|                             | * **Fan**                                                                                                                                                          |           |
|                             | * Open a window                                                                                                                                                    |           |
|                             | * Opioids                                                                                                                                                          |           |
|                             | * Benzodiazepines\                                                                                                                                                 |           |
|                             | If anxious.                                                                                                                                                        |           |
|                             | * Avoid stacking care                                                                                                                                              |           |
+-----------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| **Nausea/vomiting**         | * Antiemetics                                                                                                                                                      |           |
|                             | * Haloperidol                                                                                                                                                      |           |
|                             | * Offer small volumes of food and liquid if still eating\                                                                                                          |           |
|                             | It is usual for patients to not feel hungry - this is often distressing for families and they should be reassured that this is a normal part of the dying process. |           |
|                             | * Consider bowel obstruction                                                                                                                                       |           |
+-----------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| **Bowel/Bladder**           | * Consider IDC                                                                                                                                                     |           |
|                             | * Consider laxatives, enema or suppositories                                                                                                                       |           |
+-----------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| **Swallowing difficulties** | * Sit up                                                                                                                                                           |           |
|                             | * Regular mouth care\                                                                                                                                              |           |
|                             | Moistening swabs.                                                                                                                                                  |           |
|                             | * Treat oesophagitis                                                                                                                                               |           |
|                             | * Consider corticosteroids                                                                                                                                         |           |
+-----------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| **Delirium**                | * De-prescribe                                                                                                                                                     |           |
|                             | * Continue hearing aids and glasses                                                                                                                                |           |
|                             | * Regular circadian rhythm                                                                                                                                         |           |
|                             | * Provide explanation and reassurance                                                                                                                              |           |
|                             | * Familiarise environment                                                                                                                                          |           |
|                             | * Consider **antipsychotics**                                                                                                                                      |           |
+-----------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| **Restlessness**            | * Non-pharmacological                                                                                                                                              |           |
|                             |     * Soft music                                                                                                                                                   |           |
|                             |     * Repositioning                                                                                                                                                |           |
|                             |     * Bladder scan                                                                                                                                                 |           |
|                             |     * Massage                                                                                                                                                      |           |
+-----------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+



:::column-margin
Anticipatory prescribing is important, and involves ensuring that medications for common symptoms such as breathlessness, pain, nausea and constipation are available for PRN use.
:::

:::column-margin
Regular patient assessments should be performed to titrate therapy.
:::

---

## References

1. Australian Commission for Safety and Quality in Healthcare. [Comprehensive Care Standard End-of-life care: clinical basics](https://www.safetyandquality.gov.au/sites/default/files/2020-11/End-of-life%20care%20-%20clinical%20basics.pdf). 2024.