# Damage Control Surgery {#sec-damage_control}

Damage control surgery describes **limited surgical interventions** to correct or temporise **immediately life-threatening injuries until** a patient **regains** the **physiological reserve** to **tolerate** definitive **repair**. The key principles involve:

:::column-margin
This covers the principles of Damage Control Surgery and the care of the trauma patient after the emergency room. Conduct of the Primary Survey and Damage Control Resuscitation are covered under @sec-trauma_primary, whilst management of critical bleeding and massive transfusion are covered under @sec-critical_bleeding.
:::

* Avoiding tissue hypoxia and oxygen debt by:
	* Reducing blood loss
		* Aggressive control of external haemorrhage
		* Permissive hypotension
		* Correcting of hypothermia, coagulopathy, and acidosis
		* Aggressive transfusion\
	* Preventing coagulopathy\
		* Avoid acidosis
		* Avoid hypothermia
		* Transfusion\
		* TXA use\
		1g over 10 minutes, and a further 1g at 8 hours.
		* Minimise crystalloid use
* Abbreviated life-saving surgery
	* Normalise physiology at the expensive of anatomy
	* May result in early amputation of abbreviated surgery leading to neurovascular deficit, in order to save life
* Expediting transfer to definitive care


## Indications

Severely injured patients with multisystem trauma, generally indicated by:

* Severe physiological derangement	
	* Hypothermia
	* Coagulopathy
		* Clinical\
		No visible clots or diffuse tissue ooze.
		* Laboratory\
		APTT/PT >1.5× normal.
	* Persistent cellular shock
		* pH <7.2
		* BD >15mmol/L
		* Lactate >5mmol/L
		* O~2~ consumption index <100ml/ml/m^2^
		* New ventricular arrhythmia
* Inability to control bleeding
* Large volume resuscitation
	* \>10 units PRBC
	* \>12L of volume resuscitation\
	Including crystalloid and blood, in both pre- and intra-hospital phases.
* Injury patterns
	* Major venous injury with poor access\
	Intrahepatic, retrohepatic, retroperitoneal, pelvic.
	* Major liver injury\
	* Pancreato-duodenal injury with:
		* Haemodynamic instability
		* Head of pancreas bleeding
	* Massive vascular disruption to:
		* Duodenum
		* Pancreas
		* Pancreato-duodenal complex\
		With ampulla/pancreatic duct injury.
	* Requirement for staged abdominal or thoracic wall reconstruction


## Contraindications

Damage control surgery is associated with ↑ morbidity and hospital length of stay, and so should not be performed for patients with the physiological reserve to tolerate definitive repair.


## Haemodynamic Goals

* Penetrating trauma
	* Maintain cerebration
	* Central pulses
	* SBP >60mmHg
* Blunt trauma
	* Maintain radial pulse
	* SBP >80mmHg
* Head injury
	* Maintain temporal pulse
	* SBP >100mmHg
* Spinal cord injury
	* Avoid SBP ⩽90mmHg
	* Aim MAP 85-90mmHg


## Phases of Care

Damage control surgery can be divided into **five phases**:

* Pre-surgery damage control
* Damage control surgery\
* ICU resuscitation
* Definitive repair
* Reconstructive surgery


### Pre-surgery Damage Control

Prehospital:

* Perform life-saving maneuvers\
Necessity varies depending on:
	* Degree of injury
	* Transportation time
	* Provider skill
* Expedite transfer to definitive care


Emergency Department:

* Rapid assess extent of injury and physiological derangement
* Commence damage control resuscitation

:::column-margin
Damage Control Resuscitation is covered under @sec-trauma_primary.
:::

### Damage Control Surgery

:::tick
Operative time should be **⩽90 minutes** to avoid exacerbating physiological derangement.
:::

Principles:

* Arrest haemorrhage
* Limit contamination
	* GIT injury
* Maintain flow to vital organs and extremities
	* Consider use of temporary shunts
* Avoid prolonged operating time, leading to further blood loss and physiological derangement


Methods:

* Damage control laparotomy
	* Open abdomen and pack all four quadrants\
		* Most significant bleeding packed first
		* Packs are then removed in reverse order, and bleeding and contamination in each quadrant is addressed in turn
	* Control haemorrhage
		* Resect severely damaged non-essential organs
		* Pack severely damaged essential organs
		* Ligate or shunt transected intraabdominal vessels
	* Control contamination\
		* Seal or resect perforated hollow viscera
		* Avoid reanastomosis
	* Temporary abdominal closure\
	Consideration of open abdomen to prevent abdominal compartment syndrome.
* Extremities
	* External fixation devices\
	Useful to avoid prolonged operative internal fixation or with contaminated wounds.
	* Vascular shunting\
	Temporary shunts to maintain flow, rather than ligation or definitive revascularization.
	* Fasciotomy


### ICU Resuscitation

:::priority
Goal is to **normalise physiology**.
:::

Methods:

* Continue fluid resuscitation
* Correct hypothermia
* Correct coagulopathy
* Obtain further imaging to define full extent of injuries


### Definitive Repair

:::info
Usually begins 24-48 hours after initial injury.
:::

Definitive repair of previously temporised injuries, including:

* Removal of packs
* Anastomosis or externalisation of discontinued bowel
* Removal of vascular shunts and definitive vascular repair
* Closure of abdominal and soft tissue defects


### Reconstructive Surgery

Surgery to restore premorbid form and function, e.g.:

* Cranioplasty
* Closure of large abdominal wall defects


---

## References

1. Cap AP, Pidcoke HF, Spinella P, et al. Damage Control Resuscitation. Mil Med. 2018;183(suppl_2):36-43. doi:10.1093/milmed/usy112
2. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.