# Achondroplasia


Skeletal dysplasia occurring (usually) due to spontaneous mutation of fibroblast growth factor, leading to premature ossification of epiphyseal growth plates and growth restriction. Affects include:

* Airway and spine deformities
* Variably affected organ function
* Normal intelligence and life expectancy

## Epidemiology and Risk Factors

Achondroplasia is the most common cause of dwarfism, with an incidence of ~1/10:000 live births


## Pathophysiology

### Aetiology

## Clinical Manifestations

## Diagnostic Approach and DDx

## Investigations

## Management

### Medical

### Surgical

### Anaesthetic Considerations

* A
	* AFOI is the preferred method of intubation
	* May be difficult mask ventilation and intubation
		* Narrowed nasal passages
		* Tracheal stenosis
		* Maxillary hypoplasia
		* Pharyngeal and laryngeal thickening
		* Short neck
		* Stiff TMJ
	* C-spine at risk  
	Avoid hyperextension due to:
		* Foramen magnum stenosis
		* Cervical instability
* B
	* Central sleep apnoea  
	Medullary compression.
	* Restrictive lung disease
* C
	* Pulmonary hypertension secondary to lung disease
* D
	* Anxiety
	* Spinal cord abnormalities
		* Kyphoscoliosis
		* Spinal canal stenosis
		* Engorged epidural veins
	* Neuraxial anaesthesia difficult and relatively contraindicated  
		* Increased incidence of epidural failure, including:
			* Unrecognised dural puncture  
			Due to absence of CSF flow from stenosed canal.
			* Difficult to feed catheters
			* Patchy block
* E
	* Difficult IV access
	* Significantly increased obesity rate

### Obstetric Considerations

Major issues:

* Restrictive lung disease
* High rate of elective caesarian section  
Due to rate of cephalopelvic disproportion. 

### Ineffective Therapies

## Complications

## Prognosis

## Key Studies


---

## References

