# Down's Syndrome


Genetic disorder due to trisomy 21, associated with:

* Physical growth delays
* Intellectual disability
* Characteristic facies
* Other organ system impairment

## Epidemiology and Risk Factors

Down's syndrome is:

* The most common chromosomal disorder  
~1/700 live births.


Risk factors:

* Maternal age  
	* 1/1400 at 25
	* 1/46 at 45
* Previously affected child

## Pathophysiology

### Aetiology

Predominantly due to trisomy 21. Remainder are:

* Chromosomal translocation  
~4% of cases.
* Mosaic trisomy 21  
~1% of cases.

## Clinical Manifestations

### History

### Examination

Characteristic facies:

* Brachycephaly  
Disproportionately wide head.
* Third fontanelle
* Flat nasal bridge
* Epicanthic folds  
Skin fold covering medial canthus.
* Upwardly slanting palepbral fissues
* Small mouth
* Small ears
* Single palmar crease  
Occurs in 50%.

* Often low birth weight in infancy, with obesity in adulthood

## Diagnostic Approach and DDx

## Investigations

## Management

### Anaesthetic Considerations

* A
	* Airway difficulty  
	Despite the below changes, muscular hypotonia makes laryngoscopy generally straightfoward.
		* Macroglossia
		* Micrognathia
		* Midface hypoplasia
		* Short neck
		* Tonsillar hypertrophy
	* Atlanto-axial instability  
		* Cord compression symptoms may develop post-operatively in previously asymptomatic individuals
		* Asymptomatic in 10-20%
		* Symptomatic in 1.5%
	* Subglottic stenosis  
	In ~5%. Use smaller ETT than expected for age.
	* Recurrent RTIs  
	Due to immune deficiency.
* B
	* High incidence of post-operatively respiratory complications
	* Impaired central respiratory drive
	* Chronic lower respiratory tract infections are common
		* Impaired immunity
		* GORD
		* Hypotonia
	* OSA  
		* Due to craniofacial abnormalities  
		* Present in 50-75%
* C
	* **Bradycardia** common and significant with anaesthetic agents  
	Have atropine available.
	* Strong association with congenital heart disease  
	In ~60%.
		* Common abnormalities
			* ASD
			* VSD
			* PDA
			* TOF
		* Pulmonary HTN develops earlier and more severely than non-DS patients
* D
	* Intellectual impairment  
	Mean IQ ~50 in adulthood.
	* Agitation  
	Post-operatively.
	* Epilepsy  
	In ~10%.
* E
	* Generalised hypotonia
* G
	* GORD
* H
	* Prone to polycythaemia
	* Higher incidence of leukaemias
* I
	* Immune dysfunction  
	General abnormalities in T cell, B cell, gamma globulins, and neutrophil function.


### Marginal and Ineffective Therapies

## Complications

## Prognosis

Mortality:

* Life expectancy generally good in developed world
* ~20% die in first year of life
* 45% survive until 60


## Key Studies


---

## References

1. Allt, Jules E, and Charlotte J Howell. ‘Down’s Syndrome’. BJA CEPD Reviews 3, no. 3 (June 2003): 83–86. https://doi.org/10.1093/bjacepd/mkg083.
