# Mitochondrial Disease


Heterogenous group of (hundreds of) genetic and environmental enzymatic mitochondrial defects. 

Two major categories of defects:

* Respiratory chain\
Five complexes in this chain, at least one of which is affected by most anaesthetic agents.
* Fatty acid metabolism\
	* No affect on volatiles
	* Some types may alter local anaestheic toxicity thresholds


## Epidemiology and Risk Factors

Prevalance is estimated 1:8,500.

Disease (and inheritance) may occur:

* De novo\
Spontaneous mutation (usually deletion) in mitochondrial DNA.
* Mitochondrial DNA defect
	* Transmitted only by maternal inheritence\
	Mother of affected patient will usually have detectable levels of the mutation.
	* Amount of affected mitochondria transmitted to the child is highly variable\
		* Significant clinical variability in presentation, even amongst siblings in the same family
* Nuclear gene defect\
May be autosomal dominant or recessive.

## Pathophysiology

Mutation of genes either in nuclear DNA or in mitochondrial DNA.

Manifestations may be:

* Single-organ\
e.g. Leber hereditary optic neuropathy.
* Multi-organ\
Generally greatest effect on body systems with the highest metabolic requirements:
	* CNS
	* Cardiac
	* GI tract
	* Musculoskeletal

## Clinical Manifestations

Clinical presentation:

* May fall into a discrete syndrome
* Can be highly variable\
Some common features include:
	* Cardiac effects:
		* Cardiomyopathy
	* CNS effects:
		* Seizures
		* Dementia
		* Migraine
		* Ataxia
		* Spasticity
		* Optic atrophy
		* Pigment retinopathy
		* Sensorineural deafness
		* External opthalmoplegia
	* MSK effects:
		* Ptosis
		* Proximal myopathy
		* Exercise intolerance
	* Metabolic effects
		* DM
		* Lactic acidosis


## Diagnostic Approach and DDx

## Investigations

Dependent on presentation:

* Consistent with a defined mitochondrial disorder\
Specific mitochondrial DNA testing, usually on blood.
* Not consistent with any particular disorder\
Testing includes:
	* Blood lactate
	* CSF lactate
	* Neuroimaging
	* Molecular genetic testing


## Management

Medical therapy depends on underlying deficiency. General principles:

* Supportive\
Treatment of other system manifestations (e.g. epilepsy).
* Supplementation
	* Vitamins
	* Coenzyme Q
	* L-Carnitine

### Anaesthetic Considerations

Most patients do well, although there may be an ↑ risk of perioperative complications including organ damage and death.
* A
	* Airway obstruction\
	Secondary to hypotonia.
* B
	* Respiratory failure
		* Pre-existing muscle weakness
		* Worsened by anaesthetic drugs
	* Post-operative monitoring for return of respiratory function
* C
	* Conduction abnormalities
	* Reduced contractility
* D
	* Anaesthetic technique
		* General anaesthesia usually required
		* Brief anaesthetics usually safe
		* Hypersensitive to volatile anaesthesia\
			* Complex I in the respiraory chain is affected by all halogenated anaesthetic agents\
			* Safe provided titrated to anaesthetic depth. Mitochondrial function returns as agent is washed-out.
		* **Consider avoiding propofol for *maintenance***
			* Affects complexes I, II, IV: significant affect on electron transport chain function
			* Risk of propofol infusion syndrome may be ↑ with substantial doses
		* **Avoid bupivacaine**\
		Toxicity threshold lowered in carnitine-deficiency.
	* Use drugs which do not affect mitochondrial function
		* Opioids (*except* morphine)
		* NSAIDs
		* Benzodiazepines
		* Ketamine
		* Dexmedetomidine
* E
	* Optimise temperature control\
	Minimise shivering.
* F
	* Avoidance of lactated solutions\
	Lactate metagbolism may be impaired.
	* Avoid dextrose solutions for patients on ketogenic diets
* G
	* Dysphagia
	* GORD
	* Avoid prolonged fasting\
		* Exacerbates metabolic burden\
		Fatty acid metabolism may be impaired.
		* Aim first on list


### Marginal and Ineffective Therapies

## Complications

## Prognosis

## Key Studies


---

## References

1. Hsieh VC, Krane EJ, Morgan PG. [Mitochondrial Disease and Anesthesia](http://med.stanford.edu/content/dam/sm/pedsanesthesia/documents/mitochondrial-disease.pdf). Journal of Inborn Errors of Metabolism and Screening. 2017 Jan;5:232640981770777. 
2. Chinnery PF. [Mitochondrial Disorders Overview](https://www.ncbi.nlm.nih.gov/books/NBK1224/). In: Adam MP, Ardinger HH, Pagon RA, Wallace SE, Bean LJ, Stephens K, et al., editors. GeneReviews® [Internet]. Seattle (WA): University of Washington, Seattle; 1993 [cited 2019 Jun 16]. Available from: http://www.ncbi.nlm.nih.gov/books/NBK1224/
