# Mucopolysaccharidosis


Rare inherited liposomal storage conditions:

* Where the body is unable to effectively breakdown mucopolysaccharides  
Causes buildup of these sugar molecules in tissues.
* Classified by age at presentation and enzymatic deficiency into seven forms



## Epidemiology and Risk Factors

## Pathophysiology

Genetic diseases with:

* Variable inheritance patterns including:
	* Autosomal recessive  
	Majority.
	* X-linked recessive
* Deficiencies in lysosomal enzymes involve in metabolism of mucopolysaccharides
* Accumulation of mucopolysaccharides in organs leads to dysfunction of that organ

## Clinical Manifestations

In general:

* Asymptomatic at birth
* Initial period of normal development
* Decline in mental and physical function

Four broad categories of clinical appearance:

* Soft tissue storage and skeletal disease without brain disease  
MPS I, II, VII.
* Soft tissue and skeletal disease  
MPS VI.
* Primarily skeletal disease  
MPS IVa, IVb.
* Primarily CNS disease  
MPS IIIa-d.



## Diagnostic Approach and DDx

## Investigations

## Management

Primarily supportive.

Therapeutic interventions include:

* Bone marrow transplant  
May:
	* Reduce hepatosplenomegaly
	* Improve myocardial function
	* Improve respiratory function
	* Stabilise mental regression

### Anaesthetic Considerations

* A
	* Facial and airway distortion
		* Difficult face mask ventilation  
		7-14%.
		* Difficult tracheal intubation  
		28-44%.
	* Atlanto-axial instability
	* Excessive secretions
* B
	* OSA
	* Obstructive/restrictive lung disease
	* Frequent infections
* C
	* Cardiomyopathy
	* Valvular disease
	* Coronary disease
	* Pulmonary hypertension
* D
	* Developmental delay
	* Communicating hydrocephalus
* E
	* Skeletal dysplasia
		* Pectus carinatum
		* Scoliosis
	* Spinal cord compression
* G
	* Hepatosplenomegaly

### Ineffective Therapies

## Complications

## Prognosis

Grim, with:

* Death in early childhood
	* Pulmonary infection
	* Pulmonary hypertension
	* Cardiomyopathy

## Key Studies


---

## References

1. Clark BM, Sprung J, Weingarten TN, Warner ME. Anesthesia for patients with mucopolysaccharidoses: Comprehensive review of the literature with emphasis on airway management. Bosn J Basic Med Sci. 2018;18(1):1-7. doi:10.17305/bjbms.2017.2201
1. Sam JA, Baluch AR, Niaz RS, Lonadier L, Kaye AD. MUCOPOLYSACCHARIDOSES: ANESTHETIC CONSIDERATIONS AND CLINICAL MANIFESTATIONS. 2011:12.
