# Williams Syndrome


Developmental disorder characterised by:

* Intellectual disability\
Usually visual-spatial.
* Distinctive facies
* Cardiovascular abnormalities\
Including:
	* **Supravalvular aortic stenosis**\
	* Abnormalities of coronary artery implantation


## Epidemiology and Risk Factors

Prevalence of 1:~7,500.




## Pathophysiology

Genetic condition that is:

* Classified as autosomal dominant
* Involves deletion of 26-28 genes on chromosome 7
	* The ELN gene encodes tropoelastin, which is involved in vascular wall development

## Clinical Manifestations

Key characteristics:

* Distinctive facies
	* Broad forehead
	* Epicanthal folds
	* Short nose
	* Long philtrum
	* Wide mouth
	* Thick vermillion
	* Mandibular hypoplasia
* Developmental delay
* Hypotonia
* Hypercalcaemia\
Develops in infancy and resolves by ~4; unclear cause.
* Cardiac disease\
	* **Present in 80%**\
	40% will require procedural intervention.
	* Includes
		* Supravalvular AS\
		Non-compliant aorta narrows at the sinotubular junction, and ↑ AV leaflet degeneration. Severity usually remains stable in most patients.
		* Pulmonary artery stenosis\
		Often occurs with SVAS.




## Diagnostic Approach and DDx

## Investigations


ECG:

* LVH
* Long QT

TTE:

* Presence of AS
* Presence of PS

**Laboratory**:

* Cardiac MRI



## Management

### Anaesthetic Considerations

* A
	* Potentially difficult airway\
	Secondary to mandibular hypoplasia.
* C
	* Evaluate cardiac disease
		* Supravalvular AS
		* Coronary occlusion
	* 5-lead ECG
	* Defend coronary blood flow
		* Minimise NPO time\
		* Maintain volume state
		* Avoid fall in SVR/rise in PVR
* F
	* Hypercalcaemia\
	Testing recommended every 2 years.

### Marginal and Ineffective Therapies

## Complications

Include:

* Perioperative death\
Likely due to myocardial ischaemia.

## Prognosis

## Key Studies


---

## References

1. Genetics Home Reference. [Williams Syndrome](https://ghr.nlm.nih.gov/condition/williams-syndrome). National Library of Medicine. 2019.
2. Matisoff AJ, Olivieri L, Schwartz JM, Deutsch N. Risk assessment and anesthetic management of patients with Williams syndrome: a comprehensive review. Thomas M, ed. Paediatr Anaesth. 2015;25(12):1207-1215. doi:10.1111/pan.12775
