# Clipping of Intracranial Aneurysm

>Time: 3+ hours <br>
>Pain: Moderate <br>
>Position: Supine or head up, prone for posterior circulation lesions <br>
>Blood loss: May be substantial; G+H and crossmatch <br>
>Special Drugs

*This covers factors unique to clipping of intracranial aneurysms. Factors relating to craniotomies in general are covered [here](/anaesthesia/neuro/craniotomy.md).*


Clipping of an intracranial aneurysm involves placing a spring clip across the aneurysmal neck to occlude it. Clipping is performed under GA. Approaches include:

* TIVA\
May be preferred in cases with high ICP, using propofol and remifentanil.
* Volatile\
Sub-MAC with a remifentanil infusion.


## Considerations

* B
	* **No coughing or movement is tolerated**\
	Dissection of vasculature and aneurysm are delicate.
		* Deep opioid analgesia with remifentanil
		* Deep muscle relaxation (TOF of 0)
* C
	* Stable haemodynamics\
	Avoid alterations in aneurysm transmural pressure critical to prevent re-bleeding.
		* Usually target 140-160mmHg; discuss with surgeon
		* Hypo- and hypertension can be disastrous
	* Consider two IV access sites:\
		* One large volume line
		* One anaesthetic/remifentanil infusion line
	* Arterial line
	* Have a plan for:
		* Aneurysmal rupture
		* Management of temporary clipping
* D
	* ICP control
		* Optimise CO~2~
		* Head up
		* Sodium
		* Vent EVD if in situ and appropriate
	* Cerebroprotective strategies may be required if a temporary clip is placed over a major vessel\
	↑ BP gently to at least that of pre-operative BP.
	* Vasospasm prophylaxis
	* Avoid N~2~O

* E
	* Muscle relaxation\
	Not *technically* required if using remifentanil, but paralysis recommended given the extreme requirement for immobility.
		* Aim ToF = 0
		* Consider relaxant infusion\
		Cisatracurium reliable and will wear off adequately for extubation if ceased when skull replaced.

## Preparation

* Standard monitoring
* Awake arterial line
* Large venous access
* Consider CVC\
For aspiration of gas in case of air embolism in patients in seated position.


## Induction

* Haemodynamic stability is vital\
Avoid ⩽ 10% change in SBP.
	* Propofol and remifentanil standard in most institutions


## Intraoperative

Aneurysmal Rupture:

* Call for help
* Determine if the aneurysm is exposed or unexposed
* Goals:
	* Keep ICP low
	* Balance maintaining CPP vs. exacerbating haemorrhage\
		* Exposed aneurysm: Rapid reduction in BP to reduce bleeding to allow surgeon to clip quickly
		* Unexposed aneurysm: Induce a degree of hypotension
	* Requires urgent surgical control of source
	* **Reverse heparin** if in IR
* Induce hypotension to reduce haemorrhage\
	* Target:
		* SBP ⩽100mmHg if in IR
		* Aim SBP 60-80mmHg or adequate reduction of haemorrhage if in OT
	* Strategies\
	Multiple options; will depend on severity of haemorrhage and what is currently running/drawn up/available. Some include:
		* Anaesthetic agents
			* Propofol\
			Immediately available and intimately familiar, but may not be enough.
			* Remifentanil bolus (e.g. 1ug/kg)\
			* Thiopentone\
			* Volatile
		* Cardiac agents
			* Adenosine
			* Labetalol 5-10mg
			* Esmolol
			* GTN\
			3-5mg/kg bolus, then 3-5mg/kg/hr, targeted to burst suppression.
		* Compress ipsilateral carotid artery to reduce bleeding
* Volume resuscitation
	* ↑ IVT rate
	* Begin transfusion
* Consider cerebroprotective strategies



Cerebroprotection:

* May be requested if placing temporary clip on a major vessel
* Goal is to maintain cerebral perfusion by collateral vessels
* Gentle elevation in BP desirable


### Surgical Stages

Haemodynamically critically points include:

* Induction
* Pins
* Incision
* Dural opening
* Haematoma removal
* Exposure and clipping
	* Dissection and exposure of aneurysm
	Delicate - **ensure immobility**.
	* Potential temporary clipping of vessels supplying aneurysm\
	↑ blood pressure to improve collateral circulation whilst temporary clip in situ.
		* ⩽15 minutes is well tolerated
		* ⩾30 minutes will have ischaemic injury
	* Clipping of aneurysm\
	Multiple clips may be applied.
	* Potential aspiration of aneurysm\
	To ensure that there is no further flow to the lesion.
* Extubation






## Postoperative

May require ICU care if:

* Complicated intraoperative course
* Vasospasm
* Poor grade SAH prior


---

## References
