# Carcinoid

Neuroendocrine tumour that:

* May occur from any neuroendocrine cell\
Found in many tissues; tumour incidence depends on neuroendocrine cell density. May arise in:
	* Lung\
	~25%. Technically only neuroendocrine tumours of the lung should be called carcinoid tumours.
	* GIT\
	Should be referred to as neuroendocrine tumour (NET). May occur in:
		* Small intestine\
		40%.
		* Rectum\
		27%.
		* Stomach\
		10%.
* Contain neuroendocrine cells and secrete biological amines
	* Serotonin\
	Most commonly.
	* Corticotrophin
	* Histamine
	* Dopamine
	* Substance P
	* Neurotensin
	* Prostaglandins
	* Kallikrein

 

## Epidemiology and Risk Factors

## Pathophysiology

Derived from neuroendocrine cells:

* Enterochromaffin cells
* Kulchitsky cells

* Frequency of occurrence related to neuroendocrine cell density


### Aetiology

## Clinical Features

:::info
* Many are asymptomatic and found incidentally due to long lead time to diagnosis
* Average time from diagnosis to symptoms is 8 years
:::

Presentation may be from **mass effect** or **carcinoid syndrome**, and varies depending on location:

* Pulmonary
	* Pneumonia
	* Cough
	* Haemoptysis
	* Chest pain
* Gastric
	* Zollinger-Ellison syndrome\
	Peptic ulcers occurring due to excessive acid production, in turn occurring due to a gastrin-producing tumour.
	* Atrophic gastritis
* Bowel
	* Mass effect
		* Obstruction
		* Abdominal pain


### Carcinoid Syndrome

Syndrome associated with secretion of vasoactive mediators from the tumour. Carcinoid syndrome is:

* Rare\
~10% of patients with carcinoid tumours.
* Unpredictable clinical effects\
Variable:
	* Secretion of (usually) histamine and serotonin
	* First-pass hepatic metabolism\
	Depending on location.
* Usually **intermittent** symptoms\
Associated with:
	* Exercise
	* Tyramine ingestion\
	Cheese, chocolate.
* Common symptoms:
	* Flushing (80%)
	* Diarrhoea (70%)
* Less common symptoms:
	* Lacrimation
	* Rhinorrhoea
	* Bronchospasm
	* Carcinoid heart disease


### Carcinoid Heart Disease

Characteristic cardiac lesions:

* Associated with high circulating 5-HT\
Rarely seen if 5-HIAA levels are ≤50mg/24 hours.
* Classically **right-sided endocardial thickening**:
	* Leads to retraction and fixation of valve leaflets
	* TR near-universal
	* TS, PR, and PS may occur
* Left sided disease may occur in the presence of an intracardiac shunt (e.g. PFO) that leads to serotonin entering left-sided chambers


### Carcinoid Crises

Exaggerated form of carcinoid syndrome that is:

* Potentially fatal
* Associated with medical intervention
* Characterised by:
	* Profound flushing
	* Bronchospasm
	* Tachycardia
	* Widely fluctuating BP\
* Requires octreotide to control haemodynamics\
0.5-1mg IV followed by infusion of 50-200μg/hr.


## Diagnostic Approach and DDx

## Investigations

Tumour activity:

* Blood
	* Plasma CgA
	* LFTs
	* Coags
	* UECs
	* S. Protein
* Urine
	* 24 hour 5-HIAA levels\
	Serotonin metabolite.


Tumour localisation:

* Octreotide scan
* Gallium PET/CT
* Echocardiography

## Management

### Medical

Premedication:

* Octreotide therapy
	* 100-500μg/day in divided doses
	* 30-60mg long-acting octreotide given IM every 4 weeks


### Surgical

### Anaesthetic Considerations

:::info
Surgery should proceed when:
	* Symptom control achieved
	* 2 weeks after last long-acting octreotide dose
:::

Premedication:

* Octreotide
	* Give usual dose of subcutaneous octreotide or 500μg (if untreated, or emergency) 2 hours pre-surgery
	* Commence infusion at 1μg/kg/hr in holding bay, prior to insertion of invasive monitoring
* Ranitidine 50mg IV/150mg PO 2 hours prior
* Promethazine 12.5mg IV/10-20mg PO 2 hours prior
* Ondansetron 4-8mg IV 2 hours prior
* Dexamethasone 2-4mg IV\
For gastric neuroendocrine tumours.


General:

* Disposition:
	* HDU post-operatively
		* Haemodynamic monitoring
		* Continuation of octreotide infusion
	* Endocrinology involvement
* B
	* **Perioperative bronchospasm**
		* Octreotide 10-200μg boluses
		* Antihistamine
		* Ipratropium nebuliser
		* Steroid
* C
	* ECG
	* TTE
	* Arterial line
	* CVC
	* Cardiac disease
		* **Carcinoid cardiac disease**
		* **Coronary spasm**
		* **Erratic BP**\
		Hypo- or hypertensive crises may:
			* Occur due to variation in hormone secretion
			* **Unresponsive** to **conventional vasoactives**
	* Haemodynamic goals
		* Deep, stable anaesthesia prior to resection
		* **Avoid**:
			* Morphine
			* Atracurium
			* Suxamethonium
		* Low CVP during resection
		* Avoid inotropes and vasopressors\
		Unpredictable and potentially **paradoxical** response.
			* Noradrenaline may release kallikrein from tumour, leading to vasodilation
			* Exaggerated hypertension also described
			* Vasopressin is appropriate to use as a vasopressor, if required.
			* Short-acting α-blockade ideal for managing persistent hypertension
	* **Perioperative hypotension**
		* Inform surgeon
		* Cease tumour handling
		* Octreotide bolus, 10-100μg
		* Phenylephrine 50-100μg bolus
		* Avoid indirect acting adrenergics
			* Cautious use acceptable for inotropy if on octreotide
		* Consider steroids, calcium, and vasopressin for unresponsive hypotension
	* **Perioperative hypertension**
		* ↑ depth of anaesthesia
		* Octreotide 10-200μg bolus
		* Labetalol, GTN, and esmolol if unresponsive
* D
	* Consider epidural if major abdominal surgery\
	Avoid loading until after tumour resection to avoid hypotension.
* E
	* **Octreotide** infusion\
	Used to limit vasoactive crises. Octreotide has many effects, however its key:
		* Mechanism of action is via:
			* Reducing splanchnic blood flow
			* Reducing secretion of vasoactive peptides
		* Adverse effects include:
			* Conduction defects
				* QT prolongation
				* Bradycardia
			* Abdominal cramps


### Marginal and Ineffective Therapies

## Complications

## Prognosis

Death:

* 70% 5 year survival

## Key Studies


---

## References

1. Powell B, Al Mukhtar A, Mills GH. [Carcinoid: the disease and its implications for anaesthesia](https://academic.oup.com/bjaed/article/11/1/9/285683). Continuing Education in Anaesthesia Critical Care & Pain. 2011;11(1):9-13.