# Lymphangitic Carcinomatosis

Progressive hypoxaemic respiratory failure due to inflammation and obstruction of pulmonary lymphatics secondary to infiltration of malignant cells.

:::column-margin
Lymphangitic carcinomatosis is distinct from (but related to) pulmonary tumour embolism, which occurs due to haematogenous embolism of tumour cells into pulmonary vasculature and leads to greater pulmonary hypertension and right heart failure.
:::

## Epidemiology and Risk Factors

## Pathophysiology

### Aetiology

## Assessment

Days to weeks history of:

* Progressive dyspnoea
* Pleuritic chest pain
* Cough
* Haemoptysis
* Weight loss
* Fever
* Tachypnoea



### History

Common primary malignancies include:

:::column-margin
Patients will usually have a diagnosed malignancy, although on rare occasions lymphangitic carcinomatosis may be the primary presentation.
:::

* Breast
* Lung
* Gastric
* Prostate
* Pancreatic
* Colon
* Cervical
* Uterine


### Examination


### Investigations

**Bedside**:

**Laboratory**:

**Imaging**:

* CXR\
Normal in 30-50% in early stages, however may demonstrate:
	* Interstitial oedema
	* Pleural effusions
* CT chest
	* Interstitial oedema
	* Thickening of interlobular septa
	* Preservation of lung architecture
* PET C
Highly sensitive.

**Other**:

### Diagnostic Approach and DDx


## Management

:::priority
* Treat underlying malignancy
* Oxygen
* Consider mechanical ventilation\
Depending on prognosis.
* Consider steroids
:::

**Resuscitation**:

**Specific therapy**:

* Pharmacological
* Procedural
* Physical

**Supportive care**:

**Disposition**:

**Preventative**:


### Marginal and Ineffective Therapies

## Anaesthetic Considerations

## Complications

## Prognosis

* Typically indicates end-stage malignancy, with survival estimates ~6 months

## Key Studies


---

## References
