# Myeloma

:::info
Myeloma is also known as multiple myeloma.
:::

Incurable malignancy of plasma cells in the bone marrow, leading to:

* Bone destruction
	* Bone pain
	* Fractures
	* Bone marrow failure
		* Cytopenia
		* Immunocompromise
* Monoclonal protein production

## Epidemiology and Risk Factors

## Pathophysiology

### Aetiology

## Clinical Features

Presentation:

* Bone pain
* Fractures
* Bone marrow failure
	* Anaemia
	* Immunocompromise

## Assessment

**History**:

**Exam**:

### Investigations

**Bedside**:

**Laboratory**:

**Imaging**:

**Other**:

### Diagnostic Approach and DDx


## Management

:::priority
Goals of management
:::

**Resuscitation**:

**Specific therapy**:

* Pharmacological
* Procedural
* Physical

**Supportive care**:

**Disposition**:

**Preventative**:


### Marginal and Ineffective Therapies

## Anaesthetic Considerations

## Complications

* F
	* Renal failure
		* Light chain deposition
		* Hypercalcaemia
		* Amyloidosis

## Prognosis

## Key Studies


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.