# Tumour Lysis Syndrome

Life-threatening metabolic syndrome that occurs due to **rapid destruction** of a **large number** of **tumour cells** leading to toxic changes in ECF composition, namely:

* **Hyperuricaemia**
	* Nephropathy\
	Due to uric acid deposition in the DCT.
* **Hyperkalaemia**
* **Hyperphosphataemia**
* **Hypocalcaemia**\
Due to phosphate precipitation.


## Epidemiology and Risk Factors

## Pathophysiology

Chemotherapy causes death of large number of tumour cells causes a release of cellular contents:

* Potassium\
The dominant intracellular cation.
* Phosphate
* Purines\
Metabolised to uric acid by metabolic pathways. Uric acid is:
	* Renally cleared by a saturatable pathway\
	Production of uric acid occurs much more rapidly than excretion, so in situations of purine excess a high amount of uric acid builds up.
	* Weakly soluble\
	Precipitates in fluids, namely:
		* Renal tubules
		* Joints

:::column-margin
Notably, primates are relatively unique in the animal kingdom in their inability to natively convert uric acid to the fairly harmless allantoin.
:::

### Aetiology

TLS occurs most commonly:

* In high-volume malignancies:
	* Bulky solid tumours
	* Haematological malignancies
* Following treatment
	* Chemotherapy
	* Radiotherapy

:::column-margin
TLS may occasionally occur in absence of chemotherapy.
:::

## Clinical Features

## Assessment

**History**:

**Exam**:


### Investigations

**Bedside**:

* ECG\
Hyperkalaemic changes.

**Laboratory**:

* Blood
	* UEC
		* AKI
		* Potassium
		* Calcium
		* Magnesium
	* LDH
	* Urate

**Imaging**:

**Other**:


### Diagnostic Approach and DDx

## Management

:::priority
* Prevent with **uric acid suppression**
* **Cease nephrotoxins**
* **Fluid** resuscitation
* Consider **urinary alkalinisation**
* **RRT** if refractory
:::

**Resuscitation**:

* C
	* Arrhythmia\
	Secondary to hyperkalaemia. Standard treatment applies.

**Specific therapy**:

* Pharmacological
	* Cease nephrotoxins
	* Urinary alkalinisation\
	Target serum HCO~3~^-^ >28mmol/L; aiming to prevent urate crystallisation.
* Procedural
	* RRT\
	May be required for hyperkalaemia or hyperphosphataemia.

**Supportive care**:

**Disposition**:

**Preventative**:

:::column-margin
The pathology of methaemoglobinaemia is covered under @sec-methb.
:::

* Intravenous hydration
* Uric acid suppression
	* **Rasburicase**\
	Recombinant enzyme that catalyses metabolism of uric acid to allantoin, preventing uric acid buildup.
		* May cause methaemoglobinaemia
		* 15% develop an antibody response to rasburicase
	* **Allopurinol**\
	↓ Uric acid formation by inhibiting xanthine oxidase.
		* Leads to formation of xanthine
		* Less preferred to rasburicase as xanthine is accumulated, which can itself cause renal failure
		* Ineffective once uric acid is already ↑

### Marginal and Ineffective Therapies

## Anaesthetic Considerations

## Complications

## Prognosis

## Key Studies


---

## References
