# Hyperlactataemia

Elevation in serum lactate >2mmol/L, which may be:

* Physiological
* Pathological


## Pathophysiology

Lactate is an organic acid produced:

* From pyruvate, via glucose and alanine
* In order to regenerate NAD^+^, which:
	* Allows further conversion from glucose into pyruvate
	* Facilitates ATP production in the absence of oxygen


Lactate occurs in two isomers:

* **L-lactate**\
	* Produced by multicellular organisms, including humans
		* At ~0.8mmol/kg/hr
			* Predominantly by skeletal muscle (~40%)
			* Also skin/brain/gut/RBC
	* Metabolised by:
		* **Liver**
		* Kidneys
		* Brain\
		Hypothesised as substrate for ATP generation, particularly when neuronal uptake of ATP is ↓ in brain injury.
* **D-lactate**
	* Normally produced by some colonic flora\
	Not usually significant, however overproduction can occur with:
		* Short bowel syndrome
		* Post-pancreatectomy
		* Colonic overgrowth
		* Malabsorbed carbohydrate loads
	* Leads to ↓ cellular ATP generation\
	D-lactate:
		* Competes with pyruvate and L-lactate for mitochondrial uptake
		* Metabolism is limited and tissue dependent\
		The liver is the only organ whose mitochondria are able to clear reasonable quantities.
		* Toxicity may be:
			* Neurotoxic
				* Confusion
				* Ataxia
				* Slurred speech
				* Obtundation → coma
			* Cardiotoxic
				* Arrhythmias
				* Heart block
	* Not detected by routine lactate testing\
	Blood gas or laboratory.


:::column-margin
An ↑ in brain lactate is associated with ↓ mortality.
:::

Lactate may be pathologically elevated by:

* ↑ Production
	* Tissue hypoxia (Type A)\
	Anaerobic metabolism.
	* Altered metabolism (Type B)\
	Catecholamines ↑↑ cellular ATP requirement and generation, ↑ lactate production even with normal cellular DO~2~.
* ↓ Clearance
	* Microvascular shunting
	* Hepatic dysfunction
	* Renal dysfunction


### Aetiology

Type A:

* Shock\
* **Mesenteric ischaemia**\
Although this is just localised ischaemia, it is important enough to be mentioned separately.
* ↓ O~2~ carriage
	* Hypoxia
	* Anaemia\
	Severe.
	* CO poisoning

Type B:

* Disease
	* Sepsis
	* Failures
		* Liver failure
		* Renal failure
	* Malignancy\
	↑ Anaerobic glycolysis, possible liver parenchymal destruction.
		* Phaeochromocytoma
		* Haematological
	* Thiamine deficiency
	* Diabetes
* Drugs
	* Catecholamines
		* Adrenaline
		* Salbutamol
	* Analgesics
		* Paracetamol
		* Salicylates
	* Energy sources\
		* Alcohols
			* Methanol
			* Ethanol
		* Sugars
			* Fructose
			* Sorbitol
	* Glycols
	* Metformin
	* SNP
* Inborn Error of Metabolism
	* G6PD


## Investigations

Bloods:

* Lactate\
This is by default L-lactate, which is the isomer produced by human metabolism. D-lactate is:
	* Not detected by standard assays
	* Produced by gut organisms
	* May be raised in:
		* Mesenteric ischaemia\
		Translocation through ischaemic bowel.
		* Short gut syndrome
		* Pancreatic insufficiency

## Management

:::caution
Treating an elevated lactate in isolation is unhelpful.\
\
An elevated lactate should prompt a search for evidence of systemic or regional malperfusion, and any underlying abnormality corrected to restore DO~2~.
:::

* Treat the primary disorder
* Correct acidosis\
Bicarbonate is reasonable if:
	* pH < 7.2
	* Disorder exacerbated by acidosis is present:
		* Pulmonary hypertension
		* Arrhythmia risk
		* High-dose vasoactives


## Prognosis

Hyperlactataemia is associated with:

* ↑ Mortality in sepsis/shock\
Level is proportional to mortality; >4 is highly significant.
* ↑ Mortality in severe cardiac disease\
Post-arrest, post-CABG, AMI, heart failure.


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.