# Metabolic Alkalosis {#sec-metalk}

Abnormal ↑ in plasma bicarbonate. Sustained metabolic alkalosis requires both a process for:

:::column-margin
A maintenance process is required because renal bicarbonate excretion is highly efficient, such that a transient alkali load (e.g. an IV bolus of bicarbonate) will result in a rapid ↑ in urinary bicarbonate excretion and restoration of normal plasma pH.\
\
This is the therapeutic mechanism behind urinary alkalinisation.
:::

* **Initiation**
	* Alkali gain
		* Exogenous\
		e.g. Bicarbonate, citrate, RRT.
		* Endogenous\
		e.g. Ketones.
	* Acid loss
		* Renal\
		e.g. Diuretics.
		* Gut\
		e.g. Vomiting.
* **Maintenance**
	* **Hypochloraemia**\
	Results in ↑ bicarbonate reabsorption despite alkalosis, in order to maintain electroneutrality.
	* Hypokalaemia\
	Less common and typically milder than chloride depletion.

## Aetiology

: Causes of Metabolic Alkalosis

+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+
| Acid Loss                                                                                                                                                           | Alkali Gain                                                                                                              |
+=====================================================================================================================================================================+==========================================================================================================================+
| **Urinary**:                                                                                                                                                        | **Exogenous**:                                                                                                           |
|                                                                                                                                                                     |                                                                                                                          |
| * **Diuretics**\                                                                                                                                                    | * **Iatrogenic**                                                                                                         |
| Loop and thiazide diuretics ↓ chloride reabsorption.                                                                                                                |     * Sodium bicarbonate                                                                                                 |
|     * Licorice (glycyrrhizin)                                                                                                                                       |     * β-lactams                                                                                                          |
| * **Chloride loss**\                                                                                                                                                |     * Sodium citrate\                                                                                                    |
| "Contraction alkalosis" occurs due to loss of chloride rather than volume, as HCO~3~^-^ secretion is inhibited by insufficient available Cl^- for anion exchange.   |         * Blood                                                                                                          |
| * **Mineralocorticoid effects**\                                                                                                                                    |         * RRT anticoagulation                                                                                            |
| ↑ Na^+^ reabsorption in exchange for K^+^ and H^+^.                                                                                                                 |     * High SID RRT                                                                                                       |
|     * Severe hypokalaemia                                                                                                                                           | * **Milk alkali syndrome**\                                                                                              |
|         * Hypomagnesaemia\                                                                                                                                          | Consumption of vast quantities of calcium and alkali, leading to alkalosis:                                              |
|         Magnesium is reabsorbed in exchange for potassium, which prolongs ↓ K^+^.                                                                                   |     * Directly\                                                                                                          |
|     * Corticosteroids                                                                                                                                               |     From the alkali.                                                                                                     |
|     * Cushing's syndrome                                                                                                                                            |     * Indirectly\                                                                                                        |
|     * Primary hyperaldosteronism                                                                                                                                    |     From the calcium, as the ↑ UO secondary to hypercalcaemia leads to hypovolaemia, ↓ GFR, and ↓ bicarbonate clearance. |
|     * Bartter's syndrome\                                                                                                                                           | * **Antacids**                                                                                                           |
|     Hyperplasia of the juxtaglomerular apparatus, ↑ renin and aldosterone secretion.                                                                                |                                                                                                                          |
|     Inhibits conversion of cortisol to cortisone, which has a mineralocorticoid effect.\                                                                            |                                                                                                                          |
| * **Gitelman syndrome**\                                                                                                                                            |                                                                                                                          |
| Autosomal recessive disease causing renal potassium and magnesium wasting.                                                                                          |                                                                                                                          |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+                                                                                                                          |
| **Enteric**:                                                                                                                                                        |                                                                                                                          |
|                                                                                                                                                                     |                                                                                                                          |
| * **Vomiting**                                                                                                                                                      |                                                                                                                          |
|     * Pyloric stenosis                                                                                                                                              |                                                                                                                          |
|     * NG suction                                                                                                                                                    |                                                                                                                          |
| * **Chloride loss**                                                                                                                                                 |                                                                                                                          |
| * **Laxative abuse**\                                                                                                                                               |                                                                                                                          |
| Diarrhoea causes substantial K^+^ loss; consequently renal K^+^ resorption is ↑ in exchange for NH~4~^+^.                                                           |                                                                                                                          |
| * **Villous adenoma**                                                                                                                                               |                                                                                                                          |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+

:::column-margin
Mineralocorticoid excess also ↑ HCO~3~^-^ loss equivalent to the ↑ H^+^ load.
:::

:::column-margin
Milk alkali syndrome is mostly a relic when of a bygone age, when milk and cream was cutting-edge therapy for peptic ulcers.
:::


## Pathophysiology

Adverse effects of metabolic acidosis include:

* B
	* Hypoventilation
		* Atelectasis
* C
	* Arrhythmias
	* ↓ Inotropy
* D
	* Vasospasm
	* Seizures
	* Confusion
	* Cramps
* F
	* Electrolyte derangements
* H
	* ↑ Hb oxygen affinity


## Management

Specific therapy:

:::column-margin
Normal saline has a number of mechanisms of action:

* Diluting ECF with a low SID fluid\
* Reversing volume depletion\
↓ Renal sodium reabsorption, which ↑ SID and causes contraction alkalosis.
* Provides chloride\
Reabsorbed in preference for bicarbonate, aiding renal bicarbonate elimination.
:::

* Pharmacological:
	* **Chloride volume resuscitation**
	* Correct **hypokalaemia**
	* Correct **hypoalbuminaemia**
	* **Acetazolamide**
* Physical
	* **RRT**

:::column-margin
Hydrochloric acid infusions are also described for metabolic alkalosis refractory to more pedestrian therapies.
:::

---

## References

1. Brandis, K. [Acid-base pHysilogy](http://www.anaesthesiamcq.com/AcidBaseBook/ABindex.php). 2015.
1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.
1. Medarov BI. Milk-Alkali Syndrome. Mayo Clinic Proceedings. 2009;84(3):261.
1. Luke RG, Galla JH. [It Is Chloride Depletion Alkalosis, Not Contraction Alkalosis](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3269186/). J Am Soc Nephrol. 2012;23(2):204-207. doi:10.1681/ASN.2011070720
