# Carotid Endarterectomy

>Airway: ETT or spontaneous ventilation. <br>
>Access: Large IVC, arterial line. <br>
>Pain: Minimal <br>
>Position: Supine, neck extended and rotated <br>
>Time: ~90 minutes total <br>
>Blood loss: 100-300ml <br>
>Special: Additional monitoring may include stump pressure monitor, cerebral perfusion monitor, or patient interaction with regional techniques <br>



Resection of ICA plaque to reduce the risk of embolic stroke in patients with ICA stenosis. Performed:

* To reduce risk of embolic stroke\
Indication (and risk) depends on degree of stenosis:
	* No risk at 100% occlusion
	* Symptomatic stenosis between 70-99%\
	Symptomatic if:
		* Focal neurological disease
		* Sudden onset
		* Appropriate distribution
	* Symptomatic moderate stenosis between 50-69%\
	Depends on patient factors.
	* Asymptomatic patient between 80-99%\
	Provided surgical risk of CVA is ⩽3%.
* Under GA or regional\
Broadly; no major difference provided technique is done well.
	* Regional:
		* Pros:
			* Best neurological monitoring
			* Reduces haematoma\
			Lower BP during closure and emergence.
			* Avoids risks of airway intervention
			* Lower shunt rate
		* Cons:
			* Surgeon comfort
			* Patient compliance
			* Risk of conversion to GA with limited access to head
			* Risks of siting blocks
			* Anxious patient and myocardial stress
	* GA:
		* Pros:
			* Immobility
			* Controlled ventilation
			* Attenuated stress response
		* Cons:
			* Limited neurological monitoring
			* Intraoperative hypotension
			* Delayed GA recovery may mask neurological complications

## Considerations

Get SET:

* Centre must have M&M of <6%\
Stroke risk of procedure must be substantially less than that of doing nothing.


* A
	* LMA may reduce carotid blood flow - consider using ETT.
	* Head is inaccessible during surgery
* C
	* Arterial line required
	* Co-existing CVS disease\
	Particularly HTN.
	* Plan for management of cross-clamping
		* Accurate measurement of normal BP\
		Measure in both arms, and target the highest intraoperatively.
	* Haemodynamic management
		* Impaired autoregulation after VA
		* Altered baroreceptor activity following carotid surgery
* D
	* Use of cerebral perfusion monitoring
		* **Regional techniques**\
		Deficits may present as:
			* Immediate unconsciousness upon clamping
			* Immediate subtle deficit
			* Delayed deficient\
			Typically related to hypoperfusion.
		* EEG monitoring
			* Commence prior to anaesthesia
			* Usually requires an electrophysiologist
			* Less affected by TIVA than volatile
			* Best predictor of cerebral ischaemia with low-stump pressure
		* SSEPs\
		Usually bilateral median nerve.
		* Transcranial doppler\
		Monitors both flow and **emboli**. Disadvantages:
			* Operator dependent
			* Placed near surgical site
		* Cerebral oximetry\
			* Monitors anterior circulation
			* Non-quantitative
		* Jugular venous bulb oximetry
		* Stump pressure\
		Transducing distal carotid stump as an indicator of efficacy of cerebral perfusion.
			* Less commonly performed now
			* Ischaemia is rare when stump pressure is **>40-50mmHg**
		* Regional CBF\
		Generally unavailable.
	* CVA recency\
	Reperfusion within **one month** of the original infarct may lead to haemorrhagic transformation of ischaemic brain.
		* Reasonable to perform surgery within 2 weeks if no specific contraindications
	* Regional technique\
	Involves:
		* Choice of anaesthesia\
		Usually combination of superficial and deep cervical plexus block, but may include:
			* Layered block\
			Local field block performed in each dissection plane by the surgeon.
				* Useful as a rescue for failed block
			* Cervical epidural\
			Rarely performed.
			* Superficial cervical plexus block
				* Does not provide muscular relaxation
			* Deep cervical plexus block
				* Provides muscle relaxation
				* Greater incidence of complications



## Preparation

* Standard ANZCA monitoring
* 5-lead ECG
* Arterial line\
Transduce at the level of the EAM.
* Bilateral blood pressure monitoring


## Induction

* Haemodynamically stable induction


## Intraoperative

Patient comfort in regional technique:

* Judicious conscious sedation\
Options include:
	* Propofol TCI
	* Midazolam
	* Clonidine\
	1μg/kg, then 1μg/kg/hr.
	* Dexmedetomidine
	3μg/kg/min for 10 minutes to give a load of 0.5μg/kg, then ↓ to 0.1μg/kg/hr (titrated to effect).
* Continual communication
* Use of a non-heated mattress
* Padding and support of all pressure areas
* Ensure bladder emptied
* Minimise IVT to prevent need to void
* Water to wet the lips appropriate, but drinking may precipitate choking/coughing/aspiration, and is to be avoided


Complications:

* Bradycardia
	* Usually due to carotid baroreceptor manipulation
	* Requires:
		* Cessation of surgical stimulation
		* Atropine\
		CPR may be required in profound bradycardia.
		* Surgical infiltration of local anaesthetic



### Surgical Stages

Can be divided into four stages:

* Exposure
	* Oblique neck incision
	* Division of common facial vein
	* Exposure of carotid artery
	* Control of common carotid, internal carotid, and external carotid
	* Administration of **heparin**\
	Usually 5000 units prior to clamping.
* Clamping	
Sequential clamping of internal, external, and common carotid arteries above and below the stenosis.
	* Clamping of internal carotid may significantly reduce cerebral perfusion
	* Aim MAP **greater than highest recorded awake level** during clamping\
	Consider **⩾20% above baseline** to reduce POCD.
	* Stimulation of **carotid baroreceptors** may lead to sudden haemodynamic instability\
	Anticipate sudden ↓ HR or ↓ BP.
	* Consider use of neuroprotective agents to achieve burst-suppression
	* **Evidence of impaired cerebral perfusion** should be managed surgically with **place**ment of a **shunt**
	* Note total clamping time on record
* Excision of atheroma
	* Longitudinal excision along carotid
	* Closure usually with patch\
	Reduces risk of re-stenosis.
* Emergence
	* Avoid hypertension during extubation
	* Deep extubation appropriate



### Post-Operative

Stroke:

* Major concern
* Neurology should be assessed early


Hypertension:

* Treat aggressively if **SBP >160mmHg**
	* Hydralazine
	* Labetalol
	* Phentolamine
	* **Avoid GTN**\
	Headache and cerebral vasodilation is undesirable.
* Multiple potential causes
	* Disruption of baroreceptors
	* Pain
	* Bladder distension


Hypotension:

* Disruption of baroreceptors


Neck haematoma:

* Occurs in ~3% of patients post-operatively
	* ↑ risk if poorly-controlled HTN
* May lead to obstruction to VR and subsequent lymphoedema
* May require emergency airway management


Vocal cord palsy:

* Vagal nerve/recurrent laryngeal nerve palsy\


Cerebral Hyperperfusion Syndrome:

* Occurs in 1-3% of carotid surgery\
Associated with:
	* HTN
	* ⩾80% stenosis
	* Previous CVA
* Occurs due to excessive flow through the now un-stenosed vessel
* Cause of most ICH post-CEA
* Presents as:
	* Headache
	* Focal seizures
	* Impaired conscious state
	* Up to 2 weeks post-operatively\
	May occur in theatre or in recovery.
* Unilateral cerebral oedema on CTB

---

## References

1. Stoneham MD, Stamou D, Mason J. Regional anaesthesia for carotid endarterectomy. Br J Anaesth. 2015 Mar 1;114(3):372–83. 
