# Endovascular Abdominal Aortic Aneurysm Repair (EVAR)



>Airway: 
>Access: 
>Pain: 
>Position:
>Time: 
>Blood loss:
>Special:

Endovascular repair of aorta using percutaneously inserted grafts. EVAR:

* Preferred approach in most patients provided the anatomy is favourable, as:
	* No laparotomy
	* No cross-clamp
	* Reduced perioperative morbidity and mortality
* May be:
	* Standard EVAR
	* Thoracic EVAR
	* Fenestrated EVAR
* Involves access via:
	* Femoral arteries\
	Standard EVAR.
		* Supine
		* May limit distal flow
	* Subclavian arteries\
	Required for complex grafting.


## Considerations

* B
	* Requirement for **breath-holding**\
	Major effect on anaesthetic plan; either:
		* GA & ETT
		* Light sedation and obeying commands\
			* May be difficult to maintain patient comfort in long procedures
			* Requires ability to lie flat
* C
	* Conversion to open \
	Incredibly rare.
* D
	* Anaesthetic technique
		* Local
		* Neuraxial
		* GA with ETT


## Preparation

## Induction

## Intraoperative

### Surgical Stages

## Emergence

## Postoperative

Complications include:

* C
	* Post-implantation syndrome\
	Early, self-limiting, postoperative occurrence of:
		* Fever
		* Leukocytosis
		* Raised inflammatory markers
	* Endograft collapse\
	Collapse of the endograft:
		* Usually occurs within 3 months
		* May present:
			* Asymptomatically
			* Abdominal pain
			* Multiorgan failure
			* Reduced femoral pulses
	* Endoleaks\
	Leakage of blood into aneurysm sac around graft.
		* Occurs in ~30% of patients
		* Classified into:
			* Type I\
			Incomplete seal. Requires repair.
			* Type II\
			Leakage of blood from collateral vessels. Requires repair.
			* Type III\
			Inadequate sealing of overlapping graft joints. Requires repair.
			* Type IV\
			Direct leakage through a porous graft. Historical curiosity of old grafts.
	* Major bleeding
	* Abdominal compartment syndrome\
	~15% of cases, more common if blood loss >5L.
	* MACE
* D
	* Spinal cord ischaemia\
	Related to spinal perforator injury. Management aimed at ↑ spinal perfusion pressure:
		* CSF drain to 10mmHg
		* ↑ MAP to 100mmHg or whatever resolves neurology
* F
	* AKI
* G
	* Mesenteric ischaemia

		

---

## References
