# Spinal Cord Protection


Paraplegia following descending aortic surgery:

* Occurs in 2-6% of patients\
* Due to occlusion of feeder vessels to the anterior and posterior spinal arteries
	* Anterior spinal artery and therefore motor function is at ↑ risk
	* Source vessels from the left subclavian and vertebral arteries
	* Anterior spinal arteries have additional supply:
		* Superiorly from the intercostal and lumbar segmental arteries, and the artery of Adamkiewicz\
		* Inferiorly from the mesenteric, internal iliac, and sacral arteries
* Occlusion may occur from:
	* Aortic cross-clamping
	* Destruction/occlusion of intercostal arteries
	* Embolisation
		* Air
		* Plaque
* Risk is related to:
	* Extent of aneurysm\
	⩾20% of aneurysm stented.
	* Less common with:
		* Infrarenal aneurysms\
		~0.25%.
		* Endovascular repair
* Continues despite major improvements in surgical technique
* May occur:
	* Immediately\
	Generally poor prognosis.
	* Delayed\
	Better prognosis. Manged with:
		* CSF pressure drained to 10mmHg
		* MAP ↑ to 100mmHg


## Mechanisms for Spinal Cord Protection

Consider:

* **Defend MAP** and spinal perfusion pressure\
Maintenance of spinal cord perfusion is crucial and is the **single most important factor**. Requires:
	* Maintain an adequate mean systemic filling pressure
	* ↓ CVP
	* Avoiding CSF pressure ↑
* **Lumbar drain**
	* Recommended in patients with high risk of ischaemia\
	Carries a spinal cord injury risk of ~1-3%. Discuss with the surgeon for:
		* Thoracic stents
		* Non-fenestrated stents
		* Open AAA
		* Previous aortic hardware
	* Reverses poor perfusion caused by spinal cord oedema
	* Also facilitates regional hypothermia of cord, if desired\
	Aim to cool at the watershed area of T8-L1.
	* Technical aspects:
		* Use an epidural kit to place a spinal drain
		* Optimise spinal perfusion pressure by draining CSF\
		Drain to **10mmHg**. Limit drainage to:
			* 20mL in first hour of surgery
			* 40mL in any four hour period
		* If nerve injury indicated on SSEPs or MEPs, drain 10ml of CSF and augment MAP
		* Leave in for 1-3 days post operatively
* **Hypothermia**\
May be:
	* Active\
	With CPB circuit.
	* Passive\
	Hypothermia of anaesthesia.
* **Partial CPB**
	* Bypass of left heart
	* Access cannula placed into the left atrium, with a return cannula into the femoral artery\
	Oxygenator can be used, but is not required.
	* Anterograde flow is provided to vessels distal to cross clamp
* **Nerve monitoring**\
	* Include:
		* SSEPs\
		Indicate dorsal column function by stimulating the posterior tibial nerve and recording cortical response.
		* MEPs\
		Indicate spinothalamic tract function by stimulating motor cortex.
			* Performed by:
				* Recording anterior tibial muscle response
				* Monitor hands as controls
	* Indicator of ischaemia
	* Allows surgical technique to be adapted
	* **Significant false positives**\
		* High specificity but poor sensitivity
		* Thresholds for intervention are not defined
* **Surgical techniques**\
Of controversial benefit, but include:
	* Intercostal artery reimplantation
	* Vessel preservation
	* Side-branch stenting


---

## References

1. Scott DA, Denton MJ. [Spinal cord protection in aortic endovascular surgery](https://academic.oup.com/bja/article/117/suppl_2/ii26/1744361). Br J Anaesth. 2016 Sep 1;117(suppl_2):ii26–31. 
