# Antifungals {#sec-antifungals}

Antifungal drugs occur in **three classes**:

* **Azoles**\
All have excellent oral bioavailability.
	* Generally fungicidal by inhibiting ergosterol synthesis in the cell wall\
	Fungistatic in some organism-dependent cases, notably aspergillus with voriconazole.
* **Echinocandins**\
All three agents are similar enough to be clinically interchangeable.
	* Inhibit β-glucan synthesis causing cell wall instability, which is:
		* Fungicidal for yeasts
		* Fungistatic for aspergillus
* **Polyenes**\
Essentially restricted to Amphotericin.
	* Fungicidal by binding to ergosterol

## Drugs

: Comparison of Antifungals

+---------------+------------------+----------------------------------------------------+--------------------------------------------------------------+---------------------------------------------------+
| Class         | Drug             | Indications                                        | Pharmacokinetics                                             | Toxicity                                          |
+===============+==================+====================================================+==============================================================+===================================================+
| Azoles        | **Fluconazole**  | * Yeasts\                                          | * Renal elimination unchanged                                | * ↑ QTc                                           |
|               |                  | Covers **most Candida** species.                   | * Dose ↓ 50% if GFR <50mL/min                                | * Hepatitis                                       |
|               |                  | * Excludes *C. glabrata* and *C. Krusei*           | * Dose ↑ in CRRT\                                            |                                                   |
|               |                  |                                                    | Usual renal tubular reabsorption does not occur.             |                                                   |
|               |                  |                                                    | * Extensive CYP interactions\                                |                                                   |
|               |                  |                                                    | e.g. Tacrolimus, warfarin, phenytoin.                        |                                                   |
+---------------+------------------+----------------------------------------------------+--------------------------------------------------------------+---------------------------------------------------+
|               | **Voriconazole** | * Invasive Aspergillosis                           | * IV contraindicated if GFR <50mL/min\                       | * Neurotoxicity\                                  |
|               |                  | * Fluconazole-resistant Candida                    | PO dosing safe and unchanged.                                | Delirium, myoclonus.                              |
|               |                  | * Endemic fungi\                                   | * Dose ↓ 50% in hepatic dysfunction                          | * Nephrotoxicity\                                 |
|               |                  | Coccidiomycosis, histoplasmosis, blastomycosis.    | * Extensive CYP interactions                                 | IV only.                                          |
|               |                  |                                                    |                                                              | * ↑ QTc                                           |
|               |                  |                                                    |                                                              | * Psychosis                                       |
+---------------+------------------+----------------------------------------------------+--------------------------------------------------------------+---------------------------------------------------+
| Echinocandins | **Caspofungin**  | * Candida\                                         | * No renal or hepatic dose reduction required                | * Avoid in acute hepatic failure\                 |
|               |                  | Resistance is rare; may occur with:                | * Very highly protein bound                                  | Results in deranged LFTs, confounding monitoring. |
|               |                  |     * *C. parapsilosis*                            |                                                              |                                                   |
|               |                  |     * *C. glabrata*                                |                                                              |                                                   |
|               |                  |     * *C. guilliermondii*                          |                                                              |                                                   |
|               |                  | * Aspergillus\                                     |                                                              |                                                   |
|               |                  | Not as monotherapy; synergistic with voriconazole. |                                                              |                                                   |
+---------------+------------------+----------------------------------------------------+--------------------------------------------------------------+---------------------------------------------------+
| Polyenes      | **Amphotericin** | * *Cryptococcus Neoformans*                        | * No hepatic impact\                                         | * Infusion reactions\                             |
|               |                  | * Dimorphic fungi\                                 | Major role in treating fungal infections in hepatic failure. | Atopic/immune symptoms.                           |
|               |                  | Change between yeast and mould form.               | * Contraindicated in renal failure                           | * AKI                                             |
|               |                  | * Moulds                                           |                                                              | * RTA                                             |
|               |                  | * Otherwise resistant fungi                        |                                                              |                                                   |
+---------------+------------------+----------------------------------------------------+--------------------------------------------------------------+---------------------------------------------------+

:::column-margin
Liposomal amphotericin has replaced other more toxic amphotericin preparations.
::: 



+------------------+-----------------------------------------------------------------------+--------------------------------------------------------------+
| Drug             | Echinocandins                                                         | Liposomal Amphotericin                                       |
+==================+=======================================================================+==============================================================+
| Dosing           | * Caspofungin\                                                        | * 3-5mg/kg IV Q24H                                           |
|                  | 70mg IV load, then 50mg IV daily.                                     |                                                              |
|                  |     * ↑ Dose if on strong enzyme inducer, e.g. phenytoin, rifampicin. |                                                              |
|                  | * Anidulafungin\                                                      |                                                              |
|                  | 200mg IV load, then 100mg IV daily.                                   |                                                              |
|                  | * Micafungin\                                                         |                                                              |
|                  | 100-150mg IV daily.                                                   |                                                              |
+------------------+-----------------------------------------------------------------------+--------------------------------------------------------------+
	

## Dosing

: Dosing of Antifungals

+------------------+----------------------------------------+--------------------------------------------------------------------------+
| Drug             | Indication                             | Dosing                                                                   |
+==================+========================================+==========================================================================+
| **Amphotericin** | * *Aspergillus*                        | 3-5mg/kg Q24H IV                                                         |
+------------------+----------------------------------------+--------------------------------------------------------------------------+
| **Fluconazole**  | * Mucocutaneous candidiasis            | CrCl >50: 200-400mg Q24H IV/PO                                           |
|                  |                                        +--------------------------------------------------------------------------+
|                  |                                        | CrCl ⩽50: 100-200mg Q24H IV/PO                                           |
|                  |                                        +--------------------------------------------------------------------------+
|                  |                                        | IHD: 200-400mg IV/PO post IHD                                            |
|                  |                                        +--------------------------------------------------------------------------+
|                  |                                        | CRRT: 800mg load then 400mg IV/PO daily                                  |
+------------------+----------------------------------------+--------------------------------------------------------------------------+
| **Fluconazole**  | * Candidaemia                          | CrCl >50: 800mg load then 400-800mg Q24H IV/PO                           |
|                  | * CNS infection                        +--------------------------------------------------------------------------+
|                  | * Endophthalmitis                      | CrCl ⩽50: 800mg load then 200-400mg Q24H IV/PO                           |
|                  | * Endocarditis                         +--------------------------------------------------------------------------+
|                  | * Susceptible dose dependent *Candida* | IHD: 800mg IV/PO post IHD                                                |
|                  |                                        +--------------------------------------------------------------------------+
|                  |                                        | CRRT: 800mg Q24H Q24H                                                    |
+------------------+----------------------------------------+--------------------------------------------------------------------------+
| **Voriconazole** | * *Aspergillus*                        | CrCl >50: 6mg/kg IV ×2 doses (load), then 4mg/kg IV Q12H                 |
|                  |                                        +--------------------------------------------------------------------------+
|                  |                                        | CrCl <50: Avoid IV due to risk of accumulation of cyclodextin excipient. |
+------------------+----------------------------------------+--------------------------------------------------------------------------+
| **Casofungin**   | * General infection                    | 70mg load then 50mg Q24H IV                                              |
|                  |                                        | 70mg daily if on CYP inducer (e.g. phenytoin, rifampicin)                |
+------------------+----------------------------------------+--------------------------------------------------------------------------+
| **Caspofungin**  | * Endocarditis                         | 150mg Q24H IV                                                            |
|                  | * Endovascular infection               |                                                                          |
+------------------+----------------------------------------+--------------------------------------------------------------------------+

:::column-margin
:::info
All CrCl values are given in mL/min.
:::
:::

---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.