# Antivirals {#sec-antivirals}

: Comparison of Antivirals

+-----------+------------------+----------------+
| Drug      | Pharmacokinetics | Considerations |
+===========+==================+================+
| Acyclovir |                  | * Use ABW      |
+-----------+------------------+----------------+

## Dosing

: Dosing of Antivirals

+--------------------+--------------------+---------------------------------------------------------+
| Drug               | Indication         | Dosing                                                  |
+====================+====================+=========================================================+
| **Acyclovir**      | * Prophylaxis      | CrCl ⩾10: 2mg/kg Q12H IV                                |
|                    |                    +---------------------------------------------------------+
|                    |                    | CrCl <10: 1mg/kg Q12H IV                                |
|                    |                    +---------------------------------------------------------+
|                    |                    | IHD: 1mg/kg Q24H IV                                     |
|                    |                    +---------------------------------------------------------+
|                    |                    | CRRT: 2mg/kg Q12H IV                                    |
+--------------------+--------------------+---------------------------------------------------------+
|                    | * HSV              | CrCl ⩾50: 5mg/kg Q8H IV                                 |
|                    | * VZV              |                                                         |
|                    | * CMV              | CrCl 50-25: 5mg/kg Q12H IV                              |
|                    |                    +---------------------------------------------------------+
|                    |                    | CrCl 25-10: 5mg/kg IV OD                                |
|                    |                    +---------------------------------------------------------+
|                    |                    | CrCl <10: 2.5mg/kg IV OD                                |
|                    |                    +---------------------------------------------------------+
|                    |                    | IHD: 2.5mg/kg IV OD                                     |
|                    |                    +---------------------------------------------------------+
|                    |                    | CRRT: 5-10mg/kg Q12H IV                                 |
+--------------------+--------------------+---------------------------------------------------------+
|                    | * Severe disease   | CrCl ⩾50: 10mg/kg Q8H IV                                |
|                    |     * CNS          +---------------------------------------------------------+
|                    |     * Disseminated | CrCl 50-25: 10mg/kg Q12H IV                             |
|                    |     * HSV          +---------------------------------------------------------+
|                    |                    | CrCl 25-10: 10mg/kg IV OD                               |
|                    |                    +---------------------------------------------------------+
|                    |                    | CrCl <10: 5mg/kg IV OD                                  |
|                    |                    +---------------------------------------------------------+
|                    |                    | IHD: 5mg/kg IV OD                                       |
|                    |                    +---------------------------------------------------------+
|                    |                    | CRRT: 10mg/kg Q12H IV                                   |
+--------------------+--------------------+---------------------------------------------------------+
| **Ganciclovir**    | * CMV induction    | CrCl >70: 5mg/kg Q12H IV                                |
|                    |                    +---------------------------------------------------------+
|                    |                    | CrCl 50-70: 2.5mg/kg Q12H IV                            |
|                    |                    +---------------------------------------------------------+
|                    |                    | CrCl 25-50: 2.5mg/kg Q24H IV                            |
|                    |                    +---------------------------------------------------------+
|                    |                    | CrCl 10-25: 1.25mg/kg Q24H IV                           |
|                    |                    +---------------------------------------------------------+
|                    |                    | CrCl <10: 1.25mg/kg 3×/week                             |
|                    |                    +---------------------------------------------------------+
|                    |                    | IHD: 1.25mg/kg IV post HD                               |
|                    |                    +---------------------------------------------------------+
|                    |                    | CRRT: 2.5mg/kg IV Q12-24H                               |
+--------------------+--------------------+---------------------------------------------------------+
| **Ganciclovir**    | * CMV maintenance  | CrCl >70: 5mg/kg Q24H IV                                |
|                    |                    +---------------------------------------------------------+
|                    |                    | CrCl 50-70: 2.5mg/kg Q24H IV                            |
|                    |                    +---------------------------------------------------------+
|                    |                    | CrCl 25-50: 1.25mg/kg Q24H IV                           |
|                    |                    +---------------------------------------------------------+
|                    |                    | CrCl 10-25: 0.625mg/kg Q24H IV                          |
|                    |                    +---------------------------------------------------------+
|                    |                    | CrCl <10: 0.625mg/kg 3×/week                            |
|                    |                    +---------------------------------------------------------+
|                    |                    | IHD: 0.625mg/kg IV post HD                              |
|                    |                    +---------------------------------------------------------+
|                    |                    | CRRT: 1.25-2.5mg/kg IV Q12-24H                          |
+--------------------+--------------------+---------------------------------------------------------+
| **Oseltamivir**    | * Prophylaxis      | CrCl >60: 75mg Q24H PO                                  |
|                    |                    +---------------------------------------------------------+
|                    |                    | CrCl 30-60: 30mg Q24H PO                                |
|                    |                    +---------------------------------------------------------+
|                    |                    | CrCl <30: 30mg Q48H PO                                  |
|                    |                    +---------------------------------------------------------+
|                    |                    | IHD: 30mg PO load, then 30mg PO post every *second* IHD |
|                    |                    +---------------------------------------------------------+
|                    |                    | CRRT: 75mg Q24H PO                                      |
+--------------------+--------------------+---------------------------------------------------------+
| **Oseltamivir**    | * Treatment        | CrCl >60: 75mg Q12H PO                                  |
|                    |                    +---------------------------------------------------------+
|                    |                    | CrCl 30-60: 30mg Q12H PO                                |
|                    |                    +---------------------------------------------------------+
|                    |                    | CrCl <30: 30mg Q24H PO                                  |
|                    |                    +---------------------------------------------------------+
|                    |                    | IHD: 30mg PO load, then 30mg PO post IHD                |
|                    |                    +---------------------------------------------------------+
|                    |                    | CRRT: 75mg Q12H PO                                      |
+--------------------+--------------------+---------------------------------------------------------+
| **Valacyclovir**   | * VZV              | CrCl >50: 1g Q8H PO                                     |
|                    |                    +---------------------------------------------------------+
|                    |                    | CrCl 30-50: 1g Q12H PO                                  |
|                    |                    +---------------------------------------------------------+
|                    |                    | CrCl 10-30: 1g Q24H PO                                  |
|                    |                    +---------------------------------------------------------+
|                    |                    | CrCl <10: 500mg Q24H PO                                 |
|                    |                    +---------------------------------------------------------+
|                    |                    | IHD: 500mg Q24H PO                                      |
+--------------------+--------------------+---------------------------------------------------------+
|                    | * Genital herpes   | CrCl >30: 1g Q12H PO                                    |
|                    |                    +---------------------------------------------------------+
|                    |                    | CrCl 10-30: 1g Q24H PO                                  |
|                    |                    +---------------------------------------------------------+
|                    |                    | CrCl <10: 500mg Q24H PO                                 |
|                    |                    +---------------------------------------------------------+
|                    |                    | IHD: 500mg Q24H PO                                      |
+--------------------+--------------------+---------------------------------------------------------+
| **Valgancyclovir** | * Induction\       | CrCl >60: 900mg Q12H PO                                 |
|                    | 14-21 days.        +---------------------------------------------------------+
|                    |                    | CrCl 40-60: 450mg Q12H PO                               |
|                    |                    +---------------------------------------------------------+
|                    |                    | CrCl 25-39: 450mg Q24H PO                               |
|                    |                    +---------------------------------------------------------+
|                    |                    | CrCl 10-24: 450mg Q48H PO                               |
|                    |                    +---------------------------------------------------------+
|                    |                    | CrCl <10: 200mg 3×/week PO                              |
|                    |                    +---------------------------------------------------------+
|                    |                    | IHD: 200mg PO post IHD                                  |
+--------------------+--------------------+---------------------------------------------------------+
| **Valgancyclovir** | * Maintenance      | CrCl >60: 900mg Q24H PO                                 |
|                    | * Prophylaxis      +---------------------------------------------------------+
|                    |                    | CrCl 40-60: 450mg Q24H PO                               |
|                    |                    +---------------------------------------------------------+
|                    |                    | CrCl 25-39: 450mg Q48H PO                               |
|                    |                    +---------------------------------------------------------+
|                    |                    | CrCl 10-24: 450mg 2×/week PO                            |
|                    |                    +---------------------------------------------------------+
|                    |                    | CrCl <10: 100mg 3×/week PO                              |
|                    |                    +---------------------------------------------------------+
|                    |                    | IHD: 100mg PO post IHD                                  |
+--------------------+--------------------+---------------------------------------------------------+

:::column-margin
:::info
All CrCl values are given in mL/min.
:::
:::

---

## References

1. Balfour HH. [Antiviral Drugs](https://www.nejm.org/doi/full/10.1056/NEJM199904223401608). New England Journal of Medicine. 1999 Apr 22;340(16):1255–68. 
