# Staff Exposure

Blood and body fluid exposure occurs when a healthcare staff member is exposed to patient fluid that could contain a potentially transmissible organism.

## Indications

## Contraindications

## Principles

## Management

Management:

1. Staff member to **abort procedure**/scrub out
2. **Clean site**
	* Wound\
		* Irrigate under running water for several minutes
		* Wash with soap and water
		* Apply aqueous betadine
	* Eyes
		* Remove contact lenses
		* Rinse with saline or water
	* Clothing
		* Remove
		* Shower if necessary
3. **Report** incident\
Risk management process.
4. Conduct **risk assessment**
	* Patient factors
		* Known blood-borne disease
		* High blood titre of blood-borne disease
		* Risk factors for blood-borne disease
	* Event factors
		* Hollow needle
		* Large needle
		* Intravascular needle
		* Gloves
			* None
			* Double
		* Depth of wound
		* Wound into vein or artery
		* High volume exposure
5. Perform **investigations**
	* Staff\
	For immunity.
	* Patient\
	For HIV, HBV, HCV.
6. Management
	* Consider need for post-exposure prophylaxis
		* Discuss with ID
		* Arrange counselling
		* Patient and staff followup
	* Post-exposure prophylaxis
		* Hepatitis B\
		IVIG.
		* HIV\
		**Antiretrovirals**, must be **commenced** within **2 hours**.
	* Barrier protection with intercourse for 6 months
	* No blood donation
	* Emotional support
	* Review procedural technique

:::column-margin
Policy for third-party consent or medical consent for testing patients without capacity is present in many institutions.
:::

## Complications


## Key Studies

---

## References
