# Principles of Antimicrobial Use

Key principles of antimicrobial use include:

:::column-margin
Empirical antibiotics are those given to cover *likely* organisms, rather than given in response to a known pathogen.
:::

:::column-margin
Inappropriate or delayed antibiotic use ↑ morbidity and mortality.
:::

* Sensible prescribing
* Appropriate sourcing and prescription of cultures
* Antimicrobial characteristics
	* Minimum inhibitory concentration
	* Kill characteristics
	* Post-antibiotic effect
* Treatment failure
* Dose adjustment

## Prescribing

Principles:

* Administer antibiotics **without delay**
* Choice of empirical antimicrobial should be based upon:
	* Site of infection
	* Community or hospital-acquired
	* Local microbiome\
	Understanding of the hospital or intensive care units antibiogram.
	* Patients previous microbiology results
* The narrowest-spectrum drug should be used\
Ideally empirical spectrum can be narrowed after **3 days**.
* Drugs eliminate susceptible organisms, at the cost of significant side-effects
	* Provide huge evolutionary advantage to resistant strains
	* Promote overgrowth of non-susceptible organisms
		* Including fungi
* Monotherapy is preferable to combination therapy\
Exceptions include:
	* Achieving adequate empiric cover
	* Treatment of polymicrobial infections with known sensitivities
	* Antibiotic synergy
		* Neutropaenic sepsis
		* Known bacteraemia
		* High (>25%) mortality
* Clinical response should be used to guide therapy\
	* *In vitro* sensitivity does not equate with clinical effectiveness
	* ***In vitro* resistance** is a **better predictor** than **sensitivity**
* A **>7 day course** is **rarely indicated**
	* Prolonged courses are associated with significant adverse effects
	* Exceptions include:
		* Immunosuppressed patients
		* Osteomyelitis
		* Infective endocarditis
		* Complicated bacteraemia\
		Require longer therapy and have ↑ mortality. Indicated by:
			* CNS involvement
			* Septic emboli
			* Multiple infected regions
			* Recurrent infection
* An adequate dose should be given\
Under-dosing leads to resistance.
* Serum levels of toxic antibiotics should be monitored for both toxicity and efficacy
* Recognise patients with **augmented renal clearance**, and ↑ dose accordingly

: Factors Influencing Antibiotic Choice

+---------------------+--------------------+--------------------------------------------------------------------------------+
| Category            | Factor             | Examples                                                                       |
+=====================+====================+================================================================================+
| **Patient**         | Age                | * Weight-based dosing                                                          |
|                     |                    |                                                                                |
|                     +--------------------+--------------------------------------------------------------------------------+
|                     | Allergies          | * Presence                                                                     |
|                     |                    | * Significance                                                                 |
|                     |                    |                                                                                |
|                     +--------------------+--------------------------------------------------------------------------------+
|                     | Metabolic function | * ↓ Renal clearance                                                            |
|                     |                    |     * Renal failure                                                            |
|                     |                    | * Augmented renal clearance                                                    |
|                     |                    |     * Dialysis                                                                 |
|                     |                    |     * Pregnancy                                                                |
|                     |                    |     * High CO state                                                            |
|                     |                    | * ↓ Hepatic clearance                                                          |
|                     |                    | * Altered clearance                                                            |
|                     |                    |     * Extracorporeal circuits                                                  |
|                     |                    |     * Plasma exchange                                                          |
|                     |                    |     * Haemoperfusion                                                           |
|                     +--------------------+--------------------------------------------------------------------------------+
|                     | Pregnancy          | * Teratogenesis\                                                               |
|                     |                    | Tetracyclines, chloramphenicol, sulfonamides.                                  |
|                     |                    | * Lactation                                                                    |
|                     |                    |                                                                                |
|                     +--------------------+--------------------------------------------------------------------------------+
|                     | Immunocompetence   | * Immunosuppression                                                            |
|                     |                    |     * Transplantation                                                          |
|                     |                    |     * Steroid use                                                              |
|                     |                    | * Vaccination status                                                           |
|                     |                    | * Asplenia                                                                     |
|                     |                    | * Chemotherapy                                                                 |
|                     |                    | * Radiotherapy                                                                 |
|                     |                    | * Malignancy                                                                   |
|                     |                    | * Malnutrition                                                                 |
|                     +--------------------+--------------------------------------------------------------------------------+
|                     | Genetic            | * G6PD\                                                                        |
|                     |                    | Nitrofurantoin, fluoroquinolones, cotrimoxazole, sulfamethoxazole, primaquine. |
+---------------------+--------------------+--------------------------------------------------------------------------------+
| **Epidemiological** | Travel             | * Regional geography                                                           |
|                     |                    | * Known outbreaks                                                              |
|                     |                    | * Seawater\                                                                    |
|                     |                    | *Vibrio vulnificus*.                                                           |
|                     +--------------------+--------------------------------------------------------------------------------+
|                     | Occupational       | * Abattoir workers\                                                            |
|                     |                    | *Coxiella burnetii*                                                            |
|                     |                    | * Cattle farmers\                                                              |
|                     |                    | *Brucella* sp.                                                                 |
|                     |                    |                                                                                |
|                     +--------------------+--------------------------------------------------------------------------------+
|                     | Recreational       | * IVDU                                                                         |
|                     |                    | * Pets                                                                         |
|                     |                    |     * Birds\                                                                   |
|                     |                    |     Psittacosis.                                                               |
|                     |                    |     * Cats\                                                                    |
|                     |                    |     Toxoplasmosis.                                                             |
|                     |                    | * Bushwalking\                                                                 |
|                     |                    | Tick-borne illnesses.                                                          |
|                     +--------------------+--------------------------------------------------------------------------------+
|                     | Therapeutic        | * Recent antimicrobial use                                                     |
|                     |                    | * Drug interactions                                                            |
+---------------------+--------------------+--------------------------------------------------------------------------------+
| **Disease**         | Clinical           | * Clinical urgency                                                             |
|                     |                    | * Differential diagnosis                                                       |
|                     |                    | * Likelihood of diagnosis                                                      |
|                     +--------------------+--------------------------------------------------------------------------------+
|                     | Infection          | * Source control                                                               |
|                     |                    |     * Controlled                                                               |
|                     |                    |     * Uncontrolled                                                             |
|                     |                    |     * Uncontrollable                                                           |
|                     |                    |     * Persistent bacteraemia                                                   |
|                     |                    | * Duration of therapy                                                          |
|                     |                    | * Clinical response to existing therapy                                        |
|                     +--------------------+--------------------------------------------------------------------------------+
|                     | Organism           | * Resistance patterns                                                          |
|                     |                    |     * Local antibiogram                                                        |
|                     |                    | * Life-cycle\                                                                  |
|                     |                    | Particularly for parasites, which may only be vulnerable at certain stages.    |
+---------------------+--------------------+--------------------------------------------------------------------------------+
| **Drug**            | Pragmatic          | * Cost                                                                         |
|                     |                    | * Availability                                                                 |
|                     |                    | * Available routes of administration                                           |
|                     +--------------------+--------------------------------------------------------------------------------+
|                     | Pharmacokinetics   | * Bioavailability                                                              |
|                     |                    | * Absorption                                                                   |
|                     |                    | * Penetration                                                                  |
|                     |                    |     * CSF                                                                      |
|                     |                    |     * Organ affinity                                                           |
|                     |                    |     * Organ aversion                                                           |
|                     |                    |                                                                                |
|                     +--------------------+--------------------------------------------------------------------------------+
|                     | Pharmacodynamic    | * Bactericidal vs. bacteriostatic                                              |
|                     |                    | * Synergism\                                                                   |
|                     |                    | TB.                                                                            |
+---------------------+--------------------+--------------------------------------------------------------------------------+

## Microbial Cultures

* Microbiological **specimens** should be obtained **before** commencing **antimicrobials**
	* Prevents false-negative cultures
	* Immediate Gram stain may guide therapy
* Interpretation of cultures depends on the site:
	* Sterile sites:
		* Include blood, urine, CSF
		* Cultured organisms are significant and indicate infection
		* Usually only one organism cultured, which is the causative organism
	* Non-sterile sites:
		* Usual commensal organisms are expected
		* Diagnosis of infection is clinical\
		Exception is cultured organisms that are definitively not commensal:
			* *Legionella*
			* TB
		* Microbiological results *guide* treatment
* Gram negative organisms become dominant with hospital admission
* The hallmark of an intravascular device infection (including CLABSI) is a continuous bacteraemia

:::column-margin
True bacteraemia (or fungaemia) should be assumed with culture of:

* *S. Aureus*
* *E. Coli*
* *Candida*
:::

:::column-margin
An antibiogram is a summary of the **local** antimicrobial susceptibilities of different pathogens, and is important to determine choices for antimicrobial agent for both empirical therapy, and prior to receiving sensitivity data.
:::


## Drug Properties

### Minimum Inhibitory Concentration

The MIC is the **lowest concentration** of antimicrobial that will **inhibit visible growth** of an organism after **overnight incubation**. The MIC is:

* Reported as μg/mL\
A lower MIC indicates ↑ efficacy.
* Easily performed\
Usually automated, and therefore reproducible
* Affected significantly by:
	* Incubation time\
	↑ MIC with ↑ time.
	* Concentration of bacteria in sample\
	↓ MIC with ↓ concentration.
* Not a perfect surrogate for *in vivo* efficacy
	* Other factors besides MIC determine antibiotic effect
	* Antibiotic tissue concentration (at site of disease) may be higher or lower than sampled serum concentration


### Kill Characteristics

Antibiotics can effect bacterial genocide in three broad ways:

* **Time-dependent** killing\
Efficacy dependent on the time that antibiotic concentration exceeds MIC, but not by how much.
	* Occurs when the drug only works at a particular point in the bacterial life cycle\
	e.g. Preparation for cell division.
	* Threshold effect\
		* Maximal effect reached at some proportion (usually 40-70%) of the dosing interval\
		Drug concentrations do not have to be continuously over MIC.
		* Affected by tissue penetration\
		Time over MIC is important only in the tissue where the infection is, which may not be in blood (where we measure concentrations).
	* Lend themselves to **dosing by infusion**
		* Benefits (at steady-state) include:
			* ↓ Mortality compared to intermittent dosing
			* ↑ Time above MIC, which should ↑ efficacy and ↓ 
			* ↓ Peak concentration, which generally ↓ toxicity
			* ↓ Nursing workload
		* Disadvantages include:
			* ↓ Concentration gradient driving diffusion into tissues
			* Most drugs are not *pure* time-dependent killers, and ↑ concentration still results in some ↑ efficacy
			* MIC is not known in early stages of treatment
			* Requires continuous use of a lumen
		* May ↓ ventilator days without clear evidence of mortality benefit, with greatest effect seen in the critically ill
	* Examples include:
		* β-lactam
		* Carbapenems
		* Linezolid
* **Concentration-dependent** killing\
Efficacy dependent on how much antibiotic concentration exceeds MIC, but not by how long for.
	* Occurs when drug affects some critical component of bacterial infrastructure\
	* Greater effect with greater dose
	* Examples include:
		* Aminoglycosides
		* Metronidazole
		* Fluoroquinolones
* **Time and concentration-dependent** killing\
Efficacy dependent on both time over MIC and concentration above MIC.
	* Occurs for drugs which prevent synthesis of components for cell division
		* ↑ Concentration results in ↑ inhibition of relevant components
		* ↑ Time results in affecting a greater number of bacteria\
		As they won't all divide at the same time.
	* Examples include:
		* Fluoroquinolones
		* Azithromycin
		* Glycopeptides


### Post-Antibiotic Effect

The post-antibiotic effect describes bacterial killing that persists after the concentration falls below MIC. Post-antibiotic effects:

* Are an idiosyncratic feature of some agents\
Usually where the drug binds strongly to some part of the bacteria.
* Are **strongest** generally **for** drugs with **concentration-dependent** killing


## Treatment Failure

Antibiotic treatment failure may occur due to:

* Wrong bug
	* Not susceptible
		* Viral
		* Fungal
		* Parasitic
	* Not infection
* Wrong drug
	* Resistant organism
	* Poor penetration to infected tissue
	* Bacteriostatic antagonism\
	Administration of a bacteriostatic antibiotic may ↓ efficacy of a bacteriocidal antibiotic, as cell division cannot be interrupted if it does not occur.
* Wrong dose
	* Too small
	* Too infrequent
	* Too short
* Wrong route
	* Inadequate oral absorption
* Source control
	* Incomplete surgical resection
	* Inadequate sputum clearance


## Dose Adjustment

: Pharmacokinetic Changes in Critical Illness

+---------------------------+------------------------------------+------------------------------------------------+
| Characteristic            | Increased With                     | Decreased With                                 |
+===========================+====================================+================================================+
| Peak Target Concentration | * ↓ Protein binding\               | * ↓ Gut absorption                             |
|                           | ↑ Free drug fraction.              | * ↑ V~D~\                                      |
|                           | * ↑ Penetration into target tissue | Oedema ↑ distribution of water-soluble agents. |
|                           |                                    | * ↓ Penetration                                |
+---------------------------+------------------------------------+------------------------------------------------+
| Half-life                 | * Renal dysfunction                | * RRT                                          |
|                           | * Hepatic dysfunction\             | * Enzyme induction                             |
|                           | Particularly sepsis.               |                                                |
|                           | * ↓ Metabolism                     |                                                |
+---------------------------+------------------------------------+------------------------------------------------+


### Renal Failure

Adjusting antibiotic administration in renal failure is to **avoid toxicity** as efficacy is unaffected by impaired renal clearance. Drugs may require:

:::column-margin
In general:

* **Interval**-adjustment:
	* Aminoglycosides
	* Fluoroquinolones
	* Glycopeptides
* **Dose *or* Interval** adjustment:\
For drugs not particularly toxic in overdose either can be chosen, although interval adjustment is cheaper.
	* Beta-lactams
	* Carbapenems
:::

* **Dose adjusted**
	* Best for *both*:
		* Time-dependent *killing*\
		Time above MIC determines efficacy, but amount above MIC doesn't.
		* Concentration-dependent *toxicity*\
	* Maintains time above MIC, with ↓ dosing to avoid progressively ↑ drug levels when amount given exceeds amount cleared
* **Interval adjusted**
	* Best for *both*:
		* Concentration-dependent *killing*\
		Peak concentration should be 8-10 times MIC, but the time above MIC doesn't effect efficacy.
		* Concentration-dependent *toxicity*
	* Maintains the high peak concentration required for killing, but minimises concentration at other times


### Renal Replacement Therapy

Dose adjustment on RRT is similar to renal failure. In general, drugs can require:

* **No adjustment**\
Administration is unchanged due to:
	* Small free drug fraction
		* High V~D~
		* Highly protein bound
	* Hepatically cleared
	* Cleared by filtration\
	CRRT replicates glomerular filtration reasonably well, but not other forms of renal clearance.
* **Interval adjustment**\
	* Actively transported drugs\
	Renal clearance by tubular secretion is not replicated by CRRT, and so interval adjustment needed to ↓ toxicity.
* **Dose adjustment**\
	* Renally reabsorbed drugs\
	Drugs that are usually reabsorbed by the tubule undergo **increased clearance** in the kidney, and therefore require ***↑ dose*** on RRT.


## Key Studies

{{< include /trials/fabled.qmd >}}
{{< include /trials/brett_abx.qmd >}}


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.
1. Cheng MP, Stenstrom R, Paquette K, et al. [Blood Culture Results Before and After Antimicrobial Administration in Patients With Severe Manifestations of Sepsis](https://www.acpjournals.org/doi/10.7326/M19-1696). Ann Intern Med. 2019;171(8):547-554. doi:10.7326/M19-1696