# Antimicrobial Resistance

Resistance is the complete or partial loss of response of an organism to a certain antimicrobial agent, and is particularly problematic for Gram negative bacteria which have developed a wide spectrum of resistance to many antibiotic classes. Resistance is classified into:

* Extensive resistance\
**Resistant** to **2 classes**.
* Multidrug resistance\
**Resistant** to **⩾3 classes**.
* Pan-resistant\
Resistant to all known agents.

:::column-margin
Broadly, resistance may occur by:

* Enzymatic inactivation of antimicrobial
* Change to antimicrobial binding site
* ↓ Antimicrobial uptake
* Altered metabolic pathway that obviates antimicrobial action
:::


## Mechanisms of Resistance

### Inducible β-lactamase

Group of **Gram-negative** organisms which:

* **Rapidly develop resistance** to β-lactam antibiotics
	* Due to **inducible β-lactamase**\
	Chromosomal-mediated cephalosporinase enzyme that is strongly selected for in the presence of β-lactam antibiotics.
	* May be inhibited by tazobactam, and so piperacillin/tazobactam may be effective
	* General require **treatment** with a **carbapenem**
* Should be **treated** with **non-β-lactam agents**, even if they initially appear sensitive
* Include the ESCHAPPM (or ESCAPPM) organisms:
	* ***E**nterobacter* spp.
	* ***S**erratia* spp.
	* ***C**itrobacter*
	* ***H**afnia* spp.
	* ***A**cinetobacter* and ***A**eromonas* spp.
	* ***P**roteus* spp.\
	Excluding *P. mirabilis*
	* ***P**rovidencia* spp.
	* ***M**organella morgani*


### Extended Spectrum β-lactamase

Describes organisms that develop a β-lactamase that also produces **resistance** to **other antibiotic classes**. The ESBL:

* Provides (variable) resistance to:
	* Third-generation cephalosporins\
	e.g. Ceftriaxone.
	* Fluoroquinolones
	* Aminoglycosides
* Producing organisms include:
	* Enterobacteriae:
		* *E. Coli*
		* *Klebsiella* spp.
		* *Enterobacter* spp.
		* *Serratia* spp.
		* *Proteus* spp.
	* *Citrobacter* spp.
* Can spread by **plasmid transmission**\
Bacteria share chromosomal coding for the β-lactamase between organisms, resulting in rapid ↑ resistance in a colony.


### Carbapenemases

Carbapenems are typically reserved for treating ESBL and AmpC producing organisms, and so carbapenemase-producing organisms are particularly problematic. Carbapenemases are divided into three groups by their **Ambler class**:

:::column-margin
Although many organisms may produce carbapenemases, carbapenemase-producing *Enterobacteriaceae* (CPE) are of significantly concern due to the native resistance of *Enterobacteriaceae* to many other classes of antibiotics.
:::

* **Class A**\
Most common form, which include:
	* *Klebsiella Pneumoniae* Carbapenemase (KPC)
	* Imipenem-hydrolysing beta-lactamase
* **Class B**\
	* Often found on plasmid vectors\
	Allows transmission of resistance between organisms.
	* Significant genetic variability limits testing accuracy
	* Include:
		* Metallo-beta-lactamase (NDM-1)
		* Imipenem-resistant *Pseudomonas*
		* Verona integron-encoded metallo-lactamase
* **Class D**\
	* Oxacillin-hydrolysing carbapenemase


Treatment:

* Often difficult due to complex resistance patterns
* Microbiology and infectious disease involvement recommended
* Prevention of transmission is critical:
	* Regular surveillance
	* Epidemiological assessment of detected cases
	* Contact precautions for all suspected or confirmed cases
* Possible antibiotics (often in combination) include:
	* Carbapenems
	* Polymyxins (colistin)
	* Aminoglycosides
	* Fosfomycin
	* Tigecycline


## Treatment of Multidrug Resistant Organisms

:::priority
* Determine **colonisation vs. infection**
* **Source control**
* Early specialist ID advice
:::

**Specific therapy**:

* Pharmacological
	* Antimicrobial therapy
		* ↑ Dose to overcome MIC
		* Novel (or very old) antibiotics
			* Ceftaroline
			* Ceftobiprole 
			* Colistin
			* Fosfomycin
			* Tigecycline
			* Aztreonam/Avibactam\
			For metallo-carbapenemases.
		* Combination therapy\
		Interaction of two antibiotics may overcome intrinsic resistance. Options include:
			* Add colistin
			* Add gentamicin
			* Use two drugs from the same class
* Procedural
	* Source control
* Physical

---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.
1. Smith HZ, Kendall B. [Carbapenem Resistant Enterobacteriaceae](http://www.ncbi.nlm.nih.gov/books/NBK551704/). In: StatPearls [Internet]. Treasure Island (FL): StatPearls Publishing; 2023 [cited 2023 Oct 1].
