# Anaesthetic Awareness


Accidental intraoperative awareness is the ability to recall any events which occurred during the period at which it was intended that the patient was unconscious. Awareness:

* Occurs in ~1:20,000 cases\
	* Incidence with NMB is ~1:8200 cases
	* Incidence without NMB is ~1:135,000
	* **Dynamic phase** of anaesthesia is the most common time\
	i.e. Induction and emergence.
* May lead to memory formation\
Memories may be:
	* Explicit\
	Memory of exact events, which may be:
		* Recalled spontaneously
		* Provoked by post-operative events or questioning
	* Implicit\
	Not consciously recalled events, but may affect later behaviour.
* May cause significant psychological harm
	* Insomnia
	* Depression
	* Anxiety
	* PTSD


## Risks

Key factors affecting risk of awareness include:

* **Depth of anaesthesia**\
	* Inspired agent concentration
		* Rare when MAC >0.8
		* Virtually non-existent when MAC >1\
		Once steady state has been reached.
	* Poor anaesthetic technique
		* Omission or late commencement of volatile
		* Underdosing of induction agent
		* Underdosing during hypotensive episodes\
		**Titration of anaesthetic agent to BP ↑ risk** of awareness.
		* Failure to recognise signs of light anaesthesia
* **Patient factors**\
↑ anaesthetic requirement in:
	* Young age
	* Hyperthyroidism
	* Obesity
	* Anxiety
	* Drug exposures
		* Smokers
		* Heavy alcohol
		* Recreational drug users
		* Repeated anaesthetics
* **Neuromuscular blockade**\
Greatly ↑ both the incidence and severity of awareness. Particularly:
	* Use of non-depolarising agents
	* Failure to monitor effect of non-depolarising agents
* **High risk surgery**\
Usually due to intentional dose reduction to minimise haemodynamic effects.
	* Cardiac surgery
	* Emergency surgery
	* Significant haemorrhage
	* Caesarian section
* **Equipment malfunction**


## Clinical Manifestations


>May be masked by β-blockers and anti-muscarinics, among other things

Relate to sympathetic activation:

* ↑ HR
* ↑ BP
* Sweating
* Crying
* Movement/grimacing
* Tachypnoea
* Pupillary dilatation and reactivity

## Management

Includes:

* Preventative
* Intraoperative management
* Post-operative management

### Preventative

* Premedication\
Use of benzodiazepines reduces incidence.
* Use of at least 0.8 MAC of volatile

### Intraoperative Management

* Use of processed EEG monitoring\
	* May ↓ awareness in high risk patients (NNT ~140)
	* Effect confounded by muscle relaxants
* Rapidly deepen anaesthesia
* If hypotension is present, support BP whilst deepening anaesthesia
* Consider administration of IV benzodiazepine\
Will not provide retrograde amnesia, but anterograde amnesia reduces evidence of further recall.


### Postoperative Management

Obtain and document a detailed account of the experience:\
* Perioperative timing
* Distinguish between dreaming and awareness
* Note details of recalled events\
* **The Brice Questionnaire** is a traditional approach to assessing events:
	* Performed twice
		* First at 24-48 hours
		* Second at 7-8 days
	* Consists of five questions:
		* What was the last thing you remembered happening before you went to sleep?
		* What is the first thing you remember on waking?
		* Did you dream, or have any other experience whilst you were asleep?
		* What was the worst thing about the operation?"
		* What was the next worst thing?


Provide:

* Support and sympathy\
Denial of veracity of events worsens psychological outcome.
* Early referral to psychiatric and counselling services



---

## References

1. Hardman JG, Aitkenhead AR. Awareness during anaesthesia. Contin Educ Anaesth Crit Care Pain. 2005 Dec 1;5(6):183–6. 
2. Pandit JJ, Andrade J, Bogod DG, Hitchman JM, Jonker WR, Lucas N, et al. 5th National Audit Project (NAP5) on accidental awareness during general anaesthesia: summary of main findings and risk factors. Br J Anaesth. 2014 Oct 1;113(4):549–59.
3. Brice DD, Hetherington RR, Utting JE. A Simple Study of Awareness and Dreaming During Anaesthesia. British Journal of Anaesthesia. 1970 Jun;42(6):535–42. 


