# Laparoscopy


Insufflation of abdominal cavity with CO~2</sub,> in order to facilitate intra-abdominal surgery.

## Physiology

Key changes:

* Respiratory
	* Limited diaphragmatic excursion
		* Elevated airway pressure
		* Decreased pulmonary compliance
		* Atelectasis
	* Increased PaCO~2~  
	Due to absorption of insufflated CO~2~.
* Cardiovascular  
Effects vary depending on intraabdominal pressure, and these changes will be exacerbated by changes in positioning altering venous return:
	* IAP ⩽10mmHg
		* Splanchnic compression and autotransfusion  
		Up to 40% reduction in mesenteric blood flow.
		* ↑ Preload, VR, and CO
	* IAP 10-20mmHg
		* IVC compression and ↓ preload
		* ↑ SVR
		* ↑ SVR exceeds ↓ preload; so BP is maintained
	* IAP >20mmHg
		* ↑ IVC compression and ↓↓ preload
		* ↑ SVR  
		Inotropes more effective than vasopressors in management of hypotension.
		* ↓ CO with ↓ in BP

## Benefits

Include:

* Reduced incision size
	* Improved post-operative pain
	* Decreased recovery time
	* Decreased post-operative infections


## Risks and Contraindications

Patient:

* Raised ICP  
Due to increased PaCO~2~.
* Severe hypovolaemia
* Right-to-left shunts  
Increased passage with raised venous pressures.


Surgical:

* Organ injury
	* Vascular
	* Bowel
	* Ureteric
	* Venous gas embolism
* Positioning
	* Movement
	* Cerebral oedema/hypoperfusion


Anaesthesia:

* Generally requires ETT  
LMA use controversial.
* Increased PONV

---

## References

1. Hayden P, Cowman S. Anaesthesia for laparoscopic surgery. Contin Educ Anaesth Crit Care Pain. 2011 Oct 1;11(5):177–80. 
