# Low-Flow Anaesthesia 


Low-flow anaesthesia:

* Requires a FGF less than the patients MV  
Therefore requires a rebreathing system and a CO<sub>2</sub> absorber.
* Typically uses FGF of 1L/min
* In absence of leak, flow can be reduced to the gas volume that a patient is absorbing and metabolising  
This has lead to:
	* Minimal-flow anaesthesia  
	Uses an even lower FGF of 0.5L/min; which in normal circumstances, this gives a rebreathing fraction of ~75-80%.
	* Metabolic-flow anaesthesia  
	Uses pure oxygen as a carrier gas, and replacing only the gas that is consumed by patient metabolism.

## Advantages of Low-Flow Anaesthesia

Benefits include:

* Clinical
	* Measurement of oxygen consumption  
	Can be estimated by comparing FGF requirements to circuit volume.
	* Increased humidification  
	Rebreathing increases humidity, decreasing mucociliary impairment.
	* Temperature  
	Rebreathing increaeses temperature of inspired gases, decreasing heat loss under anaesthesia. This can be substantial - up to 1°C in core body temperature after 1 hour of anaesthesia.
* Environmental  
Inhalational anaesthetic agents are potent greenhouse gases. Decreased FGF results in decreased volatile consumption, and therefore emission of inhalational agents.
* Economic  
Decreased use of inhalational agents decreases the cost of delivering anesthesia.


## Disadvantages of Low-Flow Anaesthesia

Disadvantages include:

* Circuit gas composition does not correspond to FGF composition  
Change in circuit gas composition will depend on the time-constant of the circuit.
	* Remember that for an anaesthetic circuit $$\tau = {Circuit Volume \over FGF - Patient \ Gas \ Uptake}$$  
	A process will be 95% complete at the end of three time-constants.
		* At low flows, the time-constant for equilibration between the circuit and the FGF gas increases  
		Results in very slow equilibration between the circuit/patient and the delivered gas.
		* E.g., for a 5L circuit + FRC volume, increasing the FGF to 5L/min will see circuit gas composition approximate FGF composition in ~3 minutes
* Risk of hypoxia  
If oxygen consumption exceeds oxygen delivery:
	* Circuit volume will decrease  
	As the overall volume of gas has decreased.
	* Circuit mixture will become relatively hypoxic  
	Oxygen is consumed, however nitrogen and inhalational agent amounts remain constant; this results in a decreased FiO<sub>2</sub>.
* Increased soda-lime concentration  
As less CO<sub>2</sub> will be scavenged, soda-lime consumption will increase.
* Loss of circuit volume  
Indicated by decrease in minute ventilation, peak airway pressure, and collapse of the bellows or resevoir bag.
	* Increase FGF to overcome leak
	* Search for source of leak


### Contraindications to Low-Flow Anaesthesia

Contraindications include:

* Toxic gases  
Adequate FGF must be used to ensure washout of toxic gases.
* Smoke inhalation
	* Carbon monoxide
* Cyanide toxicity
* Malignant hyperthermia  
As volatile agents will be ceased, there is no benefit to low-flow techniques. Additionally, high FGF is required to ensure adequate washout of CO<sub>2</sub>. 
* Alcohol intoxication  
Prevents pulmonary clearance of gaseous alcohol.
* Acetone poisoning
	* Prolongs anaesthesia
	* Increases PONV
* Ketoacidosis  
In severe cases, may lead to accumulation of gaseous acetone in the circuit.


## Performing Low-Flow Anaesthesia

* Technical requirements
	* End-tidal gas measurement  
	As end-tidal agent concentration will differ markedly from delivered agent concentration, closed-loop monitoring must be used.
	* Free of circuit leaks


* Estimate VO<sub>2</sub>
	* VO<sub>2</sub> can be crudely measured using the Brody Formula: $$ VO_2 = 3.5 \times kg$$  
	This typically overestimates consumption by 10-20%, which introduces a margin of safety.
* Set an FiO2 alarm  
e.g. 30%.
* Deliver a volume of gas greater than the patients oxygen consumption  
At minimal-flows, it easier (and safter with respect to hypoxia) to use 100% oxygen as the carrier gas to prevent buildup of nitrogen and delivery of a hypoxic gas mixture; although over time this will cause FiO2 to steadily increase.
* Use an insoluble agent if possible  
Desflurane and sevoflurane are better agents for use with low-flow techniques due to their shorter time constants.


### Template for Low-Flow Anaesthesia with Oxygen and Air

* Standard Induction
* Initial Phase
	* FGF of 4L/min with 40% FiO<sub>2</sub>  
	3L/min air, 1L/min O<sub>2</sub>; will lead to an FiO<sub>2</sub> of 35-40%.
	* Vaporiser:
		* Sevoflurane 3.5%
		* Isoflurane 2.5%
		* Desflurane 6%
* At target MAC (0.8-1)
	* Decrease FGF to 0.5L/min with 68% FiO<sub>2</sub>  
	0.3L/min air, 0.2L/min O<sub>2</sub>.
	* Increase vaporiser:
		* Sevoflurane 5%
		* Isoflurane 5%
		* Desflurane 8%
* Adjusting
	* Rapid change in agent concentration:
		* Set vaporiser to 0.5-1% above target concentration
		* Increase FGF to 4L/min  

	* Slow increase in agent concentration:
		* Continue FGF at 0.5L/min
		* Increase vaporiser by 1-2% or higher
		* At target, leave vaporiser 0.5-1% higher than target
	* Slow decrease in agent concentration:
		* Continue FGF at 0.5L/min
		* Reduce vaporiser by 1-3.5%
		* At target, increase the vaporiser to its previous setting
* Reversal
	* Set vaporiser to 0% ~10 minutes prior to end of operation
	* Continue FGF at 0.5L/min
	* Begin spontaneous ventilation
	* At the last suture, purge system with 100% O<sub>2</sub> at 6L/min  
	Increasing the FGF above this does not appreciably decrease the time for washout, as at 6L/min rebreathing fraction is only ~2.5%.

### Template for Minimal-Flow Anaesthesia with Oxygen and Nitrous Oxide

* Standard induction
* Initial Phase
	* FGF of 4.4L/min with 32% FiO<sub>2</sub>  
	1.4L/min O<sub>2</sub> and 3L/min N<sub>2</sub>O; will lead to an FiO<sub>2</sub> of 30-40%.
	* Vaporiser:
		* Sevoflurane 2-2.5%
		* Isoflurane 1-1.5%
		* Desflurane 4-6%
* At target MAC (0.8-1)
	* Reduce FGF to 0.5L/min (0.3L/min O<sub>2</sub> and 0.2L/min N<sub>2</sub>O)
	* Increase vaporiser:
		* Sevoflurane 3-3.5%
		* Isoflurane 2.5%
		* Desflurane 5-7.5%
* Adjusting
	* Rapid change in agent concentration:
		* Set vaporiser to 0.5% above target concentration
		* Increase FGF to 4.4L/min
		* At target, reduce the FGF to 0.5 L/min
	* Slow increase in agent concentration
		* Continue FGF at 0.5L/min
		* Increase vaporiser by 1-2% or higher
		* At target, set vaporiser to 0.5-1% higher than target
	* Slow decrease in agent concentration
		* Continue FGF at 0.5L/min
		* Decrease vaporiser by 1-3.5%
		* At target, increase vaporiser to its previous setting
* Reversal
	* Set vaporiser to 0% ~10-15 minutes prior to end of operation
	* Continue FGF at 0.5L/min
	* Begin spontaneous ventilation
	* At the last suture, purge the system with 100% O<sub>2</sub> at 6L/min



---

## References

1. Hönemann C, Mierke B. [Low-flow, minimal-flow and metabolic-flow anaesthesia: Clinical techniques for use with rebreathing systems](https://www.draeger.com/Library/Content/low-minimal-flow-anaesthesie-bk-9067990-en-global.pdf). Drägerwerk AG & Co., Lübeck, Germany.