# Total Intravenous Anaesthesia


*The interpretation of BIS-processed EEG waveform is [covered elsewhere](/anaesthesia/general/eeg.md).*


TIVA describes provision of general anaesthesia solely by intravenous drugs (though some consider nitrous oxide to be a reasonable adjunct). TIVA can be delivered via:

* Target-Controlled Infusions  
Pumps programmed with pharmacokinetic models targeting a plasma or effect-site concentration of drug.
* Rate-Controlled Infusions  
A pump run at a standard ml/hr rate.

## Indications

Absolute:

* Trigger-free anaesthetic required
	* Malignant hyperthermia
	* Neuromuscular diseases  
	Volatile may precipitate hyperkalaemia.
* Long QT  
QTc >500ms.
* Tubeless ENT and thoracics
* High ICP
* Surgery requiring neuromuscular monitoring
* Transfer of anaesthetised patients

Relative:

* Severe PONV
* Difficult intubation or extubation
* Remote location
* Gas trapping/sleep apnoea  
Offset of anaesthesia decoupled from ventilation.

## Contraindications

Relative:

* Shock/cardiac dysfunction/complex anaesthesia
	* Requires more involvement
	* ↓ ability to measure and adjust values
* Propofol contraindication
	* Mitochondrial disease
	* Risk of propofol infusion syndrome
	* Allergy
* Lack of TCI pumps available

## Advantages

* A
	* Obtundation of airway reflexes  
	Airway surgery.
* B
	* Reduced airway reactivity  
	Smoother extubation and emergence.
		* Reduced respiratory adverse events in children
	* Potential preservation of hypoxic pulmonary vasoconstriction
	* Allows spontaneous ventilation when titrated
* C
	* Potentially greater haemodynamic stability
* D
	* Reduced ICP
	* ↓ incidence of PONV
	* ↓ incidence of emergence delirium
* Other
	* ↓ pollution
	* Cheaper
	* Benefit still exists even if converting from another anaesthetic modality (e.g. volatile)


## Disadvantages

* D
	* Potentially ↑ risk of awareness  
	Related to failure to apply the technique effectively, rather than failure of the technique itself.
		* Suggest use of **processed EEG monitoring** in patients with neuromuscular blockade
* E
	* Obesity  
	Models are not validated in obese patients, and the risk of awareness is ↑.
		* Marsh model is capped at 150kg
		* Schneider is capped at a BMI of 42 (men) or 35 (women)


## Principles

* Effect of:
	* Bolus doses of propofol are mostly determined by V~D~
	* Infusion rates are mostly determined by clearance

## TIVA Models

Many different pharmacokinetic models exist:

* Propofol  
All models perform well in practice, and any are reasonable. After 10 minutes they are peform similarly. Models include:
	* Manual infusion  
	Important role remains due to:
		* Ease of use
		* (Lack of) availability of TCI pumps in some institutions
		* Variability within and between TCI models
	* **Marsh**
		* Plasma site targeting
		* Requires:
			* Total body weight
			* Age  
			Not used in calculation.
		* Less haemodynamic stability/shorter induction time
	* **Modified Marsh**  
	Greater haemodynamic stability than Marsh.
	* **Schnider**
		* Effect-site target
		* Requires:
			* Age
			* Height  
			To calculate ideal body weight.
			* Total body weight
		* Administers less propofol than Marsh
		* Greater haemodynamic stability/Longer induction time
	* Paediatrics
		* Models not as refined as adults  
		Generally require larger initial bolus (greater V~1~) and infusion rate (↑ clearance)
		* Note highly variable propofol pharmacokinetics in neonates
		* Widely available models include:
			* **Paedfusor**  
			Requires:
				* Weight  
				5-61kg.
				* Age  
				1-16 years.
			* **Kataria**  
			Generally inferior to paedfusor.
* Remifentanil
	* Minto
		* Can be used in either plasma-site targeting or effect-site targeting  
		Effect-site gives greater speed of induction but ↑ risk of chest-wall rigidity or severe bradycardia.


## A Framework for Delivering TIVA

TIVA:

* Can be performed with any combination of IV hypnotic and analgesic
* Practically, propofol is used for induction and maintenance  
Propofol TIVA can be used:  
	* On its own for sedation techniques
	* With other drugs for GA  
	Remifentanil is often used as its pharmacokinetic profile it is synergistic with propofol.

### Performing Safe TIVA

* **In all cases, regular checking of anaesthesia delivery should occur**:
	* The IV site should be visible and checked regularly to ensure drug delivery is occurring  
	i.e. the drip has not tissued/become disconnected.
	* A depth of anaesthesia monitor should be used
* Secure the IV well
* Use antireflux valves on all lumens
* Use Luer-lock syringes only
* Minimise deadspace between the TIVA extension and the patient
* Check the infusion site when pump alarms occur
* Remove 3-way taps from the IV line at the end of the case and flush any dead space


#### TIVA Checklist

1. Use dedicated TCI pumps if using TCI models
2. Know what you're doing
3. Ensure pumps have been serviced in the last 12 months
4. Ensure pumps are powered and batteries are charged
6. Ensure **drug dilutions** are correct and **entered correctly**
7. Ensure correct syringe type and size data are entered
8. Ensure **the right drug** is in the **right pump**
9. Ensure infusion pressure alarms are set
10. Ensure that the targets set are appropriate to the age and ASA status
11. **Have a Plan B**


#### Failure of TCI Pumps

In case of failure, consider:

* Change to a volatile-based technique
* Restart the pump at a manual infusion at the last known rate
* Restart the pump in TCI mode
	* Be prepared for exaggerated haemodynamic responses as the pump administers a bolus
	* Up-titrate the infusion rate slowly



### Propofol TIVA for Sedation

Propofol for sedation:

* Typically targets an effect-site concentration of 2-4ug/ml


### Propofol TIVA for GA

Propofol can also be used to provide general anaesthesia. This requires:

* Requires a greater-effect site concentration when used alone
Typically **an effect-site concentration of 7μg/ml is a reasonable starting point** in most well adult patients.
	* Check to see if the bolus/loading dose given appears reasonable
	* Reduction can be achieved with another analgesic, consider:
		* Remifentanil
		* Nitrous oxide
* Titration to effect
	* Depth of anaesthesia monitoring
	* Loss of haemodynamic response or limb movement to vigorous jaw thrust
	* Loss of haemodynamic response to laryngoscopy
* Cease infusion once final sutures are applied, before application of dressings  
The **decrement time** is useful for timing emergence:
	* Decrement time set to a Ce at 1.8 appears to be a reliable marker for extubation in children

Suggested Cp for propofol TIVA:

|Sole Agent|Adjuncts|
|--|--|
|4-6μg/ml|3-4μg/ml|


### Propofol/Remifentanil TIVA for GA

This combination:

* Allows provision of strong intraoperative analgesia and anaesthesia with a rapid-wake up
* Can be initiated in three ways:
	* **Both** agents with **effect-site targeting**  
	Agents should be started simultaneously.
	* **Effect-site propofol** target with **plasma-site remifentanil** target  
	Propofol will equilibrate with the effect site much more rapidly than remifentanil. Therefore:
		* A greater dose of propofol will be required, reducing the efficacy of the synergy of these drugs
		* Starting the propofol after the remifentanil has equilibrated will achieve a much more rapid induction
	* **Plasma-site propofol** target with **plasma-site remifentanil** target  
	In this instance, remifentanil will equilibrate with the effect site more rapidly. This leads to:
		* A period of awareness with apnoea  
		This can be overcome with over-pressuring the propofol, but this may lead to adverse CVS effects. 
* Cease propofol infusion once final sutures applied
* Remifentanil infusion can be:
	* Ceased with the propofol infusion
	* Ceased (e.g. 30 minutes) prior to the end of the case  
	With administration of a long-acting opioid to provide post-operative analgesia.  
		* Long-acting may also be given throughout the case to reduce remifentanil requirements and (theoretically) opioid hyperalgesia
		* Long-acting should be given ~30-40 minutes **prior** to ceasing a remifentanil infusion  
		A dose of 0.1-0.3mg/kg of morphine can be used.
	* Continued at a target of 1-2μg/ml for a smooth, cough-free extubation


Suggested minimum effect-site concentrations for propofol/remifentanil TIVA in adults:

|Age|Spontaneously Ventilating|PPV|
|--|--|	
|⩽50|PPF: 4-6μg/ml <br> Remi: 1-3ng/ml|PPF: 3-4μg/ml <br> Remi: 5-8ng/ml|
|⩾50|PPF: 2-4ug/ml <br> Remi: 1-2ng/ml|PPF: 2-3μg/ml <br> Remi: 3-6μg/ml




---

## References

1. Al-Rifai Z, Mulvey D. [Principles of total intravenous anaesthesia: practical aspects of using total intravenous anaesthesia](https://academic.oup.com/bjaed/article-pdf/16/8/276/7135003/mkv074.pdf). BJA Educ. 2016;16(8):276-280. doi:10.1093/bjaed/mkv074
2. Gaynor, J, and J M Ansermino. ‘Paediatric Total Intravenous Anaesthesia’. BJA Education 16, no. 11 (November 2016): 369–73. https://doi.org/10.1093/bjaed/mkw019.
