# Toxic Alcohols {#sec-tox_etoh}

Toxic alcohols are relatively benign in themselves but produce highly **toxic metabolites** that cause **neurotoxicity** as well as other organ-specific toxicities. Toxic alcohols include:

* **Methanol**\
	* Found in de-icers, windshield wiper fluid, antifreeze, paint strippers, embalming fluid
	* Metabolised to formaldehyde and then to **formic acid**\
	HAGMA and ocular toxicity in addition to neurotoxicity.
* **Ethylene glycol**
	* Found in antifreeze, degreasers, and metal cleaners
	* Metabolised in a series of steps to **oxalic acid**\
	HAGMA, cardiopulmonary toxicity, and nephrotoxicity in addition to neurotoxicity.
* **Isopropanol**
	* Found in rubbing alcohol, hand sanitiser, and other antiseptics
	* Metabolised to **acetone** and so does *not* produce a HAGMA\
	Gastrointestinal toxicity, and ketosis without acidosis in addition to neurotoxicity.
	

:::column-margin
Methanol is metabolised into formic acid, ethylene glycol is metabolised into glycolic acid.
:::

# Disease


## Epidemiology and Risk Factors

## Pathophysiology

### Aetiology

## Clinical Features

: Clinical Features of Toxic Alcohol Ingestion

+-----------------+------------------------------+------------------------------------------------------------+--------------------------+
| System          | Methanol                     | Ethylene Glycol                                            | Isopropanol              |
+=================+==============================+============================================================+==========================+
| Cardiopulmonary |                              | * ↑ HR                                                     |                          |
|                 |                              | * ARDS                                                     |                          |
|                 |                              | * Heart failure                                            |                          |
+-----------------+------------------------------+------------------------------------------------------------+--------------------------+
| Neurological    | **Ocular**:                  | * Coma                                                     | * Confusion → Coma       |
|                 |                              | * Seizures                                                 | * Cerebellar signs       |
|                 | * Blurry vision              | * Meningism                                                |                          |
|                 | * ↓ Acuity                   | * CN deficit\                                              |                          |
|                 | * Photophobia                | Often delayed by 5-20 days.                                |                          |
|                 | * "Snowstorm" vision         |                                                            |                          |
|                 | * Permanent blindness\       |                                                            |                          |
|                 | Retinal toxicity.            |                                                            |                          |
|                 |                              |                                                            |                          |
|                 | **Other**:                   |                                                            |                          |
|                 |                              |                                                            |                          |
|                 | * Parkinsonism               |                                                            |                          |
|                 | * Transverse myelitis        |                                                            |                          |
|                 | * Basal ganglia haemorrhages |                                                            |                          |
+-----------------+------------------------------+------------------------------------------------------------+--------------------------+
| Renal           | * HAGMA                      | * ↓ Calcium\                                               | * Normal OG              |
|                 |     * Formic acid            | Chelated by oxalic acid.                                   |                          |
|                 |     * Lactic acid            | * AKI\                                                     |                          |
|                 | * ↑ OG                      | Precipitation of calcium oxalate crystals in renal tubule. |                          |
|                 |                              | * HAGMA                                                    |                          |
|                 |                              | 	  * Glycolic acid                                         |                          |
|                 |                              | 	  * Oxalic acid                                           |                          |
|                 |                              | 	  * Lactic acid                                           |                          |
|                 |                              | * ↑ OG                                                     |                          |
+-----------------+------------------------------+------------------------------------------------------------+--------------------------+
| GIT             |                              |                                                            | * Haemorrhagic gastritis |
+-----------------+------------------------------+------------------------------------------------------------+--------------------------+


## Diagnostic Approach and DDx

## Investigations

**Bedside**:

* ABG
	* HAGMA
	* AG

**Laboratory**:

:::column-margin
Osmolar gap and anion gap change over time. Initially, the OG is ↑ due to the toxic alcohols, then as the alcohol is metabolised to acids the OG ↓ and the AG ↑.
:::

* Blood
	* UEC
	* Osmolar gap
	* Serum alcohol concentrations\
	Toxic levels usually only available after commencing treatment.

:::column-margin
If you can quantitatively measure the serum alcohol, you can also determine the contribution of that alcohol to the osmolar gap. 1mmol/L of:

* Ethanol: 4.6 mg/dL
* Methanol: 3.2 mg/dL
* Ethylene glycol: 6.2 mg/dL
* Isopropanol: 6.0 mg/dL
:::

:::column-margin
Methanol has the lowest molecular weight and therefore greatest ↑ in OG per unit volume. 
:::

:::column-margin
Degree of **inebriation** is **proportional** to **molecular weight**.
:::

**Imaging**:

* CTB
	* Methanol toxicity
		* Putamen necrosis
		* Basal ganglia haemorrhages
		* Optic chiasmal atrophy
		* Caudate nuclear necrosis


**Other**:

## Management

:::priority
* Treat **acidosis**
* Early **RRT**
* For methanol and ethylene glycol:
	* Give **antidote**
	* Give **cofactors**
:::

**Resuscitation**:

**Specific therapy**:

* Pharmacological
	* **Antidote**\
	Inhibit conversion to toxic acids in methanol and ethylene glycol poisoning.
		* Agents:
			* Fomepizole 15mg/kg IV load, then 10mg/kg Q12H
			* Ethanol 0.6g/kg PO, targeting a BAC of 0.1-0.15%.
				* Will contribute to CNS toxicity
		* Indicated for:
			* Osmolar gap >10mOsm
			* pH <7.3
			* Urinary oxalate crystals
	* **Sodium bicarbonate**
		* For metabolic acidosis
	* **Metabolic cofactors**\
	↑ Clearance of toxic metabolites to non-toxic metabolites.
		* Ethylene glycol toxicity
			* Pyridoxine 100mg IV Q6H and thiamine 100mg IV Q6H
		* Methanol toxicity
			* Folic acid 50mg IV Q4-6H
			* Folinic acid 1-2mg/kg IV Q4-6H
* Procedural
	* **RRT**
		* pH <7.25
		* Visual abnormalities
		* Renal failure
		* Refractory electrolyte derangements
		* Refractory haemodynamic instability
* Physical

:::column-margin
Fomepizole is not available in Australia.
:::

:::column-margin
Activated charcoal has no role as absorption of alcohols is too rapid.
:::

**Supportive care**:

* G
	* PPI
	* Thiamine\
	Enhances metabolism of ethylene glycol.


**Disposition**:

* ICU if:
	* Acidaemia
	* End-organ dysfunction
* Toxicologically cleared if:
	* Toxic alcohol concentration <20mg/dL
	* No organ dysfunction
	* Haemodynamic stability
	* Normal pH

**Preventative**:


### Marginal and Ineffective Therapies

* Activated charcoal

## Anaesthetic Considerations

## Complications

## Prognosis

## Key Studies


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.
1. Mahdi AS, McBride AJ. [Intravenous Injection of Alcohol By Drug Injectors: Report of Three Cases. Alcohol and Alcoholism](https://academic.oup.com/alcalc/article/34/6/918/192717). 1999;34(6):918-919. doi:10.1093/alcalc/34.6.918
