# Amphetamines

:::info
This covers amphetamines including ecstasy and MDMA.
:::

:::column-margin
This covers specific features of amphetamine toxicity. The general approach to management of a poisoning is covered under @sec-tox.
:::


## Epidemiology and Risk Factors

## Pathophysiology

### Aetiology

## Clinical Features

Mild:

* Sweating
* Dry mouth
* Anxiety


Severe:

* Serotonin syndrome
* Hypertension
* Supraventricular dysrhythmia


## Diagnostic Approach and DDx

## Investigations

**Bedside**:

**Laboratory**:

* Blood
	* UEC
		* Hyponatraemia\
		Water intoxication.

**Imaging**:

**Other**:

## Management

:::priority
* Manage **agitation** with **benzodiazepines**\
This also treats haemodynamic effects and ↓ stroke risk.
* Correct **residual hypertension** once agitation controlled
* **Treat** concomitant **serotonin syndrome**
* Prevent **rhabdomyolysis**
:::

:::column-margin
Management of serotonin syndrome is covered under @sec-serotonin.
:::

**Resuscitation**:

**Specific therapy**:

* Pharmacological
* Procedural
* Physical
	* Cooling

**Supportive care**:

* A
	* Intubation may be required for:
		* Safety
		* To manage sedation
* C
	* Hypertension control\
	Once agitation is controlled, consider:
		* Pure α-antagonist\
		* Mixed α/β-antagonists for refractory hypertension
		e.g. Phentolamine.
		* GTN/SNP
* D
	* **Benzodiazepines**\
	First line for:
		* Agitation
		* Haemodynamic control when agitation still present
		* Seizures
	* Post-intubation sedation
		* Propofol
		* Dexmedetomidine
* E
	* Maintain normothermia
		* Neuromuscular blockade
		* Active cooling
* F
	* Maintain adequate urine output\
	↓ Risk of rhabdomyolysis-associated AKI. 

:::column-margin
The hyperthermia of sympathomimetic toxicity is not due to an altered hypothalamic set point - paracetamol is ineffective.
:::

**Disposition**:

**Preventative**:


### Marginal and Ineffective Therapies

* Isolated β-blockade\
Theoretic risk of unopposed alpha stimulation.

## Anaesthetic Considerations

## Complications

* D
	* Haemorrhagic stroke
* F
	* Hyponatraemia
	* Rhabdomyolysis

## Prognosis

## Key Studies


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.
