# Anticholinergic


## Epidemiology and Risk Factors

## Pathophysiology

### Aetiology

## Clinical Manifestations

Peripheral toxicity:

:::column-margin
Peripheral features are essentially **parasympatholytic**.
:::

:::column-margin
The classic mnemonic for anticholinergic toxicity:

* Blind as a bat\
Mydriasis, dilated pupils without accomodation.
* Mad as a hatter
Delirium.
* Dry as a bone\
Anhydrosis.
* Red as a beet\
Erythema due to vasodilation.
* Hot as a hare\
Warm to touch.
:::

* ↑ HR
* Cutaneous vasodilation
* Anhydrosis
* Mydriasis
* Ileus
* Urinary retention
* ↓ Sweating


Central toxicity:

* Tremor
* Hyperthermia
* Delirium
* Seizures

## Diagnostic Approach and DDx

## Investigations

**Bedside**:

**Laboratory**:

**Imaging**:

**Other**:

## Management

**Resuscitation**:

ABC approach. Comment on team coordination and clinical priorities.
**Specific therapy**:

* Pharmacological
* Procedural
* Physical

**Supportive care**:

**Disposition**:

**Preventative**:


### Marginal and Ineffective Therapies

## Anaesthetic Considerations

## Complications

* E
	* Hyperthermia
* F
	* Rhabdomyolysis
* H
	* DIC

## Prognosis

## Key Studies


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.
