# Salicylates {#sec-tox_salicylate}

:::info
Salicylates include aspirin and Oil of Wintergreen. The Oil has ↑↑ toxic potential due to ↑ drug concentration.
:::

Salicylate overdose classically causes:

* Triad of:
	* Nausea
	* Vomiting
	* Tinnitus
* An initial **primary respiratory alkalosis**\
Direct respiratory centre stimulation.
* **Secondary metabolic acidosis**\
Late sign indicating imminent demise. Produces a HAGMA due to:
	* Salicylate anion production
	* Uncoupled oxidative phosphorylation

:::column-margin
Nausea and vomiting occur due to irritation of both gut mucosa and the medullary chemoreceptor trigger zone.
:::

## Epidemiology and Risk Factors

## Pathophysiology

### Aetiology

## Clinical Features

Initial:

* Tinnitus
* Nausea, vomiting
* Abdominal pain

Severe:

* Pulmonary oedema
* ARDS
* Seizures
* Coma
* Acidaemia
* Hyper or hypoglycaemia
* Hypokalaemia

## Assessment

**History**:

* Dose\
Risk assessment:
	* <150mg/kg: Minimal
	* 150-300mg/kg: Mild-moderate\
	Recommend activated charcoal.
	* \>300mg/kg: Severe intoxication, metabolic acidosis and neurological features expected
	* \>500mg/kg: Potentially lethal\
	Consider gastric lavage.

**Exam**:

### Investigations

:::caution
Many **bedside ABG** machines **mistake salicylate** for **chloride** and **incorrectly report** a **hyperchloraemic NAGMA**.
:::

**Bedside**:

* ABG
	* Respiratory alkalosis
	* HAGMA

**Laboratory**:

* Blood
	* Salicylate level\
	Correlate poorly with toxicity but can be used to identify trend of absorption.
	* UEC
		* Monitor for hypokalaemia
	* Paracetamol level
	* BSL

**Imaging**:

**Other**:

### Diagnostic Approach and DDx


## Management

:::priority
* **Activated charcoal**
* Treat **seizures**
* **Urinary alkalinisation** or **RRT**
:::

**Resuscitation**:

* Pulmonary oedema
	* CPAP\
	NIV or intubation, depending on conscious state.
* C
	* Fluid resuscitation\
	GIT and insensible losses.
* D
	* Seizures
		* Benzodiazepines


**Specific therapy**:

:::column-margin
Activated charcoal and urinary alkalinisation are covered in detail under @sec-tox.
:::

* Pharmacological
	* **Activated charcoal**\
	Up to 8 hours following overdose.
	* **Alkalinisation**
		* ↑ Urine pH traps salicylate ions in urine, ↑ elimination
		* ↑ Blood pH prevents salicylate movement into CSF
* Procedural
	* RRT
		* ↑ Clearance
		* Allows control of volume when bicarbonate is ↑
* Physical


**Supportive care**:

* B
	* Hyperventilation\
	To aid alkalinisation.
* F
	* Correct hypokalaemia\
	Hypokalaemia will ↑ DCT K^+^/H^+^ exchange, acidifying urine.
	

**Disposition**:

**Preventative**:


### Marginal and Ineffective Therapies

## Anaesthetic Considerations

## Complications

## Prognosis

## Key Studies


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.
