# Beta-Blockers

β-blocker overdose causes ↓ HR, ↓ inotropy, and (possibly) vasodilation; the size of each effect depending on the:

* Receptor specificity of the drug taken
* Underlying cardiac function\
Particularly:
	* Systolic function
	* AV nodal blockade

:::column-margin
Notably, **propranolol** penetrates the BBB and ↓↓ seizure threshold. Most deaths from β-blocker overdose are due to propranolol.
:::

## Epidemiology and Risk Factors

## Pathophysiology

### Aetiology

## Clinical Features

Cardiac:

* Bradyarrhythmias
	* ↓ HR
	* AV nodal blockade\
	Full spectrum is possible.
	* Asystole
* Hypotension
* Cardiogenic shock
	* Pulmonary oedema

Extra-cardiac: 

* **Bronchospasm**
* **↓ BSL**
* ↑ K^+^

:::column-margin
Unlike β-blockers, calcium channel blockers do not cause bronchospasm, and will typically **↑** the BSL.
:::

## Diagnostic Approach and DDx



## Investigations

**Bedside**:

**Laboratory**:

**Imaging**:

**Other**:

## Management

:::priority
* **Activated charcoal**
* **Cardiovascular support**
	* Chronotropy
	* Pacing
	* Glucagon
* **High-dose insulin euglycaemic therapy**
:::

**Resuscitation**:

* C
	* Bradycardia
		* Atropine\
		Reasonable for symptomatic bradycardia.
		* Adrenaline
		* Cardiac pacing
	* Hypotension
		* Volume resuscitation
		* Glucagon 10mg IV
		* High-dose insulin-euglycaemic therapy
		* Inotropes
		* Vasopressors
	* ECMO if refractory

**Specific therapy**:

* Pharmacological
	* **Activated charcoal**
		* Ideally within 1-hour of immediate release ingestion
		* Any time after sustained release ingestion
			* Consider multiple (Q4H) dosing
	* **Gastric lavage**\
	Consider if very recent (<1 hour) overdose.
	{{< include /includes/hiet.qmd >}}
* Procedural
* Physical

**Supportive care**:

* A
	* 
* B
	* Mechanical ventilation

**Disposition**:

**Preventative**:


### Marginal and Ineffective Therapies

## Anaesthetic Considerations

## Complications

## Prognosis

## Key Studies


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.
