# Calcium-channel Blockers

Calcium channel blocker overdose produces 

:::column-margin
Non-dihydropyridines (diltiazem, verapamil) are the agents of concern. Dihydropyridine overdose typically causes isolated hypotension with a compensatory *tachy*cardia, although subclass selectivity is lost in massive overdose and myocardial suppression (and *brady*cardia) can occur.
:::

* ↓ HR
* ↓ BP
	* ↓ Inotropy
	* ↓ SVR

## Epidemiology and Risk Factors


## Pathophysiology

* Direct ↓ inotropy
* Direct ↓ SVR
* ↓ Insulin release from β-islet cells
* ↑ Insulin resistance


### Aetiology

Calcium channel blockers:

* Have high PO absorption
* Are highly protein bound
* Hepatically metabolised
* Include:
	* Phenylalkylamines
		* Greatest cardio-selectivity
		* Include:
			* Verapamil
				* Slow-release preparation
	* Benzothiazepine
		* Mid-range cardioselectivity
		* Include:
			* Diltiazem
	* Dihydropyridines
		* Least cardioselective
		* Include:
			* Amlodipine
			* Felodipine
			* Nimodipine


## Clinical Features

Cardiac:

* Bradyarrhythmias
	* ↓ HR
	* AV nodal blockade\
	Full spectrum is possible.
* Hypotension


Extra-cardiac: 

* **↑ BSL**

:::column-margin
Unlike calcium channel blockers, β-blockers can also cause bronchospasm, and will typically **↓** the BSL.
:::


## Diagnostic Approach and DDx

## Investigations

**Bedside**:

**Laboratory**:

**Imaging**:

**Other**:


## Management

:::priority
* Give **activated charcoal**
* Treat **haemodynamics**\
Pacing may be required; chemical may be ineffective.
* **High-dose insulin**
* Consider **intralipid**
:::


**Resuscitation**:

:::column-margin
{{< include /includes/calcium_equiv.qmd >}}
:::

* C
	* Hypotension	
		* Fluid resuscitation
		* Calcium
			* 10mL 10% Calcium chloride
			* 30mL 10% Calcium gluconate
			* Infusion can be considered but requires close monitoring
		* Insulin
	* Bradycardia
		* Atropine\
		Unlikely to be effective.
		* Cardiac pacing

**Specific therapy**:

* Pharmacological
	* **Activated charcoal**
		* Within 1-hour of immediate release ingestion
		* Any time after sustained release ingestion
			* Consider multiple (Q4H) dosing
	{{< include /includes/hiet.qmd >}}
	* **Intralipid**
* Procedural
* Physical


**Supportive care**:

**Disposition**:

**Preventative**:


### Marginal and Ineffective Therapies

## Anaesthetic Considerations

## Complications

## Prognosis

## Key Studies


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.