# Chemotherapy Toxicities

Chemotherapeutic agents are infamous for a wide range of adverse effects. These include:

* General chemotherapeutic toxicities
* Immunotherapy toxicity
* Agent-specific toxicity

## Immunotherapy Toxicity

Immunotherapeutics are biological therapies that augment the immune system to destroy cancer cells, and have revolutionised the treatment of many malignancies with traditionally poor prognoses.

Adverse effects of immunotherapy relate to augmented immune function and include:

* B
	* Pneumonitis
* C
	* Myocarditis
	* Pericarditis
	* Vasculitis
	* Arrhythmia
	* ACS
* D
	* Uveitis
	* Encephalopathy\
	1-5%.
* E
	* Thyroiditis
	* Diabetes
	* Hypophysitis
* G
	* Colitis
	* Hepatitis\
	5-10%.
	* Pancreatitis
	* Cholangitis
* I
	* Dermatitis\
	Most common side effect.
		* Maculopapular rashes
		* Lichenoid eruptions


Management:

* Predominantly supportive
* Agents may be continued, adjusted, or ceased depending on the nature and severity of toxicity
* Immunosuppressants may be required, including:
	* Steroids
	* Infliximab
	* Tacrolimus
	* Mycophenolate

## Agent-Specific Toxicities

Chemotherapeutic agents with unique toxidromes include:

* **Anthracyclines**
	* Include daunorubicin, doxorubicin, epirubicin
	* Cause acute or chronic heart failure
		* Acute typically arrhythmia or cardiogenic shock
		* Chronic typically a dose-dependent cardiomyopathy
			* May present 3 months to years following chemotherapy
			* Standard heart failure treatment applies
* **Bleomycin**
	* Antibiotic that destroys DNA by generation of oxygen free-radicals
	* Used in cervical, germ cell, and head and neck tumours
	* Causes pneumonitis in 5-18% of exposed patients
		* Via generation of oxygen free radicals with alveolitis and fibrosis\
		Condition is **exacerbated by ↑ FiO~2~ >30%**, which should be avoided.
		* Risk factors include:
			* Age
			* Cumulative bleomycin dose
			* CKD
			* FiO~2~\
			Evidence is unclear about whether there is a dose-response relationship, or a threshold FiO~2~ exists.
			* Smoking
		* 2-5% mortality
* **Ifosfamide**
	* Alkylating agent
	* Used in lymphoma, cervical, ovarian, breast, lung, and head and neck cancer
	* Toxicity is likely from metabolites, and consists of
		* Visual or auditory hallucinations
		* Encephalopathy in 10-20%\
		Variable severity from confusion to coma.
	* Risk factors for toxicity include:
		* Hypoalbuminaemia
		* Hyponatraemia
		* ↑ Creatinine
		* Previous cisplatin
		* Bulky disease
	* Management consists of:
		* Normalisation of electrolytes and albumin
		* Benzodiazepines for seizures
		* Methylene blue 50mg IV Q6H
* **Retinoic acid**
	* Used for APML
	* Toxic features include:
		* Respiratory failure
		* Shock
			* AKI
		* Fluid retention
	* Management is supportive
* **Trastuzumab** (Herceptin)
	* Causes dose-independent myocardial dysfunction
		* Commonly combined with anthracyclines which ↑ risk
		* Reversible myocardial stunning - can be resumed when myocardial function recovers


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.
2. J. Haanen, M. Obeid, L. Spain, et al. [Management of toxicities from immunotherapy: ESMO Clinical Practice Guideline for diagnosis, treatment and follow-up](https://www.esmo.org/guidelines/guidelines-by-topic/supportive-and-palliative-care/toxicities-from-immunotherapy). Annals of Oncology. Published online: 18 October 2022.
3. Ingrassia TS, Ryu JH, Trastek VF, Rosenow EC. [Oxygen-Exacerbated Bleomycin Pulmonary Toxicity](https://www.mayoclinicproceedings.org/article/S0025-6196(12)60489-3/fulltext). Mayo Clinic Proceedings. 1991;66(2):173-178.
