# Carbon Monoxide {#sec-carbon_monoxide}

Carbon monoxide is a **toxic gas** that has **high affinity** for **haemoglobin**, displacing oxygen from haemoglobin binding sites resulting in a significant **fall** in blood **oxygen carrying capacity** and cellular hypoxia.

:::column-margin
Carbon monoxide is also:

* Odourless
* Colourless
* Less dense than air
* Flammable
:::

## Epidemiology and Risk Factors

## Pathophysiology

Carbon monoxide:

* Has **240 times** the **affinity** for **haemoglobin** than oxygen
* Has a half-life of ~320 minutes breathing air
	* ↓ To 75 minutes on 100% O~2~

### Aetiology

## Clinical Manifestations

Symptoms vary with the proportion of COHb:

:::column-margin
Smokers may have a COHb level up to 10%.
:::

* Mild (10-25%)
	* Weakness
	* Dizziness
	* Confusion
* Moderate (25-40%)
	* Nausea
	* Arrhythmia
* Severe (>40%)
	* Coma → Seizure

:::column-margin
Cyanosis is much more common than "cherry-pink" skin.
:::

## Diagnostic Approach and DDx

## Investigations

**Bedside**:

* ECG
	* ST segment changes

**Laboratory**:

**Imaging**:

**Other**:

## Management

**Resuscitation**:

* A
	* Intubation indicated if no longer protecting airway
* B
	* Supplemental oxygen

**Specific therapy**:

* Pharmacological
* Procedural
* Physical
	* Hyperbaric oxygen\
	Often used though no strong evidence of benefit.

**Supportive care**:

**Disposition**:

**Preventative**:


### Marginal and Ineffective Therapies

## Anaesthetic Considerations

## Complications

## Prognosis

## Key Studies


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.
