# Cocaine

Acute cocaine toxicity presents with:

* Sympathomimetic effects\
Similar to amphetamines.
* Vasospasm
	* Cardiac
	* Cerebral
* Myocardial ischaemia\
Combination of:
	* ↑ Myocardial oxygen demand
	* Coronary vasospasm
	* ↑ Platelet aggregation


## Epidemiology and Risk Factors

## Pathophysiology

### Aetiology

## Clinical Manifestations

## Diagnostic Approach and DDx

## Investigations

**Bedside**:

**Laboratory**:

**Imaging**:

**Other**:

## Management

**Resuscitation**:

ABC approach. Comment on team coordination and clinical priorities.
**Specific therapy**:

* Pharmacological
	* Benzodiazepines
	* Aspirin
	* Calcium channel blockade
	* α-blockade
* Procedural
	* Angioplasty
* Physical

**Supportive care**:

**Disposition**:

**Preventative**:


### Marginal and Ineffective Therapies

* β-blocker\
Relative contraindicated due to risk of unopposed α stimulation.
* DAPT\
Not recommended due to ↑ ICH risk with systemic hypertension.
* Heparin

## Anaesthetic Considerations

## Complications

* C
	* MI
* D
	* ICH

## Prognosis

## Key Studies


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.