# Neuroleptic Malignant Syndrome {#sec-nms}

**Idiosyncratic reaction** to initiation or change of an **antipsychotic** or **dopamine antagonist** characterised by:

* Hyperthermia
* Muscle rigidity
* Mental status change
* Autonomic dysfunction
	* Tachycardia
	* Diaphoresis
	* Incontinence


## Epidemiology and Risk Factors

## Pathophysiology

Dopamine antagonism at the:

* Hypothalamus\
Hyperthermia.
* Mesocortical and nigrostriatal region\
Mental state change and extrapyramidal symptoms.

### Aetiology

## Clinical Features

* Fever
* Encephalopathy
* Haemodynamic instability
* Rhabdomyolysis


## Investigations

**Bedside**:

* Blood
	* FBE\
	Leukocytosis.
	* UEC
	* CK
	* Coag

**Laboratory**:

**Imaging**:

**Other**:

## Diagnostic Approach and DDx

Diagnosis requireds:

* Use of neuroleptic medication
* Muscle rigidity
* Fever
* ⩾2 of:
	* Tremor
	* Altered conscious state
	* ↑ HR
	* HTN or labile BP
	* Diaphoresis
	* Leukocytosis
	* Rhabdomyolysis
	* Leukocytosis

:::column-margin
Serotonin Syndrome is a always a differential for NMS.\
\
{{< include /includes/nms_ss.qmd >}}
:::

## Management

:::priority
* Cease offending agent
* Manage **hyperthermia**
* **Give dopminergic**
:::


**Specific therapy**:

* Pharmacological
	* Dopaminergic agent
		* Bromocriptine 2.5-5mg PO/NG Q8H
		* Amantadine
* Procedural
* Physical

**Supportive care**:

* D
	* Sedation
		* Benzodiazepines
* E
	* Manage hyperthermia
		* Neuromuscular blockade
		* Active cooling


**Disposition**:

**Preventative**:


### Marginal and Ineffective Therapies

## Anaesthetic Considerations

## Complications

* B
	* Respiratory failure
* C
	* Arrhythmias
* F
	* AKI
	* Rhabdomyolysis
* H
	* DIC


## Prognosis

## Key Studies


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.