# Paraquat

Widely available highly **toxic herbicide** that **generates reactive oxygen species** which cause extensive injury to:

* **Lungs**
* Kidneys
* Liver


## Epidemiology and Risk Factors

## Pathophysiology

Key pharmacology of paraquat:

* Highly hydrophilic
	* Rapid gut absorption
	* Poor skin absorption
* Rapidly inactivated in soil\
Leads to popularity as a herbicide, as planting can occur immediately.
* Pulmonary accumulation
* Rapid renal clearance of unchanged drug


### Aetiology

## Clinical Features

: Features of Paraquat Toxicity

+------------------+------------------------------+-------------------------+-----------------------+
| System           | Mild                         | Moderate                | Severe                |
+==================+==============================+=========================+=======================+
| **General**      |                              |                         | * Multi-organ failure |
|                  |                              |                         | * Death               |
+------------------+------------------------------+-------------------------+-----------------------+
| **Respiratory**  | * Haemoptysis                | * Pulmonary oedema\     |                       |
|                  | * Mucous membrane ulceration | Day 1-3.                |                       |
|                  |                              | * Pulmonary haemorrhage |                       |
|                  |                              | * Pulmonary fibrosis\   |                       |
|                  |                              | Day 3-7.                |                       |
+------------------+------------------------------+-------------------------+-----------------------+
| **Neurological** | * Tremors                    | * Convulsions           |                       |
+------------------+------------------------------+-------------------------+-----------------------+
| **Renal**        | * AKI                        | * ATN                   |                       |
+------------------+------------------------------+-------------------------+-----------------------+
| **GIT**          | * Nausea                     | * Hepatotoxicity        |                       |
|                  | * Vomiting                   | * Haematemesis          |                       |
|                  | * Diarrhoea                  |                         |                       |
|                  | * Intestinal haemorrhage     |                         |                       |
+------------------+------------------------------+-------------------------+-----------------------+


## Assessment

**History**:

**Exam**:

### Investigations

**Bedside**:

**Laboratory**:

* Blood
	* Paraquat assay
	* FBE
	* UEC
* Urine
	* Sodium dithionite

**Imaging**:

**Other**:

### Diagnostic Approach and DDx


## Management

:::priority
* **Early management essential** to avoid pulmonary fibrosis and death
* Give oral absorbents
* Target mild *hypoxia*
:::

**Resuscitation**:

* B
	* Avoid hyperoxia\
	SpO~2~ >88% acceptable, minimise O~2~.

**Specific therapy**:

* Pharmacological
	* **Absorbents**
		* Fullers earth\
		30% 250ml Q4H until seen in stools.
		* Activated charcoal\
		If Fullers earth not available.
	* Antioxidants
		* Salicylate
		* Acetylcysteine
* Procedural
	* Extracorporeal filtration\
	Both RRT and plasma exchange are generally ineffective due to rapid pulmonary redistribution.
* Physical
	* Remove contaminated clothes
	* Wash skin with soap and water


**Supportive care**:

**Disposition**:

**Preventative**:


### Marginal and Ineffective Therapies

## Anaesthetic Considerations

## Complications

* Death\
In >50%.

## Prognosis

## Key Studies


---

## References