
# Serotonin Syndrome


> * **Severe** and life-threatening cases **almost always** involve a **monoamine oxidase inhibitor**
> * Awareness of potent serotonergic agents is key to preventing reactions

Drug-induced over-stimulation of serotonin receptors in CNS. Serotonin syndrome is:

* Characterised by:
	* CNS dysfunction
	* Autonomic disturbance
	* Hyperreflexia
* Potentially fatal
* Largely avoidable
* Subdivided into:
	* Mild  
	May be difficult to distinguish from underlying medical conditions, or supra-therapeutic use of an SSRI. Symptoms include:
		* Brisk reflexes, inducible clonus
		* Insomnia, anxiety
		* Nausea, diarrhoea, hypertension, tachycardia
	* Moderate  
	May occur with overdose of single agent, or ↑ therapeutic doses. Symptoms include:
		* Sustined clonus, ocular clonus
		* Agitation
		* Mydriasis, diaphoresis, fever ⩽38.5
	* Severe  
	Potentially fatal.
		* Usually only occurs with two or more serotonergic drugs
		* Usually requires one monoamine oxidase inhibitor
		* Symptoms include:
			* Muscle rigidity, respiratory failure
			* Confusion, coma
			* Severe hyperthermia

## Epidemiology and Risk Factors

## Pathophysiology

Excessive serotonin activity at 5-HT~2~ receptors in the CNS.

## Clinical Manifestations

Careful and detailed drug history is essential:

* Many drugs influence serotonergic neurotransmitters
* Many drugs listed with serotonin syndrome as a side effect will rarely cause
* Many contributing drugs have:
	* Persistent activity  
	e.g. Irreversible MAO.
	* Long half-lives  
	May have been stopped weeks prior.
* Use of herbal remedies
* Use of illicit substances


Presentation:

* Toxicity usually within hours of ingestion
* Diagnosis requires:
	* Overdose of serotonergic drug
	* ↑ in dose of serotonergic drug
	* Addition of a second sertonergic drug
* **Classic triad** of:
	* **Neuromuscular excitation**  
	Hyperreflexia, myoclonus, rigidity.
		* **Generalised clonus** is classical, and may be:
			* Inducible  
			Ankle dorsiflexion.
			* Spontaneous  
			Generally rhythmic, large muscle contractions triggered by minor stimulus.
			* Ocular  
			May be fine or coarse gaze oscillations.
	* **Autonomic nervous system excitation**  
	Nausea, diarrhoea, hypertension, tachycardia, hyperthermia, severe hyperthermia.
	* **Altered mental state**  
	Insomnia, anxiety, agitation, confusion, coma.
* **Severe serotonin toxicity** is characterised by:
	* Rapid hyperthermia
	* Muscle rigidity

### Diagnostic Criteria

Hunter Serotonin Toxicity Criteria:

* Sertonergic agent  
Dose ↑, overdose, or new agent.
	* Spontaneous clonus
		* Yes  
		Serotonin toxicity.
		* No  
		Inducible clonus *or* Ocular Clonus?
			* Yes  
			Agitation *or* diaphoresis *or* (hypertonia and temperature ⩾38°C)?
				* Yes  
				Serotonin toxicity.
				* No  
				Go to tremor and hyperreflexia.
			* No  
			Tremor *and* hyperreflexia?
				* Yes  
				Serotonin toxicity.
				* No  
				No serotonin toxicity.

### Drugs Associated with Moderate to Severe Serotonin Toxicity

Include:

* **Monoamine oxidase inhibitors**
	* Irreversible inhibitors
		* Phenelzine
		* Tranylcypromine
		* Iproniazid
		* Isocarboxazid
	* Reversible inhibitors of MAO-A
		* Moclobemide
	* Non-psychotropic drugs
		* Linezolid
		* Methylene blue
* **Serotonin releasing agents**
	* SSRIs
	* SNRIs
	* TCAs
	* Opioids
		* Fentanyl
		* Tramadol
		* Pethidine
		* Dextromethorphan
	* Amphetamines
	* Synethetic stimulates
		* Ecstasy
		* Bath salts
	* Herbal
		* St John's Wort
* **Other**
	* Lithium
	* Buspirone
	* Tryptophan

### Drugs Without Significant Risk of Toxicity

Serotonin antagonists, or those that do not agnoise 5-HT~2~:

* Antipsychotics
* Anxiolytics
* Anti-migraine drugs
* Antiemetics

## Diagnostic Approach and DDx

Key differentials include:

* Alcohol withdrawal
* Drug withdrawal
* Non-convulsive seizures
* Encephalitis
* Neuroleptic Malignant Syndrome

### Differentiating from Neuroleptic Malignant Syndrome

Key differentiating features are that NMS has:

* A slow onset over days
* Extrapyramidal features and rigidity
* No clonus

## Investigations

Diagnosis is clinical. Investigations usually targeted towards ruling out other causes, or identifying complications.

Bloods:

* UEC/CMP  
Rhabdomyolysis.
* Coagulation screen  
DIC.

Imaging:

* CTB

Other:

* LP  
Encephalitis.
* EEG



## Management

> Largely consists of sedation
> Prevention of hyperthermia is critical in severe toxicity
> Evidence for specific antidotes is lacking

Principles of management:

* Cease agent
* Supportive care
	* A
		* Intubation may be required to control temperature
	* B
	* C
		* Volume resucitation
	* D
		* Sedation
			* Reduces musclea activity
	* E
		* Prevent hyperthermia  
			* Beneficial as:
				* Reduces complications
				* Down regulates 5-HT~2a~ receptors
			* Methods:
				* Active cooling
				* Paralyis and ventilation
* Specific agents  
In severe cases, seek toxicology advice:
	* Chlorpromazine
		* Most commonly used
		* Requires pre-load with IV fluid
	* Cyproheptadine  
	Serotonin and histamine antagonist.
		* No significant differences in severe cases in a retrospective review


### Anaesthetic Considerations

### Marginal and Ineffective Therapies

## Complications

Include:

* Hyperthermia related
	* Rhabdomyloysis
	* DIC
	* Multiorgan failure
* ARDS


## Prognosis

Mild:

* Will not progress to severe toxicity without:
	* Dose escalation
	* Drug interactions
* Moderate:
	* Usually resolves over 1-3 days following cessation
* Severe  
Medical emergency. Requires:
	* Aggressive supportive care
	* Consideration of specific reversal agents

---

## References

1. Buckley NA, Dawson AH, Isbister GK. Serotonin syndrome. BMJ. 2014 Feb 19;348(feb19 6):g1626–g1626. 
2. Nguyen H, Pan A, Smollin C, Cantrell LF, Kearney T. An 11-year retrospective review of cyproheptadine use in serotonin syndrome cases reported to the California Poison Control System. J Clin Pharm Ther. 2019 Apr;44(2):327–34. 
