# Snakebite Envenomation

Potential medical emergency secondary to bite *and* subsequent envenomation of an individual that present with either:

:::column-margin
Most snakebites do not cause envenomation because either:

* Insufficient venom is injected
* The snake is non-venomous
:::

* Local symptoms
* Systemic symptoms
* **Toxidromes**\
Including:
	* **Venom-Induced Coagulopathy**\
	May be a:
		* Consumptive coagulopathy
		* Anticoagulant coagulopathy
	* **Neurotoxicity**\
	*Descending* flaccid paralysis.
	* **Myotoxicity**\
	Generalised myalgia or tenderness.
		* Rhabdomyolysis may develop


## Epidemiology and Risk Factors


## Pathophysiology

Venoms are complex protein mixtures that act as toxins via one or more of these effects:

* **Neurotoxins**\
Pre- and post-synaptic neuromuscular blockade
	* Post-synaptic blockade reversible with antivenom
	* Pre-synaptic blockade may not be reversible
* **Prothrombin** activators
	* Leads to:
		* Consumptive coagulopathy
		* MAHA
		* Cardiovascular collapse\
		Likely due to idiosyncratic pulmonary hypertension or PE.
	* Requires antivenom
* **Anticoagulants**\
Prevents clotting without consumption.
* **Rhabdomyolysins**
	* Direct muscle damage
	* AKI


### Aetiology

: Pathophysiology by Snake Species

| Snake                  | Neurotoxin | Prothrombin Activation | Anticoagulant | Rhabdomyolysin |
|------------------------|------------|------------------------|---------------|----------------|
| **Brown** snake        | Maybe      | Yes                    |               | Maybe          |
| **Tiger** snake        | Yes        | Yes                    |               | Maybe          |
| Taipan                 | Yes        | Yes                    |               | Maybe          |
| Black                  |            |                        | Yes           |                |
| Death Adder            |            | Yes                    |               |                |
| Rough-scaled snake     |            | Yes                    |               |                |
| Stephen's Banded snake |            | Yes                    |               |                |
| Sea snake              | Maybe      |                        |               | Yes            |


## Clinical Manifestations

: Clinical Manifestations by Time Course

+-------------------------+--------------------------------------+---------------------------------+-------------------+
| Time Since Envenomation | <1 hour                              | 1-3 hours                       | \>3 hours         |
+=========================+======================================+=================================+===================+
| General                 | * Headache                           | * ↑ HR                          | * Shock           |
|                         | * Nausea                             | * ↓ BP\                         |                   |
|                         | * Vomiting                           | May precipitate collapse.       |                   |
|                         | * Confusion                          |                                 |                   |
|                         | * Regional lymphadenitis             |                                 |                   |
+-------------------------+--------------------------------------+---------------------------------+-------------------+
| Neurotoxin              |                                      | * Cranial nerve paresis         | * Truncal paresis |
|                         |                                      | * ↓ V~T~                        | * Limb paresis    |
+-------------------------+--------------------------------------+---------------------------------+-------------------+
| Prothrombin Activation  | * Coagulopathy on laboratory testing | * Mucosal haemorrhage           | * DIC             |
|                         |                                      | * Venepuncture site haemorrhage |                   |
+-------------------------+--------------------------------------+---------------------------------+-------------------+
| Anticoagulant           | * Coagulopathy on laboratory testing |                                 |                   |
|                         |                                      |                                 |                   |
+-------------------------+--------------------------------------+---------------------------------+-------------------+
| Rhabdomyolysin          |                                      |                                 | * Rhabdomyolysis  |
|                         |                                      |                                 | * AKI             |
+-------------------------+--------------------------------------+---------------------------------+-------------------+

:::column-margin
Features may progress much more rapidly in children.
:::

Local features:

* Local pain and swelling
* Myonecrosis
* Painful lymphadenopathy of draining nodes


Systemic features:

* Haemodynamic instability
* GI upset
* Diaphoresis
* Headache


Neurotoxicity classically progresses from smaller muscle groups to larger ones:

* Extra-ocular muscles
* Bulbar muscles
* Respiratory muscles
* Skeletal muscles


## Investigations

**Bedside**:

**Laboratory**:

* Venom detection kit\
Performed on blood, urine, or other tissue.
	* Highly sensitive
	* ~25 minutes to run
	* **Very high venom** concentration may **cause** a **false negative**\
	Dilute sample and run again if that possiblity exists.

**Imaging**:

**Other**:


## Diagnostic Approach and DDx

Identification of the snake is helpful but not essential:

* Venom detection kit should be used to guide antivenom selection
* Antivenom should be used to cover snakes in that geographical region


## Management

:::priority
* **Pressure-immobilisation bandage**
* **Antivenom**
* Resuscitation as required
:::

**Resuscitation**:

:::column-margin
The **pressure-immobilisation bandage** is designed to ↓ lymphatic and capillary absorption. It is **not** an arterial **tourniquet**.
:::

* **Pressure-immobilisation bandage**
	* Crepe bandage applied from digits up the limb as far as possible, including the bite site
	* Further immobilisation applied to restrict joints on either side
	* ↓ Absorption by lymphatics by:
		* ↑ Hydrostatic pressure
		* ↓ Skeletal muscle pump
	* Should only be removed once antivenom administered
	* Should not be removed for sampling\
	Cut a window over the bite site to sample.
	* Should be reapplied if the patient deteriorates
* A
	* Intubation if required
* B
	* Supplemental oxygen or mechanical ventilation as required
* C
	* Fluid resuscitation as required

**Specific therapy**:

:::column-margin
In general, the dose is two vials of polyvalent antivenom. Dosing is reasonably crude and based mostly on trials in small, cute animals.
:::

* Pharmacological
	* **Antivenom**\
		* 2-3× dose should be given if critically unwell
		* Can be withheld if clinical situation is mild
		* High risk of immediate hypersensitivity (25%) including **anaphylaxis (10%!)**
		* **Premedication** with **subcutaneous adrenaline** is recommended:
			* 0.01mg/kg in children
			* 0.25mg in adults
		* Administer over 15-30 minutes if situation permits
		* Re-dosing is ineffective
	* Antibiotics\
	Consider for contaminated wounds.
* Procedural
* Physical

**Supportive care**:

:::column-margin
Antivenom will reverse anticoagulant effects, but not replace lost clotting factors.
:::

* D
	* Analgesia\
	Particularly if rhabdomyolysis.
* F
	* AKI prevention
		* Aim 1-2mL/kg/hr of urine output
	* Electrolyte derangement\
	Rhabdomyolysis.
* H
	* Coagulopathy treatment

**Disposition**:

* Observe for at least 12 hours

**Preventative**:


### Marginal and Ineffective Therapies

* Heparin\
Not recommended in procoagulant coagulopathy (or for anything else).

## Anaesthetic Considerations

## Complications

* Death
* D
	* Persistent neurological sequelae:
		* Diplopia
		* Anosmia
	* PTSD
* F
	* AKI\
	May progress to CKD. Causes are multifactorial:
		* Pre-renal
			* Sepsis
			* Cardiac failure
			* Thrombotic microangiopathy
		* Intra-renal
			* ATN secondary to pre-renal failure
			* Myoglobinuria
			* Haemoglobinuria
		* Post-renal
			* Haematuria and obstruction


## Prognosis

Death is:

* Due to:
	* Respiratory paralysis
	* Cardiac arrest
	* AKI
	* Haemorrhage
* Relatively rare:
	* Untreated ~2%
	* Treated ~0.1%

Poor prognostic signs:

* Massive envenomation
* Remote location
* Out-of-hospital collapse
* Inadequate antivenom therapy


## Key Studies


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.
1. Isbister GK, Brown SGA, Page CB, McCoubrie DL, Greene SL, Buckley NA. [Snakebite in Australia: a practical approach to diagnosis and treatment](https://www.mja.com.au/journal/2013/199/11/snakebite-australia-practical-approach-diagnosis-and-treatment). Med J Aust. 2013;199(11). Accessed July 12, 2023.
