# Sodium Valproate


## Epidemiology and Risk Factors

## Pathophysiology

### Aetiology

## Clinical Features

Mild:

* Nausea
* Drowsiness
* Confusion

Severe:

* Cerebral oedema
* Metabolic derangement
	* Metabolic acidosis
	* Hypernatraemia
	* Hypoglycaemia
	* Hyperammonaemia

## Assessment

**History**:

**Exam**:

### Investigations

**Bedside**:

**Laboratory**:

* Blood
	* Valproate level\
	Poor correlation between level and toxicity. 

**Imaging**:

**Other**:

### Diagnostic Approach and DDx


## Management

:::priority
* Supportive care
* Consider L-carnitine if hepatic dysfunction or hyperammonaemia
:::

**Resuscitation**:

**Specific therapy**:

* Pharmacological
* Procedural
* Physical

**Supportive care**:

**Disposition**:

**Preventative**:


### Marginal and Ineffective Therapies

## Anaesthetic Considerations

## Complications

## Prognosis

## Key Studies


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.