# Acute-on-Chronic Liver Failure

Acute **decompensation of stable** compensated or uncompensated **chronic liver disease** leading to additional organ failure and ↑ short term mortality. ACLF is:

* Classified by number of organ failures into:
	* **Class 1**\
	Single organ failure, further divided into:
		* 1a: Renal failure
		* 1b: Non-kidney organ failure
	* **Class 2**\
	Two organ failures.
	* **Class 3**\
	Three organ failures.
* Characterised by:
	* Ascites
	* Encephalopathy
	* Gastrointestinal haemorrhage
	* Infection


## Epidemiology and Risk Factors

## Pathophysiology

### Aetiology

Common precipitants include:

* Infection
	* Bacterial peritonitis
* Variceal haemorrhage
* Alcoholic hepatitis\
Acute onset of jaundice or ascites in a patient with chronic alcohol abuse.
* HCC
* Portal vein thrombosis


## Clinical Features

Usual presentations include:

* Encephalopathy
* Sepsis
* Renal failure
* Variceal haemorrhage

{{< include /includes/hepatic_enceph.qmd >}}


## Investigations

**Imaging**:

* Ultrasound
	* Portal vein patency
	* Hepatic vein patency
	* Malignancy


**Other**:

* Ascitic tap


## Diagnostic Approach and DDx



## Management

**Resuscitation**:

**Specific therapy**:

* Pharmacological
* Procedural
* Physical


**Supportive care**:

* A
	* Intubation\
	For aspiration prevention with haematemesis.
* C
	* Individualise MAP target\
	Tolerate MAP 60mmHg (or lower, depending on baseline pressure).
		* Noradrenaline 1^st^ line
		* Vasopressin 2^nd^ line
* D
	* ICP control
	* Low dose sedation usually adequate
* G
	* Hyperammonaemia\
	Aim to ↓ gut load of ammonia-producing bacteria.
		* Lactulose
		* Rifaximin 550mg PO BD\
		Non-absorbable broad-spectrum antibiotic that ↓ gut flora concentrations.
	* Feeding\
	Protein 1.2-2g/kg/day.
	* Correct hypoglycaemia
	* Trace element and micronutrient supplementation
* H
	* Hb >70

:::column-margin
Cerebral oedema secondary to hyperammonaemia is less common in ACLF due to established compensatory mechanisms.
:::

:::column-margin
Lactulose, an osmotic diuretic, ↓ ammonia by unconventional means:

* Lactulose is metabolised by gut bacteria into lactic and acetic acid
* The ↓ in colonic pH favours conversion of ammonia (NH~3~) to ionised ammonium (NH~4~^+^), which is trapped in the colon\
This is **analogous to urinary alkalinisation** for elimination of weak acids.
* Trapped ammonium is then cleared by the more mundane osmotic laxative effect
:::

**Disposition**:

### Marginal and Ineffective Therapies

## Anaesthetic Considerations

## Complications

{{< include /includes/liver_coag.qmd >}}

## Prognosis

## Key Studies


---

## References

1. Van Eldere A, Pirani T. [Liver intensive care for the general intensivist](https://associationofanaesthetists-publications.onlinelibrary.wiley.com/doi/10.1111/anae.15956). Anaesthesia. 2023;78(7):884-901.