# Acute Pancreatitis

Acute inflammation of the pancreas that is subclassified by severity into:

:::column-margin
The **Glasgow Criteria** are adverse prognostic factors:

* Admission
	* Age >55
	* WCC >15 1,000/mm^3^
	* Glucose >10 mmol/L
	* AST >250 U/L
* Within 48 hours
	* ↓ In Hct >10%
	* ↑ In urea >1.8 mmol/L
	* Calcium <2 mmol/L
	* PaO~2~ <60 mmHg
:::

* Mild acute pancreatitis\
No organ failure or complications.
* Moderate acute pancreatitis\
	* Transient (<48 hours) organ failure
	* Local complications\
	Peripancreatic fluid collections, which can be:
		* Necrosis\
		Non-viable pancreas that may be sterile or infected. Necrosis:
			* Usually develops early
			* Is established by 96 hours
			* Is a major prognostic factor
		* Pseudocysts
		* Cysts
	* Systemic complications
* Severe acute pancreatitis\
As moderate, but with persistent single or multiorgan failure.


## Epidemiology and Risk Factors

## Pathophysiology

### Aetiology

Precipitants include:

* Biliary obstruction\
35-40%.
	* **Gallstones**
	* Malignancy
* Drugs
	* **Alcohol**\
	35%.
	* Antibiotics
		* Metronidazole
		* Nitrofurantoin
		* Erythromycin
		* Tetracyclines
		* Sulphonamides
	* Diuretics
		* Furosemide
		* Thiazides
	* Toxins
		* Methyl alcohol
		* Scorpion venom
		* Organophosphates
* Metabolic
	* **Hyperlipidaemia**
	* Hypercalcaemia
		* Hyperparathyroidism
	* DKA
	* ESRD
* Infections
	* Viral
		* HIV
		* EBV
		* Mumps
	* Bacteria
		* Mycoplasma
		* Legionella
		* Campylobacter
	* Parasites
		* Ascariasis
* Immune
	* Polyarteritis nodosa
	* SLE
	* TTP
* Pregnancy
* Trauma
* Iatrogenic
	* Postoperative

:::column-margin
An enjoyable mnemonic for some of these causes is:

* **I**diopathic\
\
* **G**all stones
* **E**thanol
* **T**rauma\
\
* **S**teroids
* **M**umps\
And other viruses.
* **A**utoimmune
* **S**corpions
* **H**yperlipidaemia
* **E**RCP
* **D**rugs
:::

## Clinical Manifestations

## Diagnostic Approach and DDx

## Investigations

**Laboratory**:

:::column-margin
Amylase has been replaced by lipase, and has little current role in the diagnosis of pancreatitis.
:::

* Blood
	* Lipase\
	90% sensitive and specific for acute disease.
		* Elevations from non-pancreatic causes are typically <3× ULN
	* LFTs\
	For biliary obstruction.
	* Triglycerides\
	\>1000 mg/dL diagnostic of hypertriglyceridaemic pancreatitis, absent other causes.
	* Calcium


**Imaging**:

* Contrast CT
	* Pancreatitis\
	Loss of normal contrast enhancement.
	* Necrosis
* Ultrasound
	* Usually limited by bowel gas
	* Cannot quantify necrosis
	* Provides assessment of biliary tree\
	CBD dilation most important finding.
	* May provide guidance for needle aspiration

## Management

:::info
Surgical management of pancreatitis is associated with very high mortality; supportive treatment is first line and and surgical management should only be resorted to if it is otherwise unavoidable.
:::

**Resuscitation**:

* C
	* Volume resuscitation\
		* Aggressive volume resuscitation required for offsetting distributive shock and correcting hypovolaemia
		* \>10mL/kg associated with ↑ ARDS and ↑ abdominal compartment syndrome
	* Haemodynamic support


**Specific therapy**:

:::column-margin
Carbapenems have exceptional penetration into pancreatic tissue, and are effective against most culprit organisms.
:::

* Pharmacological
	* **Antibiotics**\
		* Low threshold for IV antibiotics if suspecting infected collection
		* Prophylactic antimicrobials *may* have a role in severe disease
	* NSAIDs\
	Appropriate post-ERCP in mild gallstone pancreatitis as analgesics and may ↓ severity.
	* Insulin/dextrose\
	If hypertriglyceridaemia.
		* Goal is to promote anabolism
		* Effect achieved when enough insulin is provided such that the BSL does not rise in the face of dextrose infusion
* Procedural
	* Open necrosectomy\
		* **Infected** collections should be managed **non-operatively** for **>4 weeks** to allow fibrous walls and liquefaction to occur
		* Indications for surgery usually are other abdominal complication, e.g.:
			* Perforation
			* Bleeding
			* Mesenteric ischaemia
	* Needle aspiration
	* For gallstone pancreatitis:
		* Cholecystectomy\
		Indicated due to high (up to 90%) rate of recurrence.
			* Mild cases can proceed immediately
			* More severe disease should be stabilised first
		* ERCP
			* ↓ Morbidity and mortality in **mild** gallstone pancreatitis
	* Plasmapheresis\
	For hypertriglyceridaemia, with very little supportive evidence.


**Supportive care**:

:::column-margin
Feeding:

* Maintains gut mucosal barrier
* Corrects nutritional deficiencies\
Many patients malnourished on presentation.
* ↓ Risk of secondary infection of necrotic pancreatic tissue
:::

* G
	* Feeding\
		* If non-intubated:
			* Oral diet as clinically tolerated
		* If intubated:
			* EN should be started once resuscitation finished
			* PN indicated only if EN fails or is contraindicated\
			EN ↓ infection, organ failure, and mortality compared with PN.
			* NJ feeding may be preferable to NG to avoid ↑ pancreatic secretion
		* If hypertriglyceridaemic:
			* Zero-fat diet initially
			* Low-fat diet once triglycerides normal


**Disposition**:

### Marginal and Ineffective Therapies

Prophylactic antifungal therapy is not recommended.

Various therapies aimed at generally ↓ pancreatic exocrine function are without evidence, and include:

* Octreotide
* Somatostatin
* H~2~-antagonists
* Atropine
* Calcitonin
* Glucagon
* Fluorouracil


Interventions aimed to ↓ protease secretion are also without evidence, and include:

* Aprotinin
* Gabexate mesilate

## Anaesthetic Considerations

## Complications

* Death\
5-10% mortality in severe disease.
* B
	* ARDS
* C
	* Shock
		* Distributive
		* Hypovolaemic
* G
	* Abdominal compartment syndrome
	* Pancreatic cysts\
	Do not merit surgical intervention unless:
		* Gastric outflow obstruction
		* Biliary obstruction
	* **Infected necrosis**
		* Usually arise at **10-14 days**
		* Carbapenem or tazocin preferable for good solid organ penetration
	* **Pancreatic abscess**\
	Infected collections are a major contributor to morbidity and mortality.
		* Usually arise at **4 weeks**
		* Amenable to percutaneous drainage


## Prognosis

Poor prognostic signs:

* Pancreatic necrosis
	* Pancreatic head necrosis is as severe as whole pancreatic necrosis
	* Pancreatic tail necrosis usually has a good prognosis

## Key Studies

{{< include /trials/waterfall.qmd >}}


---	

## References

1. de-Madaria E, Buxbaum JL, Maisonneuve P, et al. [Aggressive or Moderate Fluid Resuscitation in Acute Pancreatitis](https://www.nejm.org/doi/full/10.1056/NEJMoa2202884). New England Journal of Medicine. 2022;387(11):989-1000.
