# Acute Liver Failure

Rapidly progressive, life-threatening development of **coagulopathy** (INR >1.5), **encephalopathy**, and **jaundice** in a patient with a previously normal liver due to massive liver parenchymal injury. ALF is subclassified by time interval between jaundice and encephalopathy:

* **Hyperacute**\
Encephalopathy within 7 days. Typically:
	* Severe encephalopathy, coagulopathy, ↑ ICP, and very deranged LFTs\
	Encephalopathy usually preceeds jaundice.
	* Common aetiologies: paracetamol, viral hepatitis
	* Higher rate of spontaneous recovery
* **Acute**\
Encephalopathy within 28 days. Typically:
	* More gradual decline
	* Common aetiologies: idiosyncratic drug reactions, viral hepatitis
* **Subacute**\
Encephalopathy within 3 months. Typically:
	* Less deranged LFTs
	* Common aetiologies are drug or immune-mediated disease and *un*likely to be pregnancy-related or viral. 
	* Poorest recovery in absence of transplantation
	* Greatest degree of jaundice


:::column-margin
Acute Liver Failure is distinct from:

* **Acute Liver Injury**\
Coagulopathy and jaundice in absence of encephalopathy.
* **Acute on Chronic Liver Failure**\
Acute decline in liver function in patients with chronic liver disease.
:::

:::column-margin
Hepatic encephalopathy may complicate either acute liver failure or chronic liver disease, and is covered under @sec-hep_enc.
:::


## Epidemiology and Risk Factors

Rare:

* 400 cases annually in the UK


## Pathophysiology

Pathological processes:

* Direct hepatocyte damage
* Immune response
	* Local
	* Systemic
		* MODS
* Cerebral dysfunction
	* Oedema
	* Altered autoregulation


### Aetiology

:::column-margin
Cause varies substantially with geography.
:::

* **Vascular**
	* Ischaemia
	* Budd-Chiari Syndrome\
	Hepatic vein thrombosis, usually with an underlying procoagulant condition.
* **Infection**
	* Hepatitis A\
	Infection rarely leads to liver failure (<1%) and contributes to ~10% of infective cases.
	* Hepatitis B\
	25-75% of viral cases. **Reactivation** may occur in immunosuppressed patients.
	* Hepatitis C\
	Common cause of CLD but rarely causes acute failure.
	* Other viruses may cause rarely infection in the immunocompromised:
		* EBV
		* Measles
		* HSV 1/2
	* Dengue
	* Yellow fever
	* Lassa
* **Autoimmune**
* **Drugs**/toxins
	* **Paracetamol**\
	50-70% of cases in the developed world. Occurs due to:
		* Depletion of hepatic glutathione\
		Consumed in conjugating NAPQI, a Phase I metabolite of paracetamol.
		* NAPQI accumulation causes direct hepatocyte injury
	* Aspirin\
	Reye's syndrome.
	* Herbal
	* Halothane
	* Antituberculosis drugs
	* Alcohol
	* Ecstasy
	* *Amanita phalloides*\
	Mushroom poisoning. Usually presents with diarrhoea, followed by hepatic necrosis at 48-72 hours.
* Pregnancy-related\
	* Acute fatty liver of pregnancy
	* Severe pre-eclampsia
	* Liver rupture
* Hyperthermia
* Other
	* Wilson disease
	* Haemophagocytic syndrome


## Clinical Features

History:

* Overdose
* CNS
	* Encephalopathy
		* Confusion
		* Agitation
* GI
	* Nausea/Vomiting
	* Diarrhoea

Examination:

* Asterixis
* Intracranial hypertension
	* Hyperreflexia
	* Clonus
	* Hypertonicity
	* Cushing's triad
* Jaundice


## Diagnostic Approach and DDx

## Investigations

Laboratory:

* Blood
	* Liver function testing\
	Severity and pattern of injury:
		* Hepatocellular
		* Cholestatic
	* Point of care coagulation studies\
	*May* be more accurate than standard assays.
	* Coagulation studies
		* Synthetic function
	* Lactate\
	Failure of hepatic clearance.
	* Ammonia\
	Neurotoxin responsible for much of hepatic encephalopathy. ↑ Ammonia may reflect:
		* Hepatic metabolic dysfunction\
		Degree of hepatic dysfunction typically correlates with ammonia level, though not with the degree of encephalopathy.
		* ↑↑ Protein intake
		* ↑ GI ammonia production\
		Produced by gut bacteria.
		* ↓ Clearance\
		Urea cycle disorder.
	* UEC\
		* AKI
		* Electrolyte derangements
	* FBE
		* Anaemia
		* Thrombocytopaenia
		* Concurrent infection
	* Lipase/amylase
		* Associated pancreatitis
	* Paracetamol level
	* LDH\
	Malignancy.
	* Viral screen\
	Aetiology. Include:
		* Hepatitis A
		* Hepatitis B\
		Core antigen indicates infection. Surface antigen often negative.
		* Hepatitis C\
		Positive antibodies indicate infection.
		* Hepatitis E\
		Positive antibodies indicate infection. Usually faecal-oral, though a subtype is transmissable by blood.
		* EBV
		* HSV
		* VZV
		* HIV 1/2
	* Autoimmune screen
		* ANA\
		Autoimmune.
		* Anti-smooth muscle Ab\
		Autoimmune.
		* Anti-mitochondrial Ab\
		Primary sclerosing cholangitis.
		* Copper studies\
		Wilson's disease.
	* Blood cultures
	* Pregnancy test
* Urine
	* Drug screen
		* Paracetamol


**Imaging**:

* TTE
	* RV function
	* Transplant assessment
* Liver ultrasound
	* Splenomegaly
	* Ascites
	* Nodularity
	* Hepatomegaly
	* Portal blood flow
	* Portal patency
* CT\
Triple-phase liver.


**Other**:

* Liver biopsy
	* Rare in acute setting due to coagulopathy\
	Transjugular route safest.
	* Non-specific necrosis most common finding
	* May be useful in diagnosis of:
		* Autoimmune
		* Wilson's disease

## Management

:::priority
* Prevent **cerebral oedema** and treat concurrent @sec-hep_enc
* Manage **vasodilatory shock**
* **Treat** concurrent **sepsis**\
Gram negative and fungal.
* Manage **coagulopathy**
* Early **identification** of patients for **transplant**
	* Significant improvement in outcomes with **emergency liver transplantation**
	* **Early** escalation to **critical care** and early referral to a **specialist centre** is essential
:::

**Resuscitation**:


**Specific therapy**:

* Paracetamol overdose
	* **N-acetylcysteine** (NAC)\
		* Cornerstone of therapy as early administration results in significant reduction in mortality (to <1%), though even late administration may improve outcome
		* Dosing based on Prescott nomogram
* Viral hepatitis
	* Antivirals
	* Hepatitis B
		* Lamivudine\
		Benefit if given early.
* Alcoholic hepatitis
* Autoimmune hepatitis
	* Steroids
* Mushroom poisoning
	* Forced diuresis\
	↑ Renal clearance of toxin. Avoid hypovolaemia.
* Wilson's disease
	* D-Penicillamine\
	Chelates copper. Withdrawal of chronic treatment may precipitate failure.
* Hepatic vein thrombosis
	* Thrombolysis
	* Clot retrieval
	* TIPS

:::column-margin
Management of paracetamol overdose is covered under @sec-pmolod.
:::

**Supportive care**:

:::column-margin
Invasive intracranial pressure monitoring associated with ~10% intracranial haemorrhage rate.
:::

* A\
Consider **securing airway** if:
	* High grade (III/IV) hepatic encephalopathy
	* Need for transfer
* B
	* **Lung protective ventilation**\
	ARDS risk.
	* Drain pleural effusions
* C
	* **Volume resuscitation**\
	Can be aggressive in absence of pulmonary hypertension.
	* MAP 65-70mmHg\
	Or **higher** if targeting **CPP** with concurrent hepatic encephalopathy.
		* Noradrenaline 1^st^ line
		* Vasopressin 2^nd^ line
	* **Corticosteroids** for vasopressor-refractory shock
		* Hydrocortisone 50mg IV Q6H
* E
	* ↓ **BSL**\
	Use high-concentration dextrose to avoid cerebral oedema/↓ Na^+^.
* F

	* **RRT**\
		* Avoid citrate!
		* Use bicarbonate buffered solutions
		* CRRT strongly preferred for haemodynamic stability
		* Haemodiafiltration preferred\
		Dialysis is probably more effective than filtration, but both mechanisms are effective.
		* In addition to standard indications, initiate for:
			* Hyperammonaemia (>100μmol/L)\
				* Aim <60μmol/L once commenced
				* High doses (45-90mL/kg/hr) are often used to ↑ ammonia clearance\
				↑ Rate by 50% each time.
			* Hyperthermia
	* Avoid positive fluid balance
* G
	* Early low-protein **enteral feeding**
		* May have ↑ metabolic requirements\
		* Feeding may need to be interrupted if ammonia ↑ 
	* Hyperammonaemia
		* **Lactulose**\
		Controversial. May ↓ hepatic encephalopathy but lead to gaseous intestinal distension.
	* **PPI**
	* **Drain ascites**\
	For haemodynamic benefit.
	* **Extra-corporeal hepatic support**\
	 Broadly, ↓ encephalopathy and ↑ haemodynamic function without mortality benefit.
		* Should be regarded as experimental
		* Can be considered for severe refractory vasodilatory shock
		* Include:
			* Coupled Plasma Filtration Adsorption (CPDFA)
			* Molecular Adsorbant Recirculation System (MARS)
			* Single Pass Albumin Dialysis (SPAD)
		* Underlying mechanism is either:
			* Biological\
			Using human/porcine cells.
			* Mechanical\
			Molecular filtration.
{{< include /includes/liver_coag.qmd >}}



**Disposition**:

* Liver transplant centre\
Referral if:
	* Hepatic encephalopathy
	* Ammonia >100μmol/L


### Marginal and Ineffective Therapies



## Anaesthetic Considerations

## Complications

* Death
	* Intracranial hypertension\
	Classically if untreated.
	* Sepsis/multiorgan failure
* A
	* Unprotected airway
* B
	* ARDS\
	Relatively intolerant of permissive hypercapnoea due to ↑ ICP concerns.
	* Pleural effusions
* C
	* Distributive shock
* D
	* Intracranial hypertension\
	Usually develops rapidly with little time for adaptation.
	* Hepatic encephalopathy
* F
	* AKI (hepatorenal syndrome)\
	40-80% of cases.
		* ↑ In paracetamol toxicity (directly nephrotoxic)
* G
	* ↓ BSL
	* Pancreatitis
	* Ascites
* H
	* Coagulopathy\
	Clinical manifestations often not in consistent with assays.
	* Bone marrow suppression
		* Thrombocytopaenia
* I
	* Infection\
	↑ Susceptibility due to functional immunosuppression.


## Prognosis

Spontaneous recovery occurs in only **40%**. Factors:

* Age\
↑ Mortality with ↑ age.
* Aetiology\
↓ Mortality with pregnancy-related causes.
* Acuity\
↑ Mortality with ↑ acuity.


Transplantation:

* 80% 5-year survival following liver transplant for ALF


### Scoring {#sec-alfscoring}

:::info
Eligibility for transplantation is determined using one of the prognostic scores, such as MELD or the King's College criteria.
:::

: King's College Criteria for Liver Transplantation

+-----------------------------+-----------------------------+
| Paracetamol Toxicity        | Other Cause                 |
+=============================+=============================+
| * pH <7.25 and              | * PT >100s                  |
| * Lactate >3mmol/L          |                             |
+-----------------------------+-----------------------------+
|  Or:                        | Or 3 of:                    |
|                             |                             |
|  * PT >100s and             | * Age <10 or >40            |
|  * Cr >300μmol/L and        | * Hyperacute                |
|  * Grade 3/4 encephalopathy | * Seronegative/drug induced |
|                             | * Bilirubin >300μmol/L      |
|                             | * PT >50s                   |
+-----------------------------+-----------------------------+

The King's criteria are widely used but validation is less well supported, particularly in the paracetamol cohort.

An alternative to the King's criteria is the MELD score, which predicts 90 day survival using:

:::column-margin
The MELD score:

* Is calculated by sum of logarithms\
Use an app.
* Initially developed to predict mortality for TIPS
* Subsequently used to prognosticate and prioritise liver transplantation
:::

* Bilirubin
* INR
* Creatinine

| MELD Score | Mortality |
| *--------- | *-------- |
| >40        | 71%       |
| 30-39      | 53%       |
| 20-29      | 20%       |
| 10-19      | 6%        |
| <9         | 2%        |


## Key Studies



---

## References

1. Aziz, Riaz, Jennifer Price, and Banwari Agarwal. [Management of Acute Liver Failure in Intensive Care](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7892353/pdf/main.pdf). BJA Education 21, no. 3 (March 2021): 110–16. https://doi.org/10.1016/j.bjae.2020.11.006.
2. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.
1. Van Eldere A, Pirani T. [Liver intensive care for the general intensivist](https://associationofanaesthetists-publications.onlinelibrary.wiley.com/doi/10.1111/anae.15956). Anaesthesia. 2023;78(7):884-901.
1. Warrillow SJ, Bellomo R. [Preventing Cerebral Oedema in Acute Liver Failure: The Case for Quadruple-H Therapy](https://journals.sagepub.com/doi/10.1177/0310057X1404200114). Anaesth Intensive Care. 2014;42(1):78-88.
