# Chronic Liver Disease {#sec-cld}

End result of a process of progressive destruction and regeneration of liver parenchyma, leading to fibrosis and cirrhosis. Cirrhosis is:

* A leading cause of death
* Greatly ↑ perioperative morbidity and mortality

## Epidemiology and Risk Factors

## Pathophysiology

Key pathophysiological processes relate impairment of key liver functions:

* Metabolic
	* Clearance of vasoactive mediators\
	Typically altered baseline haemodynamics:
		* ↑ CO
		* ↓ SVR
			* ↓ Vasopressor response
* Synthetic
	* Coagulopathy\
	↓ Synthesis of both procoagulant (predominantly II, V, VII, X) and anticoagulant (protein C, protein S, antithrombin III) factors leads to:
		* Highly deranged clotting studies
		* Variable *in vivo* clotting activity\
		Often normal behaviour in stable patients, but can easily become both prothrombotic or coagulopathic.

### Aetiology

Common causes include:

* Viral hepatitis
	* Hepatitis B
	* Hepatitis C
* Autoimmune disease
* Alcoholic liver disease

Rarer causes include:

* Cholestasis
	* Primary biliary cirrhosis
	* Sclerosing cholangitis
* Vascular
	* Venous obstruction
	* Budd-Chiari syndrome
* Infiltrative
	* Amyloidosis
* Drugs
* Toxins
* Metabolic diseases
	* Wilson's Disease
	* Haemochromatosis
	* α1-antitrypsin

## Clinical Manifestations

Classified into:

* Hepatic
* Extrahepatic
	* Cardiac\
	Classically a hyperdynamic, ↑ CO, ↓↓ SVR (possibly ↓ BP despite ↑ CO) state.
	* Endocrine
		* Secondary hyperaldosteronism
	* Renal
		* Hepatorenal syndrome\
	* GIT
		* Portal hypertension\
		Portal pressure **>10mmHg**. Leads to:
			* Collateral venous circulation
			* Ascites
			* Splenomegaly\
			Thrombocytopaenia due to sequestration.
			* Oesophageal varices
			* Caput medusae
		* Delayed gastric emptying
		* Spider naevi
	* Haematological
		* Anaemia\
		Multiple potential causes:
			* GIT bleeding
			* Hypersplenic haemolysis
			* Malnutrition
			* Anaemia of chronic disease
		* Coagulopathy

:::column-margin
Porto-pulmonary hypertension and hepatopulmonary syndrome are discussed later, under complications.
:::

### MELD Score

Uses:

* Serum bilirubin
* Serum creatinine
* INR

## Diagnostic Approach and DDx


## Investigations

Bloods:

* FBE
	* Anaemia
	* Thrombocytopaenia
* Coagulation assays
	* PT\
	Prognostic indicator, especially post-surgery in CLD.
* UEC
	* Baseline renal function important

Imaging:

* Ultrasound
	* Shear wave elastography
		* Focused ultrasound to create "shear waves" within the tissue
		* The speed of the wave is measured and can be used to quantify the degree of cirrhosis
		* ↑ Wave speed indicates ↑ liver stiffness
* Magnetic Resonance Elastography

## Management

### Anaesthetic Considerations

:::caution
End-stage liver disease associated with high perioperative morbidity and mortality.
:::

* A
	* Aspiration risk\
	Due to delayed gastric emptying. Consider RSI.
* B
	* Presence of ascites or pleural effusions\
	Restrict alveolar ventilation, FRC, and predispose to atelectasis and hypoxia.
* C
	* Presence of alcoholic cardiomyopathy
	* Typically hyperdynamic circulation\
	High CO, low SVR.
* D
	* Wernicke's encephalopathy
	* Hepatic encephalopathy
* E
	* Neuromuscular blockade
		* Non-depolarising agents:
			* Require ↑ doses\
			Due to ↑ V~D~.
			* Aminosteroids have prolonged elimination
* H
	* Coagulopathy\


### Marginal and Ineffective Therapies

## Complications

* B
	* Ascites
* C
	* Hepatopulmonary syndrome
	* Porto-pulmonary hypertension
* D
	* Hepatic encephalopathy
* F
	* Hepatorenal syndrome
* G
	* **Portal hypertension**
		* **Variceal bleeding**\
		May be precipitated by infection due to an ↑ in sinusoidal and portal venous pressure. Therefore, patients with **variceal bleeds should receive antibiotics**.
		* **Ascites**
			* Spontaneous bacterial peritonitis
	* Hepatocellular carcinoma
	* Decompensation
* I
	* Sepsis\
	Infections are:
		* More common in patients with cirrhosis
			* Physical debilitation
			* Deconditioning
			* Malnourishment
			* ↓ Phagocytic function
		* Associated with higher mortality and morbidity\
		Up to 70% mortality. Higher incidence of sepsis associated:
			* AKI
			* Encephalopathy
			* Coagulopathy
		* The highest cause of death in cirrhotic patients

:::column-margin
Causative organisms (in order of likelihood) include:

* *E. Coli*
* *S. Aureus*
* *E. Faecalis*
* *S. Pneumoniae*
* *P. aeruginosa*
* *S. Epidermidis*
:::

:::column-margin
Management of gastrointestinal bleeding is covered under @sec-gib.
:::

:::column-margin
Hepatorenal syndrome is covered under @sec-hepatorenal.
:::

### Hepatopulmonary Syndrome {#sec-hepatopulmonary}

Intrapulmonary shunt secondary to indiscriminate pulmonary vasodilation and angiogenesis. Hepatopulmonary syndrome:

* Occurs in 20% of cirrhotic patients
* Occurs due to ↓ hepatic clearance of endogenous vasodilators or ↑ nitric oxide synthetase activity, leading to:
	* Impaired hypoxic pulmonary vasoconstriction
	* ↑ Angiogenesis, producing AVM
* Associated with high mortality
	* 15% at 90 days
	* 40% at 1 year
* Overwhelming majority resolve following liver transplantation\
May take up to 1 year, indicating some degree of pathological vascular remodelling.


### Porto-pulmonary Hypertension {#sec-portopulmonary}

Pulmonary hypertension in the setting of portal hypertension. Porto-pulmonary hypertension is:

* An ominous finding
* Secondary to:
	* ↓ Hepatic clearance of vasoconstrictors
	* Thromboembolic disease
* Responsive to pulmonary vasodilators\
May require sustained (>3 months) treatment to effect remodelling.


:::column-margin
Pulmonary hypertension *not* due to left heart failure (i.e. ↑ PAP with a normal PCWP and normal PVR) is common (20%) in patients presenting for liver transplant, but the majority reflects an ↑ in CO and is not in itself a poor prognostic sign.
:::


## Prognosis


### Child-Pugh Score {#sec-childpugh}

:::info
This is included mostly for completeness, the Child-Pugh score is inferior to standard ICU scoring systems for outcome prediction.
\
MELD (see @sec-alfscoring) is equally poor in predicting outcome in the ICU patient.
:::

Score to assess prognosis of cirrhosis:

* Initially developed to predict perioperative mortality
* Validated for prognostication and to assess necessity of liver transplantation

: Child-Pugh Score Components

| Value                          | 1 point  | 2 points                   | 3 points                       |
| ------------------------------ | -------- | -------------------------- | ------------------------------ |
| **Total bilirubin** (μmol/L)   | ⩽34      | 34-50                      | ⩾50                            |
| **Serum albumin** (g/dL)       | ⩾3.5     | 2.8-3.5                    | ⩽2.8                           |
| **PT** (s)                     | ⩽4       | 4-6                        | ⩾6                             |
| **INR**                        | ⩽1.7     | 1.7-2.3                    | ⩾2.3                           |
| **Ascites**                    | None     | Mild/medically controlled  | Moderate to severe/refractory  |
| **Hepatic encephalopathy**     | None     | Grade I-II                 | Grade III-IV                   |

:::column-margin
There are many issues with the Child-Pugh score:

* Subjective assessments have inter-observer variability
* Evaluation of ascites has progressed since the '60s when the score was developed
* Excludes effects of concomitant disease
:::

Patients are then risk stratified as follows:

: Child-Pugh Scoring

| Class  | Points  | One-year survival  |
| ------ | ------- | ------------------ |
| A      | 5-6     | 100%               |
| B      | 7-9     | 80%                |
| C      | 10-15   | 45%                |

### MELD Score {#sec-meld}

The MELD score predicts 90 day survival using:

:::column-margin
The MELD score is:

* Calculated by sum of logarithms\
Use an app.
* Historically used to predict mortality for TIPS
* Subsequently used to prognosticate and prioritise liver transplantation
* A better predictor of short-term mortality
:::

* Bilirubin
* INR
* Creatinine

: Meld Score

| MELD Score | Mortality |
| :--------- | :-------- |
| >40        | 71%       |
| 30-39      | 53%       |
| 20-29      | 20%       |
| 10-19      | 6%        |
| <9         | 2%        |


## Key Studies


---

## References

1. Lata J. Hepatorenal syndrome. World J Gastroenterol. 2012 Sep 28;18(36):4978–84. 
2. Vaja R, McNicol L, Sisley I. Anaesthesia for patients with liver disease. Contin Educ Anaesth Crit Care Pain. 2010 Feb 1;10(1):15–9. 
