# Mesenteric Ischaemia

Uncommon abdominal surgical emergency subclassified into:

* Occlusive ischaemia\
Presentation with abdominal pain and GI symptoms followed by peritonism and shock. Causes include:
	* Plaque rupture and thrombus
	* Arterial embolism
	* Venous occlusion\
	Rare.
* Non-occlusive ischaemia (NOMI)\
Severe GI symptoms in the setting of severe circulatory failure, usually with evidence of other organ failures (AKI, ischaemic hepatitis).

## Epidemiology and Risk Factors

## Pathophysiology

### Aetiology

## Clinical Manifestations

## Diagnostic Approach and DDx

## Investigations

Radiology:

* CT
	* Portal venous gas
	* Intestinal pneumatosis


**Other**:

* Endoscopy
	* Confirm ischaemia

## Management

**Resuscitation**:\

ABC approach. Comment on team coordination and clinical priorities.
**Specific therapy**:

* Pharmacological
* Procedural
* Physical

**Supportive care**:

**Disposition**:

### Marginal and Ineffective Therapies

## Anaesthetic Considerations

## Complications

## Prognosis

## Key Studies


---

## References

1. Bersten, A. D., & Handy, J. M. (2018). Oh’s Intensive Care Manual. Elsevier Gezondheidszorg.