# Systematic Examination

* Patient
	* Reposition
	* Exposure\
	Fold blankets to the midline.


## General Appearance

: General Appearance

+---------------------------------+----------------------------------------+-----------+------------+--------------+
| Component                       | Inspection                             | Palpation | Percussion | Auscultation |
+=================================+========================================+===========+============+==============+
| **General**                     | * Obesity                              |           |            |              |
|                                 | * Cachexia                             |           |            |              |
|                                 | * Wounds                               |           |            |              |
|                                 | * Drains                               |           |            |              |
|                                 | * Dressings                            |           |            |              |
|                                 | * Burns                                |           |            |              |
|                                 | * Lines                                |           |            |              |
|                                 |     * Access                           |           |            |              |
|                                 | * Position\                            |           |            |              |
|                                 | Signs of recovery include:             |           |            |              |
|                                 |     * Sleeping in the lateral position |           |            |              |
|                                 |     * Lying with crossed legs          |           |            |              |
+---------------------------------+----------------------------------------+-----------+------------+--------------+
| **Respiratory**                 | * Steroid purpura                      |           |            |              |
|                                 | * Cushingoid appearance                |           |            |              |
|                                 | * Tracheal aspirates                   |           |            |              |
+---------------------------------+----------------------------------------+-----------+------------+--------------+
| **Cardiovascular**              | * Xanthoma                             |           |            |              |
|                                 | * Marfanoid habitus                    |           |            |              |
+---------------------------------+----------------------------------------+-----------+------------+--------------+
| **Neurological**                |                                        |           |            |              |
+---------------------------------+----------------------------------------+-----------+------------+--------------+
| **Endocrine** and **Metabolic** |                                        |           |            |              |
+---------------------------------+----------------------------------------+-----------+------------+--------------+
| **Renal**                       |                                        |           |            |              |
+---------------------------------+----------------------------------------+-----------+------------+--------------+
| **Gastrointestinal**            |                                        |           |            |              |
+---------------------------------+----------------------------------------+-----------+------------+--------------+
| **Haematological**              |                                        |           |            |              |
+---------------------------------+----------------------------------------+-----------+------------+--------------+
| **Integumentary**               | * Muscle bulk                          |           |            |              |
|                                 | * Wasting                              |           |            |              |
|                                 | * Malnutrition                         |           |            |              |
|                                 | * Cachexia                             |           |            |              |
|                                 |                                        |           |            |              |
+---------------------------------+----------------------------------------+-----------+------------+--------------+
| **Trauma**                      |                                        |           |            |              |
+---------------------------------+----------------------------------------+-----------+------------+--------------+
| **Infective**                   |                                        |           |            |              |
+---------------------------------+----------------------------------------+-----------+------------+--------------+
| **Malignant**                   |                                        |           |            |              |
+---------------------------------+----------------------------------------+-----------+------------+--------------+
| **Toxic**                       |                                        |           |            |              |
+---------------------------------+----------------------------------------+-----------+------------+--------------+
| **Immune**                      | * Vasculitic rashes                    |           |            |              |
+---------------------------------+----------------------------------------+-----------+------------+--------------+
| **Congenital**                  |                                        |           |            |              |
+---------------------------------+----------------------------------------+-----------+------------+--------------+
| **Obstetric**                   | * Oedema                               |           |            |              |
|                                 | * Bruising/ecchymoses                  |           |            |              |
+---------------------------------+----------------------------------------+-----------+------------+--------------+

## Hands

: Hands

+---------------------------------+---------------------------+-------------------------------+------------+
| Component                       | Inspection                | Palpation                     | Percussion |
+=================================+===========================+===============================+============+
| **General**                     |                           |                               |            |
+---------------------------------+---------------------------+-------------------------------+------------+
| **Respiratory**                 |                           | * Nicotine staining           |            |
|                                 |                           | * Clubbing                    |            |
|                                 |                           | * Intraosseous muscle wasting |            |
+---------------------------------+---------------------------+-------------------------------+------------+
| **Cardiovascular**              |                           | * Stigmata of IE              |            |
|                                 |                           |     * Janeway lesions         |            |
|                                 |                           |     * Osler's nodes           |            |
|                                 |                           |     * Splinter haemorrhages   |            |
|                                 |                           | * Clubbing                    |            |
+---------------------------------+---------------------------+-------------------------------+------------+
| **Neurological**                |                           |                               |            |
+---------------------------------+---------------------------+-------------------------------+------------+
| **Endocrine** and **Metabolic** |                           |                               |            |
+---------------------------------+---------------------------+-------------------------------+------------+
| **Renal**                       |                           |                               |            |
+---------------------------------+---------------------------+-------------------------------+------------+
| **Gastrointestinal**            |                           |                               |            |
+---------------------------------+---------------------------+-------------------------------+------------+
| **Haematological**              |                           |                               |            |
+---------------------------------+---------------------------+-------------------------------+------------+
| **Integumentary**               | * Dupuytren's contracture |                               |            |
+---------------------------------+---------------------------+-------------------------------+------------+
| **Trauma**                      |                           |                               |            |
+---------------------------------+---------------------------+-------------------------------+------------+
| **Infective**                   |                           |                               |            |
+---------------------------------+---------------------------+-------------------------------+------------+
| **Malignant**                   |                           |                               |            |
+---------------------------------+---------------------------+-------------------------------+------------+
| **Toxic**                       |                           |                               |            |
+---------------------------------+---------------------------+-------------------------------+------------+
| **Immune**                      |                           |                               |            |
+---------------------------------+---------------------------+-------------------------------+------------+
| **Congenital**                  |                           |                               |            |
+---------------------------------+---------------------------+-------------------------------+------------+
| **Obstetric**                   |                           |                               |            |
+---------------------------------+---------------------------+-------------------------------+------------+

## Arms

: Arms

+---------------------------------+------------------------------------+----------------------+------------+---------------+
| Component                       | Inspection                         | Palpation            | Percussion | Auscultation  |
+=================================+====================================+======================+============+===============+
| **General**                     | * Trackmarks                       |                      |            |               |
|                                 | * Long-term lines                  |                      |            |               |
|                                 |     * PICC                         |                      |            |               |
|                                 |     * Midline                      |                      |            |               |
+---------------------------------+------------------------------------+----------------------+------------+---------------+
| **Respiratory**                 |                                    |                      |            |               |
+---------------------------------+------------------------------------+----------------------+------------+---------------+
| **Cardiovascular**              | * Radial and brachial access sites |                      |            |               |
|                                 |     * Evidence of vascular sheath  |                      |            |               |
|                                 | * Previous radial graft harvesting |                      |            |               |
+---------------------------------+------------------------------------+----------------------+------------+---------------+
| **Neurological**                |                                    |                      |            |               |
+---------------------------------+------------------------------------+----------------------+------------+---------------+
| **Endocrine** and **Metabolic** |                                    |                      |            |               |
+---------------------------------+------------------------------------+----------------------+------------+---------------+
| **Renal**                       | * AV Fistula                       | * Fistula thrill     |            | * Fistula hum |
+---------------------------------+------------------------------------+----------------------+------------+---------------+
| **Gastrointestinal**            |                                    |                      |            |               |
+---------------------------------+------------------------------------+----------------------+------------+---------------+
| **Haematological**              |                                    |                      |            |               |
+---------------------------------+------------------------------------+----------------------+------------+---------------+
| **Integumentary**               |                                    | * Tense compartments |            |               |
+---------------------------------+------------------------------------+----------------------+------------+---------------+
| **Trauma**                      |                                    |                      |            |               |
+---------------------------------+------------------------------------+----------------------+------------+---------------+
| **Infective**                   |                                    |                      |            |               |
+---------------------------------+------------------------------------+----------------------+------------+---------------+
| **Malignant**                   |                                    |                      |            |               |
+---------------------------------+------------------------------------+----------------------+------------+---------------+
| **Toxic**                       |                                    |                      |            |               |
+---------------------------------+------------------------------------+----------------------+------------+---------------+
| **Immune**                      |                                    | * Lymphadenopathy    |            |               |
+---------------------------------+------------------------------------+----------------------+------------+---------------+
| **Congenital**                  |                                    |                      |            |               |
+---------------------------------+------------------------------------+----------------------+------------+---------------+
| **Obstetric**                   |                                    |                      |            |               |
+---------------------------------+------------------------------------+----------------------+------------+---------------+
	
## Head and Neck

: Head and Neck

+---------------------------------+---------------------+---------------------+------------+--------------+
| Component                       | Inspection          | Palpation           | Percussion | Auscultation |
+=================================+=====================+=====================+============+==============+
| **General**                     | * Colour\           |                     |            |              |
|                                 | ↑ Mortality with:   |                     |            |              |
|                                 |     * Pallor        |                     |            |              |
|                                 |     * Cyanosis      |                     |            |              |
|                                 |     * Greyish-ness  |                     |            |              |
+---------------------------------+---------------------+---------------------+------------+--------------+
| **Respiratory**                 | * ETT               | * Tracheal position |            |              |
|                                 |     * Size          |                     |            |              |
|                                 |     * Depth         |                     |            |              |
|                                 | * Tracheostomy      |                     |            |              |
|                                 | * Tracheostomy scar |                     |            |              |
|                                 | * Tracheal tug      |                     |            |              |
+---------------------------------+---------------------+---------------------+------------+--------------+
| **Cardiovascular**              | * Xantholasma       |                     |            |              |
|                                 | * Corneal arcus     |                     |            |              |
|                                 | * Facial swelling\  |                     |            |              |
|                                 | SVC obstruction.    |                     |            |              |
+---------------------------------+---------------------+---------------------+------------+--------------+
| **Neurological**                |                     | * Meningism         |            |              |
+---------------------------------+---------------------+---------------------+------------+--------------+
| **Endocrine** and **Metabolic** |                     |                     |            |              |
+---------------------------------+---------------------+---------------------+------------+--------------+
| **Renal**                       |                     |                     |            |              |
+---------------------------------+---------------------+---------------------+------------+--------------+
| **Gastrointestinal**            | * Scleral jaundice  |                     |            |              |
+---------------------------------+---------------------+---------------------+------------+--------------+
| **Haematological**              |                     |                     |            |              |
+---------------------------------+---------------------+---------------------+------------+--------------+
| **Integumentary**               |                     |                     |            |              |
+---------------------------------+---------------------+---------------------+------------+--------------+
| **Trauma**                      | * Battle's sign     |                     |            |              |
|                                 | * Mastoid bruising  |                     |            |              |
|                                 | * Haemotympanum     |                     |            |              |
|                                 | * CSF otohorrhoea   |                     |            |              |
|                                 | * CSF rhinorrhoea   |                     |            |              |
+---------------------------------+---------------------+---------------------+------------+--------------+
| **Infective**                   |                     |                     |            |              |
+---------------------------------+---------------------+---------------------+------------+--------------+
| **Malignant**                   |                     |                     |            |              |
+---------------------------------+---------------------+---------------------+------------+--------------+
| **Toxic**                       |                     |                     |            |              |
+---------------------------------+---------------------+---------------------+------------+--------------+
| **Immune**                      |                     | * Lymphadenopathy   |            |              |
+---------------------------------+---------------------+---------------------+------------+--------------+
| **Congenital**                  |                     |                     |            |              |
+---------------------------------+---------------------+---------------------+------------+--------------+
| **Obstetric**                   |                     |                     |            |              |
+---------------------------------+---------------------+---------------------+------------+--------------+


## Chest

: Chest

+---------------------------------+-----------------------------+------------------------+------------+--------------------+
| Component                       | Inspection                  | Palpation              | Percussion | Auscultation       |
+=================================+=============================+========================+============+====================+
| **General**                     |                             |                        |            |                    |
+---------------------------------+-----------------------------+------------------------+------------+--------------------+
| **Respiratory**                 | * Hyper-expansion           | * Chest expansion      |            | * Breath sounds    |
|                                 | * Work of breathing         |                        |            |     * Wheeze       |
|                                 |     * Intercostal recession |                        |            |     * Crepitations |
|                                 |     * Tracheal tug          |                        |            |     * Rales        |
+---------------------------------+-----------------------------+------------------------+------------+--------------------+
| **Cardiovascular**              | * Sternotomy                | * Heave/thrills        |            | * Murmurs          |
|                                 | * CPR bruising              | * Apex beat\           |            | * Breath sounds    |
|                                 | * Epicardial pacing wires   | Displaced.             |            |     * Wheeze       |
|                                 | *                           | * PPM                  |            |                    |
|                                 |                             | * Sternotomy stability |            |                    |
+---------------------------------+-----------------------------+------------------------+------------+--------------------+
| **Neurological**                |                             |                        |            |                    |
+---------------------------------+-----------------------------+------------------------+------------+--------------------+
| **Endocrine** and **Metabolic** |                             |                        |            |                    |
+---------------------------------+-----------------------------+------------------------+------------+--------------------+
| **Renal**                       |                             |                        |            |                    |
+---------------------------------+-----------------------------+------------------------+------------+--------------------+
| **Gastrointestinal**            | * Jaundice                  |                        |            |                    |
|                                 | * Gynaecomastia             |                        |            |                    |
+---------------------------------+-----------------------------+------------------------+------------+--------------------+
| **Haematological**              |                             |                        |            |                    |
+---------------------------------+-----------------------------+------------------------+------------+--------------------+
| **Integumentary**               |                             |                        |            |                    |
+---------------------------------+-----------------------------+------------------------+------------+--------------------+
| **Trauma**                      |                             |                        |            |                    |
+---------------------------------+-----------------------------+------------------------+------------+--------------------+
| **Infective**                   |                             |                        |            |                    |
+---------------------------------+-----------------------------+------------------------+------------+--------------------+
| **Malignant**                   |                             |                        |            |                    |
+---------------------------------+-----------------------------+------------------------+------------+--------------------+
| **Toxic**                       |                             |                        |            |                    |
+---------------------------------+-----------------------------+------------------------+------------+--------------------+
| **Immune**                      |                             |                        |            |                    |
+---------------------------------+-----------------------------+------------------------+------------+--------------------+
| **Congenital**                  |                             |                        |            |                    |
+---------------------------------+-----------------------------+------------------------+------------+--------------------+
| **Obstetric**                   |                             |                        |            |                    |
+---------------------------------+-----------------------------+------------------------+------------+--------------------+

## Abdomen

: Abdomen

+---------------------------------+------------------------+-------------------+------------+--------------+
| Component                       | Inspection             | Palpation         | Percussion | Auscultation |
+=================================+========================+===================+============+==============+
| **General**                     |                        |                   |            |              |
+---------------------------------+------------------------+-------------------+------------+--------------+
| **Respiratory**                 |                        |                   |            |              |
+---------------------------------+------------------------+-------------------+------------+--------------+
| **Cardiovascular**              | * Femoral access sites | * Liver           |            |              |
|                                 |                        |     * Size        |            |              |
|                                 |                        |     * Pulsatility |            |              |
+---------------------------------+------------------------+-------------------+------------+--------------+
| **Neurological**                |                        |                   |            |              |
+---------------------------------+------------------------+-------------------+------------+--------------+
| **Endocrine** and **Metabolic** |                        |                   |            |              |
+---------------------------------+------------------------+-------------------+------------+--------------+
| **Renal**                       |                        |                   |            |              |
+---------------------------------+------------------------+-------------------+------------+--------------+
| **Gastrointestinal**            | * Jaundice             | * Liver           |            |              |
|                                 | * Cullen's sign        |     * Size        |            |              |
|                                 | * Grey-Turner's sign   |     * Pulsatility |            |              |
|                                 | * Tubes                | * Liver           |            |              |
|                                 |    * PTC               |     * Texture     |            |              |
|                                 |    * PEG               |     * Pulsatility |            |              |
|                                 |    * PEJ               | * Splenomegaly    |            |              |
|                                 |                        |                   |            |              |
|                                 |                        |                   |            |              |
|                                 |                        |                   |            |              |
|                                 |                        |                   |            |              |
+---------------------------------+------------------------+-------------------+------------+--------------+
| **Haematological**              |                        | * Hepatomegaly    |            |              |
|                                 |                        | * Splenomegaly    |            |              |
+---------------------------------+------------------------+-------------------+------------+--------------+
| **Integumentary**               |                        |                   |            |              |
+---------------------------------+------------------------+-------------------+------------+--------------+
| **Trauma**                      |                        |                   |            |              |
+---------------------------------+------------------------+-------------------+------------+--------------+
| **Infective**                   |                        |                   |            |              |
+---------------------------------+------------------------+-------------------+------------+--------------+
| **Malignant**                   |                        |                   |            |              |
+---------------------------------+------------------------+-------------------+------------+--------------+
| **Toxic**                       |                        |                   |            |              |
+---------------------------------+------------------------+-------------------+------------+--------------+
| **Immune**                      |                        | * Lymphadenopathy |            |              |
+---------------------------------+------------------------+-------------------+------------+--------------+
| **Congenital**                  |                        |                   |            |              |
+---------------------------------+------------------------+-------------------+------------+--------------+
| **Obstetric**                   | * Fundal examination   |                   |            |              |
|                                 |     * Height           |                   |            |              |
|                                 |     * Presenting part  |                   |            |              |
|                                 |     * Lie              |                   |            |              |
|                                 |     * Liquor volume    |                   |            |              |
+---------------------------------+------------------------+-------------------+------------+--------------+


## Legs

: Legs

+---------------------------------+-------------------------------+------------------------+------------+--------------+
| Component                       | Inspection                    | Palpation              | Percussion | Auscultation |
+=================================+===============================+========================+============+==============+
| **General**                     | * Muscle wasting              |                        |            |              |
+---------------------------------+-------------------------------+------------------------+------------+--------------+
| **Respiratory**                 |                               |                        |            |              |
+---------------------------------+-------------------------------+------------------------+------------+--------------+
| **Cardiovascular**              | * Groin vascular access sites | * Peripheral pulses    |            |              |
|                                 | * Peripheral oedema           |     * Femoral          |            |              |
|                                 |                               |     * Popliteal        |            |              |
|                                 |                               |     * Posterior tibial |            |              |
|                                 |                               |     * Dorsalis pedis   |            |              |
+---------------------------------+-------------------------------+------------------------+------------+--------------+
| **Neurological**                |                               |                        |            |              |
+---------------------------------+-------------------------------+------------------------+------------+--------------+
| **Endocrine** and **Metabolic** |                               |                        |            |              |
+---------------------------------+-------------------------------+------------------------+------------+--------------+
| **Renal**                       |                               |                        |            |              |
+---------------------------------+-------------------------------+------------------------+------------+--------------+
| **Gastrointestinal**            |                               |                        |            |              |
+---------------------------------+-------------------------------+------------------------+------------+--------------+
| **Haematological**              |                               | * Swelling\            |            |              |
|                                 |                               | DVT.                   |            |              |
+---------------------------------+-------------------------------+------------------------+------------+--------------+
| **Integumentary**               |                               | * Tense compartments   |            |              |
+---------------------------------+-------------------------------+------------------------+------------+--------------+
| **Trauma**                      |                               |                        |            |              |
+---------------------------------+-------------------------------+------------------------+------------+--------------+
| **Infective**                   |                               |                        |            |              |
+---------------------------------+-------------------------------+------------------------+------------+--------------+
| **Malignant**                   |                               |                        |            |              |
+---------------------------------+-------------------------------+------------------------+------------+--------------+
| **Toxic**                       |                               |                        |            |              |
+---------------------------------+-------------------------------+------------------------+------------+--------------+
| **Immune**                      |                               |                        |            |              |
+---------------------------------+-------------------------------+------------------------+------------+--------------+
| **Congenital**                  |                               |                        |            |              |
+---------------------------------+-------------------------------+------------------------+------------+--------------+
| **Obstetric**                   |                               |                        |            |              |
+---------------------------------+-------------------------------+------------------------+------------+--------------+


---

## References

1. Foot C, Steel L, Vidhani K, Lister B, MacPartlin M, Blackwell N. Examination Intensive Care Medicine. Elsevier Australia; 2011. (Examination series).
