# Surroundings

The ICU environment provides several clues to diagnosis and severity. Considerations include:

* **Environment**
	* Isolation room
		* Positive pressure
		* Negative pressure
	* Infection control and PPE
	* Waste disposal
		* Cytotoxic
	* Room temperature\
	Burns.
	* Medications
		* Antibiotics\
		Implications for causative organism or resistance patterns. 
		* Pathognomonic medications
	* Long-stay
		* Photographs/art
		* Physical therapy equipment
		* Activity plans
	* Equipment
		* Wheelchair
		* Walking aids
		* Handweights
		* Splints
		* Cooling blanket


:::column-margin
Information from the monitor, ventilator, and medications should be integrated.\
\
e.g. "The SpO~2~ is 93% with an FiO~2~ of 50% - there is evidence of a raised A-a gradient".\
\
Or, "The patient is in AF, I note the heparin infusion and wonder if this is the sole indication for anticoagulation."
:::

* **Monitor**
	* ECG\
	Rate and rhythm.
	* Haemodynamics\
	Aligned to haemodynamic supports.
	* EtCO~2~
		* Level
		* Trace
		* PaCO~2~ gradient and dead space
	* Temperature
	* ICP\
	If transduced from EVD, ensure 


* **Ventilator**
	* Mode
	* Oxygenation
		* FiO~2~
		* PEEP
		* Quick assessment of A-a gradient based on SpO~2~ and FiO~2~
	* Ventilation
		* Minute ventilation
		* Dynamic compliance
		* Consider assessing plateau pressure if evidence of reduced compliance.
	* Disease-specific ventilation strategies
	* "Extubatable settings?"
	* Airway suction


* Fluids and **infusions**
	* Vasoactives
	* Heparin
	* Pathognomonic drugs
		* Octreotide/terlipressin
		* Hypertonic saline
		* Hypertonic dextrose
		* Nimodipine
		* Mannitol
		* IVIG
	* TPN
	* Blood


* **Ancillary** equipment
	* CRRT\
		* Mode
		* Dialysate/buffer
		* Dose
		* Anticoagulation
	* Active cooling
	* IABP


* **Bed**
	* Drains
		* Type
		* Location
		* Swinging/bubbling\
		If pleural.
		* Output
	* IDC
		* Urine colour
			* Drugs
			* Myoglobinuria
	* Faecal management system

---

## References

1. Foot C, Steel L, Vidhani K, Lister B, MacPartlin M, Blackwell N. Examination Intensive Care Medicine. Elsevier Australia; 2011. (Examination series).
