# Neurological Examination

The neurological exam comes in an escalating level of detail, depending on the level of consciousness of the patient:

:::column-margin
Testing and diagnosis of brain death is covered under @sec-braindeath.
:::

* **Paralysed**
    * Pupils
* **Unconscious**
    * Pupils
    * Respiratory pattern
    * Limited cranial nerves
    * Limited peripheral motor
* **Uncooperative**
    * Variable
* **Cooperative**
    * Cerebellar exam
    * Detailed cranial nerves
    * Detailed peripheral motor
    * Detailed peripheral sensory


## Assessing Level of Consciousness

:::info
* A rigorous approach improves reproducibility and reliability
* GCS score is the sum of the **best** result in any limb
:::

In a patient with an unclear level of consciousness:

:::column-margin
Vertical eye movements (but not always lateral) are preserved in locked-in syndrome.\
:::

:::column-margin
Avoid asking the patient to squeeze hands - this may be a grasp reflex.\
:::

:::column-margin
Report the GCS in its constituent components, e.g. E~2~V~T~M~3~.
:::

* Ask to blink and to look up/down\
This assesses for locked-in syndrome.
* Ask for an *unambiguous action* (e.g. thumbs up, wiggle toes) to assess hands and feet
* Perform a painful stimulus\
*Only* after a patient has failed to respond to a command.
    * Centrally first\
    Supraorbital pressure, jaw thrust. Allows assessment for localisation.
    * Peripherally if no central response


{{< include /includes/gcs.qmd >}}

## Pupils

Bedside assessment:

* **Size**\
Normal is 2-5mm. Pupil size suggests aetiology of the lesion:
    * Small\
        * Drugs\
        Opioids and clonidine.
        * Pontine lesions
    * Semi-dilated and unresponsive\
    Midbrain lesions.
    * Large and unresponsive\
    CNIII compression.
* **Asymmetry**
    * Large and unresponsive\
        * Ipsilateral CN III lesion
        * Adie's Pupil\
        Idiopathic syndrome of mydriasis and delayed response to light; may occur in one or both pupils.
* **Reactivity**
    * Afferent pathway via CN II
    * Efferent pathway via CN III
    * Abnormalities between direct and consensual reflexes allow localisation of the lesion to a particular neural pathway


Detailed assessment:

* **Papilloedema**\
Presence suggests ↑ ICP, though this may not be present (especially acutely).


## Respiratory Patterns

+-------------------------------------+-------------------------------------------------------------------------------------+-----------------------------------------------------------------+-----------------------------------+
| Pattern                             | Presentation                                                                        | Mechanism                                                       | Causes                            |
+=====================================+=====================================================================================+=================================================================+===================================+
| Apneustic breathing                 | Deep inspiration with a **pause** at end-inspiration, followed by brief expiration. |                                                                 |                                   |
+-------------------------------------+-------------------------------------------------------------------------------------+-----------------------------------------------------------------+-----------------------------------+
| Central Neurogenic Hyperventilation | Primary respiratory alkalosis (hyperventilation)                                    |                                                                 | * Pontine lesion                  |
|                                     |                                                                                     |                                                                 | * Midbrain lesion                 |
|                                     |                                                                                     |                                                                 | * Bihemispheric lesion            |
+-------------------------------------+-------------------------------------------------------------------------------------+-----------------------------------------------------------------+-----------------------------------+
| Cheyne-Stokes                       | Sinusoidal pattern of:                                                              | Delayed feedback between CO~2~ detector and effector responses. | * Low CO                          |
|                                     |                                                                                     |                                                                 | * Metabolic encephalopathies      |
|                                     | - Rapidly ↑ depth and frequency of breathing                                        |                                                                 | * Bilateral thalamic injuries     |
|                                     | - Rapidly ↓ depth and frequency                                                     |                                                                 | * Bilateral forebrain dysfunction |
|                                     |                                                                                     |                                                                 | * Acute CVA                       |
+-------------------------------------+-------------------------------------------------------------------------------------+-----------------------------------------------------------------+-----------------------------------+

:::column-margin
Assessing respiratory pattern in the intubated patient requires some desedation and a pressure-support mode.
:::
 
## Cranial Nerve Examination

### Unconscious Patient

* **Ocular deviation**\
    * Dysconjugate gaze is present in most patients with altered conscious state, such as anaesthesia
    * Tonic deviation may be present with an **ipsilateral frontal** lobe lesion or a **contralateral pontine** lesion\
    Supranuclear (e.g. frontal) lobe lesions can be overcome by a oculocephalic or oculovestibular reflex, pontine lesions cannot.
    * Vertical (skew) deviation suggests a pontine or vestibulocerebellar lesion.\
\
* **Corneal reflex**\
Tests V~1~, III (eye movement) and VII (blink).
    * Wisp of cotton of gauze should be applied to the *cornea*
        * *Not* the conjunctiva\
        * Saline (more gentle) can be used as but administration should be precise enough to strike the cornea
        * Patient should not see the or hear the stimulus, otherwise this will not isolate V~1~.
    * Reflex is present if they blink or look upwards\
\
* **Occulo-cephalic reflex**\
A milder version of the cold caloric reflex that can be performed in unconscious patients. Tests CN III, VI, VIII.
    * The eyes are held open and the head is rotated side-to-side or up-and-down
    * The reflex is present if the eyes move in the opposite direction of head movements (**doll's eyes**)
    * **Absence** of the reflex is suggestive of brainstem dysfunction in the comatose patient\
\
* **Facial Sensation**
    * Supra orbital notch pressure\
    Tests CN V, VII.\
\
* **Gag reflex**\
Tests CN IX, X.
    * Touch the posterior pharynx on each side (use a Yankauer)
    * Absence is an unreliable predictor of risk of aspiration
    * A positive response is retching (gag reflex) or constriction of the pharynx (palatal reflex) with elevation of the uvula
\
* **Cough reflex**\
Tests CN X.
    * Suctioning the trachea should cause a cough response

:::column-margin
Ensure the cervical spine is cleared before testing the oculocephalic reflex.
:::

* **Cold caloric reflex**\
Tests CN III, VI, and VIII.
    * Predominantly **used only** in **brain-death testing**
    * Cold water is syringed into the patients ear
    * A positive reflex occurs when the eyes look towards the tested side\
    Eyes will remain in this position until irrigation stops.
    * No response will occur in brain death
    * 5 minutes should elapse before testing the other wide


### Cooperative Patient

* **Visual acuity**\
Tests CN II
    * Visual fields
        * Patient focuses straight ahead
        * Reports when a finger is moving in each quadrant
    * Visual extinction
        * Form of neglect
        * Patient is presented with a different number of fingers on each side
        * The patient will not report seeing the fingers on the affected side when presented to both sides, but can see them when presented to the affected side alone\
\
* **Extra-ocular movements**\
Tests CN III, IV, VI
    * Patient focuses straight ahead
    * Eyes follow finger in an 'H' pattern
    * Diplopia:
        * Movement limitation
        * Dysconjugate gaze:
        * Horizontal
        * Vertical\
\
* **Facial Sensation**
    * Trigeminal sensation\
    Tests CN V~1~, V~2~, V~3~.\
\
* **Facial Expression**\
Tests CN VII.
    * Evaluate strength and asymmetry as the patient:
        * Wrinkles brow
        * Closes eyes tightly
        * Puffs out cheeks
        * Smiles\
\
* **SCM and trapezius**\
Tests CN XI.
    * Evaluate strength as the patient:
        * Shrugs shoulders
        * Turns head to each side\
\
* **Tongue**\
Tests CN XII.
    * Atrophy\
    Occurs with LMN lesion.
    * Fasciculations\
    Occurs with LMN lesions.
    * Deviation\
    Weakness causes deviation to the affected side.
    * Push forcefully against inside of the cheek


## Peripheral Motor Exam

:::info
* Asymmetry in tone, reflexes, and plantar responses are useful to lateralise a lesion
* Symmetrical changes are rarely helpful in the unconscious patient
:::

:::column-margin
A lesion **above** the **brainstem** is suggested by **decorticate** posturing:

* Flexion of arms
* Adduction of shoulder
* Extension of legs
:::

:::column-margin
A lesion **below or at** the **brainstem** is suggested by **decerebrate** posturing:

* Extension of arms
* Internal rotation of shoulder
:::

:::column-margin
: Upper versus Lower Motor Neuron Lesions

| Finding        | UMN | LMN |
|----------------|-----|-----|
| Atrophy        | No  | Yes |
| Fasciculations | No  | Yes |
| Reflexes       | ↑   | ↓   |
| Tone           | ↑   | ↓   |
| Weakness       | Yes | Yes |
:::

**Observation**:

* Spontaneous or localising movements\
* Posturing
    * Abnormal flexion (decorticate posturing)\
    * Abnormal extension (decerebrate posturing)\
* Tremors\
Should be no tremors at rest in normal individuals.
* Wasting
    * Normal muscle bulk for age
    * Symmetry of muscle bulk
* Fasciculations\
    * Intrinsic hand muscles
    * Shoulder girdle
    * Thigh


**Tone**:

* Passive movement of:
    * Upper limb
        * Shoulder\
        Circumduction.
        * Elbow
            * Flexion/extension
            * Pronation/supination
        * Wrist\
        Circumduction.
* Joint should be able to be moved easily through its range of motion.
    * Spasticity\
    Velocity-dependent, i.e. ↑ in tone is proportional to the rate of movement. Associated with UMN lesion.
    * Rigidity\
    Velocity-independent, i.e. tone is ↑ irrespective of how quickly the joint is moved. May be:
        * Cogwheel\
        Hypertonia with superimposed tremor, such that tone intermittently ↑ during movement.
        * "Lead-pipe"\
        Uniform ↑ in tone throughout.
    * Flaccidness\
    Complete absence of tone, occurring when the muscle has no LMN innervation.


**Power**:

* Strength of major muscle groups
* Joints should be stabilised and isolated so each is tested individually
* Assessment must consider the age, sex, fitness, and non-neurological disease state.

:::column-margin
{{< include /includes/motor_function.qmd >}}
:::


**Reflexes**:

:::column-margin
The **deep tendon reflexes** are:

* Upper limb
    * Biceps
    * Brachioradialis
    * Triceps
* Lower limb
    * Patella
    * Ankle
:::

* Look for muscle contraction rather than physical movement
* Clonus\
\>5 sustained involuntary contractions following stretching of a muscle.
* Plantar response\
Sensitive test for the presence of an UMN lesion in the corticospinal tract.
    * Lateral side of foot is rubbed with a blunt instrument
    * Flexion of the toes is a normal (negative) response
    * Extension of the hallux with fanning of the toes is a positive Babinski sign\
    Present as a primitive reflex in infants up to 12 months of age.
* Hoffman Reflex\
Sensitive test for UMN lesion in the cervical spine.
    * DIP joint of the 3^rd^ digit is stabilised and the fingertip is flicked
    * Opposition of the thumb and forefinger is a positive response
    

## Peripheral Sensory Exam

Testing of each main afferent pathway:

* Spinothalamic tracts\
Pain, temperature, crude touch.
* Dorsal columns\
Proprioception, vibration, light touch. 


Assessment process:

* Sharp and light touch
    * Demonstrate to the patient what light and sharp touch will feel like
    * Start distally and move proximally, crossing multiple dermatomes at each point
* Proprioception 
    * Have the patient close their eyes
    * Grasp either side of the great toe IP joint
    * Orientate the patient to what up and down will be
    * Then move the toe and ask the patient to state in which direction it has been moved
        * If incorrect, then move to a more proximal joint\
        Distal joints are typically affected first.
* Vibration
    * Use a 128Hz tuning fork
    * Place the fork over the great toe IP joint
    * The patient should be able to identify when vibration occurs, and when vibration ceases
* Two-point discrimination\
Useful for peripheral neuropathy.
    * Patient should be able to distinguish simultaneous touch from two objects >5mm apart


## Cerebellar Exam

* Nystagmus
    * A fast phase of nystagmus will occur towards the side of a cerebellar lesion
* Staccato speech
* Resting tremor
    * Head\
    Known as titubation.
    * Upper limb
* Tests of coordination:
    * Rapid alternating movements
    * Finger-nose
    * Heel-shin
* Gait
* Romberg's test
    * Patient stands with eyes closed
    * A positive result occurs if the patient loses balance
        * Cerebellar ataxia occurs even when the eyes are open
        * Sensory ataxia occurs when the eyes are closed, and is a sign of disturbed proprioception

---

## References

1. Walker MC, O’Brien MD. [Neurological examination of the unconscious patient](https://www.gla.ac.uk/media/media_117701_en.pdf). J R Soc Med. 1999 Jul;92(7):353-5.
2. Smith, Eimear, and Mark Delargy. ‘Locked-in Syndrome’. BMJ: British Medical Journal 330, no. 7488 (19 February 2005): 406–9.
